### ISSUE TITLE
Social Media Footer auf Startseite

### ISSUE THREAD

**Issue by uliried** [RRZE-Webteam/FAU-Einrichtungen#1]
Als Startseite wurde eine statische Seite definiert. In den Theme Options ist bei "Social Media Footer anzeigen" "Startseite" ausgewählt. Der Footer erscheint nicht auf der Startseite. 
Wählt man bei den Anzeigeoptionen "Standard Seiten" erscheint der Social Media Footer auf der Startseite, aber eben auch auf allen anderen Seiten, was nicht erwünscht ist.
Wählt man als Startseite die letzten Beiträge und bei den Anzeigeoptionen für den Social Media Footer wieder "Startseite", erscheint der Footer auch nicht.

**Comment by xwolfde** [comment]
Das ist schon richtig so. Allerdings gibt es hier eine Begriffsverwirrung:
Mit "Startseite" ist das *Template* "Startseite" gewählt, nicht Seiten vom Template Typ "Standard" oder andere, die als statische Seite der ersten Seite des Webauftritts zugeordnet wurden.

**Comment by uliried** [comment]
Einspruch - die Startseite verwendet auch das Template Startseite und trotzdem ist der Footer nicht zu sehen. Verwende ich das Template Startseite Fakultät, ist der Footer da.

**Comment by AstridSemm** [comment]
Hm.... Da hätte ich gerne mal einen Link und - wenn möglich - Zugriff aufs Backend. Wahlweise auch screenshots. Ginge das?

**Comment by xwolfde** [comment]
Ok, da scheint noch die Zuordnung der Templatebezeichnungen falsch zu sein. Template Startseite != Template Startseite Fakultät. In den Options ist mit "Startseite" aber Template "Startseite Fakultät" gemeint und nicht Temnplate "Startseite".
Das Unter den "Einstellungen" auch der Begriff "Startseite" verwendet wird, als die Seite die als Frontpage erscheint, kann nicht geändert werden.

**Comment by xwolfde** [comment]
In der nächsten verison gefixt
