### ISSUE TITLE
Portalseiten: flyout: Navi ohne Thumbnail erzwingen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#10]
Feature Request:  Das Bild oben soll abgeschaltet werden können ohne es als Thumbnail zu entfernen.

**Comment by xwolfde** [comment]
In der nächsten version umgesetzt.

Ausserdem wurde testweise die Size der Thumbnail vom Standard Post verwendet. Wenn das ankommt, kann n Zukunft ein Bild gespart werden.

**Comment by steffigebel** [comment]
Das zweite mit dem "Bild sparen" verstehe ich nicht. Bitte einmal erklären. Danke ;-)
________________________________
Von: Wolfgang Wiese [notifications@github.com]
Gesendet: Donnerstag, 25. Februar 2016 17:13
An: RRZE-Webteam/FAU-Einrichtungen
Betreff: Re: [FAU-Einrichtungen] Portalseiten: flyout: Navi ohne Thumbnail erzwingen (#10)


Closed #10<https://github.com/RRZE-Webteam/FAU-Einrichtungen/issues/10>.

**Comment by xwolfde** [comment]
Beim den Bilder die oben erscheinen wird ein Standardformat verwendet und nicht mehr ein eigenes Bildformat, welches nur zu diesem einen Zweck existiert und erstellt werden musste.

**Comment by steffigebel** [comment]
war das so? Ich dachte eher, es wäre die Größe, die unten im Portalmenü dann auch verwendet wird. Dass man dafür noch ein zweites Bild einstellen kann, ist mir neu, falls es überhaupt so ist?! Oder ich habs noch nicht verstanden.
--
Steffi Gebel
Webmanagement
Regionales RechenZentrum Erlangen (RRZE)
Friedrich-Alexander-Universität Erlangen-Nürnberg
Martensstrasse 1, 91058 Erlangen, Germany
Tel. +49 9131 85-27807
stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de>
www.rrze.fau.de

Von: Wolfgang Wiese <notifications@github.com<mailto:notifications@github.com>>
Antworten an: RRZE-Webteam/FAU-Einrichtungen <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Freitag, 26. Februar 2016 10:32
An: RRZE-Webteam/FAU-Einrichtungen <FAU-Einrichtungen@noreply.github.com<mailto:FAU-Einrichtungen@noreply.github.com>>
Cc: "Gebel, Stefanie" <stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de>>
Betreff: Re: [FAU-Einrichtungen] Portalseiten: flyout: Navi ohne Thumbnail erzwingen (#10)


Beim den Bilder die oben erscheinen wird ein Standardformat verwendet und nicht mehr ein eigenes Bildformat, welches nur zu diesem einen Zweck existiert und erstellt werden musste.

**Comment by xwolfde** [comment]
Beim Hochladen eines jeden Bildes werden automatisch 12 verschiedene Einzelbilder mit eigenen AUflösungen erstellt. Das Bild oben ist eines davon.
