### ISSUE TITLE
Portalmenüs - Die verbotene Einstellungskombination

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1001]
Die Darstellung der Portalmenüs könnte noch weiter optimiert werden. Zwei Punkte:

- [ ] Lange Titel sorgen dafür, dass ein unschöner Rahmen entsteht
- [x] Die verbotene Einstellung: Eine Kombination von "Beitragsbilder verbergen" und "Unterpunkte verbergen" sorgt für ein zerschossenes Portalmenü.
<img width="1502" alt="Bildschirmfoto 2022-01-25 um 10 30 03" src="https://user-images.githubusercontent.com/58593037/150950209-4f207363-ef2e-4f98-b44c-d4f19baeeada.png">
<img width="1502" alt="Bildschirmfoto 2022-01-25 um 10 30 25" src="https://user-images.githubusercontent.com/58593037/150950219-8156621c-4c9d-438b-9973-a9ae70a3ff01.png">

Getestet in Safari auf:
https://www.wordpress.rrze.fau.de/plugins/

**Comment by cassandre** [comment]
Verbotene Einstellung ist jetzt erlaubt. :-)
Zu Punkt 2 gibt es keine optimale Lösung: 
- align-items:flex-start passt die Box der notwendigen Höhe an -> der graue Überstand fällt weg, aber alle Boxen sind unterschiedlich groß.
- eine begrenzende Linie um die gesamte Box sieht bei den angeschrägten Bilder doof aus.
