### ISSUE TITLE
Interessantes Verhalten beim markieren von Text auf Inhaltsseite mit Navi

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1003]
Wenn man aus Versehen die Navigationsleiste links mit markiert (Safari), dann verschwindet der erste Paragraph.

Vermutlich kein richtiger Bug, aber interessant. 🪄🤹
<img width="1611" alt="Bildschirmfoto 2022-01-26 um 07 52 53" src="https://user-images.githubusercontent.com/58593037/151117257-139cec5d-9a90-41e3-b590-e41edf9ecf4b.png">
<img width="1611" alt="Bildschirmfoto 2022-01-26 um 07 52 59" src="https://user-images.githubusercontent.com/58593037/151117280-907b2b18-a079-4656-bbdc-b1433e97ba6a.png">

**Comment by xwolfde** [comment]
Safari... Ich glaub für den Browser sollten wir noch irgendwann eine eigene Kategorie einführen.

**Comment by xwolfde** [comment]
Ich kann das Problem bestätigen mit Safari auf Mac.
Aber eine Lösung und eine Ursache in der Semantik des Themes sehe ich nicht...
