### ISSUE TITLE
Portalmenü: Rahmen innen bei Portaltop?

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#1004]
Hier erscheint innen im Portaltop ein Rahmen. Der Portaltop ist da nicht 100%.

![grafik](https://user-images.githubusercontent.com/1070669/151123842-27ee8afa-309a-4354-8931-d53821ef2080.png)

URL: https://www.intern.fau.de/informationstechnik-it/

**Comment by wrcg** [comment]
auch dieser Shortcode passt noch nicht:
[portalmenu menu="IT" showsubs="false" type="2" skewed="1"]
<img width="579" alt="image" src="https://user-images.githubusercontent.com/9526974/151125086-c096f1a3-2422-49c2-bbf2-60794e8b9f09.png">
evtl. reicht hier schon das:
.no-sub .subpages-menu li .portaltop {
+ left: 0;
}
