### ISSUE TITLE
Bildfarben variieren je nach Browser-Fenstergröße

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Einrichtungen#1005]
Farben der Bilds in der Bühne variieren je nach Fenstergröße.
Volle Größe, recht blasses Blau:
 
![image](https://user-images.githubusercontent.com/9526974/151130301-33b37801-6fb4-4f58-87a5-9ff643b49046.png)

Irgendeine eine kleinere Größe, fast neonblau:
![image](https://user-images.githubusercontent.com/9526974/151130309-27b8e9ca-db57-4b7c-b5de-1121a2e055a3.png)

**Comment by wrcg** [comment]
dieser Browser wurde verwendet: ![grafik](https://user-images.githubusercontent.com/9526974/151158574-78f45c5d-1243-4559-b8bb-a84abe2f684b.png)

**Comment by xwolfde** [comment]
Ich hab mal geschaut, das liegt nicht am Theme, sondern am Bild: Es wird in verschiedenen Auflösungen vorgehalten:

`/files/2020/08/banner_fauintern_web_lay5_schloss.jpg 1260w, /files/2020/08/banner_fauintern_web_lay5_schloss-300x43.jpg 300w, /files/2020/08/banner_fauintern_web_lay5_schloss-1024x148.jpg 1024w, /files/2020/08/banner_fauintern_web_lay5_schloss-768x111.jpg 768w, /files/2020/08/banner_fauintern_web_lay5_schloss-480x69.jpg 480w, /files/2020/08/banner_fauintern_web_lay5_schloss-940x136.jpg 940w`

Je nach Auflösung entscheidet der Browser, welches er läd und anzeigt.

Und wenn du schaust:
https://www.intern.fau.de/files/2020/08/banner_fauintern_web_lay5_schloss-1260x182.jpg
vs
https://www.intern.fau.de/files/2020/08/banner_fauintern_web_lay5_schloss.jpg
siehst du, dass es am Bild liegt.

Irgendwie scheint hinter bei der Konvertierung des Bildes in den kleinen Format Information verloren gegangen zu sein.
War das Bild an sich selbst vielleicht schon zu klein und vorab komprimiert worden?

**Comment by wrcg** [comment]
danke, mit Bildtausch ist das Problem behoben :-)
