### ISSUE TITLE
Portalmenü Darstellung auf Startseiten ( Portalmenü oben ) und Portalmenü-Shortcode

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1006]
# Für die Startseite Fakultät  gibt es den Wunsch, dass

- [x] Der Text auch als Overlay im Bild dargestellt werden kann. 
- [x] Der Text optional in Versalien (Großbuchstaben) ausgegeben werden kann.

<img width="1154" alt="Bildschirmfoto 2022-01-26 um 09 40 19" src="https://user-images.githubusercontent.com/58593037/151130379-e2038479-2be0-4b7f-93a7-8fa22df987c4.png">

# Für die Nutzung der Portalmenü Shortcodes gibt es den Wunsch, dass

- [x] Die Portalmenüdarstellung für [portalmenu menu="Portal Grundlagen 22" showsubs="false"] und [portalmenu menu="Portal Grundlagen 22" showsubs="false" nothumbs="true"] ebenfalls funktionieren, da die Shortcodes auf zahlreichen Seiten im Einsatz sind.
- [x] Die Portalmenüs auch bei Verwendung des Portalmenü-Shortcodes die ganze Seitenbreite einnehmen wie bei Portalmenü oben. 

<img width="1571" alt="Bildschirmfoto 2022-01-26 um 09 45 05" src="https://user-images.githubusercontent.com/58593037/151131050-b50ef6ab-cf11-4f39-af24-3509f9764003.png">
https://www.wordpress.rrze.fau.de/themes/fau-einrichtungen/shortcodes/portalmenus/beispiel-portalmenu-auf-dem-standardtemplate/

**Comment by xwolfde** [comment]
Wegen Wunsch: Die Portalmenüs nehmen *immer* die verfügbare Breite ein, die der Content hat.
Aber die Menüs können nicht hexen. Wenn es eine Sidebar rechts gibt oder ein Menu links, dann ist der Platz eben nicht verfügbar.
Es geht nicht.

**Comment by cassandre** [comment]
> Wegen Wunsch: Die Portalmenüs nehmen _immer_ die verfügbare Breite ein, die der Content hat.
> Aber die Menüs können nicht hexen. Wenn es eine Sidebar rechts gibt oder ein Menu links, dann ist der Platz eben nicht verfügbar.
> Es geht nicht.

Ich denke, dabei geht es um den überflüssigen margin- und padding-right bei Portalseiten. Dadurch ist das Shortcode-Portalmenü schmaler als das über die Seiteneinstellungen erstellte.
![Bildschirmfoto 2022-01-26 um 12 20 10](https://user-images.githubusercontent.com/4435815/151322555-1c49fe3b-e63f-4dca-9c51-48bc9a2e908d.png)

**Comment by cassandre** [comment]
Wegen Text in Versalien: Da es sich um ein manuell angelegtes Menü handelt, kann der Text dort direkt in Versalien eingegeben werden.
