### ISSUE TITLE
Balken bei Widget/Sidebar: prüfen ob noch gewünscht

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#1012]

**Comment by xwolfde** [comment]
Der Balken befindet sich auf den Templates, in denen eine Sidebar rechts ist, die aber keine Startseite

Portalseite:
![grafik](https://user-images.githubusercontent.com/1070669/151522587-7f2a09a7-2425-49d8-838d-5f5bc043e094.png)


Normale Seite mit Sidebar
![grafik](https://user-images.githubusercontent.com/1070669/151522668-36375ee4-b667-4bb1-83ed-c7c63619b5a5.png)

**Comment by cassandre** [comment]
in 58b261ad960f20a1d84fb13cc518cbf019ecfcaf erledigt
