### ISSUE TITLE
Individuelle Fallback-Bilder haben blaugrauen Rand

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1013]
Wenn man im Customizer ein individuelles Fallback-Bild für die Blogroll festlegt, so hat dieses Bild einen dicken Rand.
s. https://www.urlaubaufsagrotan.test.rrze.fau.de

(Safari)
<img width="653" alt="Bildschirmfoto 2022-01-27 um 14 44 55" src="https://user-images.githubusercontent.com/58593037/151370967-3b4d162e-f687-4d7d-a422-509cd4516870.png">

**Comment by xwolfde** [comment]
fixed im update
