### ISSUE TITLE
SVG's die eine Beschriftung haben, werden nicht angezeigt

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1015]
SVG-Dateien, die eine Beschriftung/Beschreibung in der Mediathek gesetzt haben, werden anscheinend nicht angezeigt.
<img width="1059" alt="Bildschirmfoto 2022-01-28 um 10 51 56" src="https://user-images.githubusercontent.com/58593037/151525514-76f09b69-af86-4391-ad7b-ef3d6319ff26.png">

(Aufgefallen in Safari)

https://www.urlaubaufsagrotan.test.rrze.fau.de/2022/01/27/beispieleintrag/

**Comment by lukasniebler** [comment]
https://www.beta.wordpress.rrze.fau.de/ein-weiterer-testfall/

**Comment by xwolfde** [comment]
Das width: auto;  bei figure > img funkt da rein. Das kann da raus.

Außerdem, wenn schon dabei:
main figure.aligncenter, aside figure.aligncenter, .portalpage-sidebar figure.aligncenter, .widget figure.aligncenter {}

braucht ein
  margin: 0 auto;
