### ISSUE TITLE
Seitenreihenfolge im Baum (Gewichtung)

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Einrichtungen#102]
Hallo,

wie besprochen hier die Überführung des Issue https://github.com/RRZE-Webteam/FAU-Theme/issues/265 an diese Stelle.

Ich bin nicht ganz sicher, wie ich das hier formulieren soll. Wir haben vor längerer Zeit mal besprochen, dass nicht ganz klar ist, wie die Seitenreihenfolge funktioniert. Wir hatten, glaube ich, nach einer komfortableren Möglichkeit gesucht (aufgeschoben mangels Kapazität) und hatten das Problem, dass die Reihenfolge sich willkürlich änderte (wohl ein Speicherproblem, tritt derzeit nicht auf).

Aktuell scheint etwas Verwirrung zu herschen.  Was wir tun und immer benötigen, ist das manuelle Bestimmen der Reihenfolge von Seiten im Seitenbaum - z.B. für automatisch erzeugte Menüs:

Siehe https://cloud.githubusercontent.com/assets/9445370/7700437/fef6d004-fe1e-11e4-8107-7822b9166f3a.PNG

Dafür nehmen wir aktuell die umständliche out-of-the-box-Lösung von Wordpress: https://wp-bistro.de/reihenfolge-von-seiten-im-navigationsmenu-andern-ein-individuelles-menu-erstellen/

Die ist auch Teil des Einrichtungs-Themes, jeder kann die benutzen, denke ich. Ob im Einrichtungs-Theme die linke Navigation (Subnavi) anders erzeugt wird als im FAU-Theme, weiß ich allerdings nicht - das wäre eine Rückfrage an euch. 

Was genau gibt es für euch zu klären?

Wir könnten uns das immer noch komfortabler vorstellen, aber das hat aktuell keine Prio, weil es nicht trivial sein dürfte. Einzig damals im Plugin für die visuelle Baumdarstellung mit Javascript ging es ganz gut, aber das ist längst deaktiviert aus guten Gründen.

**Comment by xwolfde** [comment]
"Was genau gibt es für euch zu klären?"

Naja, ein konkreter Vorschlag, wie man es in der Bedienung umsetzen soll, wäre gut :) 
Im Prinzip schreibst du, dass du es einfacher haben willst, aber was ist das? Wie soll das aussehen?


Eigentlich müsste man die Reihenfolge wahrscheinlich im Moment der Bearbeitunbg einer Seite festlegen können. Quasi das in den Optionen irgendwi eine Reihemnfolge auftaucht mit Pfeilen hoch und runter, bei der man die anderen existierenden Seiten sehen könnte...

Weißt du wie aufwendig sowas nicht nur in der ENtwicklung, sondern auch darin bestände das zu speichern? Eigentlich wird damit ja nur ein neues Menu gespeichert. 
Daher mein damaliger Vorschlag nochmal: Man könnte ja optional angeben: Zeige bei der Subnav nicht die automatische Seitenhierarchie, sondern ein definierten Menu, welches man sich zuvor zusammengebaut hat.

**Comment by wrkb** [comment]
Weil es so aufwändig ist, haben wir das aktuell auf keiner Liste, es gibt nichts zu tun, wenn wir das nicht als ToDo aufnehmen. Wir haben aber sehr viel Dringenderes in der gemeinsamen Liste :)

Wenn die Verbesserung allerdings auch für andere Klienten relevant und wichtig ist, dann können wir Verbesserungen sammeln.
Es stimmt, es müsste entweder 1) eine komfortable Möglichkeit an der Seite direkt beim Bearbeiten geben oder, 2) wie bei anderen Systemen, eine Liste der Seiten auf der gleichen (Menü-)Ebene, mit der Möglichkeit, diese zu gewichten.

Für 1) wäre vielleicht Metabox denkbar, in der man per JS die Seite in einer Liste verschiebt? Definierte Menüs gingen in die Hunderte, wenn ich das richtig verstehe, aber die Lösung ist mir noch nicht ganz klar. Aufwand klingt hoch, ja.

Für 2) hatte (hat noch?) Joomla die Pfeil-Lösung, Drupal hat Dropdowns mit Zahlen an der Liste der Seiten.  Bei Wordpress kann man in der Seitenliste auf Quickedit gehen und kann so nur jeweils die Gewichtung einer Seite sehen. Geht schon, man muss sich nur ein paar Zahlen merken :) In Wordpress hakt es also vor allem einer übersichtlichen Liste der Seite (die Hierarchie ist schwer erkennbar) und man kann die Gewichtung nicht ein einem Rutsch für alle einstellen und speichern. 

Wir vergeben die Gewichtung übrigens immer in 10er Schritten, um unkompliziert Seiten zwischen andere einfügen zu können.

Soviel als schneller Input, mehr Ideen wohl besser dann, wenn das Thema tatsächlich für weitere Klienten interessant ist.

**Comment by xwolfde** [comment]
Das 
"Wenn die Verbesserung allerdings auch für andere Klienten relevant und wichtig ist"
ist ausgeschlossen. Nur ihr habt die Funktion. Die ist bei keiner anderen SIte mehr aktivierbar :)

**Comment by wrkb** [comment]
Wir missverstehen uns immer noch. Es handelt sich um eine Out-of-the-box-Funktion von Wordpress. Da wurde gar nichts gebaut oder angepasst oder entwickelt. Ich wüsste auch nicht, wie man die deaktivieren kann.

Lass uns das mal am Rechner anschauen...

**Comment by xwolfde** [comment]
Oh, wenn es out of the box ist, können wir den Code ja löschen. Danke :)

**Comment by wrkb** [comment]
Den hab ich jetzt nicht verstanden :question:

**Comment by xwolfde** [comment]
Und ich erwarte nach wie vor einen KONKRETEN UMSETZUNGSVORSCHLAG.

Bitte diesen bis Ende dieser Woche hier schriftlich liefern, ansonsten schließe ich das als Wontfix.

**Comment by wrkb** [comment]
Dann lieber Wontfix. Denn hier ist aus einer sehr alten Frage nach einer besseren Lösung und der folgenden Entscheidung, "es kann halt auch so bleiben" ein Verständnisproblem geworden, dass sich hier nunmal - auch mit Screenshots, wie bereits versucht - nicht hier lösen lässt. Und aktuell gibt es auch keine Beschwerden oder Dringlichkeiten von irgendeiner Seite, das Ticket war schlicht noch offen.

Ich schlag daher vor, das Ganze hier zu schließen und ich zeige dir am Donnerstag, was ich meine. Oder nicht - wie du magst. Dann wissen wir, ob es überhaupt etwas zu tun gibt.
