### ISSUE TITLE
Horizontaler scroll auf mobile

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1020]
Bei bestimmten bildausrichtung scheint horizontaler scroll möglich zu sein.

![image](https://user-images.githubusercontent.com/58593037/151714946-072f0fe1-d582-492a-bf28-654d647f962f.png)

https://www.wordpress.rrze.fau.de/grundlagen/inhalte-bearbeiten/bilder/

Safari mobile 

(Per Zufall darüber gestolpert)

**Comment by lukasniebler** [comment]
<img width="385" alt="Bildschirmfoto 2022-01-31 um 08 32 02" src="https://user-images.githubusercontent.com/58593037/151754659-bb83748e-9a36-4a40-9ce1-4d39c993b421.png">

**Comment by xwolfde** [comment]
sieht aus, als ob das bild, das fullscreen sein sollte, links ein margin 15 hat, der dann alles nach rechts um den betrag + 15 verschiebt.

**Comment by xwolfde** [comment]
fixed in update
