### ISSUE TITLE
Plugin Person: Sidebar: Portalseiten: Gridgap

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#1023]
Hier scheint das grid nicht richtig zu greifen:
![grafik](https://user-images.githubusercontent.com/1070669/151762332-7f28b7d5-8140-4f82-8b7f-1d7918068402.png)

URL: https://www.oer1.rw.fau.de/

**Comment by xwolfde** [comment]
Möglicherweise hängt das Problem eher an alte Bilder, die noch mit 80px hochgeladen wurden und nicht an dem Grid.

**Comment by cassandre** [comment]
Das CSS kommt aus dem Person-Plugin:
````
.fau-person.thumb-size-small {
    .row .person-thumb {
	flex-basis: 80px;
	img {
	    width: 80px;
	    height: 106px;
	    object-fit: cover;
	    max-width: inherit;
	}
    }
}
````
