### ISSUE TITLE
FAU-Person: Aussehen von Links auf Personenseiten weicht ab

### ISSUE THREAD

**Issue by MichaelEischer** [RRZE-Webteam/FAU-Einrichtungen#1028]
Mit Version 2.0 des Webseitendesigns weicht die Darstellung von Links auf Personen-Seiten von der auf anderen Seiten ab. Auf normalen Seiten sind Links immer unterstrichen und werden bei Hover per Animation hervorgehoben. Auf den Personenseiten sind Links optisch zuerst nicht von normalem Text zu unterscheiden und werden unterstrichen sobald man mit der Maus drüberfährt. Das führt zu einer optisch recht inkonsistenten Darstellung.

Beispiele:
- Personenseite: https://www.beta.wordpress.rrze.fau.de/person/martin-mustermann/#collapse_0
- Normale Seite: https://www.beta.wordpress.rrze.fau.de/2020/04/29/update-fau-person-3-0/

**Comment by xwolfde** [comment]
Ja, bekannt, wurde bewusst (nach Tests) entschieden, dass LInks in den Metadaten der Person nicht m Contentstyle für Links erscheinen sollen

@lukasniebler Etwas für die FAQ?

**Comment by MichaelEischer** [comment]
Ist das auch für den Inhalt der Accordions auf der Personenseite so beabsichtigt (im oberen Link bspw. das "Lehrveranstaltungen aus UnivIS"-Accordion)? In denen sehen die Links auch anders aus als auf Content-Seiten.

**Comment by xwolfde** [comment]
Ja, die "Styled Links" sollen prinzipiell nur für Textcontent aus dem Editor, aber nicht für dynamischen Content aus Drittquellen zum Einsatz kommen.

**Comment by MichaelEischer** [comment]
Der Erklärung zu Folge sollte doch, wenn ich auf einer Personen-Seite folgendes einfüge, ein "Styled Link" rauskommen? Es wird aber nur ein nicht unterstrichener Link wie in den Personenmetadaten daraus. Oder zählt händisch eingefügter Text auf den Personenseiten nicht als Textcontent?
```
<a href="https://www.beta.wordpress.rrze.fau.de">Test-Link</a>
```

Auf der Beispielpersonenseite gibt es ein ähnliches Beispiel. Unter https://www.beta.wordpress.rrze.fau.de/person/martin-mustermann/#collapse_1 sieht der Link mit der Aufschrift "Regionales Rechenzentrum Erlangen (RRZE)" (die Überschrift im Screenshot) stark nach Textcontent aus dem Editor aus, der Link ist aber nicht irgendwie hervorgehoben und daher nicht wirklich erkennbar. 

![Screenshot 2022-02-07 at 18-21-05 Martin Mustermann](https://user-images.githubusercontent.com/9106997/152839629-30e60cfd-ca54-44ab-b3ec-7f43b88b8bb2.png)

**Comment by lukasniebler** [comment]
🎫 http://go.fau.de/9sat | Interaktive Elemente auf Personenseiten in z.B. Akkordeonfächern über die Vita / Lebenslauf und Co. sind nicht als Links erkennbar.

Beispiel: https://www.pol.phil.fau.de/person/katrin-kinzelbach/#collapse_2
Man weiß als Nutzer nicht, welche Publikationen oder Vorträge Links sind und somit interaktive Elemente.

**Comment by xwolfde** [comment]
Ok, wir sollten da nochmal in uns gehen.

Ggf. sollten wir dann es so machen, dass die Links im Personen-Container doch "stylish" sind. Mit AUsnahme von Links in `<address>`-Bereichen.
