### ISSUE TITLE
Portalmenü/Sizes-Angaben fehlen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#1029]
Bei dem Portalmenü sind alle srcset-Angaben vorhanden, die Sizes-Angaben sind jedoch nicht vollständig.
`
<img src="/files/2019/08/Hoersaal_0981_minx.jpg" alt="Zur Seite: Studieren an der FAU" srcset="/files/2019/08/Hoersaal_0981_minx.jpg 800w, /files/2019/08/Hoersaal_0981_minx-300x200.jpg 300w, /files/2019/08/Hoersaal_0981_minx-360x240.jpg 360w, /files/2019/08/Hoersaal_0981_minx-480x320.jpg 480w, /files/2019/08/Hoersaal_0981_minx-704x470.jpg 704w, /files/2019/08/Hoersaal_0981_minx-719x480.jpg 719w, /files/2019/08/Hoersaal_0981_minx-539x360.jpg 539w" sizes="(max-width: 800px) 100vw, 800px" width="800" height="534">`

**Comment by xwolfde** [comment]
srcset und sizes werden direkt aus WP generiert:
        $imgsrcset   = wp_get_attachment_image_srcset($id, $size);
        $imgsrcsizes = wp_get_attachment_image_sizes($id, $size);

Wenn weniger sizes als srcset geliefert werden, könnte es ein Problem mit dem Upload gegeben haben, der älter war und über ein Plugin statt fand?

**Comment by cassandre** [comment]
Nur wenn der Portalmenü-Typ 2 oder 3 ist, wird das Thumbnail in voller Größe angefordert (`'full'`).
Typ 1 und Default sind `'rwd-480-2-1'`.
Entsprechend werden auch die Sizes nur in dieser Größe ausgeliefert. Ich vermute mal, dass wp_get_attachment_image_srcset() für Retina-Displays trotzdem auch größere Bilder referenziert als im $size-Parameter angegeben.

**Comment by xwolfde** [comment]
ok, hat sich erledigt. ist so korrekt.
