### ISSUE TITLE
Farbcodes in Hauptmenü-Elemente

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#1031]
Es fehlen die CSS-Regeln für .textcol-white und .bgcol-rw ua. für das Hauptmenü.

**Comment by xwolfde** [comment]
ggf. wären hier die vorhandenen Button-Classes aus Elements eine Lösung. Müsste geprüft werden.

Ziel ist aber eigentlich nur, dass man eine Class für ein Menuelement angeben möchte, welches dann bewirkt, dass im Nicht-Hover-Fall die Hintergrundfarbe und die Vordergrundfarbe anfders gesetzt werden - zum Beispiel für ein Alert, oder aber auch in Fakultät-Farben (--color-$name-ci-hell  als background, --color-$name-ci-hell-kontrast als farbe).

**Comment by wrcg** [comment]
für unseren Corona-Button wäre eine schnelle Lösung mit den Farben gut :-) ich hab's jetzt als Workaround in Blau gesetzt, dass man den Button sieht.
