### ISSUE TITLE
Mouseover Effekt funktioniert nicht bei Bildern die eine Bildunterschrift enthalten (Grid-Gallery)

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1032]
- [x] Gallery Grid Darstellung: Der Mouseover Effekt (Zoom und SW-Darstellung) funktioniert nicht bei Bildern die eine Bildunterschrift enthalten.

- [ ] Gallery mit Slider: Die Vorschaubilder im Slider werden nicht zentriert dargestellt das sieht bei Gallerien die Bilder mit verschiedenen Formaten enthalten teilweise sehr unschön aus.

( 🎫 http://go.fau.de/9s-ck | Aus Helpdesk )

**Comment by xwolfde** [comment]
fixed
