### ISSUE TITLE
Hauptmenü - Sieht unschön aus

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1034]
- Das Hauptmenü wird teilweise nicht sauber dargestellt (Siehe https://www.wtm.tf.fau.de „Forschung“ ). Die mittlere Spalte ist verschoben. Dies tritt allerdings nur mit dem Safari-Browerser auf, beim Firefox ist alles in Ordnung.

<img width="2240" alt="Bildschirmfoto 2022-02-01 um 08 31 20" src="https://user-images.githubusercontent.com/58593037/151928872-b5847474-9264-4eb8-9011-091f086e3ab4.png">

( 🎫 http://go.fau.de/9s-ck | Aus Helpdesk )

**Comment by xwolfde** [comment]
Inwiefern ist da was verschoben?

**Comment by lukasniebler** [comment]
Glaube damit ist gemeint, dass Firefox die Menüpunkte anders bricht, als Safari.
Safari gefüllt zuerst die ersten beiden Spalten. Safari füllt vorne und hinten und lässt die Mitte "frei"

Firefox:
<img width="2156" alt="Bildschirmfoto 2022-02-01 um 11 58 32" src="https://user-images.githubusercontent.com/58593037/151956497-c7362e98-190e-456f-b80a-b2932ad906ed.png">

Safari:
<img width="2156" alt="Bildschirmfoto 2022-02-01 um 11 58 44" src="https://user-images.githubusercontent.com/58593037/151956535-2d0c31ef-ea62-4a77-a89d-f3d103d7df5b.png">

**Comment by lukasniebler** [comment]
Und die Menüpunkte sind immer oben ausgerichtet. Bei Safari sind die Punkte nicht bündig zum oberen Rand.

**Comment by xwolfde** [comment]
Wir können da mal checken. Aber wenn es ein Browserbug ist, ist es ein Browserbug.

**Comment by xwolfde** [comment]
Ich würde das auf die V2.1 verschieben.
Denn wir sollten eh nochmal an das Menü ran. Dass es nämlich teilweise das Logo überdenken kann, ist irgendwie doof. Aus den bekannten gründen können wir aber auch nicht einfach das Metamenü weiter unten beginnen. Ggf. könnten wir es aber statt über die ganze Briete gehen zu lassen, doch erst ab der Mitte starten.. 
ggf. sollten wir da nochmal jemand anderes fragen.

**Comment by lukasniebler** [comment]
Aus 🎫 |  http://go.fau.de/9s-1v 

Die Darstellung bei wenigen Inhaltspunkten / Menüpunkten müsste auch noch optimiert werden. Aktuell sieht es eher ungünstig aus (wie bei der Webmastersprechstunde schon von dir angesprochen)

![image001](https://user-images.githubusercontent.com/58593037/152346443-2d17d998-e18c-461b-97d4-3ef156b40aea.png)

**Comment by lukasniebler** [comment]
🎫 http://go.fau.de/9s-z3 | Aus Helpdesk

**Comment by lukasniebler** [comment]
Als Verbesserungsvorschlag aus den Fakultäten kam der Wunsch auf, ob man den Trennstrich zwischen 2. und 3. Menüebene deutlicher kennzeichnen kann, indem beim zentralen Themen z.B. ein weißer statt blauer Trennstrich verwendet wird.

Ausführlicher Vorschlag unter 🎫 http://go.fau.de/9saa2

**Comment by cassandre** [comment]
Ich habe bei den Arbeiten an FAU-Blog (WIP) das Hauptmenü unten bündig im dem Logo gemacht, und es sieht wesentlich besser aus!

**Comment by lukasniebler** [comment]
Aus 🎫 http://go.fau.de/9saon | Telefonticket | Informieren nach Besserung am Hauptmenü:

Kritik: Sehr unschön bei wenigen Menüpunkten (und die Portalbilder im Hauptmenü wurden vorher wohl gerne genutzt)

**Comment by xwolfde** [comment]
Eine Anregung kann uns auch die Mattermost-Seite geben:
https://mattermost.com/blog/how-to-install-and-set-up-neovim-for-code-editing/
![grafik](https://user-images.githubusercontent.com/1070669/153615565-2e737132-724b-4af6-905d-abbabd522da6.png)
und
![grafik](https://user-images.githubusercontent.com/1070669/153615628-800d7e6c-ba55-4f5b-ad96-e2fb3377550d.png)

und
![grafik](https://user-images.githubusercontent.com/1070669/153615684-484b8de4-8b27-4669-8034-cea5e59bf8be.png)


Das Overlay der Submenüitems 
* wird nach rechts ausgerichtet
* hat eine breite abhängig von der Zahl der Inhalte
* hat auch zusätzlich zu den Submenupunkten die Option auf Zusatzinhalten

**Comment by lukasniebler** [comment]
Nich nichts ausgereiftes aber ein paar Ideen für ein überarbeitetes Hauptmenü. Noch problematisch: die teilweise ungleiche Verteilung von Menüeinträgen, bzw. wie sich das Menü verhält wenn nur eine Hand voll Einträgen vorhanden ist (und wie das dann auch technisch umsetzbar ist?)

Ideen um das Menü zu verbessern:

- [ ] Hauptmenü farblos
- [ ] Menüpunkte der 1. Ebene werden konsistent dünn in Akzentfarbe unterstrichen
- [ ] Menüpunkte der 2. Ebene sind 2-3 Fontstufen leichter. (Also z.B. Roboto Light statt Bold)
- [ ] Der Portal-Button wird wie andere Menüpunkte behandelt und unter den letzten Menüblock geschoben. Ghostbutton oder alternativ transparent mit Farbakzent-Rahmen?
- [ ] Menü ist immer ein Click-Menü

Gibt noch viele ungeklärte Fragen. Hier ein paar Entwürfe. 
_________________________
![Full Mega Menu blue](https://user-images.githubusercontent.com/58593037/159488691-82c6780f-f014-4a13-bf85-4f25486e7a6f.png)
![Full Mega Menu green – 1](https://user-images.githubusercontent.com/58593037/159488795-859a1713-81a7-46e9-8440-f55291fbb603.png)
![Full Mega Menu green – 2](https://user-images.githubusercontent.com/58593037/159488816-b7fbd1bb-6d4d-4fab-b2fd-8e0e4363d371.png)
![Full Mega Menu green – 3](https://user-images.githubusercontent.com/58593037/159488836-6b0e8d46-b1fc-4b38-ab15-0595028be35b.png)
![Full Mega Menu green – 4](https://user-images.githubusercontent.com/58593037/159488844-508d8cce-103c-4d9f-a7ab-133b7c094f46.png)
![Full Mega Menu tf – 5](https://user-images.githubusercontent.com/58593037/159489118-0758676c-35b9-491c-8926-6133586c6714.png)
![Full Mega Menu green – 8](https://user-images.githubusercontent.com/58593037/159489184-1b892dc6-b746-4512-972e-600a44acbca6.png)
![Full Mega Menu green – 7](https://user-images.githubusercontent.com/58593037/159489188-d57dce9d-0798-406d-ae6f-a06700bca4fb.png)
![Full Mega Menu green – 6](https://user-images.githubusercontent.com/58593037/159489196-5450d54f-e679-4639-9226-32ea1532f5db.png)
![Full Mega Menu green ungünstige Verteilung – 7](https://user-images.githubusercontent.com/58593037/159489283-ba25b50e-9712-4086-8268-ca8bb162312e.png)
![Full Mega Menu not enough content blue – 1](https://user-images.githubusercontent.com/58593037/159489291-b3d3df52-9727-4f6c-95ca-077ee36dc4d1.png)
![Full Mega Menu tf – 9](https://user-images.githubusercontent.com/58593037/159489301-6992089c-2a66-4be6-9aaa-460836f64e10.png)

**Comment by xwolfde** [comment]
Die FH Aschaffenburg https://www.th-ab.de/ zeigt auch eine gute Umsetzung:
![grafik](https://user-images.githubusercontent.com/1070669/161764267-b5fdeab7-edf1-4e53-a8f9-be99bda094f7.png)

**Comment by lukasniebler** [comment]
Von Kundenseite gab es nochmal den Wunsch, dass das überarbeitete Hauptmenü auch die Option bietet, dass das Beitragsbild der Portalseite wieder mit ausgegeben wird. (Also ähnlich wie in dem Beispiel über diesem Kommentar).
