### ISSUE TITLE
Logo Abstand zwischen FAU und Schriftzug zu eng

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Einrichtungen#1036]
![Bildschirmfoto 2022-02-01 um 09 12 35](https://user-images.githubusercontent.com/9526974/151962676-fb0158a0-b255-4f1e-8edb-7401dae14f9e.png)

klein genug passt's dann wieder:
![Bildschirmfoto 2022-02-01 um 09 12 56](https://user-images.githubusercontent.com/9526974/151962679-6c1dc067-2147-4f3b-85f2-d7ab2c21e801.png)

**Comment by xwolfde** [comment]
Bei mir nicht? 

Du solltest dein Browser/PC aktualisieren?
![grafik](https://user-images.githubusercontent.com/1070669/151977412-3c5b0cf0-2e69-4c2e-952d-873e591fd910.png)

**Comment by xwolfde** [comment]
Bei deinem Browser sind lt. dem Bild auch alle anderen Abstände kaputt.

**Comment by cassandre** [comment]
Falls das nochmal aufschlägt: Safari 14.0 unterstützt kein column-gap / gap (https://css-tricks.com/safari-14-1-adds-support-for-flexbox-gaps/).

**Comment by xwolfde** [comment]
Wie bedauerlich... für Safari Nutzer :)
