### ISSUE TITLE
Bildgröße der Kontakte (FAU Person) nicht konfigurierbar

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1037]
Aus Helpdesk: 🎫 http://go.fau.de/9s-hm
(Plugin scheint korrekt konfiguriert zu sein)
____
Nach der Umstellung auf die neuen FAU Themes werden auf unserer Departmentswebseite Bilder bei Personenanzeigen, welche mittels dem FAU-Person Plugin eingebunden wurden, sehr groß dargestellt. Unsere Personen-Bilder sind alle gleichermaßen in einer Auflösung von 150-200 abgelegt und sind nun auf Grund der Größe extrem unscharf dargestellt. Ein Versuch, bei den Settings zum FAU Person Plugin das Format (unter Advanced Settings) zu ändern, führte leider zu keinerlei Veränderung. Die Bilder bleiben bei allen Einstellungen immer in der selben (viel zu großen) Darstellung.
 
Beispiele zu dem Problem finden Sie unter
 
https://www.datascience.nat.fau.eu/research/groups/amio/members/yiannis-giannakopoulos/
 
oder
 
https://www.datascience.nat.fau.eu/research/groups/pde/members/frank-duzaar/

**Comment by xwolfde** [comment]
liegt am flex-basis des figures. Das muss durch die eigene Definition im Kontext fau-person "überschrieben" werden.

**Comment by lukasniebler** [comment]
🎫 | http://go.fau.de/9s-kj  | Helpdesk | Erinnerung an mich selbst: Nach fix benachrichtigen

**Comment by lukasniebler** [comment]
🎫 | http://go.fau.de/9s-om | Helpdesk

**Comment by lukasniebler** [comment]
🎫 | http://go.fau.de/9s-op | Helpdesk

**Comment by xwolfde** [comment]
fixed

**Comment by lukasniebler** [comment]
🎫 | http://go.fau.de/9s-hm

Wie sieht es denn mit diesen anderen Größen aus. Wenn man die als Nutzer in den Settings unter Bildformat Kontaktseite einstellt, dann ändert sich die Bildgröße auf den Kontaktseiten nicht. z.B. Person-thumb... 

Größen Thumbnail / Medium / Large funktionieren korrekt wie erwartet.

**Comment by lukasniebler** [comment]
Nach Fix informieren:  🎫 | http://go.fau.de/9s-2b

**Comment by xwolfde** [comment]
ALso ich meine ja früher war das mit CSS. Aber da sollten wir nochmal nachchecken.

**Comment by cassandre** [comment]
Früher war mehr Lametta! ;-)
