### ISSUE TITLE
Darstellungsfehler auf der Suchergebnisseite

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Einrichtungen#104]
Wenn man der Suchergebnisseite ein Menü mitgibt, wird ein Papirfalz-&lt;hr&gt; dargestellt, in dem Teile der Max-und-Moritz-Grafik wiederholt werden. Das kann so nicht gemeint sein.
Screenshot mit Menü: 
![bildschirmfoto 2016-08-02 um 15 49 29](https://cloud.githubusercontent.com/assets/11296947/17330838/bf5ea48e-58c8-11e6-9de6-ee97611b2738.png)

Screenshot ohne Menü:
![bildschirmfoto 2016-08-02 um 15 50 11](https://cloud.githubusercontent.com/assets/11296947/17330863/d6d1b980-58c8-11e6-9518-49f626d7a146.png)

**Comment by xwolfde** [comment]
Skandal!

**Comment by AstridSemm** [comment]
Ja, verdammt! Wie soll ich denn die Screenshots verkaufen? Das sieht doch.... SCHLIMM aus!!!!111einself!

**Comment by AstridSemm** [comment]
Bescheid: Bei der Fehlerseite ist's dasselbe.

**Comment by xwolfde** [comment]
Das kommt, weil wir das HR geändert haben. Hätten wir auf @wrkb gehört, wäre das nicht passiert. Erzähle das bloß niemand weiter :))

**Comment by AstridSemm** [comment]
Dann mach das weg, das braucht auf der Seite sowieso kein Mensch! (Und @wrkb merkt das bestimmt, der merkt alles, was mit dem Falz zu tun hat. ;oD)

**Comment by xwolfde** [comment]
HA! Wäre auch vorher passiert. Es liegt gar nicht an der Pfalzhöhe, sondern an dem zu Wenig an Inhalt.

**Comment by xwolfde** [comment]
Fixed. 
These are not the Pfalzes you are looking for
