### ISSUE TITLE
Textumbruch in linker Navi klappt nicht

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Einrichtungen#1043]
![image](https://user-images.githubusercontent.com/9526974/152148926-793291e4-31c9-4abd-aa24-476fc26d853b.png)

**Comment by xwolfde** [comment]
Das wäre so auch ein Barrierefreiheitsfehler, wie ihr es macht. Bitte führt da Lehrzeichen vor und nach dem "/" ein. Dann löst sich auch das Problem.
An sich wäre es ansonsten auch besser ganz auf "/" in Seitentiteln zu verzichten.
