### ISSUE TITLE
Bildauflösungen und Größen Blogroll/Startseite

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#1048]
Aktuell wird eine feste Breite vorgegeben und das Bild dementsprechend proportional in der Höhe gesetzt.

Vorher war es ein festes 3:2 Format mit maximaler Breite und maximaler Höhe.
 
Probleme:
- Wenn das Ursprungsbild kleiner ist als die Maximalbreite , dann wird es vergrößert. Sieht schlecht aus.
- Wenn das Bild höher ist als 3:2, wird der Textbereich rechts einen zu großen Weißraum bekommen
- Wenn aber jemand genau das Bild so hochladen will, gehen Automatismen nicht

Lösung:
- Freiheit des AUtors belassen
- ZUsatzoption, auf der Blogroll das Bild entsprechend des Formats zu "Quetschen", so dass es in 3:2 passt und dabei dann auch kleiner wird, wenn es zu groß ist.

**Comment by xwolfde** [comment]
@lukasniebler @cassandre Sollen wir das so mit der Option machen? Wäre IMHO das einfachste. Ich würde die Customizer-Option einfach eine body-class "blogroll-image-3-2" (oder so) setzen lassen. Würdest du @cassandre das schonmal umsetzen im CSS?

**Comment by lukasniebler** [comment]
🎫 http://go.fau.de/9s-jc | Nach Umsetzung ggf. nochmal informieren (Erinnerung an mich..)

**Comment by xwolfde** [comment]
Ggf. erstmal bis V2.1 das Quetschen als Default, weil es so bisher ja auch war. Ab V2.1 stellen wir den default dann um auf Bild-Original.

Andere Meinungen?

**Comment by xwolfde** [comment]
@wrcg

**Comment by cassandre** [comment]
Ich wäre für die jetzige Darstellung als Default – das kennen die Leute jetzt schon seit einer Woche. Und manchen hat es ja explizit gefallen.

**Comment by wrcg** [comment]
Wir haben im Vorfeld auch mal lange darüber diskutiert, dass dann bei kleineren Bildern der "Füllbereich" zu 3:2 ein grau bekommt. Wir würden bei uns vermutlich auf "Quetschen" einstellen. 
Ich würde auch als default jetzt und auch bei V2.1 quetschen nehmen. Denen es jetzt so gefallen hat, werden sie melden und können es wieder umstellen. Wie die Stimmen heute waren, denke ich, der Mehrheit würde das gequetschte besser gefallen.

**Comment by xwolfde** [comment]
Aufgrund des Feedbacks: Wir machen es so, dass per Default "Quetschen" an ist.

**Comment by xwolfde** [comment]
im nächsten update
