### ISSUE TITLE
CSS-Anpassung bei Trennlinie innerhalb eines Akkordeons notwendig(?)

### ISSUE THREAD

**Issue by csw-** [RRZE-Webteam/FAU-Einrichtungen#105]
Bei der Verwendung einer Trennlinie innerhalb eines Akkordeons kommt es zu einem unschönen Effekt (siehe Bild) da das Akkordeon eine andere Hintergrundfarbe besitzt. Hier müsste ggf. im CSS nachgebessert werden.

![akkordeon-hr](https://cloud.githubusercontent.com/assets/6545158/17363605/bfae7f5a-597b-11e6-968d-94ac125f19a6.png)

**Comment by xwolfde** [comment]
ARGH .. Ihr verwendet HR in Accordions?!?   Wieso??  Die Accordions selbst sind doch schon trennende Bereiche. 
Ich werd es reparieren, kein DIng. Aber die Nutzung von hr innerhalb Accordions ist IMHO eine Fehlbenutzung.

**Comment by xwolfde** [comment]
fixed. siehe da schau:
http://test8.tindu.rrze.uni-erlangen.de/tests/shortcodes/accordion-und-personen/accordions-mit-multimedialen-inhalten/
die Linienfarbe ist die jeweilige CI Farbe in der hellsten farbvariante

**Comment by xwolfde** [comment]
Im nächstebn Bugfix enthalten
