### ISSUE TITLE
Schrifthintergrund an der TechFak im Header

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1050]
Aus  🎫 | http://go.fau.de/9s-22
<img width="242" alt="Bildschirmfoto 2022-02-03 um 16 01 36" src="https://user-images.githubusercontent.com/58593037/152368572-3f4507cd-2d34-4f25-b61d-95901071fe75.png">

Der Texthintergrund wird als störend dunkel wahrgenommen.

Gibt es Alternativen? Vielleicht einfach weiß, etc.?

**Comment by xwolfde** [comment]
Der "Fehler" liegt im hochgeladenen Bild.  Der Hintergrund der Schrift kann nicht geändert werden, da der fest auf der Designfarbe ist.
