### ISSUE TITLE
Bedienungsproblem - Markieren verursacht scroll | kopieren von Überschriften nicht möglich

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1051]
Aus Helpdesk 🎫 | http://go.fau.de/9s-7x

- [ ] Betroffene Seite:
https://www.fau.de/education/studienorganisation/semestertermine/
Details: 
Erst scrollt man ein stück runter. Beim Markieren des Textes in "Semestertermine" scrollt
bzw. springt die Seite automatisch wieder hoch.
- [x] #1052
aus den blauen Balken markieren und damit rauskopieren (habe ich gestern beim
Newslettererstellen bemerkt) - in Firefox und Chrome.

Nähere Informationen im Helpdesk-Fall 🦉

**Comment by xwolfde** [comment]
Hab aus den zweiten Punkt einen eigenen Issue gemacht. War mir auch schon aufgefallen.
Das erste kann ich nicht nachvollziehen mit einem modernen Browser. Leider gibt der Helpdeskfall keine Informationen über die Konfig der Melder.

**Comment by lukasniebler** [comment]
Bei mir im Safari passiert das auch. Wenn du die Überschrift selektierst springt es hoch.

**Comment by lukasniebler** [comment]
Semest- und Vorlesungstermine muss markiert werden wenn man leicht runter gescrollt hat, dann springt der Browser nach oben und die Überschrift wird unsichtbar.

**Comment by xwolfde** [comment]
Ich hab die Seite mit Firefox, Chrome und Safari offen.

Da springt bei mir nichts.

**Comment by lukasniebler** [comment]
Meine Theorie zum scroll...

Beim markieren springt es automatisch nach oben und es wird das Problem unter: https://github.com/RRZE-Webteam/FAU-Einrichtungen/issues/1003 getriggert, weil die Sidebar mitmarkiert wird.

(Getestet in Safari)

![2022-02-04_14-28-09 (1)](https://user-images.githubusercontent.com/58593037/152537431-45069c74-cacd-4411-9b12-7118bafe94fe.gif)

**Comment by cassandre** [comment]
Kann ich mit Safari, Chrome und Firefox (jeweils neueste Version) auf MacOS 11.6.2 auch bestätigen. 

Passiert meiner Beobachtung nach immer, wenn man ein Block-Element von Zeilenanfang an markiert.

**Comment by xwolfde** [comment]
Ich hab das Gefühl, es liegt am scrolling-offset für die Sprungmarke zum Inhalt.

Wir brauchen diese aber wegen dem fixed Header, da man ohne sie bei einer Sprungmarke von einem Link oder beim Sprung auf den Inhaltsbereich von den Quicklinks sonst den angesprungenen Teil nicht sieht; er dann "unter" dem Header liegt.

Möglicherweise müssen wir nochmal den scrolling offset abhängig vom jeweiligen Template und dem Header optimieren.

**Comment by xwolfde** [comment]
Das Problem ist nach wie vor bei einigen Seiten feststellbar. Wir sollten hier nochmal schauen, ob wir eine Lösung finden. Zur Not wäre eine Retoure der CSS-Eigenschaft denkbar. Dann würde allerdings bei einer Sprungmarke der angesprungene Teil under the fold sein....

**Comment by xwolfde** [comment]
Das Problem wird mit der nächsten Version behoben sein.
