### ISSUE TITLE
Darstellung der Ansprechpartner in Akkordeons verbessern

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1054]
Es wurde gefragt, ob man die Darstellung der Ansprechpartner im Akkordeon noch aufwüschen kann:
https://www.fau.de/fau/leitung-und-gremien/gremien-und-beauftragte/cio-gremien/#collapse_0

**Comment by xwolfde** [comment]
Ja, kann man.

Zum Beispiel kein Accordion um eine schlichte UnivIS Ausgabe machen, sondern das Personenplugin nutzen.
Das hat nichts mit dem Theme zu tun.
