### ISSUE TITLE
Galerien in Akkordeonfächern werden erst nach klick angezeigt

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1059]
Beispielseite:
https://www.getr.rw.fau.de/institut-fuer-recht-und-technik/tagungen/#collapse_2

Verbundenes Ticket:
🎫 http://go.fau.de/9saon

**Comment by cassandre** [comment]
Das gabs schon mal: https://github.com/RRZE-Webteam/rrze-elements/issues/78, wurde aber damals schon als FAU-Theme-Problem weitergereicht.
