### ISSUE TITLE
Slider auf der Startseite fehlt am Handy

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/FAU-Einrichtungen#1060]
Der Startseiten-Slider fehlt, wenn ich fau.de auf meinem Smartphone öffne komplett. Browser ist Firefox, Slider fällt auch raus, wenn ich das Browserfenster kleiner mach.

**Comment by xwolfde** [comment]
Ja, ist Absicht, war aber schon im letzten Jahr in der Vorversion so.

**Comment by AndiWebred** [comment]
Bitte das Ticket wieder öffnen. 
Inhalte sollten nicht für einen User verborgen sein, nur weil er ein bestimmtes Gerät verwendet.
Wir möchten den Slider auch in der Handyversion haben. Und ja: Uns ist bewusst, dass die Darstellung des Bildes nicht toll ist. Uns nervt das auch, aber dann muss an der Stelle eben bei Gelegenheit noch nachgearbeitet werden.

**Comment by xwolfde** [comment]
Der Slider ist nur eine zusätzliche, optische Methode den Content zu erreichen, die auch nur für Menschen funktioniert, die optisch den Slider sehen können. Die Sliderinhalte sind auch nicht für Menschen mit Screenreader zugänglich.

Ein weiterer Punkt der gegen den EInsatz auf Handy spricht ist das übertragene Datenvolumenen. Das ist nicht akzeptabel, dass Handyuser die großen Bilder laden müssen.

Von daher: Nein, hier hab ich als Projektleiter entschieden, dass der Slider ausgeblendet wird und bleibe dabei.

**Comment by xwolfde** [comment]
Ich öffne das mal als Diskussions-und DOkumentations-Issue.

Stell dir doch einfach mal vor, was passieren wird:
![grafik](https://user-images.githubusercontent.com/1070669/152992971-95cc73a2-ff9b-4ba8-bcff-616ae8fd5fff.png)

Wir haben ein riesiges Originalbild, welches für Desktop optimiert wurde. Es ist im Orginal 1600px breit und 835px hoch.
In der Regel habt ihr da auch irgendwelche Menschen drauf, die man irgendwie doch erkennen sollte.
Und ihr habt mindestens einen Titel.


Das muss auf einem Handy. Bei Iphone 12/13 haben wir nur 428pixel Breite, bei Pixel haben wir 411px.

![Uploading grafik.png…]()

Wir brauchen aus Gründen der UX und der Barrierefreiheit für die beiden Pfeile links und rechts immer mindestens 48px Breite plus je einen Margin zum Rand und zum Text von nochmal 10px. Also  68px x 2 = 136px für die Bedienelemente.
Ergo haben wir bei Pixel nur 411-136px = 275px Platz für den Titel. (Den Teaser kannst du da eh schonmal knicken).
Bei einer Mindestschriftgröße von 16px hast du in etwa 17 Buchstaben pro Zeile frei.

Du brauchst also bei der üblichen Titellänge in der Regel 3, wenn nicht gar 4 Zeilen
Wenn du die obigen Grafik proportional auf 411 Pixel verkleinerst, ist sie nur 214 Pixel hoch (Pixel Handy). Bei dem IPHone wären es 223 Pixel hoch.
 
Nehmen wir wieder das Pixelhandy:  In einer 223 Pixel Höhe kriegst du bei einer Zeilenhöhe von 16px * 1,5 = 24px maximal 9 Zeilen rein, ohne Abstand zum Rand. Da du aber Abstand zum Rand brauchst, sind es maximal 7 Zeilen.
Ergo hast du aber maximal 7 Zeilen a 17 Buchstaben 119 Buchstaben für den Titel zur Verfügung, wobei du dann aber das ganze Bild vollknallst.

Jetzt hast du aber ein schönes Bild mit Menschen drauf. Was passiert da wohl?
Genau. Die Leute werden durch die Textüberlagerung nicht mehr lesbar sein.

Damit ist der ganze dekorative Charakter des Sliders in der Büx.

Ergo: Ein Slider, also ein rein dekoratives Element, macht auf einem Handy in der Form keinen Sinn.

**Comment by AndiWebred** [comment]
Vielen Dank für die ausführliche Problembeschreibung, die ich durchaus nachvollziehen kann. Ich bin da auch bei dir, dass der Slider auf Handys ein Problem ist (zum Beispiel auch der Bildausschnitt). Wir brauchen aber eine Lösung dafür. Denn für uns als Kommunikatoren ist der Slider einer unserer wichtigen Kommunikationswege. Und wenn wir den Slider von den Handys nehmen, geben wir für potentiell 50% unserer Nutzer:innen diesen Kommunikationsweg praktisch auf und das ist nicht gut. 

Ich bin aber froh, dass du das zur Diskussion stellst, denn eine Lösung, die sowohl barrierefrei als auch datenarm ist, wäre toll.

- Was wäre, wenn der Text nicht auf dem Bild, sondern darunter in einerm blauen Box erscheint?
- Was ist, wenn wir auf Handys die Pfeile weglassen? Die Punkte unten reichen ja. Dann sparen wir wieder Platz.

Es gibt sicherlich noch viele andere Möglichkeiten, wir sind ja nicht die einzigen Menschen, die einen Slider nutzen: 
- www.tum.de
- www.uni-stuttgart.de
- www.uni-leipzig.de
- www.hu-berlin.de
- www.uni-hamburg.de

**Comment by xwolfde** [comment]
_Wir brauchen aber eine Lösung dafür. Denn für uns als Kommunikatoren ist der Slider einer unserer wichtigen Kommunikationswege_

Wenn ich mir die aktuelle Clickmap anschaue (und zwar ein IPad-Ansicht, wo der Slider noch zu sehen ist), dann muss man konstatieren, dass es zwar Leute gibt, die auf die Pfeiltasten gehen, aber nahezu niemand klickt auf den Link des Beitrags:
![grafik](https://user-images.githubusercontent.com/1070669/153000816-1545565c-3534-4a6c-83a4-edd3e7f4b707.png)

Von daher: Nein, auf Auflösungen unter Desktop sehe ich die Behauptung nicht erfüllt, dass die der Slider ein wichtiger Kommunikationsweg ist. Im Gegenteil ist er offensichtlich ein Element bei dem Leute verzweifelt klicken, aber nichts finden: Der Slider bewirkt das Gegenteil.

Und selbst wenn ich mir die Clickmap der Desktopseite anschaue:
![grafik](https://user-images.githubusercontent.com/1070669/153001286-c73d253d-3836-4e3e-95b9-3c119ebb0bc0.png)

Dann muss ich feststellen, dass die allermeisten Klicks nicht auf dem Link des Slides zum Artikel sind. Auch wenn es bei dem Weihnachtsbeitrag mehr sind als auf IPad, sind das offenbar deutlich weniger Klicks als auf das Menü oder auf die 3 Portalmenübilder darunter.

**Comment by xwolfde** [comment]
Du hattest aber echt, dass der Slider doch vorher in Handyauflösung da war. Da hab ich mich getäuscht. Das gilt nämlich nur für euren ILI-Slider. Bei den SLider der Fakultäten war es so, dass der schon lange auf Handy unsichtbar war.

Aber dafür haben wir eine Klickmap für Handy:
![grafik](https://user-images.githubusercontent.com/1070669/153002222-4789715f-7e6d-4091-a160-224f497cc50d.png)

Und auch hier zeigt sich mehr als eindeutig: Der Slider wird so gut wie gar nicht benutzt. Er ist also kein wichtiger Kommunikationsweg.

**Comment by AndiWebred** [comment]
Willst du jetzt über Lösungen diskutieren oder über Farben auf Klickmaps? Also bitte: Gerade der letzte Screenshot zeigt ja wohl, dass der Slider durchaus geklickt wird. Er wird nicht so häufig geklickt wie "Studieren an der FAU"? Ja, so what. Beiträge, die im Slider laufen haben aber im großen und ganzen bessere Zugriffszahlen als andere Beiträge. Der Slider wird also genutzt.

Können wir jetzt vielleicht auch mal über Lösungsvorschläge reden?

**Comment by lukasniebler** [comment]
Aus UX Sicht sind Slider weder auf Desktop, noch auf Mobile nutzerfreundlich. Stattdessen sollte man langfristig versuchen davon weg zu kommen und sich ein Vorbild an entsprechenden Vorbildern nehmen, die davon Leben, Beiträge zu präsentieren.

https://www.nytimes.com
https://www.sueddeutsche.de
https://www.br.de/index.html
https://www.merkur.de
https://www.spiegel.de
https://medium.com
https://www.faz.net/aktuell/
https://www.theguardian.com/international
https://www.nationalgeographic.com
... usw.

**Comment by AndiWebred** [comment]
1. Ich bin für konstruktive Vorschläge offen.
2. Der Vergleich hinkt leider etwas, denn wir sind keine reine Newsseite.

**Comment by xwolfde** [comment]
Es wird keine Vorschläge geben können, wenn wir nicht faktenbasiert an Bedürfnisse herangehen können. Wenn die Fakten nicht gefallen, ignoriert und daher abgetan werden ("über Farben diskutieren"), dann können wir nicht dahin kommen ein gemeinsamen Verständnis über das Problem zu entwickeln und somit  daraus hinaus auch keine Lösung erarbeiten.
Wir haben auf den Milestones die Todo den Slider für alle Websiten zu vereinheitlichen. Das ist bis Sommer vorgesehen.  In dem Zuge können wir das Thema gern nochmal anschauen.

**Comment by migrosch** [comment]
@lukasniebler Das mit dem Slider sehe ich aus UX-Sicht ähnlich. Allerdings lassen sich, wie @AndiWebred bereits geschrieben hat, News-Websites nur bedingt mit der FAU-Website vergleichen, die eher werblichen Charakter hat. Außerdem wäre das, wie du auch schreibst, eher langfristig zu sehen.

@xwolfde Es ist sehr wohl ein Problem, da der Slider Bestandteil des Funktionsumfangs war, der anscheinend vom Projektleiter ohne Rücksprache mit den betreffenden Stakeholdern eigenmächtig entfernt wurde. Deshalb wäre es schön, wenn wir hier gemeinsam eine sinnvolle Lösung finden könnten, anstatt Ping-Pong zu spielen. Und diese Lösung kann nicht sein, den Slider einfach zu entfernen und somit bestimmten Usern diese Inhalte vorzuenthalten. Es ist nicht sehr benutzerfreundlich wenn der Webmaster entscheidet, welche Inhalte wer zu Gesicht bekommt und welche nicht. Das grenzt ja schon fast an Zensur. ;-)

Wir sind offen für konstruktive Lösungsvorschläge, die auch sein könnten, dass der Slider durch etwas anderes ersetzt wird.

**Comment by AndiWebred** [comment]
Wir können gerne faktenbasiert und offen an die Sache rangehen. Kein Problem. Und wenn am Ende der Diskussion der Slider fällt: Bitte. Aber dann erwarte ich auch, dass unsere Einwände ernst genommen werden. "Es gibt kein Problem, wie ich darlegte. Also gibt es auch keinen Bedarf an einer Lösung." -> So nimmt man mich und meine Argumente (und Fakten) nicht ernst.
