### ISSUE TITLE
Pdf-Icon vor Listenicon

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Einrichtungen#1061]
in der Sidebar:
<img width="353" alt="image" src="https://user-images.githubusercontent.com/9526974/152939571-35d30af1-5bbb-41a6-aec2-8d58beafb56e.png">
Seite: https://www.fau.de/education/studienorganisation/die-faucard/

**Comment by xwolfde** [comment]
Das ist die Mime-Link-Icon-Plugin für Links.  

Empfehlung: Deaktivieren.

**Comment by xwolfde** [comment]
Theoretisch könnten wir Links mit einem HTML-Attribut versehen, welches dem Plugin sagt, hier keine Icons zu setzen.
Aber dies funktioniert nur bei solchen Links, die z.b. bei einem Menu gesetzt werden.
Denkbar wäre das aber gleichwohl auch bei den Links aus der Quicklinkliste in den Sitebars von Pages. Nachteil: Es würde immer gelten.
Aber: Wenn nun jemand in der Sidebar statt mit den Quicklinks eine Widget nutzt und darin über eigenes HTML dann auch LInks setzt, dann könnten die plötzlich die Icons haben, wären die Liste darüber keine hat.

Mir fällt keine gute Lösung ein. Das Plugin und der Zweck ist halt "out" und nicht gut konfigurierbar.
Richtig wäre bei PDF-Links der Weg, einfach den Link zu setzen und im Titel dann zu ergänzen: "(PDF, nicht barrierefei)"

**Comment by xwolfde** [comment]
In der Version 2.1 werden Links, die in einem Widget sind und dabei als Liste angeordnet sind, nun das Mimetype Link Icons rechts erhalten. Es muss dazu nichts an dem Plugin konfiguriert werden.
