### ISSUE TITLE
Seitebreite zwischen 992 und 1399px flexibel machen

### ISSUE THREAD

**Issue by cassandre** [RRZE-Webteam/FAU-Einrichtungen#1062]
Zwischen 992 und 1399px könnte man die Seitenbreite mit dem Bildschirm wachsen lassen (also ohne max-width). Dann wird der mittlere Bereich nicht so schmal, obwohl außen noch Platz wäre:
![Bildschirmfoto 2022-02-08 um 14 56 25](https://user-images.githubusercontent.com/4435815/153001866-ae30b7a3-0815-4a3b-8d95-e14b83cb21f2.png)

**Comment by xwolfde** [comment]
Auf 2.2 verschoben, da keine Sache vom Print
