### ISSUE TITLE
Umsetzung des Sliders auf Mobile Devices

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#1072]
Auch wenn der Slider der Startseite ein rein dekoratives Element ist, ist nicht von Hand zu weisen, dass man die "Inhalte" in irgendeiner Form auch auf kleinen Displays haben möchte. Vgl. Diskussion in #1060 . 
Das aber die Darstellung nicht dieselbe sein kann, wie auf größeren Displays, versteht sich von selbst und sollte hier nicht weiter diskutiert werden. 
Es geht darum eine neue mediengerechte Darstellung derselben zu finden auf Basis derselben Inhalte.

Folgen Inhaltsdaten stehen zur Verfügung:
* Ein großes Bild in vorab definierten Image Sizes. Optional können die Bilder auch einen Copyright-Text haben.
* Eine Überschrift
* Eine URL
* Ein Teasertext

Folgende Rahmenbedingungen haben wir:
* Content matters: Wiederkehrende Nutzer der Seite aber auch Suchmaschinen priorisieren den eigentlichen Content. Der Slider ist nicht Teil des Content-Bereiches der Seite.
* Maximale Breite 480 Pixel. Pixel und IPhone Hände sind jedoch eher auf 414, bzw 420 Pixel Breiten unterwegs.
* Es muss auch eine Lösung geben für Geräte mit einer maximalen Breite von 320 Pixel
* Die verwendete Grafik enthält unter Umständen auch Personenbilder. Diese möchte man erkennen. Bei der geringen Größe führt aber eine Überlagerung mit Text dazu, dass die Grafik nicht mehr erkannt werden kann.
* Der Slider muss stoppbar sein, man muss vor und zurückspringen können. 
* Touch-Events (Swipe) statt Mausklicks müssen vorhanden sein und funktionieren

Erwägungen:
* Der Leser der Seite soll durch den Slider nicht über Gebühr scrollen/nach unten swipen müssen um zum eigentlichen Inhalt zu kommen. Ggf. wäre daher zu überlegen, ob man den Slidercontent auch auch unter den Content aber vor der Sidebar positioniert.
* Denkbar wäre auch, die Anzeige der Grafik zu skippen und nur eine aufgehübschte Liste der verlinkten Artikel anzubieten.
* Um den Ermüdungseffekt bzw den Nerveffekt von Wiederkehrenden Nutzern abzumildern, könnte man auch in Erwägung ziehen, den Slider via Option durch den User und dem Speichern eines Cookies abschaltbar zu machen. Dann würde der Slider nicht mehr auftauchen, solange es keine neuen Elemente gibt. Nachteil: Erlaubnisvorbehalt des Users beim Setzen von Cookies einholen.

**Comment by AndiWebred** [comment]
Ich möchte hier noch ergänzen, dass der Slider (oder welche Darstellungsform hier auch immer gewählt wird) durchaus Content ist und zum Contentbereich genauso dazugehört, wie die drei Startseitenmeldungen. Meiner Interpretation der Heatmap mit den vielen Klicks auf die Pfeile wäre nämlich: Es reicht den Leuten manchmal auch einfach nur eine Headline zu lesen bzw. sich durch die wichtigen News zu klicken/zu scrollen.

Aber ich bin offen dafür, den Slider zu skippen oder sogar die Bilder rauszuwerfen.

Wenn wir aber bei Slider+Bild bleiben finde ich es kein Problem, den Text unter das Bild zu setzen. Wir müssen ja nicht das hochkant Bild-Format nehmen, das wir vorher auf mobil hatten, sondern ein Querformat nehmen, etwa wie die Uni Köln das macht. Ganz charmant finde ich die Uni Leipzig, weil die das Bild eh so von allen Seiten beschneiden, dass der Ausschnitt fast schon Wurst ist. Sieht aber bei Gruppenbildern vermutlich furchtbar aus.

Als Alternative zum Slider fallen mir jetzt zwei Möglichkeiten ein: Entweder es gibt nur noch eine Bühnenmeldung. Oder die Slides erscheinen untereinander.
Wenn die Slides untereinander erscheinen: Könnte man nicht das gleiche Bild-Format wie bei Desktop nutzen? Das wäre dann sehr schmal, aber vielleicht reicht es ja um Aufmerksamkeit zu erzeugen.

**Comment by xwolfde** [comment]
Es geht u.a. um die Barrierefreiheit: Wenn es nicht als Dekorativ deklariert werden sein soll, sondern als Content gesehen wird, dann müssen die Bilder eine Aussage haben und beschrieben werden. Diese Beschreibung muss dann irgendwo verfügbar gemacht werden und sie muss ggf mit sliden.

**Comment by xwolfde** [comment]
Ggf. auch einfach eine Option für den Customizer einbauen:
_Slider auf Bildschirmgrößen unter 480 Pixel ausblenden_

**Comment by AndiWebred** [comment]
> Es geht u.a. um die Barrierefreiheit: Wenn es nicht als Dekorativ deklariert werden sein soll, sondern als Content gesehen wird, dann müssen die Bilder eine Aussage haben und beschrieben werden. Diese Beschreibung muss dann irgendwo verfügbar gemacht werden und sie muss ggf mit sliden.

Und ist das schwierig umzusetzen? Weil einen alt-Text sollten die Bilder ja eh haben, eine Aussage auch.

**Comment by xwolfde** [comment]
Anbei die aktuellen Headmaps 
![fau-behaviourmap-startseite-desktop](https://user-images.githubusercontent.com/1070669/199939368-511db5e3-8055-442a-8c5f-aea4a277e9eb.png)
![fau-behaviourmap-startseite-handy](https://user-images.githubusercontent.com/1070669/199939383-a3eb7d82-6102-41f7-a706-5f0bb1d67334.png)
![fau-behaviourmap-startseite-tablet](https://user-images.githubusercontent.com/1070669/199939391-2ec2aefe-d90e-4ab1-ad76-5394b6dcf1ff.png)
