### ISSUE TITLE
Startseiten: Slider-Update

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#1073]
Sammel-Issue zum Update des Sliders

- [x] #1072 
- [x] #1071 
- [x] #960 
- [x] #1074
- [ ] #1076
- [x] #1077
- [ ] Slidertechnik evaluieren: Ist Slick-Slider noch immer die beste Lösung? Finden wir auch eine barrierefreiere Lösung ohne JS, die aber trotzdem auf Mobile Devices Swiping unterstützt?

**Comment by wrcg** [comment]
Die Schrift auf dem Slider - weiß auf (oft) buntem Hintergrund - wirkt unruhig. Evtl. gibt es hier noch bessere Möglichkeiten...
