### ISSUE TITLE
Bildergalerien - Rückmeldung zur Darstellung

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1080]
(Aus 🎫 http://go.fau.de/9sbwt )

In der Bildergalerie werden die Bilder, in der Verlaufsleiste unten, mit verschiedenen Höhen angezeigt.

Beispiel:
https://www.kunstgeschichte.phil.fau.de/studium/bachelorstudiengang/
<img width="1264" alt="Bildschirmfoto 2022-02-14 um 07 58 26" src="https://user-images.githubusercontent.com/58593037/153815037-c6278c4f-32c0-455b-9bf3-636b67083aa4.png">

Mögliche Ideen, wie die Darstellung verbessert werden könnte:
- [ ] Bilder haben identische Höhe und Breite variiert
- [ ] Oder dasselbe Vorgehen wie in der Startseiten-Blogroll. Bilder im anderen Format erhalten eine Stauchung & Hintergrundfarbe
(Wären zumindest meine Vorschläge)

**Comment by cassandre** [comment]
Bei der variablen Breite kommt wahrscheinlich das JS in die Bredouille, weil es die Leiste beim Weiterblättern dann jedes Mal unterschiedlich weit verschieben muss.
Man könnte auch einfach croppen (image-fit: cover):
![Bildschirmfoto 2022-02-14 um 15 25 54](https://user-images.githubusercontent.com/4435815/153883124-2b41416c-62a6-4f00-ad41-fb6a0c809a09.png)
