### ISSUE TITLE
Einschub: Links werden nicht als Links markiert

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/FAU-Einrichtungen#1084]
In Einschüben ([pull-left]) werden Links nicht als Links markiert (also nicht unterstrichen/kein Mouse-Over) und sind damit nicht als Links identifizierbar.
Beispiel: https://www.fau.de/2021/07/frisch/mission-money/

**Comment by cassandre** [comment]
Liegt am allumfassenden Link-Styling im neuen FAU-Theme.

**Comment by xwolfde** [comment]
Wieso wird hier denn bitte ein `aside`  im Content verwendet?

```
<aside class="pull-left">
<p><a href="http://www.ibz.fau.de" data-wpel-link="internal">Informations- und Beratungszentrum für Studiengestaltung (IBZ)</a><br>
Halbmondstraße 6, Zi. 0.021, Erlangen<br>
Tel.: 09131/85-23333 oder 24444</p>
</aside>
```

**Comment by xwolfde** [comment]
Und wenn schon eine Adresse/Kontaktdaten, dann entweder über Kontakt-Plugin oder in `<address>`

**Comment by cassandre** [comment]
Nein. Das ist ein Einschub, den es so schon ewig in Elements gibt. Und der ist semantisch auch korrekt als aside definiert (https://developer.mozilla.org/de/docs/Web/HTML/Element/aside).
Dass der an dieser Stelle für zweispaltigen Inhalt missbraucht wird, ist ein anderes Problem.

**Comment by xwolfde** [comment]
Dann bleibt uns nichts über als die Defaultlink-Include bei aside wegzunehmen.

Wenn wir das machen, dann müssen wir danach noch schauen, ob die Sidebar "gut" ausschaut oder wir dann ewttliche Klassen/Widgets ergänzen müssen.

**Comment by cassandre** [comment]
Ich denke, dafür ist es zu spät. Das hat ja Auswirkungen auf alle Plugins... Ich werde wohl eher im elements-Stylesheet das überbügeln.

**Comment by xwolfde** [comment]
Ich meine, wenn wir in sass/elements/_links.scss, Zeile 120 einfach aside entfernen.

Da dort in Zeile 119 ja noch .widget definiert ist, werden dann die Links in den Widgets trotzdem noch im defaultlinkstyle() formatiert, wie es gewollt ist. Nur aside wird nicht mehr der "Umschalter" sein.

**Comment by cassandre** [comment]
OK, ich probier's.
