### ISSUE TITLE
Problemmeldung Safari: Level 2 Ebene Items erscheinen nicht ausgerichtet

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#1088]

**Comment by xwolfde** [comment]
Meldung aus Fall:

Im Safari Browser, aktuelle Version 15.x unter iOS, sind Menüpunkte nicht in einer Linie.
![grafik](https://user-images.githubusercontent.com/1070669/155527750-cdd22768-a666-40e5-a268-7bfb621d0035.png)

Das Problem tritt bei anderen Browserm (Firefox, Chrome, Opera) nicht auf.

Beispiel https://www.rt.tf.fau.de/, Unterpunkt Lehrstuhl.

Ggf. wird das Problem durch die geplante Optimierung des Menüs verbessert. Dennoch prüfen.

**Comment by cassandre** [comment]
Ist bereits in 68f9f44 (16.02.) gefixt. Ist dann im nächsten Update drin.

**Comment by cassandre** [comment]
Siehe auch #1034
