### ISSUE TITLE
Fertig eingerichtete VM mit Entwicklungsumgebung / FAU Theme Testinstanz bereitstellen?

### ISSUE THREAD

**Issue by Albager** [RRZE-Webteam/FAU-Einrichtungen#1089]
Es wäre total super, wenn Sie vom Webteam eine _fertig eingerichtete_ virtuelle Maschine mit allen zur Entwicklung für das FAU Wordpress-Theme benötigten Tools zum Download bereitstellen könnten, idealerweise auch gleich mit allen Fakultätsthemes als Tochterseiten wie unter https://www.wordpress.rrze.fau.de/entwicklung/eigene-testinstanz/ beschrieben. Das würde es erleichtern, "mal schnell" eigene Code-Ideen testen zu können, ohne sich erst (stunden-) lang mit dem Setup einer Testinstanz + Entwicklungsumgebung herumschlagen zu müssen 🥴 Darüber würde ich mich sehr freuen und vielleicht haben andere ja auch Bedarf an sowas.

**Comment by xwolfde** [comment]
Darüber können wir uns gesondert unterhalten. Ist aber kein Issue zum Theme.
