### ISSUE TITLE
.content-person: Linker Innenabstand zu gering (bei max-width: 767px) 

### ISSUE THREAD

**Issue by endv02** [RRZE-Webteam/FAU-Einrichtungen#109]
siehe https://github.com/RRZE-Webteam/fau-person/issues/149

**Comment by xwolfde** [comment]
Wieso? IMHO ist der Margin ausreichend, da braucht es nicht nich zusätzlich einen Padding in der inneren Box.
@csw-

**Comment by csw-** [comment]
Der Content ist von einem grauen Rahmen umgeben, ohne das Padding klebt der Text direkt am Rahmen und sieht entsprechend ungut aus. 

![screen shot 2016-08-09 at 18 08 56](https://cloud.githubusercontent.com/assets/6545158/17523861/65076964-5e5c-11e6-959a-bf4557731945.png)

**Comment by xwolfde** [comment]
ah, jetzt ja

**Comment by xwolfde** [comment]
In der nächsten Version behoben
