### ISSUE TITLE
PDF-Icon in Suchergebnissen zu groß 

### ISSUE THREAD

**Issue by cassandre** [RRZE-Webteam/FAU-Einrichtungen#1090]
Beispiel: https://www.fau.de/?s=Vorbereitungsdienst&se=0
![Bildschirmfoto 2022-03-01 um 15 49 36](https://user-images.githubusercontent.com/4435815/156191008-2c5478ed-0b09-4f1c-863d-836db97c469d.png)

**Comment by xwolfde** [comment]
Leider können keine Preview-Grafiken mehr von PDFs erstellt werden.
Daher wird, wenn keine Grafik für das PDf hochgeladen wurde, das Fallbackbild genutzt.

**Comment by cassandre** [comment]
Wo kann man denn für ein PDF ein Preview-Bild hochladen, das dann in den Suchergebnissen angezeigt würde?

**Comment by xwolfde** [comment]
Bis WP 5.2 konnte man das... Danach allerdings gab es zwei Optionen: Entweder war ein Plugin installiert, welches mit dem dafür bei dem System ebenfalls notwendigen ImageMagik eine Preview erzeugte oder man installiert ein anderes Plugin. welches das Attachment mit einem Artikelbild verknüpft.

Aktuell haben wir aber keine der Optionen mehr.
