### ISSUE TITLE
Old logo thumbnail

### ISSUE THREAD

**Issue by lukasfolle** [RRZE-Webteam/FAU-Einrichtungen#1091]
Hi,

I just noticed that the thumbnail of the WordPress template still uses the old logo.

E.g.: https://www.intern.fau.de/kommunikation-marketing-und-corporate-identity/corporate-identity/fau-logo/
`<meta property="og:image" content="https://www.fau.de/files/2019/12/FAU-Logo-Default.jpg">`

**Comment by xwolfde** [comment]
jepp.
 But this is not matter of the Theme. The Webredaktion has to change it in the preferences of their SEO-Plugin.

**Comment by lukasfolle** [comment]
Ok, in case they are aware of that..

**Comment by xwolfde** [comment]
They should :) (I also informed them yesterday in another case).
