### ISSUE TITLE
Feature Request: Prev/Next-Link bei einzelnen Beiträgen (single.php)

### ISSUE THREAD

**Issue by cassandre** [RRZE-Webteam/FAU-Einrichtungen#1096]

**Comment by xwolfde** [comment]
Würde ich nicht pauschal machen wollen, sondern über eine Customizer-Option

**Comment by xwolfde** [comment]
Im Customizer bei der Artikeldarstellung die option einbauen, dass die Prev/Next Links gezeigt werden. Wenn gesetzt (Default aufgrund Abwärtscompatibilität erstmal false), werden die Links am Ende des ARtikels eingefügt.

**Comment by wrcg** [comment]
evtl. auch über customizer eine Option einbauen, um ähnliche Artikel (gleiches Schlagwort) unten am Beitrag anzuzeigen. Oder mittels Shortcode...

**Comment by xwolfde** [comment]
Statt nur Prev/Next als Buttons wäre auch der Titel zum jeweiligen Artikel schön als Ergänzung:
Vgl. Beispiel:
![grafik](https://user-images.githubusercontent.com/1070669/200162066-5a165b5c-0fa4-4a3a-b147-4a71fd031914.png)
