### ISSUE TITLE
CSS-Problem mit Auswirkung auf Plugin FAU-Studienangebot

### ISSUE THREAD

**Issue by thenickless** [RRZE-Webteam/FAU-Einrichtungen#1098]
Die Tabelle ist zu schmal auf https://www.fau.de/education/studienangebot/internationale-studiengaenge/rein-englischsprachige-studiengaenge/ (Kunde: https://mattermost.rrze.fau.de/fau-webmaster/pl/ncuf5z8bm3r6zjmfxu4yxoxmxr)

Grund ist 
`            <div class="span9">
`
in [fau-studienangebot /includes/shortcodes/studiengaenge.php Z.99](https://github.com/RRZE-Webteam/fau-studienangebot/blob/7a9bf5a642b9431c40b032ab072da81725d2c7b3/includes/shortcodes/studiengaenge.php#L99)

und

styles.css in fau-einrichtungen:

`.span9{width:538px}`

bzw u.U. auch _oldgrid.scss Z.131:
```
@media (min-width: $screen-sm)  {
	.span9 {
		width: 538px;
	}	
}

```

**Comment by xwolfde** [comment]
fixed
