### ISSUE TITLE
Vertikale Navigation: Einrückung fehlt

### ISSUE THREAD

**Issue by cassandre** [RRZE-Webteam/FAU-Einrichtungen#1101]
Ab der sechsten Ebene werden die Menüpunkte in der Seiten-Navigation links nicht mehr eingerückt.
![Bildschirmfoto 2022-03-24 um 11 18 21](https://user-images.githubusercontent.com/4435815/159895377-943391c2-9c4f-4f1a-9914-60079041ff9d.png)

Beispiel: https://www.datascience.nat.fau.eu/research/groups/pde/members/jens-habermann/

**Comment by xwolfde** [comment]
Ja. irgendwann muss halt Schluss sein...

Das obigen Beispiel ist aber fies, weil die Unterelemente kurz sind.  Sehe die Titel auf der dritten Ebene, die viel länger sind. Stell dir vor, man macht da noch eine Einrückung und dann ist statt so einem kurzen Titel so ein langes Textmonster.

Es wäre sicher eine Überlegung, ob man nochmal eine tiefere Einrückung macht.
Aber früher oder später (in diesem Fall hat es immerhin 7 Jahre gedauert bis jemand deswegen ankam), wird auch jemand ankommen, der selbst das  nicht ausreichend findet.
Besser wäre doch, an die Wurzel des Problems zu gehen und die ist: Muss das wirklich hierachisch so tief im Baum sein?

**Comment by xwolfde** [comment]
Hab noch zwei Ebenen eingefügt, so dass bis zur 6. Ebene Einrückungen erfolgen. Das sollte aber wirklich reichen.
