### ISSUE TITLE
Erweiterte Menüeigenschaften ergänzen: Aria-Label

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/FAU-Einrichtungen#1102]
Wird vermutlich nicht besonders oft gebraucht, aber es wäre praktisch, die Möglichkeit zu haben, einem Menüpunkt ein Aria-Label zu geben. In den Erweiterten Menüeigenschaften gibt es ja bereits die Möglichkeit einen anderen Title zu vergeben, aber das hilft in diesem Fall leider nicht.

Beispiel:
Menüpunkt Kontakt in der Meta-Navigation-Top auf fau.de. Hier gibt es einen Accessibility-Fehler sobald z.B. in der Sidebar oder dem linken Menü ebenfalls ein Kontakt-Link auftaucht.

**Comment by xwolfde** [comment]
Bist du sicher, dass es tatsächlich ein ARIA-Fehler ist, der da gemeldet wird?

In den Tests von mir war das ein potentieller Fehler, wenn der Titel redundant zu einem Link im Text war. Hier muss man dann die Meldung einmalig manuell überprüfen. Wenn dann im Kontext auch ein Link ist der mit dem selben Linktext dasselbe Ziel hat, dann muss man nur bestätigen, dass beide Linktexte auf dasselbe Ziel leiten. Wenn man das getan hat, wird das als korrekt markiert.

**Comment by AndiWebred** [comment]
Ich bin mir nicht sicher, ob das "Aria-Label" die beste Lösung ist. Aber ich bin mir sicher, dass es da ein Accessibility-Problem gibt. Sowas hier zum Beispiel: https://www.fau.de/research/welcome-centre-fuer-internationale-promovierende-und-wissenschaftler/

Da hast du "Kontakt" oben in der Meta-Navigation und du hast "Kontakt" links im Menü.

Klar, ich kann auch die H1 von der Seite "Kontakt" anpassen, dann hab ich das Problem zumindest auf dieser Seite nicht. Klappt aber nicht immer so unkompliziert.

Also keine Ahnung, ob sich das echt lohnt mit dem Aria-Label, oder ob man halt in solchen Fällen besser irgendwie die H1 anpassen sollte.

**Comment by xwolfde** [comment]
Ich glaub das ARIA-Label wird hier keine Lösung sein; Denn was sollte darin stehen?

Besser wäre es glaub ich in diesem speziellen Fall, dass wir bei einer Subnavigation mal schauen ob wir den Kontext der Navigation automatisiert in das ARIA-Label reintun.

Sprich: Oben wäre kein ARIA-Label, weil "Kontakt" sich ja auf die ganze SIte bezieht.
Der Link in der Subnav ist aber dem Kontext "Welcome Centre für internationale Forschende" klar zugeordnet. Daher könnte man dort ein ARIA-Label " Research / Welcome Centre für internationale Forschende  / Kontakt" denken.
Hm... aber das würde dann beim Vorlesen der Seite auch sch..lecht sein. Und wenn das dann später 4te oder 5te Ebene wäre, wäre noch schlimmer.


Ich werde das nochmal durchdenken & recherchieren, wie wir das optimaler lösen.

**Comment by AndiWebred** [comment]
Und wenn im ARIA-Label nur die Ebene darüber steht? Wäre zumindest im obigen Beispiel eine Lösung.

**Comment by xwolfde** [comment]
Nach einigen Recherchen:

Eigentlich ist ein ARIA-Label oder ein Labeledby nicht notwendig, da hier der Kontext erfüllt ist: https://www.w3.org/WAI/WCAG21/Techniques/html/H81

Wie da auch steht, sind leider noch nicht alle Screenreader und Testtools schlau genug, den bestehenden Kontext in einer Liste mit zum Link zu berücksichtigen.
Die Alternative wäre nun, dass wir automatisch bei jedem Link ein aria-lavel setzen, der vom Text erst den Titel des höheren Listitems/Links beinhalten, gefolgt von einem trennzeichen und dann den eigenen Linktext.

Also bei der obigen URL bei dem Link zu "Kontakt" dann so:

`aria-label="Welcome Centre für internationale Forschende: Kontakt"`

Nur leider können wir beim AUfbau des Menüs nicht wissen, welche anderen Links auf der Seite mit selben Namen sind.
Ergo müssten wir bei allen Links des NavMenüs und des Hauptmenüs  bei jedem EIntrag den Aria-Eintrag generieren lassen, der den Titel der jeweils höheren Ebene zeigt.
Das wäre automatisch möglich. Und es wäre valide. Das Testtool wäre glücklich.


Aber der Mensch, der sich das ganze vorlesen lassen würde, würde ein Rappel kriegen, weil der redundante Titel des Kontextes jedesmal von neuem vorgelesen wird.


Ergo: Eine Automatik, die bei mehrstufigen Navigationselementen die Aria-Label anlegt, ist nicht sinnvoll.

Daher ist dein ursprünglicher Vorschlag doch der sinnvollste: Ein optionales Feld für Seiten, bei der man ein Aria Label eingeben könnte.
Alternativ wäre es denkbar, den vorhandenen Eintrag aus dem Untertitel zu nehmen. Aber auch dies würde ich eher ausschliessen, da man diesen ja eher für inhaltliche Aussagen nutzen möchte. Ausserdem wird es Seiten geben, wo man den Untertitel nicht anzeigen wollte, aber für den Aria bräuchte.

Von daher wäre mein Lösungsvorschlag: Ein neues optional befüllbares EIngabefeld Aria-Label für Seiten unter der Box Seiten-Eigenschaften.

**Comment by xwolfde** [comment]
In der nächsten Version wird ein EIngabefeld ARIA Label in den Seiteneigenschaften bereitstehen, weldhes optional befüllt werden kann.
