### ISSUE TITLE
Bildlinks: Option für statische Darstellung

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#1104]
Statt eines Sliders soll es auch möglich sein, die Bilder rein statisch darzustellen, wie im folgenden Beispiel einer anderen Website:

![grafik](https://user-images.githubusercontent.com/1070669/160843041-c4d2a218-30d6-4cd5-a1f0-ba1278e75f1e.png)

**Comment by lukasniebler** [comment]
Die Version ohne Slider oben finde ich schick.

## Noch ergänzend zu Bildlinks:

Im Backend kann man für Logos das Format "300 x 150" wählen. Dadurch dachte ich, dass die Box dann auch 300x150 ausfällt, in der das Logo ausgegeben wird.

Allerdings erhalten Bildlinks wohl immer die vollen 300 x 300 px als Logobox, wodurch der Abstand zwischen der Paginierung und Content sehr überdimensioniert wirkt.

<img width="1635" alt="Bildschirmfoto 2022-05-24 um 08 56 10" src="https://user-images.githubusercontent.com/58593037/169967875-9675ecbf-1f27-4f57-a007-b5e2e036a5d5.png">


Kommt natürlich immer auch auf das Logo an. Aber da finde ich es fast passender, wenn man dann ggf. einfach eine andere Höhe im Dropdown der Startseite auswählen kann. (z.B. 300 x 300 - Ich glaub 150x150 quadratisch gibts auch schon als Alternative)

<img width="1512" alt="Bildschirmfoto 2022-05-24 um 09 00 57" src="https://user-images.githubusercontent.com/58593037/169968730-5c55d76b-3229-4a12-98a1-a27b5f907b0e.png">
Screen Zum Vergleich mit nur 150 px höhe. 


Aktuell finde ich die Animation ziemlich "schnell". Die Pause könnte man fast verdoppeln - Zumindest in meinen Augen.

Beispiel von
https://www.muster-lehrstuhl.wordpress.rrze.fau.de/

**Comment by lukasniebler** [comment]
Es besteht der Kundenwunsch, dass man die Paginierung unter den Bildlinks ausblenden kann.

🎫 http://go.fau.de/9sw92

**Comment by xwolfde** [comment]
Das kann man schon alles machen (Dots abschalten, etc). Dann verwendet man aber den Shortcode und nicht die im Design vorbelegte Oben/Unten-Bildlinkliste.

Wir könnten im Customizer eine Option hinterlegen, welches die Darstellung der Bildlinks der unten/oben-Attribute der Pages global für die Website festlegt. Dann würden diese Optionen aber überall gelten.

**Comment by xwolfde** [comment]
in der nächsten version
