### ISSUE TITLE
Links in Safari werden je nach Browserbreite unterschiedlich dick unterstrichen

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1105]
Vermutlich ein Browser Issue?

In Safari werden Linkunterstreichungen unterschiedlich dick dargestellt.
Je nach Fensterbreite variieren die dick/schmal unterstrichenen Elemente.

https://www.wordpress.rrze.fau.de/tutorials/schnelleinstieg/vorbereitungen/

![Bildschirmfoto 2022-04-04 um 10 35 18](https://user-images.githubusercontent.com/58593037/161505944-16190dc3-5237-4d3b-a82a-71f003e5f783.png)
![Bildschirmfoto 2022-04-04 um 10 35 31](https://user-images.githubusercontent.com/58593037/161505985-2cdbac55-c9b3-4553-812f-9365bf03f694.png)

**Comment by xwolfde** [comment]
Wäre es nicht einfacher, die 3 Safari-Nutzer ausfindig zu machen und sie durch geeignete Druckmittel der IT-Admins freiwillig auf auf Firefox zu zwingen? ;) 
(Disclaimer: Das war ein Scherz)

**Comment by xwolfde** [comment]
Der Safari verkleinert hier die Font. Und damit auch die Höhen.
Hab es durch -webkit-Eigenschaften entschärft:
    -webkit-font-smooth: antialiased;
    -webkit-text-size-adjust: 100%;
