### ISSUE TITLE
Template Startseite Fakultät | Optional statischen content ermöglichen

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1106]
🎫 http://go.fau.de/9smk0

Von Kundenseite gab es den Wunsch, dass man den Slider des Templates Startseite Fakultät in Zukunft auch in Kombination mit statischen Texten auf der Startseite nutzen kann.

**Comment by xwolfde** [comment]
Aufgrund der Abwärtskompatibilität wird dies nur möglich sein, wenn man vorher im Customizer einschaltet, dass man den Content auch anzeigen möchte.

Zu finden unter: 
_Customizer-> Templates ->  Startseite: Inhalt zeigen_ 

Ab der Version 2.1.
Issue auf "Für Doku" umgestellt.
