### ISSUE TITLE
Abstand nach Videoeinbindung durch RRZE Video zu Text

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1109]
Der Abstand nach Videoeinbindungen zu Textelementen und Listen / Definistionslisten sollte noch etwas erhöht werden.

<img width="486" alt="Bildschirmfoto 2022-04-11 um 13 58 14" src="https://user-images.githubusercontent.com/58593037/162734759-9a28d0c9-a2e8-49bb-9038-371590063006.png">
<img width="486" alt="Bildschirmfoto 2022-04-11 um 13 58 29" src="https://user-images.githubusercontent.com/58593037/162734795-b176e501-d5d3-4089-922a-949b8559fcf4.png">

**Comment by xwolfde** [comment]
Eigentlich in RRZE-Video und in FAU-oEmbed vorzunehmen, aber kann im Theme individuell angepasst werden.

**Comment by xwolfde** [comment]
In der 2.1 werden die Abstände oben und unten angepasst sein und oben 1/3 und unten 1/2 des Gridgutters(30px) sein.
