### ISSUE TITLE
Zeitverzögerter Menüwechsel gewünscht

### ISSUE THREAD

**Issue by endv02** [RRZE-Webteam/FAU-Einrichtungen#111]
Von einem Kunden wurde der Wunsch geäußert, beim Wechsel der Hauptmenüpunkte bei mouseover das Menü erst einen Ticken zeitverzögert zu wechseln, damit das Menü nicht bereits wechselt bei dem Versuch, einen Untermenüpunkt zu erreichen. Wäre bei sehr vielen Anwendern das Problem und würde sich durch eine leichte Zeitverzögerung evtl. einfach beheben lassen, ohne dass es die sonstige Navigation beeinflusst.

**Comment by xwolfde** [comment]
Es gibt aber auch Wünsche von Usern, die sich gar kein Delay beim Aufklappen wünschen... Und nun?

**Comment by xwolfde** [comment]
Auch nach längeren Nachdenken sehe ich da mehr Nachteile als Vorteile. Es wird genug leute geben, die das hauptmenü schnell benutzen wollen und sauer darüber sein werden, jedes mal warten zu müssen.
