### ISSUE TITLE
Social media Icons (1. Widgetspalte) sind nicht centered

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1110]
Die Social Media Icons in der 1. Widget-Spalte sind nicht centered?

<img width="2079" alt="Bildschirmfoto 2022-04-13 um 13 34 03" src="https://user-images.githubusercontent.com/58593037/163171846-1c0e8150-68fa-429f-b4a8-dab5aaa4d35c.png">

https://www.muster-lehrstuhl.wordpress.rrze.fau.de

In: Safari

**Comment by xwolfde** [comment]
Das soll so..

Die Spalte ist dann nicht gecentert, wenn es rechts davon keine anderen Spalten/Widgets gibt.
