### ISSUE TITLE
Responsive-Lösung für kleine Bilder mit align left oder right

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/FAU-Einrichtungen#1113]
Bilder in Beiträgen und auf Seiten werden von Redakteuren oft mit einer festen Größe von z.B. 300x200 ausgeben (Auswahl der mittleren Größe, z.B. linksbündig). Auf bestimmten Bildschirmgrößen sind diese Bilder dann aber unscharf.  

Beispiel: https://www.fau.de/2022/02/news/individuelle-fluchtgeschichten-im-portrait/

**Comment by xwolfde** [comment]
Müssen wir konzeptionell durchdenken.
Einerseits legt ein Autor eine kleine Größe fest. Andererseits wollen oder müssen wir das dann doch bei verschiedenen Auflösungen ignorieren. 

Die Frage ist daher, ob es nicht besser wäre, die Option zur kleinen Darstellung oder zumindest kleine Darstellungen unter 600px  (halbe Breite bei STandardbildschirmgröße 1200px) aus der Auswahl zu nehmen, damit dies garnicht erst versucht wird.

Alternativer Ansatz: 
Die Auswahl setzt nicht width/height der img-Attribute und wählt dann fest das kleine Bild aus sondern wir sezen damit nur CSS-Anweisungen, die aber abhängig von der tatsächlichen Screenresolution die Bild darstellen. Bei der Bildsrc /Sizes werden dann aber alle Größen angegeben, inkl. dem Original.

**Comment by FitoreGashi** [comment]
Ich befürchte, ich verstehe das nicht richtig. Ich kann eine Funktion erstellen mit der wir das auswählen von Medium oder Thumbnail größen im Editor nicht erlauben. Vielleicht könnt Ihr mir das erleutern.

**Comment by lukasniebler** [comment]
@AndiWebred Ist das weiterhin ein Problem mit den Auflösungen oder kann das Issue geschlossen werden? Ansonsten ist mir bis jetzt nicht aufgefallen, dass es Probleme mit den Auflösungen / gibt.

Hast du Beispiele, falls das Problem weiter bei euch auftritt? Ansonsten würde ich das Issue schließen.

**Comment by AndiWebred** [comment]
Ein Beispiel findet ihr auf dieser Seite: https://www.fau.de/2022/02/news/individuelle-fluchtgeschichten-im-portrait/
Die Bilder, die ich händisch einpflege (also nicht das Beitragsbild) sind bei mir unscharf. Wenn ich draufklicke und das Bild öffne, ist es aber scharf.

**Comment by lukasniebler** [comment]
@AndiWebred Hast du für Fitore vielleicht noch einen Screenshot und welchen Browser du benutzt hast? 

(Ideal wärs natürlich noch, falls du die Auflösung vom Browserfenster mitschicken kannst, falls es nur bei bestimmten Breakpoints auftritt).

(Bei mir in Safari / Firefox sieht es tatsächlich scharf aus – Aber meine Augen sind auch nicht die besten…)

**Comment by FitoreGashi** [comment]
Bei mir in Safari / Chrome sieht auch scharf aus.

**Comment by FitoreGashi** [comment]
<img width="876" alt="Screenshot 2023-02-16 at 09 15 17" src="https://user-images.githubusercontent.com/101202370/219306861-77e3c35f-4af9-44c8-920a-576f56ff3a27.png">
<img width="1100" alt="Screenshot 2023-02-16 at 09 14 50" src="https://user-images.githubusercontent.com/101202370/219306871-0a06bb70-2575-4ad1-9360-e1383d6a9d49.png">

**Comment by AndiWebred** [comment]
Firefox, Auflösung: 1920 x 1080

![Screenshot 2023-02-16 at 09-17-33 Individuelle Fluchtgeschichten im Portrait Friedrich-Alexander-Universität Erlangen-Nürnberg](https://user-images.githubusercontent.com/53909165/219307128-b78a2b4b-cc5f-4290-8833-6ef803c3efb1.png)

**Comment by FitoreGashi** [comment]
Ich kann es nicht reproduzieren, vielleicht kann @lukasniebler  es auch überprüfen, wenn er dasselbe hat

so sieht es bei firefox bei mir aus:
<img width="1434" alt="Screenshot 2023-02-16 at 09 24 03" src="https://user-images.githubusercontent.com/101202370/219308563-e4fa81fd-7aad-488c-b8ed-cffcf40ccc5a.png">

**Comment by AndiWebred** [comment]
in der mattermost diskussion zu dem thema ging es unter anderem um obejct-fix und krumme aspect-ratio zahlen. vielleicht hilft das? 
lukas: das war eine diskussion am 29. april bis 2. mai. vielleicht verstehst du das besser? (habs mit schlagwort "unscharf" gefunden).

**Comment by AndiWebred** [comment]
ok. vielleicht hilft noch dieses beispiel, es geht um das bild im text links.
scharf: https://www.fau.eu/2022/04/28/news/research/can-planting-a-tree-tackle-climate-change/
unscharf: https://www.fau.de/2022/04/news/wissenschaft/kann-baeume-pflanzen-den-klimawandel-bekaempfen/

der unterschied: 
scharf: [caption id="attachment_2282668" align="alignleft" width="300"]<a href="https://www.fau.de/files/2022/04/ipcc_6_ohne.png"><img class="size-medium wp-image-2282668" src="https://www.fau.de/files/2022/04/ipcc_6_ohne.png" alt="" width="300" height="199" /></a> Image: Colourbox/FAU[/caption]
unscharf: [caption id="attachment_2282668" align="alignleft" width="300"]<a href="https://www.fau.de/files/2022/04/ipcc_6_ohne.png"><img class="wp-image-2282668 size-medium" src="https://www.fau.de/files/2022/04/ipcc_6_ohne-300x199.png" alt="Waldbrand" width="300" height="199" /></a> Foto: Colourbox/FAU[/caption]

bei "unscharf" steht also "300x199.png" in der source am ende der url, bei "scharf" habe ich diesen abschnitt das rausgenommen.

**Comment by FitoreGashi** [comment]
Ok, jetzt verstehe ich das Problem, weil WordPress verschiedene Größen für Bilder erstellt, die an verschiedenen Orten verwendet werden können. Es hängt von der Größe ab, die Sie zuerst wählen.

Meine Idee, die Option Miniaturansicht und mittlere Größe für den Editor zu entfernen, ermöglicht es Benutzern nicht, verkleinerte Bilder auszuwählen, aber sie können die Breiten- und Höhenparameter auswählen.

hier habe ich ein beispiel für verschiedene verwendungen von bildgrößen gemacht und das gleiche width-attribut gesetzt:
http://sites.chillibrain.de/2023/02/16/2224946/

**Comment by AndiWebred** [comment]
Genau! das untere bild ist bei mir scharf, die anderen sind unscharf.

**Comment by FitoreGashi** [comment]
<img width="302" alt="Screenshot 2023-02-16 at 09 55 32" src="https://user-images.githubusercontent.com/101202370/219316308-beee800d-b6e1-4cd9-b966-7113523b6b03.png">
