### ISSUE TITLE
Automatisch generiertes Seitenlogo verschwindet nach wechseln des Themes

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1114]
Nach einem Wechsel von Med. Fak. Theme auf Nat-Fak Theme verschwand das automatisch generierte Seitenlogo und das Bild des Seitenbanners.

Selbst wenn man im Customizer die Website-Informationen aktualisiert, erscheint das Logo nicht wieder.
Meine Vermutung: Man muss händisch ein statisches Logo einfügen und wieder entfernen, bevor das automatische Seitenlogo wieder erscheint.

Zum Vergleich: Der Seitenbanner kann zwar wieder über den Customizer ohne Probleme eingefügt werden.

https://www.muster-lehrstuhl.wordpress.rrze.fau.de
<img width="1824" alt="Bildschirmfoto 2022-05-19 um 07 38 21" src="https://user-images.githubusercontent.com/58593037/169218154-654d9307-7ac0-46dd-9b55-36dd02679962.png">

**Comment by FitoreGashi** [comment]
Ich kann das Problem anscheinend nicht Reproduzieren. Können Sie mir weitere Details senden, wenn dies immer noch ein Problem ist

**Comment by lukasniebler** [comment]
Ich glaube das Problem ist inzwischen bereits gelöst. Das Issue kann also geschlossen werden.
