### ISSUE TITLE
Zoom-Links in Kalendereinträgen sind nicht als "Link" identifizierbar

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1116]
Die Zoom-Links in Kalendereinträgen sind nicht als Link erkennbar. Vgl. Siteimprove im verknüpften GitHub Issue.

https://github.com/RRZE-Webteam/FAU-Einrichtungen/issues/1130

**Comment by xwolfde** [comment]
dup
