### ISSUE TITLE
Bilder in der Sidebar

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Einrichtungen#112]
Wir haben es immer wieder mit Logos, Bildmarken und Titeln von Printveröffentlichungen zu tun, die auf Webseiten platziert werden sollen. Meist passt dieses Kontextmaterial nicht in den Inhalt, am Ende der Seite ist es auch eher lieblos platziert und daher gab es immer mal eine Platzierung im Freitextfeld der Sidebar, was so natürlich nicht vorgesehen ist (html-Link). Diese Ausnahmen schaffen wir nun wieder Stück für Stück ab, aber gäbe es vielleicht eine Alternative?

Der Bedarf wäre: Platzierung eines Bildes (Hochformat, Empfehlung: 2:3) in der Sidebar, auswählbar aus Medienbibliothek. Das Bild kann dann z.B. der Screenshot eines Broschürencovers sein, beim Klick darauf öffnet sich die Broschüre als PDF. Das muss dann aber kenntlich gemacht werden, idealerweise automatisch. Wir weisen bislang per Text darauf hin).

Kennt ihr den Bedarf von anderen Klienten? Seht ihr den Bedarf/ist das schon auf einer Todo-Liste evtl.? Der Vorteil wäre meiner Meinung nach, dass man ohne Beeinträchtigung des Contents Kontextinformationen über Bilder geben kann.

**Comment by xwolfde** [comment]
Der Bedarf ist an einzelnen Stellen vorhanden und bekannt, aber wir wollen das nicht durch eine deutlich  sichtbare neue Funktion fördern. Denn dadurch würden auch Leute darauf aiufmerksam werden, die das wirklich nicht brauchen und dort Unsinn reintun werden.
 
Wenn ein Site-Admin das tatsächlich braucht und möchte, muss er die WYSIWYG-Funktion für die Texteingabefelder bewusst und selbstständig aktivieren.
![screenshot-themeoptions-wysiwyg-sidebar](https://cloud.githubusercontent.com/assets/1070669/17588623/9ad96676-5fd0-11e6-92f8-786c51265f55.jpg)

Der Admin, der dies freischaltet, weiß hoffentlich was er oder sie damit mit erlaubt und welche Folgen das haben kann.

Eine Alternative möglichkeit, dass man dort nicht über den WYSIWYG sondern über eine Funktion wie die der Bildlinks nur Bilder aus einer Liste aktivieren kann, wäre sicher auch denkbar. Aber dafür gab es bislang nicht genug Anfragen.

**Comment by wrkb** [comment]
Danke, das hilft uns schon mal weiter. Wenn es aus Designsicht sonst keine Bedenken gibt (Bilder liefen eigentlich ganz gut), dann werden wir evtl. die Ausnahme nutzen. Aber die Einwände gegen das (ZUV-)globale Freischalten des WYSIWYG leuchten ein, wir überlegen mal, ob wir das wollen. :+1:
