### ISSUE TITLE
Apple Touch Icon - Transparentes Icon sorgt für schlechte Darstellung auf iOS-Geräten

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1120]
## Problem

Wenn man auf einem iOS-Gerät eine FAU-Seite über Share > Als Lesezeichen zum Home-Bildschirm hinzufügen ablegt,
sieht das FAU-Icon ungünstig aus, da das transparente Favicon gleichzeitig als Apple Touch Icon (App-Icon) eingesetzt wird.

## Lösung

Einbinden eines apple-touch-icons ohne transparenten Hintergrund. https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html

## Screenshots
![IMG_2381](https://user-images.githubusercontent.com/58593037/171618256-fda588c7-7c3c-4e28-8337-2252fe46b946.PNG)
![IMG_2382](https://user-images.githubusercontent.com/58593037/171618381-2ffcce9a-2ae4-4c3a-bb50-39e408a803e6.PNG)

## Zum Vergleich auch GitHub mit der gleichen Lösung.
Bei GitHub gibt es sowohl ein transparentes Favicon als auch ein nicht transparentes Apple Touch Icon

![IMG_2384](https://user-images.githubusercontent.com/58593037/171618573-96196039-87f8-4c9b-8a20-c99c7f200622.PNG)
<img width="747" alt="Bildschirmfoto 2022-06-02 um 13 26 17" src="https://user-images.githubusercontent.com/58593037/171619291-9dd11726-4fcd-443c-b14f-9611f79d83ee.png">

**Comment by xwolfde** [comment]
Wird in der nächsten Release sein
