### ISSUE TITLE
Darstellung mobile - Blogroll Beitragsbilder

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1132]
Auf Mobile werden seit einiger Zeit die Beitragsbilder mit einem deutlicheren Abstand zum linken/rechten Rand dargestellt.

Wenn ich mich richtig erinnere, dann gingen die Beitragsbilder auf Mobile (anfangs) von Rand zu Rand. Das war deutlich schöner.

Blogroll jetzt:
https://www.wordpress.rrze.fau.de
<img width="734" alt="Bildschirmfoto 2022-06-15 um 16 11 30" src="https://user-images.githubusercontent.com/58593037/173848561-8ce7a0c6-2e8f-4994-8c95-92711eca9425.png">

Zum Vergleich Elements custom-news Shortcode
https://www.wordpress.rrze.fau.de/wordpress-tipp-der-woche/
<img width="734" alt="Bildschirmfoto 2022-06-15 um 16 12 09" src="https://user-images.githubusercontent.com/58593037/173848734-8558ebf5-696a-40bc-970d-ebaf98d39e5a.png">

(Am besten sieht in meinen Augen eine Darstellung ohne Abstand links/rechts neben den Beitrasgsbildern aus. Oder gibts die Funktion schon und ich muss es noch aktivieren?)

**Comment by xwolfde** [comment]
Bitte mach ein Gegencheck auf zentral.tindu (bzw. nachher auf beta). Gerade genau dieses problem hab ich heute mEn behoben.
