### ISSUE TITLE
Formularfelder auf Mobile ermöglichen horizontales Scrollen

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1136]
Auf https://www.beta.wordpress.rrze.fau.de/texte/formularfelder/ ist es möglich, horizontal zu scrollen.

(iPhone 6/7/8 plus -iOS Mobile 14.0)

<img width="767" alt="Bildschirmfoto 2022-06-20 um 09 22 34" src="https://user-images.githubusercontent.com/58593037/174546922-81eedcb1-d438-42de-b8e6-48869e11e9dc.png">

**Comment by xwolfde** [comment]
In der nächsten Version gefixt
