### ISSUE TITLE
Beitragsbilder haben sehr schmalen Abstand links und rechts auf Mobile

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1137]
https://www.beta.wordpress.rrze.fau.de/2020/04/29/update-fau-person-3-0/

iPhone 12 Safari 14.0

Ist nörgeln auf hohem Niveau. Aber aktuell haben Beitragsbilder noch einen sehr schmalen Rand auf mobile.
Bei Smartphones mit infinity-Edge sieht es ohne den Abstand noch besser aus.

![IMG_585A0D778D8C-1](https://user-images.githubusercontent.com/58593037/174549097-105175aa-e02b-4fa1-a7ff-09a93945fcb9.jpeg)

**Comment by xwolfde** [comment]
fixed in der nächsten Version
