### ISSUE TITLE
Optimierungen im Print CSS - Seitenumbrüche definieren

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Einrichtungen#1141]
Seitenumbrüche

•	Bei Kontakteinträgen
Bei Kontakteinträgen wird der Eintrag nicht ordentlich getrennt: (Bei Accordions wird ein Seitenumbruch erstellt, wenn der Inhalt des neuen Accordions nicht mehr auf die Seite passt.)
 
![image](https://user-images.githubusercontent.com/9526974/174996291-6b5f7185-23a7-4891-acc1-0d9f1c3fb9db.png)

•	Alert nicht auf zwei Seiten aufteilen
![image](https://user-images.githubusercontent.com/9526974/174996310-3c39c8a5-a378-4d78-a39e-7398901af353.png)

**Comment by wrcg** [comment]
Fußnoten zu Buttons
![image](https://user-images.githubusercontent.com/9526974/174996414-d50d153a-68f0-4b73-99a3-f9498b7addd5.png)

 
https://www.beta.wordpress.rrze.fau.de/plugins/elements/elements-buttons/
Die Fußnote bei den Buttons wäre aus meiner Sicht als hochgestellte Zahl direkt am Buttontext schöner

**Comment by wrcg** [comment]
Tabellen
![image](https://user-images.githubusercontent.com/9526974/174996466-98374b95-7013-43a1-b80c-a3bdfa20e163.png)

https://www.beta.wordpress.rrze.fau.de/texte/tabellen/
Tabellenüberschrift überlappt

**Comment by wrcg** [comment]
Spalten

Spalten bitte immer als Spalten darstellen
Mit [two_columns_one] funktioniert’s nicht (https://www.beta.wordpress.rrze.fau.de/theme-shortcodes/spalten/), 
mit [columns number=2] funktioniert’s… (https://www.beta.wordpress.rrze.fau.de/elements-neue-funktionen-testseite/ )
Beispiel mit columns number=2

 
![image](https://user-images.githubusercontent.com/9526974/174996673-da03267f-ba2a-4ddd-9fca-09e0deaca5c9.png)

Beispiel 1 mit [two-columns…]
![image](https://user-images.githubusercontent.com/9526974/174996641-b555c0d1-0fc5-4faf-9cc2-1864995f87fc.png)

 
Beispiel 2 mit [two-columns…]
 
![image](https://user-images.githubusercontent.com/9526974/174996602-97c798f8-75f8-4826-8cbb-02d92f771772.png)

https://www.beta.wordpress.rrze.fau.de/?page_id=2222813 dreispaltig (und auch zweispaltig) mit Bildern und Links wird nicht schön gedruckt
Screen:  
![image](https://user-images.githubusercontent.com/9526974/174996574-84f859f4-1d63-4879-ac3c-9817d6bf8f69.png)

https://www.beta.wordpress.rrze.fau.de/?page_id=2222813

•	Vier Spalten im Newsportal/Blogroll
 
![image](https://user-images.githubusercontent.com/9526974/174996553-e16a0b94-aada-4318-bdd7-c0b5df5b5f46.png)

Screen:  

![image](https://user-images.githubusercontent.com/9526974/174996542-e66b8471-39de-4e72-a37f-f2efa5b19303.png)

**Comment by wrcg** [comment]
Slider
Inhalte vom Slider werden nicht gedruckt - > ist aus meiner Sicht aber nicht unbedingt nötig
![image](https://user-images.githubusercontent.com/9526974/174996778-f26851c3-56e1-4126-b6e8-7174b0dd0e2f.png)

 
https://www.beta.wordpress.rrze.fau.de/?page_id=2222792

**Comment by wrcg** [comment]
Abstände 
•	bei „abgeschnittenen“ Bildern sind zu groß
https://www.beta.wordpress.rrze.fau.de/?page_id=2222792
![image](https://user-images.githubusercontent.com/9526974/174996842-e254fb33-75ee-4fac-b823-c1b7ee558be8.png)

 
•	bei Buttons und Bild zu klein
https://www.beta.wordpress.rrze.fau.de/?page_id=2222792
 
![image](https://user-images.githubusercontent.com/9526974/174996830-50c839e3-0fbb-43be-8ae2-38b407b7f63b.png)

**Comment by xwolfde** [comment]
Ähm... alles was andere Plugins (hier Elements mit Accordion, Buttons, etc) machen, kann die Druckausgabe des Themes nicht beeinflussen und muss ggf. in den Plugins nachoptimiert werden. Daher dort rein.

**Comment by xwolfde** [comment]
two_columns_one gibt es nicht mehr in Elements Plugin

**Comment by wrcg** [comment]
> two_columns_one gibt es nicht mehr in Elements Plugin. Muss die Beispielseiten erneuern...
wird aber noch über den Editor so auf Seiten eingefügt und deswegen eigentlich fast überall verwendet...
<img width="394" alt="image" src="https://user-images.githubusercontent.com/9526974/174999174-dd14bed8-f16b-4b90-b922-1fb09a5452e7.png">

**Comment by cassandre** [comment]
Es gibt es schon noch aus Abwärtskompatibilitätsgründen. Ich würde aber das aktuellere `[columns number=3][column span=2][/column][column span=1][/column][/columns]` empfehlen, das auf https://www.wordpress.rrze.fau.de/plugins/inhaltsseiten-mit-funktionen-erweitern/elements/ beschrieben ist.

Den Editor hatte ich in der Tat nicht mehr auf dem Schirm, das werde ich natürlich noch anpassen. Danke für den Hinweis!

**Comment by xwolfde** [comment]
Hm... bei einigen der o.g. Dinge müsste man mal ausführlicher rein. Z.B. das Umbruch-Verhalten bei einem [alert].
Ich kenne ein paar Seiten, wo ein Alert auch länger ist und ein Umbruch fest davor optisch negativ wäre.


Aber wenn ich es richtig sehe, sind das obige alles eher Sache, wo man noch optisch verschönern kann, aber, abgesehen von der Tableheader (#1143) nichts was irgendwo kritisch ist, oder?

**Comment by wrcg** [comment]
> Hm... bei einigen der o.g. Dinge müsste man mal ausführlicher rein. Z.B. das Umbruch-Verhalten bei einem [alert]. Ich kenne ein paar Seiten, wo ein Alert auch länger ist und ein Umbruch fest davor optisch negativ wäre.
> 
> Aber wenn ich es richtig sehe, sind das obige alles eher Sache, wo man noch optisch verschönern kann, aber, abgesehen von der Tableheader (#1143) nichts was irgendwo kritisch ist, oder?

ja, bei den Spalten wäre es aber tatsächlich wichtig, dass es auch mit den alten Shortcodes kompatibel ist! Seitenumbrüche kann man diskutieren, bei Kontakten wäre ein Seitenumbruch m.E. nicht nur optisch sinnvoll.
