### ISSUE TITLE
Bildlinks / Kooperationspartner verschwinden

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1153]
Details unter: 🎫 http://go.fau.de/9s2x4

ich habe eben das Bild eines Bildlinks aktualisiert und anschließend festgestellt, dass keiner der Bildlinks bzw. die durchlaufenden Banner (inkl. 26 Logos) nicht mehr auf unseren entsprechenden Seiten angezeigt werden (https://www.forum-v.de/ & https://www.forum-v.de/kooperationspartner/)... (weitere Details im Helpdesk)

**Comment by xwolfde** [comment]
Das ist ein "besonderes" Problem, welches hiermit der speziellen Website zusammenhängt:

Bei der o.g. Website wurden keine Beiträge geschrieben. Stattdessen werden auf der Startseite die Artikel händisch in Contentbereich geschrieben.
Die Anzeige der Bildlinks beruhte aber darauf, dass es eine Post-Id gab. Da es aber keine erolgreiche Schleife über die Beiträge gab, lieferte diesen keinen Wert und daher auch keine Bildlinks.

Positiv: Problem wird nur für diesen speziellen Fall auftreten, wo noch niemand einen Artikel schrieb (bzw. wo es keine sichtb aren Artikel gibt).
Negativ: Muss trotzdem auch diesen Ausnahmefall berücksichtigen.

**Comment by xwolfde** [comment]
Ok, der Grund ist ein ganz anderer: Keine der Bildlinks hat eine URL!
Es werden nur Bildlinks gezeigt, wenn es Links sind. Sind es aber nicht.

**Comment by xwolfde** [comment]
Das hat sich in der Tat geändert zur Version 2.0. Vgl. https://github.com/RRZE-Webteam/FAU-Einrichtungen/blob/v2.0/functions/posttype_imagelink.php 

Es wurde im Zuge anderer Änderungen an den Bildlinks eingebaut dass diese nur erscheinen, wenn eine URL angegeben ist.
Ich werde das mal teilrückändern, so dass ein Bildlink auch erscheint, wenn es keine URL hat.

**Comment by xwolfde** [comment]
Im nächsten Update drin.
