### ISSUE TITLE
Darstellung Personenkarten Portraits bei Linkhover

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1155]
Beispiel unter:

https://www.wordpress.rrze.fau.de/plugins/neue-inhaltstypen-erstellen/fau-person/eine-kontaktuebersicht-erstellen-und-anlegen/kontaktuebersicht-musterseite-a/

Bilder zeigen blaue Linie links + Rechts die beim hover breiter wird. FAU Person betreffend
<img width="242" alt="Bildschirmfoto 2022-06-28 um 13 19 15" src="https://user-images.githubusercontent.com/58593037/176166368-16805718-eece-471d-9ae2-bfdef59d1833.png">
.

**Comment by xwolfde** [comment]
Im nächsten Update gefixt
