### ISSUE TITLE
Metanavigation oben: Link zu Mein Campus in Campo umändern?

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1156]
## Issue
Seit der Umstellung von MeinCampus auf Campo vor runde 10 Tage führt der alte Link zu MeinCampus (campus.fau.de) automatisch zu Campo (campo.fau.de) – allerdings ist die Beschriftung in der Kopfzeile der Homepage noch die alte (sh. Screenshot) und ich finde in Wordpresse keine Möglichkeit zur Anpassung (zumindest nicht bei den Menüs und beim Theme) und meine mich dunkel zu erinnern, dass diese Link-Leiste auf ziemlich fix im Theme eingebaut ist. Könnten Sie das bitte anpassen („Campo“ statt „Mein Campus“) 

--------------------------------
Nähere Details und Screenshots im zugehörigen Helpdesk-Ticket: 🎫 http://go.fau.de/9s3hw

**Comment by xwolfde** [comment]
Jupp, das war ein guter Hinweis. Wird in der nächsten Version umgesetzt sein.
