### ISSUE TITLE
Bildlinks werden quadratisch dargestellt und gehen über Rahmen hinaus.

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1161]
## Issue
Bildlinks werden zu groß dargestellt.
<img width="1122" alt="Bildschirmfoto 2022-07-04 um 09 41 36" src="https://user-images.githubusercontent.com/58593037/177106350-b46c719e-66b1-439b-804d-68d67b9282b9.png">

Einstellung wohl: 150 x 150 Bildlinks 7 Logos

Beispiel: 🖥 https://www.maot.studium.fau.de 

Verknüpfter Helpdesk-Fall: 🎫 http://go.fau.de/9s4hm

**Comment by xwolfde** [comment]
Update: Nein, ist nicht mittig: 
<img width="1287" alt="grafik" src="https://user-images.githubusercontent.com/1070669/177177412-78591c33-9bcf-47ec-ad62-4f8dd5766a6c.png">

**Comment by xwolfde** [comment]
Sicherheitshalber bekommt der Slider eine maximale Höhe bei den Bildern.

**Comment by xwolfde** [comment]
im Update verbessert
