### ISSUE TITLE
Portalmenüs - Darstellung von langen Einträgen in Kombination mit kurzen Einträgen

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1163]
## Issue:
Wenn lange und kurze Einträge in Portalmenüs eingebunden werden, dann stört der Rahmen unter den kürzeren Einträgen, da eine weitere leere "Box" entsteht.

## Screenshot
![image](https://user-images.githubusercontent.com/58593037/177521152-bdc8f94c-0020-43d8-9503-5c20e4a84089.png)

## Helpdesk
Verknüpfter Helpdesk-Fall unter 🎫 http://go.fau.de/9s5a5

**Comment by lukasniebler** [comment]
https://www.cbi.tf.fau.eu/beispiel-seite/cbi/sustainability/
https://www.fau.eu/fau/history-and-successes/
https://www.fau.eu/education/degree-programmes/

**Comment by MManthey** [comment]
Wurde indirekt durch ein Issue aus Milestone 2.2 erledigt. 
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/43784820/217539648-af629f59-9ccc-46b3-b6dd-ea6fc5179dda.png">
