### ISSUE TITLE
Startseite Fakultät: Anleser auf der Bühne werden ersetzt

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Einrichtungen#117]
Wenn ich auf der Startseite einen Text eingebe und das Template "Startseite Fakultät" auswähle, wird auf der Bühne statt des Anlesers aus den gefeatureten Blogartikeln der Seitentext angegeben.

Screenshot Texteingabe:
![bildschirmfoto 2016-08-15 um 14 00 40](https://cloud.githubusercontent.com/assets/11296947/17663969/ee339c2e-62f0-11e6-8a44-4ee57213da36.png)

Screenshot Ergebnis:
![bildschirmfoto 2016-08-15 um 13 59 08](https://cloud.githubusercontent.com/assets/11296947/17663973/f9aefb02-62f0-11e6-875b-564517da78d0.png)

**Comment by xwolfde** [comment]
Was ist wenn du mehr als ein Artikel hast. Welcher Anleser steht dann im anderen Artikel?

**Comment by AstridSemm** [comment]
Es sind zwei Artikel; die Überschrift und das Hintergrundbild wechseln, der Text nicht.

**Comment by xwolfde** [comment]
Ich behaupte mal: Das soll so sein.
Weil ansonsten hätte der Text bei dem template ja gar keine Wirkung und wäre nirgends sichtbar...

**Comment by AstridSemm** [comment]
GENAU! Das ist ja auch das, was wir die ganze Zeit schon für das Fakultätstheme schulen!

**Comment by xwolfde** [comment]
Hm... vielleicht sollten wir genau das ändern.
Also: Wenn Text eingegeben wird, dann wird er da auch unter der Hero und über den Artikeln angezeigt.

Und in dem Zuige dann fixen, daß der Default-teasertext aus dem Seiteninhalt kommt.

**Comment by xwolfde** [comment]
Sollte mit dem Update kein Problem mehr sein
