### ISSUE TITLE
Galerie Vorschaubilder abgeschnitten

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1172]
Bilder werden anscheinend abgeschnitten beim zufügen einer Galerie.

Aufgetreten in Firefox.

https://www.wordpress.rrze.fau.de/grundlagen/testseite/
<img width="1184" alt="Bildschirmfoto 2022-07-11 um 13 40 55" src="https://user-images.githubusercontent.com/58593037/178256528-429e7de4-0dee-4f65-b833-53eb9b5716f8.png">

**Comment by xwolfde** [comment]
WTF?! Das hatte ich doch erst repariert?

**Comment by xwolfde** [comment]
Im nächsten Fix repariert
