### ISSUE TITLE
Quadratische Bildlinks ohne horizontalen Weißraum ermöglichen

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1174]
Es gab Webseiten, die Ihre Bildlinks & Logomarken von Partnern im Seitenverhältnis 1:1 eingestellt haben. Das hatte auch funktioniert.

Mit der neuen Darstellung haben die Bildlinks allerdings viel Weißraum in der horizontalen.

Wunsch von Kundenseite: Eine Möglichkeit, dass auch quadratische Bildlinks (Seitenverhältnis 1:1)
ideal dargestellt werden können, ohne den zusätzlichen Weißraum in horizontaler Richtung.

Nähere Informationen & Beispiel unter 🎫 http://go.fau.de/9s63d

**Comment by xwolfde** [comment]
Das geht schon (siehe Auswahl Bildformat), wozu auch das Quadratische gehört), aber da liegt ein Bug vor, der in der Testphase leider übersehen wurde :(

![grafik](https://user-images.githubusercontent.com/1070669/178698891-8f18aad5-73fb-4468-85dd-c38f54d153d5.png)

**Comment by xwolfde** [comment]
Nochmal prüfen
