### ISSUE TITLE
Portalmenü bei max-width von 480px: Zusätzlicher margin-bottom für eine angenehmere Liste

### ISSUE THREAD

**Issue by csw-** [RRZE-Webteam/FAU-Einrichtungen#118]
Durch den zusätzlichen margin würde man die Liste etwas nutzerfreundlicher machen (man klickt ja dann doch manchmal daneben wenn die so eng aneinander stehen). Zum anderen würde die Liste nicht so stark am Footer kleben.

Siehe Bilder für den Vergleich ohne und mit margin-bottom (15px):

![subpage-menu_1](https://cloud.githubusercontent.com/assets/6545158/17702077/bc24ff20-63cc-11e6-9651-03eec704a9d6.png)
![subpage-menu_2](https://cloud.githubusercontent.com/assets/6545158/17702084/bf98047c-63cc-11e6-9a26-5a6123179210.png)

**Comment by xwolfde** [comment]
Ja. Der Footer ist eh derzeit noch Murks positioniert und da muss in Zusammenhang mit #82 sowieso nochmal nachgebessert werden.

**Comment by xwolfde** [comment]
hab den #content mal 10 pixel mehr gegeben
Im Dev Zweig drin
