### ISSUE TITLE
Galerien funktionieren nicht in Akkordeonfächern

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1181]
Beispielseite:

https://www.wordpress.rrze.fau.de/beispielseite/#collapse_0
Die Galerie wird in Akkordeonfächern nicht dargestellt.

**Comment by xwolfde** [comment]
Ja, wir hatten das Problem schonmal. Und keine Lösung gefunden.

Das Slick-Skript versucht anhand des verfügbaren Platzes den notwendigen Raum zu berechnen.
Wenn aber nun der Raum wegem dem geschlossenen Akkordion zu uns, dann schlägt hier das Skript wohl fehl, denn es kann den Platz nicht korrekt berechnen.

Aktuell kann ich nur sagen: Galerien (mit dem Slider) funktionieren mit der aktuellen Technik nicht in Akkordions.
