### ISSUE TITLE
Vorschlag: Bilder nebeneinander platzieren (große Bildschirme)

### ISSUE THREAD

**Issue by lagerlit** [RRZE-Webteam/FAU-Einrichtungen#1188]
Hallo. 
ich würde in Beiträgen mit tollem Bildmaterial gern nebenenander einbinden können. Beispiel hier: https://www.research-in-bavaria.de/paleobiology Zwei Bilder nebenander (auf großen Bildschirmen - auf kleinen entsprechen umgebrochen).

**Comment by xwolfde** [comment]
Du meinst so?:
http://zentral.tindu.rrze.uni-erlangen.de/inhaltselemente/bilder/bilder-mit-elements-nebeneinander/

**Comment by xwolfde** [comment]
Ah jetzt ja. Ja, das haben wir in Teilen ja schonmal als Feature Requests aufgenommen: #910 
Dabei insbesondere die Out of the Box Darstellung.


Mit versetzter Darstellung, meinst du wirklich so etwas:
![grafik](https://user-images.githubusercontent.com/1070669/180819412-cc0a556c-9dea-47f0-b970-198a8d69f1e8.png)

(Das erschien mir wie ein Fehler...)

WIllst du da ein optische Treppe haben?

**Comment by lagerlit** [comment]
Ja genau, out-of-box steht schon im Feature Request #910 (da geht es ums Artikelbild). 

Bilder im Beitrag:
Die optische Treppe mit den verschiedenen Bildgräößen gefällt mir, weil es den Beitrag optisch auflockert (statt ein langer Block Text + Bilder wie hier https://www.fau.de/?p=2286465&preview=true).

**Comment by xwolfde** [comment]
Ich sehe auf dem Preview-Beitrag aber nirgends eine Treppe... ? Kannst du davon ein Screenshot machen und hier reinkopieren?

**Comment by lagerlit** [comment]
Missverständnis: die Treppe hast du gescreenshottet oben, die ist hier https://www.research-in-bavaria.de/paleobiology

KEINE Treppe bzw. langer Schlauch/Block hier: https://www.fau.de/?p=2286465&preview=true (hab versucht das mit den Spalten aufzulockern aber das sieht irgendwie nix aus)

**Comment by xwolfde** [comment]
Urg. Ok, wenn ihr das so wollt...


Notice self:
Die machen es auf der Seite mit einem

```
.ribcontent_imagexx_container {
   grid-template-columns: 2fr 3fr;
   display: grid;
   grid-gap: 1.5rem;
}
.ribcontent_imagexx_container figure:last-child {
  padding-top: 4.5rem;
}
```
