### ISSUE TITLE
"role" befindet sich nicht im erforderlichen Kontext

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/FAU-Einrichtungen#1189]
Siteimprove gibt mir für immer mehr Seiten den Fehler aus, dass "role" sich nicht im erforderlichen Kontext befindände. Es handelt sich dabei in erster Linie um das Dropdown-Menü des Meldungsarchives.
Zum Beispiel hier: https://www.fau.de/2022/07/news/leute/ein-dankeschoen-an-die-mitarbeiterinnen-und-mitarbeiter-dienstjubilaeen-an-der-fau/

Auch für unsere Formulare mit "Contact-Form" taucht der Fehler auf. Ich schau mal, ob ich das in diesen Fällen selber lösen kann.

**Comment by xwolfde** [comment]
Ich prüf das mal mit dem Select-Feld.

Wegen: Der Fehler bei "Contact-Form"  kann nicht unsererseits gelöst werden. Das ist ein Problem am Plugin. Vgl #948

**Comment by xwolfde** [comment]
Bug kommt aus der nativen WordPress-Funktion bei dem Widgets für den Artikel-Archiv. Ist als erstmal kein Theme-Fehler, sondern etwas was auch bei anderen Themes auftritt.
Die Auswahl ist in keinem Form und wird überdies auch noch mit JS gemacht.

Das Problem trifft neben dem Archiv-Widget auch den Kategorie-Widget. Beide dann, wenn man dort anhakt, dass man die Liste als Drop-Down haben will.

Lösung erstmal als Workaround:
- Drop Down Liste abschalten
- Bei zu langen Listen dann stattdessen von Hand eine Subliste machen. ggf. eine Verlinking zu Seiten, die den Custom-News-Shortcode beinhalten und dort auf das Jahr oder Monate filtern.

**Comment by AndiWebred** [comment]
Problem scheint bei den Dropdowns behoben, jedenfalls wird mir da von Siteimprove nix mehr angezeigt.
