### ISSUE TITLE
Mobile Navigation: Suche und Sprachwechsler in das Flyout-Menu übernehmen?

### ISSUE THREAD

**Issue by csw-** [RRZE-Webteam/FAU-Einrichtungen#119]
Wurde schon einmal darüber gesprochen wie die Suche und der Sprachwechsler in der mobilen Version umgesetzt wird? 
Wie wäre es denn, wenn man die beiden Funktionen in das Flyout-Menü mit aufnehmen würde? 
Im Moment sehen die beiden Funktionen etwas verloren aus, wenn in dem Meta-Bereich sonst keine weiteren Buttons sind. (siehe Bild)

![top-meta-mobile](https://cloud.githubusercontent.com/assets/6545158/17704764/530ef07c-63d6-11e6-959d-ea408da9f0fb.png)

**Comment by xwolfde** [comment]
Wäre ich offen für. 
Gibt es auch von anderen Meinungen dazu?
@RRZE-Webteam/fau-webmaster 
@RRZE-Webteam/fau-webredaktion

**Comment by wrkb** [comment]
Die aktuelle Lösung ist wohl tatsächlich etwas untypisch. Für mich okay. Die Suche draußen lassen (wie z.B. bei skatedeluxe.de) wäre sinnvoll, wenn sie mal perfekt funktioniert, bis dahin...

**Comment by csw-** [comment]
Die Suche auf die ganze Breite zu legen hört sich auch nicht schlecht an. Allerdings, mit dem blauen Hintergrund wirkt es dann vielleicht auch etwas zu "mächtig".

**Comment by xwolfde** [comment]
Auch Thema der Deisgn-Runde

**Comment by xwolfde** [comment]
Haben uns für anderen Entwurf entschieden. Zu sehen auf BETA
