### ISSUE TITLE
Custom News haben einen Link-Hover-Effekt

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1190]
Die Custom-News Ausgabe hat anscheinend den klassischen Link-Hover Effekt seit v.2.1 übernommen, was dazu führt, dass die Beiträge einen kleinen Strich neben dem Beitragsbild ausgeben:
<img width="697" alt="Bildschirmfoto 2022-07-25 um 15 46 48" src="https://user-images.githubusercontent.com/58593037/180792601-8925d0b5-4226-4300-9926-36a40147e451.png">

Beispielseite:
https://www.wordpress.rrze.fau.de/wordpress-tipp-der-woche/

**Comment by xwolfde** [comment]
fixed in der nächsten version
