### ISSUE TITLE
Aria-Label-Feld bei den Seiteneigenschaften funktioniert noch nicht (?)

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/FAU-Einrichtungen#1197]
Das neue Feld "Aria-Label" bei den Seiteneigenschaften hat noch nicht den gewünschten Effekt (siehe Ticket 1102 https://github.com/RRZE-Webteam/FAU-Einrichtungen/issues/1102).

Siteimprove zeigt für Seiten, die zum Beispiel "Kontakt" heißen immer noch einen Fehler an, Screenreader lesen das Aria-Label noch nicht aus.

Beispiel hier: https://www.fau.de/research/welcome-centre-fuer-internationale-promovierende-und-wissenschaftler/kontakt/

(Ich schließe nicht aus, dass der Fehler bei mir liegt, finde ihn aber nicht)

**Comment by xwolfde** [comment]
Fehler liegt bei dem Entwickler - hab was in der Umsetzung übersehen.

**Comment by xwolfde** [comment]
in 2.3

**Comment by xwolfde** [comment]
Nochmal nachprüfen

**Comment by xwolfde** [comment]
im dev
