### ISSUE TITLE
Portalindex vs. Portalseite

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/FAU-Einrichtungen#1198]
Gibt es da noch einen Unterschied? Früher war bei Portalindex der Zwischenbalken zwischen Content und Portalmenü weg, aber jetzt ist er wieder da wie bei der Portalseite. Soll das so sein oder kann der weg? Wenn er gewollt ist, dann müssen wir unsere Überschriften, die wir über dem Portalmenü auf den Portalindexseiten hatten, entfernen...

**Comment by cibsell** [comment]
![Screenshot 2022-08-12 at 08-19-44 Angebote für Schülerinnen, Schüler und Lehrkräfte › Naturwissenschaftliche Fakultät](https://user-images.githubusercontent.com/8234890/184296205-d6dffe5a-4b4f-47ba-b850-95422ee1def6.png)

**Comment by xwolfde** [comment]
Die Portalindex hat die Sidebar inline, also als Teil des Contentbereiches,  während die Portalseite die Sidebar dvaon getrennt hat. Der Unterschied ist also eher dann da, wenn es eine Sidebar gibt.

Aber du hast recht, dass es heutzutage eigentlich nicht mehr notwendig ist.

Allerdings können wir eine der beiden nicht einfach löschen: Wenn wir eine der beiden Templates wgenehmen, dann ist dieses auch bei alten Websites, die auf dieses Template gestellt waren, weg. Und die Seite damit broken.
Daher müssen wir erstmal damit leben. Ggf. kann man in Rahmen der Umbauten zu dem Block Eidtor aber da nochmal ran.
