### ISSUE TITLE
target-Setzung von Links aus TinyMCE Editor

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#1199]
Miut Hilfe des TinyMCE Editors ist es (leider wieder?) möglich, zu definieren, dass der LInkziel in einem neuen Fenster geöffnet wird. Überdies auch noch nicht mit einem Namen für das Target, sondern über "_self", so dass jeder Klick ein neues Fenster eröffnet.

Dies sollte so nicht sein und das Theme sollte so etwas nicht unterstützen, da dies ein Eingriff in die UX des Users darstellt und auch einen Bruch der Barrierefreiheit.

Daher prüfen, ob man mit einem Filter den Link nachträglich, nach der Bearbeitung eines Editors, wieder sanitizen kann.

**Comment by xwolfde** [comment]
Info zur Umsetzung:

via CSS ist die Darstellung der Option zum Link-Target im WP Editor bereits unsichtbar.
vgl: src/sass/backend/_ui.scss

Trotzdem gibt es Altfälle, wo Leute das target bereits gesetzt hatten.

**Comment by xwolfde** [comment]
Fast... Bitte gar kein target-Attribut setzen Also auch kein _self im replacement. Jedes unnötige gesparte Byte ist gut ;)

**Comment by FitoreGashi** [comment]
Sie haben Recht, wir können es so effizienter machen
`function fau_change_link_targets($content) {
    $pattern = '/<a(.*?)href=[\'"](.*?)[\'"](.*?)(target=[\'"](.*?)[\'"])?(.*?)>/i';
    $replacement = '<a$1href="$2"$3$6>';
    $content = preg_replace($pattern, $replacement, $content);
    return $content;
}
add_filter('the_content', 'fau_change_link_targets');`
