### ISSUE TITLE
Sprachwechsler: Textfarbe des searchsubmit-Buttons an Fakultätsfarbe anpassen

### ISSUE THREAD

**Issue by csw-** [RRZE-Webteam/FAU-Einrichtungen#120]
Die Textfarbe beim Sprachwechsler ist ja (bereits) abhängig von der Fakultät, das sollte beim Suche-Button dann eigentlich ebenfalls der Fall sein. 
Oder andersrum, stets in FAU-Blau - zumindest sollte es hier einheitlich sein. 

![searchsubmit](https://cloud.githubusercontent.com/assets/6545158/17705040/448ad4b6-63d7-11e6-91d4-da4c2ab2b6a6.png)

**Comment by xwolfde** [comment]
Da würde ich eher den Sprachwechsel auf das Default tun. 
Andererseits ist das ein Navigations-Element via der Hamburger. Also ist die Farbe nicht ganz verkehrt...

Die Farbe des Buttons bei Suchen möchte ich wiederum nicht ändern: Dies wiederrum wegen der Farblogik: Wenn wir den Button ändern müssten, wir auch den Hintergrund der EIngabe ändern. Und das sieht dann gerade bei der roten Farben doof aus (das hatte ich schonmal durchgetestet)

**Comment by xwolfde** [comment]
Die Farbe wird in der nächsten Version vereinheitlicht sein (Standard Blau).

Die beschäftigung mit dem problem und auch die Arbeiten an der Perforamnceoptimierung brachten mich aber auf ein anderes Problem: Das Sprachsymbol (der Globus) ist als solches diskutabel. Dazu werde ich aber noch ein Extra Issue aufmachen.

**Comment by xwolfde** [comment]
Ref #177
