### ISSUE TITLE
Widgetbereich Seiten-Sidebar - Darstellung von Bildern weicht ab

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1200]
<img width="263" alt="Bildschirmfoto 2022-08-17 um 11 35 01" src="https://user-images.githubusercontent.com/58593037/185086231-eeab
<img width="263" alt="Bildschirmfoto 2022-08-17 um 11 35 31" src="https://user-images.githubusercontent.com/58593037/185086324-985a0e02-06a2-47c5-8d8b-8bc8df8538f7.png">
2acf-82a8-48fe-a473-f5074368e976.png">

Wenn man Bilder als Widgetblock für den Bereich Seiten-Sidebar hinterlegt, dann weicht die Darstellung auf Archiv- und Inhaltsseiten ab (unschöner Rand).

nähere Details und URLs unter 🎫 http://go.fau.de/9te14

-

**Comment by MManthey** [comment]
Dies konnte nicht reproduziert werden.
