### ISSUE TITLE
Pre-Tags in der Dokumentation

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1201]
<img width="794" alt="Bildschirmfoto 2022-08-17 um 14 53 00" src="https://user-images.githubusercontent.com/58593037/185136324-7acb9ed3-4d50-41dc-8704-358bfc58b708.png">

Seit einiger Zeit werden die < pre >...< /pre >-Tags in Kombination mit [[Shortcodes]] unleserlich dargestellt.
Codebeispiele werden mit Einrückung dargestellt. Macht das lesen deutlich schwerer.

Betrifft die komplette Anleitungsseite Wordpress.rrze.fau.de

Bsp.: https://www.wordpress.rrze.fau.de/plugins/inhaltsseiten-mit-funktionen-erweitern/elements/accordion/?preview_id=4928&preview_nonce=91edd2e8fc&_thumbnail_id=20926&preview=true#collapse_14

**Comment by xwolfde** [comment]
Optik prüfen und verbessern.

**Comment by lukasniebler** [comment]
Ok es war mein Anwendungsfehler (und der meiner Vorgänger). Damit es nicht zerschossen aussieht hätte ich es einfach mit <br>-Tags und ohne Leerzeichen schreiben müssen. Sry für die Umstände 🙏 

## So hätte es im Textmodus hinterlegt werden müssen... 
<img width="754" alt="Bildschirm­foto 2023-01-27 um 08 28 58" src="https://user-images.githubusercontent.com/58593037/215031776-13ab7e52-b424-4b24-90e5-e4584552a693.png">
<img width="1125" alt="Bildschirm­foto 2023-01-27 um 08 30 02" src="https://user-images.githubusercontent.com/58593037/215031924-69303149-b7a6-4d31-a354-7f781654ddfb.png">

## So war es hinterlegt...
![image](https://user-images.githubusercontent.com/58593037/215032059-64628bd8-9ba9-4937-9c5e-e262b7f0c592.png)
![image](https://user-images.githubusercontent.com/58593037/215032072-59eee52c-f466-4b37-a431-3412abe4816d.png)
