### ISSUE TITLE
Layout archive-person.php ist fehlerhaft

### ISSUE THREAD

**Issue by thenickless** [RRZE-Webteam/FAU-Einrichtungen#1204]
Beispiel: https://www.mr-physik.med.fau.de/person

/themes/FAU-Einrichtungen/archive-person.php wird vom Plugin FAU-Person geladen (siehe   templates.php -> include_archive_template()   

```
if ($theme_file = locate_template(array('archive-person.php'))) {
                $template_path = $theme_file;
            }

```

**Comment by xwolfde** [comment]
Können wir es einfach entfernen und die Ausgabe dem Plugin überlassen?

**Comment by thenickless** [comment]
Ja.

Im FAU-Person existiert ein Template für FAU-Themes und im neuen RRZE-Contact ebenso.

` if (Helper::isFAUTheme()) {
                    $template_path = dirname($this->pluginFile) . '/includes/Templates/archive-person-fau-theme.php';
                }
                else {
                    $template_path = dirname($this->pluginFile) . '/includes/Templates/archive-person.php';
                }
                `
                
  `if (Helper::isFAUTheme()) {
                    $template_path = dirname($this->pluginFile) . '/templates//archive-contact-fau-theme.php';
                } else {
                    $template_path = dirname($this->pluginFile) . '/templates//archive-contact.php';
                }
`

**Comment by xwolfde** [comment]
ok, also ist das jetzige obsolet und kann einfach raus. Geht das jederzeit oder müssen wir das mit einem Update der Plugins timen?
