### ISSUE TITLE
Übersetzung des Seitentitels (Multilang)

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1206]
Ich legs dir hier noch als Erinnerung ab. Falls du es erst nach deiner Rückkehr schaffst informier ich die Kundin:

Hinweis: Damit das Multilang-Plugin den Website-Namen ('blogname') und die Beschreibung ('blogdescription') übersetzen kann, ist es wichtig, dass bei Verwendung der Funktion get_bloginfo($show, $filter) für die Anzeige der Parameter $filter mit dem Wert 'display' verwendet wird. ZB.:

get_bloginfo('name', 'display')
get_bloginfo('description', 'display')

🎫 http://go.fau.de/9toh3

**Comment by lukasniebler** [comment]
🎫 http://go.fau.de/9uc3y

## Weitere Feature-Wünsche zwecks Übersetzung im Theme:

- [ ] Seitentite
- [ ] Logomarke?
- [ ] Brotkrümennavigation?
- [ ] Adresse im Footer

**Comment by lukasniebler** [comment]
🎫 http://go.fau.de/9ug2a

**Comment by xwolfde** [comment]
im dev
