### ISSUE TITLE
Buttons in Sidebar auf Inhaltsseiten sind zu schmal?

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1207]
<img width="494" alt="Bildschirmfoto 2022-10-21 um 16 11 56" src="https://user-images.githubusercontent.com/58593037/197216453-276b7e19-b3b5-4aab-8716-340e28869323.png">

Evtl. folgende Zeile auslöser?:
<img width="240" alt="Bildschirmfoto 2022-10-21 um 16 12 41" src="https://user-images.githubusercontent.com/58593037/197216609-2498506a-6d1a-4068-9da3-cb0733caca07.png">

URL für Beispiel: https://www.wordpress.rrze.fau.de/tutorials/schnelleinstieg/was-ist-wordpress/

**Comment by xwolfde** [comment]
Ich verstehe nicht ganz? Sieht doch gut aus?

**Comment by lukasniebler** [comment]
<img width="437" alt="Bildschirmfoto 2022-10-25 um 14 02 39" src="https://user-images.githubusercontent.com/58593037/197768185-4f8f67fd-88b1-4f14-a1f5-7fe61a089bc2.png">

Als Referenz auf der Startseite. Da sieht der Button anders aus. (Klickfläche ist größer).

**Comment by lukasniebler** [comment]
Einheitlich wär schick
