### ISSUE TITLE
Sprachwechsler: margin-right erhöhen / Button "klebt" am rechten Bildschirmrand

### ISSUE THREAD

**Issue by csw-** [RRZE-Webteam/FAU-Einrichtungen#121]
Zumindest in der mobilen Ansicht (ab max-width: 767px) müsste der margin-right der Klasse ".mlp_language_box" erhöht/gesetzt werden, damit der Button nicht direkt am rechten Bildschirmrand sitzt.
Der margin sollte dabei so gesetzt werden dass es rechts bündig mit dem Flyout-Toggle liegt (ich meine das wären 15px). 
Alternativ könnte man wohl auch ein padding an die top-meta-Leiste anbringen und bei der Suche und dem Sprachwechsler ein margin-left setzen. Dann könnte man das bei weiteren Funktionen die dort untergebracht werden zumindest den Abstand einheitlich lassen. Denn nun hat die Suche ein margin-right von 20px und der Sprachwechsler hätte eines von 15px. 

![pull-right](https://cloud.githubusercontent.com/assets/6545158/17705683/82832f78-63d9-11e6-81a5-482a8a2cae87.png)

**Comment by xwolfde** [comment]
Guter Vorschlag. Magst du es nicht gleich als Merge-Request in den Dev-Zweig reintun?

**Comment by xwolfde** [comment]
in der nächsten version umgesetzt
