### ISSUE TITLE
Kundenfeedback zu Abständen

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1212]
Von Kundenseite kam über Helpdesk das Feedback:

"Bei 1 und 3 finde ich den Abstand zu groß. Bei 2 das Menü dagegen etwas zu klein."
![image](https://user-images.githubusercontent.com/58593037/200301543-02d4665f-8647-48ef-afbd-de5b06fa8f5f.png)

**Comment by xwolfde** [comment]
Naja, was soll man da sagen: Genau diese Stellen wurden so zusammen mit anderen genauso durchdiskutiert. Nicht jedem gefällt es so, wie es ist.

**Comment by xwolfde** [comment]
Wie abgestimmt: Hätte große Auswirkungen auf viele Websites. Kann nicht übers Knie gebrochen werden. Daher nicht.
