### ISSUE TITLE
Hauptmenü - Menüelemente der Ebene 2 sind nicht mehr sichtbar unterstrichen

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1213]
# Problem:
Unterpunkte werden schlecht als solche erkannt. Vorher gab es einen dezenten Trenner, der seit einiger Zeit fehlt.

## Ist-Zustand:
![image](https://user-images.githubusercontent.com/58593037/200828885-9353c06a-8a1c-401c-91e5-72e4581a429d.png)

## Vor kurzem:
![image](https://user-images.githubusercontent.com/58593037/200829489-6f7e99f5-4d17-4d34-b7b3-d3c660c4a099.png)

## Zusatzinfos:
![image](https://user-images.githubusercontent.com/58593037/200829298-b57eda41-9ae4-4a66-b36d-8fedebb7a59b.png)

Gemeldet über Helpdesk: 🎫 http://go.fau.de/9t0-p

**Comment by xwolfde** [comment]
Wir haben dies in #1083 bereits schonmal aufgeführt gehabt als Todo. Daher in diesen Zusammenhang angehen.
