### ISSUE TITLE
Prominente Kontaktmöglichkeit einbauen

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Einrichtungen#1214]
Idee wurde an uns herangetragen, dass man rechts einen ausklappbaren Kontaktbutton hat (für die wichtigsten Kontakte für Studierende):
Beispiel: 
https://www.leuphana.de/ rechts die Texte "Fragen und Antworten..." oder 
https://www.sparkasse-fuerth.de/de/home.html der Telefonicon-Button.

**Comment by xwolfde** [comment]
Das ist schon eine Komponente des Designs, die zwar nur klein erscheint, aber doch ins Gesamtkonzept passen sollte. Auch und gerade bei der Responsibilität. Einfach "rechts" an de Rand klatschen geht nicht, wenn es auf kleinen Displays dann den Platz nehmen würde (jedes Icon muss mind. 44x44px groß sein).

Kurzum: Das sollten wir uns genauer überlegen.
Hast du eine Idee, welche Inhalte das sein könnten und wo die dann herkommen würden? Die genannten Beispiele sind in der Umsetzung ja auch völlig verschieden.

**Comment by lukasniebler** [comment]
Die IU hat auch so einen Button unten rechts in der Ecke Studienberatung & Co.
https://www.iu-fernstudium.de

Zwar nicht direkt zum Thema Studienberatung aber Kundenservice Chat gibts von Nielsen Norman UX-Best practices was solche Buttons angeht:
https://www.nngroup.com/articles/chat-ux/
(Auch wenn es bei der FAU ja kein Chat wäre)

**Comment by xwolfde** [comment]
Da wir mit den Arbeiten im MAi die gestaltung umfangreich angepasst haben und damit mit den CTAs auch Kontaktmöglichkeiten hervorgehoben haben, schließe ich den Issue hiermit.
