### ISSUE TITLE
Wunsch: Einfaches Bild im Slider ohne Verlinkung

### ISSUE THREAD

**Issue by TFWebm** [RRZE-Webteam/FAU-Einrichtungen#1216]
Es waere schoen, wenn man ein einfaches Bild im Slider ohne Verlinkung verwenden koennte.

**Comment by lukasniebler** [comment]
Die TUM Fakultätsseiten benutzen Ihren Slider auch als Galerie.
https://www.cit.tum.de/cit/startseite/

Aber gute Frage, wo die Bilder dann herkommen sollen..

**Comment by xwolfde** [comment]
Ja, aber die Website bei denen verströhmt auch den Charme eines Beton-Rohbaus.

**Comment by xwolfde** [comment]
Aber Spaß beiseite. Ich würde erstmal die Milestones 2.2 und 2.3 abwarten, bis wir den neuen Slider ausgerollt haben.

Wenn hier der eigentlich Zweck der Sache nur die ist, eine optische Präsentation verschiedener Bilder zu zeigen als Startseite, dann sollten wir da vielleicht anders herangehen. Der Slider jetzt basiert ja auf Artikeln, ist eine MIni-Blogroll.
Wenn der Zweck aber der eine Bildergalerie ist, dann sollten wir auch einen anderen Ansatz bzw. eine Funktion des Startseiten-Templates dafür andenken.

**Comment by TFWebm** [comment]
> Oder geht es hier lediglich um eine Verwendung des Slides als eine Art Galerie? Wenn ja, wie sollen neben dem Bild die Inhalte textuell geliefert werden? Wo kommen die her?

> Der Slider jetzt basiert ja auf Artikeln, ist eine MIni-Blogroll. Wenn der Zweck aber der eine Bildergalerie ist, dann sollten wir auch einen anderen Ansatz bzw. eine Funktion des Startseiten-Templates dafür andenken.

Ja, der Gedanke war der einer Galerie bzw. dass man zwischen Blogroll und Galerie wechseln kann. Konkreter Anlass war die Betriebsschließung über die Feiertage und dass eine weihnachtliche Grußbotschaft zeigen wollte, ohne eben auf einen Artikel verlinken zu müssen.

Als Funktion des Templates würde natürlich Sinn machen.

**Comment by xwolfde** [comment]
Dumme Frage, aber ihr wisst schon, dass man unter den Beitragsoptionen eine URL als Ziel für den SLider geben kann und dann damit auch die Seite mit sich selbst verlinken könnte?
<img width="1064" alt="grafik" src="https://user-images.githubusercontent.com/1070669/228472603-aa90e822-e8b9-45e8-a060-ce9880a93f78.png">

Was aber zugegeben eine Userverwirrung verursachen könnte.

**Comment by xwolfde** [comment]
Durch die Option der Selbstverlinkung eines Beitrags lösbar ohne Codeänderung.
