### ISSUE TITLE
Moderne Portalmenüs mit Text

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1217]
Es wäre cool, wenn man Portalmenüs einbauen kann, die ohne Bilder auskommen aber dafür die Möglichkeit bieten, z.B. einen kurzen Text / Anleger einer Seite zu nutzen:

![image](https://user-images.githubusercontent.com/58593037/207267501-4646fae4-c056-4997-950b-85ba6d01766f.png)
https://www.muster-fakultaet.wordpress.rrze.fau.de/fakultaet/

Inspiration:
https://www.cit.tum.de/cit/school/

**Comment by xwolfde** [comment]
Ggf. Zusammenhang mit den Arbeiten zu #1163 ?

**Comment by xwolfde** [comment]
Das kann man mit den Columns bereits machen:
<img width="1954" alt="grafik" src="https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/1070669/a7d66097-c3be-483b-bbeb-8abc68125499">
