### ISSUE TITLE
Text-Widget: Keine Shortcodes mehr möglich?

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Einrichtungen#122]
Bisher konnte man in das Texteingabefeld des Text-Widgets einen Shortcode einfügen (z. B. Termine, die dann auch angezeigt wurden). Das geht jetzt nicht mehr. Warum? Das wäre eine sehr praktische Möglichkeit, den Terminkalender oder auch eine Kontaktperson auf News- und vor allem Fehler- und Suchseiten einzubinden.

**Comment by xwolfde** [comment]
wie, wo?

**Comment by AstridSemm** [comment]
![bildschirmfoto 2016-08-17 um 17 16 52](https://cloud.githubusercontent.com/assets/11296947/17764133/af79b91c-651d-11e6-906c-03040a39afcc.png)

Newsseite auf dem alfirin, zB: https://www.alfirin.test.rrze.uni-erlangen.de/category/allgemein/

**Comment by xwolfde** [comment]
In der nächsten version gefixt
