### ISSUE TITLE
Portalmenü: Zoom-Effekt beim Bildhover deaktivieren oder verbessern

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1220]
Feature request von Kundenseite: Ob man bei Portalmenüs optional den Zoom-Effekt der Bilder deaktivieren kann.

**Comment by xwolfde** [comment]
Ich nehm es als Enhancementvorschlag auf. 
Wir bräuchten dazu dann wahrscheinlich einen lokalen (für das jeweilige Menu) als auch einen globalen Parameter (für alle).

**Comment by xwolfde** [comment]
ggf. wäre auch ein blur- oder Filter auf dem Bild sinnvoll

**Comment by xwolfde** [comment]
ggf. stattdessen blue oder filter-effekt

**Comment by MManthey** [comment]
Ich habe lokale Optionen auf den Seiten...
![lokalop](https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/43784820/950fd807-836f-4cac-bd52-71cdf064e197)
und globale Optionen im Customizer...
![globalop](https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/43784820/96606458-baa8-409d-bc32-65193aa8c555)
für optionale Hovereffekte auf den Portalmenü-Thumbnails (Zoom und Blur) hinzugefügt.

Die Seiten-Option wird priorisiert.
