### ISSUE TITLE
PDF-Icons bei Dokumenten

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Einrichtungen#1221]
kurze Frage: Sollten nicht eigentlich mit Version 2.1 irgendwo wieder die Icons sichtbar sein? Ich sehe sie nicht...
Beispiele: 
https://www.fau.eu/education/application-and-enrolment/applying-for-masters-degree-programmes/#bewerbungszeitraum
https://www.intern.fau.de/personal-und-arbeitsleben/personaleinstellung/akademische-raete-auf-zeit/
(https://github.com/RRZE-Webteam/FAU-Einrichtungen/issues/1061)

**Comment by lukasniebler** [comment]
Aus 🎫 http://go.fau.de/9ubmb

![image](https://user-images.githubusercontent.com/58593037/212890211-e938e6ca-3a3b-40cd-b3b8-b33efb735ca6.png)

**Comment by xwolfde** [comment]
Das hat nichts mit dem Theme zu tun, sondern liegt an dem verwendeten Plugin Mime Type Icons https://wordpress.org/plugins/mimetypes-link-icons/. 

Leider liefert dieses Plugin veraltetes HTML und nutzt noch veraltetete Technik statt SVGs.
Da müssen wir ran, um ein neues Plugin zu besorgen, zumal obiges PLugin auch seit > 12 Monaten nicht aktualisiert wurde.
Leider fehlte es bisher an der Zeit. (Und es sieht da derzeit auch nicht gut aus).

Vielleicht könnte jemand aus eurem Team ein neues PLugin suchen mit den Requirements:
- Aktuell gepflegt
- SVG Icons über CSS
- Beachtung der Barrierefreiheit bei Icons, die eine Bedeutung tragen
- Anpassbare Farbsets, die auf unserer Farbpalette eingestellt werden können (keine bunten Icons ohne jegliche Berücksichtigung der Farbe)
