### ISSUE TITLE
Darstellungsfehler mit Sucheingabe bei RTL-Ausrichtung

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#1222]
Bei einer RTL-Ausrichtung der Website kommt es im Kopfteil zu einem Darstellungsfehler bei der Sucheingabe:

Bespiel bei der Website www.ar.bafid.fau.eu:
<img width="1722" alt="grafik" src="https://user-images.githubusercontent.com/1070669/210233628-68f6d499-3ee9-4a18-9f15-4e3414393312.png">

**Comment by FitoreGashi** [comment]
![Screenshot 2023-04-26 at 12 07 55](https://user-images.githubusercontent.com/101202370/234567734-d2b32d7f-bc3c-47e3-a1a4-3d1ce22c6436.png)

**Comment by lukasniebler** [comment]
@FitoreGashi 
Sieht gut aus. Bei der neuen eckigen Darstellung fällt später der Abstand zwischen Finden-Button und dem Suchfeld ja sowieso nicht auf, richtig?

Sollte also passen.

**Comment by FitoreGashi** [comment]
Ja, wenn wir den Border-Radiues entfernen, wird es dort kein Leerzeichen geben

**Comment by lukasniebler** [comment]
Super, dann passt es so
