### ISSUE TITLE
Hero in Header verschieben zur Standardkonformität zu WP

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#1223]
Der Hero-Bereich ist derzeit Teil des Contents, bzw. der Seitentemplates.

Da dies bei vielen Custom Post Types von Plugins Probleme macht und erzwingt dass man da dann für das Thema extra was machen muss, soll der Hero in der wp_head() wandern. 

Dabei ist bei dem Ausrollen darauf zu achten, dass die gäbngigen RRZE Plugins, die eigene FAU-Templates beinhalten, dementsprechend angepasst werden, so daß dann keine doppelte Hero erscheint.

**Comment by xwolfde** [comment]
Möglicherweise betroffene Plugins mit FAU-Theme-spezifischen Templates, die angepasst werden müssten:

- [ ] RRZE Person / RRZE Contact
- [ ] RRZE UnivIS
- [ ] RRZE FAQ
- [ ] RRZE Glossary
- [ ] RRZE Synonym

**Comment by xwolfde** [comment]
Im Theme umgesetzt. Die Plugins müssen noch angepasst werden. 

Am Besten sollte in diesen eine Überprüfung der Version statt finden. Wenn <2.3 bei der Theme Version, dann sollen die ihren modifizierten FAU-Theme Template nutzen, ansonsten den von jeden Default-Theme.

**Comment by cassandre** [comment]
Bei CPT-Archiven wird der hero-small statt hero-index angezeigt: https://www.beta.wordpress.rrze.fau.de/room/.
Kann es sein, dass in header-hero.php noch ein switch für is_archive() fehlt?

**Comment by xwolfde** [comment]
@cassandre Jein, das kann man in den Customizer einstellen, welcher Hero gezeigt wird.
Unter Customizer-> Anzeigeoptionen->Header:

<img width="404" alt="grafik" src="https://user-images.githubusercontent.com/1070669/236443071-2b85d5e1-42bf-4003-9fc8-5b67dbb23019.png">

Dort ist gerade bei beta voreingestellt, das die Standardanzeige (die schmale) verwendet wird.

**Comment by xwolfde** [comment]
@cassandre Das Problem mit dem Title im Hero sollte auch mit der neuen Version behoben sein (konkret ab 2.3.8)

**Comment by xwolfde** [comment]
Sieht IMHO gut aus. Finde keine Probleme mehr
