### ISSUE TITLE
Bildlinks funktionieren nicht im Standard-Template

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1226]
# Issue
Wenn man Bildlinks im Dropdown-Menü auswählt und einbindet, werden Sie in einem zweispaltigen Layout ausgegeben (s. Screenshot).

![image](https://user-images.githubusercontent.com/58593037/213189829-e6322412-7252-4037-80d6-31cf4e257442.png)

## Übergangslösung:
Seiten-Template auf Portalseite umstellen.

**Comment by MManthey** [comment]
Gefixt, indem ich im Template den Image-Link Bereich an das Ende des <main>-Bereichs verschoben habe.
