### ISSUE TITLE
Es wird ein Shortcode gewünscht, der "ähnliche Artikel" anzeigt.

### ISSUE THREAD

**Issue by FitoreGashi** [RRZE-Webteam/FAU-Einrichtungen#1229]

**Comment by FitoreGashi** [comment]
Ich habe den Shortcode basierend auf Tags erstellt, um den Beitrag mit denselben Tags anzuzeigen, aber im Moment ist es nur eine Liste von Titeln, wie Sie das anzeigen möchten?

**Comment by lukasniebler** [comment]
Ich glaube die Idee war, dass unter einem Beitrag optional auch ähnliche Beiträge ausgegeben werden können.

Ich finde die Lösung gut, dass zuerst Beiträge angezeigt werden, die ähnliche /dieselben Schlagwörter nutzen und ansonsten die neusten Beiträge gezeigt werden.

Werden dann automatisch unter den Beiträgen ähnliche Beiträge ausgegeben, oder muss der Nutzer händisch einen Shortcode am Beitragende hinzufügen?
Eine Customizer-Option wäre vielleicht die beste Lösung, damit es global unter allen Beiträgen ausgegeben wird?

**Comment by FitoreGashi** [comment]
Wir haben auch die Option next/prev. Ich kann den ähnlichen Beitrag auch zum Coztumizer hinzufügen, aber Ich bräuchte da noch Infos, wie viele wir anzeigen sollen, soll nur der Titel oder auch die Bilder hinzugefügt werden? Wird es eine Liste oder Grid sein? Sollen wir zuerst die Layout-Mocups machen ?

**Comment by lukasniebler** [comment]
Gute Frage. Wolfgang ist zur Zeit im Urlaub. Vielleicht sieht er aber die Frage und hat darauf eine genauere Antwort @xwolfde .
Ansonsten ist meine Meinung, dass ihr als Agentur ein gutes Gespür für das Design und eine geeignete Lösung habt. Ich würde das also erstmal offen lassen. Es kann auch gerne identisch / ähnlich aussehen, wie die Blogroll auf der Startseite.

**Comment by xwolfde** [comment]
Die Idee war/Ist: 

Bei längeren Artikeln sollen die Autioren eine Option mit einem Shortcode bekommen, um an geeigneter aber individueller Stelle eine Liste an Links zu ähnlichen Titeln auszugeben.

Für die Gestaltung in einem Kasten oder einem Accordion haben wir ja schon Elemente. Daher braucht da nivcht viel gemacht werden. Hier geht es also nur darum, ein Shortcode a la 
`[relevant-posts tag="tag1" max=5]`
anzubieten, der dann eine schlichte `<ul>`-Liste ausgibt der Artikel, die den `tag1 `haben. Wobei der aktuelle eigenen Artikel (wenn man auf einem Post ist und dieser auch ein `tag1 `hat) natürlich nicht dabei sein soll.
Bitte die Liste noch einkapseln mit einem 

```
<div class="relevant-posts">
..
</div>
```

`max=5` bedeutet: maximal 5 Artikel. Der Shortcodename `relevant-posts` ist jetzt nur aus dem Bauch heraus. Kann auch anders heißen.
