### ISSUE TITLE
Abstand zu Überschrift bei eingebundenen Kontakten recht groß

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Einrichtungen#123]
Wenn man auf der Seite einen Kontakt einbinden möchte und darüber eine Überschrift setzt, wird der Abstand recht groß.  Liegt das am Theme, am Plugin oder an beidem? Sollte jedenfalls behoben werden.
![bildschirmfoto 2016-08-17 um 17 33 13](https://cloud.githubusercontent.com/assets/11296947/17742606/fd153e9e-64a0-11e6-9319-ba75850ad230.png)

**Comment by xwolfde** [comment]
URL?

**Comment by AstridSemm** [comment]
Hier: https://kunstgeschichte.cms.rrze.uni-erlangen.de/institut/

Überschrift ist eine h3, wenn man einfach nur einen Absatz nimmt, ist's dasselbe.

**Comment by xwolfde** [comment]
gefixt in nächster Version
