### ISSUE TITLE
Es gibt der Wunsch, "Scroll-Stories" zu unterstützen

### ISSUE THREAD

**Issue by FitoreGashi** [RRZE-Webteam/FAU-Einrichtungen#1230]

**Comment by FitoreGashi** [comment]
Was meinten Sie damit wie eine Karussellfunktion für Beiträge?

**Comment by xwolfde** [comment]
Meiner Erinnerung nach wird so etwas wie dies gemeint:
https://pudding.cool/process/how-to-implement-scrollytelling/demo/scrollstory/

@AndiWebred @wrcg könnt ihr da nochmal drüber schauen. Das kam eigentlich mal von euch

**Comment by AndiWebred** [comment]
Ich glaube es ging darum, die Möglichkeit zu haben, solche Scroll-Elemente einzubauen. Also diese Scroll-Trigger, die dann zum Beispiel ein Bild oder Video verändern oder tauschen oder fixieren, während der Text dran vorbeifließt.
https://reportage.wdr.de/onkel-willi#8644
https://pitchfork.com/features/cover-story/reader/daft-punk/
https://pudding.cool/process/how-to-implement-scrollytelling/#scrollstory
