### ISSUE TITLE
Es wird gewünscht, dass man Artikel mit Infobox-Content anreichern kann. Also Boxen, mit interaktiven Inhalten oder LInks+Bild zu anderen Artikeln

### ISSUE THREAD

**Issue by FitoreGashi** [RRZE-Webteam/FAU-Einrichtungen#1231]

**Comment by FitoreGashi** [comment]
meinten Sie einen Shortcode das Infobox generiert, der zum Beispiel: 

[infobox title="Info Box Title" link="https://example.com" image="http://localhost/wp-content/uploads/2023/02/Hannah-Schreyer_rebecca-kleine-moellhoff_FAU1583-4.jpeg"]Info Box Content[/infobox]

**Comment by xwolfde** [comment]
Ich glaub diesen Issue können wir skippen und als erledigt schliessen, da wir bereits mit unserem Elements-Plugin im letzten Jahr solch ein gestaltungselement bekommen haben
