### ISSUE TITLE
Der Slider soll nicht mehr durch Schlagworte (startseite1...) gesteuert werden. Stattdessen sollen Schlagworte nur noch tatsächlich als Schlagworte Verwendung finden und nicht durch Steuerbefehle in der Liste der Schlagworte entwertet werden.

### ISSUE THREAD

**Issue by FitoreGashi** [RRZE-Webteam/FAU-Einrichtungen#1232]

**Comment by FitoreGashi** [comment]
Ich sehe das nirgendwo im Customizer, ist das immer noch ein Problem, wenn ja, können Sie es mir bitte erklären @lukasniebler @xwolfde

**Comment by lukasniebler** [comment]
@FitoreGashi Es gibt eine Einstellung im Customizer unter Anzeige Optionen > Artikelliste (Blogroll).

Wenn Nutzer einem Beitrag /Post das Schlagwort "startseite1" oder "startseite2" bzw. startseite3 gegeben haben, wurde es auf der Startseite oben gehalten. Aber ich weiß nicht, ob es auch auf den Slider Auswirkungen hat.

**Comment by FitoreGashi** [comment]
Dies hat keinerlei Auswirkungen auf den Slider

**Comment by lukasniebler** [comment]
Ich kann mich auch an kein dokumentiertes Feature erinnern, dass ein Schlagwort den Slider kontrolliert. Vielleicht einfach ein Wording Fehler von Wolfgang. Statt Slider müsste dort wohl stehen: "Die Blogroll..."

**Comment by xwolfde** [comment]
Ja, es geht um die Blogroll.
Hier gibt es den Positionierungstag.
![grafik](https://user-images.githubusercontent.com/1070669/220383004-05a5ea9f-dcfb-4d01-9efc-d1890dcf6714.png)


Das wurde auch so genutzt. Leider hat das den Nachteil entwickelt, dass die Schlagworte die eigentöich Themen-Keywords sind, nun ein Keyword bekommen, welches eine interne Steuerungsanweisung hat.Sprich: Wenn man die Schlagwort-Wolke anzeigt und als Navi nutzen möchte, dann stört diese eine Schlagwort dabei, weil der eben kein Schlagwort ist.

Daher wäre die Idee hier statt auf Schlagworte zu schauen, auf ein zusätzliches Custom Field der Posts zu schauen (ähnlich wie "sticked") statt einem Tag.
Zur Abwärtscompatibilität müsstegleichwohl auch als Fallback nach wie vor auch nach dem im Customizer eingegebenen Tag geschaut werden.

**Comment by FitoreGashi** [comment]
Ok, ich werde die QUERY ändern, um zuerst die Sticky-Posts abzurufen, als die Posts mit demselben Tag abzurufen, oder möchten Sie den Tag-Teil aus der Option entfernen? @xwolfde @lukasniebler

**Comment by FitoreGashi** [comment]
Ich werde beide Template ändern: Template Name: Startseite page-start-sub.php und Template Name: Startseite Fakultät page-start.php

**Comment by xwolfde** [comment]
Hm, was bewirkt die Umbenennung bei den vorhandenen Websites, die diealten Namen nutzten?

**Comment by FitoreGashi** [comment]
Wenn es keine Sticky-Posts gibt, funktioniert das alte Tag und zeigt die Posts an
