### ISSUE TITLE
Pfeilposition im neuen Slider

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1236]
## Kritik / Issue
In der aktuellen Version des Sliders werden die Pfeile teilweise zu weit unten angezeigt. Je nach Bildschirmgröße variiert die Pfeilposition deutlich. Man kann nicht erkennen, woran sie ausgerichtet werden.

In der Grafik kann man an A (Gelb) und B (Magenta) sehen, dass nicht klar wird, woran die Pfeile ausgerichtet sind.

### Teilproblem B
Bei verschiedenen Gerätegrößen (Mobile / Tablet / Desktop) variiert die Pfeilposition teils noch stärker. Auch hier sollte die Positionierung klar ausgerichtet sein.

## Vorschlag für das Design
Beim neuen Slider sollte die Position der Pfeil-Icons (Chevrons) so ausgerichtet sein, dass Sie idealerweise vertikal zentriert zwischen oberer blauen Boxrand und oberem Rand des Sliders sind.

Der Abstand zum oberen Rand und zur Oberkante der Textbox-Hintergrundfarbe sollte also idealerweise 50:50 sein. (Siehe C Türkis in der Grafik).
<img width="1713" alt="image" src="https://user-images.githubusercontent.com/58593037/223486937-1383e9dc-deb8-4404-8ab8-59467d781976.png">

**Comment by MManthey** [comment]
Pfeilposition nach dem Vorschlag von @lukasniebler korrigiert.

![image](https://user-images.githubusercontent.com/43784820/224738949-59aa0cf5-642c-469d-9c9c-80ba6ab82dd0.png)

![image](https://user-images.githubusercontent.com/43784820/224739337-97347c57-ff17-4bfc-ab1c-dfea4031af3f.png)

![image](https://user-images.githubusercontent.com/43784820/224739557-8c373b5f-ff0e-4d61-993d-b7ea39ba2a6b.png)

68d70ecf8d21fd3f3b8ce3a343b5a609c6acd4da

**Comment by xwolfde** [comment]
ok, passt
