### ISSUE TITLE
Pfeilgröße auf dem überarbeiteten Slider in Mobile-View

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1237]
Es gab den Wunsch, ob die Chevron-Icons (Pfeile) auf dem mobilen Slider noch leicht größer dargestellt werden können.
In Kombination mit einem weißen Hintergrund ist es ansonsten sehr schwer zu erkennen.

(Wohl vor allem auf Mobile - Tablet)

<img width="789" alt="Bildschirm­foto 2023-03-08 um 08 33 17" src="https://user-images.githubusercontent.com/58593037/223649832-49c27e73-50a6-4c9d-8723-14cefe85c1e6.png">
<img width="1104" alt="Bildschirm­foto 2023-03-07 um 08 09 50" src="https://user-images.githubusercontent.com/58593037/223650051-16341303-b010-44fb-9fb0-571e706b8e7c.png">

**Comment by xwolfde** [comment]
passt!
