### ISSUE TITLE
Darstellung Bildlinks fehlerhaft auf Beta

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1239]
<img width="1473" alt="Bildschirm­foto 2023-03-08 um 12 21 42" src="https://user-images.githubusercontent.com/58593037/223700716-84838248-e809-4d44-92b0-8252e21322ba.png">

Zu sehen auf https://www.beta.wordpress.rrze.fau.de

Getestet mit Safari

**Comment by FitoreGashi** [comment]
wie sie normalerweise aussehen sollten, soweit ich mich erinnere, haben wir an diesem Teil keine Änderungen vorgenommen, aber vielleicht haben einige Slider-CSS, die wir geändert haben, damit in Konflikt geraten, also brauchen wir das, um zu sehen, wie die normale Ansicht ist @lukasniebler

**Comment by xwolfde** [comment]
Das sind die Bildlinks ganz unten beim Template Startseite. Diese sind konfigurierbar im Customizer:

So sieht es jetztt auf Beta aus:
<img width="1953" alt="grafik" src="https://user-images.githubusercontent.com/1070669/224701405-a1c796c7-c4ab-4179-98c9-602af7370a96.png">

So sah es vor dem Update aus;

<img width="1953" alt="grafik" src="https://user-images.githubusercontent.com/1070669/224701585-b48638c6-97d8-4612-97cd-11519c35e468.png">


Für die Bildlinks muss man Bildlinks definiert haben (Images + URL) und diese dann in der STartseite oder der Seite wo sie dargestellt werden sollen, auswählen über die Metabox "Seiten-Eigenschaften":
<img width="395" alt="grafik" src="https://user-images.githubusercontent.com/1070669/224702115-e479ce4c-e83e-4bbb-a4ab-f69b484a9966.png">

**Comment by FitoreGashi** [comment]
![Screenshot 2023-03-13 at 14 39 07](https://user-images.githubusercontent.com/101202370/224718729-d8de92e4-a112-4b1d-aa10-0017a534ba46.png)
![Screenshot 2023-03-13 at 14 38 46](https://user-images.githubusercontent.com/101202370/224718736-e25ee44f-ab4e-47a2-af49-0d27aa4d9790.png)

**Comment by FitoreGashi** [comment]
![Screenshot 2023-03-13 at 14 40 31](https://user-images.githubusercontent.com/101202370/224718964-72635ff3-1312-4d5c-8522-33d9f5f18ccf.png)

**Comment by xwolfde** [comment]
ich glaub die dots hatten wir vor 1,2 versionen absichtlich weggemacht. ALso hier auhc bei den Bildlinks ruhig aus/wegblenden.

**Comment by FitoreGashi** [comment]
Ja genau, ich habe versehentlich den Code gepusht, als ich am Anfang die Zahlen entfernt habe, als ich dachte, der Schieberegler wird auch die Punkte verwenden. das war mein Fehler
