### ISSUE TITLE
Meta-Navigation abhängig von der eingestellten Sprache machen

### ISSUE THREAD

**Issue by csw-** [RRZE-Webteam/FAU-Einrichtungen#124]
Die Default-Einträge der Top- & Bottom-Meta-Nav sollten bei englischsprachigem Webauftritt, auf die entsprechenden Webseiten verlinken:

Zur FAU: https://www.fau.eu/ 
(Am wichtigsten, da es nicht durch ein eigenes Menüü ersetzt werden kann)

Jobs: https://www.fau.eu/university/careers-at-fau/ 
Intranet: https://www.fau.eu/intranet/
Legal notice: https://www.fau.eu/legal-notice/

**Comment by csw-** [comment]
Auf Department/Lehrstuhl-Ebene wird es beim Punkt 'Fakultät' sicher etwas schwieriger. Vielleicht kann man hier die Möglichkeit anbieten, die URL manuell zu setzen? Hm..

**Comment by xwolfde** [comment]
Ja, guter Hinweis. Das mit dem Logolink müssen wir uns anschauen.

Das mit den Links dagegen ist so ne Sache. Das würde am Ende dazu führen, dass wir eine immer größere Liste an Links mit in den Themes mitschleppen müssen. Ausserdem besteht da dann auch immer mehr die Gefahr, daß es dort zu Diskussionen kommt, welche Links wir aufnehmen und in welcher Reihenfolge.
Da würde ich also eher weniger Links reintun als mehr um den Ball flach zu halten.

**Comment by csw-** [comment]
Hm da hast du natürlich auch wieder recht.. 

Btw. wollen wir den Logolink nicht überall einheitlich mit dem Pfeil darstellen, anstatt "Zur FAU" zu schreiben? Dann wäre die Kennzeichnung für organisatorisch höherstehende Webseiten auch dort einheitlich.

**Comment by csw-** [comment]
@xwolfde Der Linktext "Zur FAU" sollte natürlich ebenfalls übersetzt werden. Vllt im gleichen Abwasch wie #150 ? :=)

**Comment by xwolfde** [comment]
Ab der nächsten Version wird bei den Meta-Links auf die gleichsprachige Site verwiesen, sofern diese vorhanden ist.
