### ISSUE TITLE
Datum und Kategorie standardmäßig ausschalten

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1242]
Mit Silke wurde intern abgesprochen, dass es ideal wäre, wenn man Datum / Kategorie standardmäßig ausgeblendet ist.

<img width="327" alt="Bildschirm­foto 2023-03-09 um 15 24 51" src="https://user-images.githubusercontent.com/58593037/224054441-ff7cee80-683a-4f5d-bcac-9bed16b49b89.png">

## Begründung
Die Beiträge sollen bei den Webseiten im Vordergrund stehen (und nicht Datum/Kategorie). Am leichtesten wäre es, wenn die Funktion standardmäßig im Customizer auf Aus steht.

### (Alternative Lösung)
Falls das nicht gehen sollte, wäre eine designtechnische Lösung, die Metainformationen unter den Text neben den Weiterlesen-Button zu schieben.

(Silke und mir genügt aber die schnellere, leichte Lösung, einfach den Default auf Aus zu setzen.)
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/58593037/224055393-841000e5-6a72-4e2b-a41c-067cce96aa35.png">

**Comment by xwolfde** [comment]
Für den Kontext der  vielen Hundert Einrichtungen und Lehrstühle ist es besser, wenn wir es auf An lassen im Default.
Silke geht es primär um die 2 Hauptseiten. Hier kann man erwarten, dass die dortigen Webmaster in der Lage ist das umzuschalten. Zumal inzwischen dort eh nicht mehr die Blogroll verwendet wird.

Für den Leser ist die Information, wann ein Artikel erstellt wurde, wichtig. Die Bedürfnisse der Zielgruppen sind mEn wichtiger als die Wünsche aus dem Design.
