### ISSUE TITLE
Teaser-Regler im Customizer entfernen?

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1243]
Den Teaser / Anleser gibt es doch nicht mehr im Slider, richtig?
Dann kann die Option dafür auch entfernt werden:

<img width="329" alt="Bildschirm­foto 2023-03-09 um 15 53 27" src="https://user-images.githubusercontent.com/58593037/224062230-7aee4290-09eb-437a-906f-8932366e2a7a.png">

**Comment by xwolfde** [comment]
Eigentlich ja...
