### ISSUE TITLE
Autoplay off => Pause-Icon on siteload

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1245]
Wenn Autoplay im Customizer für den Slider deaktiviert ist,
sieht man beim Seitenload in Firefox / Safari das Pause-Symbol.

Beim ersten Klick auf das Icon passiert nichts.
Beim zweiten Klick wechselt das Icon auf ein Play-Icon.
Beim dritten Klick startet erst der Slider wie vom User erwartet.

**Comment by xwolfde** [comment]
"if Safari, set Label Verwirrend" :)
