### ISSUE TITLE
Aktive Elemente werden im Hauptmenü nicht hervorgehoben

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1246]
Wenn sich ein Nutzer auf einer Unterseite befindet und er in der Desktop-Ansicht ins Hauptmenü schaut, sieht er nicht, dass er sich bereits auf einer Seite befindet.

Hier sieht man, dass die Seite "Leitbild" in keiner Weise im Hauptmenü hervorgehoben wird, obwohl sich der User bereits darauf befindet.

<img width="1509" alt="Bildschirm­foto 2023-03-09 um 16 19 27" src="https://user-images.githubusercontent.com/58593037/224069522-8b4d4870-fcab-4618-a5b3-ba00dbe770d5.png">

**Comment by xwolfde** [comment]
Auch der Hauptmenu-Button (erste Ebene) sollte, wenn man auf einer Unterseite ist, signalisieren, dass man "darin" ist.  Auch dann, wenn man in dem Augenblick das Menü nicht durch Klick geöffnet hat.

**Comment by xwolfde** [comment]
Das Problem ist dann aber, dass wir bei Natfak und Philfak eine Hintergrundfarbe haben, die zu hell ist um weiß zu nehmen. ALso müsste man dort schwarz nehmen. Und dann passt es nicht mehr so schön.
Wie wäre es stattdessen mit dem Unterstrich oder Border-left mit der Akzentfarbe?

**Comment by danielboese** [comment]
Also bei der Philfak ist die Schrift doch aktuell auch Schwarz auf Akzentfarbe. Bei der Natfak aktuell nur bei den Level1-Menüpunkten. Die Schrift sollte hier vielleicht auch einfach Schwarz auf Akzentfarbe bleiben, wenn man auf Level2 hovert.

Es würde quasi einfach überall der aktuelle Hover-Zustand der Menüpunkte auch für den Aktiv-Zustand benutzt.

Unterstrich würde ich eher gern vermeiden wollen, da es mehr wie ein Link wirkt, als ein Aktiv-Zustand. Border-Left mit Akzentfarbe passt stilistisch eher zu der Side-Nav, und hätte, denke ich, auch weniger Gewicht als der volle Akzentfarbe-Hintergrund.

**Comment by xwolfde** [comment]
ok, überzeugt
