### ISSUE TITLE
Hauptmenü Farbgebung – Der Hover nutzt die Aktive Farbe

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1247]
Wieder mal was zu prüfen / diskutieren

Aktuell ist beim Hover der Menüpunkte zu sehen, dass diese im aktiven Blau hinterlegt sind.
Die Buttons sind beim Hover in einem dunkleren FAU-Blauton gehalten.

Es sollte (in Rücksprache mit Silke) einheitlich sein.
Der Hover müsste also eigentlich ebenfalls das dunklere Blau nutzen, wenn Silke und ich das richtig gesehen haben.

Side by side. Hover-Element nutzt die gleiche Farbe wie der Standard-Button.
<img width="1509" alt="Bildschirm­foto 2023-03-09 um 16 22 39" src="https://user-images.githubusercontent.com/58593037/224070351-cefffc98-176c-4fe6-9b0c-65d21665e8d4.png">

Korrekt wäre wohl das Blau, dass man auch oben im Screenshot für "Fakultät" sieht.

**Comment by danielboese** [comment]
Habe mir das eben nochmal angeschaut, und stimme Lukas zu. Gerade auch in Hinblick auf die anderen Fakultäten, wo wir ja z. B. bei der philosophischen dieses recht starke Gelb haben – das mit dem aktiven "Orange" zu mischen wäre hier nicht so gut. 

Wäre daher auch für "--color-mainmenu-sublevel-bg"; sprich die gleiche Farbe wie die Level1-Hintergrundfarbe.

**Comment by danielboese** [comment]
@xwolfde Ist geändert und in dev gepusht :)
