### ISSUE TITLE
Overflow auf Beitrag in der Beta

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1248]
@xwolfde  Auf der Beitragsseite habe ich Overflow in x-Richtung auf mobile (Safari).
https://www.beta.wordpress.rrze.fau.de/2023/03/06/testbeitrag-mit-verschiedenen-inhaltsanreicherungen/

Ggf. mal prüfen. Kann auch am gewählten Seitentemplate liegen?

**Comment by wrcg** [comment]
ist vermutlich das gleiche...
Bild outside the box wird bei kleineren Auflösungen abgeschnitten
<img width="923" alt="image" src="https://user-images.githubusercontent.com/9526974/224634175-ae7dc5bb-dfb5-4dbd-ad21-6a9ea6d45709.png">
Sidebar läuft über Bild outside the box...
<img width="734" alt="image" src="https://user-images.githubusercontent.com/9526974/224634351-0c0a6a16-63b2-4390-a3b5-95a3bae4ef9d.png">
