### ISSUE TITLE
Anzeige der Logoleiste in mobiler Ansicht verbessern

### ISSUE THREAD

**Issue by csw-** [RRZE-Webteam/FAU-Einrichtungen#125]
In der mobilen Anzeige werden die Logos ohne den Player direkt aneinandergereiht abgebildet. Das sieht imo etwas verbesserungswürdig aus.

- Eine relativ simple Lösung wäre es wahrscheinlich,  dem img oder der span-Klasse einen margin von z.B: 10px zu geben. Damit würde das ganze schon einmal etwas aufgeräumter aussehen (vorrausgesetzt die Logos wurden in quadratischem Format hinterlegt).
- Alternativ dazu könnte man ja den Player bestehen lassen, aber die Anzahl der sichtbaren Logos reduzieren. Allerdings ist dies wahrscheinlich etwas umständlicher umzusetzen.

default
![logoleiste_mobile](https://cloud.githubusercontent.com/assets/6545158/17836979/c24ec9f2-67a6-11e6-9ef9-2c64713f7bc9.png)

1
![logoleiste_mobile_2](https://cloud.githubusercontent.com/assets/6545158/17836973/a3d3f92a-67a6-11e6-98df-1a62c448143d.png)

2
![logoleiste_mobile_1](https://cloud.githubusercontent.com/assets/6545158/17836971/a3cc83b6-67a6-11e6-926b-2a1ceaeb096c.png)

**Comment by xwolfde** [comment]
Jupp, da müssen wir ran.

**Comment by AstridSemm** [comment]
Lustig. Bei mir wird auf dem Handy einfach mal nichts angezeigt (Seite: https://www.alfirin.test.rrze.uni-erlangen.de/ ).
Screenshot:
![keine_bildlinks](https://cloud.githubusercontent.com/assets/11296947/17931340/51d5f300-6a0b-11e6-81dd-4a075901c1a2.png)

**Comment by xwolfde** [comment]
Das CMS denkt halt mit :)

**Comment by xwolfde** [comment]
ggf. auch Design-Entscheidung.

**Comment by xwolfde** [comment]
Das Carousel wird ab der nächsten Version bei Browser-Fenstergrößen
- über 979px  erscheinen mit 6 Elementen
- über 767px  erscheinen mit 5 Elementen
- über 480px  erscheinen mit 3 Elementen
- über 320px  erscheinen mit 2 Elementen
- unter 321px nicht erscheinen.
