### ISSUE TITLE
Link-Darstellung und Hovereffekt vereinheitlichen und korrigieren

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#1257]
Die Darstellung vin LInks im Content und in anderen Bereichen ist nicht ganz durchgängig handhabbar.
Die Darstellung mit dem Hovereffekt ist nicht immer machbar un deinheitlich, insbesondere nicht wenn Content aus Fremdquellen in dem COntentbereich eingebettet wird.
Zudem ist der Hovereffekt nicht ganz schön.
Gleichzeitig muss aber die Farbe des Links sich an die Fakultätsfarbe orientieren und kann nicht überall gleichmässig das Blau der Zentrale sein.

Es sollte daher der Gebrauch der Linkstile nochmal geprüft werden,, dieses vereinheitlicht werden und etwaige CSS-Korrekturen gemacht werden wo nötig.

**Comment by xwolfde** [comment]
Muss auch unbedingt in Zusammenhang mit allen anderen LInks und Buttons und mit den Einsatz in den Fakultätsthemes in deren CI Fraben betrachtet werden.

**Comment by xwolfde** [comment]
Bitte erst prüfen und dann eine Lösung vorschlagen, wenn das Design geändert werden sollte. Wichtig ist, dass die Darstellung plausibel bleibt.

**Comment by danielboese** [comment]
Die normale Ansicht des Links im Contentbereich würde ich so lassen. Eventuell könnte man die Underline in "--color-primary-dunkler" darstellen, für mehr Kontrast auf Weiß.

Dann beim Hover verschwindet die Underline, und der Text färbt sich in "--color-primary-dunkler". Wäre das okay? Die Akzentfarben haben ja oft zu wenig Kontrast auf Weiß, aber soweit ich sehen kann, haben sie allesamt als die dunkle Version stets ausreichend Kontrast. Falls das nicht gewünscht ist, kann der Text beim Hover ruhig die Standard-Textfarbe behalten, die Funktion wäre immer noch gegeben.

Hier wäre noch die Frage, ob es irgendwo einen Fall gibt, wo ein Contentlink auf der Akzentfarbe stehen kann. Bisher habe ich nur Links auf Weiß oder auf Grau gefunden. 

![mockup-link-contentbereich](https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/120717884/87fa734d-63af-497d-a2cc-f26fdda76d42)

(Ich werde jetzt vermehrt einfach direkt in die Issues posten, denke das ist dann übersichtlicher :) )

**Comment by xwolfde** [comment]
Also die CI Farbe soll ja grundsätzlich nicht als Textfarbe verwendet werden (bei Nat und Phil und TF wird man diesen dann nicht mehr lesen können). Daher wäre es dann bei Hover schon der der Default-Textfarbe besser.
ich bin mir nur nicht sicher, ob das so reicht. Der Unterschied eines gehovwerten/gefocussten Elements zum normalen Text drum herum wäre ja nicht mehr vorhanden. Das wäre gerade dann wenn der Link im Fließtext ist und man Tab-Focus nutzt (und daher nicht unbedingt sofort sieht wo der Focus ist), nicht so doll.

**Comment by danielboese** [comment]
Okay, dann die Default-Textfarbe.

Guter Punkt mit dem Tab-Focus, dann werde ich einen anderen Vorschlag machen.

**Comment by xwolfde** [comment]
Wenn ihr vorschlagt, dass die derzeitige Form ok ist und so bleiben sollte, ist das für mich auch in Ordnung.
Wir sind halt mit der jetzigen Form unsicher und wollen daher eure Expertenmeinung :)

**Comment by danielboese** [comment]
Also die jetztige Form funktioniert schon, passt nur stilistisch nicht so 100%-ig zum Rest (Hintergrund schließt direkt mit dem Text ab).

Hier noch ein Vorschlag. Ohne Änderungen an der Schriftfarbe sind die Möglichkeiten leider begrenzt... wenn dieser nicht gefällt würde ich vorschlagen, dass der Ist-Zustand einfach beibehalten wird.

![mockup-link-hover-var2](https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/120717884/8cde8ef2-67ce-49ee-ad3c-8ae919ef07bd)

**Comment by xwolfde** [comment]
Der Vorschlag gefällt mir

**Comment by xwolfde** [comment]
Ggf. bei dem LInk noch ein 
` transition: all .1s ease-out;`
rein?
Hab mal hier ien bißchen getestet: https://codepen.io/xwolfde/pen/XWyRaJw

**Comment by xwolfde** [comment]
Informativ: Hier hab ich mal die verschienen Optiken durchgespielt: 
https://codepen.io/xwolfde/pen/XWyRaJw
