### ISSUE TITLE
Anpassungen für mobile Version

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#1258]
- [x] Sprachwechsel verschieben vom Meta-Menü (unter FAU Icon), stets sichtbar vor dem Hamburger-Menu.
- [x] Wegen der Länge des Sitenames: Kurze Version eingebbar machen im Backend, die dann nur in der Handyversion sichtbar gemacht wird, so daß Hamburger, FAU Logo und optionaler Sprachwechsel genug Platz haben
- [x] Sitename linksbündig

**Comment by xwolfde** [comment]
Bitte auch hier Vorschläge abstimmen

**Comment by danielboese** [comment]
So würde der Sprachwechsler neben dem Burger aussehen:

![sprachwechsler-tablet](https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/120717884/bb88e1d5-b047-42cf-9b5e-46c217b3a176)

![sprachwechsler-klein](https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/120717884/7729f927-289f-4d5e-8888-c22eab833fd4)

![sprachwechsler-ab-480px](https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/120717884/2bd034d4-f7bf-4292-a31c-dc34572db46c)

Nur beim XS-Format müssten wir auf was sehr Knappes wechseln; z. B. "EN" und "DE". Alternativ könnte man hier auch einfach eine Länderflagge zeigen.

**Comment by danielboese** [comment]
Jap klar, wird übernommen
