### ISSUE TITLE
Linksbündiger Ansatz

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#1259]
Design prüfen und anpassen, dass die Linksbündigkeit priorisiert wird und Zentrierungen entfernt werden.

Hintergrund:
Einige Inhaltselemente waren bislang zentriert in der Ausgabe.
Hier soll geprüft werden, ob und wo solche Elemente noch vorhanden sind und diese ggf. umgestellt werden auf ein linksbündigen Ansatz. (Immer vorausgesetzt, dass man im LTR-Modus ist).

**Comment by FitoreGashi** [comment]
Haben Sie einen Screenshot der Probleme, damit wir sie besser untersuchen können? @xwolfde  @lukasniebler

**Comment by FitoreGashi** [comment]
Wir haben das Problem mit dem Slider behoben und überprüft, ob jetzt alles gut aussieht.
