### ISSUE TITLE
Visitenkarten - Überlagerung beim Druck

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Einrichtungen#126]
Beim Druck der Seite https://www.fau.de/universitaet/leitung-und-struktur/leitung/praesidialbuero/ in Firefox (48.0.1) sind Elemente verschoben und überhaupt sieht das Ganze sehr merkwürdig aus (blauer Rand) - betrifft das FAU-Theme. In Chrome tritt das Problem nicht auf, im IE auch nicht.

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/17858437/048892b4-6886-11e6-803d-da8a44443087.JPG)

Im Einrichtungs-Theme habe ich das Ganze nachgebaut, wenn auch der Komplexität geschuldet nicht detailliert mit allen Kontakten. Doch auch da gibt es noch eine Überlagerung: http://test4.tindu.rrze.uni-erlangen.de/test-pb-seite-kann-geloescht-werden/

![unbenannt2](https://cloud.githubusercontent.com/assets/9445370/17858443/0b2626cc-6886-11e6-9f0d-a4d47476fdf7.JPG)

Mögt ihr mal prüfen? Vielleicht ist das Problem in beiden Themes gleich, so dass man beides parallel fixen kann...

**Comment by xwolfde** [comment]
https://github.com/RRZE-Webteam/FAU-Einrichtungen/issues/60

**Comment by xwolfde** [comment]
Wir brauchenn jedenfalls auch eine grundlegende Entscheidung, wie das "Print-Design" aussehen soll.

**Comment by wrkb** [comment]
Gern. Das bisherige war eine sehr schlichte Lösung (in der funktionierenden Variante natürlich ohne die grafischen Elemente aus den Screenshots von oben).

Spontaner Input für die Vorbereitung einer solchen Entscheidung: Oftmals wurde der Ausdruck als Platzverschwendung wahrgenommen, weil auch dort viel Weißraum zu sehen war. Da könnte man tatsächlich noch kleiner werden mit der Schrift, ich würde mich hier an Printbroschüren orientieren (FAU, RRZE...).

**Comment by xwolfde** [comment]
Thema erhielt in Runde keine Priorität, wurde dort als unnötig gesehen. 
Wird dennoch wegen belegbarer Rückmeldungen aus den Servicetheken grundlegend in #60   angegangen. 
Dieser Issue als duplicate geschlossen.
