### ISSUE TITLE
Linke Navigation prüfen und anpassen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#1260]
- Linke Sidebar: Obere Level2-Navigationspunkt anders darstellen; die Linie oben stört etwas. Evtl. eher als Button darstellen, oder im gleichen Listenstil, aber in anderer, stärkerer Farbe
- Anpassen der Optik an Hauptmenü. ggf. Farbloser machen. Seite soll "beruhigt" werden; insbesondere bei Fakultätsversionen (siehe Phil, RW, Nat, ..)
- Vorschläge erwünscht

**Comment by lukasniebler** [comment]
In meinen Augen sollte die Navigation links die gleiche Designsprache wie im Mega Menü nutzen. Es sollte also:

- [ ] weitgehend farblos neutral gestaltet sein
- [ ] Einen seriösen Eindruck bei den Nutzern hinterlassen
- [ ] Die CD-Farben nur als Akzent nutzen und nicht als Hintergrundfläche
- [ ] Eine deutlich erkennbare Struktur zeigen, damit Nutzer wissen, ob ein Unterpunkt zur 1. 2. oder ggf. 3. Ebene gehört

## Wie könnte es aussehen
So oder so ähnlich könnte eine überarbeitete Navigation aussehen. Vielleicht ist der Farbstreifen Links bereits etwas zu viel. 
![navigation-links](https://user-images.githubusercontent.com/58593037/228525021-6fc6f577-d7bb-4d4a-88f8-a05e485d49f7.png)

**Comment by xwolfde** [comment]
Wie in dem Meeting und danach übver Chat besprochen, werden die neuen Mookups von Daniel umgesetzt.

Jeweils das untere:
![grafik](https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/1070669/afd0795b-ad8e-47e0-b754-4796334ac564)
![grafik](https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/1070669/abc5a986-6da7-4f4b-bc28-0781ac445d65)
![grafik](https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/1070669/749719ac-4d0e-46e6-9edc-c5c82a7d781a)
![grafik](https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/1070669/22bbb09d-7a20-4f08-9582-c0d4b9624a07)
![grafik](https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/1070669/b828f90f-3cb0-4e49-8d09-c834a0cf1396)
