### ISSUE TITLE
Portalmenü-Feature Listenansicht für Menüelemente

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1261]
# Vorschlag
Vorschlag ist eine Liste, die aussieht wie Buttons und dynamisch umbrechen. Ähnlich wie auf der Tum.de-Seite 

<img width="1120" alt="Bildschirm­foto 2023-03-07 um 17 18 48" src="https://user-images.githubusercontent.com/58593037/223483127-ff10e3a7-4400-4005-ba53-60f3c603a581.png">

https://www.tum.de

<img width="530" alt="Bildschirm­foto 2023-03-07 um 17 20 21" src="https://user-images.githubusercontent.com/58593037/223483613-08a45568-5f98-49a3-b014-8655b0477141.png">

(Erinnerung an mich: Wenn Issue closed 🎫 http://go.fau.de/9ulvt informieren.)

**Comment by xwolfde** [comment]
Hier soll unser Portalmenu verwendet werden, da an der Stelle bereits existiert. Dem Portalmenü soll dann eine neue Darstellungsoption "Listenansicht" hinzugefügt werden, welches dann dafür sorgt, dass das Portalbild entfällt und auch alle Unterpunkte wegkommen und nur noch die Oberpunkte da stehten. Aber statt sich dann als Grid mit Innenabstand zueoinander zu verzeilen, sollen die Buttons als horizontale Liste links (bei RTL Ansicht) ausgerichtet stehen.


Ggf. überlegen, ob die Kästchen dann ein neuer Buttonstyle sind oder der Buttonstyle verwendet werden soll.

**Comment by xwolfde** [comment]
vgl auch zu den Optionen des Portalmenüs:
https://www.beta.wordpress.rrze.fau.de/theme-shortcodes/shortcode-portalmenu/

**Comment by MManthey** [comment]
Habe das mal mit dem vorhandenen Button-Style umgesetzt. Dadurch bleibt der Stil einheitlich:

![image](https://user-images.githubusercontent.com/43784820/231492211-8ff77b3d-4f24-4362-b664-9a8d917e5df3.png)

Mobile:

![image](https://user-images.githubusercontent.com/43784820/231493169-256dc57c-cbf9-463b-9106-e4397deffaf1.png)

**Comment by lukasniebler** [comment]
@MManthey Danke. Ich zeige und bespreche es am Freitag gleich mal mit Silke. Am Ende soll die Darstellung des Portalmenü ja vor allem auf der Startseite unter dem neuen Startseiten-Slider ausgegeben werden. Ob die Buttons jetzt border-radius haben oder was die Farbwahl angeht, kann ich dann ggf. noch mehr mit auf den Weg geben, falls es noch Änderungswünsche geben sollte

**Comment by lukasniebler** [comment]
Hi @MManthey,

Da das Portalmenü direkt unter dem neuen Slider ausgegeben werden soll, würde sich das Button-Blau mit dem FAU-Blau schneiden. (Noch schlimmer würde es z.B. mit den Phil-Aktivfarben aussehen).

Den Border-Radius / Pudding könnt ihr aber natürlich von den anderen Buttons so übernehmen.
(Falls ihr eine der Alternativen vom Aussehen her besser findet, dann gerne schreiben.)

## Version mit DFE6EC (Aktuell unser Favorit)
(Der gleiche Farbton, der aktuell bei Ghost-Buttons in der Rahmenfarbe genutzt wird)
<img width="960" alt="Bildschirm­foto 2023-04-14 um 08 51 30" src="https://user-images.githubusercontent.com/58593037/231966240-b6782b47-f74b-4b6e-a2d7-705d4c7388c9.png">

## Alternativen
### Version mit FAU-Blau
<img width="960" alt="Bildschirm­foto 2023-04-14 um 08 54 33" src="https://user-images.githubusercontent.com/58593037/231966821-b0a4c49f-3e10-4bc9-917c-69c0489af02e.png">

### Ghost-Button Style
Nutzung des vorhandenen Ghost-Button Styles
<img width="960" alt="Bildschirm­foto 2023-04-14 um 08 56 59" src="https://user-images.githubusercontent.com/58593037/231967335-3f0c8197-78b4-49d6-b839-77f4afc691a6.png">

## Ausgeschlossen:
### Version mit Std-Btn-Farbe
<img width="960" alt="Bildschirm­foto 2023-04-14 um 08 54 45" src="https://user-images.githubusercontent.com/58593037/231966872-cc3cac38-d01d-41ce-9d91-3a2e0a2090df.png">

**Comment by MManthey** [comment]
Hier die neue Version mit Hover auf 'Facebook':

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/43784820/232040741-d4608726-13b8-4b1d-8e18-8daa70df3a03.png">

**Comment by lukasniebler** [comment]
Sieht gut aus.
