### ISSUE TITLE
Darstellungsfehler Reiter von WSForm-Formularen

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1262]
Bei der Nutzung von WS Form wird neben den Reitern aktuell noch ein Aufzählungspunkt mit ausgegeben. Dieser sollte verschwinden (List-style: none)
# Screenshots
<img width="837" alt="Bildschirm­foto 2023-03-29 um 13 34 16" src="https://user-images.githubusercontent.com/58593037/228523101-8ce39740-b80f-4a79-a736-2503373a905c.png">

## Beispielseite
https://www.wordpress.rrze.fau.de/person/webmanagement/

## Dev
Vielleicht hilfreich:
<img width="1329" alt="Bildschirm­foto 2023-03-29 um 13 36 59" src="https://user-images.githubusercontent.com/58593037/228523699-9fb5f80f-591d-4edc-8cd5-1500667eaf89.png">

**Comment by xwolfde** [comment]
Bei The Events Calendar haben wir genau dasselbe (mit den Listenpunkt).

**Comment by FitoreGashi** [comment]
![Screenshot 2023-04-26 at 11 54 42](https://user-images.githubusercontent.com/101202370/234540419-6916f3f3-9745-4f50-adda-cc59adc97d4f.png)

**Comment by lukasniebler** [comment]
Sieht gut aus
