### ISSUE TITLE
Portalmenü: Option skew entfernen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#1263]
Bei der Darstellung des Portalmenüs soll die Option zur schrägen Darstellung des Bildes entfernt werden.

Optionen:
<img width="288" alt="grafik" src="https://user-images.githubusercontent.com/1070669/228524856-9e6c2711-59a0-4628-9d65-b41a6777ebe9.png">

Darstellung Beispiel FAU Startseite:
<img width="1290" alt="grafik" src="https://user-images.githubusercontent.com/1070669/228524699-77115a54-9a1c-46a1-a269-8b7cb0bb538e.png">

**Comment by MManthey** [comment]
Skewoption und dazugehoerige Styles entfernt.
