### ISSUE TITLE
Galerieslider kaputt?

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#1264]
Siehe
https://www.fau.de/outreach/veranstaltungen/schlossgartenfest/#collapse_0

Wo kommt dann der Effekt her, dass die Icons links/rechts reinschweben?  Das wurde doch von uns garnicht so gecodet?

**Comment by AndiWebred** [comment]
Das ist nur bei den Galerien mit Remoter-Plugin so: https://github.com/RRZE-Webteam/rrze-remoter/issues/3
