### ISSUE TITLE
Runde ecken bei Buttons: Suche auch anpassen?

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#1265]
Wir haben überall einheitlich ein border-radius von 4px.
Ausser bei den Sucheingaben:
<img width="538" alt="grafik" src="https://user-images.githubusercontent.com/1070669/228833452-0d9773ea-0192-47bc-85e1-dca2335eb8bc.png">

Soll das so bleiben?

**Comment by FitoreGashi** [comment]
![Screenshot 2023-04-26 at 11 33 19](https://user-images.githubusercontent.com/101202370/234537194-8994e620-8426-493e-acea-42b66b3f3ec0.png)
@lukasniebler

**Comment by lukasniebler** [comment]
@FitoreGashi Sieht auf den ersten Blick gut aus. Ich bespreche das noch kurz mit Silke, falls es noch Wünsche zur Gestaltung gibt.

**Comment by lukasniebler** [comment]
@FitoreGashi - Ich hab mal Rücksprache mit Silke gehalten. Wir entscheiden uns für die Version mit hellem Textfeld und blauem Button:
<img width="1470" alt="Bildschirm­foto 2023-04-27 um 09 15 09" src="https://user-images.githubusercontent.com/58593037/234787576-f52483e3-842e-4c09-a0c9-42b298353d56.png">

(Am idealsten finden wir zwar, wenn das Suchfeld nur erscheint, wenn ein Nutzer auf ein Search-Icon klickt. Aber das ist vermutlich eher was für den kompletten Relaunch, da es vermutlich aufwendiger umzusetzen ist)

**Comment by FitoreGashi** [comment]
https://user-images.githubusercontent.com/101202370/234798896-bf4588e7-7bbb-4c85-807e-bb142384a312.mov

denken Sie so? Bitte kümmern Sie sich nicht um den Radius @lukasniebler

**Comment by lukasniebler** [comment]
@FitoreGashi Ich finde es gut! Aber ich warte noch ab, bis Ich Feedback von Silke und Wolfgang noch dazu bekomme. Spätestens nächsten Dienstag / Mittwoch habe ich dann von beiden Feedback zum Suchfeld.

**Comment by xwolfde** [comment]
Für mich passt es so, aber bitte unbedingt auch die Pad und Handy-Variante prüfen!
Bei der Desktop-Variante, zumal einer wo so viel Platz frei ist, würde ich den Suchschlitz offen lassen, damit er augenfälliger und klarer zu erkennen ist.

**Comment by lukasniebler** [comment]
> 

@xwolfde 
Hintergrund war ja eigentlich, dass er in der Desktop-Variante unauffälliger wird, damit die Aufmerksamkeit nicht auf der (derzeit nicht gut funktionierenden) Suche liegt.

Aber ich kann auch mit einem offenen Suchfeld leben.

**Comment by xwolfde** [comment]
Ich bin an der Stelle selbst nicht so sicher...

**Comment by xwolfde** [comment]
Ok, machen wir so: Nur die Lupe zeigen, und wenn man drauf klickt, geht das Suchfeld auf. 
DerAbsende-Button soll dann auch erst sichtbar werden, wenn die Suche aufgeklappt wird.

Bitte beachten: Buttons sollten immer mind. 48px Größe (Daumengröße :) haben.

**Comment by FitoreGashi** [comment]
https://github.com/RRZE-Webteam/FAU-Einrichtungen/commit/b527e3230b31f5c7ca7f4a68c1664c64740a527e Müssen wir jetzt den allen Randradius auf 0 ändern?

**Comment by xwolfde** [comment]
Ja, aber bitte jeweils einen der beiden Custom Properties (--border-radius, --border-radius-buttons)  verwenden, frü den Fall, dass es doch irgendwann wieder geändert wird.
