### ISSUE TITLE
Widgetbereich Sidebar

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1266]
Es gab die Kundenfrage, ob man den Widgetbereich Sidebar ( der über den Customizer freigeschaltet wird ) auch über der Sidebar ausgeben kann.

Wenn man auf bestimmten Inhaltsseiten eine Sidebar händisch anlegt, liegt diese aktuell über dem WIdgetbereich Sidebar.
Wenn man im Widgetbereich z.B. die Ansprechpartner hinterlegt, wäre es praktisch, wenn diese zuerst über der händisch angelegten Sidebar erscheinen.

**Comment by xwolfde** [comment]
Das könnte das Problem workarounden, das. man die bisherige Sidebar nicht mit Gutenberg bearbeiten kann.

**Comment by xwolfde** [comment]
Im Dev
