### ISSUE TITLE
Icon für FAU-Community in Social Media Menü

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/FAU-Einrichtungen#1271]
Damit wir die FAU-Community (https://community.fau.de) im Social Media Menü im Footer anständig darstellen können, müsste ein Icon ergänzt werden.

Das Icon hier zum Download, könnt ihr damit was anfangen oder braucht ihr etwas bestimmtes anderes?
![FAU-community_web-icon_RZ](https://user-images.githubusercontent.com/53909165/229425521-f4331ab1-334d-4d2f-910b-911d9ce24470.svg)

**Comment by xwolfde** [comment]
Das ist nur ein Farbklecks? Wie soll das Wiedererkennbar sein?
Ist das mit der CDO abgestimmt?

**Comment by lukasniebler** [comment]
Sollte ein solcher Link überhaupt an so prominenter Stelle platziert werden?

Wenn ein Nutzer dem Link folgt, sieht er nicht einmal, was das überhaupt ist, wofür er sich da registrieren soll:
"Das Kommunikationsportal für Angehörige, Alumni und Freunde der FAU."

Man wird weder darüber aufgeklärt, was es ist, wofür es da ist, warum man sich anmelden sollte, was mit den eigenen Daten passiert etc. 

Es macht also eigentlich weder im Header noch im Footer sinn, Nutzer ins Niemandsland zu führen.
Wenn dann würde es Sinn machen, wenn es auf einer Themen-Seite z.B. Alumni-Portalseite oder einer Alumni-Landingpage vorher beschrieben wird, was das eigentlich ist, bevor Nutzer zu einer Registrierungsmaske weitergeleitet werden.

Auf mich macht das ganze ein wenig den Eindruck, als wär es eine geschlossene Gesellschaft, die im Geheimen agiert und gar keine neuen Nutzer möchte.

**Comment by xwolfde** [comment]
Prominenter würde es auch mit den neuen CTA Boxes werden.

**Comment by xwolfde** [comment]
Da ich nach meinen Mails nichts mehr gehört habe, schließe ich den Fall.

**Comment by AndiWebred** [comment]
Bitte wieder das Ticket öffnen.

1. Wo genau ist der Unterschied zwischen dem Icon, das ich hochgeladen habe und der ersten Version in der Datei, die du hochgeladen hast? Das Icon wurde in Zusammenarbeit mit der Grafikabteilung, also auch der CBO, erstellt.
2. Ja, die FAU-Community kann als internes und externes Kommunikationsinstrument an solch prominenter Stelle stehen. Sie richtet sich nicht ausschließlich an Alumnis, sondern auch an aktuelle FAU-Mitglieder. Letztendlich ist das aber auch nicht an euch zu entscheiden, welche Plattformen wir unten in der Leiste prominent platzieren, sondern an uns.
3. Die Kritikpunkte an der Startseite des Community-Portals gebe ich natürlich gerne weiter.

**Comment by xwolfde** [comment]
Die Grafik du du hochgeladen hast sieht so aus:
<img width="1444" alt="grafik" src="https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/1070669/5713542c-9a77-473c-84b2-1dac4a40c5a1">


Die Grafiken die ich von CBO bekamm sehen so aus:
<img width="1444" alt="grafik" src="https://user-images.githubusercontent.com/1070669/237062047-b732a6ab-d545-404d-8582-62c9e7d959ec.png">

**Comment by xwolfde** [comment]
Wir klären nochmal mit SIlke und mind einer Community-Person, was sinnvoll ist.
IMHO wäre ein CTA auf der Startseite (z.B. aktuell zwischen Veranstaltungen un dden 3 Videos ) besser als ein Icon ganz unten am Ende welches noch kein Wiedererkennungseffekt haben kann.
Der Wiedererkennungseffekt kann auch nur existieren, wenn das Symbiol auch auf der Plattform präsent wäre, das ist es aber nicht.
Dort hingegen müsste man über das Logo das dort verwendet wird reden.

**Comment by xwolfde** [comment]
Es hat sich hier nichts getan. 
Aber da im Zuge des Updates ohnehin die Icons neu gemacht werden musste, hab ich ein Standard-Gruppe-SVG eingefügt und der URL von community.fau.de zugefügt.

Dann auch neu:
- twitter zu X
- reddit
- pinterest
- mastodon
- bluesky
