### ISSUE TITLE
Archivseiten von Kategorien: Reihung der Buttons umkehren (aus Helpdesk)

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1272]
# Problem
Nutzer finden es verwirrend, wenn auf Archivseiten (Kategorie-Übersichtsseiten) die Reihung der Buttons umgekehrt ist. Ältere Beiträge erreicht man dabei über den Button auf der rechten Seite, während der Button für neuere Beiträge links liegt.
<img width="1188" alt="Bildschirm­foto 2023-04-11 um 07 55 53" src="https://user-images.githubusercontent.com/58593037/231069044-fc30a2cc-5623-4141-8ba8-56890234e42f.png">

"Als Nutzer finde ich das Springen des Buttons von links nach rechts völlig verwirrend. 
Es wäre meiner Meinung nach besser, wenn  "Older posts“ immer rechts steht, auch wenn kein "Recent posts“ vorhanden ist oder eine alternative Darstellung mit Seiten-Anzahl und Pfeilen, analog dem https://en-ca.wordpress.org/plugins/wp-pagenavi/ oder https://wordpress.org/plugins/styles-for-wp-pagenavi-addon/ angeboten wird."

# Lösung
Global sollte der "Weiter"-Button immer rechts liegen, während der "Zurück"-Button immer auf der linken Seite liegt.

# Vergleichsbeispiele aus dem Theme
Rechts: Neuerer Beitrag
Links: Älterer Beitrag
<img width="1188" alt="Bildschirm­foto 2023-04-11 um 07 57 13" src="https://user-images.githubusercontent.com/58593037/231069237-22949ea9-d41e-4ebc-9739-3794ab8f7457.png">

# Zugeordnetes Ticket
🎫 http://go.fau.de/9utm7

**Comment by xwolfde** [comment]
Sollten wir noch diskutieren und prüfen. Eine Meldung nur bei einer Laufzeit von > 1 Jahr nach aktuellem Zustand spricht eher für die jetzige Reihenfolge.
Auch andere Blogs nutzen es so...

**Comment by xwolfde** [comment]
Ich lass es jetzt so.
