### ISSUE TITLE
Button List: Mobile Ansicht - Abstand zum linken Seitenrand 

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1273]
Feedback: In der mobilen Ansicht (Smartphones) fehlt für die Button-List aktuell noch etwas Abstand auf der linken Seite:

Screenshot:
<img width="675" alt="Bildschirm­foto 2023-04-20 um 10 13 03" src="https://user-images.githubusercontent.com/58593037/233303070-538f0729-ccb2-4012-a1d1-622e0e26ee72.png">

**Comment by FitoreGashi** [comment]
@MManthey
