### ISSUE TITLE
TEC: No results & Datepicker Icons

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1274]
- [x] Meldung für "Kein Ergebnis" zeigt aktuell noch einen Listenpunkt über Icon
- [x]  Datepicker Icons nicht sichtbar 

## Meldung für "Kein Ergebnis" zeigt aktuell noch einen Listenpunkt über Icon:
Wenn man keinen Termin findet als Nutzer, wird ein Listenpunkt mit ausgegeben:
<img width="547" alt="Bildschirm­foto 2023-04-20 um 10 26 50" src="https://user-images.githubusercontent.com/58593037/233306601-2781ed6e-7146-4248-a09d-4b80e5a68c1e.png">
<img width="547" alt="Bildschirm­foto 2023-04-20 um 10 27 43" src="https://user-images.githubusercontent.com/58593037/233306823-744ce0a4-197e-42c1-b225-93b70df6d208.png">

## Datepicker Icons nicht sichtbar
Anscheinend überlagern noch ein paar Tabellen-Styles die Ausgabe des Datepickers:
<img width="547" alt="Bildschirm­foto 2023-04-20 um 10 28 44" src="https://user-images.githubusercontent.com/58593037/233307085-0b4f87ff-9366-4a4b-aa77-a03da7f5fea1.png">
<img width="555" alt="Bildschirm­foto 2023-04-20 um 10 29 12" src="https://user-images.githubusercontent.com/58593037/233307233-f3c98ac9-9b80-48a1-b19f-68f68c2ab392.png">

**Comment by FitoreGashi** [comment]
![Screenshot 2023-04-24 at 14 33 23](https://user-images.githubusercontent.com/101202370/233997418-8b140e75-ac61-4e67-abfc-bdb72177ba6d.png)
![Screenshot 2023-04-24 at 14 33 17](https://user-images.githubusercontent.com/101202370/233997423-cee363b4-7679-489e-af44-6cd065fdb7b1.png)
![Screenshot 2023-04-24 at 14 33 12](https://user-images.githubusercontent.com/101202370/233997424-8e246039-5d35-45e9-ae0b-19f1f7b22c5f.png)

**Comment by lukasniebler** [comment]
@FitoreGashi Shouldn't there be a caret-icon or another symbol-indicator next to April?

Like so:
< April > (or <- April ->)

Ansonsten sieht es gut aus.

**Comment by FitoreGashi** [comment]
![Screenshot 2023-04-24 at 14 59 23](https://user-images.githubusercontent.com/101202370/234003524-2b99a3a0-a5b5-4cd9-bb17-2d3539332eaa.png)
is this part you are talking about ?

**Comment by FitoreGashi** [comment]
ahh in dates view,  no there is no function from free version let me check if we can add it

**Comment by FitoreGashi** [comment]
Nein, Sie müssen auf den Monat wie April klicken und Sie haben alle Monate zur Auswahl https://youtu.be/ZfyAG3H_avw
