### ISSUE TITLE
Borderradius in der Button-List (& ggf. Calendar-Kacheln) auf 0?

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1276]
@FitoreGashi – Ist es noch möglich bei der Button-List ( https://github.com/RRZE-Webteam/FAU-Einrichtungen/issues/1261 ) (und ggf. bei der Ausgabe der Kalender-Kacheln ( https://github.com/RRZE-Webteam/FAU-Einrichtungen/issues/1228 )) den Border-Radius bereits auf 0 zu setzen?

Ansonsten wurde das Design für Milestone 2.3E komplett abgenommen. Passt das bei euch noch zeitlich in den Rahmen, den border-radius für die Button-Liste (und ggf. für die Kalender-Kacheln) auf 0 zu setzen?

(In einem kommenden Milestone sollen dann auch der border-radius für andere Elemente fallen. Aber wir würden sehr gerne zumindest die Button-Liste unter dem Slider schon mit der nächsten Version mit Border-Radius 0 ausrollen)

**Comment by FitoreGashi** [comment]
@lukasniebler  Ja, kein Problem, wir machen das. 
<img width="665" alt="Screenshot 2023-04-25 at 14 25 36" src="https://user-images.githubusercontent.com/101202370/234275535-f90e4a49-70b2-4231-bb45-efdec069d7af.png">
<img width="380" alt="Screenshot 2023-04-25 at 14 24 48" src="https://user-images.githubusercontent.com/101202370/234275542-29819531-300a-4e14-868e-b284175c66cb.png">

**Comment by lukasniebler** [comment]
Super, Danke!
