### ISSUE TITLE
Neues Styling für den HTML-Trenner hr

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1277]
## Problem
Der alte Trenner 
```
<hr>
```
ist zum Strukturieren von Inhalten ungeeignet und passt nicht mehr ins aktuelle FAU Design.

### Derzeitiger Ist-Zustand:
<img width="1717" alt="Bildschirm­foto 2023-05-02 um 10 23 45" src="https://user-images.githubusercontent.com/58593037/235616419-7c461779-fc97-4838-9145-708099f1f80c.png">

## Vorschlag
Ein neuer Trenner, der in den FAU-Farben die Inhalte strukturiert.
<img width="1717" alt="Bildschirm­foto 2023-05-02 um 10 19 12" src="https://user-images.githubusercontent.com/58593037/235615518-cc30276e-2cf4-46a3-8618-03699c5e70be.png">

### Custom-CSS aus dem Vorschlag:
```
.filigran{
	margin: 0;
	box-shadow: none;
	border-bottom: 4px solid #04316A;
}
```

## Weitere Gedanken

- [ ] Aktuell werden Trenner auf mobile nicht ausgegeben – Soll das so sein?
- [ ] Die Trenner sollten zum restlichen FAU-Design passen (Oben ist nur ein Vorschlag)
- [ ] Die Trenner können auch dezenter sein und z.B. dem Ansatz von anderen Webseiten folgen (z.B. nytimes oder Nature.com)
- [ ] Eventuell kann es auch 2 Versionen geben. z.B. eine Klasse für subtrenner die dezenter sind und einen Haupt-Trenner (Eventuell sind die Sub-Trenner auch was für Elements-Plugin)

## Weitere Inspiration
<img width="1303" alt="Bildschirm­foto 2023-05-02 um 10 25 30" src="https://user-images.githubusercontent.com/58593037/235616845-7d313dc3-706f-4b50-bc90-96c830960ddf.png">
Von der nytimes
<img width="1303" alt="Bildschirm­foto 2023-05-02 um 10 27 47" src="https://user-images.githubusercontent.com/58593037/235617310-14eb9a14-2d55-4a13-9f9c-fa1bc1b21f07.png">
Von nature.com

**Comment by xwolfde** [comment]
Wie gerade besprochen:

Per Default soll die CI-Farbe --color-FAU verwendet werden. Ohne Schatten.

Die bisherigen Classes "big" und "line" erntfallen. 
Vgl: https://www.beta.wordpress.rrze.fau.de/texte/trennlinien/

Stattdessen werden wir die Default-Fakultätsclassen hinzufügen:
hr.nat {
   color: var(--color-nat-basis); 
}

usw. für .rw, .med, .phil, .tf

**Comment by lukasniebler** [comment]
Ein Auszug aus dem aktuellen Mockup:

Der Trenner mit einer Strichdicke von 4 px.
Der Trenner nimmt die komplett verfügbare Inhaltsbreite ein.
Der Trenner hat nach oben und unten einen identischen Abstand.
(Im Prototyp sind das ca. 52px, vielleicht kannst du mit dem Auge abschätzen, wie viel das in em / rem wären. Falls wir da schon variablen haben, dann kannst du ja 1x bzw. 2x die Abstandsvariable nehmen, je nachdem was besser aussieht...)

<img width="782" alt="Bildschirm­foto 2023-05-08 um 13 48 30" src="https://user-images.githubusercontent.com/58593037/236816815-df9260b8-2629-4d66-8f61-411bb39a5f57.png">

**Comment by xwolfde** [comment]
Ins Backlog verschoben, da ich es selbst mit in 2.3 reintu

**Comment by xwolfde** [comment]
in dev
