### ISSUE TITLE
Blogroll kann auf Template Startseite bzw. Startseite Fakultät nicht mehr deaktiviert werden

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1278]
Früher konnte man über den Customizer > Blogroll die Anzahl der Einträge auf 0 setzen, dann wurde die Blogroll nicht eingeblendet.
Das funktioniert aktuell nicht mehr. Wäre aber praktisch für z.B. die FAU Startseite.

**Comment by xwolfde** [comment]
Für 2.4 einsortiert. Es betrifft die Websiten mit dem Templates Startseite.
Es gibt diesbzgl. auch eine Einstellung, dass bei diesen Templates über der Blogroll der Content gezeigt wird.
Es bräuchte dazu also ebenfalls im Customizer ein Schalter, die Blogroll einfach abzuschalten.
