### ISSUE TITLE
Ghost-Button hat andere Typographie und Größe als normaler Button

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1279]
<img width="240" alt="Bildschirm­foto 2023-05-03 um 14 25 40" src="https://user-images.githubusercontent.com/58593037/235915005-40d5ea0f-4e1b-4f19-80e8-cdf524eefd9d.png">

In der beta hat ein Ghost-Button eine andere Größe als ein normaler Button
Getestet auf page-start.php

**Comment by lukasniebler** [comment]
## Genutzter Shortcode:
[button style="ghost" link="https://www.wordpress.rrze.fau.de"]Portal Universität[/button]
[divider]
[button link="https://www.wordpress.rrze.fau.de"]Portal Universität[/button]

**Comment by xwolfde** [comment]
@FitoreGashi Könnt ihr dies bitte noch prüfen, ob das von Theme kommt? Wenn das Elements-Plugin der "Übeltäter" ist, kann man dies ggf. durch das Theme-CSS (hierarchisch) überschrieben?
