### ISSUE TITLE
Höhenunterschied Content- & Sidebar-Überschriften - Idee: top-padding bei h2-Überschrift im main-Content entfernen

### ISSUE THREAD

**Issue by csw-** [RRZE-Webteam/FAU-Einrichtungen#128]
Ich erinnere mich das schonmal angesprochen zu haben, konnte aber den Issue dazu nicht mehr finden.
Es geht darum, dass die Überschriften des main-Contents und der Sidebar (wie z.B. "Kontakt") nicht auf gleicher Höhe sind und das ganze somit etwas unschön aussieht.

Wie ich das sehe ist die h2 für die erste Überschrift des eigentlichen Seiteninhalts vorgesehen, richtig? 
Könnte man dann nicht das padding-top der ersten h2-Überschrift via first-of-type-selector auf 0px setzen?

Die widget-class hat ja bereits keinen Außen- und Innenabstand und die Elemente wie Überschriften, Kontakt-Thumbnails etc, haben afaik auch keinen Abstand nach oben um den man sich Sorgen machen müsste (oder?)

![sidebar_heading](https://cloud.githubusercontent.com/assets/6545158/17978029/5c4f2448-6af4-11e6-8d39-aceb012b85f1.png)

**Comment by xwolfde** [comment]
Guter Hinweis, dem ich auch auf Anhieb zustimme.
Ich möchte aber erst noch genauer schauen. Wenn ich mich richtig erinnere, haben wir den Abstand der optionalen ersten Überschrift im Contentbereich bei Pages genauso hoch gesetzt wie bei Beiträgen. Dort existiert dann aber auch keine Sidebar.

Mal laut gedacht:

Wenn wir jetzt als Lösung die Sidebar bei Pages weiter unten beginnen, haben wir allerdings das problem, dass dessen Beginn nicht mehr gleich auf mit dem Nebginn einer Seite ist, deren Content eben nicht mit einer SUbüberschrift beginnt.

Die Frage ist eigentlich auch eher die: Ist die Korrektur so richtig? Denn: Die Subübnerschrift ist ja nur Optional. Richtiger wäre es doch, mit dem Text zu beginnen; Denn eine Überschrift hat die Seite ja in der Breadcrumb.
Wenn man dann eine zweite Unterüberschrift hat, dann sollte die ja ein eigenes Kapitel bezeichnen.

Im Beispiel tut es das aber nicht. Da wird die h2 ja nicht als Kapitelüberschrift verwendet, sondern als Subtitel. Und wenn es ein definierter Subtitel ist, dann können wir dem auch eigene Classes mitgeben und brauchen nicht auf ::first schauen.

**Comment by csw-** [comment]
Hm, also die Sidebar würde ich nicht verschieben wollen, da sie dann mit der linken Seitennavigation nicht mehr auf gleicher Höhe ist.
Und ja, wir verwenden die h2 sozusagen als Subtitel, es gibt aber auch Fälle da wird diese direkt als Kapitelüberschrift verwendet (so z.B. bei unserem neuen Forschungszentrum gesehen: https://www.cmts.fau.de/ueber-uns/kontakt/).

**Comment by csw-** [comment]
@xwolfde Wie sollte dies hier dann gelöst werden? Mit einer separaten h2-Formatierung und entspr. Klasse könnte ich auch leben. Müsste dann zwar nochmal über jede Seite aber das wäre dann auch nur ein mal und gut ist.

**Comment by xwolfde** [comment]
Ist in der nächsten Version behoben.
Die h1,h2,h3,h4-Überschriften - mit Ausnahme des definierten Subtitels!- mit denen der Content anfängt, haben kein Padding und auch kein Margin mehr nach oben und sind daher nun auf derselben Sichtlinie wie die Überschrift in der Sidebar.
