### ISSUE TITLE
Sprachwechsler wird bei bestimmten Breakpoints falsch dargestellt

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1286]
Beispiel: https://www.cbi.tf.fau.de

Ab einer bestimmten breite wird der Sprachwechsler-Button falsch dargestellt.
Getestet auf 1087px x 691 px

![Bildschirm­foto 2023-05-08 um 12 56 00](https://user-images.githubusercontent.com/58593037/236806673-4fc56817-e874-4827-8f5f-bc7038e95c26.png)

**Comment by FitoreGashi** [comment]
Wie ich gesehen habe, lädt dies, das `::before` und den Inhalt in dieser Größe. Ich habe im Theme das Ausblenden von `::before` behoben und eine Breite von 100 % hinzugefügt, damit der Text nicht abgeschnitten wird, aber ich denke, der beste Weg ist, es im Plugin zu beheben und zu bestimmen, wo das vollständige Wort angezeigt werden soll und wo nur das Slug-Attribut (hreflang) @lukasniebler @xwolfde
