### ISSUE TITLE
Warning in "Schneller Entwurf"-Box im Dashboard

### ISSUE THREAD

**Issue by cassandre** [RRZE-Webteam/FAU-Einrichtungen#1288]
In der Box "Schneller Entwurf" im Dashboard bekomme ich nach dem Aktivieren der Version 2.3. den PHP-Warning: 
"Warning: Cannot modify header information - headers already sent by (output started at [...]/wp-includes/class-wp-styles.php:290) in [...]/wp-content/themes/FAU-Einrichtungen/functions.php on line 428"

**Comment by xwolfde** [comment]
Kommt da her:
<img width="1225" alt="grafik" src="https://user-images.githubusercontent.com/1070669/236840579-0fd79e1d-be20-4d4e-9920-f3a35a05d1cd.png">


Das kam glaub ich in 2.2 rein...

**Comment by xwolfde** [comment]
Problemquelle: 
https://github.com/RRZE-Webteam/FAU-Einrichtungen/commit/52b47d9881459892837c6ec344f84da7c968084e

**Comment by xwolfde** [comment]
In Issue #1289 gesetzt

**Comment by xwolfde** [comment]
Cookiesetzung wird temporär auskommentiert, womit erstmal der Bug verschwindet.
Der eigentliche Issue wurde neu eröffnet.
