### ISSUE TITLE
Generell soll auch das Artikelbild in der Ansicht abschaltbar sein

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#1289]
Reopened.

Die Umsetzung aus 2.2 muss nochmal neu angegangen werden.

Die Abschaltung der Artikelbildes soll durch den Post-Autoren erfolgen. Momentan wird diese durch ein Cookie gesetzt und wirft dabei auch ein PHP Fehler.

Stattdessen sollte hier ein Custom Field Var gesetz werden, der dann bewirkt, dass zu dem Post das Artikelbild wegfällt.

**Comment by xwolfde** [comment]
Referenz: https://github.com/RRZE-Webteam/FAU-Einrichtungen/commit/52b47d9881459892837c6ec344f84da7c968084e

**Comment by xwolfde** [comment]
Auf Beta/Dev scheint das Feature zu funktionieren. ggf. ist daher nichts mehr zu tun. 
Bitte aber noch mal prüfen.

Ausserdem fiel mir auf, dass der Schalter in einer eigenen Metabox ist. Könnte man den Schalter nicht bei der Metabox des Artikelbildes ergänzen? Oder alternativ in die Metabox der Beitragsattribute:

<img width="373" alt="grafik" src="https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/1070669/66bd7bab-a34a-4c06-8702-96e0bb9a5815">

Wir haben schon so viele Metaboxen...

**Comment by FitoreGashi** [comment]
WordPress-Core ermöglicht keine einfache Änderung vorhandener Metaboxen.

Ich kann jedoch mit anderen erstellten Metaboxen gruppieren

@xwolfde

**Comment by xwolfde** [comment]
@lukasniebler Was denkst, welche der anderen vom Theme  erzeugten Metaboxes hier für eine Vereinigung ein Frage käme?

**Comment by lukasniebler** [comment]
Auf Inhaltsseiten gibt es (zumindest für Template "Inhaltsseite mit Navi")
eine Metabox mit "Seiten-Eigenschaften".

Dort könnte die Funktion mit unterkommen. Problem:
Die Metabox existiert nur auf Inhaltsseiten.

Auf Beitragsseiten gibt es eine Metabox (Beitragsoptionen).
<img width="1404" alt="Bildschirm­foto 2023-05-25 um 10 13 11" src="https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/58593037/7142e50c-1f57-4def-8dea-8de2268c7517">
<img width="282" alt="Bildschirm­foto 2023-05-25 um 10 11 30" src="https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/58593037/c70e3df1-2af7-4ae2-9849-19c9d05fde82">

**Comment by xwolfde** [comment]
Na dann lasst uns doch die Beitragsoptionen nehmen.
