### ISSUE TITLE
Neue Theme-Screenshots

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#1292]
Für Version 2.3 oder spätestens 2.4 brauchen wir für die Theme-Auswahl jeweils neue  Screnshots.

**Comment by lukasniebler** [comment]
Hier wär ein Screenshot von meiner Testinstanz
![Bildschirm­foto 2023-05-16 um 10 52 16](https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/58593037/468430d6-741e-46b3-a289-07d9470b2497)

**Comment by xwolfde** [comment]
- [ ] Zentrales Theme FAU-Einrichtungen
- [ ] FAU-Med
- [ ] FAU-Phil
- [ ] FAU-Nat
- [ ] FAU-RW
- [ ] FAU-TF
