### ISSUE TITLE
Custom-News 3 columns

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1293]
Für die neue Startseite der FAU wird eine Reihe von verschiedenen Shortcodes genutzt.
Der Custom-News-Shortcode soll die News-Artikel ausgeben, wobei das Design leicht geändert werden soll:
- Der Rahmen der Bilder soll nur noch eine 1px dicke, hellgraue Linie sein, (damit Bilder mit weißem Grund in der Grid bleiben)
- Parallel dazu soll der Schatten verschwinden

## Ist-Zustand
<img width="867" alt="Bildschirm­foto 2023-05-08 um 14 26 23" src="https://user-images.githubusercontent.com/58593037/236823443-dc355a10-9ee2-4d06-a319-b5c93a2345aa.png">

## Soll-Zustand
Im folgenden Screenshot, siehst du eine Übersicht:

## Aufbau der Startseite
Im Folgenden siehst du eine Auflistung der derzeit geplanten Inhalts-Elemente auf der Startseite von oben nach unten:

- Der überarbeitete Slider (Bereits vorhanden)
- Der überarbeitete Gruppeneinstieg (Portalmenü mit Listendarstellung - Bereits vorhanden)
- HTML HR-Trenner (In Arbeit)
- H2 Aktuelles
- [custom-news cat="Musterbeiträge" columns="3" type="img_first" hide="date, category" number="6" hideduplicates="true"] Übernommen von: https://www.wordpress.rrze.fau.de/plugins/inhaltsseiten-mit-funktionen-erweitern/elements/news/custom-news-beispielumsetzung/
- Trenner (HR)
- CTA mit Suche oder Button (In Arbeit für 2.4)
- Trenner (HR)
- Columns 2 valign="center" + Kombination von limit-width, Bildern, text und Button
- Trenner (HR)
- Wiederholung x2
- CTA mit Button (In Arbeit für 2.4)
- Trenner (HR)
- Überschrift, Video
- Trenner (HR)
- Veranstaltungen + Columns
- Trenner(HR)
- Portalmenü unten (In Arbeit für 2.4)

![Startseite Mockup 80523](https://user-images.githubusercontent.com/58593037/236822425-f22bba8a-58e7-4098-b6de-43dbb2c39480.png)

**Comment by cassandre** [comment]
Die Style-Angaben sind in FAU-Einrichtungen.

**Comment by xwolfde** [comment]
Kann dieser Issue zu @lukasniebler ?
