### ISSUE TITLE
Shortcode/Block zur Ausgabe von statistischen Daten

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#1294]
Es ist gewünscht, dass man statistische Daten in ansprechender Form darstellen kann.
In herausgehobener Form ausserhalb eines Textabsatzes mit oder ohne Animation (z.b. bei Aufruf der Seite und Anzeige im Viewport wird die Zahl hochgezählt). 

Beispiele:
<img width="253" alt="grafik" src="https://user-images.githubusercontent.com/1070669/235919566-7a75afc6-b013-4251-9a5f-e0fa2490da8c.png">
Quelle: https://www.tum.de/ueber-die-tum/daten-und-fakten/tum-in-zahlen  (dort auch mit Zählanimation)

Oder so:
<img width="568" alt="grafik" src="https://user-images.githubusercontent.com/1070669/235947378-3b04e74f-95f5-4468-a51f-7c3a46faf31d.png">

**Comment by xwolfde** [comment]
Ebenfalls schöne Umsetzung an der Uni Leipzig:
<img width="914" alt="grafik" src="https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/1070669/035658e7-7312-4f8e-b776-e951411f16de">

**Comment by xwolfde** [comment]
Diskussionsfrage auch: Im Theme oder in RRZE-Elements? @cassandre

**Comment by xwolfde** [comment]
Bei allen Darstellungen haben wir immer:
* EIne Zahl
* Eine Bezeichnung für die Zahl

Und optional:
* ein Symbol dazu

**Comment by xwolfde** [comment]
Weiteres Beispiel:
<img width="755" alt="grafik" src="https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/1070669/4969fc78-6354-402c-abcf-13482309075d">

**Comment by FitoreGashi** [comment]
https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/101202370/6b2f88d6-4a79-4b28-b109-97cf1ed09dd4

Meinten Sie so: Der Benutzer kann drei Attribute hinzufügen: eine Zahl, ein Wort und eine Bild-URL 

[counterword number="115" word="test" image_url="http://localhost/wp-content/uploads/2023/05/mov_icon_co2_blau-svg.png"]

**Comment by xwolfde** [comment]
ja. genauso in der Richtung 
(Bitte bei der Umsetzung aber auch aus A11y Gründen die Media Query/Browser Setting prefers-reduced-motion https://webkit.org/blog/7551/responsive-design-for-motion/ mit berücksichtigen)

**Comment by FitoreGashi** [comment]
ja wir betuzen window.matchMedia('(prefers-reduced-motion: reduce)');
