### ISSUE TITLE
Externe Beiträge ignorieren festgelegte Blogroll-Kategorie

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1298]
Szenario:

1. Startseite Fakultät, Setting: Keine Inhalte, nur Blogroll
2. Blogroll-Kategorie definieren, z.B. Kategorie "Top"
3. Externen Beitrag anlegen und verlinken...

## Issue
Externer Beitrag erscheint in der Blogroll:
https://www.beta.wordpress.rrze.fau.de

**Comment by lukasniebler** [comment]
Ich glaub betrifft einfach alle Beiträge. Scheint wohl die Einschränkung der Blogroll auf eine Kategorie nicht zu funktionieren?

**Comment by xwolfde** [comment]
Ich glaub das hängt mit #1304  zusammen

**Comment by xwolfde** [comment]
Bitte nochmal am Montag prüfen, ob das problem noch auftritt

**Comment by xwolfde** [comment]
wurde damals behoben
