### ISSUE TITLE
Absatztext bei glossary

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#13]
Wenn der Glossar mit mindestens einem Element befüllt wird, sorgt er dafür, daß 
der Absatztext vor oder nach dem Shortcode nicht mehr mit autop versehen wird.

vgl
http://test8.tindu.rrze.uni-erlangen.de/tests/testseite-glossar/

**Comment by csw-** [comment]
Hinweis: Der Fehler tritt auch bei [include] auf.

**Comment by xwolfde** [comment]
Was ist [include]? ^^

**Comment by csw-** [comment]
Die Funktion zur Einbindung von Seiten-Inhalten ( [include id="[page-id]"] ).

**Comment by xwolfde** [comment]
Das ist ein Fremdplugin. Not our business.

**Comment by xwolfde** [comment]
fixed (one more time autop)
