### ISSUE TITLE
Blogroll und Sticky Posts Problem

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#1304]
Die Umsetzung der Sticky Posts ist buggy.
Es werden Posts nach oben gesetzt obwohl die nicht sticky sind, sondern nur weil sie neu sind.

Prüfen.

Relevanter Teil u.a. in page-start.php und page-start-sub.php
```
for($j = 1; $j <= $max; $j++) {
				    $i = 0;
				    $thistag = get_theme_mod('start_prefix_tag_newscontent').$j;    
				    	// retrieve sticky posts
						$sticky_query = new WP_Query( array(
							'post__in' => get_option( 'sticky_posts' ),
							'ignore_sticky_posts' => false,
							'posts_per_page' => $max - $i,
							'post__not_in' => $displayedposts,
						) );

						while ( $sticky_query->have_posts() && ( $i < $max ) && ( $number < $maxall ) ) {
							$sticky_query->the_post();
							echo fau_display_news_teaser( $post->ID );
							$i++;
							$number++;
							$displayedposts[] = $post->ID;
						}
						wp_reset_postdata();

						// retrieve regular posts with specific tags
						for ( $j = 1; $j <= $max; $j++ ) {
							$i = 0;
							$thistag = get_theme_mod( 'start_prefix_tag_newscontent' ) . $j;

							$query = new WP_Query( array(
								'tag' => $thistag,
								'ignore_sticky_posts' => false,
								'posts_per_page' => $max - $i,
								'post__not_in' => $displayedposts,
							) );

							while ( $query->have_posts() && ( $i < $max ) && ( $number < $maxall ) ) {
								$query->the_post();
								echo fau_display_news_teaser( $post->ID );
								$i++;
								$number++;
								$displayedposts[] = $post->ID;
							}
							wp_reset_postdata();
						}

				     while ($query->have_posts() && ($i<$max) && ($number<$maxall) ) { 
					$query->the_post(); 
					echo fau_display_news_teaser($post->ID);
					$i++;
					$number++;
					$displayedposts[] = $post->ID;
				    }
				    wp_reset_postdata();
				    wp_reset_query();

			    }

```

Mir schein, die Suche nach Sticky posts sollte ausserhalb (und vor) der Schleife gemacht werden und nicht mehrmals innerhalb dieser. Ausserdem sollte gecheckt werden, dass die query auch nichts zurückliefert, wenn es keine stickys gibt.

**Comment by xwolfde** [comment]
Vermutung: Wenn es GAR KEINE STicky Posts gibt, liefert die erste Query einfach die neuesten X Artikel.
Und aufgrund von Max-Artikelanzahl bleibt dann kein Platz mehr für die anderen Artikel über.
(Un dggf. brauchen wir bei den Sticky-Posts auch ein Max-Wert? (von 3))

**Comment by xwolfde** [comment]
Notfix gemacht um den Rollout durchführen zu können.

Trotzdem bitte die aktuelle Umsetzung in Dev nochmal unabhängig prüfen.

**Comment by xwolfde** [comment]
Ergänzung für Doku:
Es gibt im Customizer eine neue Option um die Sticky Posts anzuzeigen:
<img width="290" alt="grafik" src="https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/1070669/b76e6d33-9e7a-494e-9810-0615771d0837">


Eine Range-Option für die Anzahl der STicky Posts hab ich mir aber erspart und in der Config den Wert auf 1 gesetzt. Also nur ein, der letzte, Sticky Post wird gezeigt.

**Comment by FitoreGashi** [comment]
Können Sie mir das noch einmal klarstellen? Wir haben eine Option für Sticky Posts. Wenn diese Option aktiviert ist, werden Sticky-Beiträge zuerst angezeigt, gefolgt von den anderen, basierend auf der Gesamtzahl. @xwolfde

**Comment by xwolfde** [comment]
Naja, ich hab ja im Code bereits ein Fix gemacht, der das mit den Sticky Posts jetzt macht.
Mir geht es jetzt darum, dass ihr nochmal prüft, ob ich nichts vergessen habt oder doch noch ein Fehler da ist.

Eine Problemmeldung haben wir gerade tatsächlich schon 2mal bekommen: Vorher gab es wohl noch -zusätzlich neben der Filter nach nach einem Tags- die Filterung der AUsgabe nach der Kategorie.
Diese scheint nicht mehr zu funktieren, die im Customizer auwaählbare Kategorie dient nur noch für die Erzeugung des Links zu weiteren Artikeln, unter der Blogroll.

Ggf. muss also der jetzige Code nochmal darauf geprüft werden, ob und wie man die Kategorie zusätzlich oder auch zusammen mit den Tags benutzt. Wahrscheinlich also zweite Schleife nach der Suche nach Tags.

**Comment by xwolfde** [comment]
Hier ist auch jemand mit der Problemmeldung: https://github.com/RRZE-Webteam/rrze-elements/issues/266

**Comment by xwolfde** [comment]
@FitoreGashi @MManthey Wäre es möglich, dass ihr diese Sache vorzieht? Hierzu bekommen wir gerade von Anwendern viele Tickets rein :/

Also der Wunsch, dass neben Sticky und den Beiträgen mit Tags, wieder die Auswahl der Kategorie, die man anzeigen will, aktiviert wird. Die ist leider herausgefallen...


Also im Prinzip Logik so:

1. Wenn Sticky-Anzeige im Customizer aktiv ist und es 1 Sticky Beitrag gibt, zeige diesen als erstes an. Die Zahl der maximalen Artikel reduziert sich um den Sticky-Beitrag. (Darüber könnte man aber diskutieren, ob man die aus de Zählung nimmt?)
2. Wenn es eine Listung nach ein Schlagwort gibt, welche als erste Erscheinen sollen, dann diese entsprechenden den vorhandenen Regeln anzeigen. (Das scheint wohl auch zu funktionieren),
3. Wenn danach eine definierte Kategorie (dieselbe wie bei de m Link) angegeben ist, dann zeige die letzten Beiträge der Kategorie, sofern die maximale Zahl der anzuzeigenen Artikel noch nicht erreicht ist.
4. Wenn weder Sticky gesetzt, noch Schlagworte zum Anzeigen, noch eine Kategorie gesetzt ist, dann zeige als Fallback die letzten Artikel an (bis zum max), die erstellt wurden, egal zu welcher Kategorie sie gehören.

**Comment by FitoreGashi** [comment]
`<main<?php echo fau_get_page_langcode($post->ID);?>>
    <h1 id="maintop" class="screen-reader-text"><?php the_title(); ?></h1>
    <?php 
    the_content();

    wp_reset_postdata();
    wp_reset_query();

    $number = 0;
    $displayedposts = array();
    $max = get_theme_mod('start_max_newspertag');
    $maxall = get_theme_mod('start_max_newscontent');

    if ($maxall === false || $maxall <= 0) {
        echo 'Invalid maximum post number';
        return;
    }

    $maxpositioncount = get_theme_mod('start_max_tagposition');
    $showsticky = get_theme_mod('advance_show_sticky_posts');
    $maxsticky = get_theme_mod('advance_show_sticky_posts_max');

    if ($showsticky) {
        $sticky = get_option('sticky_posts');
        if (!empty($sticky)) {
            // Sticky posts exist
            $sticky_query = new WP_Query(array(
                'post__in' => get_option('sticky_posts'),
                'ignore_sticky_posts' => false,
                'posts_per_page' => $maxsticky,
                'post__not_in' => $displayedposts,
            ));

            while ($sticky_query->have_posts() && $number < $maxall) {
                $sticky_query->the_post();
                echo fau_display_news_teaser($post->ID);
                $number++;
                $displayedposts[] = $post->ID;
            }

            wp_reset_postdata();
        }
    }

    // Retrieve regular posts with specific tags
    for ($j = 1; $j <= $maxpositioncount && $number < $maxall; $j++) {
        $i = 0;
        $thistag = get_theme_mod('start_prefix_tag_newscontent') . $j;

        if (!$thistag) {
            echo 'Invalid tag value';
            continue;
        }

        $query = new WP_Query(array(
            'tag' => $thistag,
            'ignore_sticky_posts' => false,
            'post__not_in' => $displayedposts,
        ));

        while ($query->have_posts() && $i < $max && $number < $maxall) {
            $query->the_post();
            echo fau_display_news_teaser($post->ID);
            $i++;
            $number++;
            $displayedposts[] = $post->ID;
        }

        wp_reset_postdata();
        wp_reset_query();
    }

    $newscat = get_theme_mod('start_link_news_cat');        
    if ($number < $maxall) {
        $num = $maxall - $number;
        $num = ($num <= 0) ? 1 : $num;

        if ($newscat) {
            $query = new WP_Query(array(
                'post__not_in' => $displayedposts,
                'posts_per_page' => $num,
                'has_password' => false,
                'post_type' => 'post',
                'cat' => $newscat
            ));
        } else {
            $query = new WP_Query(array(
                'post__not_in' => $displayedposts,
                'posts_per_page' => $num,
                'has_password' => false,
                'post_type' => 'post',
            ));
        }

        while ($query->have_posts()) { 
            $query->the_post(); 
            echo fau_display_news_teaser($post->ID);
            wp_reset_postdata();
            $number++;
        }
    }

    if ($number > 0 && get_theme_mod('start_link_news_show')) {
        echo fau_get_category_links();
    }
    ?>
</main>
`   
Here's a walkthrough of the logic:

**Resetting the Query:** The script starts by resetting any post data and query with wp_reset_postdata() and wp_reset_query(). This is done to ensure that any previous queries or posts won't interfere with this particular logic.

**Sticky Posts**: If the "Show Sticky Posts" setting is enabled, the script checks if there are any sticky posts. If there are, it fetches them and displays them first. The number of sticky posts to be displayed is defined in the theme customizer.

**Tagged Posts**: After displaying sticky posts, the script fetches regular posts with specific tags. These tags are dynamically created based on the theme settings. For example, if the maximum position count is set to 3, it looks for tags like startseite1, startseite2, and startseite3. For each tag, a maximum number of posts are fetched and displayed.

**Category Posts:** If there are still fewer posts displayed than the maximum allowed number, it fetches posts from a specific category. If no category is set, it fetches the latest posts without considering the category.

**Fallback:** If there are no sticky posts, no posts with specific tags, and no category specified, the script fetches the latest posts up to the maximum allowed number.

**Displaying the Posts**: Each post is displayed using a custom function (fau_display_news_teaser()). This function is likely defined elsewhere in the theme, and it's responsible for formatting the post data.

**Post Count and Category Links**: Finally, the script checks if any posts have been displayed. If they have, and if the "Show News Links" setting is enabled, it displays category links using the fau_get_category_links() function.

**Comment by FitoreGashi** [comment]
i was debugging, just a sec let me remove and check if there is any other...
