### ISSUE TITLE
Bildlinks und "WP External Links"-Plugin kollidieren

### ISSUE THREAD

**Issue by csw-** [RRZE-Webteam/FAU-Einrichtungen#131]
Ich habe gerade die unschöne Entdeckung gemacht, dass die Formatierung der Bildlinks (innerhalb des Portalmenüs) sich mit der des "WP External Links"-Plugins. überschneidet (siehe Anhang).

Über das Plugin gibt es zwei Möglichkeiten die Überschneidung zu verhindern: 1, Die betroffenen URLs manuell über die Plugin-Einstellungen in die Exclude-Liste aufnehmen. Und 2, Betroffene Links um das Attribut "data-wpel-link" erweitern.

1. Wäre wohl nur bei kleineren Webauftritten möglich, andernfalls kann man wohl davon ausgehen das die betroffenen URLs auch irgendwo im Fließtext verwendet werden. Dort braucht es dann aber wiederrum das Link-Icon. 
2. Müsste man irgendwie so lösen, das man prüft ob das Plugin aktiv ist und falls ja bei der Ausgabe der Bildlinks das Attribut "data-wpel-link" entsprechend hinzufügt und mit "ignore" oder "exclude" belegt...

(Ein weiterer Workaround wäre, man legt einen Redirekt auf den externen Link an und verwendet den Redirekt bei den Bildlinks. Wäre aber schon sehr technisch die Lösung :P )

![bildlinks-linkicon](https://cloud.githubusercontent.com/assets/6545158/18472807/d31bea1a-79b9-11e6-9bc2-24c319bf0035.png)

**Comment by xwolfde** [comment]
Hast du dich auch an die Angaben in der Readme gehalten bei der Konfig des Plugins?

" WP External Link
   with Options: 
    - General Settings: Open external link in same window
    - SEO-Settings: Add "external" rel-attribute, please no "nofollow" !
                    Dont use title-Attribut, it messes with accessibility
    - Style Stettings: Icon 19, No icon for external links with images"

**Comment by csw-** [comment]
Nein (hatte ich übersehen) - allerdings waren die Einstellungen auch in etwa bereits so gesetzt.

Auch der Haken bei "- Style Stettings: Icon 19, No icon for external links with images" ist gesetzt. Sonst hätten wir nämlich direkt unter dem Bild noch ein drittes Link-Icon.

**Comment by xwolfde** [comment]
Sagst du mal bitte eine UR? ich finde keine doppelten Icons....

**Comment by csw-** [comment]
Hier bitte: https://www.wiso.rw.fau.de/international/

**Comment by xwolfde** [comment]
thxs

**Comment by xwolfde** [comment]
ok, wird in Kürze repariert sein. Man wird nichts selbst ändern müssen am Plugin.
