### ISSUE TITLE
Block Editor Upgrade: Theme-Shortcodes zusätzlich als Blöcke bereitstellen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#1314]
Alle Theme-Shortcodes sollen auch als Block für den Block-Editor verfügbar gemacht werden. Dabei soll aber gleichzeitig die klassische Shortcode-Funktion für Nutzer von Classic Editoren erhalten bleiben. 

Folgende Shortcodes/Funktionen sollen auch für den Block Editor als neue Blöcke bereitgestellt werden:

- [ ] fau_portalmenu
- [ ] fau_shortcode_blogroll
- [ ] fau_shortcode_articlelist
- [ ] relevant_posts_shortcode
- [ ] row_outside_box

**Comment by xwolfde** [comment]
counter und hr shortcodes entfernen

**Comment by lukasniebler** [comment]
Sollen wir die Blöcke mit Elements-Block abbilden?

Beispiel: Elements-Blocks zeigt aktuell den Custom-News-Block an, falls das Plugin Custom-News aktiviert ist.
Genauso könnte es die Theme-Blöcke anbieten, wenn das Theme aktiv ist (und die Shortcodes zur Verfügung stehen).

Dann sparen wir uns das komplexe Setup für FAU-Einrichtungen.
