### ISSUE TITLE
Galerie mit Überlagerung bei Dots

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#1318]
Galerien, bei denen die Dots angezeigt werden, scheinen ein Problem mit der Positionierung dieser zu haben. Die Dots überlagern den folgenden Text. 

<img width="1028" alt="grafik" src="https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/1070669/ec744773-aba5-4ca4-b25e-b2e1d7f1b999">

**Comment by hdbhm** [comment]
Hallo, das Problem betrifft uns aktuell auch (z.B. https://sys.cs.fau.de/2023/10/01/emeritierung-wosch). Das Problem scheint ja daher zu kommen, dass der umgebende `ul`-Block der Dots absolut positioniert wird.

Da die Dots ja laut #1253 neu designt werden sollen, hätte ich hier einen schnellen Lösungsvorschlag als Übergangslösung: man könnte den unteren Außenabstand im umschließenden Container erhöhen, so dass der verwendete Platz der Dots mit vom margin abgedeckt wird. Dadurch bleiben alle anderen Abstände der Galerie erhalten und man hat den gewünschten Effekt.

Die entsprechende Zeile wäre hier: https://github.com/RRZE-Webteam/FAU-Einrichtungen/blob/446e89495cc76eb7ae9b8250a1a2bf46e8f1fabf/css/fau-theme-style.css#L13052
