### ISSUE TITLE
Bilder teilweise unscharf im Slider

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#1319]
Ggf. sollten wir die Größe von 1260x350 die der SLider gibt, im image_size vergrößern, so dass Bilder nicht im kleinen 1260er Format geladen werden und dann per Inline-Style vergrößert werden, sondern gleich die richtige ursprüngliche Größe speichern.

**Comment by cibsell** [comment]
Ist das Problem bereits gelöst worden? Leider sind die Bilder in der Bühne immer noch sehr unscharf. Das sieht insbesondere bei Personenabbildungen nicht schön aus.

**Comment by xwolfde** [comment]
Wenn der Issue gelöst worden wäre, wäre er doch geschlossen...

**Comment by lukasniebler** [comment]
Als Ergänzung ist hier noch das Beispiel von der aktuellen hat-Startseite inkl. Slider-Bilder in 4 Formaten:
http://go.fau.de/9v-kv

In meinen Augen muss der Slider auch Bilder im 2facher skalierung erlauben. Auf 1260x315 px kann man nicht genug Pixel unterbringen, um Details scharf darzustellen.

(Da die meisten Monitore 1920px bis 4k unterstützen, sollte der Slider ggf. auch eine höhere Auflösung für solche Bildschirme bereitstellen können... Ansonsten wird das sowieso nicht detailreiche 1260 px Bild auf 1920 gestreckt, was immer zu unscharfen Ergebnissen führt...?)

**Comment by xwolfde** [comment]
Code-Archäologie:
- srcset/sizes Berechnung war in dem Zusammenhang nicht mehr korrekt und lieferte daher keine Werte.
- Die CSS-Anweisungen zur Darstellung nutzten noch einen Hook von 2013 zur mittigen darstellung von Bildern, die vergrößert wurden. ( margin-left: 50%, transform (-50%)). object-fit wurde nicht verwendet.
- Die Bilddimension ist auch im proportional geschnittenen Zustand kleiner als die Bildfläche und wird zusätzlch unten nochmal um 1rem geschnitten für die Höhe des Copyright Textes
- Das Bild hat als Background ein gradient definiert. Wahrscheinlich als Fallback für PNG mit transparenz. Was aber bei diesen DImensionen niemand verwenden sollte. Das erscheint auch obsoleter Code

Wir präsentieren: Seit 2013 gewachsener Code.
