### ISSUE TITLE
Werbung in mobiler Ansicht herunter skalieren oder ausblenden

### ISSUE THREAD

**Issue by csw-** [RRZE-Webteam/FAU-Einrichtungen#132]
Werbebanner werden derzeit in der mobilen Version nicht in ihrer Größe angepasst. (Zumindest bei denen die z.B. am Seitenende mittig eingeblendet werden. Andere Varianten habe ich jetzt nicht getestet.)

Hier wäre es vllt besser die Werbung würde dann für die mobile Ansicht ausgeblendet werden, da sie für die Bildschirmgröße dann auch meist nicht ausgelegt sind. Es bräuchte dann eigentlich eine seperate Werbe-ID auf der dann auch nur Werbung läuft die auch für mobile Devices angepasst ist. 

Oder die sind ggf. so fortschrittlich das die das mit dem eigenen JS-Script prüfen und darauf hin die Ausgaben anpassen. Falls das eine Option wäre, sollte man die Varifast-Leute dazu ggf. mal abholen.

desktop
![werbung_desktop](https://cloud.githubusercontent.com/assets/6545158/18473218/080a49ea-79bc-11e6-8f3a-0235d6689dba.png)

mobile
![werbung_mobile](https://cloud.githubusercontent.com/assets/6545158/18473219/0ba3c5cc-79bc-11e6-9fd3-a298801cbad2.png)

**Comment by xwolfde** [comment]
Ja. Da läuft seit geraumer Zeit eine Rückfrage. Leider mangelt es bei den Angefragten an Verständnis der Problematik.

**Comment by csw-** [comment]
Schade. die Lösung wäre eigentlich für die Kunden als auch den Anbieter am elegantesten.. Aber naja, zielgruppengerechte Werbung wird ja heutzutage auch überbewertet. 

Sollte die Werbung auf mobilen Devices nicht einfach ausgeblendet werden, oder dies zumindest als Option in der Theme-Konfig bereitstellen?

Mit separaten IDs müsste man sich auch erstmal auf ein paar Viewports einigen, und für diese dann jeweils min- und max-Abmessungen der Werbeflächen festlegen.

**Comment by xwolfde** [comment]
Es reicht ja nicht nur die Frage nach der Auflösung der Bilder: Der kleine Viewport macht es notwendig, auch die Reihenfolge der Inhalte vor und nach der Werbung zu ändern. 
Zudem ist es so, daß die WP-eigene Erkennung von Mobilgeräten allein auf die freiwillige und nicht zuverlässige UserAgent-Angabe des Browsers auf dem Smartphone beruht. Diese ist aber allenfalls bei den BuildIn-Browser noch korrekt.  Denn aufgrund der Tatsache, daß die Erkennung in der Vergangenheit dazu geführt hat, daß Menschen mit Mobilen Devices nicht derselbe Inhalt gezeigt wurde, sind viele Browserhersteller dazu übergegangen, keinen Hinweis mehr auf das Gerät im UserAgent anzugeben.

Die einzige sinnvolle Erkennung der Auflösung erfolgt mit Hilfe von CSS oder mit JavaScript auf dem jeweiligen Client selbst. 
Einziger Workaround für ein "guten" Banneradd-Lieferer wäre es, wenn die Bilder mit srcset="" ergänzt ausgeliefert werden. Aber auch das tun die nicht, weil das ja moderner Schnickschnack ist. :/

**Comment by xwolfde** [comment]
Aktueller Code (noch von Agentur) sorgt dafür, daß die Werbung an der rechten Seite bei Auflösungen kleiner als 970 Pixel "verschwindet", da sie außerhalb des verfügbaren Viewports positioniert ist. 
Ein Lösungsvorschlag, wie man derartige Werbung (hoch, nicht breit) in kleinen AUflösungen ohne starke Beeinträchtigung darstellen soll, gibt es nicht. 
Daher wird es jetzt "sauber" ab kleiner als md-Auflösung ausgeblendet.

Gilt nicht für das  breite Inhaltsbanner. Dies wird immer gezeigt und hat keine Probleme.
