### ISSUE TITLE
Warning in block-editor.php

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1325]
Durch Zufall entdeckt.

In Kombination mit dem Blockeditor wird beim öffnen des Customizers und später von einzelnen Seiten die Folgende Warning ausgegeben:
```
[24-May-2023 14:20:20 UTC] PHP Warning:  Trying to access array offset on value of type bool in /Users/x/Local Sites/testumgebung-alice/app/public/wp-includes/block-editor.php on line 450
```

**Comment by lukasniebler** [comment]
WP Version 6.2.2, PHP 8.0.22, nginx

Die Warning tritt nur auf, wenn man den Blockeditor benutzt, eine Seite erstellt / bearbeitet und den Browser refresht.
Theme-Version Version 2.3.22 | Branch: Dev

**Comment by xwolfde** [comment]
Duplicate zu #1353.  Dort genauer. Daher dort ggf gefixt
