### ISSUE TITLE
filtering content of newsfeed on landing page does not work as it used to

### ISSUE THREAD

**Issue by dbblumenthal** [RRZE-Webteam/FAU-Einrichtungen#1326]
I used to filter the posts displayed on the landing page of our lab (https://bionets.tf.fau.de) as follows:

Appearance --> Customize --> Display options --> Entry list ("blogroll") --> Select category --> <Category of posts I want to have displayed on landing page – "News", in my case>

This no longer works. The selection now only has an effect on what's shown when clicking on "More news".

**Comment by xwolfde** [comment]
fixed meanwhile
