### ISSUE TITLE
Portalmenü Darstellung

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1329]
Ich wurde gefragt, weshalb die Titel hier hoch rutschen

<img width="1404" alt="Bildschirm­foto 2023-05-25 um 13 46 31" src="https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/58593037/8328ae96-49af-4537-a381-8aad49ea1471">

https://www.fau.de/research/

**Comment by xwolfde** [comment]
wurd egefixt
