### ISSUE TITLE
Beitragsbild Hochformat

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/FAU-Einrichtungen#1330]
Neben dem hochformatigen Beitragsbild ist zu viel Platz links und rechts. Dadurch ist die Bildbeschreibung an komischer Stelle links bzw. rechts angeordnet. 

![Screenshot 2023-05-25 at 14-44-29 Department Chemie und Pharmazie](https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/8234890/4a61d209-3e33-4f63-a3fd-21002c4483c9)

https://www.chemie.nat.fau.de/2023/05/25/prof-dr-joerg-libuda-in-die-academia-europaea-aufgenommen/

**Comment by xwolfde** [comment]
Wird im nächsten Update behoben sein
