### ISSUE TITLE
Kategorie Mehr Meldungen springt auf Seite 2

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1332]
Bei Klick auf „Mehr Meldungen“ unter den drei Beiträgen auf der Startseite öffnen sich ja die älteren Meldungen, die unter der Kategorie „Aktuelles“ abgelegt sind. Allerdings springt es nach dem Klick direkt auf die zweite Seite der aktuellen Meldungen (https://www.wiso.rw.fau.de/category/aktuelles/page/2/) und lässt damit eine ganze Reihe Meldungen aus (https://www.wiso.rw.fau.de/category/aktuelles/). Das heißt man müsste erst nochmal auf „Neuere Beiträge“ klicken, um die aktuelleren Meldungen zu erhalten. Bei der englischen WiSo-Website existiert das Problem auch. Kann es sein, dass das ebenfalls durch das Update aufgetreten ist bzw. kann ich das irgendwie selbst beheben?

**Comment by fitoreg** [comment]
https://github.com/RRZE-Webteam/FAU-Einrichtungen/issues/1202

**Comment by xwolfde** [comment]
Hab jetzt auch von anderer Siete die Problemmeldung: 
Wenn nämlich nicht genug Meldungen für eine 2. Seite da sind, dann erscheint die Fehlermeldung.

Ich denke, es wäre besser, wenn wir #1202 rückgängig machen.

**Comment by xwolfde** [comment]
Ggf. kann man ja alternativ in dem Customizer eine zusätzliche URL-Eingabe erlauben, in der man ein individuelles Ziel angibt. Wenn das dann belegt ist mit einer gültigen URL, wird diese verlinkt. Ansonsten die Category wie bisher.

**Comment by FitoreGashi** [comment]
Ok, ich werde nach der besten Lösung suchen

**Comment by lukasniebler** [comment]
🎫 http://go.fau.de/9u7cw (aus Helpdesk)

Der Beitrag „Was Moose anders machen als Blütenpflanzen“
https://www.biologie.nat.fau.de/2023/03/01/was-moose-anders-machen-als-bluetenpflanzen/
 
wurde am 1. März 2023 veröffentlicht und war zunächst oben auf der Startseite (entsprechend mit Schlagworte startseite1 / startseite2 / … versehen)
 
Inzwischen sind neuere Beiträge dazugekommen, deshalb haben wir das Schlagwort „startseite…“ entfernt. Dennoch sollte der Beitrag auf erscheinen, wenn der Button „Mehr Meldungen“ auf der Startseite geklickt wird.
Dies ist aber nicht der Fall, stattdessen erscheinen Beiträge aus dem Jahr 2022.
Erst wenn ich dann wiederum auf den Button „Neuere Beiträge“ klicke, erscheint der Artikel „Was Moose anders machen als Blütenpflanzen“ in der richtigen Reihenfolge.

**Comment by FitoreGashi** [comment]
Änderung 'Springe zur zweiten Kategorieseite', zurücknehmen, bis wir eine effektive Lösung erarbeiten.

**Comment by xwolfde** [comment]
Danke. Ich mach gleich/nachher in Dev auch noch ein paar Commits mit andeen Bugfixes (die nicht beauftragt waren, wo wir aber Rückmeldungen haben).

**Comment by xwolfde** [comment]
Nun erstmal im main von FAU-Einrichtungen.
Die Fakultäten kommen erst nächste Woche dran.
