### ISSUE TITLE
Sidebar filtert h2 heraus in Textfeld oben

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1333]
Im wysiwyg Feld für oben werden Überschriften h2 automatisch beim speichern rausgefiltert, obwohl die Option im Customizer aktiviert ist.

<img width="163" alt="Bildschirm­foto 2023-05-25 um 16 11 43" src="https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/58593037/bdaf6e06-e032-4ebd-bd0a-c861f14a11cb">

**Comment by lukasniebler** [comment]
Beispiel:
https://www.wordpress.rrze.fau.de
<img width="387" alt="Bildschirm­foto 2023-05-25 um 16 15 32" src="https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/58593037/8b6ce5d7-01a2-4edc-b0fa-4c9a00874348">

Musterseiten müsste hier ein h2 sein.

**Comment by xwolfde** [comment]
uuuh.. haben wir da mit kses doch zu viel....?
