### ISSUE TITLE
Scrollstories embed von cloudflare.com

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1334]
# Ist-Zustand
In scrollstories.php werden die Skripte aktuell von Cloudflare CDN geladen:

```php
// Enqueue necessary JavaScript files
function scroll_page_scripts() {
    wp_enqueue_script( 'd3', 'https://d3js.org/d3.v5.min.js' );
    wp_enqueue_script( 'scrollmagic', 'https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.7/ScrollMagic.min.js' );
    wp_enqueue_script( 'animation-gsap', 'https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.7/plugins/animation.gsap.min.js' );
    wp_enqueue_script( 'debug', 'https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.7/plugins/debug.addIndicators.min.js' );
    wp_enqueue_script( 'scroll-page-script', get_template_directory_uri() . '/js/fau-scroll-stories.min.js', array( 'jquery', 'd3', 'scrollmagic', 'animation-gsap', 'debug' ), '1.0.0', true );
}
```

# Soll-Zustand
Externe Skripte sollten nicht über ein CDN geladen werden, sondern lokal im Projekt eingebunden sein.

@FitoreGashi Könnt Ihr die notwendigen Skripte für die Scrollstories noch lokal einbinden?

https://github.com/RRZE-Webteam/FAU-Einrichtungen/blob/cd20af23637d48f7a4802543d434f55c04ccc864/page-templates/scroll-stories.php#LL7C1-L14C2

**Comment by xwolfde** [comment]
Nebenbei haben wir damit natürlich auch ein Datenschutz- und Perfrormanceproblem.

**Comment by FitoreGashi** [comment]
Ja, ich kann sie speichern. Kann ich in js einen neuen Ordner mit dem Namen „cloudflare-scrollmagic“ erstellen?

**Comment by xwolfde** [comment]
Ja, aber in /src/js und dann über das Gulpdskript dann die produktive JS in /js kopieren/erstellen lassen

**Comment by xwolfde** [comment]
done
