### ISSUE TITLE
Slider lädt "unten"

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/FAU-Einrichtungen#1335]
Der Slider lädt das 2. Bild beim Aufrufen der Webseite (Firefox + Chrome) unter dem 1. Bild, bevor es dann "umswitcht" und ihn korrekt darstellt. Das sieht nicht schön aus... Ist zwar nur für einen kleinen Zeitraum, aber es reicht, um einen Screenshot zu machen... 

![Unbenannt-1](https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/8234890/5fcde618-2bf7-4d4e-95c5-2bfdb44bd718)

**Comment by xwolfde** [comment]
Ist ein Dup zu #1310

**Comment by xwolfde** [comment]
Im Dev gefixt
