### ISSUE TITLE
Portalmenü Listview Shortcode

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1336]
Das Padding fehlt wohl, wenn man die neue Darstellung per Shortcode einbindet.
![Bildschirm­foto 2023-05-26 um 09 16 22](https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/58593037/fac5d837-f7ff-42c0-a257-2f7d4b52bd1b)

siehe am Seitenende: https://www.wordpress.rrze.fau.de/themes/fau-einrichtungen/shortcodes/portalmenus/beispiel-portalmenu-auf-dem-standardtemplate/?preview_id=18677&preview_nonce=206b247a75&_thumbnail_id=-1&preview=true

**Comment by xwolfde** [comment]
Bereits in #1321 gelöst.
Muss dann noch ausgerollt werden.
