### ISSUE TITLE
Bildunterschriften alle nach links gerückt

### ISSUE THREAD

**Issue by AndyFau** [RRZE-Webteam/FAU-Einrichtungen#1338]
Seitdem diese neue Version eingespielt wurde, sind die Bildunterschriften alle nach links gerückt (siehe Screenshot)

![Verrückte Bildunterschrift](https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/135023366/c562fae9-4d59-42df-931e-868d56a957fe)

**Comment by xwolfde** [comment]
Wird im nächtsten Update glöst sein.
Im Dev.
