### ISSUE TITLE
Links im Portalmenü

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Einrichtungen#134]
Im Portalmenü sind ja sowohl die Bilder als auch die Textlinks anklickbar und sollen eigentlich beide auf die zugehörige Seite führen. Die Links unter den Bildern zeigen aber auf die Portalseite zurück, so dass sie einfach nur neu lädt. Das sollte geändert werden.

Link: https://kunstgeschichte.cms.rrze.uni-erlangen.de/forschung/forschungsprojekte/

**Comment by csw-** [comment]
Jepp, aber ist das nicht auch das Problem bei #133 ?

**Comment by AstridSemm** [comment]
Habe ich schon wieder nicht richtig hingeguckt? Sorry!

**Comment by xwolfde** [comment]
Wie lang war die aktuelle Version noch auf dem testserver. Warum werden solche Bugs eigentlich erst dann bemerkt, wenns released ist.... verflixtundzugenähtverdammteundhimmerherrgottspotzblitz

**Comment by xwolfde** [comment]
Im nächsten Update repariert. In Kürze.
