### ISSUE TITLE
Unnötige Pfeile in der Hauptnavigation

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Einrichtungen#135]
In der Hauptnavigation erscheint ein Pfeil neben dem Menüpunkt, wenn es Unterseiten gibt. Dummerweise hat dieser Pfeil überhaupt keine Funktion - er verwirrt grundsätzlich nur den Besucher. Kann man das vom Theme her unterbinden?

![bildschirmfoto 2016-09-14 um 15 40 43](https://cloud.githubusercontent.com/assets/11296947/18514424/dca48fd2-7a91-11e6-9fde-6334f17ea122.png)

**Comment by xwolfde** [comment]
This is not a bug, this is a feature.

**Comment by AstridSemm** [comment]
This does not answer my question. Is it possible to oppress, subdue, squelch this feature? If so: How? ^^

**Comment by xwolfde** [comment]
Nein, ist so.

**Comment by AstridSemm** [comment]
Ok, dann lautet die Lösung: Keine Unterseiten in die Hauptnavi, die werden dort sowieso nicht angezeigt.

**Comment by xwolfde** [comment]
Muss doch nochmal ran..

**Comment by xwolfde** [comment]
In 1.6.15 behoben
