### ISSUE TITLE
404-Fehler auf fau-image-caption-editor.min.js im Backend

### ISSUE THREAD

**Issue by cassandre** [RRZE-Webteam/FAU-Einrichtungen#1350]
Das neue FAU-Theme sucht im Backend vergeblich nach einer /wp-content/themes/FAU-Einrichtungen/js/fau-image-caption-editor.min.js?ver=1.0.:

`"GET /wp-content/themes/FAU-RWFak/js/fau-image-caption-editor.min.js HTTP/2.0" 404 64440 "https://www.jura.rw.fau.de/wp-admin/"`

**Comment by xwolfde** [comment]
im nächsten dev gefixt
