### ISSUE TITLE
Bildlinks auf Inhaltsseiten werden nicht durch Customizer Größen-Setting beeinflusst

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1356]
Aus Helpdesk ( http://go.fau.de/9u8cb )

Wenn auf der Startseite eine Größe für Bildlinks festgelegt wird, scheint diese keinen Einfluss auf die Darstellung der Bildlinks zu haben.

![Bildschirmfoto 2023-06-22 um 13 11 40](https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/58593037/fc507497-d892-4867-8b2e-95ad8d976472)

Gibts da einen Trick? Schaffe es auch nicht, die Bildlinks auf meiner Testinstanz zu beeinflussen. Der Shortcode dagegen kann es https://www.wordpress.rrze.fau.de/themes/fau-einrichtungen/shortcodes/bildlinks/anpassung-der-bildgroessen/

Zeigt aber auf der Doku andere Bildgrößena ls im Dropdown wählbar.

**Comment by xwolfde** [comment]
Bist du sicher dass das Bild wirklich nicht die Größe nutzt?
Das CSS/der Browser kann aufgrund der responsivität dann nämlich eine andere Darstellungsgröße wählen-

**Comment by lukasniebler** [comment]
Bei mir sieht's so im Inspektor aus:
![Bildschirmfoto 2023-06-22 um 13 41 16](https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/58593037/fe5f8907-044b-42d4-9ceb-b43df919d160)

**Comment by xwolfde** [comment]
Ich fürchte wir müssen bei den Bildlinks mal ordentlich refactoren.

Da ist zu viel von der Vergangenheit drin, was mitgezogen wurd eim Code und alles sehr strapaziert.
WIr müssen uns da aber dann entscheiden verschiedene Optionen zu entfernen und somit die Abwärtscompatibiltät einzuschränken.

**Comment by xwolfde** [comment]
Dieses problem sollte bei der nächsten version behoben sein.

Aber Achtung: DIe globalen Optionen im Customizer können dies ändern UND die Breite ist auch abhängig von dem verfügbaren Platz.
