### ISSUE TITLE
Übersicht über Kontakte verstecken

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Einrichtungen#136]
Die mit FAU Person angelegten Kontakte sind grundsätzlich Beiträge; wenn man sich eine Kontaktseite anzeigen läßt, gibt es in der Breadcrumb einen Menüpunkt "Kontakt", der auf eine (wohl dynamisch erzeugte Kategorie-)Seite mit einer Übersicht über alle Kontakte führt. 

Das wird allgemein als recht verwirrend empfunden und ich wurde schon mehrfach gefragt, ob man diese Seite nicht "verstecken" kann, so dass der Besucher sie gar nicht erst zu Gesicht bekommt. Diese Frage gebe ich hierher weiter.

![bildschirmfoto 2016-09-14 um 15 46 10](https://cloud.githubusercontent.com/assets/11296947/18514624/9d90ab5e-7a92-11e6-9fab-2f0306178937.png)

![bildschirmfoto 2016-09-14 um 15 47 06](https://cloud.githubusercontent.com/assets/11296947/18514645/a9f367ba-7a92-11e6-8c0e-aa8fa72c2c19.png)

**Comment by xwolfde** [comment]
nein, geht nicht

**Comment by AstridSemm** [comment]
Dann weiß ich Bescheid und der issue kann zu.
