### ISSUE TITLE
Kategorie und Datum in Blogroll

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Einrichtungen#1363]
Auf der Startseite intern.fau.de waren gerade Kategorie und Datum in der Blogroll doppelt. Einmal konnte ich die beiden Werte deaktivieren (im Customizer) - wo kann ich die Ansichtanderen beiden deaktivieren

<img width="737" alt="image" src="https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/9526974/5b023d76-2705-438f-ba6f-ab38d6a09c9c">

**Comment by lukasniebler** [comment]
@wrcg 
Auf intern.fau.de wird eure Blogroll händisch über den Shortcode [blogroll cat="fau-intern" tag="" num=2] erzeugt.
https://www.wordpress.rrze.fau.de/themes/fau-einrichtungen/shortcodes/shortcode-blogroll/

hidemeta="true" versteckt die Ausgabe von Kategorie + Datum

**Comment by wrcg** [comment]
danke
