### ISSUE TITLE
width bei Artikelbild falsch 

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#1364]
Nochmal ran, da das width: inhertit in der verwendeten KOnstallation nicht passt:
<img width="1953" alt="grafik" src="https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/1070669/3d988075-de2e-404e-96fb-4541291e3e3a">

**Comment by wrcg** [comment]
<img width="794" alt="image" src="https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/9526974/af30506e-bbe9-41ae-86b2-89dc0348242b">
hier auch...
ich denke, es liegt daran, dass die BU nicht automatisch umbricht (mit kurze BU passt alles wieder...)
<img width="757" alt="image" src="https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/9526974/eaa59104-de38-480b-b583-af368a28655a">

**Comment by xwolfde** [comment]
Ja, die BU war der Auslöser des ganzen.

Bzw. eigentlich die urururalte Art der Ausrichtung mit floating => Relikt aus 2013.

**Comment by xwolfde** [comment]
Im dev
