### ISSUE TITLE
Bildmittelpunkt bei Slider festlegen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#1365]
Mit Hilfe neuer Features des Block Editors ist es möglich, bei Artikelbildern den Bildmittelpunkt festzulegen; Dies hilft gerade bei Bildern, die optisch geschnitten werden, die wichtigen teile sichtbar zu lassen.
Es soll geprüft werden, ob ein solches Feature auch für die Sliderbilder machbar ist.
Wenn das nur mit den Blockeditor funktionieren wird, dann wäre es für mich ok, dass diese Funktion  nur bei aktivierten Block Editor zur Verfügung steht.

**Comment by lukasniebler** [comment]
Blockkomponente für die Auswahl des Fokuspunkt:
https://developer.wordpress.org/block-editor/reference-guides/components/focal-point-picker/

**Comment by xwolfde** [comment]
via Plugin
