### ISSUE TITLE
Button "Portal XYZ" aus der Hauptnavi ausblenden

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Einrichtungen#137]
Im Flyout der Hauptnavigation steht immer ganz unten ein Button "Portal (Portalname)". Es gibt Kunden, die das als verwirrend empfinden, sie wüßten gern, ob dieser Button sich ausblenden läßt (zumal die Portalseite ja sowieso aufgerufen wird, wenn man den Menüpunkt anklickt).

In diesem Beispiel ist es "Portal Allgemeines".
![bildschirmfoto 2016-09-14 um 15 50 15](https://cloud.githubusercontent.com/assets/11296947/18514806/47f96b4e-7a93-11e6-832a-49b2bc1bc594.png)

**Comment by xwolfde** [comment]
Ja

**Comment by AstridSemm** [comment]
Ahja?

**Comment by xwolfde** [comment]
Man kann den Pretitel "Portal" ändern. Ansonsten ist der Button Teil des Designs und daher nicht wegzumachen.
