### ISSUE TITLE
Slider in Fakultätsthemes (Mobile) – Falsche Farbe im Hintergrund

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1371]
In der mobilen Ansicht wird derzeit in den Fakultätsthemes die falsche Farbe genutzt (s. Screenshot).

![Bildschirmfoto 2023-07-11 um 08 07 32](https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/58593037/f5898956-cf13-44d9-af1c-5e001081d8cd)

**Comment by xwolfde** [comment]
Das muss leider bis mindestens 2.4 warten.

**Comment by xwolfde** [comment]
kann ich nicht nachvollziehen in der aktuellen version?

**Comment by xwolfde** [comment]
ggf schon zwischendrin von fito gelöst?
