### ISSUE TITLE
Menüpunkte im Hauptmenü auf bestimmten Bildschirmgrößen unerreichbar

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1376]
Betroffen: Safari, Chrome, Firefox

Wenn das Browserfenster auf kleinere Größen wie z.B. 839 px Breite gezogen wird sind alle Menüpunkte unter der Fold unerreichbar.

Zu sehen auf https://www.wordpress.rrze.fau.de Menü Menüpunkt unter Plugins

**Comment by xwolfde** [comment]
Hm, kann ich nicht nachvollziehen, ich hab da einen scrollbalken:
<img width="1049" alt="grafik" src="https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/1070669/7b2f0a8d-03ed-4d4a-b404-689c4421d4d6">

**Comment by lukasniebler** [comment]
Wenn der Bildschirm nicht so hoch ist (egal ob in Safari oder Firefox) erreiche ich auch mit Scrollbalken den Portalbutton nicht, weil der Scrollbereich außerhalb der Bildschirmfläche liegt.

Man muss erst ans komplette Seitenende der Inhaltsseite scrollen, bevor das Hauptmenü zum Ende scrollt.

**Comment by lukasniebler** [comment]
Bei Chrome gibt es bei mir zudem gar keine Scroll-Leiste im Menü...

**Comment by xwolfde** [comment]
Leider noch nicht gelöst, aber kein Blocker für die neue Version, da der Bug schon vorher da war.

**Comment by xwolfde** [comment]
@FitoreGashi @danielboese Könntet ihr da noch reinschauen? Der Bug muss wohl in 2.3 reingekommen sein und war bisher nicht aufgefallen (wer nutzt schon noch Chrome und wer hat Seiten mit so viel Subpunkten :) ) 

Wahrscheinlich ist es nur eine Kleinigkeit (ein fehlenden scroll-offset oder so).

Bitte auf basis der letzten Dev arbeiten. Ich hab die letzten Tage noch einige Sachen an Icons gemacht.

**Comment by xwolfde** [comment]
In der neuen Version behoben.
