### ISSUE TITLE
Hauptmenü - Feedback von Kundenseite

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1377]
Für das Hauptmenü gab es mit dem neuen Design die Folgenden Kritikpunkte, die wir beim Relaunch für das neue Design berücksichtigen sollten:

- [x] "Das Hauptmenü sieht seltsam aus, wenn man nur wenige Menüpunkte auf einer Website hat. Vor allem das Zentrierte ist irgendwie komisch". – "Wir dachten zuerst es wäre vielleicht ein Fehler"
- [x] "Ist es Absicht, dass alles Sub-Menüs zentriert untereinander stehen? Das ist auf einem mobilen Gerät evtl. hilfreich, aber auf einem PC/MAC finde ich die UX optimierbar."

**Comment by xwolfde** [comment]
Hab wg. dem Menu gerade nochmal mit SIlke gesprochen. Das es nicht schön ist ist klar, aber eine bessere Lösung gibt es nicht. Andere Lösungen würden an anderen Stellen Probleme machen.
Empfehlung könnte auch sein, dass er seine Menüinhalte ggf. strukturiert und nicht Obermenüpunkte macht, worunter dann nur 3 oder wenige Einzelelemente folgen.

**Comment by lukasniebler** [comment]
Naja das ist jetzt einfach ein Sammler für das Feedback das wir dazu bekommen.
Wir wissen beide, dass Lehrstuhlseiten fast alle gleich strukturiert sind und das Umstrukturieren hier auch keine Lösung ist. V.a. da es einfach nicht genug Inhaltsseiten für ein Umstrukturieren gibt.

Ob oder wie das im zukünftigen Relaunch berücksichtigt wird ist dann eine andere Sache. Für den Rebrush ist das erstmal unwichtig. Für den Relaunch sollte man es zumindest im Hinterkopf behalten.

**Comment by xwolfde** [comment]
Wird mit der neuen Option #1390 und der daraus folgenden Umsetzung gelöst.
