### ISSUE TITLE
Feedback von Kundeseiten: sticky Headerbereich ist sehr dominant

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Einrichtungen#1378]
der Stickybereich oben mit Metanavi, Logo und Hauptnavi ist sehr groß, so dass man bei kleinen Monitoren/Laptops nur sehr wenig Inhalt sieht, Header nimmt fast 1/3 des sichtbaren Bereichs ein. -> gerne schmaler machen :-) oder schnellerer Umbruch zur mobilen Ansicht...

**Comment by lukasniebler** [comment]
Bereits unter https://github.com/RRZE-Webteam/FAU-Einrichtungen/issues/1252 für die Agentur aufgeführt.
