### ISSUE TITLE
align-right mag nicht

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Einrichtungen#1379]
<img width="652" alt="image" src="https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/9526974/60dd2059-5574-4af1-9cc8-cb7bfdde69d3">
https://meinstudium.cms.rrze.net/

**Comment by xwolfde** [comment]
?? Wo kommt denn diese Class her?
<img width="594" alt="grafik" src="https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/1070669/8ad56c60-0314-43c2-b137-61d50efd3fa9">


Also das Theme hatte definitiv niemals so einen Class-Name.
Der korrekte Name wäre `alignright`.

**Comment by lukasniebler** [comment]
Aus dem Blockeditor. Da wir aber noch keinen Gutenberg-Support bieten muss man die alignright klasse einfach händisch im Blockeditor setzen.

**Comment by xwolfde** [comment]
Wie bedauerlich, dass der Editor einfach so Classes erfindet, die das Theme nicht kennt :)

**Comment by wrcg** [comment]
danke! so geht's :-)

**Comment by xwolfde** [comment]
#1380
