### ISSUE TITLE
Hochformat-Bilder in Beiträgen werden auf der Beitragsseite gestreckt

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1385]
Hochformat-Bilder in Beiträgen werden auf der Beitragsseite gestreckt.

Details: http://go.fau.de/9visn
Beispiel: https://www.gmp.tf.fau.de/2023/08/10/new-group-leader-in-nanomechanics/

**Comment by xwolfde** [comment]
fixed in dev
