### ISSUE TITLE
Slider gibt Übersetzte Beiträge doppelt aus

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1387]
Der neue Startseiten-Slider gibt übersetzte Beiträge doppelt aus, einmal in deutscher und englischer Sprache.

Betroffen sind Websites die das Multilang Plugin im Modus "einsprachig" nutzen und den neuen Startseiten-Slider verwenden.
=> Man kann derzeit nicht das neue Startseitenlayout auf Mehrsprachigen Websites nutzen, wenn Sie im einsprachigen Modus konfiguriert wurden.

http://go.fau.de/9vfhc

**Comment by lukasniebler** [comment]
s. auch https://github.com/RRZE-Webteam/FAU-Einrichtungen/issues/1206

**Comment by xwolfde** [comment]
Hm.. die Websites für die der Slider gemacht wurde, sind Fakultätsportale. Und diese sind allesamt zweisprachige in Domains.

Daher: Geringe Prio.

**Comment by xwolfde** [comment]
Wird über #1398 workarounded lösbar werden.

**Comment by lukasniebler** [comment]
Aus http://go.fau.de/9v0hl – Gibt es den Workaround schon in der kommenden Version?

**Comment by xwolfde** [comment]
nein. Nicht Teil von 2.4

**Comment by xwolfde** [comment]
display wurde gesetzt. Dies aber nochmal in 3.0 prüfen.

**Comment by xwolfde** [comment]
Ich wüsste nach wie vor nicht, wie wir das Themeseitig lösen soll was das Multilang-Plugin macht. Sehe ich nicht als Theme-Sache.
