### ISSUE TITLE
Rechtsbündige Bilder haben seit neuem Top-Margin

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1388]
Von Kundenseite:

- Bilder die Rechtsbündig eingebunden werden haben seit neustem einen Top-Margin, damit sind sie aber nicht mehr auf einer Linie mit dem Text

http://go.fau.de/9vdmu

**Comment by xwolfde** [comment]
Hm... hatten wir das nicht schon irgendwo als Issue?

**Comment by xwolfde** [comment]
ok, ab der nächsten version wird das erste bild ohne margin-top ausgestattet
