### ISSUE TITLE
Erstellen im Customizer zwei Optionen für den Hauptmenüstil

### ISSUE THREAD

**Issue by FitoreGashi** [RRZE-Webteam/FAU-Einrichtungen#1390]

**Comment by lukasniebler** [comment]
Aktuell erreicht man die Navigationselemente der 1. Ebene nicht mehr, wenn das optionale DropDown-Menü ausgewählt wird.
Für das Dropdown-Menü müsste wahrscheinlich Hover aktiv sein, damit Nutzer die Punkte erreichen.
(Ich weiß nicht, wie das auf Touch-Geräten aussieht, ob man durch Hover dort dann auch die Punkte erreichen kann, wenn Nutzer zweimal klicken)

**Comment by FitoreGashi** [comment]
Da die Hover-Option vor einiger Zeit aus dem Menü entfernt wurde, habe ich die gleiche Logik im kleinen Dropdown umgesetzt. Zudem gibt es am Ende des Dropdowns einen 'Portal'-Button.
![Screenshot 2023-10-04 at 11 41 18](https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/101202370/13556261-c937-439d-9a94-78222f678126)

**Comment by lukasniebler** [comment]
Hi Fitore,

den hatte ich übersehen. Kann man ihn vielleicht noch farblich hervorheben, ähnlich wie im Mega-Menü? Aktuell ist der Hover-Effekt auch anders als bei den anderen Menüpunkten:

<img width="430" alt="Bildschirmfoto 2023-10-04 um 12 01 20" src="https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/58593037/bae4523c-9cd9-4df5-bda5-b0a8911a757c">
<img width="430" alt="Bildschirmfoto 2023-10-04 um 12 01 55" src="https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/58593037/7eba082e-8cb7-4c39-b08e-5f6744abcdfc">

**Comment by FitoreGashi** [comment]
Ja, ich habe gerade gesehen, dass der Hover anders ist. Wir werden diesen Fehler beheben :) @danielboese
