### ISSUE TITLE
Startseiteninhalt verbergen funktioniert nicht

### ISSUE THREAD

**Issue by cassandre** [RRZE-Webteam/FAU-Einrichtungen#1392]
Customizer > Erweitert > Templates > Startseite: Inhalt zeigen 
ändert nichts (auf keinem der beiden Startseiten-Templates).

**Comment by xwolfde** [comment]
fixed in dev

**Comment by xwolfde** [comment]
wurde heute nach abstimmung wieder rausgenommen. 
Wenn kein Content angezeigt werden soll, darf halt kein Content eingegeben werden
