### ISSUE TITLE
Letzte Beiträge auf Startseite: Seitentitel falsch

### ISSUE THREAD

**Issue by cassandre** [RRZE-Webteam/FAU-Einrichtungen#1393]
Customizer > Startseite
Wenn man "Deine letzten Beiträge" wählt, wird im Header der Titel des ersten Beitrags angezeigt. 

-> Wechsel auf "Eine statische Seite"
-> Seite für die Beitragsseite setzen und speichern
-> zurück auf "Deine letzten Beiträge wechseln und speichern
=> der Titel der vorher gesetzten Beitragsseite wird im Header angezeigt.

**Comment by xwolfde** [comment]
fix in dev
