### ISSUE TITLE
Schriftfarbe Portalbutton bei med, nat, tf falsch

### ISSUE THREAD

**Issue by cassandre** [RRZE-Webteam/FAU-Einrichtungen#1394]
Der Portal-Button im Hauptmenü ist bei med, nat, und tf in weißer Schrift, obwohl auf der hellen Farbe ansonsten schwarz verwendet wird. Bei phil ist es interessanterweise korrekt. 
Vgl. aufgeklapptes Menü auf https://www.med.fau.de/ vs. https://www.phil.fau.de/.
![Bildschirmfoto 2023-09-26 um 11 57 08](https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/4435815/9f77f124-007f-4432-8347-ec358f123363)
![Bildschirmfoto 2023-09-26 um 11 58 04](https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/4435815/67c2b204-ff6c-4726-804f-5bbaa05c6b89)

**Comment by xwolfde** [comment]
fixed in dev
