### ISSUE TITLE
wpautop-Problem in der Sidebar und WYSIWYG-Editor

### ISSUE THREAD

**Issue by cassandre** [RRZE-Webteam/FAU-Einrichtungen#1395]
Wenn für die Sidebar der Editor aktiviert ist, wird der Text im Frontend nicht umgebrochen.
Wahrscheinlich seit das allgemeine wpautop im Downloads-Plugin deaktiviert wurde.

Lösung in FAU-Einrichtungen/template-parts/sidebar-textabove.php bzw. FAU-Einrichtungen/template-parts/sidebar-textbelow.php, Z. 11-13: if-Bedingung weglassen. 

Funktioniert nicht:
````
if ($useeditor==false) {
    $text = wpautop($text);
}
````

Funktioniert:
````
$text = wpautop($text);
````

![Bildschirmfoto 2023-09-26 um 12 35 31](https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/4435815/906623fc-1faf-4f19-bcbb-b8d60caf126b)

![Bildschirmfoto 2023-09-26 um 12 36 05](https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/4435815/9bd83bd5-2ac9-46eb-a093-707030de2bf5)

**Comment by lukasniebler** [comment]
🎫 http://go.fau.de/9vinz

**Comment by xwolfde** [comment]
fixed in dev
