### ISSUE TITLE
Linksymbole in den Bildlinks

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Einrichtungen#140]
Nachdem wir ja jetzt das Plugin haben, das externe Links kennzeichnet, bräuchten die Bildlinks die fest eingebauten Linksymbole ja nicht mehr - zumal sie recht gern genutzt werden, um Portalseiten zu basteln. 
Beispiele: 
https://anglistik.cms.rrze.uni-erlangen.de/information-for-students-portalindex/
und
https://www.versicherungsmarketing.rw.fau.de/team/wissenschaftliche-mitarbeiter/

**Comment by xwolfde** [comment]
Nein, das Symbol innerhalb des Bildes war Teil des Designs und wird so nicht vom Plugin gemacht.
Das Plugin macht nur das Symbol bei dem Textlink.

**Comment by csw-** [comment]
Das Icon innerhalb des Bildes sollte auch beibehalten werden, da es ja doch recht markant auf einen externen Link hinweist.

Noch eine andere Idee, wie wäre es denn wenn man die Hintergrundfarbe des Icons innerhalb des Bildes variabel macht? 
z.B. kann man Links auf die Fau.de mit blauer Ecke kennzeichnen und Links auf Seiten innerhalb der eigenen Fak behalten eben ihre Fak-farbene Ecke.

**Comment by xwolfde** [comment]
Müsste machbar, sein wenn man der Definition des Menüs die CSS-Klasse für das jeweilige Item ergänzt.
Ich hab da auch schon vorgesehen, dass man im Hauptmenü ind in den anderen Menüs die Klasse mit ausgibt.

Ich hab es im Design aber noch nicht umgesetzt. Denn ich fürchte mich solchen Stellen vor der desktruktiven Kreativität von Leuten, die Freude an bunten Websites haben und das sofort ausnutzen würden :=)

**Comment by csw-** [comment]
Die Idee kam mir mal auf als ich mir über die Seitenstruktur unseres neuesten Webauftritts Gedanken gemacht habe. Es ging darum, das wir in Portalmenüs oft zusätzlich noch Seiten von anderen "Navigationssträngen" hinzufügen, aber rein vom Design kein Unterschied zwischen den eigentlichen Unterseiten und diesen "fremden" Seiten besteht. Hier könnte man dann echte externe Inhalte z.B. mit einem Blauen (vllt auch anderen) Link-Icon versehen und diese navigationsfremden mit der Fak-Farbe versehen. Aber vielleicht ist das alles für diesen Zweck auch unangebracht und ggf. auch überhaupt nicht nötig. War auch nur mal so laut Gedacht...

**Comment by xwolfde** [comment]
Genau da hab ich gestern auch dran gedacht als ich dort die Sache mit den Pfeilen reparierte.
Theoretisch können wir die Klassen (tf,med,fau,nat,rw,phil) nutzen um irgendwas mit den Links zu gestalten.

Mach doch mal ein Vorschlag. Aber bedenke die Gefahr, dass unbedarfte User das auch nutzen könnten.... Das müssen wir abwägen, ob der  Schadern durch falsche aber gewollte Nutzung zu groß ist

**Comment by csw-** [comment]
Hm, selbst mit "ordentlicher" Benutzung gäbe es Probleme.. Was wenn in einem Portal auf eine Seite der Nat und Tf verlinkt wird. 
Wenn dann müsste man es vllt beschränken auf das Fau-Blau für externe Links.

Aber naja, ich kann das demnächst gerne mal etwas ausformulieren und ein paar konkrete Use-Cases bauen. Vllt kommen dabei noch andere Ideen auf...

**Comment by xwolfde** [comment]
Erstmal zurückgestellt. Bei Bedarf kann der Issue ja wieder geöffnet werden..
