### ISSUE TITLE
ZickZack-Modus Position von Datum / Kategorie ungünstig?

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1401]
Uns ist beim Testen aufgefallen, dass beim ZickZack-Modus Kategorie und Datum identisch zur normalen Darstellung ausgegeben werden.

Allerdings müsste das wenn es der Logik vom ZickZack-Modus folgt eigentlich rechts unterm Bild dargestellt werden.

**Comment by xwolfde** [comment]
Nein, die jetztige Form ist schon so richtig. DIe Metaleiste unten ist nicht orieniert nach dem Bild, sondern nach dem Pfeil nach rechts zum Weiterlesen. Dieser ist und bleibnt auch immer rechts.
Der Zick-Zack-Modus sollte nur Bild und Teasertext austauschen, aber nichts anders.
Der Titel bleibt ja auch immer links oben.
