### ISSUE TITLE
Artikelbild auf Beiträgen wird verzerrt, wenn es Maximalwerte überschreitet

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1402]
Getestet in: Safari / Chrome | FAU Einrichtungen (Phil)

## Problembeschreibung
Auf Beiträgen wird das Artikelbild verzerrt, wenn es die CSS-Anweisungen Min-Width / Max-Width überschreitet.

### Ist-Zustand (Fehlerhafter Zustand)
<img width="1276" alt="Bildschirmfoto 2023-10-04 um 11 40 32" src="https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/58593037/184d8a2d-3841-4233-a68b-20ada8e078ae">

### Soll-Zustand
<img width="1276" alt="Bildschirmfoto 2023-10-04 um 11 41 02" src="https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/58593037/05f23343-744d-4d93-9780-ae854a2c8eda">

### Beispiel
Beispiel entnommen von: https://www.dhss.phil.fau.de/2023/03/10/save-the-date-die-lange-nacht-der-wissenschaften-am-21-10-2023/

## CSS-Selektoren
<img width="236" alt="Bildschirmfoto 2023-10-04 um 11 40 06" src="https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/58593037/ff24d7d1-3234-46bb-bc72-59c1dd665dea">

## Workaround
Betroffenes Artikelbild deaktivieren und Bild im Content-Bereich Einpflegen

**Comment by xwolfde** [comment]
Das sollte bereits in Beta repariert sein, dazu gab es ein issue

**Comment by xwolfde** [comment]
fixed im dev/beta. kommt demnächst
