### ISSUE TITLE
Optimierung der Kennzeichnung, welche Studiengänge aktuell angezeigt werden

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Einrichtungen#1405]
Die Seitenüberschrift lautet auch bei einer Auswahl an Studiengängen immer "Alle Studiengänge" (z.B. https://meinstudium.fau.de/studiengaenge/?search=mobility)
Eigentlich sieht man aber nur Studiengänge "mit Bezug zu..."/ bzw. "Alle Studiengänge zur Suchanfrage"

Können wir hier optimieren?

**Comment by xwolfde** [comment]
Also aktuell geht das so nicht. 
Die Seite hat den Titel "Alle Studiengänge" und der Content ist der Shortcode vom Plugin.Das man mit dem Shortcode nun Filter setzen kann, ändert nicht die Seite selbst und somit auch nicht dessen Überschrift.
