### ISSUE TITLE
Default Link zu XING führt ins Leere (404)

### ISSUE THREAD

**Issue by dominik-probst** [RRZE-Webteam/FAU-Einrichtungen#1413]
Dadurch, dass die Seite unter `https://www.xing.com/net/alumnifau` in `functions/defaults.php` nicht mehr vorhanden ist, führen die XING Buttons auf FAU Webseiten (unten rechts im Footer), wie [https://cms.rrze.uni-erlangen.de/](https://cms.rrze.uni-erlangen.de/), [https://cs.fau.de/](https://cs.fau.de/) und [https://www.cs6.tf.fau.de/](https://www.cs6.tf.fau.de/) ins Leere.

Da ich selbst auf unserer Lehrstuhlwebseite ([https://www.cs6.tf.fau.de/](https://www.cs6.tf.fau.de/)) nur eine Redakteursrolle innehabe, kann ich leider nicht prüfen, ob wir dieses Problem zumindest für unsere Webseite beheben können, aber da die Defaults offensichtlich auch von vielen anderen FAU-Webseiten genutzt werden, wäre vermutlich auch eine zentrale Lösung im Template selbst angebracht.

**Comment by xwolfde** [comment]
Danke für den Hinweis, das wird im nächsten Update behoben sein.

In den eigenen Seiten kann man die Defaults ändern, indem man ein eigenes Menu im Bereich "Social Media Bereich im Footer" einstellt.
