### ISSUE TITLE
Bildlink Carousel vertikal mittig 

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#142]
Nun da die Bildlinks nicht mehr croppen wäre es sinnvoll, dass wenn Bilder in der Höhe zu klein sind, diese nicht auf y=0 ausgerichtet sind, sondern vertikal mittig.

Aktuell:
![screenshot-ausrichtung-bildlinks-carousel](https://cloud.githubusercontent.com/assets/1070669/18630311/f58757b8-7e6b-11e6-9a2f-87912027c772.png)

**Comment by xwolfde** [comment]
Bei der FAU ist es schon Standard, wird dort aber manuell durch das Hochladen entsprechend geeigneter Bilder geleistet. Daher ist da keine Entscheidung beim Design mehr zu treffen. Es ist nur technisch umzusetzen :)

**Comment by AstridSemm** [comment]
Für den Fall, dass du eine Meinung möchtest: Ja, sehr gute Idee. :o)

**Comment by xwolfde** [comment]
Im nächsten Update enthalten
