### ISSUE TITLE
Sprachschalter auf Mobile unsichtbar

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#1429]
Der Sprachschalter ist auf der mobilen Darstellung nicht zu finden?

Bei fau.de ist er da:
<img width="369" alt="grafik" src="https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/1070669/f808edf3-66ee-41e7-872e-20a53aa956e4">

Bei meinstudium.fau.de aber nicht:
<img width="369" alt="grafik" src="https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/1070669/6c6a523b-2939-44f9-9694-64bcae14a938">

Ansätze:
1. Bei meinstudium ist die Suche abgeschaltet. Ggf. ist damit zu viel abgeschaltet?
2. Bei meinstudium ist nicht Workflow im EInsatz für den SPrachschalter, sondern Multilang. Dadurch andere Classes?
<img width="989" alt="grafik" src="https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/1070669/3a2e1606-f38a-46c8-b0fc-b88d00834803">

**Comment by wrcg** [comment]
auf intern.fau.de ist der Sprachumschalter auch nicht da, Suchfeld ist hier aber vorhanden, hier wird Multilang mWn verwendet

**Comment by xwolfde** [comment]
fixed, aber da muss noch an den HTML-Code vom Multilang-Plugin rann, um die Info der Sprache zu verbessern
