### ISSUE TITLE
Content-Markierung für Sprache

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#143]
Für Websites die deutsch und anderssprachig auf derselben Site verwenden, aber auch bei Gelegenheiten bei denen sich auch bei einer Site die getrennte Sprach-Webauftritte hat, auf einer Seite anderssprache Texte befinden, muss es die einfache Möglichkeit geben, diese so zu deklarieren, daß die Semantik korrekt ist und von Suchmaschinen erkannt wird.

Ideen:
- Ergänzung in einer Metabox: Sprache des Inhalts kennzeichen als [Auswahlliste](Auswahlliste=Englisch, Deutsch, Spanisch, Französisch, Russisch, Chinesisch,..). Mit Checkbox: Auch Überschrift deklarieren.
- Nur für Contentbereiche: Shortcode [langexcerpt="de|en|..."] .... zum deklarieren.

Ziel ist, daß der Textbereich und ggf. auch der Titel im Markup richtig mit den korrekten lang=""-Attribut versehen werden kann. Nur so können wir bei Gemischsprachlichen Sites und bei Quotes für Suchmaschinen eine geeignete Rückmeldung liefern.

**Comment by AstridSemm** [comment]
Hat das eigentlich auch Einfluß auf screenreader?

**Comment by csw-** [comment]
Gibt es eigentlich auch einen Standard bzw. "Best practice"  zur Kennzeichnung von Links die auf anderssprachige Webseiten führen? Auf FAU.eu wurde bei den Links ja z.B. ein "(German)" angehangen.

**Comment by xwolfde** [comment]
Dafür gibt es das Attribut hreflang:
https://wiki.selfhtml.org/wiki/Referenz:HTML/Attribute/hreflang

**Comment by csw-** [comment]
Ja, ich meinte eher die Kennzeichnung für den User und nicht für SEO. Schätze so etwas wie es FAU.eu gemacht wird ist wohl ausreichend...

**Comment by xwolfde** [comment]
ich muss an der stelle aber nochmal ran: Bei Websites die keine Language Switcher haben, wird kein hreflang gesetzt. Das bemeckert Google wiederum in den Webmaster Tools. Für die Suche hat es uzwar keine großen Auswirkungen, weil Google es detektiert, aber minuspunkte will ich deswegen auch nicht haben.
Und Rückfragen von Wbemastern, die sich wegen der Meldung in GWT wundern brauch ich auch nicht

**Comment by xwolfde** [comment]
Leider gibt es einige Fürsprecher, die darauf bestehen, ein Sprachmischmasch-Website zu haben und sich nicht von der Erfahrung (schlechter FIndbarkeit in Suchmaschinen) beirren lassen. Tenor ist: 'Der AUfwand das auf zwei Domains zu teilen sei viel zu hoch. Stattdessen sind zwei Bereich innerhalb einer Website viel gewohnter und überhaupt machen das andere auch so.'
Die SEO-Probleme seien da egal, die müsste dann eben die Technik lösen.

Meinungen?

**Comment by wrkb** [comment]
Ein wenig Mischung deutsch-englisch haben wir hier und da auch mal, wenn es um Hinweise für Nicht-Deutschsprachige auf deutschen Seiten geht. Da, wo der Umschalter nicht hilft. Das sind meist 2 bis 5 Zeilen und es sind wenige Fällle, die von allen als Notlösung begriffen werden. Kann man die noch eindeutiger kennzeichnen (wie)?

Ansonsten ist es wohl eine pragmatische Entscheidung, was einem wichtiger ist: Auffindbarkeit oder Arbeitsaufwand/Budget. Wobei ich nicht ganz verstehe: Geht es um explizit um zwei getrennte Domains oder um die saubere Trennung von Bereichen? Denn Wordpress bietet ja auch im Netzwerk die Möglichkeit, Sites nach Unterverzeichnissen zu unterscheiden, was für kleinere use cases auch die einzig zumutbare Lösung ist (Privatpersonen oder kleinere Sites). Ich fand die auch viel besser, als krampfhaft eine zweite Domain zu suchen, die auch keinen echten Hinweis auf die Sprache enthält (fau.eu ist ja nicht wirklich sinnvoll). Hat die Unterordner-Lösung handfeste Nachteile?

**Comment by csw-** [comment]
Sehe das ähnlich. Eine strikte Trennung wird es bei den meisten Seiten wohl kaum geben wenn das nur einzelne Themen sind die auf englisch geschrieben sind.  Wenn man bedenkt, dass bei den meisten Webauftritten eine Hiwi-Stelle mit wenigen Stunden dahinter steht, ist eine komplette 1zu1-Übersetzung kaum zu handhaben. Von den Kosten der Übersetzung mal ganz zu schweigen.

**Comment by xwolfde** [comment]
"Hat die Unterordner-Lösung handfeste Nachteile?" 
Ja.  Siehe SEO-Vorträge von anderen und auch von mir.

**Comment by xwolfde** [comment]
Wie stellt ihr euch denn bei einer Mischmasch-Seite die Navigation vor? Also mal Biutter bei den Fischen. Konkret.

**Comment by wrkb** [comment]
Wichtig: Ich plädiere nicht für eine Mischmasch-Seite, ich habe nur darauf hingeweisen, dass bei Minimal-Content auch mal Ausnahmen okay sein müssen, realitätsbezogen. Echter Content muss separat behandelt werden - eben auch wegen der Navigation.

Eine Mischnavigation wird hier und da gemacht, z.B. http://ib.wiso.fau.de
Wenn ich zwangsweise mehrere Sprachen in der Navigation mischen müsste, würde ich Unterbereiche schaffen (Portale) und mit "English pages" o.ä. ankündigen und die einzelnen Seiten dann verlinken, dann ist es wenigstens transparent. Nicht schön, aber wenigstens klar kommuniziert.

**Comment by xwolfde** [comment]
Ja, sorry, missinterpretativ. Die Frage war ja nicht, wie man es sich zurechtbiegen kann, wenn man möchte, sondern wie es im optimalen Fall konkret aussehen sollte.

**Comment by AstridSemm** [comment]
Kurze Anmerkung: Das internationale Büro der WiSo hat aber gewußt, dass sie volle Knäcke gegen das Theme arbeiten. Ich habe die Herrschaften nämlich geschult und es ihnen gesagt. Tja.

**Comment by xwolfde** [comment]
Leider können wir uns den stetigen Anfragen nicht erwehren. 
Andererseits:
Die Umsetzung erweist sich als nicht ungefährlich.  Eine gleichzeitige Nutzung dieser Funktion mit Workflow-Plugin und dort aktivierter Mehrsprachigkeit wird zu Problemen führen:  Wir können nicht gleichzeitig mehrsprachige Domains und mehrsprachige Mischmaschinseiten haben. Das Übersetzungsworkflow kann nicht wissen, wenn eine Seite die es als DE hält und nach EN übersetzt werden soll, plötzlich doch ne andere Sprache hat.
 Dennoch ist damit zu rechnen, dass User das trotzdem einschalten werden.

**Comment by xwolfde** [comment]
Ab der kommenden Version im Theme enthalten.

Mit deutlichen Warnungen.
@AstridSemm  Bitte in die Doku aufnehmen. Screenshot sind auch im Rollout-Projekt im Git.

![seitensprache-metabox-20171013](https://user-images.githubusercontent.com/1070669/31553583-3cf7df9e-b03b-11e7-9b46-1db920db64d0.gif)
![seitensprache-20171013](https://user-images.githubusercontent.com/1070669/31553584-3d0db558-b03b-11e7-98cb-408d8aa03fd7.gif)
