### ISSUE TITLE
Quotes mit Sharelinks

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#144]
Wahrscheinlich nur als Plugin-Ergänzung lösbar:

Wie wäre es, wenn wir bei Verwendung von Zitaten im Content, automatische Sharelinks dazu ergäntzen könnten? Vgl, dieses Beispiel von T3N:
![screenshot-quotes-sharelinks](https://cloud.githubusercontent.com/assets/1070669/18632059/bcb72972-7e75-11e6-9e37-55706c6d7d94.png)

D.h. der Quote selbst muss über einen Anchor verlinkbar sein und der Quote-Text wird bei einem Share als Text übernommen und mit dem Artikel verlinkt.

**Comment by AstridSemm** [comment]
Ich fände es ziemlich riesig, wenn das ginge.

**Comment by xwolfde** [comment]
Sollten wir als Plugin machen.

**Comment by xwolfde** [comment]
Da Quotes nicht oder fast gar nicht eingesetzt werden, ist der Issue erstmal hinfällig
