### ISSUE TITLE
Das Feld Untertitel wird als Absatz, statt als H2-Überschriftebene ausgegeben

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1444]
Durch eine der letzten Theme-Versionen wurde aus dem Untertitel aus einem Absatz eine H2-Überschrift gemacht.
Dadurch haben SEO-Optimierte Seiten mit richtiger Überschriften-Hierarchie jetzt eine Lücke im Content, wenn Sie den Untertitel verwendet haben.

## Dokumentation
Unsere Dokumentation zeigt, dass der Untertitel eine H2 sein müsste (So wurde auch in Schulungen in der Vergangenheit dahingehend geschult). 
![image](https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/58593037/d5ea3be6-4b01-4662-8ff0-6817aac37e78)

## GitHub
In älteren Versionen von page.php kann man sehen, dass aus dem H2-Tag ein p-Tag gemacht wurde.
https://github.com/RRZE-Webteam/FAU-Einrichtungen/blob/f6b70687f26958b4106983fce13a54ca68180504/page.php

## Mögliche Lösung
Entweder den Untertitel wieder als H2 gestalten (oder Kunden müssten hunderte Inhaltsseiten überarbeiten)…

**Comment by xwolfde** [comment]
Das Problem war/ist, dass die Nutzung des h2 ein Fehler bei der WCAG Erkennung war: Einfach gesagt muss hinter jeder Überschrift auch ein Inhalt kommen.

Siteimprove hat zu recht jedoch mehrere Fälle gemeldet, wo die h2 gesetzt war, danach aber kein Text erschien, sondern weitere Überschriften oder eben andere semantische Bereiche (Artikelisten, Slider, Bilder).
Auch für die SEO ist der Gebrauch dann problematisch, wenn auf die Überschrift kein entsprechender Inhalt kommt.

Relevante WCAG Kriterium ist: 
https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships

Erläuterung zum selben Thema hier auch:
https://hidde.blog/when-there-is-no-content-between-headings/

Streng ausgelegt muss hinter der h1 ein Absatz-Content folgen. Bevor eine neue Überschrift kommt.
Dies wird durch den Wechsel auf p erreicht. Der Subtitel bezieht sich zudem auch immer auf das h1, so daß dies auch sematisch richtiger ist.
Noch richtiger wäre es, wenn man die Subheadline sogar in die h1 mit einfügen würde. Aber ich denke, das würde die Komplexität dann doch zu sehr erhöhen.


Kurzum:
Die vorherige Verwendung war falsch. Fehler müssen behoben werden.
Ich denke, die schrittweise Korrektur der Seiten von h3 auf h2 bei den Zwischenüberschriften ist nicht unzumutbar. Ich bezweifle, dass sehr viele Seiten da wirklich betroffen sind, die gleichzeitig so viel Content haben, dass sie die h3 mehrfach nutzten und die Subheadline nutzen. 
Die allermeiste Nutzung der Subheadline war und ist stets die, den eigentlichen Titel optisch mit einen optisch hervorgehobenen Subtext zu ergänzen.
