### ISSUE TITLE
Hover-Effekt für aktive Zeilen in Tabellen

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1445]
Von Kundenseite gab es den Wunsch, ob man auch einen Hover-Effekt für größere Tabellen festlegen kann, damit Nutzer leichter die aktive Zeile sehen.

Aus 🎫 http://go.fau.de/9v8qm | # 1

**Comment by xwolfde** [comment]
Hatten wir schon mal.
Ich nehme das aber mal als Style-Option in #1468 auf
