### ISSUE TITLE
Notwendiges Styling für Patterns

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#1447]
Welche Pattersn müssen gestylt werden.

Bitte Liste ergänzen:

- [ ] Name , Kontext, verwendete Blöcke

**Comment by lukasniebler** [comment]
Ich denke, wir sollten keine der Core-Patterns bereitstellen im FAU Einrichtungen, sondern über das Elements-Plugin eigene Patterns bereitstellen.

Der Aufwand ist sehr gering. Und du hast den Vorteil, dass die Patterns die Akkordeons und Co. nutzen können...
(Können wir aber nächsten Mittwoch auch nochmal besprechen)

**Comment by xwolfde** [comment]
Missverständnis: Es geht nicht um die Bereitstellung der Technik der Patterns, sondern um etwaige CSS-Anpassungen damit der Block optisch in das FAU-CD passt.
Dies kann nicht in Elements erfolgen, da Elements ja unabhängig vom Theme sein soll.

**Comment by xwolfde** [comment]
Wird erstmal nur über das Blocks Plugin behandelt.
