### ISSUE TITLE
Top Events ohne Datum

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#145]
Die Webredaktion verwendet Top Events ohne Datum. Das sind dann eigentlich keine Events, sondern Texthinweise, die in der Textbox erscheinen sollten.
Mit der neuen Version werden diese Top Events mangels Datum eigentlich korrekt nicht mehr angezeigt.

Nochmal diskutieren oder als fehlbenutzung abhaken?

**Comment by AstridSemm** [comment]
Als Fehlbenutzung abhaken; wenn ich einen Event promote, gehört das Datum dazu. :o)

**Comment by csw-** [comment]
Mir fällt ad hoc gerade auch kein Use Case ein bei dem es nötig wäre das Datum wegzulassen. 

Allerdings gibt es bei mehrtägigen Events das Problem, dass es zu früh herausfällt da das Anfangsdatum bereits vorbei ist, die Veranstaltung aber noch andauert. Wie eben grade bei den Schülerinfotagen.

**Comment by xwolfde** [comment]
Ja. Genau das war der ANlass - wir haben gerade fau.de auf das FAU-Einrichtungen-Theme aktualisiert.
Ich hab jetzt die Schüleriunfotage bei der deutschen Site als normalen HTML in der Textbox der Sidebar oben eingefügt. Geht auch.

**Comment by csw-** [comment]
Ja, schöner wäre es wohl wenn man im Beitrag ein optionales End-Datum angeben könnte zu dem das TopEvent dann rausfliegt.

**Comment by xwolfde** [comment]
Aklternative wäre, dass das Datumsfeld zum Textfeld wird, wo man dann Auch von-bis eintragen kann. 
ABER: Das wird dann den Nachteil haben, daß wir das nicht mehr im markup sauber abbilden können und Google dann dieses Event nicht mehr als Event erkennen & auf der Suchergebnisseite promoten wird.

**Comment by csw-** [comment]
Und dann würde das Top-Event doch nicht mehr automatisch entfernt werden, sondern das müsste man dann selber über en Tag regeln, oder?

**Comment by xwolfde** [comment]
Vielleicht machen wir es uns zu kompliziert: Eine einfache Option: "Auf Startseite/Sidebar sichtbar halten" könnte eine ALternative sein, die bewirkt dass der Eintrag auch dann angezeigt wird, wenn kein Datum gesetzt wird oder dieses abgelaufen wird.

**Comment by csw-** [comment]
Jepp. Das wäre natürlich auch eine Lösung. :+1:

**Comment by AstridSemm** [comment]
Hm. Wirklich sauber wär's ja, wenn man bei mehrtägigen Events auch mehrere Artikel macht, die man als Top-Event einblendet. Die Programme der einzelnen Tage sind ja eh nicht identisch. Ich weiß, das ist mehr Arbeit für den Webmaster undsoweiter. Aber so würde tatsächlich das angekündigt, was am jeweiligen Tag los ist und Google wäre auch happy...

**Comment by wrkb** [comment]
Ich verstehe die Fragen nach dem use case nicht - er war doch online ;) Es gibt immer wieder Anlässe, die kein konkretes Datum haben, die wir dort gern beworben haben für einige Tage (Semesterticket kaufen jetzt etc.). Zack - neuer Use case entstanden, wenn auch mit Verbiegen der ursprünglich angedachten Funktion.

Mit gefällt Wolfgangs Vorschlag am besten - ein "sticky post" draus machen, dass manuell platziert und runtergenommen wird. Die Startseite hat man als Admin ja ständig im Blick, so dass die Pflege erst mal sichergestellt sein sollte.

Eine Zeitautomatik wäre dennoch nicht übel - aber haben wir die mit Planung und Runternehmplanung nicht schon?

Wenn das Top-Event zu anderen Zeiten online gehen soll/muss als das Posting im Newsfeed der Startseite, dann müsste man eher über 2 Kategorien nachdenken, so dass man separate Inhalte nur für das Top-Event anlegen kann... naja, die Möglichkeiten sind bekannt.

Habe ich alles richtig verstanden?

**Comment by xwolfde** [comment]
Ok, in der nächsten version wird es folgende Änderungen geben:
- Bei der Beitragsbearbeitung wird der Metabox für Top Event eine Option hinzugefügt "Diesen Artikel als Top-Event anzeigen". 
- Wenn diese Option gesetzt ist, wird der Beitrag als Top Event angezeigt. Ganz unabhängig davon ob er ein gültiges Datum hat oder nicht.
- Die Kategorie "top" kann natürlich auch weiterhin verwendet werden anstelle des Schalter, muss aber nicht mehr! Dies deswegen, weil manche Schlagworte in der Form einfach sinnfrei sind. Die Schlaghworte wollen wir den Lesern anzeigen und sie sollen sich auf den Inhalte beziehen. Sie sind nicht dafür gedacht,. dass man damit Artikelanzeigens teuert. Daher ist das jetzt aus Abwärtscompatibiltät noch drin, aber in Zukunft sollte der Schalter beim Artikel selbst bevorzugt genutzt werden
- Ich werde noch ähnlich wie bei den Social Media Footer eine option einbauen, dass die Top Events nicht nru auf der Startseite angezeigt werden können, sondern auch auf Portalseiten

**Comment by wrkb** [comment]
Klingt gut! Auch der letzte Punkt.
Was passiert dann übrigens mit den Schlagworten wie startseite1,2,3... Ist ja ähnlich in der Nutzung, müsste dann irgendwann auch weg :)

**Comment by xwolfde** [comment]
Gemach, es hat ettlichen Supportstunden gekostet, den Leuten zu verklickern, wie das mit den Positionen startseite1-3 ging. Das will ich jetzt nicht auch noch gleichzeitig mit den anderen ändern...

**Comment by wrkb** [comment]
:D Ist schon klar, das war ja kein Drängeln. Aber wenn man an Beiträgen sich für das Anzeigen von Schlagworten entscheidet, dann wären die mit dabei theoretisch. Das war der Hintergedanke. Kommt Zeit, kommt Update, war nur neugierig.

**Comment by xwolfde** [comment]
Ja, da hast du Recht. Im Prinzip ist das die Richtung: WIr müssen die Schlagworte wieder nur für Schlagworte verwenden und nicht für andere Dinge missbrauchen.  Ggf. wäre daher bei Beiträgen auch eine "Positions-Option" sinnvoll. Dafür mach ich mal ein Extra-Issue.

**Comment by AstridSemm** [comment]
Wo ist hier der "Like"-Button? ;o)

**Comment by xwolfde** [comment]
Ref #180

**Comment by wrkb** [comment]
> Wo ist hier der "Like"-Button? ;o)
Na da, ganz rechts in der Titelbar eines Postings :)

**Comment by xwolfde** [comment]
Nach diversen rumtesten, mach ich der Einfachheit halber doch eine simple Form:
Ein Top-Event wird angezeigt, wenn

- Der Artikel mit einem neuen Schalter als Top Event deklariert ist. Solange dieser Schalter gesetzt ist, ist der Beitrag Top-Event. Egal, welches Datum er trägt. Der Beitrag wird von der Seite entfernt, wenn man den Schalter wegnimmt oder er durch einen anderen Eintrag überschrieben wird (order by datum der Beiträge)
- Der Artikel einen Datumseintrag hat und dieses Datum noch nicht abgelaufen ist.

Die Kategorie spielt keine Rolle mehr.

**Comment by xwolfde** [comment]
Weiteres feature wurde eingebaut: Das Bild kann ganz weggeblendet werden.
Somit ist die Funktion auch für irgendwelche besonderen Hinweise nutzbar.

In der nächsten version aktiv.
