### ISSUE TITLE
DEV: Theme.json – Farbwerte für Elements-Blöcke sind falsch

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1462]
Das Elements-Plugin zieht sich die Farbwerte aus der Theme.json für den jeweiligen Block.
Die Farbwerte passen aktuell wieder nicht mehr für die verschiedenen Blöcke:

- [x] rrze-elements/accordion (Inner Accordionelement) Nur FAU | RW | TF | Phil | Nat | Med erlaubt keine sonstigen Farben
![Bildschirmfoto 2024-05-13 um 08 48 41](https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/58593037/2b4dd977-8a90-4c7d-859d-1b1783be97f2)
- [x] rrze-elements/collapse (Accordionelement) – Nur FAU | RW | TF | Phil | Nat | Med erlaubt keine sonstigen Farben
![Bildschirmfoto 2024-05-13 um 08 50 16](https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/58593037/64e11e65-1cda-435f-9dc5-61406be115ef)
- [x] rrze-elements/columns (Dynamische Textspalten) – Nur Alert-Farben erlaubt (default | success | danger | warning | info)
![Bildschirmfoto 2024-05-13 um 08 52 18](https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/58593037/2f599a31-6d07-4900-83cf-eda08d9bdb45)
- [x] rrze-elements/alert (Hinweisboxen) – (default | success | danger | warning | info) Nur Alert-Farben erlaubt 
![Bildschirmfoto 2024-05-13 um 08 54 11](https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/58593037/8f07675f-3c20-4c8c-b4fe-d040aaaeb95d)
- [x] rrze-elements/tabs Nur FAU | RW | TF | Phil | Nat | Med erlaubt ![Bildschirmfoto 2024-05-13 um 08 57 46](https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/58593037/271c8021-f69f-44ec-a2ff-477ac83e58ba)

**Comment by xwolfde** [comment]
done.

Wir sollten aber offen lassen, dass man auch andere Hintergrundfarbwerte für Columns in Erwägung zieht.
