### ISSUE TITLE
DEV: Theme.json – 

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1464]
Mein Editor meckert noch bei den folgenden zwei Werten

<img width="622" alt="Bildschirmfoto 2024-05-13 um 09 47 32" src="https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/58593037/e4cdccae-2275-4532-a7c4-aac676ceeacf">
<img width="622" alt="Bildschirmfoto 2024-05-13 um 09 48 15" src="https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/58593037/c933d449-301b-42f9-a030-54b78e4af884">

**Comment by xwolfde** [comment]
fontFamilies fällt mit V3 ganz weg. Ist gelöscht.

Der untere Fehler ist aber für V3 falsch, da String erlaubt ist:
<img width="817" alt="grafik" src="https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/1070669/d5f8da7a-6c6c-4931-9d9f-8fd627bb7af0">
