### ISSUE TITLE
core/paragraph

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1466]
Das max-width 125ch im Styling sorgt dafür, dass der rechts ausgerichtete Text nicht bündig ist sondern etwas eingerückt.

<img width="1421" alt="Bildschirmfoto 2024-05-14 um 09 10 54" src="https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/58593037/42e6894a-a95a-436f-b747-c309701cd05e">
<img width="1421" alt="Bildschirmfoto 2024-05-14 um 09 11 49" src="https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/58593037/e26018ca-c491-4d02-b063-c65c8e2fe709">

## Gutenberg-Code zum ausprobieren:
``` html
<!-- wp:group {"metadata":{"name":"Custom News"},"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:separator -->
<hr class="wp-block-separator has-alpha-channel-opacity"/>
<!-- /wp:separator -->

<!-- wp:heading -->
<h2 class="wp-block-heading">Aktuelles</h2>
<!-- /wp:heading -->

<!-- wp:rrze-elements/news {"num":3,"hidemeta":true,"hstart":3,"type":"img_first","hide":"date,category","columns":3} /-->

<!-- wp:paragraph {"align":"right"} -->
<p class="has-text-align-right"><a href="/category/aktuelles/">Mehr Meldungen</a></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"metadata":{"name":"CTA Abschnitt"},"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:separator -->
<hr class="wp-block-separator has-alpha-channel-opacity"/>
<!-- /wp:separator -->
```

**Comment by xwolfde** [comment]
wp class "has-text-align-right" ist im Theme nicht präsent. 

Hast du mal eine URL für das Beispiel?

**Comment by lukasniebler** [comment]
Hier sieht man es im ersten Abschnitt mit den Custom-News:
https://zortzi.dev.cms.rrze.de

**Comment by lukasniebler** [comment]
Müsste behoben sein?
