### ISSUE TITLE
Schriftsatz im Gutenberg-Editor ergänzen / einbinden

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1484]
Für kommende Versionen Links, Buttons und Schriftsatz in Gutenberg noch anpassen.

Am besten mit abgeschaltetem Elements-Blocks testen / stylen.

![image](https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/58593037/04570187-198b-457b-a3ce-adc9443aa091)

**Comment by xwolfde** [comment]
done im dev
