### ISSUE TITLE
Layout-Bug bei vielen Kategorien und Schlagwörtern 

### ISSUE THREAD

**Issue by cassandre** [RRZE-Webteam/FAU-Einrichtungen#1497]
Entweder es fehlt ein wrap, oder eine Lösung ohne flex:

<img width="1088" alt="Bildschirmfoto 2024-06-04 um 11 03 38" src="https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/4435815/607022b1-4b1c-43a9-8459-ea1d1ae9c084">
https://www.wordpress.rrze.fau.de/2022/10/06/pdf-dateien-auf-der-webseite-einbinden-tipp-der-woche/

**Comment by xwolfde** [comment]
Folgender Teil optimieren:

```
.meta-footer .post-meta-categories, .meta-footer .post-meta-tags {
  align-items: center;
  display: flex;
  gap: .3rem;
  margin-right: var(--width-gutter-half);
}
```

Flex war notwendig um das Icon auf gleicher Höhe wie "Kategorie"/"Schlagworte" zu haben. Hier brauchts ggf. dann doch ein eigenes span oder div.

**Comment by xwolfde** [comment]
Hab das erstmal rauskommentiert für die 2.5. Für eine Änderung müsste die Generierung und nicht nur das CSS geändert werden. Das ist jetzt eher was für später.
