### ISSUE TITLE
Listenelement wird in Textwidget zu groß dargestellt

### ISSUE THREAD

**Issue by endv02** [RRZE-Webteam/FAU-Einrichtungen#15]
Screenshot kommt von Phil-Theme
![screenshot_textwidget](https://cloud.githubusercontent.com/assets/5851793/13741035/31926bf8-e9d4-11e5-8b68-afbd53d9a3bd.jpg)

**Comment by xwolfde** [comment]
Und was ist die Frage?

**Comment by AstridSemm** [comment]
Wie kriegt man's kleiner?

**Comment by xwolfde** [comment]
Ist in FAU-Einrichtungen gefixt. Damit auch beim nächsten update Philfak.
