### ISSUE TITLE
Englischsprachige 404-Fehlerseite spielt deutschen Hinweistext aus

### ISSUE THREAD

**Issue by csw-** [RRZE-Webteam/FAU-Einrichtungen#150]
Auf der 404-Fehlerseite wird der Hinweistext noch auf Deutsch ausgespielt. Über's Backend kann man den Text wohl nicht anpassen oder? Hier bräuchten wir dann entsprechend den englischen Text...

![404](https://cloud.githubusercontent.com/assets/6545158/19014545/052ec100-87f0-11e6-86f0-9c6db84f0fa0.png)

**Comment by xwolfde** [comment]
Sprachdatei testen...

**Comment by xwolfde** [comment]
Ihr verwendet EN_US. Bitte schaltet um auf EN_UK. 
Übersetzungen werden nun mehr in EN_UK bereit gestellt. EN_US sind noch alte Dateien enthalten, die aber nicht mehr gültig sind

**Comment by wrcg** [comment]
Wir haben das gleiche Problem. Allerdings habe ich keine Möglichkeit, auf EN_UK umzuschalten:

<img width="436" alt="2016-10-21 09_57_38-einstellungen" src="https://cloud.githubusercontent.com/assets/9526974/19590956/d727a76a-9774-11e6-82cd-f0e40c9dfe20.png">

oder geschieht das an einer anderen Stelle?

**Comment by csw-** [comment]
Wir haben auf US gestellt, weil wir am Fachbereich nicht das Uk-En verwenden. War vor allem im Rahmen der Übersetzungen wichtig.

**Comment by xwolfde** [comment]
EN-UK ist aber durch UL Beschluss als Standard festgelegt.
