### ISSUE TITLE
Custom CSS aus dem Customizer lädt nur im Backend

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1504]
Das Custom-CSS aus dem Customizer lädt nur im eingeloggten Zustand.
Sobald man ausgeloggt ist, wird es nicht mehr angezeigt.

**Comment by xwolfde** [comment]
Hast du mal ne URL?

**Comment by lukasniebler** [comment]
https://www.kunst.phil.fau.de/lehrstuhl-profil/personen/

Da steht im Customizer ein paar Anpassungen dass die Kacheln links ausgerichtet sind.

Das Beispiel von FAU.de kann ich nicht nehmen, weil die das jetzt schon als Workaround umgefplügt haben. Aber hat auch Zeit bis nach deinem Urlaub

**Comment by xwolfde** [comment]
Die URL zeigt eine Website, die eine FAU Einrichtung ist. Für jene gibt es kein CustomCSS!

CustomCSS wird nur für Websites im Typ Kooperation erlaubt.
Der Trick, erst auf Kooperation zu wechselb, dann CSS einzutragen und dann wiedder auf Lehrstuhl-Typ zu gehen, funktioniert nicht mehr :)

**Comment by lukasniebler** [comment]
Das betrifft alle Websites mit FAU-Einrichtungen. Auch FAU.de / FAU.eu 
Die Möglichkeit, dass der Support / Superadmins temporäre Hotfixes einspielen kann fällt dadurch komplett weg, was beim Update-Zyklus von FAU-Einrichtungen uns vielleicht später irgendwann mal in den Rücken fallen könnte.

Ansonsten stört es mich nicht. In der Vergangenheit hat das allerdings immer funktioniert als Superadministrator.

**Comment by xwolfde** [comment]
Hab die Darstellung wieder erlaubt, sonst würde es bei Kooperationen nicht klappen. Wir haben aber auch in den Network-Settings was dazu gemacht.

in dev
