### ISSUE TITLE
CSS Inkonstistenzen bei Hyperlinks

### ISSUE THREAD

**Issue by JuliaaNbr** [RRZE-Webteam/FAU-Einrichtungen#1505]
Hyperlinks werden teilweise nicht mehr in den Theme-Farben dargestellt.

Offensichtlich ist dieses Problem bei der Anzeige der Schlagworte in Blogrolls. Diese werden auf der Übersichtsseite korrekt farbig unterstrichen, beim Öffnen der Beiträge sind dann alle Links jedoch nicht mehr farblich angepasst. Hovert man darüber werden Links im Text wieder farblich korrekt hervorgehoben, die Schlagworte unterhalb verleiben jedoch weiterhin in einer neutralen Farbe.

Vergleiche hierzu: [Blogroll auf Startseite](https://www.dhss.phil.fau.de/) und [Beitrag](https://www.dhss.phil.fau.de/2024/06/05/naechsten-montag-startet-die-funklust-ki-woche/)

Anbei auch ein Screenshot eines unveröffentlichten Startseiten-Entwurfs bei dem innerhalb eines [custom-news]-Elements mit drei Spalten ein Link andersfarbig angezeigt wird. 

![Screenshot](https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/124438817/a04bdda0-0384-4de7-9cc1-c5ea856d5e6f)

**Comment by xwolfde** [comment]
im nächsten dev gefixt
