### ISSUE TITLE
[hr /] 

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Einrichtungen#1508]
[hr/] shortcode wird (seit dem update?!) nicht mehr korrekt dargestellt
![image](https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/9526974/fa910c6d-7c51-49a8-b86f-9617974e4759)

**Comment by lukasniebler** [comment]
@wrcg als Workaround kannst du [divider] für einen unsichtbaren Trenner oder <hr /> nutzen

**Comment by xwolfde** [comment]
Guten Morgen :) 
Der Shortcode ist weggefallen. Ich hatte doch extra nachgefragt... :P
