### ISSUE TITLE
Galerie – Bildunterschriften werden nur in Safari angezeigt

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1510]
# Problem
Bei der Bildergalerie wird die Bildbeschriftung nur in Safari angezeigt. 
Chrome & Firefox zeigen die Bildbeschriftung nicht an.

## Schritte zum Nachstellen des Problems
https://www.inorgchem1.nat.fau.de/harder-team/former-group-members/

## Bild des Problems
Safari:
<img width="1430" alt="Bildschirmfoto 2024-07-08 um 12 24 32" src="https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/58593037/33628dab-eb09-4a3c-ac1a-976f38a31b4e">
Firefox (Bildbeschriftung fehlend):
<img width="681" alt="Bildschirmfoto 2024-07-08 um 12 25 43" src="https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/58593037/e8af6aec-1ec8-4ea2-83dd-cf0a7f93d901">

**Comment by xwolfde** [comment]
fixed im dev
