### ISSUE TITLE
Fehlermeldung: Absätze sind nicht #222 sondern #000

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1513]
# Beschreibung des Problems
Die Schriftfarben von Text und Absätzen sind falsch rgb(0,0,0) und müssen auf die Theme-Variable angepasst werden.

**Comment by xwolfde** [comment]
Wo genau?

**Comment by xwolfde** [comment]
Also Absätze sehen für mich richtig aus:
<img width="1532" alt="grafik" src="https://github.com/user-attachments/assets/c742622c-b339-4a86-95fa-54f1f369dedb">

**Comment by lukasniebler** [comment]
Im Gutenberg-Editor auch?

**Comment by xwolfde** [comment]
Deswegen die Nachfrage, wo der Fehler auftrat ;)

**Comment by xwolfde** [comment]
Tritt nur noch im Classic Editor auf. Dort verschmerzbar.
