### ISSUE TITLE
Falsche Überschriftengröße in der mobilen Ansicht

### ISSUE THREAD

**Issue by GiniSt19** [RRZE-Webteam/FAU-Einrichtungen#1515]
Problem: 
in der mobilen Ansicht ist die Überschrift (z.B. H2) mit 14,33px kleiner als der Absatztext (16px).

Wird **font-size: var(--wp--preset--font-size--medium) !important; */** deaktiviert, erscheint die Überschrift wieder in richtiger Größe.

**Comment by xwolfde** [comment]
fixed in dev
