### ISSUE TITLE
Pullquote-Block im Gutenberg-Editor fehlerhaft

### ISSUE THREAD

**Issue by GiniSt19** [RRZE-Webteam/FAU-Einrichtungen#1523]
Der Pullquote Block im Gutenberg-Editor wird aktuell noch mit zu viel Optionen dargestellt. 
Man kann Ränder und Radius einstellen sowie extreme Farben für den Hintergrund.
Wird die Textfarbe eingestellt, färbt sich auch der Rand in dieser Farbe ein.
Zudem entsteht immer ein weißer Kasten mit dem Zitat. Die Zitatschrift ist Georgia.

<img width="821" alt="Bildschirmfoto 2024-08-06 um 09 28 19" src="https://github.com/user-attachments/assets/483739df-eee4-473b-89e2-eb9da0dad39e">

**Comment by xwolfde** [comment]
ggf. jetzt schon mit behandeln, da alles ein Kontext: #1527

**Comment by xwolfde** [comment]
Notiz für mich:

Der Block-Editor überschreibt die blockquote-Rahmenfarbe, die wir beim Theme vorgeben:
<img width="494" alt="grafik" src="https://github.com/user-attachments/assets/7c46d35d-8a53-42e7-8744-492b904b8623">

**Comment by xwolfde** [comment]
Wird in der nächsten Version behoben sein
