### ISSUE TITLE
Mobile Darstellung FAU-Einrichtungen (Gutenberg-Editor)

### ISSUE THREAD

**Issue by GiniSt19** [RRZE-Webteam/FAU-Einrichtungen#1525]
Die mobile Darstellung von Seiten, die mit dem Gutenberg-Editor erstellt wurden, ist fehlerhaft.

- Überschriften sind zu klein (kleiner als der Fließtext)
- Bilder laufen über den rechten Rand, wenn sie in Spalten platziert wurden.
- mehrere Spalten werden nicht sauber untereinander dargestellt

https://www.wordpress.rrze.fau.de/der-gutenberg-editor/hauptelemente-des-editors/die-obere-editorleiste/

![simulator_screenshot_8F5000E7-31B0-4B9A-8FDE-A9E9FC5F091F](https://github.com/user-attachments/assets/f374c2b1-b0d7-4f68-8f9e-396b9a9b03dd)
![simulator_screenshot_E384F78F-44ED-472E-88B4-EF1612A5EE02](https://github.com/user-attachments/assets/efe8f055-8b5c-4401-bf3d-850cea25a417)

**Comment by lukasniebler** [comment]
Behoben in dev
