### ISSUE TITLE
Klötzchen in Fak-Farbe im Banner der Startseite

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Einrichtungen#153]
Wenn man die Startseite anlegt und unter Anpassen -> Website-Informationen nichts eingibt, aber ein Header-Bild definiert, dann erscheint im Banner links oben ein Klötzchen in Fakultätsfarbe:
![bildschirmfoto 2016-10-06 um 14 07 33](https://cloud.githubusercontent.com/assets/11296947/19151750/c5a181ac-8bce-11e6-9ee2-270d66ac729e.png)

Definiert man nun _kein_ Header-Bild, ist das Klötzchen auch weg:
![bildschirmfoto 2016-10-06 um 14 07 14](https://cloud.githubusercontent.com/assets/11296947/19151769/dc6d0e7e-8bce-11e6-9805-ac370e01646d.png)

Mal ganz ab davon, dass es vollkommen sinnfrei ist, keine Website-Informationen anzugeben oder diese in eine Grafik zu verpacken wie hier:
![bildschirmfoto 2016-10-06 um 14 13 23](https://cloud.githubusercontent.com/assets/11296947/19151814/18919dca-8bcf-11e6-8eba-7d1e7eb736df.png)

Der Zusammenhang interessiert mich. Welchen Zusammenhang hat die Hintergrundfarbe für den Text der Website-Information mit der Headergrafik?

**Comment by xwolfde** [comment]
WTF?!

**Comment by xwolfde** [comment]
Ok, das liegt daran, dass kein Sitetitel gegeben wurde. Was ausgegeben wird, ist ein leeres h1. Das h1 ist in einem div gepackt, welches die Hintergrundfarbe macht und dabei ein Padding angibt.

Wir könnten eine fette Meldung ausgeben wenn kein Website-Titell da ist. Sowas wie:
DER WEBMASTER DIESER WEBSITE WOLLTE KEINEN LESBAREN UND FINDBAREN TITEL ANGEBEN, DENN ER GLAUBT DAS JEDER EIN BILD ERKENNEN KANN; MENSCHEN MIT SCREENREADERN UND SUCHMASCHINEN SIND EGAL. HIER DIE ADMIN-EMAIL-ADRESSE... 


Na, ich würde sagen, wir lassen das jetzt so wie es ist.
Ohne fette Fehlermeldung, aber auch mit einem "Etwas", was vielleicht nachdenken lässt.

**Comment by AstridSemm** [comment]
Ich mache den mal eben für mich wieder auf, damit ich das in die Doku schreibe.

**Comment by xwolfde** [comment]
Klötzchen is no more.
