### ISSUE TITLE
Vorlage Block-Editor

### ISSUE THREAD

**Issue by GiniSt19** [RRZE-Webteam/FAU-Einrichtungen#1539]
Problem: Schreibfehler im Block-Titel
Statt **Editor** steht dort **Ediotr**

<img width="268" alt="Bildschirmfoto 2024-09-11 um 10 41 36" src="https://github.com/user-attachments/assets/4090db08-ec7d-4222-8849-e528296dda4c">
<img width="484" alt="Vorlage bearbeiten" src="https://github.com/user-attachments/assets/1ac72e5a-efa5-4e7f-96e5-53378416d69d">

**Comment by xwolfde** [comment]
Das Wort kommt aber im Theme nicht vor/ kommt nicht von da.

**Comment by lukasniebler** [comment]
@xwolfde Glaube das kommt aus dem WP core?

**Comment by xwolfde** [comment]
Wahrscheinlich... Jedenfalls können wir da am Theme nichts dran ändern.

**Comment by lukasniebler** [comment]
Warten auf nächste WP-Version, da core-issue
