### ISSUE TITLE
h4 (+h3) in Akkordeons schwarz statt blau

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Einrichtungen#154]
Nach dem Wechsel auf Einrichtungs-Theme fällt auf, dass die h4 _in Akkordeons_ nicht mehr blau sind, wie früher, die h3 sind scheinbar auch betroffen. War das beabsichtigt und wenn ja, warum? Das Blau hat den Überschriftencharakter ausgemacht und die h4 auch von der Fettung abgehoben - das ist nun nicht mehr der Fall.

Im Editor im Backend ist noch blau, was blau war, siehe unterer Screenshot.

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/19184852/5635076a-8c7f-11e6-92fa-4e110f5f1d37.JPG)

![unbenannt2](https://cloud.githubusercontent.com/assets/9445370/19184872/6643632c-8c7f-11e6-9857-a438a9db2038.JPG)

**Comment by xwolfde** [comment]
Ja, es ist beabsichtigt: 
Das Blau an der Stelle ist die CI Farbe des jeweilgen Themes bzw. der Einrichtung.
Wenn wir da also jeweils die CI Farbe haben, haben wir aber das Problem, das bei Verwendung der CI Farbe von Med, Nat und  besonders bei TF der Kontrast zur grauen Hintergrundfläche zu klein ist.
Ergo kann dort keine CI-Farbe verwendet werden, sondern es muss eine einheitliche Farbe sein, die überall gleich ist.

**Comment by wrkb** [comment]
Verstanden. Das bringt aber das Problem mit sich, dass es für den User ein Bruch ist - für den im Backend und den im Frontend. Der im Backend versteht nicht mehr, warum er sich an die Überschriftenstruktur halten soll, wenn es eh nur fett wird (die Leute greifen aus unerfindlichen Gründen immer wieder zur Fettung, wenn es sich anbietet). Und der Frontend-Nutzer sieht - bewusst oder unbewusst - auch nur eine Fettung.

Aktuell ist es auch ein Bruch mit dem Fakultäts-CI (schwarz statt Fakultätsfarbe) - ich würde dafür plädieren, hier das Einheitsblau zu nehmen, dass den besten Kompromiss darstellt.

**Comment by AstridSemm** [comment]
1.) Zur fetten Formatierung greifen die meisten Leute, weil sie's von ihrem Textverarbeitungsprogramm her gewöhnt sind - da kann man nicht viel machen.
2.) Ich schule grundsätzlich so, dass ich den Leuten sage, warum sie Überschriften verwenden müssen; das funktioniert meistens ganz gut, dann ist ihnen auch egal, ob die Überschrift fakultätsfarben oder schwarz ist. Die einzigen Frontend-User, für die der Unterschied "fett vs. Überschrift" wichtig ist, sind Sehbehinderte (und für die schule ich ja auch so). Menschen, die keine Probleme in der Hinsicht haben, nehmen das tatsächlich nicht großartig wahr.
3.) Einen Bruch mit der Fakultäts-CI sehe ich nicht, denn wir befinden uns innerhalb eines Accordions und nicht etwa im Fließtext; dass da andere Regeln gelten können (und des Kontrasts wegen sogar müssen), ist mE nicht im Widerspruch und wird vom Frontend-User problemlos hingenommen.

**Comment by wrkb** [comment]
zu 1): Na das klingt ja  nach Aufgeben ;) Man darf nicht vergessen, dass es immerauch  Webseiten an der FAU geben, die nach dem Mehr-Rollen-Prinzip gepflegt werden, bei dem jemand korrigierend eingreifen kann (nachdem schon gegen das Fetten geschult wurde). Und da ist es schon kontraproduktiv, etwas wie fett aussehen zu lassen, was nicht fett ist. 

Aber zum Rest sage ich nix weiter, ist ja angemerkt und muss mehrheitsfähig sein, sonst halt nicht.

**Comment by AstridSemm** [comment]
Das klingt nicht nach Aufgeben, sondern nach Realitätssinn; ich kenne meine Pappenheimer halt. Deswegen auch 2.) - da vermittle ich das mit den Überschriften nämlich recht energisch. ;o)

**Comment by xwolfde** [comment]
Ich hab alles notwendige dazu oben geschrieben und denke nicht das eine Änderung notwendig und sinnvoll ist.

**Comment by wrkb** [comment]
Mal ein längeres Beispiel. Man kann sich über so lange Akkordeoneinträge streiten (kürzer versuchen wir noch), aber hier sieht man besonders deutlich, dass unsere gesamte Überschriftenstruktur dadurch entwertet wird. Es ist einfach hässlich ;)

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/23457202/36db1a20-fe77-11e6-8ec5-2568dc100c6f.JPG)

(Seite ist ein Entwurf, kein Link verfügbar)
