### ISSUE TITLE
Im Blockeditor fehlt noch das Font-Loading im Stylesheet

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1546]
Im BlockEditor in der BrowserKonsole
![Bildschirmfoto 2024-10-10 um 15 49 04](https://github.com/user-attachments/assets/6110269c-a302-4ed6-9cb8-c61599121537)

**Comment by xwolfde** [comment]
Auf Basis deiner dev oder der main?

**Comment by lukasniebler** [comment]
(Ist noch Dev-Branch)

**Comment by xwolfde** [comment]
duplicate
