### ISSUE TITLE
Sidebar – Abstand zwischen Ansprechpartner fehlt auf Fakultätsthemes

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1548]
# Problem:
Auf der Startseite von Template Startseite-Fakultät fehlt ein Abstand zwischen den Bildern von Kontakten:

## Screenshot
<img width="1623" alt="Bildschirmfoto 2024-10-14 um 09 49 42" src="https://github.com/user-attachments/assets/f6ea1fb2-45e2-470e-b0da-aa3b07d6b6fc">

## Inspector
<img width="966" alt="Bildschirmfoto 2024-10-14 um 09 52 38" src="https://github.com/user-attachments/assets/7b4274b5-06c9-49f8-8bd6-7f2e061ec1b9">

## Beispiel-Website
https://www.entwbio.nat.fau.de

## Konfiguration im Customizer:
WYSIWYG-Editor für Sidebar ist aktiviert

**Comment by xwolfde** [comment]
in dev
