### ISSUE TITLE
Umbruch in den Überschriften der Blogroll auf der Startseite

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/FAU-Einrichtungen#1549]
Seit der letzten Version werden die Überschriften (scheinbar willkürlich?) der Beiträge in der Blogroll auf der Startseite an nicht nachvollziehbaren Stellen mit einem Umbruch versehen. 

Siehe z. B. hier: https://www.nat.fau.eu/ und hier: https://www.nat.fau.de/

Es ist nicht ersichtlich, wieso z. B. bei der Überschrift "KI soll Diagnostik auf Basis von Messdaten aus Blutproben verbessern" nicht umgebrochen wird, aber bei "FAU-Chemiker erforscht funktionelle organische Materialien für die Energiewende" nach "funktionelle" umgebrochen wird, obwohl theoretisch noch genug Platz wäre die Überschrift in der 1. Zeile weiterzuführen. 

Bei der englischen Webseite ist es z. B. genau umgekehrt, da wird bei "AI set to improve diagnostics on the basis of measurement data from blood samples" bereits nach "basis" umgebrochen, bei "FAU chemist researches functional organic materials for the energy transition" wird jedoch nicht in der Desktop-Version umgebrochen. 

Erst, wenn das Browser-Fenster (Firefox 128.1esr) in der Breite deutlich verkleinert wird, findet ein automatischer Umbruch in der Überschrift der AI-Meldung statt. Hier bleibt der Umbruch nach "basis" auch noch vorhanden und wird nicht erneut umgebrochen, wenn bei der anderen Überschrift bereits ein automatischer Umbruch erfolgt nach "functional". Erst, wenn man das Fenster auf Smartphone-Breite reduziert, wird in der ersten Überschrift statt nach "basis" bereits nach "diagnostics" umgebrochen.

**Comment by xwolfde** [comment]
Das ist eine neue EIgenschaft moderner Browser, die Texte "Balanced" umzubrechen. Wenn ein Browser feststellt, dass ein Umbruch erfordern muss, vermeidet es dabei ein einzelnes Wort auf der nächsten Zeile zu lassen, da dies optisch schlecht ist und den Lesefluß stört. Stattdessen werden Browser dann den Umbruch so positionieren, dass die Worte sich möglichst ausgeglichen auf die Zeilen verteilen.
Vgl. auch: https://de.wikipedia.org/wiki/Hurenkind_und_Schusterjunge 


Wie dies genau vorgeht, kann ich nicht sagen. Da bei den jeweiligen Browserengines nachschauen. Aber in den meisten Fällen erscheint mir das durchaus richtig gemacht zu werden.
Wir können da aktuell meines Wissens nach keinen Einfluß nehmen auf die Art und des Orts des balancierten Umbruches einzelner Browser.  Wir könnten es nur ganz verhindern, für alle Browser und nicht für einzelne. Und das wäre auch nicht wünschenswert.
