### ISSUE TITLE
Top Event wird nicht angezeigt, wenn das Datum aus dem Kalender ausgewählt wird

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Einrichtungen#155]
Wenn man aus dem Kalender ein Datum für seinen Top-Event auswählt, wird im Texteingabefeld die lange Schreibweise des Datums eingegeben (z. B. Mittwoch, 12. Oktober 2016). Das Datum muss aber offensichtlich zwingend im Format mm/dd/yyyy angegeben werden, sonst passiert genau gar nichts. Insofern ist der Kalender mit der automatischen Datumseingabe derzeit nicht sinnvoll und kann eigentlich weg.
![top_event_github](https://cloud.githubusercontent.com/assets/11296947/19187008/56b95768-8c89-11e6-8a49-d58694ab4aec.jpg)

**Comment by xwolfde** [comment]
Mein Browser setzt da kein deutsch ausgeschriebenes Datum rein. Das muss ne neue Browserfunktion sein..  :(

**Comment by AstridSemm** [comment]
Ich teste mal in anderen Browsern.

**Comment by AstridSemm** [comment]
In Chrome sieht das Datumseingabefeld so aus:
![bildschirmfoto 2016-10-07 um 15 29 34](https://cloud.githubusercontent.com/assets/11296947/19191524/231d64b6-8ca3-11e6-8224-e1bd50b37302.png)

Wenn man hineinklickt, bekommt man den bekannten Kalender und es passiert bei Anklicken eines Datums nichts:
![bildschirmfoto 2016-10-07 um 15 29 46](https://cloud.githubusercontent.com/assets/11296947/19191544/3db4e2c2-8ca3-11e6-8b80-9205dea9923b.png)

Wenn man auf das Symbol mit dem schwarzen Dreieck, das nach unten zeigt, klickt, kommt ein anderer Kalender, in dem man dann auch das Datum anklicken kann:
![bildschirmfoto 2016-10-07 um 15 30 15](https://cloud.githubusercontent.com/assets/11296947/19191575/602c0cae-8ca3-11e6-927f-7e81955bd29d.png)

Daraufhin wird das Datum mit tt.mm.jjjj eingefügt, was aber wenigstens nicht zu Fehlern führt:
![bildschirmfoto 2016-10-07 um 15 30 27](https://cloud.githubusercontent.com/assets/11296947/19191600/7adb505a-8ca3-11e6-8335-7464fe8c9ba8.png)

Ergebnis:
![bildschirmfoto 2016-10-07 um 15 36 05](https://cloud.githubusercontent.com/assets/11296947/19191701/cc1b8dfe-8ca3-11e6-9854-044853df1843.png)

**Comment by AstridSemm** [comment]
Moment. Warum will Chrome tt.mm.yyyy? HÄ?

**Comment by xwolfde** [comment]
Ok, Ursache gefunden. Wird angegangen

**Comment by xwolfde** [comment]
Boah, die scheinbar kleinsten Probleme erweisen sich wie üblich als die größten Monster... Dauert!

**Comment by xwolfde** [comment]
Ist in der nächsten Version gefixt.
