### ISSUE TITLE
BlockEditor: Deaktivieren des Code-Editors im UI

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1551]
# Problembeschreibung
Der Blockeditor bietet standardmäßig wie der traditionelle TinyMCE einen Code-Ansicht / Code-Editor des Seiteninhalts mit an. Aus Gewohnheit kann es vielen Nutzern passieren, dass sie nach der Bearbeitung im Code-Modus suchen (da das früher oft notwendig war).

Da der BlockEditor allerdings fest auf korrekte Blocklimiter sucht und schon minimale Änderungen in der Code-Ansicht dazu führen, dass Blöcke zerstört werden oder nicht mehr funktionieren / Fehlermeldungen werden, erhöht sich dadurch der Support-Aufwand für uns deutlich.

### Szenario 1
Nutzer verändern im Code-Editor aus Versehen Parameter innerhalb eines Blockkommentars: Der Block erzeugt eine Fehlermeldung im UI und ist nicht mehr verwendbar.

### Szenario 2
Nutzer fügen nicht erlaubte Blöcke über den Code-Editor hinzu. (Eher unwahrscheinlich aber möglich)

### Szenario 3
Blöcke werden um eigentlich deaktivierte parameter erweitert, was zu unerwünschten Ergebnissen im Frontend (Veränderte Font / Styling) führen könnte.

## Mögliche Lösung
Der Code-Editor wird nach Benutzerrolle (z.B. nur Superadministratoren oder ggf. Administratoren angeboten). – Normale Redakteure erhalten keinen Zugriff auf den Code-Editor, damit sie nicht aus Versehen Inhaltsseiten durch die falsche Bearbeitung zerstören.

Das Einschränken der Code-Ansicht sollte auch zu weniger Support-Anfragen in der Zeit der freiwilligen Umstellung führen.

## Mögliche Umsetzung im Code
(Eine Filterung nach Rolle sollte in Betracht gezogen werden, damit der Support noch weiterhin einen Blick auf die Code-Ansicht werfen kann.)
vgl.:
https://www.youtube.com/watch?v=6lBIkf3xNDw&list=WL&index=1&t=299s
https://tremendously-tender-iguana.wp.build/modify-editor-settings-in-php/
``` php
function example_modify_editor_settings_with_context( $settings, $context ) {
	$is_page = $context->post && 'page' === $context->post->post_type;

	if ( $is_page ) {

		// Disable the block-locking user interface.
		// $settings['canLockBlocks'] = false;
		
		// Disable the Code Editor.
		$settings['codeEditingEnabled'] = false;
		
		// Set default image size to Full.
		// $settings['imageDefaultSize'] = 'full';
	}

	return $settings;
}
add_filter( 'block_editor_settings_all', 'example_modify_editor_settings_with_context', 10, 2 );
```

## Auswirkung auf das BlockEditor UI
Der Code-Editor ist für Nutzer ohne Berechtigung automatisch ausgegraut. Die normale Bedienung bleibt ohne Probleme gewährleistet.
<img width="291" alt="Bildschirmfoto 2024-10-17 um 11 19 33" src="https://github.com/user-attachments/assets/de1e1670-6f12-4d82-bb05-407ddcc78fcb">

**Comment by xwolfde** [comment]
Hm...
alles was du da beschriebst ist richtig. Aber ist da das Thema der richtige Ort um so etwas zu machen? Wäre das nicht "Plugin DOmain" ?

**Comment by lukasniebler** [comment]
Wurde bereits durch @rvdforst in Settings umgesetzt und kann deshalb geschlossen werden
