### ISSUE TITLE
Theme wohl nicht kompatibel mit Internet Explorer 9.0 / Windows Vista Ultimate SP2 ?

### ISSUE THREAD

**Issue by csw-** [RRZE-Webteam/FAU-Einrichtungen#156]
Auf System mit o.g. Konfiguration kommt dieses schöne Aussehen zustande: 

![fau](https://cloud.githubusercontent.com/assets/6545158/19192455/931b449c-8ca6-11e6-8dd3-5c6be67a8b49.png)

Der blaue Farbverlauf hat aber dennoch irgendwie was..... nicht.
Schönes We :)

**Comment by xwolfde** [comment]
Windows Vista ist längst aus dem Microsoft Support raus. Ob die Nutzung überhaupt noch legal ist, könnte auch noch hinterfragt werden. An der FAU darf man das nicht mehr nutzen.
Wer hat das denn im Einsatz? Wohin dürfen wir die Anwälte schicken? ^^
Ansonsten: Browserbugs beheben wir nicht.

Dieser Browser wird gerade mal noch bei  0.57 % aller Zugriffe verwendet.
 http://statistiken.rrze.fau.de/browser/allhosts.shtml
Ein Workaround dafür zu machen würde deutlich teurer kommen, als wenn der Anwender  3 Klicks macht und sich ein Update holt.

Wer so einen alten Browser verwendet, ist selbst schuld und durch die bekannten Gefahren durch den Einsatz eines veralteten Browsers auch in bezug auf IT-Security eine Gefahr für sich und andere.
