### ISSUE TITLE
Fehlerhafte Darstellung des Glossars

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Einrichtungen#157]
Auf https://www.wordpress.rrze.fau.de/allgemeines/glossar/ sieht das Glossar derzeit so aus:
![bildschirmfoto 2016-10-10 um 15 51 06](https://cloud.githubusercontent.com/assets/11296947/19238350/699a9638-8f01-11e6-8f88-491657b18690.png)

Eigentlich sollte das alles in Accordien. Was ist denn da schon wieder passiert?

**Comment by xwolfde** [comment]
Accordion-Div wird falsch geschlossen bzw nicht erneut eröffnet

**Comment by xwolfde** [comment]
Ref #165

**Comment by xwolfde** [comment]
Fehler war seltsam...
In deiner Seite war der Shortcode des Glossars von einem "span" umgeben.
Dies führte zu einem Fehler. Nachdem ich es wegtat, war alles in Ordnung.
