### ISSUE TITLE
Bildmaße

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Einrichtungen#158]
Benutzerin schreibt folgendes:
Normalerweise laden wir das Bild mit den Maßen 300 x 150 px hoch. Sollte aber 
aus welchem Grund auch immer einmal ein Bild mit anderen Maßen als Beitragsbild 
eingesetzt werden, wird dieses Beitragsbild mit anderen Maßen eingesetzt (siehe 
Beitrag „testbeitrag“ auf dieser Seite: 
https://kunstgeschichte.cms.rrze.uni-erlangen.de/aktuelles/

Frage meinerseits: Haben sich die Maße für Beitragsbilder geändert? Ich war immer der Ansicht, das wäre 300 x 150 px?

Wie helfe ich jetzt am Besten?

**Comment by xwolfde** [comment]
Ich verstehe die Frage nicht?
Siehe:
https://github.com/RRZE-Webteam/FAU-Einrichtungen/blob/master/functions/constants.php

Ab Zeile 104.

    /* Thumb for Posts in Lists - Name: post-thumb */
    'default_postthumb_width'	    => 220,
    'default_postthumb_height'	    => 147,
    'default_postthumb_crop'	    => false,
   
     /* Thumb for Posts, displayed in post/page single display - Name: post */
    'default_post_width'	    => 300,
    'default_post_height'	    => 200,
    'default_post_crop'		    => false, 


Bedeutet: In der Listendarstellung von Artikeln dürfen Bilder da maximal 220 Pixel breit und 147 Pixel hoch sein. Wenn sie größer sind, werden sie in diese Dimension eingepasst ohne Abschneiden.
Wenn ein Bild hochgeladen wird, dass sehr hoch ist, wird es also auf 147 Pixel höhe runter reduziert und die Beite ist dann proportional dazu.

Bei der Darstellung im Beitrag selbst gelten die anderen Werte, nämlich 300x200.

**Comment by AstridSemm** [comment]
Orrrrr.... dann hatte ich das falsch verstanden und muss mal wieder in der Doku was anpassen. 
Issue bitte nicht schließen, damit ich dran denke.
Wo ist das "Für Doku"-Label geblieben?

**Comment by xwolfde** [comment]
wie lange muss dieser Issue denn noch offenbleiben?

**Comment by AstridSemm** [comment]
Bis ich die Zeit gehabt haben werde, die Bildmaße mit dem, was in der Doku steht abzugleichen und ggf. zu korrigieren. Nachdem die constants.php für Leute wie mich nicht wirklich übersichtlich ist, bedarf das eines Zeitpunkts, an dem ich mich der Angelegenheit mal ein bis zwei Stunden am Stück widmen kann. Ich hab's aber auf dem Schirm, es wird mit ziemlicher Sicherheit dieses Jahr noch was.

**Comment by AstridSemm** [comment]
Habe zwar schon was angepasst, bleibt aber erstmal noch offen für eingehende Prüfung. Ich verstehe das ein oder andere nicht und muss nachfragen.

**Comment by xwolfde** [comment]
Durch den neuen Customizer müssen die Maße nicht mehr gesondert dokumentiert werden, da der Customizer die Maße anzeigt und anbietet, das Bild in die richtigen Maße zu setzen.
