### ISSUE TITLE
Was ist aus dem Linkchecker-Plugin geworden?

### ISSUE THREAD

**Issue by csw-** [RRZE-Webteam/FAU-Einrichtungen#159]
Vor etlichen Monaten gab es noch ein Plugin das, zumindest laut der Beschreibung, die vorhandenen Links hinsichtlich 404-Fehler überprüft. Wird es das Plugin wieder geben?

**Comment by wrkb** [comment]
Laut letztem Treffen mit dem Webteam auf der Todo-Liste. Wir waren uns aber einig, dass es nicht wichtiger als andere offene Arbeiten derzeit.

**Comment by cibsell** [comment]
Würde mich auch sehr freuen, wenn es das Plugin wieder gäbe.

**Comment by xwolfde** [comment]
Eine neue Version ist vorhanden und kann unter der Pluginübersicht aktiviert werden

**Comment by cibsell** [comment]
Danke, gerade schon ausprobiert! Prima.

Bei einer vorherigen Version gab es die Funktion, dass man automatisch beim Aktualisieren der Seite darauf hingewiesen wurde, dass ein Link defekt ist. Wird die Funktion auch wieder eingebaut? 

Werden den Redakteuren / Autoren die fehlerhaften Links irgendwo angezeigt oder sehen nur die Admins diese?

**Comment by wrcg** [comment]
Ja, danke für die neue Version!
Ich hatte jetzt allerdings eine Seite, auf der definitiv falsche Links waren. Diese wurden weder direkt an der Seite noch im Dashboard angezeigt :-( - Wo sind solche Links "versteckt"?

Außerdem habe ich bei den Einstellungen zum Linkchecker noch einen CPT aktivieren wollen, danach hat der Linkchecker nur noch vier Fehler gefunden, die aber nicht speziell in dem CPT waren (vorher waren es über 100...)

Und dann noch ein Wunsch für die Weiterentwicklung: 
Es gibt bei uns einige fehlerhafte Links, die auch nicht mehr korrigiert werden (z.B. Links in sehr alten Pressemeldungen). Hier wäre es schön, wenn es einen Button gibt "diesen fehlerhaften Link ignorieren und dauerhaft ausblenden", damit man diese Links nicht bei jeder Prüfung wieder prüft...

**Comment by cibsell** [comment]
Ich habe auch ziemlich viele "Operation timedout" bei Links zur FAUbox... Wäre schön, wenn man das mit einem Ignorieren-Button ausblenden könnte, da die FAUbox oft sehr langsam ist.
