### ISSUE TITLE
Link auf Akkordeon-Schubladen - geht nicht aus dem Akkordeon heraus

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Einrichtungen#160]
Wir wollten von einem Akkordeoneintrag heraus auf einen anderen verlinken (das war ein des Teil des Mehrwerts der Akkordeonlinks, den wir haben wollten). Geht leider nicht, siehe https://www.fau.de/studium/im-studium/studium-a-z/#collapse_22012370005 - der Link auf Vorabbeglaubigung geht nicht. Kopiere ich ihn in den Browser, geht er.

Lösbar?

**Comment by xwolfde** [comment]
Müsste lösbar sein. Man muss nur statt nur auf das onload zu achten auch Change-Requests auf der Webseite betrachten.

Wer macht es?

**Comment by xwolfde** [comment]
Ihr verwendet da ein Glossar. Und nicht das Standard Accordion.

**Comment by wrkb** [comment]
Oh, ah, Falle. Das heißt, ein Glossar bedient sich nicht der gleichen Mechanik wie ein Akkordeon? Gerade für die Glossare wäre es aber wichtig, naja, genauso wichtig wie bei Akkordeons...

**Comment by xwolfde** [comment]
Genau. Irgendjemand hat es 2014 so programmiert :P   

Denk mal drüber nach, ob das wirklich so richtig und wichtig ist:
Wollt ihr, dass der Leser bei unbekannten Begriffen hin und her springt? Und wenn er z.B. bei einer Kreuzreferenz zu dem Glossareintrag oben gesprungen ist, weiß er vielleicht nicht mehr wo er vorher war (weil die Lasche dann ja wieder zu ist).
Von der Usability finde ich das etwas blöd.

Wenn der Glossar so lange ist wie der eure, wäre es nicht sinnvoller, den über die Kategorien aufzuteilen? 
Und für Kreuzreferenzen, wäre ggf. eine andere Glossardarstellung hilfreich. (Nämlich die, eines Hover-Textes).

Was übrigens auch geht: Ihr könnt wenn ich Kreuzreferenzen habt, ein Glossar in einem Glossar einbauen.
Also in einem Eintrag, der CMS bneschreibt auch ein Glossareintrag zu WordPress machen:
=================
"CMS"
Wir benutzen WordPress.

[Glossary id="$id"]  
================= mit $id = Id für den Glossar eintrag für WordPress.

Aber Achtung: Ihr könnt damit dann auch Loops machen.
Wenn ich in Glossareintrag A ein Shortcode für den Glossar B macht und Glossar B enthält den Shortcode auf Glossar A => Loop.
Oder ihr macht ein Glossareintrag, der in sich selbst den ganzen Glossarindex [glossary] aufruft. Und ruft dann den Glossary auf => Loop.
Die Loops können wir nicht verhindern.

**Comment by wrkb** [comment]
Uh oh, das muss ich mir genauer anschauen mit den Kolleginnen. Wenn es programmiert war, dann ist es tatsächlich nicht sinnvoll, sollte generell geändert werden. Für die außenstehenden Nutzer und für die internen (Autoren), die den Unterschied nicht kennen.

Was das Referenzieren angeht, reagieren wir in Kürze wieder. Es ist chaotisch, ja, aber aktuell auch nicht schön. Danke für die Anregung!

Bis in Kürze

**Comment by wrkb** [comment]
Wir würden die Links auf Glossareinträge gern behalten. Für...

- fau.de-Autoren, die diese Inhalte wie jedes andere Akkordeon verlinken wollen
- FAU-Beschäftigte, die auf sowas verlinken möchten über Ihre Webseiten oder in E-Mails (bei Anfragen von Studierenden z.B.) 
- eine konsistente Bedienung - jedes Akkordeon (egal ob echt oder optisch beim Glossar) funktioniert gleich
- die mobile Bedienbarkeit - hier ist ein Hover ja eher schwierig?

Die Glossare bieten ja einen Mehrwert, den wir sehr wertvoll finden: Sie referenzieren Wissen, dass man sonst überall neu als duplicate content aufführen müsste und vermeidet Letzteres - was ja unser aller Ur-Anliegen ist. Alle haben auf die Verlinkungsmöglichkeit von Akkordeons gewartet - wir sollten sie auch im Glossar haben bitte :smiley:

**Comment by wrkb** [comment]
P.S. Das aktuelle Verhalten ist für uns auch in Ordnung. Man springt ja in der Regel zu anderen Einträgen, wenn einem der vorige nicht half bzw. man ihn gelesen hat. Daher ist das Schließen des alten Eintrags kein Problem. Und selbst wenn man zurück will, ist der Aufwand zumutbar.

**Comment by xwolfde** [comment]
Äh... ich werde und werd nicht schlau darauf, was deine beiden Einträge jetzt inhaltlich mit den vorherigen Eintrag zu tun haben?
Niemand will die Glossare wegmachen.

Mein Rat war aber drüber nachzudenken, ob ihr statt einer riesenlanger einzelseite mit allen Glossareinträgen nicht lieber über die Kategorien oder geschachtelte Glossareinträge die Darstellung der vorhandenen Glossareinträge (ohne sie wegzumachen!) schöner und usabler machen wollt.

**Comment by wrkb** [comment]
> Niemand will die Glossare wegmachen.

Haben wir auch nicht so verstanden. Aber du schriebst

> Denk mal drüber nach, ob das wirklich so richtig und wichtig ist:

in Bezug auf die Angleich des Glossarverhaltens an die "echten" Akkordeons. Und darauf haben wir im Prinzip mit Ja geantwortet :)
Wir wollen also von einem Glossareintrag heraus auf eine andere Schublade verlinken können, das ist ganz wichtig!

Die riesenlange Einzelseite ist grundsätzlich auch erst einmal Okay, das ist nunmal die Natur eines Glossars. - ein Überblickscharakter Kategorisierungen können vielleicht sinnvoll sein, aber das Prinzip kann ich mir grad noch nicht vorstellen.
