### ISSUE TITLE
Update Font Awesome

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#161]
Aktuell ist 4.6.3.
http://fontawesome.io/icons/

**Comment by xwolfde** [comment]
Oh, und dabei ggf. in der Doku ggf. mal eine FAQ machen, wie man eine LInkliste wie hier
https://www.fau.de/category/news/politik/  (rechts die auf die Social Media Plattformen) 
mit Hilfe der Icons ergänzt.

**Comment by AstridSemm** [comment]
ORRRRR! Ja, gut. Aber nicht sofort.

**Comment by xwolfde** [comment]
gestern reicht völlig

**Comment by xwolfde** [comment]
Font Awesome ist im Theme auf 4.7 aktualisiert.
