### ISSUE TITLE
Alphabet-Linksliste bei Glossaren. Buchstaben größer (besser klickbar)

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Einrichtungen#162]
...nicht dringend, aber ein enhancement...

**Comment by xwolfde** [comment]
Ja. Gefällt mir optisch auch nicht

**Comment by wrkb** [comment]
Es war okay für den Anfang. Aber es geht natürlich schöner :smiley:

**Comment by xwolfde** [comment]
Ref #165

**Comment by xwolfde** [comment]
Hab die Buchstaben deutlicher gemacht.
http://test8.tindu.rrze.uni-erlangen.de/tests/shortcodes/glossar-beispiel/

**Comment by wrkb** [comment]
Sieht besser aus :) Aber, wir sind ja nie zufrieden (sorry): Kann man die als Buttons umsetzen, so dass man nicht auf den Buchstaben zielen muss? Man kann auch mit der Maus auf einen Buchstaben fahren und er ist nicht klickbar (zum Beispiel das Jott), weil er so klein ist und man weiterhin genau zielen muss.

Passt das ins CD? Wir haben ja Buttons, das in ihrer Gesamtheit drückbar sind, aber die sind halt dunkelblau...
