### ISSUE TITLE
Standard-Bild für Beiträge funktioniert auf fau.de nicht

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Einrichtungen#163]
Mit Astrid nochmal die Einstellung vorab geprüft (Option ist aktiviert). Für fau.eu noch nicht getestet (aktuell kein Feed dafür frei).

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/19481241/9215d17a-954d-11e6-80d9-f53908a2b7cf.JPG)

**Comment by xwolfde** [comment]
Hm... bei mir gehts?   Und der Fehler sieht irgendwie nicht nach dem Defaultbild aus.
Wenn das Bild nicht vorhanden oder geladen werden konnte, dann erscheint der (leere) Alt-Tag.
Hier aber sehe ich im Bild das broken Image Symbol. Das steht eigentlich für ein Anzeige- und  Ladefehler vom Client?

**Comment by xwolfde** [comment]
WTF?

**Comment by xwolfde** [comment]
Ok. anscheinend sind da noch alte Einträge in den Options, die nicht korrekt durch das neue Themes überschrieben wurden :/

**Comment by wrkb** [comment]
Ok, also Ursache gefunden. Danke Wolfgang :)

**Comment by wrkb** [comment]
Ok, also reparabel. Danke Wolfgang. Wir kommen in 95 Prozent der Fälle auch ohne Standardbild aus bzw. haben wir noch eines in der DB als Workaround.

**Comment by xwolfde** [comment]
Erstmal über Link gelöst. 
@rvdforst Könntest du mal in der Options-tabelle reinschauen und dort die Einträge bei der auf Dateien verwiesen wird und die noch auf   ../themes/fau/.. liegen, die Einträge ändern auf /FAU-Einrichtungen/ ... ?

**Comment by rvdforst** [comment]
Ist erledigt.

**Comment by xwolfde** [comment]
thxs.
Hier ist halt das bewusste Feature, das wir bei Themewechsel die Konfig behalten wollten (und daher bei allen FAU Themes die selbte Optiontable verwenden), zum Nachteil geworden.
