### ISSUE TITLE
Anzeigefehler im Menü Faculties auf fau.eu, Startseite

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Einrichtungen#164]
Der oberste Eintrag ist deutsch (Philfak), obwohl englisch im Backend hinterlegt (und seit Monaten nicht angefasst). Evtl. durch Theme-Umstellung? Bug?

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/19511593/1dc0baf6-95e8-11e6-8e65-778bdb91d0fe.JPG)

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/19511562/fda770a2-95e7-11e6-89ad-9952dccc3c26.JPG)

**Comment by xwolfde** [comment]
Ich hatte eure Menus deaktiviert, so daß dort das Default-Fakultätenmenü verwendet wird, welches im Theme hinterlegt ist.
In dem findet sich offenbar ein Übersetzungsfehler bei der ersten Fakultät, weswegen diese nicht ins englische übertragen wird.

Warum hab ich eure Ersatzmenüs deaktiviert: Weil diese falsch konfiguriert waren bei den CSS-Klassen. Die Balken mit den Farben waren nicht da.
Also entweder kurz abwarten, bis ich ein Update gemacht hab  oder das Menu reparieren. Wichtig ist bei dem Menueintägen, das in der CSS Klasse das Fakultätskürzel enthalten ist. Das fehlte nämlich.

**Comment by wrkb** [comment]
Ich denke, wir können kurz warten. Danke!

**Comment by xwolfde** [comment]
Der Vorteil vom Standard im Theme ist ja auch, daß eure riesige Liste an Menüs aufgeräumt wird und wir für andere ggf. eine Standardliste für die Fakultäten haben. ;)

**Comment by xwolfde** [comment]
Ist in der nächsten Version behoben.

**Comment by wrcg** [comment]
Im Standardmenü im Theme für fau.eu sind offensichtlich die deutschen Websites der Fakultäten hinterlegt. Wenn ich das Standardmenü überschreibe mit einem eigenem Menü (und dabei die Klassen phil, nat, etc. setze) erscheinen zwar die Links korrekt, aber die Farbbalken werden nicht angezeigt :-( Habe ich Zugriff auf das Standardmenü? Wenn ja, wo?
