### ISSUE TITLE
Glossar in Plugin auslagern

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#165]
Das Glossar im Theme soll in ein Plugin ausgelagert werden.
Dabei unbedingt aber die API-Funktionen zum Auslesen beachten.

**Comment by xwolfde** [comment]
Ref #166

**Comment by xwolfde** [comment]
Brainstorming: 
Glossar und Plugin-Inhalte sollten wir ggf. auch so bereitstellen können, dass wir diese bei anderen Websites importieren können. Ggf. solltenw ir hier auch größer denken und eine eigene Verwaltung dafür vorsehen, statt dies als Teil einer Website zu sehen.
Dazu gehört aber dann auch, daß wir die Mehrsprachigkeit mit einbauen.

**Comment by wrcg** [comment]
ja, das wäre eine gute Idee. Ich melde das gleiche mal für das Studiengangsplugin an :-)

**Comment by xwolfde** [comment]
*Hüstel* Das "Studiengangsplugin" ist doch schon ein Plugin...

**Comment by wrcg** [comment]
das weiß ich ich :-) Ich war gedanklich schon einen Schritt weiter...: Ich dachte, du wünscht dir das Gloassar bereits mit Inhalten gefüllt zum Einbinden.

**Comment by xwolfde** [comment]
Relevanzsteigerung durch Anfrage, statisches Daten die wie Glossar-Bezeichner zentral gepflegt werden, auf anderen Webseiten automatisiert einzubinden.

Also:
* Glossar + Synonyme + Daten in einem neuen Plugin zusammenfassen. 
* APIs von/zu anderen Websites
* Zentrale Daten nur an einer Quelle pflegbar
* Eigene Capability

Dringlichkeit wird gerade auf anderer Ebene besprochen. Planung im Januar konkretisieren.

**Comment by xwolfde** [comment]
Wird zu https://github.com/RRZE-Webteam/rrze-faq
