### ISSUE TITLE
Glossar: unterschiedliche Link-Darstellung

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Einrichtungen#169]
Links werden in Glossarbeiträgen unterschiedlich angelegt und angezeigt:

- Beispiel deutsche Glossar (Wissenschaftszeitvertragsgesetz)
Link wird unterstrichen: 
`<a href="http://www.bmbf.de/de/7702.php" data-wpel-link="external" target="_self" rel="follow external noopener noreferrer" class="ext-link wpel-icon-right">`  

- Beispiel englisches Glossar (Employees with children and...): 
Link wird farbig
`<a href="http://www.bmbf.de/de/7702.php">`

**Comment by xwolfde** [comment]
Bitte geb mir doch immer die genaue URL wo ich das sehen kann. Andernfalls muss ich Testseiten anlegen :P

**Comment by wrcg** [comment]
https://www.fau.de/graduiertenzentrum/informationen-a-z/ ->Wissenschaftszeitvertrag
https://www.fau.eu/graduate-centre/information-and-services-from-a-to-z/ -> Employees with children...

**Comment by AstridSemm** [comment]
Verhalten ist bei mir nicht nachvollziehbar (Firefox 49.0.1, Mac, OS Sierra)

**Comment by xwolfde** [comment]
Bei der englischen Seite ist der Link nicht erkennbar, da nicht unterstrichen. 
Möglicherweise ein Zusammenhang mit einem anderen Problem (Nicht setzen der Absätze).

**Comment by xwolfde** [comment]
Liegt an den Problem, dass wir bei dem Glossar WYSIWYG zulassen.
Dadurch wird das <p> nicht forciert drum herum.
Links  im COntentbereich sind aber mit den Absätzen mit Unterstrich formiatiert.

hab als Woraround gemcht, dass wenn ein Link im Accordion-Inner Bereich ist, es genauso formatiert wird, wie als ob es im Absatz wäre.
Im nächsten Update.

**Comment by wrcg** [comment]
danke!
