### ISSUE TITLE
Verlinkbare Images in Artikel-Teaser auf Index- und Startseiten

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#170]
Hallo,

Aus Usability-Gründen haben wir derzeit das Artikelbild bei dem Artikelteaser mit zum Artikel verlinkt.

![screenshot-artikel-teaser](https://cloud.githubusercontent.com/assets/1070669/19638672/3e6ea59c-99d5-11e6-87d1-43054666ab14.png)

Der "WAVE" Validator hat damit zwei (sich etwas widersprechende) Probleme:
1. Das Linkziel ist redundant, da es bereits vorher im Artikel (ind er Überschrift gelinkt ist).
2. Das Bild hat kein Alt-Text (eben, damit dieser text nicht als redundant ein weiteres mal vorgelesen wird).

Ich denke, dass unsere Lösung einen guten Kompromiss gibt zwischen Usability (viele Leute sind es nunmal gewohnt, ein Artikelbild anzuklicken und dann auch zum Artikel zu kommen und Barrierefreiheit (der Alt-Text ist leer, so dass das Linkziel nicht ein weiteres mal vorgelesen wird).

Trotzdem ist die Methodik auch zu hinterfragen.  Daher meine Frage hier: Sollten wir den Link um die Grafik wegnehmen?

**Comment by wrkb** [comment]
Wenn ich auf Webseiten erst den Link zum Artikel suchen muss, weil das Bild nicht verlinkt ist, ärgere ich mich jedesmal richtig. Und frage mich, warum das immer noch so nutzerfeindlich gearbeitet wird. Soviel zu meiner persönlichen Erfahrung/Sicht.

Auch objektiver gesehen ergibt es kaum Sinn, nicht zu verlinken, wo verlinkt werden kann und dem Nutzer Steine in den Weg zu legen oder Möglichkeiten zu nehmen. Es ist nunmal gelernt von gut gestalteten Webseiten (und, nicht zu vergessen: auf Usability getrimmten Onlineshops), dass man Bild, Überschrift und oft noch einen weiteren Link (...mehr) zum Anklicken hat. Manchmal ist sogar der Teasertext verlinkt, aber das haben wir bewusst abgelehnt 2014.

Warum der Validator Redundanz im Jahr 2016 noch als problematisch ansieht, verstehe ich nicht. Redundanz _ist_ umgesetzte Nutzerfreundlichkeit (mehrere Wege zum Ziel), das ist nun keine sonderlich neue Erkenntnis der Usability-Forschung...

Ich denke auch, dass es hier nur einen Kompromiss geben kann. Bild sollte verlinkt bleiben.

**Comment by xwolfde** [comment]
Ich werde gemäß den Tests von Jan-Eric (http://www.hellbusch.de/links-mit-aria-verstecken/)  das Bild als auch den Weiterlesen-Link mit einem aria-hidden="true" versehen.

**Comment by xwolfde** [comment]
In der nächsten Version drin
