### ISSUE TITLE
Merkwürdiges Verhalten bei Umstellung auf FAU Einrichtungen

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Einrichtungen#171]
Am Beispiel von ithron sehen wir, dass das PhilFak-Theme problemos funktioniert:
![bildschirmfoto 2016-10-25 um 10 38 49](https://cloud.githubusercontent.com/assets/11296947/19678745/50673a1e-9a9f-11e6-8da1-6ce9bf0730a0.png)
Beim Versuch, auf FAU-Einrichtungen umzustellen, passiert dann aber dies (das hatten wir auch schon einmal, ich weiß nur nicht mehr, woran es lag):
![bildschirmfoto 2016-10-25 um 10 40 32](https://cloud.githubusercontent.com/assets/11296947/19678785/80f397a4-9a9f-11e6-9bc6-28f95c3abf92.png)

Dasselbe ist's bei alfirin und rrze.cms.rrze.uni-erlangen.de, von daher gehe ich davon aus, dass da irgendwas am Theme schief ist.

**Comment by xwolfde** [comment]
Das ist ein Feature.

**Comment by AstridSemm** [comment]
Ein unerwartetes?
Heute haben wir's übrigens nochmal versucht, da ging es klaglos.

**Comment by xwolfde** [comment]
Ich kann es nicht nachstellen... Vielleicht nur ein temporäres Browserproblem
