### ISSUE TITLE
Kategorien und Schlagworte bei Medien und Seiten

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Einrichtungen#173]
Wo/wie kann ich einstellen, dass ich Kategorien und Schlagworte bei Medien (und auch bei Seiten) vergeben kann?
Siehe Scrennshot der Seite https://tuilinn.zuv.cms.rrze.uni-erlangen.de/wp-admin/  
![2016-10-27 10_43_20-einstellungen](https://cloud.githubusercontent.com/assets/9526974/19760511/60fd7138-9c32-11e6-9aad-420f9c1b8264.png)

**Comment by xwolfde** [comment]
Hast du auf tulinn das Downloads-Plugin aktiviert?

**Comment by wrcg** [comment]
nein, ich hab's aber auch gar nicht in der Übersicht, um es aktivieren zu können :-(

**Comment by xwolfde** [comment]
@rvdforst Bitte prüf mal ob und welche Plugins bei der ZUV CMS iNstanz fehlen. Die, welche bei der zentralen Instanz sind, sollten da auch zur Verfügung stehen. Insbes. RRZE Downloads.

**Comment by xwolfde** [comment]
Issue geschlossen, da kein Issue zu dem Theme. Weitere Kommunikation diesbezug bitte über Mail.
