### ISSUE TITLE
Standard-Symbol für Sprachwechsel

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#177]
Derzeit wird als Symbol für den Sprachwechsler ein Globus-Symbol verwendet.

Es sollte jedoch darüber diskutiert werden, ob dies so richtig ist:
- International setzt sich derzeit ein Sprachsymbol durch. Dieses Symbol wird bereits teilweise von Wikipedia verwendet und ist im AweSome Font auch enthalten: http://www.languageicon.org/ und http://fontawesome.io/icon/language/ 
- Oft verständlicher ist die Nutzung eines Globus-Symboles, welches jedoch nicht eine Skizze der Kontinente zeigt, sondern jeweils 2 Längen und Breitengrade (siehe Google)
- Sehr eingänglich und verständlich sind Sprechblasensymbole http://fontawesome.io/icon/comment-o/
- In der Font Icon Bibliothek ist als Globus-Symbol folgendes enthalten, welches auch in der aktuellen version des Themes verwendet wird: http://fontawesome.io/icon/globe/  (leider zeigt es nur Nordamerika)

Bei den Sprachen selbst wiederum eine Flagge hinzuzeichnen ist von unserem Design her schlecht, aber auch sachlich oft inkorrekt: Die Fahne von United Kingdom steht für die Vereinigten Königreiche von Großbrittanien. Die Fahne von England hingegen ist nicht so gut erkennbar. Dort wird aber nicht überall Englisch-UK gesprochen. Die Fahne von USA ist ebenfalls falsch und besonderes irreführen, weil wir als Sprache auf Englisch-UK setzen. Ähnliches für die Sprache Deutsch? Auch in anderen Ländern wird Deutsch gesprochen: Schweiz und Österreich. Der Schalter ist nicht für Deutsche gedacht, muss aber verständlich für andere sein.

**Comment by wrkb** [comment]
Was ist mit Kürzeln wie EN, DE, FR, CN, ES und Co.? Sicher nicht genormt, aber eindeutig und auch in der URL zu finden.

Flaggen sind absolut inakzeptabel, weil politisch inkorrekt. Ich sag nur Kolonialmächte... ;) Den Rest hast du schon erwähnt, anmaßend und inkorrekt (australisches Englisch, neuseeländisches Englisch...).

Das Sprechblasensymbol ist irreführend, erinnert an eine Kommentarfunktion. Dann lieber das aus dem ersten Punkt (auch nicht so dolle) oder einen anderen Globus. Der Globs war auch nicht der Weisheit letzter Schluss, uns fiel nichts besseres ein.

Sollen wir mal benchmarken gehen?

**Comment by xwolfde** [comment]
Die Sprachkürzel (oder deren Ausschreibungen) sind nach wie vor vorhanden. Es geht um das allgemeine Symbol für den Schalter. Derzeit eben der Globus.
Am liebsten würde ich ein Icon aus dem Awesome Font Satz nehmen, damit nicht mehr (wie bisher) eine eigene Datei geladen werden muss.

**Comment by wrkb** [comment]
Achso, ja, ich meine, dass der Globus ganz wegfliegt und man die aktuelle Sprache sieht. In der Annahme, dass jeder kapiert, dass damit die aktuelle Sprache gemeint ist. Was meint ihr dazu?

Ich stöber mal in FA, das macht immer Spaß :smiley:  :hooray:

**Comment by wrkb** [comment]
Okay, in FA gibts nix weiter. Dann "language", wenn mein anderer Vorschlag nicht gefällt. Aber "language" sieht auch aus wie Spielkarten oder ein Buch oder sowas. Supereindeutig würdeich das nicht nennen, zumal man asiatische Schriftzeichen im europäischen Nutzerkreis auch nicht aus dem Alltag kennt...

**Comment by xwolfde** [comment]
Diskussion in dem Zusammenhang auch hier:
https://forum.selfhtml.org/self/2016/jul/4/webseite-mehrsprachig-gestalten/1670759#m1670759

Manches aus dem riesen Wust ist dann doch wertvoll.

**Comment by wrkb** [comment]
Interessant ist dort, dass die Flaggen Anstoß erregen - das bestätigt im Wesentlichen deren Brisanz.

**Comment by wrkb** [comment]
![unbennant](https://cloud.githubusercontent.com/assets/9445370/21850801/9d98a57a-d80c-11e6-9b77-f775eea0f310.jpg)

**Comment by xwolfde** [comment]
Hier zwar ohne Flaggen, aber es zeigt, dass auch im United Kingdom, dessen Flagge gern verwendet wird, English nicht das einzige Wahre ist :) 
https://www.youtube.com/watch?v=NMS2VnDveP8

**Comment by wrkb** [comment]
Den Wolfgang gefundenen Link dann auch gleich hier noch rein, für die nächste Diskussion (jenseits dieser), in der schöne bunte Bilder wichtiger sind als professionelle Umsetzung: http://t3n.de/news/internationale-website-sprachumschaltung-748172/

**Comment by xwolfde** [comment]
Nach all den Feedback und den Erfahrungen mit inzwischen einigen Dutzend Anwender, würdeich vorschlagen, daß eine Erneuerung an der Stelle wie folgt aussieht:

1. Als Symbol wird von der Weltkugel auf das internationale SPrachsymbol gewechselt, welches immer mehr Verbreitung findet.
2. Per Default wird die (erste) anderer Sprache angezeigt auf die man wechseln kann und nicht die aktuelle Sprache

**Comment by xwolfde** [comment]
IIn der neuen Version enthalten
