### ISSUE TITLE
Jahresanzeige bei Events

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#178]
Bei de Anzeige von Terminen wurde es so gestaltet, daß nur Tag und Monat dabei steht.
Es fehlt aber an einer Angabe zum Jahr.
Das ist doof, wenn man Termine hat, die über den Jahreswechsel gehen odie die länger zurück/weiter voraus liegen.

tl;dr: Wie/wo soll das Jahr stehen?

@RRZE-Webteam/fau-webredaktion

**Comment by wrkb** [comment]
Wir haben auch grade drüber beraten und haben uns gegen ein Issue entschieden, da es inhaltliche Lösungen geben sollte und - in der ZUV - das Problem so sonst nicht auftritt.

Das Problem tritt eigentlich nur auf, wenn sehr wenige Termine im Kalender sind und somit nicht ersichtlich wird, dass mehrere Jahre abgedeckt werden. Zum Jahreswechsel wird es eigentlich automatisch logisch. Das kann man aber auch gut über Überschriften oder Kalenderbezeichnungen abdecken. Oder mehrere Kalender (wobei das nicht die Ideallösung ist).

Da es schwierig ist, das Jahr auch noch unterzubringen, optisch, könnte Pragmatismus also helfen.

Ansonsten fällt mir spontan ein:

- Zwischenüberschrift vor den ersten 2017er-Termin
- Das Kästchen höher machen und das Jahr drunter (wird noch kleinteiliger und schwerer lesbar)

**Comment by xwolfde** [comment]
Woanders(TM) wollen wir eine Lösung der Form machen:
![ausschnitt-kalender-rrze](https://cloud.githubusercontent.com/assets/1070669/19928314/3a9b7014-a0fe-11e6-94f7-d325eff2e40b.png)

(Anmerkung: Bitte nicht nur an euch denken. Corporate Design bedeutet, dass wir auch an andere Anwendungsfälle berücksichtigen und unterstützen müssen. Ansonsten ist es kein Corporate Design, sondern nur Dekoration)

**Comment by AstridSemm** [comment]
Diese Lösung finde ich übrigens sehr gut.

**Comment by wrkb** [comment]
@xwolfde Ich berücksichtige doch bei _jedem_ Posting auch andere Fälle und verweise explizit darauf :) Es geht also nie um Definitionshoheit o.ä., sondern nur um unsere Erfahrungen oder konstruktive Vorschläge.

Weil ich ja immer was zu nörgeln habe: Die Lösung oben ist eigentlich schicke, aber: Das Vertikale ist für mich schwer lesbar - weil man streng genommen den Kopf drehen muss oder eben länger ninschauen. und wegen des Kontrasts (graue Schrift). Und wegen zu vieler Details.

Diese Kalenderkästchen orientieren sich ja am klassischen Abreisskalender bei der Gestaltung, und bei dem ist das Jahr eben nicht oder nur am Rande vorgesehen (https://www.google.de/search?q=abreisskalender&client=firefox-b-ab&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiZ_ubDkYrQAhWJbxQKHdqlDS8Q_AUICCgB&biw=2560&bih=1329)

**Comment by wrkb** [comment]
Auf die Schnelle hingekliert, Abstände grauenhaft, aber Aussage sollte klar sein. Jahr schwarz/anthrazit auf weiß ohne Rahmung drunter und die Platzierung schöner machen?

![unbenannt-1](https://cloud.githubusercontent.com/assets/9445370/19930159/6ce8cc52-a107-11e6-964d-9557d39c4e3a.jpg)

**Comment by lagerlit** [comment]
Ich bin nicht dafür, das Kalenderblatt auf diese Weise zu überfrachten. Bei einer Lösung darf das Jahr visuell nicht in Aufmerksamkeitskonkurrenz mit dem Datum (Tag/Monat) treten. 

Vorschlag: In den wenigen Fällen, in denen es nicht klar wird (weil die zeitlichen Abstände zwischen den Terminen zu groß sind - bei Nov/Dez/Jan/Feb in der Abfolge gibt es ja keine Schwierigkeiten - das Ganze besser über den Veranstaltungsnamen lösen, wie zB "Vortrag Wissenschaft auf AEG 2017".

**Comment by xwolfde** [comment]
Da hält sich ja keiner lange dran...
ich würde jetzt erstmal vorschlagen, das vollständige Datum und ggf. Zeiten, wenn vorhanden, beim Text nochmal hinzuschreiben.

**Comment by wrkb** [comment]
Als erste Lösung sicher das Beste und so schön unaufwändig. Den Rest vielleicht fürs Designgremium mal mitnehmen. Es ist eine Mischung aus Usability (less is more), möglichen User-Anforderungen und Geschmack.

Bechmark:

![rwth](https://cloud.githubusercontent.com/assets/9445370/19935093/30494544-a119-11e6-9c8a-8c024a351689.JPG)
![chemnitz](https://cloud.githubusercontent.com/assets/9445370/19935098/304f246e-a119-11e6-8bec-cd39e9ca8bfa.JPG)
![fau-florida](https://cloud.githubusercontent.com/assets/9445370/19935094/304b06c2-a119-11e6-8f40-e7f2a5ef0606.JPG)
![hamburg](https://cloud.githubusercontent.com/assets/9445370/19935095/304bf60e-a119-11e6-9f53-f2e17c99c7a2.JPG)
![koeln](https://cloud.githubusercontent.com/assets/9445370/19935097/304d2894-a119-11e6-9d16-9703723f8222.JPG)
![michigan](https://cloud.githubusercontent.com/assets/9445370/19935096/304c942e-a119-11e6-80d3-fc79b33fe7a0.JPG)

**Comment by cibsell** [comment]
Hallo,

das Problem hatte ich schon einmal angesprochen. Ich glaube, in FAU Events, aber das kann ich nicht mehr finden...

Wir haben jährlich wiederkehrende Veranstaltungen, z. B. Schülertage oder Einführungsveranstaltungen, die z. B. über Google gesucht werden und dort natürlich auch über Jahre hinweg gefunden werden. Wenn keine Jahreszahl dabei steht und diese auch nicht explizit im Text enthalten ist, notieren sich die Besucher ein falsches Datum. 

Ich finde den 1. Vorschlag von Wolfgang mit der vertikalen Jahreszahl im Kästchen gut.

**Comment by wrkb** [comment]
> und dort natürlich auch über Jahre hinweg gefunden werden. 

Wenn ich genau drüber nachdenke: Wieso wird denn alter Content noch gefunden bzw. wieso ist er nicht im richtigen Archiv-Kontext zu finden? Das ist eher eine Kommunikationsfrage und sollte nicht aufs ganze Design durchschlagen.

Wir haben noch einmal intern gesprochen und das Empfinden unserer direkten Kollegen abgefragt. Vertikaler Text stößt überall auf Ablehnung, er stört eben bei der Wahrnehmung. Dazu noch folgende Fragen @xwolfde :

A) Wie steht es mit der Barrierfreiheit?

- Technisch sicher durch CSS gewährleistet? 
- Optisch von der Anordnung und den Kontrasten her - Lesbarkeit usw.?
- Redundanz beim Vorlesen?

B) Wie passt das eigentlich mit der Spaltenbreite im Kalender? Die ist doch optimiert für das bisherige Icon und den Text - soll der Text jetzt in der Breite schrumpfen für eine Angabe, die nur wenige Admins/Webmaster benötigen oder wächst die Spaltenbreite?

@lagerlit

**Comment by xwolfde** [comment]
Die Sache mit dem Beispiel für die vertikale Datumsangabe war nur ein Vorschlag zur Diskussion. Das war kein Demo für das aktuelle Theme. Der Screenshot kommt auch aus einem anderen Theme. 
Wenn wir das aktuelle Theme an der Stelle ändern oder ergänzen, dann würden all die Fragen geklärt werden, wie es dort dann tatsächlich optisch aussieht.

**Comment by wrkb** [comment]
Ja, eine Diskussion wäre an dieser Stelle wünschenswert. Und da du ja im Issue #25 beim Kalender die Jahreszahl anfragst, wäre es doch sicher möglich, am Termin selbst das Jahr deutlich zu machen, nicht in der Kalenderblattansicht. Wäre die beste Lösung IMHO.

Wir warten also auf die Debatte :)

**Comment by cibsell** [comment]
> Wenn ich genau drüber nachdenke: Wieso wird denn alter Content noch gefunden bzw. wieso ist er nicht im richtigen Archiv-Kontext zu finden? Das ist eher eine Kommunikationsfrage und sollte nicht aufs ganze Design durchschlagen.

Weil Google nichts vergisst?

**Comment by wrkb** [comment]
> Weil Google nichts vergisst? 

Es gibt meiner Meinung nach drei Wege, da für Klarheit zu sorgen:

Alten Content offline nehmen, dann vergisst ihn Google durchaus.

Alten Content inhaltlich vom neuen Trennen - also in einen anderen Kalender überführen in dem Fall. Sonst muss der Nutzer doch verwirrt werden?

Alten Content deutlich als solchen zu kennzeichnen - inhaltlich mit Archiv-Hinweisen und mit SEO-Maßnahmen - also Archiv-Hinweise auch in den relevanten Feldern. Und vielleicht auch canonical links setzen, so dass Google die alten Seiten nicht höher als die neuen gewichtet. Usw.

**Comment by xwolfde** [comment]
Wenn es um das Design geht, sollten wir zwischen Optik für sehende Menschen auf Desktop und Mobile Devices einerseits , von dem maschinen. und screenreader-lesbaren Content andererseits unterscheiden.
Das sollte man nicht zusammenschütten.
Ganz klar ist und muss sein: Wir müssen bei einer neuen Version des Plugins das Markup ohnehin um entsprechende Codes ergänzen mit dessen Hilfe Suchmaschinen und Screenreader den Text als solchen interpretieren können. Dazu muss dieser aber keinesfalls sichtbar sein.

Wenn wir nur auf das sichtbare Bezug nehmen wollen, dann muss die Frage gestellt sein, was wir als optisches und dekoratives Element nutzen wollen und was als textuelles Element. 
Der Bedarf zur Anzeige eines Jahresdatums wurde oben ja bereits formuliert und ist plausibel. Ich denke, die Sachlage an der Stelle ist klar: Es muss die Möglichkeit geben, die Jahreszahl anzugeben. Punkt.

Das bedeutet aber nicht, dass die Jahresangabe im dekorativen Element des Tags-Monatsdatum angezeigt werden müsste. Stattdessen könnte man auch ein neues dekoratives Element schaffen oder das Jahresdatum ganz banal nochmal beim Textbereich darstellen.

**Comment by wrkb** [comment]
> oder das Jahresdatum ganz banal nochmal beim Textbereich darstellen.

Wenn du die Detailansicht des Termins meinst: Da ist es sogar ein Mangel, dass sie nicht sichtbar ist - fiel uns bisher nur nicht auf.

**Comment by xwolfde** [comment]
Anmerkdung: Mit der Textwüste will ich niemand erschrecken. Bitte macht Vorschläge, wie wir das machen können. 
Reden wir nicht mehr über das OB, sondern gehen einfach von dem Case auf, das wir nun Termine mit Jahresdatum haben. Wie sollen diese angezeigt werden auf der Übersichtsseite (nicht auf der Detailseite! Bitte jetzt nicht noch ein Randthema dazumixen).

**Comment by AstridSemm** [comment]
Auf der Übersichtsseite reichen Tag und Monat meiner Ansicht nach vollkommen aus (da rede ich vom dekorativen Element), denn es werden ja (hoffentlich!) auf der Übersichtsseite nicht alle Termine über mehrere Jahre hinweg angezeigt. Wenn die Termine auf einer Seite eingebunden sind, begrenzt man ja sinnvollerweise auch die Anzahl.

Technisch (also für die Suchmaschinen) könnte man das doch im Hintergrund einbinden, so dass es nicht optisch sichtbar ist, oder? Die Frage wäre dann auch, inwieweit es stört, wenn Screenreader die Jahreszahl mit vorlesen (was ich persönlich jetzt für völlig unschädlich hielte).

Just my 2ct.

**Comment by wrkb** [comment]
Problem: Auf der Übersichtsseite sehen wir keinen Bedarf - unserer Meinung nach erschließt sich aus dem Kontext, dass ein Termin im Folgejahr stattfindet. Der von cibsell geschilderte Fall ist meiner Meinung nach ein strukturelles/inhaltlich es Problem, dass anders gelöst werden sollte. Und bei den wenigen denkbaren Ausnahmen (jemand hat 4 Termine für die nächsten 3 Jahre als Kalender angelegt) sind schlicht bessere Lösungen denkbar - da ist der Kalender vielleicht das falsche Mittel zur Darstellung. Bei den Personenvisitkarten denken wir hier doch auch pragmatisch und das sollten wir im Interesse aller Nutzer und des Designs auch hier tun.

Wurde denn sonst noch Bedarf dafür gemeldet?

**Comment by cibsell** [comment]
> Alten Content offline nehmen, dann vergisst ihn Google durchaus.

Das ist nicht gewünscht, weil z. B. die Organisation von Fachvorträgen Teil der Öffentlichkeit von Forschungsprojekten sein kann und längerfristig sichtbar sein sollen.

> Alten Content inhaltlich vom neuen Trennen - also in einen anderen Kalender überführen in dem Fall. Sonst muss der Nutzer doch verwirrt werden?

Ich weiß nicht, ob die Webredaktion für diesen Vorschlag das Personal hat, die Departments und Lehrstühle haben für so einen zeitaufwändigen Vorschlag kein Personal. Bitte daran denken, dass die Lehrstühle und Departments keine Vollzeit-Webmaster haben, sondern dass oft Sekretärinnen oder Doktoranden die Termine als einen winzigen Teil ihres Aufgabengebiets in den Kalender einpflegen.

> Alten Content deutlich als solchen zu kennzeichnen - inhaltlich mit Archiv-Hinweisen und mit SEO-Maßnahmen - also Archiv-Hinweise auch in den relevanten Feldern (das erscheint dann auch in den Suchergebnissen). Und vielleicht auch canonical links setzen, so dass Google die alten Seiten nicht höher als die neuen gewichtet. Usw.

Siehe Punkt 2... Wenn die Lehrstuhlsekretärin oder der Doktorand, der die Seiten betreut, entsprechend geschult werden, können sie das vielleicht auch korrekt anwenden.

Abgesehen davon: Mir geht es um die Detailseiten der Kalendereinträge, nicht um die Übersichtsseiten (kam im Thread nicht heraus, dass es nur um die Übersicht geht). Auf der Startseite einer Webseite reichen Tag und Monat aus, aber auf der Übersichtsseite muss per se die Jahreszahl vorhanden sein.

**Comment by wrkb** [comment]
Also geht es gar nicht um die Übersicht mit Kalenderblättern... das ist doch schon mal eine wichtige Erkenntnis. Die Detailansicht ist ein ganz anderes Thema.
Ich unterstelle aber dennoch, dass es noch genügend Nutzer gibt, die einen kleinen Datumshinweis übersehen - auch optisch im Kalenderblatt-Icon - wenn da nicht irgendwo groß "Archiv" steht. 

Wir überlegen auch mal, wo das Jahr gut hinpassen könnte, gemäß Wolfgangs Aufforderung.

> Ich weiß nicht, ob die Webredaktion...

Keinesfalls haben zuviel Kapazitäten, deswegen müssen die Anwender/Entscheider für einen Anwendungsbereich sicherstellen, dass sie betreuen können, was online ist. Und Archive brauchen leider auch Betreuung - besonders wenn sie explizit gewünscht werden. Sie müssen aber z.B. nicht in einem Kalender geführt werden, der ist ja eigentlich nur für aktuelle Inhalte gedacht - ich halte ihn schlicht für das falsche Mittel.  Ich wollte hier aber keine Anwendungsszenarien vergleichen oder über einen Kamm scheren, das wäre unfair. Aber Anpassungen am Gesamtdesign wirken auch auf alle Nutzer und sollten keine Einzelszenarien abfangen - das gilt selbstverständlich auch für die ZUV.
