### ISSUE TITLE
Notice bei Theme Options-Seite

### ISSUE THREAD

**Issue by endv02** [RRZE-Webteam/FAU-Einrichtungen#186]
Notice: Undefined index: admin_user_level in /proj/websource/docs/RRZEWeb/www.irgendwas.test.rrze.uni-erlangen.de/websource/wp-content/themes/FAU-Einrichtungen/functions/theme-options.php on line 84

**Comment by AstridSemm** [comment]
Beim alfirin diesmal nicht... Es ist merkwürdig.

**Comment by xwolfde** [comment]
Auf deinem Testserver spukt es ja auch.

**Comment by AstridSemm** [comment]
Das Biest ist in der Multisite-Instanz...

**Comment by xwolfde** [comment]
Die Meldung erscheint nur auf ausgewählten besonders dafür konfigurierten Servern :P

**Comment by AstridSemm** [comment]
Ah. Na dann ist's ja gut. :oD

**Comment by xwolfde** [comment]
Im nächsten Update behoben
