### ISSUE TITLE
Top-Entrys mit veralteten Terminen werden angezeigt

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#187]
Zwei Meldungen dazu. Prüfen!

**Comment by xwolfde** [comment]
Test ergab, dass es sich wohl um Einträge mit ungültigen Datumsformat handeln muss.

**Comment by AstridSemm** [comment]
Ja, und sehr lustiger Effekt: Auf dem alfirin war ein Top-Event vom 8.10.2016. Da habe ich jetzt das Schlagwort "top" entfernt und ihn aus der Kategorie "Top Event" genommen. Jetzt hat er das Datum Freitag, 27.Mai 2022. Ich bin ein wenig irritiert...
![bildschirmfoto 2016-11-10 um 15 37 45](https://cloud.githubusercontent.com/assets/11296947/20180657/a9fc59e2-a75b-11e6-9d6c-28e51909f736.png)

**Comment by xwolfde** [comment]
Danke, das hilft gerade zur Erkennung & Simulation.

**Comment by AstridSemm** [comment]
Bitte. Dann lasse ich den Beitrag erstmal so, wie er ist.

**Comment by xwolfde** [comment]
Jupp. Fix ist in Arbeit.

**Comment by xwolfde** [comment]
Fixed
