### ISSUE TITLE
Sidebar Startseite bei leeren Content in Sidebar 

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#188]
Wenn die Sidebar leer ist, sollte der COntent über ganze Seite gehen.
Ist nicht mehr so. Prüfen.
Mögl. Zusammenhang mit Top-Events.

**Comment by xwolfde** [comment]
Nach dem Code sieht es nicht nach Bug aus, sondern nach einem fehlenden feature. Es war schon immer vorgesehen, dass auf der Startseitze eine Sidebar sein musste.

**Comment by AstridSemm** [comment]
Richtig; CD und so... ^^

**Comment by xwolfde** [comment]
Wollen wir das erlauben? Sprich: Soll ich was einbauen, dass den Weißraum der leeren Sidebar dort beseitigt?
Wichtig: Es geht nur um Startseiten! Bei normalen Standard-Pages ist das schon optional drin.

**Comment by AstridSemm** [comment]
Das müßte man mal vor sich sehen. Vom Gefühl her würde ich sagen: Eher nicht, weil sonst leicht zuviel Text da ist.

**Comment by xwolfde** [comment]
Musst halt von der Startseite (Normal, nicht Fakultät die Infos aus der Sidebar entfernen).

**Comment by wrcg** [comment]
wenn ich mich kurz einmischen darf:
Hier eine Seite ohne Sidebar auf der Startseite... https://www.kompetenzzentrum-religion.fau.de/
Aus meiner Sicht wäre es schöner, wenn hier der Text über die ganze Breite geht. 
Ich sehe nichts, was dagegen sprechen würde, es nicht zu erlauben.

**Comment by xwolfde** [comment]
fixed
