### ISSUE TITLE
Upload .key - Apple-Keynote-Dateien, LaTeX

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Einrichtungen#192]
Neben den Powerpointfolien auf https://www.fau.de/intranet/fau-repraesentieren/powerpoint-vorlagen/ wollen wir nun auch weitere Formate anbieten - Apple Keynote (.key) und LaTeX.

Der Upload von .key-Dateien ist derzeit nicht erlaub - kann das erlaubt werden?
Zu LaTeX weiß ich noch nichts, die Dateien erreichen uns erst später.

**Comment by xwolfde** [comment]
Nein, .key geht nicht. Und bei Latex: Welches konkrete LaTex-Format?
Und was hat das mit dem Design/Theme zu tun? Hier ist das völlig falsch. Solltesrt du inzwischen wissen.

**Comment by wrkb** [comment]
Es geht per interner Mail weiter, danke soweit :)
