### ISSUE TITLE
Top-Event: Bug bei der Datumsüberprüfung? Prüfung nur auf Tag/Monat, nicht Jahr

### ISSUE THREAD

**Issue by csw-** [RRZE-Webteam/FAU-Einrichtungen#193]
Ich wollte gerade den Hinweis zum Universitätsball (am 4.2.17) als Top-Event einbinden, leider hat das nicht geklappt. Bei der Datumsangabe 4.2.2016 wird das Event allerdings korrekt angezeigt.
Ich nehme daher an, dass bei der Datumsüberprüfung die Jahresangabe nicht mit einbezogen wird oder da in der Abfrage ein entsprechender Fehler vorliegt.

Vg, C.

**Comment by xwolfde** [comment]
"Ich wollte gerade den Hinweis zum Universitätsball (am 4.2.17) als Top-Event einbinden, leider hat das nicht geklappt."

Und wie bist du dabei vorgegangen?

**Comment by csw-** [comment]
https://www.wiso.rw.fau.de/2016/11/15/universitaetsball-der-fau/

Top-Event: An
Datum: 04-02-2017

Mit den oben eingestellten Eigenschaften wird das Top-Event nicht angezeigt.

**Comment by xwolfde** [comment]
Ok, wir haben da ein Problem mit der SQL-Query bzw. der Art der Speicherung der aktuellen Datumseinträge bei der jetzigen Abfrage.
Dieses Problem tritt dann auf, wenn das Datum vom Top-Event-Eintrag nicht im selben Jahr liegt.

Workaround:
**Kein** Datum setzen, dafür den Beitrag als Top Event aktivieren

Das Datum dann im Text reinschreiben.

Eine Lösung wird leider erfordern das Datumsformat zu speichern. Damit weren dann aber alle
alten Einträge mgwl. obsolet. bzw. es kann dazu kommen, das alte Einträge sichtbar werden.
Das möchte ich daher lieber in Ruhe angehen.
D.h. erst zum nächsten Update, welcher wohl erst im nächsten Jahr kommen wird.

**Comment by xwolfde** [comment]
Im nächsten Update ist das Problem gelöst.
Aufgrund der Natur das Problems (s.o.) macht es Sinn, ein Update erst zum jahreswechsel durchzuführen.
