### ISSUE TITLE
Kennzeichnung von deutschsprachigen Links auf englischsprachiger Seite (u.U.)

### ISSUE THREAD

**Issue by FlorianFiller** [RRZE-Webteam/FAU-Einrichtungen#198]
Ich bin derzeit auf der Suche nach einer Möglichkeit - vergleichbar den MimeType Icons - Links auf (externe wie interne) Seiten in einer anderen Sprache irgendwie optisch zu kennzeichnen; idealerweise mit einer kleinen Flagge o.ä.
Leider habe ich dazu nichts gefunden. Notfalls ließe sich natürlich manuell immer ein kleines Bildchen einbauen, aber schöner wäre natürlich eine "saubere" Lösung.

**Comment by wrkb** [comment]
Auch hier wieder der Hinweis, dass Flaggen problematisch sind, da sie Nationen und politische Systeme, aber keine Sprachen symbolisieren. Wolfgang hat dazu kürzlich einen Link mit einer kontroversen Diskussion gepostet. Wir haben sie auf fau.de und fau.eu verbannt.

**Comment by FlorianFiller** [comment]
Das Problem ist durchaus nachvollziehbar, dem "Argument" "Eine Flagge steht für ein Land" würde ich aber ganz klar den "metaphoprischen (Sprach-)Gebrauch" entgegensetzen. Ich lasse mich aber auch gerne zu Alternativen überreden.
"Flaggen sind problematisch" ist keine Lösung.

**Comment by xwolfde** [comment]
Bisher gab es diesen Bedarf nicht, daher gibt es im Theme an der Stelle auch so nichts.
Manuell kann man aber selbst da ran, indem man eben manuell die entsprechenden Symbole hinzufügt **UND** auch den hreflang-Attribut im Link ergänzt.

Aber da Manual natürlich auf Dauer fehleranfälig und aufwendig ist, wäre eine automatisierbare Lösung besser. 
Damit eine automatische Lösung funktionieren kann, muss dieser aber irgendwas haben, um zu erkennen, dass die zu verlinkende Webseite anderssprache ist.  
Das heisst: Derjenige der eine Seite anlegt, muss diese Seite schonmal richtig sprachlich kennzeichen.  Ansonten funktioniert da nichts automatisch.
Eine Erkennung könnte theoretisch also so ablaufen, dass beim Setzen eines Links auf eine andere Seite, diese andere Seite danach automatisch besucht wird. Hat dann die andere Seite im HTML-Code eine Sprache angegeben und unterscheidet sich diese Sprache von dem Dokument von dem aus der Link gesetzt wurde, dann wird ein entsprechendes Symbol fällig.

Machbar ist das.
Der Aufwand wäre aber nicht gering. Auch die Performance wird darunter leider.
Und die Zielseiten müssen sprachlich natürlich von einem Menschen mit der richtigen Sprache versehen werden.

Um weiviele Seiten handelt es sich denn aktuell bei Ihnen?
Nur um den Kosten-Nutzen-Aufwand abzuschätzen.

**Comment by xwolfde** [comment]
add zum Symbol: Dazu gibt es bereits hier eine Diskussion: #177 . Bitte das am besten dort weiterführen.

**Comment by wrkb** [comment]
@xwolfde Ich würde gern unter #177  weiter diskutieren, aber da kann ich Herrn Filler nicht per @ addressieren... (Das Problem haben wir in der Webredaktion in diversen Github-Threads).

@FlorianFiller 
Habe die Änderung erst jetzt gesehen, Github meldet keine Edits extra per Mail. Daher die späte Antwort.
Es finden sich immer Beispiele für schlechte Praxis, dict.dd z.B. nutzt bei der Sprachauswahl keine Flaggen. (die Flaggen bei den Usern sind dann wirklich Nationen-bezogen).

Zur Frage "Wer denkt bei diesen Flaggen denn bitte primär an "politische Systeme"?":
Wir vielleicht nicht, wir sind aber auch nicht die Betroffenen (sitzen als Webmaster quasi im Elfenbeinturm). Aber Flaggen stehen auch für Kolonialherrschaft, für politische Verwicklungen und für ethnische Konflikte. Kann man sich als Deutscher aus eigener Erfahrung kaum vorstellen, man muss das antizipieren. Ein lahmer Vergleich: Würde für die deutsche Sprache auf Webseiten plötzlich die österreichische Flagge genommen irgendwo, wäre das gefühlt merkwürdig.
Ich bin nicht mal ein Freund übertriebener political correctness, aber gegen die Flaggen spricht einfach zuviel und sie sind dabei so leicht zu vermeiden.

Flaggen stehen vielleicht auch für Sprachvarianten - bedeutet eine UK-Flagge, dass wir auf den Webseiten nur British English einsetzen? (eine sehr beliebte Diskussion an der FAU).

Letztendlich ist das alles bitte nicht dogmatisch zu sehen, es war als Anregung oder freundlicher Hinweis gedacht, auch aufgrund der Diskussion in #177 . Mangels FAU-weiter Entscheidung muss hier jeder selbst seine Lösung finden :)

**Comment by wrkb** [comment]
![unbennant](https://cloud.githubusercontent.com/assets/9445370/21850814/ae10feac-d80c-11e6-8396-d95e0a3ba8ae.jpg)

**Comment by FlorianFiller** [comment]
@xwolfde 
"Um weiviele Seiten handelt es sich denn aktuell bei Ihnen?
 Nur um den Kosten-Nutzen-Aufwand abzuschätzen."

Aktuell geht es nur um ein paar (semi-externe) Links auf der englischsprachigen Seite, um kenntlich zu machen, dass es unsinnig ist, den Link anzuklicken, wenn man kein deutsch kann:
[https://www.phil.fau.eu/faculty/departments/](https://www.phil.fau.eu/faculty/departments/)

Bei hohen Kosten also wohl nicht in einer günstigen Kosten-Nutzen-Relation.

**Comment by xwolfde** [comment]
Die praktikabelste Lösung erscheint mir momentan die Einführung eines Shortcodes, welches man selbst einfügen kann:

[symbol type="flag" value="en"]  zeigt eine englische Flagge (Britisch)
[symbol type="flag" value="de"]  zeigt eine deutsche Flagge
[symbol type="flag" value="int"]  zeigt das neue internationale Sprachsymbol

**Comment by xwolfde** [comment]
Im Theme passt dies nicht, da es ja auch andere Themes betreffen sollte. Daher sollten wir das Feature in eines der zentralen Plugins übernehmen.
Welche Flaggen brauchen wir? DE, EN-UK, EN-US, CN, RU,... ?

**Comment by FlorianFiller** [comment]
Also wir (Phil) bräuchten vor allem DE / EN-UK / EN-US

**Comment by xwolfde** [comment]
Nach RRZE-Elements verschoben
