### ISSUE TITLE
Responsive Design bei unter 768px: Lange Titel

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#199]
Wenn ein langer Titel oder ein langer SUbtitel zu einem Webauftritt vorhanden ist, kommt es zu Darstellungsproblemen im responsiven Deisgn unter 768px.
![str1 rw fau de-smartphone](https://cloud.githubusercontent.com/assets/1070669/21391865/b84a8fd0-c78d-11e6-8e13-79e7ef27a305.png)

**Comment by xwolfde** [comment]
Der Bereich zwischen der grau unterlegten Suchmaske und dem roten Fläche sollte nahtlos sein. Das ist ein Fehler, der auf manchen Browsern auftritt, dem wir auch noch nachgehen müssen.

**Comment by AstridSemm** [comment]
Und nicht nur dort.
![bildschirmfoto 2016-12-21 um 14 58 13](https://cloud.githubusercontent.com/assets/11296947/21391934/f69f9d66-c78d-11e6-8848-867b8be03aa0.png)

**Comment by xwolfde** [comment]
Wieso tut jemand den Titel in Untertitel duplizieren??!!

**Comment by xwolfde** [comment]
Ref #246

**Comment by xwolfde** [comment]
Ref #249

**Comment by xwolfde** [comment]
AB der nächsten Version behoben.
