### ISSUE TITLE
Werbung ID wird angezeigt

### ISSUE THREAD

**Issue by uliried** [RRZE-Webteam/FAU-Einrichtungen#2]
Beim Anzeigen der Werbun in der Sidebar der Startseite wird die ID der Werbung mit eingeblendet
![aditionid](https://cloud.githubusercontent.com/assets/8255127/10792189/ec968d2c-7d8b-11e5-9bc8-1687fc5a9080.png)

**Comment by xwolfde** [comment]
Wie sieht der EIntrag aus im Backend bei der Werbung aus? ggf. gesondert via  Mail senden

**Comment by uliried** [comment]
Screenshot per E-Mail an webmaster@rrze geschickt

**Comment by xwolfde** [comment]
debugmeldung :/   In der nächsten version raus
