### ISSUE TITLE
Übersetzung nachreichen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#20]
insbesondere für Suche

**Comment by xwolfde** [comment]
Spanisch wäre auch schick.
Ausserdem sind wir derzeit nur auf en-US.
Es gibt aber wohl Websites, die auf en-GB gestellt sind von Kunden. Diese haben dann keine Übersetzung. Was besonders auffällt, wenn auf der Seite die ansonsten englischen Text hat oben im Sucheingabefeld "Suchen nach.." 
:( 
ggf. sollten wir der EInfachheit halber erstmal en-US fertigstellen und dann auf en-GB kopieren.

Zur Übersetzung eigenet sich das Plugin Loco Translate.


ggf. Job delegieren an @AstridSemm

**Comment by rvdforst** [comment]
Sehr vorsichtig mit dem Loco-Translate-Plugin, weil es sehr viel Arbeitsspeicher benötigt, wenn es viele Plugins und Themen dabei sind. Also nicht geeignet für den Produktivserver.

**Comment by xwolfde** [comment]
Astrid kann auch auf mein testserver übersetzen. ggf. ist das auch besser, dann kann ich es ins Git einchecken und keiner muss was woanders vorbereiten.

**Comment by xwolfde** [comment]
fixed ;)
