### ISSUE TITLE
Beitragskategorien auf Unterseiten so darstellen wie auf der Startseite

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Einrichtungen#200]
Es gibt neben Fakultäten und Lehrstühlen ja auch Departments, die anbieten, dass beispielsweise Arbeitsgruppen sich dort darstellen. Dafür wäre es sehr praktisch, wenn auf Unterseiten (zB der Inhaltsseite mit Navi) die Beiträge jeweils einer bestimmten Kategorie so darstellen könnte, wie es auf der Startseite gezeigt wird, so dass die Seite einen kurzen Einführungstext hat und darunter die aktuellen Artikel der Arbeitsgruppen- oder Lehrstuhlkategorie. So in etwa:
![bildschirmfoto 2016-12-21 um 16 36 27](https://cloud.githubusercontent.com/assets/11296947/21395380/8dbb752c-c79c-11e6-93ff-9b9db84deb6f.png)

**Comment by wrcg** [comment]
Für diese Art der Darstellung hätten wir auch einen konkreten Anwendungsfall. Wir behelfen uns zur Zeit damit, auf die Kategorieseite (https://www.fau.de/category/interviews) zu verlinken. Die linke Navigation und das "Nicht-Anzeigen" der Blognavigation wäre in diesem Fall aber deutlich schöner :-)

**Comment by xwolfde** [comment]
Ref #233

**Comment by xwolfde** [comment]
Ab nächster Version verfügbar.
Testcases bald hier:
* https://www.beta.wordpress.rrze.fau.de/theme-shortcodes/shortcode-articlelist/
* https://www.beta.wordpress.rrze.fau.de/theme-shortcodes/shortcode-blogroll/
