### ISSUE TITLE
Einer Kategorie ein Bild zuweisen

### ISSUE THREAD

**Issue by anbininf12** [RRZE-Webteam/FAU-Einrichtungen#203]
Ich würde gerne einer Kategorie (z.B. Allgemein) ein Bild zuweisen können.

**Comment by xwolfde** [comment]
Kriegen wir über das Theme nicht sinnvoll hin.
Stattdessen ab der nächsten Version  eine Seite für die Kategorie anlegen mit einem Artikelbild. In der Seite dann via Shortcode [blogroll cat="Kategorie" num="10"]  o.ä. Einträge machen.
