### ISSUE TITLE
Top-Events: Bug durch fehlerhaften Default durch JavaScript-Bibliothek

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#205]
Wenn ein Artikel zum ersten mal gespeichert wird, passiert nichts, alles ist in Ordnung.
Wenn ein Artikel danach nochmal bearbeitet wird, wird er als Top-Event deklariert mit einem Datum des aktuellen Tages oder mit dem 1.1.1970 (abh. vom Browser).

Bei den Top-Events wird zur Datumseingabe eine jQuery-Bib verwendet.
Dort muss es allerdings (mglw. durch den Update auf 4.7.1) zu einer Änderung gekommen sein bei dem Handling von Default-Daten.
Offenbar wird eine leere EIngabe in dem Datumsfeld nun durch den Default der aus dem JavaScript kommt überschrieben. Wird dann der Beitrag neu gespeichert, wird dieser Wert mit übernommen.

Zwei Lösungen bieten sich an:
1. Nur noch auf das An/Aus achten beim, Top-Event und nicht mehr auf das Datum.
   Nachteil: Abwärtscompatibilität nicht mehr vorhanden!
 
2. JavaScript-Anweisung fixen.
   Nachteil: Bäh, JavaScript.

@cassandre kannst du dir das bitte anschauen? Da da alle Themes betrifft und Änderung von Artikeln häufig passiert, sollte das möglichst schnell behoben werden. Ich tendiere zu Variante 1 bei der Lösung.

**Comment by xwolfde** [comment]
Ein Workaround für Betroffene: In den Artikel zum edieren rein, Top-Event-Box öffnen, Datum löschen. Speichern.

**Comment by xwolfde** [comment]
Bugfix ist im Code. Themes werden in Kürze aktualisiert. Es wird nur noch darauf geachtet, dass der Top-Event auch tatsächlich an ist.

**Comment by lagerlit** [comment]
Kurzes Feedback (unser Top-Termin nach der heute Aktualisierung offline): Nur mit An/Aus-Schalter lässt sich ein Top-Termin jetzt nicht mehr veröffentlichen – es MUSS ein Datum eingegeben werden. Dann taucht das Datum aber auch auf der Startseite auf. Fakultative Datumseingabe würde ich bevorzugen.

Hintergrund: Wir bewerben Termine nicht zwangsläufig chronologisch, sondern gehen nach inhaltlicher Relevanz. Wenn ich das auführlicher darlegen soll, bitte Bescheid geben.

**Comment by lagerlit** [comment]
Hat meine Kollegin gerade durch zufall entdeckt @xwolfde: 
![datum-falsch](https://cloud.githubusercontent.com/assets/9449835/22102443/c6a184ce-de37-11e6-8ada-28717eba704c.JPG)
![datum-richtig](https://cloud.githubusercontent.com/assets/9449835/22102454/ce4c6acc-de37-11e6-8400-b3c9ba7a4c40.JPG)
![datum-richtig_backendjpg](https://cloud.githubusercontent.com/assets/9449835/22102457/d0f39656-de37-11e6-9f83-73bc577def81.JPG)
![top-event-datum_backend](https://cloud.githubusercontent.com/assets/9449835/22102460/d25a6e5c-de37-11e6-8b34-5ee82e0c8197.JPG)
Meldung: https://www.fau.de/2017/01/news/wissenschaft/angriff-auf-den-tumor/ 
Gibt es hier einen Zusammenhang zum voreingestellten-Top-Termin-Datum 01-01-1970?

**Comment by xwolfde** [comment]
Bugfix im Repo, wird in Kürze ausgespielt.
