### ISSUE TITLE
Glossar und Kontaktinformationen-Box

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/FAU-Einrichtungen#207]
Beim Bearbeiten eines Glossar-Eintrags fehlt die Box mit "Kontaktinformationen". Könnte diese bitte dort eingefügt werden?

**Comment by AstridSemm** [comment]
Meinst du die Auswahlbox, in der man sich die Kontakt-IDs fürs Person-Plugin holen kann? Wenn ja: Die ist im Glossar nicht vorhanden, denn das Glossar dient eigentlich tatsächlich der Sammlung kurzer Begriffserklärungen. Ich weiß, dass es auch anders genutzt wird - das ändert aber nichts daran, dass man es damit falsch nutzt. Sagst du mir, was du vorhast, vielleicht finden wir ja zusammen einen anderen Weg?

**Comment by AstridSemm** [comment]
Nach kurzem Telefonat ergänze ich die Beschreibung des Wunsches um den konkreten Anwendungsfall:
Es soll ein Schlagwortverzeichnis angelegt werden mit den wichtigsten Begriffen für Erstsemester, die sich noch nicht so gut auskennen. Hier soll beispielsweise statt eines allgemeinen Links auf die Studienberatung konkret auf die zuständige Person verlinkt werden. Dazu wäre es natürlich sinnig, die Kontaktinformationen auch im Glossar zur Verfügung zu haben (zur Verdeutlichung, was gemeint ist, gibt es hier einen screenshot:)
![bildschirmfoto 2017-01-17 um 15 04 48](https://cloud.githubusercontent.com/assets/11296947/22024698/1af60900-dccb-11e6-83eb-c1d4117d8e8f.png)
Nachdem momentan nicht viel Zeit ist, die Idee an sich aber meiner Ansicht nach sinnvoll, gibt es jetzt das Label "enhancement".

**Comment by xwolfde** [comment]
Ref #165 

Und welches Glossar gewinnt? Welches ist das einzig richtige?
"Es kann nur einen geben!"

Wäre es nicht sinnvoller, wenn man ein Plugin bereitstellt, das auf ein zentral gepflegtes "offizielles" Glossar zugreift?

**Comment by xwolfde** [comment]
Mit Blick auf den Glossar der Webredaktion, den Glossar des Sprachendienstes, den IT-Glossar des RRZE und einiger weiterer, denke ich wir sollten uns da wirklich eher eine allgemeine Lösung überlegen. Es macht doch keinen Sinn, wenn an verschiedenen Stellen Glossare gepflegt werden, bei denen wahrscheinlich ein großer Prozentsatz gleiche Begriffe bescheiben.
Gleichzeitig ist klar, dass da niemand allein "führen" kann. Die Webredaktion kann Aussagen zu offiziell von Pressestelle verwendeter Begriffe machen, nicht aber zu Fachbegriffen, welche in den Einrichtungen verwendet werden. Da müssen die Einrichtungen vorgeben. 

(Die Diskussion wird hierbei auch am RRZE in Bezug auf die Nutzungsrichtlinien der Uni schon länger geführt, wenn es um die korrekte Wahl der Begrifflichkeiten Kunde, User, Nutzer, Kontaktperson etc. geht. )

Gerade sichtbar ist es auch in der Medienberichterstattung zur TF. Diese hat die offizielle Abkürzung TF.
Trotzdem hat sich TechFak eingebürgert. So sehr, dass auch die NN das so verwendet.


Lange Rede, kurzer Sinn: 
Die jetzige Lösung ist nur eine Basislösung. Die möchte ich ungern ausbauen. Vorallem nicht, wo sie noch im Theme steckt.
Sinnvoller halte ich es, wenn eine umfassende Lösung gebaut wird, bei der Glossar-Daten aus einer zentralen Datenbank abgerufen werden können -aber nicht müssen. Ähnlich wie bei dem Personen-Plugin mit den User-Daten muss es möglich sein, die Daten durch eigenen Definitonen zu überschreiben.
Weiterhin bräuchte es ein Serverübergreifendes Rechtekonzept. Es müsste dabei festgelegt wer, welche Bereiche der Glossare verantwortlich pflegt. Man könnte sich dann quasi selbst auswählen, ob man Basis-Glossareinträge von der Webredaktion, der Natfak, des RRZE übernimmt. 
Überlegen könnte man höchstens bei einigen definierten Begriffen, ob diese überschrieben werden dürften.
Beispielsweise die fest stehenden Bezeichnungen/Abkürzungen für Einrichtungen.

**Comment by wrkb** [comment]
"Können, aber nicht müssen" ist auf jeden Fall ein guter Ansatz. Auch die Grundidee klingt sinnvoll. Ich halte sie aber nicht für umsetzbar und aus unserer Erfahrung nicht für dringend (nicht nur, weil wir noch ganz andere Probleme/defekte Funktionen wie den Linkchecker haben).

- Es gehört zu den Alltagserfahrungen und ist auch nachvollziehbar, dass verschiedene Einrichtungen Begriffe aus verschiedenen Blickwinkeln erklären möchten oder müssen (versch. Zielgruppen). Unser Glossar hat schon Dopplungen im Bereich der ZUV, weil z.B. der Career Service teils umfangreichere Einträge benötigt als wir für die knappe Variante von FAU A-Z. Nachvollziehbar und okay. Alles andere wird geteilt (Zuordnung via Kategorien). Das Gleiche gilt für das Graduiertenzentrum.
- Ein zentraler Glossar klingt gut, aber wie da jemals Einigkeit über Inhalt oder auch nur die Deutungshoheit entstehen soll, ist mir schleierhaft. Das scheitert ja schon anderswo (Beispiele gehören nicht auf diesen Kanal) und selbst bereits existierende zentrale Angebote/Datenbanken haben aus mehreren, hier ebenfalls nicht nennbaren Gründen Schwierigkeiten mit dem Anspruch als alleinige Quelle.
- Am ehesten Erfolgschance sehe ich bei der Verwendung zentral festgelegter Einrichtungsbegriffe, die ja bereits hier und da hinterlegt, gepflegt und auch übersetzt hinterlegt sind. Aber die müssten über eine Schnittstelle ins CMS eingebunden werden, richtig?
- Der größte Vorteil deiner Idee wäre aus meiner Sicht, dass bereits vorhandene Inhalte einfach genutzt werden können, aber die Erfahrung aus anderen Bereich zeigt doch auch, dass das a) kaum gemacht wird und b) allein die Möglichkeit meist nicht annähernd alle Adressaten erreicht.

**Comment by xwolfde** [comment]
@bmehler Ggf berücksichtigen bei den neuen Plugin. (Der Wunsch oben mit der optionalen Verknüpfung auf eine Person, sofern das Plugin fau-person aktiviert ist). Ggf. diesen Issue hier schließen und in das anderen Projekt schieben

**Comment by xwolfde** [comment]
Verschoben in https://github.com/RRZE-Webteam/rrze-faq/issues/3
