### ISSUE TITLE
Bilder ohne Rahmen

### ISSUE THREAD

**Issue by FlorianFiller** [RRZE-Webteam/FAU-Einrichtungen#209]
Für manche Bilder wäre - neben den bereits bestehenden Hervorhebungen "thickborder" und "shadow" - noch eine CSS-Variante ganz ohne Rand wünschenswert. Bei (runden) Logos, Stempeln etc. mit Weißraum/Transparenz stört auch der schmale graue Schattenwurf.

**Comment by xwolfde** [comment]
Wird in der nächsten release enthalten sein.

In der Bildklasse zu ergänzen: "noshadow".
Ab Montag Demoseite hier: https://www.beta.wordpress.rrze.fau.de/bilder/bilder-mit-zusatzklassen/
