### ISSUE TITLE
Metanavi oben in den englischsprachigen Themes

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Einrichtungen#211]
![bildschirmfoto 2017-02-10 um 09 29 59](https://cloud.githubusercontent.com/assets/11296947/22819808/179e8e38-ef74-11e6-891d-2b5f2b9ddb1a.png)
Ich bin gerade mittelgradig unbegeistert, denn in den englischsprachigen Fakultätsthemes (also denen mit Heroslider) scheint der Link auf die FAU in der Metanavi durch den Text "Towards FAU" ersetzt worden zu sein. Warum wurde das ersetzt und vor allem: Wer hat den Text verbrochen?

Wenn es so stehenbleiben soll, bitte "To FAU" nehmen oder - schön IT-mäßig - "Go to FAU".

**Comment by xwolfde** [comment]
In der nächsten Release
