### ISSUE TITLE
interne Links werden als "extern" gekennzeichnet

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Einrichtungen#213]
wenn ein interner Link ohne "www" im Quelltext eingegeben ist, erscheint er als extern, d.h. mit dem Symbol.

<img width="642" alt="2017-02-13 14_45_53-externer-link" src="https://cloud.githubusercontent.com/assets/9526974/22885781/2ec6d7e4-f1fb-11e6-8433-a1e3b2c520d0.png">

**Comment by xwolfde** [comment]
Ja, ist so, kann man nicht ändern, denn es ist auch korrekt. "www,.fau.de" ist technisch nicht identisch zu "fau.de" auch wenn in diesem Fall fau.de auf www.fau.de umleitet.

**Comment by wrkb** [comment]
Heißt das, in den Einstellungen werden nicht automatisch Wildcards vergeben? Was sollen wir dann hinterlegen als Aliase - http://fau.de und http://fau.eu?

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/22931289/5f766110-f2c4-11e6-8c6b-ce888a204e0a.JPG)

**Comment by xwolfde** [comment]
Wildcards gehen an der Stelle nicht, denn das wäre schlichtweg falsch. Ihr müsst die URL genau so schrieben, wie sie ist. Also eben in diesem Fall ohne Punkt, wenn ihr es so wollt.
ABER: Wenn ihr solche Links habt, habt ihr ein anderes Problem: Diese URLs kommen nur zustande, wenn sie jemand manuell eingibt. (WordPress wird nämlich immer die richtige URL angeben: Mit www.) 
Ihr werdet ein Problem bekommen, falls die verlinkte Seite, die sich auf dem Webauftritt befindet, verschoben wird an eine andere Stelle. Wenn ihr nämlich die URL manuell eingegeben habt, statt die Linksuche von WordPress zu nutzen, wird der Link nicht automatisch beim verschieben korrigiert.

**Comment by wrcg** [comment]
ok, danke, ich verstehe. Ich denke, dass die "falschen" Links, bei denen es mir aufgefallen ist, eine Ausnahme waren. Ich hatte sie am Montag auch gleich korrigiert.
