### ISSUE TITLE
Meta-Nav - Flexibel änderbar oder feste Vorgaben?

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#216]
Die derzeitige Meta-Nav besteht bei der Default-Vorgabe aus den Einträgen 
* Mein Campus 
* UnivIS 
* Lageplan 

Die Meta-Nav ist über die Menü-Funktionalität änderbar, so dass man die vorhandenen Einträge entfernen, ergänzen oder ändern kann.

Es gibt verschiedene Anregungen dazu, die Meta-Nav zu ändern:

1. So lassen wie sie ist (flexibel, änderbar, nur die bisherige minimale Vorschlagsliste)
2. Sie festlegen und nicht änderbar zu machen
3. Die genannten drei oder andere Punkte fest zu setzen ohne Änderungsmöglichkeit, aber die Möglichkeit zu lassen, bis zu zwei weitere Punkte danach zu ergänzen 

Wir haben bisher die flexible Variante 1 umgesetzt, damit es keine zeitkostenden Diskussionen darüber gibt, welche Portale der FAU so wichtig sind, dass sie in der Meta-Nav erscheinen müssen; inkl. Diskussion der Reihenfolge. Bei einer Festlegung der Punkte wird nämlich genau dies die Folge sein: Wer bestimmt, welche Einträge da sind.
Hält man es  flexibel, geht man als Theme-Anbieter die Diskussion aus dem Weg und überlässt die Entscheidung und Diskussion dann zu den Website-Betreibern. 

Der Nachteil ist allerdings, dass damit keine Einheitlichkeit "erzwungen" wird. Die Meta-Nav kann überall anders sein. Auch wenn die Praxis zeigt, dass nicht viele da was ändern.

Wie sind hierzu die Meinungen? Sollen wir an der bisherigen Methodik festhalten oder sie in einen der anderen Möglichkeiten ändern?

**Comment by wrkb** [comment]
Ich bin ja spätestens nach den Relaunch-Erfahrungen der Meinung, dass mehr starre Vorgaben möglich und zumutbar und vor allem sinnvoll sind für die Nutzererfahrung. Die Leute springen mindestens von fau.de und fau.eu auf Seiten anderer Einrichtungen weiter und bei der Anzahl bereits umgezogener Webauftritte lohnt sich eine "Corporate Usability" schon jetzt. Man kann dann auf Anfragen/Einwände eingehen (ins passende Gremium bringen ;) )

Übrigens ist bei UnivIS kein direkter englischer Link verfügbar (nur so eine Session-URL o.ä.), zur Nutzung in den englischen Themes. Ich habe vorhin Frau T. angeschrieben, aber vielleicht hat hier jemand den passenden Link zur Hand?

**Comment by xwolfde** [comment]
Wir lassen es jetzt flexibel, werden aber wohl die zweite Metanav bekommen, die auf die Orgstruktur basiert und die dann automatisch und verbindlich ist
