### ISSUE TITLE
Abstand h4 zu Kontakt innerhalb eines Akkordeons

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Einrichtungen#217]
...ist zu groß. Eine h3 sieht besser aus, aber ist dort eigentlich falsch.

Ich weiß nicht, woran das liegt, der Kontakt hat einen Titel und die Angaben in den korrekten Feldern (manueller Kontakt).

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/23457127/dc269b0e-fe76-11e6-8b76-3ff2dc7de874.JPG)

**Comment by xwolfde** [comment]
Gibst du mir eine genaue URL, oder noch besser, könntest du den verwendeten Seitencode (gesamt) so wie er jetzt ist als Beispielseite auf test4 ablegen?

**Comment by wrkb** [comment]
Stimmt, den Entwurf könntest du ja einsehen. Ich schick ihn dir :)

**Comment by xwolfde** [comment]
Ref #226

**Comment by xwolfde** [comment]
Ref #261

**Comment by xwolfde** [comment]
in der nächsten release gefixt
