### ISSUE TITLE
Auf Kontaktseiten funktioniert die Vorschau der Änderungen nicht

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Einrichtungen#219]
Auf den Kontaktseiten kann man zwar Änderungen vornehmen, diese werden aber bei Klick auf "Vorschau der Änderungen" nicht angezeigt. Nachdem ich jetzt nicht weiß, ob das im Theme begründet ist oder im Plugin, schreibe ich es erst einmal hierher. Im Falle von Irrtum bitte umswitchen.
Gesehen und getestet habe ich das hier: https://cs12.cms.rrze.uni-erlangen.de/person/andreas-bininda

**Comment by xwolfde** [comment]
Duplicate: https://github.com/RRZE-Webteam/fau-person/issues/192
