### ISSUE TITLE
404-Fehlermeldung: apple-touch-icon.png 

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Einrichtungen#220]
Bei unseren 404-Fehlern kommt verhäuft die Meldung, dass das apple-touch-icon.png bzw. apple-touch-icon-120x120.png und  apple-touch-icon-120x120-precomposed.png nicht gefunden wird. 
Dieses wird direkt im Rootverzeichnis gesucht.
Wo kann ich dafür Bilder speichern/auswählen?

**Comment by xwolfde** [comment]
Prüfen

**Comment by xwolfde** [comment]
Garnicht, das ist ein Fehler veralteter Browser.
