### ISSUE TITLE
Suche: Kombination aus Buchstabe und Zahl ("G8") führt direkt zum IdM-Login

### ISSUE THREAD

**Issue by lagerlit** [RRZE-Webteam/FAU-Einrichtungen#221]
Suche auf fau.de > Suchbegriff "G8" / "G9" / "H7" / "P4" führt direkt zur IdM-Login-Seite 

Suche auf fau.de > Suchbegriff "G 8" oder "Ge8" bringt dagegen Suchergebnisse (wenn auch keine passenden ;) ) bzw. die Info, dass nichts passendes gefunden wurde.

Wieso funkt im ersten Fall die IdM-Seite dazwischen?
LG, Luisa

**Comment by xwolfde** [comment]
Ich vermute, dass in den Treffern auch Objekte enthalten sind, die gegen Zugriffe geschützt sind und dabei ein SSO-Login erfordern.
Wenn du nämlich über SSO angemeldet bist, kommst du auf die Suchergebnisse.

Mich wundert aber eher, warum es keine Fehlermeldung gibt, dass das Suchwort zu Kurz ist.. Zweich Zeichen sind ja etwas böd.

**Comment by lagerlit** [comment]
Ja das wäre für externe Nutzer sicherlich ein befriedigenderes Ergebnis, eine Fehlermeldung zu bekommen, dass das Suchwort zu kurz ist, also einfach auf dem Login zu landen. Dann weiß man wenigstens, was man zu tun hat ...

**Comment by rvdforst** [comment]
Ein Teil des Problems war das Access Control Plugin (geschützte Dateien / Dokumente). Dieses Problem wurde behoben.

Mit WordPress (standardmäßig) gibt es keine Begrenzung für die Sucheingabe. Und ich glaube es ist gut so.
