### ISSUE TITLE
Medien (Bilder) - Anhangseite geht nicht

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Einrichtungen#222]
Beispiel: 
Der Permalink auf das  Bild (https://www.fau.de/universitaet/das-ist-die-fau/veranstaltungen/schlossgartenfest/attachment/schlossgartenfest-feuerwerk/) führt zu einer Fehlermeldung.
Hier wurden doch auch mal die Bilddaten (IPTC...)angezeigt?!

**Comment by xwolfde** [comment]
Prüfen

**Comment by xwolfde** [comment]
Nach nur 6 Stunden suchen und fluchen hab ich die Ursache gefunden...
Dadurch, dass wir bei der Suche Bilder von den Suchergebnissen ausgeschlossen haben, sind Bilder nun auch nicht mehr als Anhang-Seite auffindbar.

Wenn wir also Attachment-Seiten mit Bildern zulassen wolle -und das wollen wir!- dann müssen Bilder auch über die Suche findbar sein.

**Comment by wrkb** [comment]
dann muss die suche anpassbar sein. wenn bilder via voreinstellung mit darin auftauchen, wird die suche unbrauchbar. der haken solle also nicht per default gesetzt sein.

**Comment by xwolfde** [comment]
In der nächsten Version umgesetzt. Hinweis: Bilder und Dateien können nicht unterschieden werden. Der Haken ist also bei "Medien" per Default aus.
