### ISSUE TITLE
BR-Videos

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Einrichtungen#223]
Gibt es die Möglichkeit, Videos vom BR auch mit in die Liste der möglichen Videos zum Einbetten mit aufzunehmen (neben FAU-Videoportal und Youtube)?
U.a. hätte die Pressestelle öfters die Möglichkeit, Videos zu Pressemeldungen direkt vom BR mit einzubinden; allerdings wird momentan ja der iframe-Tag gelöscht.

Beispiel eines BR-Codes wäre:
<iframe src="http://www.br.de/static/player/embed/index.html?url=/mediathek/video/sendungen/alpha-campus/campus-talks-pfaller-100~meta_xsl-avtransform100_-daa09e70fbea65acdb1929dadbd4fc6cdb955b63.xml&extern=1&shareable=1&postroll=1" width="640px" height="360px" allowfullscreen scrolling="no" frameborder="no"></iframe>

**Comment by xwolfde** [comment]
Das müsste man im embed-Plugin einfügen.

Stattdessen würde ich empfehlen, nicht das Embed von der BR-Mediathek zu nehmen sondern das Videoportal des BR auf YouTube zu nutzen ( https://www.youtube.com/user/BR) und dann vom dem entsprechenden Video schlicht die YouTube-URL zu nehmen - diese wird dann automatisch erkannt und als Video umgesetzt.
Denn YouTube hat Standardschnittstellen, die in allen guten CMS berücksichtigt werden.
Die BR-Website dagegen hat ihre eigene Insellösung, für die man was coden müsste :/
