### ISSUE TITLE
Titel für Bildlink-Bereich

### ISSUE THREAD

**Issue by cassandre** [RRZE-Webteam/FAU-Einrichtungen#225]
Könnte man in der Metabox "Logos (Bildlinks) anzeigen" noch ein Textfeld für den Titel ergänzen?
Ich würde auf der Seite gerne eine Überschrift über den Bildlinks anzeigen, damit der Besucher weiß um was es sich bei den Bildlinks eigentlich handelt (in dem Fall Verbundprojekte).

**Comment by xwolfde** [comment]
Muss geprüft werden, ob Bildlinks noch sinnvoll sind, da WP ab 4.8. nun mit einem eigenen Bild-Widget aufwartete

**Comment by xwolfde** [comment]
Erstmal nicht, da Bildlinks zugunsten der WP Funktion in Zukunft wegfallen sollen
