### ISSUE TITLE
Portalmenus als Shortcodes

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#227]
Damit man Text auch unter dem Portalmenu machen kann, wäre ein Shortcode für Portalmenüs sinnvoll

**Comment by wrkb** [comment]
Zusätzlich oder als Ablöse für das Menü?
Letzteres wäre in meinen Augen problematisch, für Anwender (auch für die meisten erfahrenen) sind Shortcodes ein Graus, eine Menülösung ist immer besser.

**Comment by wrkb** [comment]
Als zusätzliche Option aber sehr wünschenswert (wir haben da schon einen Anwendungsfalls) :)

**Comment by xwolfde** [comment]
Zusätzlich natürlich

**Comment by wrkb** [comment]
Okay, danke :) Ausblenden von Funktionen kann ich schon nachvollziehen (fokussiertes Arbeiten), insbesondere da man als Admin durch IdM keinen zweiten Nutzer mit übersichtlicherem Backend haben kann. Allerdings sind die Templates das geringste Problem in der Hinsicht :)

**Comment by xwolfde** [comment]
Im nächsten Release vorhanden.
https://www.beta.wordpress.rrze.fau.de/theme-shortcodes/shortcode-portalmenu/

**Comment by wrkb** [comment]
Bei mir wird die Spalte mit dem Menü nicht gefüllt. Inhalte sind veröffentlicht, aber der Bereich ist noch ein Entwurf. Woran könnte es liegen? Im Handbuch geht es ja.

<img width="918" alt="unbenannt" src="https://user-images.githubusercontent.com/9445370/37142998-0d143f2e-22ba-11e8-9091-56cf6e0b2622.PNG">

**Comment by wrkb** [comment]
Ah, die Seite muss ein Portalindex sein vom Template her, keine Portalseite. Rücksicht auf die Sidebar, die hier noch nicht gefüllt wurde?

**Comment by xwolfde** [comment]
Ja. Es ist unschön da. Da muss nochmal jemand dran. Aber dazu möchte ich auch erst abwarten, bis ihr der Frontmotion Firefox eine neue Version bekam.

Lange Erläuterung:
Das hängt an der Breite des Inhalts, die ist responsive.  Wenn 4 Kacheln vom Platz nicht passen, wird auf 2 Kacheln umgeschaltet.  Wenn du das andere Template nimmst, geht es mit 4, weil dann rechts kein optionaler Bereich mit für eine SIdebar ist. Hier jedoch schon.
Ich wollte da auch lieber haben, dass er wenn 4 nicht passen, erstmal 3 Kacheln macht, wenn dafür der PLatz da ist, aber leider ging das letztes Jahr nicht (bzw. ich musste es wieder ausbauen): Weil damals CSS-Grids noch nicht bei allen Browser verbreitet genug waren. (Insbes. der Frontmotion konnte es noch nicht). 
Wenn der Frontmotion eine neue Version hat, dann ist die CSS-Grid-Unterstützung besser und wir (btzw. derjenige der das dann codet) können das Problem nachhaltiger lösen.

**Comment by wrkb** [comment]
Danke!
