### ISSUE TITLE
Portal Button bei extern verlinkten Seiten im Hauptmenü

### ISSUE THREAD

**Issue by mkuehnel85** [RRZE-Webteam/FAU-Einrichtungen#228]
Hallo,

aus Gründen der Infrastruktur betreiben wir einen zweiten Webserver, auf dem eine weitere Wordpress-Instanz läuft. Das Hauptmenü zwischen beiden Instanzen ist identisch, jedoch zeigen fast alle Menü-Einträge des zweiten Servers auf die Seiten des ersten Servers. Sprich, die Menü-Einträge sind Custom Links.

Dies funktioniert soweit gut bis auf den Portal Button: Auch wenn das Ziel in der obersten Menüebene als externer Link definiert ist, verlinkt der Button dennoch auf eine interne Seite. Da diese Seite nicht existiert läuft der Link ins Leere. Der Menüpunkt an sich verlinkt aber auf das richtige, externe Ziel. Zur Verdeutlichung:
![image](https://cloud.githubusercontent.com/assets/26654668/24354141/0aee7cc0-12f1-11e7-8950-a84808383986.png)

Aus Zeitgründen haben wir selbst im Code nachgeschaut und das Problem zumindest in unserem Fall (abwärtskompatibel) beheben können (siehe Patch im Anhang).
[patch.txt](https://github.com/RRZE-Webteam/FAU-Einrichtungen/files/872315/patch.txt)

**Comment by wrkb** [comment]
Aber das ist eigentlich doch kein "Problem" des Themes, sondern ein Workaround für ein recht seltsam klingendes Problem. Wieso verteilt man einen Webauftritt denn auf zwei Webservern und setzt Hardlinks in Menüs, die Wordpress automatisch pflegen könnte? Damit werden Inkonsistenzen und Fehlerquellen geschaffen und das will ein gutes Theme ja gerade nicht. Vielleicht besser die Altlasten angehen und beseitigen?

Custom Links in Menüs sind natürlich auch im Hauptmenü erlaubt, aber der Einsatz sollte generell meiner Meinung nach auf Ausnahmen beschränkt bleiben, da sonst die User Experience beeinträchtigt wird (in Menüs erwartet man üblicherweise interne Links). In diesem Fall wird wohl versucht, mit gleichem Design diesen Bruch zu umgehen, aber das kann doch eigentlich nur zu Problemen führen.

Das System/Theme verhält sich also völlig richtig, da es der mit der definierten "Menü-Usability" Portalseiten nur innerhalb eines Webauftritts verlinkt, so lernt es der Nutzer auf allen FAU-Seiten. Externe Links dürfen da also gar nicht stehen. Dass man oben im Hauptmenü für die Kopfeinträge überhaupt Custom Links setzen darf, ist der Flexibiiltät von Wordpress geschuldet, müsste eigentlich im Theme unterbunden werden. Aus all diesen Gründen dürfte also der Patch niemals ins offizielle Einrichtungs-Theme wandern ;)

**Comment by AstridSemm** [comment]
Links auf externe Seiten in der Hauptnavigation sind eigentlich nicht erlaubt; warum das hier geht, weiß ich nicht genau. Ich vermute aber, dass das nach dem Hinweis hier mit dem nächsten Update vorbei ist.
Ansonsten: Was wrkb sagt.

**Comment by xwolfde** [comment]
Links auf externe Seiten sind im Menu nicht erlaubt und wirken auch sehr negativ auf die Benutzerführung. Sowas sollte man tunlichst unterlassen. 
Ein "Bugfix" wird es nicht geben, allenfalls ein Fix, der verhindert, dass jemand im Hauptmenu so ein Unsinn macht.
