### ISSUE TITLE
Kategorieseite mit Inhalt bzw. Statische Seite mit zusätzlichen Kategorien-Listing

### ISSUE THREAD

**Issue by rathsky** [RRZE-Webteam/FAU-Einrichtungen#229]
Mit anderen Worten, gewünscht ist eine Seite à la Portalindex, nur dass statt einem Menü eine Beitragsliste (wie auf der Startseite) zu einer oder mehren Kategorien angezeigt wird.

**Anwendungsfall:** Lehrstuhlseite

&nbsp;&nbsp;&nbsp;&nbsp;Professor braucht bloß Beitrag schreiben,  richtig die Beitragskategorie(n) setzen, fertig.

Aktuelle Plugins die die Funktionalität (zusammen mit Paginierung etc.) via Shortcodes anbieten sind bspw. [Display Posts Shortcode](https://wordpress.org/plugins/display-posts-shortcode/) und [Post Grid, List for WordPress – Content Views](https://wordpress.org/plugins/content-views-query-and-display-post-page/).

NB1: Ohne diese Funktionalität wäre ein prominenter Hinweis gut, dass sonst Beiträge nur für die Startseite bzw. Kategorienseite verwendbar sind – da werden sonst sehr viele drüber stolpern, und u. U. – wie ich – wenn sie bereits glauben, eigentlich mit der Inhaltsstruktur bereits fertig zu sein.

NB2: Eigentlich sollte wohl ab WordPress 4.4 es zumindest möglich sein, durch schlichtes Kopieren des Permalinks einen bestimmten Post auf einer Seite manuell einbinden zu lassen, irgendwie erzeugt das bei mir aber rein gar nichts, außer eben den Link als Text. Oder gibt's dafür andere Shortcodes?

NB3: Die Bezeichner "Portalmenü" und "Portalindex" sind eher undeutlich, besser wäre meiner Meinung nach etwa "Portal" und "Portal (Balken)".

**Comment by wrkb** [comment]
Frage aus Interesse: Haben die Beiträge denn auch Newscharakter oder sollen Sie als einfachere Art der Webseitenbefüllung (für den Prof) genutzt werden? Letzteres würde spontan diverse Fragen/Einwände erzeugen...

**Comment by rathsky** [comment]
Beides. Die Beiträge sollen sowohl auf der Startseite als auch auf der Lehrstuhlseite angezeigt werden. Quasi: Fürs eine was die Einrichtung gerade insgesamt tut, fürs andere was davon dieser Lehrstuhl speziell.

**Comment by wrkb** [comment]
Okay, das klingt nach nur Newscharakter. (Mit dem einfacherer Befüllung meinte ich, dass die Beiträge quasi für statische Seiteninhalte ohne Blogcharakter hergenommen werden, das scheint hier ja nicht gewollt zu sein.)

**Comment by AstridSemm** [comment]
Mit dem RSS-Plugin geht das: https://www.wordpress.rrze.fau.de/plugins/rrze-rss-plugin/

Allerdings sieht es auf der Seite, auf der der Feed eingebunden wird, ein wenig anders aus als auf der Startseite. Wenn es exakt so gewünscht ist, müssen wir mal mit der Entwicklung reden. :o)

**Comment by wrkb** [comment]
Mein letzter Stand war, dass die Bilder für eingebundene Feeds bereits in Arbeit sind, wenn es auch noch etwas dauern kann.

**Comment by rathsky** [comment]
Die Ausgabe via RSS-Plugin wäre tatsächlich eine Lösung (abgesehen davon dass sie aus technischer Hinsicht eher sehr "von hinten durch die Brust ins Auge" ist).

Blöd nur dass momentan nur der gesamte Beitragsinhalt ausgegeben wird, und nicht der Anleser. Auf Gitlab [steht im Ticket](https://gitlab.rrze.fau.de/rrze-webteam/rrze-rss/issues/4#note_756) jedenfalls seit drei Monaten "in der Entwicklungsphase", ebenso wie in dem fürs Bild.

Interessanterweise scheint WordPress den Wert der Option "Zeige im Newsfeed" (Einstellungen → Lesen) zu ignorieren. Auch bei "Kurzfassung" wird im Feed der gesamte Artikel verwurstet, nicht wie zu erwarten der Anleser.

**Comment by AstridSemm** [comment]
Je weniger Personal, desto länger die Entwicklungsphasen. Hart, aber wahr.

Das Theme verhindert einiges, was eben aus Sicht des Corporate Design nicht gewünscht ist. Vielleeicht kann der xwolf noch etwas dazu sagen.

**Comment by xwolfde** [comment]
Hatten wir schon auf der ToDo, allerdings verklausuliert. Hab mal ein Issue gemacht, der das zusammenbringt: #233

**Comment by rathsky** [comment]
Nach der Umstellung unserer Seite auf die reguläre URL ist das RSS-Plugin irgendwie kaputt gegangen.

Die URL des Feeds habe ich natürlich angepasst, er existiert auch nach wie vor.

Sowohl mit der vorher funktionierenden Anfrage…
> [rss url='https://www.japanologie.phil.fau.de/category/lehrstuhl-i/feed/' show_description=1 show_date=0 teaser=1 items=5 max_description_words=99]

… als auch der simpelsten ohne Parameter gibt es nun entweder gar nichts aus oder meldet…

> RSS-Fehler: WP HTTP Error: cURL error 28: Operation timed out after 0 milliseconds with 0 out of 0 bytes received

**Comment by ec89yler** [comment]
Ich bekomme die gleiche Fehlermeldung bei zwei Instanzen für den Feed [https://www.institut-wipaed.rw.fau.de/feed/](url)

Der Fehler wird ebenfalls bereits bei einer Einbindung der URL ohne weitere Parameter geworfen.

**Comment by AstridSemm** [comment]
Bei mir funktionierte es gesten noch, heute dann nicht mehr. Habe das RSS-Problem weitergegeben, Entwickler arbeitet an der Lösung. Bitte etwas Geduld.

**Comment by xwolfde** [comment]
In der nächsten Version werden die neuen SHortcodes [blogroll] und [articlelist] zur Verfügung gestellt, welche das gewünschte leisten.
