### ISSUE TITLE
Kontakte bspw. als Menüeintrag für "Inhaltsseite mit Navi"?

### ISSUE THREAD

**Issue by rathsky** [RRZE-Webteam/FAU-Einrichtungen#230]
Ist es möglich, Kontaktseiten irgendwie als reguläre Seiten verwalten zu können (quasi dass WordPress die Einträge zusätzlich als Pseudo-Seiten transparent listet, die man wie reguläre Seiten genauer einordnen kann)?

**Hintergrund:** Einerseits wird die Menüstruktur für den Seitentyp "Inhaltsseite mit Navi" ja aus der Seitenhierarchie abgeleitet wird, damit kann man Kontakte nicht als Menüeinträge setzen. Andererseits sorgt ein Link auf den Kontakt (also *.de/person/XXX) dafür, dass man das gerade eigentlich geöffnete Menü verlässt.

Auf der Beispielseite ist dies durch extra Seiten für jeden Kontakt bzw. Personaltyp umgangen – eher umständlich, gerade wenn Lehrstuhle (wie unsere) tatsächlich sehr klein sind. Es ist direkter und mMn auch naheliegender, Inhalt zur Person direkt im generischen Feld (gemeint ist das ganz oben) im Kontakteintrag zu führen.

**Comment by rathsky** [comment]
Ah, ich sehe dass es sich mittels einer neuen ImN-Seite, die bloß [kontakt id="###" format="page"] enthält, lösen lässt.

Minimal umständlich, aber andererseits kann man damit bspw. den Kontakteintrag ohne Titel führen.

Bei der *.de/person/XXX-Seite wird der Name nämlich doppelt angezeigt, einmal im Titel bloß der Name des Kontakteintrags, einmal im eigentlichen Eintrag als korrekt generierter Name.

**Comment by wrkb** [comment]
Was ist mit "genauer einordnen" gemeint? Kontakt in die Navigation einzubinden ist aus gutem Grund nicht möglich. Sie sind keine echten Webseiten und dürfen daher nicht wie Webseiten in die Navigationsstruktur aufgenommen werden. Sonst funktioniert die Navigation nicht richtig. Der Link auf einen Kontakt führt in der Tat in eine Sackgasse, aber zumindest aus dem Inhalt einer Seite heraus. Vielleicht lässt sich das auch eleganter lösen als über den Zurück-Button des Browsers.

Hilft Ihnen vielleicht eine Seite und der Shortcode aller gewünschten Kontakte als Liste (einer Kategorie z.B.)?

Die Detailseite eines Kontakts ist- wenn ich mich nicht jetzt nicht irre - in etwa vergleichbar mit der Anhangsseite eines Bildes/eines Mediums. Die Inhalte werden automatisch aus verschiedenen Attributen eines Kontakts zusammengefügt.

**Comment by AstridSemm** [comment]
Ich empfehle immer gern, die Kontakte mit "format="page"" in Accordien anzubieten, dann braucht man nicht tausende von Einzelseiten zu machen.
In der Textbox der Kontaktseite kann man übrigens per shortcode Publikationslisten aus CRIS einbinden und/oder Lebensläufe präsentieren. Nur mal so... ;o)

**Comment by wrkb** [comment]
@AstridSemm @endv02 Kann man die Kontakte einfach anhand einer Kategorie jetzt schon als Liste ausgeben und als Format "page" angeben? Das würde für alle eine Lösung sein, die mit der alphabetischen Sortierung klarkommen. Mit feinen Unterkategorien kann man ja schön Bereiche abbilden.

Ansonsten könnte man es doch wie bei einer Bildergalerie machen, die die Bild-IDs nacheinander aufzählt im Shortcode. Dazu das Format "page". Das geht ja derzeit nicht, richtig?

**Comment by AstridSemm** [comment]
Äh, du möchtest eine Liste, in der alle Kontakte (eventuell nur die einer Kategorie) mit dem gesamten Text ausgegeben werden, der in den Kontaktseiten steht? Das ist meiner Ansicht nach nicht praktikabel, denn der Besucher würde sich an vielen Stellen zu Tode scrollen. In Accordien stecken ist da 1000x besser.

**Comment by wrkb** [comment]
Richtig.
Und richtig.

Passt nur für Fälle, in denen die Anhangsseite knapp genug ist. So habe ich aber @rathsky verstanden (vielleicht auch falsch verstanden), der/die ja auch ohne Akkordeons arbeitet bislang.

Akkordeons sind für laaaaange Liste natürlich besser, aber halt wieder umständlicher zu bedienen, leider.

**Comment by rathsky** [comment]
Akkordeons hab ich für die Kontakte sogar, nur nicht für diese selber, sondern Dinge wie Werdegang, Mitgliedschaften und Forschungsschwerpunkte. Das stattdessen als zweite Akkordeon-Ebene in eine einzelne Kontaktseite einzubauen presst den Inhalt arg ein, und der Webseitenbereich selbst wirkt dann ziemlich mager.

Ich hab das Ganze nun wie im zweiten Kommentar gelöst, sieht gut aus. So oft ändert sich bei den Mitgliedern auch nichts dass es arg umständlich wird.

Falls Ihr es nicht weiter besprechen wollt, könnt ihr das Ticket gern schließen. Danke für den Support.

Für das mit Kontakten einer Kategorie habe ich [hier](https://github.com/RRZE-Webteam/rrze-univis/issues/32) ein anderes Ticket aufgemacht.

**Comment by xwolfde** [comment]
Diese Funktion wird in Kürze automatisierbar bereitgestellt.
Sprich: Über ein Sync aus UnivIS wird das ganze Org aus UnivIS eingelesen und sowohl der Index als auch alle Einzelseiten automatisch erstellt. In den Seiten befindet sich dann jeweils ein Shortcode mit format="page".
Ausserdem wird das Menu automatisch gebaut.

@endv02 Gibt es kein Issue bei FAU_Person dazu den ich verlinken kann? Oder ist das Bei Univis?
