### ISSUE TITLE
Rahmen um Kontaktformular

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Einrichtungen#231]
Der Rahmen um das Kontaktformular scheint im Moment eine feste (sehr kleine) Größe zu haben. Das ist ungut, weil die Formulare normalerweise länger sind.
Zu bewundern ist das beispielsweise hier: https://wop.cms.rrze.uni-erlangen.de/contact/ (Browser Firefox 52.0.1 (64-Bit) auf Mac).

**Comment by xwolfde** [comment]
Im Dev gelöst

**Comment by xwolfde** [comment]
fixed
