### ISSUE TITLE
Portalbilder: title-Attribut fehlt

### ISSUE THREAD

**Issue by rathsky** [RRZE-Webteam/FAU-Einrichtungen#232]
Bei den Beitragsbildern, die als Portalbilder angezeigt werden, wird kein title-Attribut (oder ggf. ein Link) generiert.

Ist bei vielen [Creative Commons](https://search.creativecommons.org) kritisch, da die meisten einen Quellenverweis verlangen.

**Comment by wrkb** [comment]
Creative-Commons-Bilder sind auch aus weiteren Gründen ein Risiko, obwohl wir sie gern nutzen würden: In der Bildunterschrift ist kein html-Link möglich ohne Wysiwyg-Editor (der ist m.E. deaktiviert dort) und damit verletzt man die Lizenz bei allen Bildern.

Für Portalbilder und ähnliche Zwecke, bei denen keine Angabe sichtbar beim Bild möglich ist, nutzen wir keine CC-Bilder und nur Bilder, die für solche Zwecke eine Verwendung ohne Autorenangabe erlauben.

**Comment by rathsky** [comment]
title-Attribut müsste aber möglich sein. Beim regulären Beitragsbild wird es ja richtig generiert.

**Comment by xwolfde** [comment]
* Title-Attribute sind an der Stelle semantisch falsch und wirken auch negativ auf Screenreader-Nutzer. Daher ist dort kein title und wird auch keines kommen.
* Der Platz für Lizenzinfos ist bei den Portalbildern nicht vorhanden. Zudem handelt es sich nicht um das Vollbild, welches in der Seite sichtbar ist.

**Comment by rathsky** [comment]
Hm. Aber gut, ich konnte für meine Inhalte recht schnell komplett freie Alternativen finden.

Kann die Meta-Suchmaschine von CC, die ich oben verlinkt habe, echt empfehlen – wenn man da wiederum über Pixabay sucht, findet man sehr viele solche Bilder.
