### ISSUE TITLE
Shortcode für Darstellung der Blogroll in Seiten

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#233]
Die Blogroll der Startseite soll via Shortcode mit geeigneten Parametern (Kategorie, Tags, Anzahl) in beliebigen Seiten darstellbar sein.

**Comment by AstridSemm** [comment]
Sollte bitte auch für andere Kategorien als die auf der Startseite gehen.

**Comment by xwolfde** [comment]
In der nächsten Version enthalten.
Testcases dann hier:
*  https://www.beta.wordpress.rrze.fau.de/theme-shortcodes/shortcode-blogroll/
* https://www.beta.wordpress.rrze.fau.de/theme-shortcodes/shortcode-articlelist/
