### ISSUE TITLE
Neues Template: Landing-Page

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#234]
Ggf. nur via Admin-Option freischaltbar: Template zu Landing- und Aktionspages

**Comment by xwolfde** [comment]
Ref #246

**Comment by xwolfde** [comment]
@RRZE-Webteam/fau-webredaktion Könnt ihr mir ein kleinen Wireframe machen, an was für Landing-Page Seiten ihr dachtet?
Was sollten diese enthalten/nicht enthalten?

Kopfteil? Metanav? Hauptmenu? Slider? Footer? Sidebars?

**Comment by wrkb** [comment]
Kümmere mich. Bekommst du!

**Comment by csw-** [comment]
Na da bin ich mal gespannt :) Insbesondere weil wir gerade dabei sind eine Art "Landingpage" für ein Forschungsthema aufzuziehen. Zumindest soweit das in dem aktuellen Rahmen eben möglich ist.
Eine LandingPage als richtigen Seitentyp wäre da sehr hilfreich.

Grüße,
Clemens

**Comment by xwolfde** [comment]
@RRZE-Webteam/fau-webredaktion denkt ihr noch an den Wireframe/Entwurf?

**Comment by xwolfde** [comment]
Was ich mir an der Stelle vorstelle:

Die Landing-Page hat 
* keine Hauptnavi oben, sondern nur das Logo und das Hamburger-Menü, wie bei Mobile Device unter 768 px
* die Sucheingabe wird als Suchsymbol neben dem Hemburger-Menü positioniert. Bei Hover/KLick auf das Symbol geht erst die Sucheingabe an der Stelle auf.
* Keine Bühne
* Keine Breadcrumb-Leiste
* Zwischen Logo und Hamburger oben ein Schattenwurf, wie bei Mobile Design unter 768 bei etwas runterscrollen.
* Unten der Footer: Nur der blaue Adressbereichsfooter, kein SoMe/Video-Footer
* Der Contentbereich geht über die gesamte Container-Breite, per Default keine Navi links, keine Sidebar rechts.


Flexible Teile sollen via Shortcode im Content einfügbar sein. Dazu gehören:
* Parallax
* Menü-Boxen a la Portalmenu
* Slidende Bilder a la Startseite Bildslider unten
* Spalten über den Content (mit allen Bootstrap-Varianten, aber insbesondere 2 Spalter, 3 SPalter, 4 Spalter)
* Die Spalten sollen mit einer Hintergrundfarbe setzbar sein, die aus der gängigen Farbauswahl definiert ist.

**Comment by xwolfde** [comment]
Ich schließe den Fall hier mal - wie besprochen werden wir das gesondert in einem neuen Theme als Kampagnen-Design entwickeln.
