### ISSUE TITLE
Template Standardseite Default

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#236]
Derzeit hat die Default Standardseite keine Navi.
Die Seite mit Navi ist ein eigenes Template.

Es kam der Wunsch, die Seite mit Navi zum Standard zu machen.

**Comment by wrkb** [comment]
Ich bin dafür, vermute, dass betrifft die meisten Anwender im Alltag, nachdem die Seitenstruktur angelegt wurde und vor allem Inhaltsseiten neu erstellt werden.

**Comment by xwolfde** [comment]
ich bin mir nicht sicher ob das gut ist... Hab damit Bauchschmerzen.

Das Design hebt sich doch durch seine Übersichtlichkeit von anderen Designs an.
Die Navi links ist für mich da immer etwas unschönes, was den Content einzwängt.
"Schöne" und gut lesbare Seiten sind die, welche eben keine Navi haben.

Wenn wir jetzt die Navi-Seiten zum Default machen, werden auch mehr Seiten damit versehen, obwohl das nicht schön aussieht.
Ausserdem hat das den Effekt auf die Webmaster, daß sie nicht mehr so viel Gedanken machen über das Hauptmenü. Denn ohne Seitennavi ist man ja gezwungen, sich mit der Taxonomie auseinander zu setzen und sich was schlaues und sinnvolles auszudenken...

**Comment by xwolfde** [comment]
Wenn du die aktuellen Designtrends bei großen Medien-Websites betrachtest, wirst du sehen, daß es dort kaum noch ein Menu links gibt. Menus links sind old desktop style.
(Was nicht bedeutet, dass die in jeder Situation schlecht sind).
Heutzutage navigieren die meisten über die Suche. Die Seiten sollen (wieder) Wert auf das wesentliche lenken. Und das bedeutet, dass alles was davon ablenkt und dazu zählen eben auch die Menus, reduziert oder in Hamburgern versteckt wird.


Aber lass uns nicht streiten. 
Ich hab halt ein schlechtes Gefühl bei der Sache. Wir müssen bedenken, daß wenn wir es ändern, auch allen  Redakteuren/Autoren abverlangen, ihren gewohnten Klick zu ändern. Auch wenn es bei den "Menu-Liebhabern" nun ein Klick weniger ist, es ist nunmal eine Änderung.

Ich hätte gern Meinungen von Autoren, wir beide als PROs sind ja nicht die, welche mit so einer Änderung Probleme haben werden...

**Comment by wrkb** [comment]
Stimmt, die linke Navi ist auch mit den üblichen Problemen behaftet, wir sind keine Fans. Deswegen muss das Design einfach weiter überarbeitet werden, da waren wir uns ja einig. Natürlich muss man bis dahin den Seitenstandard auch nicht anfassen, es wäre nur logischer. Autorenrückmeldungen wären tatsächlich schön.

**Comment by xwolfde** [comment]
Wie Diskussionen zeigten, sind Änderungen an gewohnten Dingen heikel. Diese Änderung würde auch schlagartig ein paar Hundert Webmaster treffen und damit unnötig Support kosten.

**Comment by wrkb** [comment]
Anmerkung: Jenseits der Frage, was als Standard voreingestellt sein sollte und der damit verbundenen (negativen) Auswirkungen, muss m.E. diskutiert werden, was wir als Standard haben wollen im Hinblick auf Lesbarkeit. Hier die bisherige default-Seite viel zu breit beim Textlauf und nutzerunfreundlich (war ja auch nur für landing pages gedacht).
Hier kann die Entwicklung des landing-page-Designs Impulse geben (dort ist die Frage ja aktuell) und vielleicht findet sich dann recht einfach eine gute Lösung. Aber das default-Template als tauglichen default ansehen im Sinne eines Web-CD, das sehe ich nicht.
