### ISSUE TITLE
Theme Options (Erweitert): Zitatersatz

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Einrichtungen#237]
Wenn man im Backend unter "Theme Options" das Häkchen beim Zitatersatz setzt (das ist auch der default), sollte eigentlich in der Hauptnavi ein Auszug aus der Seite anstelle des Zitats angezeigt werden. Das passiert aber nicht. In Anbetracht der Tatsache, dass das auch nicht übermäßig sinnvoll ist, schlage ich vor, diese Option einfach zu entfernen.
![bildschirmfoto 2017-04-20 um 11 50 56](https://cloud.githubusercontent.com/assets/11296947/25224827/e05991b6-25bf-11e7-8719-118fc1f7d0d5.png)

**Comment by xwolfde** [comment]
Mit Auszug ist der Excerpt gemeint, nicht ein Teil des Contents. Hast du das auch geprüft?

**Comment by AstridSemm** [comment]
Äh, welcher Excerpt? Wo ist der bei den Seiten im Backend? Ich bin gerade ein wenig verwirrt.

**Comment by xwolfde** [comment]
ist raus
