### ISSUE TITLE
Bilder per default css-Klasse zuweisen

### ISSUE THREAD

**Issue by anbininf12** [RRZE-Webteam/FAU-Einrichtungen#240]
Beitragsbilder wird per default die css-Klasse lightbox zugewiesen/verknüpft. Es wäre super, wenn man auch Bilder der Beiträge oder vielleicht sogar allen Bildern des Auftritts per Einstellung eine css-Klasse zuweisen könnte. Dann müsste man nicht bei jedem Bild in den erweiterten Einstellungen die Klasse verknüpfen.

**Comment by xwolfde** [comment]
Japp, ist auch schon seit längeren ein Issue #101 - leider bislang immer wegen anderer Prioritäten runtergefallen...

**Comment by xwolfde** [comment]
Im nächsten Release werden verlinkte Bilder, deren Link auf eine jpg/gif zeigt, automatisch mit der Klasse lightbox versehen.
Das ist nur eine Workaround-Lösung; Es sollte auch ohne LInk gehen.
