### ISSUE TITLE
Font bzw. Kerning kaputt

### ISSUE THREAD

**Issue by Velines** [RRZE-Webteam/FAU-Einrichtungen#241]
Hi,
bei einigen Buchstaben ist das Kerning ziemlich kaputt, d.h. zum Beispiel ein Doppelpunkt rutscht in den Buchstaben rein. Lässt sich leicht nachstellen wenn man in der Suchbox "P:" eingibt (zB direkt auf fau.de). Richtig auffallen tut es vor allem bei Listen von Publikations-Downloads, wenn etwa dem Download-Link ein "PDF:" vorangestellt wird.
Hier noch ein Beispiel zur Visualisierung, das den im Theme enthaltenen Font (obere Zeile) mit der aktuellen Version von Google (untere Zeile) vergleicht.

```html
<html>
<head>
<style>
@font-face {
      font-family: 'rrze-roboto';
      src: url("fonts/roboto/Roboto-Regular-webfont.eot");
      src: url("fonts/roboto/Roboto-Regular-webfont.eot?#iefix") format("embedded-opentype"), url("fonts/roboto/Roboto-Regular-webfont.woff") format("woff"), url("fonts/roboto/Roboto-Regular-webfont.ttf") format("truetype"), url("fonts/roboto/Roboto-Regular-webfont.svg#robotoregular") format("svg");
      font-weight: normal;
      font-style: normal
}
</style>
<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
</head>
<body>
<div style="font-family: rrze-roboto;font-size:5em">A: B: C: D: E: F: G: H: I: J: K: L: M: N: O: P: Q: R: S: T: U: V: W: X: Y: Z:</div>
<div style="font-family: roboto;font-size:5em">A: B: C: D: E: F: G: H: I: J: K: L: M: N: O: P: Q: R: S: T: U: V: W: X: Y: Z:</div>
</body>
</html>
```

Viele Grüße

**Comment by xwolfde** [comment]
Danke. Im nächsten Update werde ich den Font mal updaten

**Comment by xwolfde** [comment]
Hm...
Also an dem Font kann es nicht liegen.

Das ist identisch und aktuell. Das bei Google ist sogar noch älter (2013)
![roboto-diff](https://user-images.githubusercontent.com/1070669/26975827-b78b5006-4d21-11e7-8ac9-a30db116cbc0.jpg)

**Comment by xwolfde** [comment]
Es liegt offenbar eher am Font-Kerning. auto bzw normal sorgt dafür, dass die Zeichen zusammen rücken.
`font-kerning: none;  `
Macht es besser.

**Comment by xwolfde** [comment]
In der nächsten Version gefixt
