### ISSUE TITLE
Bei Kategorieseite als Portalmenü-Überpunkt wird kein Link generiert

### ISSUE THREAD

**Issue by rathsky** [RRZE-Webteam/FAU-Einrichtungen#242]
Setzt man eine Kategorie (d. h. eigentlich Kategorieseite) als Oberpunkt für ein Portalmenü, so wird kein Link generiert. Der Mouseover-Effekt (Unterstrich) funktioniert dagegen.

Andererseits ist es wiederum nicht möglich, einen solchen Oberpunkt ohne Link (d. h. rein für die Organisation auf der Portalseite) regulär zu erzeugen.

**Comment by xwolfde** [comment]
ja, das ist gewollt gewesen. Die Oberpunkte sollen per default nur auf Seiten gehen.

In der nächsten Version wird es aber einen Workaround geben:
Man kann eine Seite anlegen, die über den Shortcode [blogroll cat="Kategorie"] die Einträge der Kategorie enthalten kann.
