### ISSUE TITLE
Meldungen, wenn kein Beitrag existiert

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Einrichtungen#243]
Wenn man (in welchem Theme auch immer) keinen Beitrag hat, bekommt man im Backend folgende Meldungen:

Notice: Undefined variable: currentcatliste in /srv/www/vhosts/astrid.krach.rrze.uni-erlangen.de/websource/wp-content/themes/FAU-Natfak/functions/constants.php on line 699

Notice: Undefined variable: currentcatliste in /srv/www/vhosts/astrid.krach.rrze.uni-erlangen.de/websource/wp-content/themes/FAU-Natfak/functions/constants.php on line 744

Im Frontend auf der Startseite kommt das:

Notice: Undefined offset: 0 in /srv/www/vhosts/astrid.krach.rrze.uni-erlangen.de/websource/wp-content/themes/FAU-Natfak/functions.php on line 2095

Notice: Trying to get property of non-object in /srv/www/vhosts/astrid.krach.rrze.uni-erlangen.de/websource/wp-content/themes/FAU-Natfak/functions.php on line 2095

**Comment by xwolfde** [comment]
Im nächsten Release gefixt
