### ISSUE TITLE
Backend für kleinere Bildschirme optimieren

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Einrichtungen#244]
Das ist sicher nichts, was man gleich morgen anfassen kann, aber ich möchte es zumindest festhalten: Auf kleineren Bildschirmen (wenn man 1600x900 mal als klein definiert --> typischer FAU-Laptop) bin ich gezwungen, Spalten im Backend in den Listenansichten auszublenden, um überhaupt einigermaßen arbeiten zu können. So schaut es aus, wenn ich nichts ausblende (über den Sinn der Spalten im Beispiel kann man streiten, aber für andere post types braucht man viele Spalten, mindestens als Admin).

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/26161004/fc92b902-3b22-11e7-8d3a-845cc8546bc2.PNG)

Von den Wordpress-Entwicklern ist hier scheinbar nicht viel zu erwarten. Wenn sich da jemand mal berufen fühlt, was zu machen und wenn das getrennt vom Core geht - ihn/sie erwarten Jubel und Dankessekt! 🍾 

Da Text nun mal Text ist, fielen mir spontant andere Umbrüche ein (Titel des post types) oder das automatische Einklappen von Spalten (mit Pfeil o.ä. zum Aufklappen) - irgendein dynamisches Verbergen z.B.

Kaum auszudenken, was auf einem noch kleineren Laptop passieren würde...

Danke für die Aufmerksamkeit :)

**Comment by xwolfde** [comment]
Hm... Ich glaub das hängt weniger mit WP zusammen als vielmehr, dass das Workflow-Plugin da ein paar Spalten einfügte? @rvdforst

**Comment by rvdforst** [comment]
Der Style-Fehler kommt vom RRZE-Post-Expiration-Plugin. Ich werde versuchen, innerhalb dieser Woche den Bug zu beheben.
