### ISSUE TITLE
Mit WordPress 4.8 gibt es Probleme mit Contact Form 7

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Einrichtungen#247]
Der Text auf der Seite wird vom Formular überlagert; der Rahmen ist ebenfalls immer noch zu klein. Mit WordPress 4.7 ist alles ok. Achja, Contact Form 7 ist in der Version 4.8 installiert.
![bildschirmfoto 2017-06-09 um 10 45 49](https://user-images.githubusercontent.com/11296947/26969224-49b76e5a-4d05-11e7-9777-8e9b6ee60318.png)

**Comment by AstridSemm** [comment]
Auf WordPress 4.7.5 funktioniert's übrigens fabelhaft: https://www.alfirin.test.rrze.uni-erlangen.de/startseite-2/die-bartonik-seite/
![bildschirmfoto 2017-06-09 um 12 59 44](https://user-images.githubusercontent.com/11296947/26972806-92a24794-4d13-11e7-96af-abdc38bf17ca.png)

**Comment by xwolfde** [comment]
Ref #231

**Comment by xwolfde** [comment]
fixed
