### ISSUE TITLE
Links auf Kategorieseiten in der Navi der Inhaltsseiten

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Einrichtungen#248]
Kunde möchte wissen, ob sich Beitragskategorien in den Inhaltsseiten mit Navi einbinden lassen. Meines Wissens nach geht das (derzeit) nicht, da diese Navigation aus der Seitenhierarchie automatisch erzeugt wird. Nachdem ich es aber für sinnvoll halte, Kategorieseiten einem Menü hinzuzufügen, damit man die aktuellen Artikel eines Portals entsprechend einbinden kann, gebe ich das hierher weiter; vielleicht findet sich ja eine Möglichkeit, das einzurichten.

**Comment by wrkb** [comment]
Also postings in pages ausgeben geht nicht per default, aber es gibt z.B. Plugins dafür - der Wunsch kam recht früh mit Wordpress auf. Aber die Kategorien ins linke Menü zu packen zu können klingt nach vielen Nachteilen, wenn ich mal rumunken darf. Das Menü ist ja insofern heilig, als dass es nicht mit Überraschungen aufwarten darf (z.B. externe Links oder Sprünge in ganz andere Bereiche) - davor schützt die Automatik ja auch. Dieser Schutz geriete dann meiner Meinung nach in Gefahr bzw. haben wir dann einen weiteren Punkt im System, wo die Usability verschlechtert werden kann - aus Unwissen oder Ignoranz.

Wie bezeichet sich der Menüeintrag dann? Der Kategoriename allein wird meistens nicht sinnvoll sein.

Auf der Zielseite dürfte zudem oft noch Text wünschenswert sein - erklären sich aufgereihte Postings immer selbst? 

Das Einbinden von nativen Postings einer Kategorie per Shortcode (mit Bildern und Attributen) wäre dagegen wünschenswert - aktuell gehen wir hier ja noch den Umweg, RSS-Feeds einzubinden.

Grüße!

**Comment by AstridSemm** [comment]
Es gibt so viele Leute, die sich wünschen, in Portalen einen Punkt "Aktuelles" mit den Artikeln einer bestimmten Kategorie zu haben, dass sich das ernsthaft lohnen würde, Karsten. Wir gucken jetzt einfach mal, ob's überhaupt geht (ich habe da meine Zweifel). Insgesamt brauchen wir aber die Möglichkeit, Beitragskategorien möglichst schick einbinden zu können.

**Comment by wrkb** [comment]
In Portalen oder auf Inhaltsseiten? Du meinst sicher beides, also einen "festen" Menüpunkt in Portal und dann logischerweise auch in der Seitenstruktur und Navi? Wenn man es hardkodiert, also als Option im Theme z.B. anbietet, ist es natürlich gut.

Wir kennen den Wunsch auch :) Wobei die Seiten meist veralten, wir binden daher lieber RSS auf dem Portal ein, allein wegen der Aufmerksamkeit, aber den Bedarf kennen wir auch.

**Comment by AstridSemm** [comment]
Beides - auf den Portalseiten die einen, auf den Inhaltsseiten (mit Navi) die anderen. :o)

**Comment by xwolfde** [comment]
Das ist der alte Feature-Request anstelle dem automatischen Page-Menu ein manuell definierbares Menü anwählbar zu machen. Das wurde damals absichtlich nicht gewollt.
Denn so vorteilhaft es ist, es würde zwangsläufig dazu führen, dass einige Leute wieder dazu übergehen das Menü links als Hauptmenü aufzubauen und nicht mehr das Hauptmenü oben sowie die Portalmenüs zu nutzen.
Es würde also erlauben, dass das gewünschte Navigationskonzept hintertrieben werden kann.
