### ISSUE TITLE
Bühne Titel zu hoch

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#252]
Durch Update ist der Titel der Bühne/im Slider hochgerutscht. Wahrscheinlich aufgrund der Gridanpassung bei relativer Positionierung.

**Comment by ec89yler** [comment]
Zusätzlich zum zu hohen Titel fehlt u.a. auf https://www.wiso.rw.fau.de/ die Schaltfläche, um die Slides weiterzuklicken. Es bleibt auch immer beim Ersten. Bei den Seiten, die ich betreue, betrifft das jeweils die, bei denen der Expertenmodus ausgewählt ist. Auf https://www.rw.fau.eu/ ist alles wie zuvor, hier ist der normale Modus aktiv.

**Comment by xwolfde** [comment]
Ursache war an anderer Stelle. Wird gefixt
