### ISSUE TITLE
Bühne Slider Schaltfläche fehlt / bleibt statisch

### ISSUE THREAD

**Issue by ec89yler** [RRZE-Webteam/FAU-Einrichtungen#253]
Zusätzlich zum zu hohen Titel fehlt u.a. auf https://www.wiso.rw.fau.de/ die Schaltfläche, um die Slides weiterzuklicken. Es bleibt auch immer beim Ersten. Bei den Seiten, die ich betreue, betrifft das jeweils die, bei denen der Expertenmodus ausgewählt ist. Auf https://www.rw.fau.eu/ ist alles wie zuvor, hier ist der normale Modus aktiv.

**Comment by xwolfde** [comment]
Das ist seltsam. Wird geprüft und schnellst möglich gefixt-

**Comment by xwolfde** [comment]
Der Fehler wird leider durch das neue Video-Plugin https://github.com/RRZE-Webteam/rrze-video verursacht. 

Wir sind dabei das zu beheben. Ich hab das PLugin auf wiso.rw daher mal deaktiviert.

**Comment by xwolfde** [comment]
Bug im Gitprojekt des Plugins eingetragen
