### ISSUE TITLE
Beitrag soll nur mit externer Meldung verlinkt sein

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Einrichtungen#258]
wir haben eine Meldung gepostet, die nicht bei uns liegt, sondern auf einer externen Seite. Mit dem Klick auf den Titel der Meldung auf der Seite https://www.fau.de/category/news/ kommt man auf die externe Meldung (was gewünscht ist), beim Klick auf weiterlesen (“>“) erscheint eine Fehlermeldung, da die Seite bei uns gesucht wird…

**Comment by xwolfde** [comment]
Ist die Meldung parametrisiert? vgl: #208 
Wenn ja, bitte den Link wenn möglich ohne Parameter machen

**Comment by wrcg** [comment]
nein, es war ein ganz "normaler" Link (https://www.editionf.com/Die-25-Frauen-deren-Erfindungen-unser-Leben-veraendern)

**Comment by xwolfde** [comment]
kann ich die Meldung mal sehen? Welche genau war es?

**Comment by wrcg** [comment]
gerne: https://www.fau.de/2017/06/news/leute/prof-dr-marion-merklein-erhaelt-den-25-frauen-award/ 
Ich denke aber, jetzt kann man den Fehler nicht mehr nachvollziehen... Ich habe ja zur Fehlerbehebung einen eigenen Beitrag verfasst :-)

**Comment by xwolfde** [comment]
Ich verstehe nicht.
Der verlinkte Beitrag hat keinen Eintrag im Feld "Externer Link". Daher ist das dann auch kein externer Beitrag.

**Comment by xwolfde** [comment]
Im nächsten Update gefixt
