### ISSUE TITLE
Upload-Dialog für Mediathek (modal) weiter optimieren

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Einrichtungen#259]
Input nach der letzten Umstellung nach 4.8.-Update:

- Größe  der Auswahlboxen flexibel machen (Anfasser unten rechts, das bekannte kleine Dreieck, Screenshot nötig?). Aktuell ist der Gesamtdialog schön übersichtlich, das Suchen von Kategorien aber erschwert.
- Nach Auswahl eines Eintrags springt der Dialog wieder nach oben - Korrekturen oder Anhaken weiterer Kategorie erschwert. Dialog sollte an letzter Auswahl verweilen

**Comment by wrkb** [comment]
Pardon übrigens für den Neueintrag, ich fand mit der Suche den alten geschlossenen Eintrag nicht.

**Comment by xwolfde** [comment]
danke. passt schon hier.

Ich fürchte vor der WP 4.9 müssen wir nicht nur an der Stelle groß ans Backend ran. Durch die kommende Version soll das Backend von WP grundlegend erneuert werden.  
Es ist noch völlig unklar welche Konsequenzen es für alle Metaboxen und Modals haben wird :/   vgl: https://www.youtube.com/watch?v=yeXkfOKxIpg

**Comment by wrkb** [comment]
Das Problem ist auch dringender als gedacht (je intensiver man damit arbeitet, umso mehr wird das deutlich).
Dazu kommt auch, dass das Zurückspringen auf Position 1 nach Anhaken alle Felder betrifft. Also Anhaken eines Schlagworts setzt auch die Kategoriefelder zurück. Und da das System auch langsam ist, muss man hier schlimmstenfalls einige Sekunden Pause einlegen, bevor man weiter anhaken kann.

**Comment by xwolfde** [comment]
Wurde im zentralen Settings-Plugin (Taxonomien) umgesetzt.
Leider nochmal Änderungsbedarf, da Dinge, die nur für eine Redaktion gemacht wurden, nun leider alle Redakteure aller Sites betreffen; Auch jene, die solche Option nicht wollten und sich durch diese neuen Optionen gestört fühlen.
Gesondert Case in Gitlab. Kein Zusammenhang mehr mit FAU Themes.
