### ISSUE TITLE
Logo unscharf

### ISSUE THREAD

**Issue by anbininf12** [RRZE-Webteam/FAU-Einrichtungen#262]
Hallo,

wenn man die Schärfe von dem gif auf den alten Seiten mit dem png der neuen Seiten vergleicht (auch beim Betrachten auf dem Smartphone) fällt auf, dass das png unschärfer ist, als das gif
![logo-fau](https://user-images.githubusercontent.com/20298307/28572622-15c7d212-7148-11e7-97c8-3a3e0c0d8a6d.gif)
![logo-fau](https://user-images.githubusercontent.com/20298307/28572623-15e80988-7148-11e7-8ba7-e7ed3d4a623b.png)

**Comment by xwolfde** [comment]
*Seufz*
Wenn es nur mal eine saubere Vorlage in Form der PSD-Ebenendatei von dem Logo gäbe...  Das "Beste" was ich damals offiziell erhielt war eine PDF-Datei.

**Comment by xwolfde** [comment]
IN der nächsten Version wirds scharf ;)
