### ISSUE TITLE
Timeline 

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#264]
Geeignetes Timeline-Beispiel:
https://assortment.io/posts/building-responsive-timelines-in-css-sass-bem

ggf. für Kampagnenseiten
ggf als Plugin

**Comment by wrkb** [comment]
Ich hatte immer timeline.js im Visier (http://timeline.knightlab.com), aber das beim in der Darstellung beim Testen nie so schön wie in der Demo und die Anpassungen hielten sich dann doch in Grenzen. 

Dein Beispiel, @xwolfde ist schön reduziert und vertikal ist besser als horizonal für unser Design, denke ich. Was wichtig wäre: Bilder. Im Grunde wollten wir diese Seite immer als Zeitstrahl abbilden: https://www.275.fau.de/startseite/das-jubilaeum/geschichte-der-fau 

Eine Art "mehr"-Links zu anderen Seiten in jedem Zeitabschnitt wären auch wichtig - nicht für die Jubiläumsseite, aber für andere Zwecke.

**Comment by xwolfde** [comment]
Jupp. Ich werde aber trotzdem auch noch nach einer horizontalen Lösung Ausschau halten.

Wenn wir Seiten ohne Sidebar und ohne Nav links haben, könnte die sich anbieten. Vgl. hier als Beispiel eine Zeitleiste von MyHeritage
![beispiel-timeline-horizontal-myheritage](https://user-images.githubusercontent.com/1070669/28717429-0de1832a-73a2-11e7-8825-0a3bad0e55e7.png)

**Comment by xwolfde** [comment]
@endv02 @bmehler @cassandre Was denkt ihr: Plugin oder nicht? 
So eine Timeline wird bestimmt auch woanders ab und zu benötigt. Zum Beispiel nächstes Jahr bei so einem gewissen Rechenzentrum am Rande der Stadt :)

**Comment by endv02** [comment]
Klingt sinnvoll, dann haben gleich mehrere was davon.

Von: Wolfgang Wiese [mailto:notifications@github.com]
Gesendet: Freitag, 28. Juli 2017 23:36
An: RRZE-Webteam/FAU-Einrichtungen
Cc: Kimpan, Karin (RRZE); Mention
Betreff: Re: [RRZE-Webteam/FAU-Einrichtungen] Timeline (#264)


@endv02<https://github.com/endv02> @bmehler<https://github.com/bmehler> @cassandre<https://github.com/cassandre> Was denkt ihr: Plugin oder nicht?
So eine Timeline wird bestimmt auch woanders ab und zu benötigt. Zum Beispiel nächstes Jahr bei so einem gewissen Rechenzentrum am Rande der Stadt :)

**Comment by xwolfde** [comment]
reminder: http://www.archiv.tf.fau.de/50-jahre.shtml#1970

**Comment by xwolfde** [comment]
Diese Timeline (in der MItte, nicht das Navi links und das Modul rechts)  ist gar nicht mal so unschick. Würde auch optisch gut zu einer hellen und unaufdringlichen Site passen.
![timeline-sample](https://user-images.githubusercontent.com/1070669/31549130-819ac6ba-b02d-11e7-8e70-a1dc06d89e48.jpg)

**Comment by xwolfde** [comment]
nicht mehr in diesem theme. wird gesondert in dem veranstaltungs- und eventtheme umgesetzt.
