### ISSUE TITLE
Bitte dokumentieren: Seitenumbrüche

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#265]
Bitte in die Doku (für die nächste Release) aufnehmen:

**Seitenumbrüche in Artikeln und Seiten**

In der nächsten Version werden auch "Page-Breaks" funktionieren.
Zu sehen hier bei einem Artikel: http://test8.tindu.rrze.uni-erlangen.de/2017/07/28/test-seitenumbruch/
Und hier bei einer Seite: http://test8.tindu.rrze.uni-erlangen.de/beispiel-seite/

Autoren können hierzu im Texteditor die Zeile
`<!--nextpage-->`
in den Text einfügen. Dann wird an der Stelle der Seitenwechsel statt finden.

Für diejenigen Instanzen, die das Plugin TinyMCE aktiv haben und bei denen der Admin das entsprechende Icon auch nicht aus der Leiste entfernte (oder bei alten Installationen es wieder einfügte), gibt es hierzu auch ein Symbol:
![seitenumbrueche-v1-7-20](https://user-images.githubusercontent.com/1070669/28716232-4fb65754-739c-11e7-93e5-4f8e059dbd02.png)

**Comment by AstridSemm** [comment]
Erledigt. https://www.wordpress.rrze.fau.de/2018/01/05/tipp-seitenumbrueche/
