### ISSUE TITLE
Spanische Übersetzung muss erneuert werden

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#266]
Es sind ein paar Strings hinzugekommen oder wurden geändert. Daher bitte bei Gelegenheit die 
spanische Language Datei language/es_ES.po und es_ES.mo  im dev-1-7- Tree updaten.
 
(Am einfachsten mit dem Plugin Loco Translate auf einen geeigneten Testserver).

In dem Zusammenhang wäre ein Blick in die en_GB  und die en_US auch nice. Derzeit ist en_US eine Kopie der en_GB.  en_US haben wir nur  noch zur Abwärtscompatibilität. Ich würde es auch löschen, aber dann haben einige Websites, die auf en_US gesetzt haben statt auf en_UK Probleme....

**Comment by endv02** [comment]
Das sollte eigentlich mit dem Settings-Plugin aufgefangen werden - wenn kein UK da ist nimmt er US. War zumindest der letzte Stand den ich kannte.

Am 28.07.2017 2:30 nachm. schrieb Wolfgang Wiese <notifications@github.com>:

Es sind ein paar Strings hinzugekommen oder wurden geändert. Daher bitte bei Gelegenheit die
spanische Language Datei language/es_ES.po und es_ES.mo im dev-1-7- Tree updaten.

(Am einfachsten mit dem Plugin Loco Translate auf einen geeigneten Testserver).

In dem Zusammenhang wäre ein Blick in die en_GB und die en_US auch nice. Derzeit ist en_US eine Kopie der en_GB. en_US haben wir nur noch zur Abwärtscompatibilität. Ich würde es auch löschen, aber dann haben einige Websites, die auf en_US gesetzt haben statt auf en_UK Probleme....

**Comment by xwolfde** [comment]
ah super, dann kann ich die *_US Files ja bei nächsten Gelegenheit löschen.

**Comment by AstridSemm** [comment]
Was soll ich wo ins Spanische...?

**Comment by xwolfde** [comment]
Ergänze: Doku schreiben, wie man die Textinfos aus den Themes in anderen Sprachen übersetzt :P

**Comment by AstridSemm** [comment]
Ja, steht das noch nicht im Wiki?

**Comment by xwolfde** [comment]
Wiki ist auch ok. Sag mir die URL wenn du es hast ;)

**Comment by AstridSemm** [comment]
Dazu muss ich erstmal wissen, was ich reinschreiben soll. Brauche Input! ;oD

**Comment by xwolfde** [comment]
Nicht labern, machen :)

**Comment by AstridSemm** [comment]
Ja los, ich will ja mal weiterkommen! :o)

**Comment by xwolfde** [comment]
1. Installiere dir das Plugin Loco Translate
2. Hole dir die aktuellste Version des Themes aus dem GitHub. Dev Branch 1.9
3. Rufe Loco Translate auf.
4. Wähle Sprache
5. Übersetze
6. Speichere
7. Downloade die beiden aktualisierten Sprachdateien es_ES.mo und es_ES.po   aus dem Verzeichnis languages und lass mir diese zukommen.

**Comment by xwolfde** [comment]
Lassen wir erstmal weg. Zu viel andere Dinge zu tun mit Prio-
