### ISSUE TITLE
Sprung zu Ankerlink wird von fixer Haupt-Navigation verdeckt

### ISSUE THREAD

**Issue by f42au** [RRZE-Webteam/FAU-Einrichtungen#267]
Klickt man einen Ankerlink an, wird der obere Teil des entsprechenden Ziels durch die fixe Haupt-Navigation verdeckt - meistens eine Überschrift o.ä. Das ist etwas unschön und für manche User verwirrend, weil sie im ersten Moment meinen, der Link hätte sie nicht zur gewünschten Stelle gebracht.
Ist es möglich, für diese Links im CSS einen Offset (nämlich genau die Höhe der Haupt-Navigation) zu hinterlegen?

**Comment by xwolfde** [comment]
Danke für den Hinweis.
Der Bug (und andere die damit zusammenhängen) ist bereits bekannt und wird im nächsten Release gefixt sein. Hintergrund: WIr müssen das Grid-System umstellen und neue Breakpoints machen.
Ref: #246
