### ISSUE TITLE
Sprechende Namen für Sprungmarken auf ein Accordionfach

### ISSUE THREAD

**Issue by f42au** [RRZE-Webteam/FAU-Einrichtungen#268]
Wäre es möglich, in einem Collapse-Element ein weiteres Attribut (z.B. id o.ä.) mitanzugeben, das dann auch in einem Link mitverwendet werden kann?
Der Beispiel-Link in der Doku auf das Accordionfach „Freitag“ sähe dann z.B. so aus:
https://www.wordpress.rrze.fau.de/redaktion/accordion/redaktion/accordion/#freitagsmenues
statt
https://www.wordpress.rrze.fau.de/redaktion/accordion/redaktion/accordion/#collapse_4

Das wäre ein "Nice to have", mehr nicht!

**Comment by xwolfde** [comment]
Ja

ist auch halb angefangen, aber noch nicht fertig. 
Ref: #160

**Comment by xwolfde** [comment]
Ist im nächsten Release enthalten.

Neues Attribut dann: 
  name="sprungmarke"
