### ISSUE TITLE
BETA-Release Testreport

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#276]
Auf der Website
	https://www.beta.wordpress.rrze.fau.de/

findet sich ab sofort die BETA-Release für die neue Version.

Diese Version behebt einige Probleme und Bugs und führte viele neue Features ein.

Ich bitte um Tests der BETA-Website in verschiedenen Geräten und Browsern mit 
den verschiedenen dort vorhandenen Templates und Beispielseiten.
Falls Testseiten fehlen, bitte diese selbst anlegen und in die entsprechende
Navigation einfügen oder mir entsprechende Texte zukommen lassen.

Sollten bis kommenden Freitag, den 
	15.09. 
keine Bugs gefunden werden, die sich als Showstopper erweisen, wird
diese Version ab der darauf folgenden Woche ausgerollt.

Diese Mail kann gern an weitere interessierte Tester weiter gegeben werden.
Möglicherweise wird es Montag hierzu auch ein Blogeintrag geben.

Zur Info zu denen in der Version enthaltenen Änderungen siehe:
https://github.com/RRZE-Webteam/FAU-Einrichtungen/pull/275

Zusammengefasst:

BUGFIXES und allgemeine Verbesserungen:

- Mannigfaltige Mobile Device Probleme
- Hero-Text-Positionierung im Slider
- Medien (Bilder) - Anhangseite geht nicht #222
- Klötzchen in Fak-Farbe im Banner der Startseite #153
- Abstand h4 zu Kontakt innerhalb eines Akkordeons #217
- Logo unscharf #262

Neue FEATURES:
- Go / Zur FAU #274
- Shortcode für Darstellung der Blogroll in Seiten #233
  Siehe: https://www.beta.wordpress.rrze.fau.de/theme-shortcodes/shortcode-blogroll/
- Shoertcode zur Darstellung einer Artikelliste
   Siehe: https://www.beta.wordpress.rrze.fau.de/theme-shortcodes/shortcode-articlelist/
- Spalten Shortcodes. Siehe hierzu Beispiel:
  https://www.beta.wordpress.rrze.fau.de/tests/shortcodes/spalten/
- Mobile Device Design Refresh
- Blockquotes verbessert für akademischen Bedarf
  Siehe: https://www.beta.wordpress.rrze.fau.de/texte/blockquotes-und-zitate/
- Hauptmenu Flyover bei nicht verwendeten Zitatstexten
- Automatischer Tablesorter
  Siehe: https://www.beta.wordpress.rrze.fau.de/texte/tabellen/
- Neuer internationaler Sprachschalter - Symbol
- Adaptive responsive Sprachangabe
- Verbesserung der Zugänglichkeit der Suchbuttons und der Menüs im responsiven Design
- Silbentrennung h1-h3 verbessert hinsichtlich Usability-Anforderungen
- Upgrade des Grid-Systems
- Umstellung der Größenberechnung der Schriftfonts
- Performanceoptmierung durch Austausch von Grafiken durch Schriftfonts
- Verbesserung der WAI-Kennzeichnung von rein präsentativen Darstellungen

Hinweis:
Auf der BETA-Version wurde der CSS- und der JS-Code aus Debuggingzwecken
noch nicht komprimiert.

**Comment by xwolfde** [comment]
Im HERO-Submenü fehlen (wieder) die eckigen Pfeile. Checken.

**Comment by xwolfde** [comment]
Der Teasertext im Slider ist manchmal der von der Startseite und nicht vom Beitrag. Prüfen.

**Comment by xwolfde** [comment]
Mobile Device: Schriftgröße des SItetitels erhöhen. Ggf. Box eine Mindesthöhe geben

**Comment by xwolfde** [comment]
Bug: Darstellung der Event-News auf der Startseite ist vollkommen kaputt. 
Werte ich als Blocker:
![2017-09-14-16-23-www beta wordpress rrze fau de](https://user-images.githubusercontent.com/1070669/30435163-6192f19c-9969-11e7-8549-e07822fbf41e.png)
 Das kann so nicht online gehen.

**Comment by xwolfde** [comment]
Die Titel über den Quicklinks sind zu groß.
![2017-09-14-16-24-www beta wordpress rrze fau de](https://user-images.githubusercontent.com/1070669/30435187-75832276-9969-11e7-90b7-d17af7857fb8.png)

Bisher: 
![2017-09-14-16-26-www fau de](https://user-images.githubusercontent.com/1070669/30435266-a49ee3b0-9969-11e7-8ba0-1579bc07c6a5.png)

**Comment by xwolfde** [comment]
Bei der Konfig als FAU-Startseite ist das FAU-Logo in der Meta unsichtbar zu stellen und nur in der mobilen Ansicht 
![2017-09-14-16-27-www beta wordpress rrze fau de](https://user-images.githubusercontent.com/1070669/30435320-c420d4dc-9969-11e7-891c-7f75db0cb467.png)
sichtbar zu stellen.

**Comment by xwolfde** [comment]
Darstellung Blogroll in mobile Auflösung < 768

Die jetzige Darstellung der Blogroll bei kleinen AUflösungen funktioniert zwar, aber gefällt nicht
Vorschlag:


Titel
Bild auf voller Breite
Teasertext

**Comment by xwolfde** [comment]
Diskussion: Breakpoint für breitere Darstellung verschieben?

Aktuell auf FAU.de:  Maximale Containerbreite bei 940px bei Auflösungen über 979px 
Aktuell auf BETA:      Maximale Containerbreite bei 1170px   bei Auflösungen über 1250px.

Denkbar: Erst ab 1700px auf Containerbreite 1170px wechseln. 
Nachteile: 
- Beschwerden aus der Kundschaft.
- Dann müssen wir auch die Schrift wieder kleiner machen. Die ist aber unstandardmässig schon bei der alten Version zu klein gewesen (13px). Standard ist 16px. ZEIT.de u.a. verwendet in der Artikeldarstellung tw. sogar 20px.

Als optimal im Webdesign gelten **maximal** 85 Zeichen pro Zeile. 
85 Zeichen x Schriftgröße entsprechen:

-    bei 16px Schriftgröße:   1360 Pixel Breite für den Inhaltsbereich (erreichen wir nicht, weil der Container kleiner ist)
-    bei 13px Schriftgröße:   1105 Pixel Breite für den Inhaltsbereich

Minimal sollte eine Zeile 45 Zeichen Platz lassen.

-    bei 16px Schriftgröße: 720px
-    bei 13px Schriftgröße: 585px.

Der Inhaltsbereich enthält optional die Subnavi und die Sidebar.
Die Subnavi hat eine maximale feste Breite von 33% des Containers.
(= 313px bei Auflösungen fau.de alt ab 979px: = 380px bei Auflösung ab 1250px)

Die Sidebar ist Teil des Inhaltsbereiches und floatet. Sie hat eine maximale Breite von 220px, von denen 40 px zum Randabstand gehören.


   |----------Container-----------|
   | Subnav |  Main           | Sidebar|  
   |              |                                    |
   |----------Container-----------|


Und Main muss größer sein als 720px.

720px (Main)+ 380px (Subnav) + 220px (Sidebar) = 1320px.

=>  Nach nachlesbaren Usability-Aspekten muss der Container einer Breite von 1320px aufweisen, wenn wir eine Schriftgröße von 16px haben UND eine Seite mit Sidebar und Subnav haben. 

=> Die bisherigen Breiten auf fau.de waren viel zu klein in solchen Fällen, was die Beschwerden bestätigt.

**Comment by xwolfde** [comment]
Bug: Teaser der Blogroll mit kaputter URL versetzt.
![2017-09-14-17-26-www beta wordpress rrze fau de](https://user-images.githubusercontent.com/1070669/30438644-043e9132-9972-11e7-8988-1f333b4c3217.png)

**Comment by xwolfde** [comment]
Bug: hr testen. Da ist was bei großen Auflösungen futsch gegangen :/.

**Comment by wrkb** [comment]
h2-Abstand zum blauen Header (Inhaltsseite) zu groß

![unbenannt](https://user-images.githubusercontent.com/9445370/30439997-a84c403c-9975-11e7-8240-23cb0f9f2a1f.PNG)

**Comment by wrkb** [comment]
Beim Verlinken einer Mailadresse (markieren,kopieren, Link-Tool öffnen) wird beim Einfügen der Adresse nicht automatisch mailto: vorangestellt. Auf fau.de schon eine Weile so.

Die Automatik bitte wiederherstellen :)

**Comment by wrkb** [comment]
Top-Veranstaltung: Text fließt nicht ums Bild.
![unbenannt](https://user-images.githubusercontent.com/9445370/30482333-df62543c-9a22-11e7-90bf-d9955319be89.PNG)

**Comment by wrkb** [comment]
Stufe zwischen Blogroll und Portalboxen-Menü auf der  Startseite - das Menü ist nicht in der Flucht
![unbenannt](https://user-images.githubusercontent.com/9445370/30482417-3c16d036-9a23-11e7-9cb7-61b07aded84a.PNG)

**Comment by xwolfde** [comment]
Das mit der Mailadresse hat nichts mit der Frontend-Optik zu tun. 
Aber da haben wir inzwischen schon geschaut. Das Problem geht zurück auf eine Kollission mit dem Code für das bequeme Einfügen von Links in der SIdebar. (Da geht das Modal auf mit der Suche nach Beiträgen). Dieser Code der diese Funktionalität ermöglicht, kollidiert mit der Erkennung von Mailadressen im Editor.  

tl;dr: Wir können das momentan nur so fixen, dass wir den Code wegnehmen. Dann wird man aber keine bequeme Eingabe&Suche für Links mehr haben. 
Das sehe ich als kritisch für die Normalkunden und würde es daher ablehnen. 
Grundsätzlich sehe ich das Schreiben von Mailadressen im Text eh als falsch an. Gerade für Kontaktdaten haben wir das Personenplugin. Und für die wenigen Mailadressen wo es kein EIntrag gibt, da kann man schon den Aufwand hinnehmen, 6 Buchstaben einzufügen.

**Comment by wrkb** [comment]
Achso, soll nur um Optik gehen.
Wenn es kein Bug ist, dann leben wir auch ohne Automatik, brauchen wir tatsächlich nur für Blogeinträge - kein Problem.

**Comment by xwolfde** [comment]
Nee, melde schon alles was du findest. Geht mir nur um die Einordnung ob das etwas ist, was auch außen sichtbar ist oder nicht. ggf. wenn etwas länger ist ruhig auch einen eigenen Issue aufmachen und hier nur drauf verweisen.

**Comment by wrkb** [comment]
Bilder in Blogbeiträgen grundsätzlich zentriert darstellbar machen (aktuell nur linksbündig möglich).
Sinnvolle Standard-Bilddimensionen/-formate sind gerade in Diskussion (vgl. Telefonat vom 14.9.)

**Comment by wrkb** [comment]
Zitat (im Beitragstext) zu klein (aktuell ist es größer, siehe https://www.fau.de/universitaet/stiften-und-foerdern/deutschlandstipendium-stiften/stimmen-zum-deutschlandstipendium/

Bitte Schrift größer - soll mehr herausstehen.

![unbenannt](https://user-images.githubusercontent.com/9445370/30487148-dcfaf810-9a32-11e7-91fd-005a55bff519.PNG)

**Comment by wrkb** [comment]
Bild-Slider Startseite: Bitte das Pause-Zeichen weniger fett/dominant. Das Play-Zeichen wahrscheinlich analog.
Der Abstand zwischen Zeichen und Text Pause ist auch zu klein.

![unbenannt](https://user-images.githubusercontent.com/9445370/30488075-9c83ebcc-9a35-11e7-9f11-a9f102e8c382.PNG)

**Comment by wrkb** [comment]
Bilder im Hauptmenü skalieren größer als bisher (siehe fau.de). Sicher gewollt, könnte auch gefallen (was sagen die anderen), aber dadurch wirkt der Abstand nach oben zu klein - das Bild stößt oben an gefühlt. Anders platzieren? Größe ändern? Bin mir nicht sicher.

![dafdsfasdf](https://user-images.githubusercontent.com/9445370/30488356-5ea09516-9a36-11e7-9042-8c339cc9d68e.jpg)

**Comment by wrkb** [comment]
Mobilversion: Beim Slider oben die Pfeile weg - eh zu klein zum Treffen, Wischen funktioniert und ist akzeptiert. Nur der Pause-Button müsste bleiben.

**Comment by wrkb** [comment]
Mobilversion: Darstellung des Portalmenüs mit Links unten prüfen - Links laufen aus dem Ruder, Bilder sind zu eng aneinander und skalieren verschieden. Schon gemeldet?

![screenshot_20170915-170056](https://user-images.githubusercontent.com/9445370/30489503-a1811f76-9a37-11e7-84e8-e7cd164484c0.png)

**Comment by wrkb** [comment]
Mobilversion: Menü aus dem blauen Balken aus dem Desktop-Header hängt unten an der Seiten - dort erwartet es eher niemand mehr und es ist nicht schön. Kann es als Quick-Navi irgendwo hin? Ins Hamburger-Menü? Oder als Ausklappelement auf der Seite? (Modal?) (Wohin sonst?)

![screenshot_20170915-170254](https://user-images.githubusercontent.com/9445370/30489630-fe385860-9a37-11e7-9912-89f0aa96b659.png)

**Comment by wrkb** [comment]
Mobilversion: Bedienkonsistenz: Hamburgermenü auch per Wischen aus dem rechten Displayrand öffnen? Erwünschte Redundanz, nicht ungewöhnlich?

**Comment by wrkb** [comment]
Mobilversion, zur Frage von @xwolfde , wie Blogroll besser dargestellt wird:

- Text umfließt Bilder, wie bei Desktop? (oldschool)
- Bilder über volle Breite, Text unter Bilder? (wie passt das für Hochformate?

Ich habe eine weitere Idee: Bilder (fast immer 3:2, manchmal Hochformate) 50/50 nebeneinander, randlos, also sehr flat design. Darüber/darunter nur den Titel, Teaser klappt auf, wenn man...
- auf Bild/Titel tippt oder
- gar nicht, man ruft gleich den Beitrag auf per Tipp auf Bild/Titel oder
- auf einen Haken unter dem Titel/Bild tippt (der Haken, den wir überall haben, nur horizontal)

Wireframe müsste ich dann noch liefern.

Dann müssten wir ab sofort aber 4 Beiträge auf der Startseite haben (und redaktionell mitdenken).

**Comment by wrkb** [comment]
Mobilversion: FAU-Logo im Footer unscharf

**Comment by wrkb** [comment]
Mobilversion: Bilderslider unten ruckelt, ist auch optisch nicht weiter abgetrennt vom restlichen Inhalt. Beides halb so wild fürs Erste, mein ich.

**Comment by AstridSemm** [comment]
Hat das Texthintergrunddingsi für das Lehrstuhltemplatebanner eine feste Breite?
![bildschirmfoto 2017-09-20 um 12 09 09](https://user-images.githubusercontent.com/11296947/30638726-a3de57de-9dfc-11e7-853f-9842cea35e0b.png)
Das wäre aweng ungünstig.

**Comment by AstridSemm** [comment]
Und mit den Rahmen um die Formulare gibt's auch wieder Spaß. Siehe hier: https://www.beta.wordpress.rrze.fau.de/formulartest/

**Comment by xwolfde** [comment]
GRRRR

**Comment by mduven** [comment]
Hallo zusammen,
anbei auch unsere ersten Anmerkungen speziell zur Startseite, zum Teil sind diese hier ja auch schon aufgeführt:

•	Metanavi schwebt, Suchfeld klebt am unteren Rand der grauen Fläche
•	Logo auf Bühne rechts zu wenig Abstand nach unten, Navigation und Logo nicht mehr auf einer Linie
•	Abstände zwischen Logo und Navigation passen nicht
•	Header links eng, rechts weit, unruhig
•	Siegel falsch positioniert, nicht mehr angeschnitten, schwebt frei in der Fläche
•	Überschriften Bühnen-Navigation zu groß, vorherige Verschiebung war schon gegen die Linienführung
•	Abstand Überschriften <-> Bühnen-Navigation zu groß
•	Spaltenabstände zwischen Sprunglinks viel zu weit und unschön 
•	Abstand erster Beitrag zur Bühne ist zu groß
•	Überschrift erster Beitrag und Top-Veranstaltung nicht auf der gleichen Höhe
•	Anleser der Beiträge viel zu breit, gegen Lesegewohnheit. Speziell bei RW füllen wir diese immer komplett, daher dann viel zu langer Anleser
•	Bildmaße verändert, alle alten Bilder werden verzogen sein oder graue Flächen haben.
•	Darstellung der Veranstaltungen, die Schrift ist zu groß? Die Farbfelder sind verzogen.
•	Pause-Button unter den Bildlinks zu groß
•	Social Media-Footer: Überschrift zu groß, Abstand zum Inhalt zu groß
•	Beitrags-Links werden falsch dargestellt

--> Insgesamt verliert das bisherige Design durch die Eingriffe extrem an Qualität (siehe vgl. 2014-heute). Wie in unserer Mail geschrieben, geht das Gesamtbild verloren.  Ganz speziell verändert sich die Startseite, leider nicht zum Guten, die Mittelachse verschwindet, Weißraum wird unharmonisch, das Pattern bzw. die Linienführung wird unsauber und Abstände werden zu breit, etc.

2014:
![rw_web_2014](https://user-images.githubusercontent.com/28564104/30744070-b26651ee-9fa0-11e7-8a77-137ee8fc1dbe.jpg)

aktuell:
![rw_web_aktuell](https://user-images.githubusercontent.com/28564104/30744078-bab2913c-9fa0-11e7-82a9-c3c2fba083b1.jpg)

Beta:
![fau_web_beta](https://user-images.githubusercontent.com/28564104/30744083-c0bd0314-9fa0-11e7-87f4-be69cee8222c.jpg)

**Comment by lagerlit** [comment]
Hallo, hier noch ein paar Dinge, die uns aufgefallen sind:

- Termine  auf der Startseite: Kalendersymbol höher, dadurch weniger dicht. Ingesamt Termindarstellung schmaler und größere Schrift (passt weniger Inhalt rein).

- Außerdem  wäre es schön, wenn Termine, die über zwei Tage gehen, keine zweizeilige Datumsangabe haben.

**Comment by lagerlit** [comment]
Meldungen Blockroll:

- Passepartout für Bilder nicht mehr 3:2 (wichtig, weil Arbeitsgröße)
- URL im Teaser

**Comment by lagerlit** [comment]
Logo-Slider
- Zu viel Abstand zwischen den einzelnen Bildern (horizontal)

**Comment by lagerlit** [comment]
Social Media Footer
- wird auf allen Seiten angezeigt, soll aber nur auf Startseite sichtbar sein

**Comment by lagerlit** [comment]
Innerhalb Beitrag:
- Bilder zentrieren funktioniert nicht (auf Seiten klappts)
- Zitat-Schrift zu klein (kleiner als vorher, dadurch schwer lesbar)
- Bild links von Text positionieren funktioniert nicht (Frau in LKW) – BU nicht unter Bild platziert https://www.beta.wordpress.rrze.fau.de/2017/09/14/mein-ehrenamt-laesst-andere-die-schoenheit-unseres-universums-erkennen/

**Comment by lagerlit** [comment]
Bilder auf Seiten
- Bild > bearbeiten > Option "Größe" fehlt 
(hier aufgefallen, weil Bild mit zu wenig Abstand links komisch umbricht) https://www.beta.wordpress.rrze.fau.de/bilder/medien-und-grafiken/

**Comment by lagerlit** [comment]
Schriftgrößen
- gehen insgesamt auf der Seite ziemlich durcheinander. 
- H2 und Sidebarüberschrift zum Beispiel größer
- Differnzierung zwischen Überschriften schwierig
-h3 wird fetter (bspl https://www.beta.wordpress.rrze.fau.de/plugins/accordion-und-personen/ vgl. https://www.fau.de/graduiertenzentrum/weiterbildung-und-netzwerke/)
- bei Visitenkarten Schriftgrößen komplett durchmischt (von viel zu groß bis hin zu zu wenig Abstand, Beispiele: https://www.beta.wordpress.rrze.fau.de/plugins/accordion-und-personen/seite-mit-kontakten-und-sidebar-rechts/ und https://www.beta.wordpress.rrze.fau.de/plugins/personen-shortcodes/)

**Comment by lagerlit** [comment]
Buttons linkszentriert
- https://www.beta.wordpress.rrze.fau.de/templates/startseite/

**Comment by lagerlit** [comment]
Akkordeon
- läuft, wie alles, zu breit (dazu mache ich keinen extra Post, wurde ja schon telefonisch besprochen, waurm das für uns ein absoluter Stopper im Design, oben von Silke ja auch Anmerkungen. Kann ich aber gern noch für jeden Seitentyp einzeln Rückmeldung geben, falls gewünscht. Bitte Bescheid geben)
- So ist der Pfeil zu weit rechts (Info, dass aufklappbar, kommt zu weit hinten) https://www.beta.wordpress.rrze.fau.de/plugins/accordion-und-personen/  und https://www.beta.wordpress.rrze.fau.de/plugins/accordion-und-personen/accordion-auf-standardseite-mit-sidebar-rechts/

**Comment by lagerlit** [comment]
Videos:
- Automatische Überschrift über Video, das mit shortcode eingebunden ist, zu groß https://www.beta.wordpress.rrze.fau.de/plugins/seite-mit-video-und-galerie/ 
- geht Video zentrieren? Ich weiß nicht, was ich im Shortcode verändern muss
- geht Videogröße selbst bestimmen? https://www.beta.wordpress.rrze.fau.de/tests/standard-oembeds/ hier zu klein (youtube und videoportal)

**Comment by lagerlit** [comment]
Wir testen natürlich weiter ... 
LG, Luisa

**Comment by wrkb** [comment]
Videos im Social-Media-Footer: Wollte ich testen, kam nicht weiter via Widget. Wenn ich weiß wie, pack ich da 3 Videos aus video.fau.de rein.

![unbenannt](https://user-images.githubusercontent.com/9445370/30749939-4cdb187c-9fb5-11e7-927f-e431965478c8.PNG)

**Comment by wrkb** [comment]
Portalmenüs: Boxenanzahl pro Zeile ändert sich mit Beta und ändert die ganze Menülogik.

Bislang: 4er-Teiler, maximal 8 Boxen (so ists vom Designer gedacht), minimal 2 (bzw. mehr als die Hälfte horizontal gefüllt). War auf Stimmigkeit und Übersichtlichkeit getrimmt - beides ist leider verschwunden.
Neu: 5er Teiler

8 Boxen sieht nicht mehr gut aus: https://www.beta.wordpress.rrze.fau.de/tests/ - mit Links, und https://www.beta.wordpress.rrze.fau.de/theme-shortcodes/ - ohne Links.

2 Boxen sind als Minimum nicht mehr zumutbar eigentlich: https://www.beta.wordpress.rrze.fau.de/bilder/ (Hier müssten wir komplette Seitenbereiche umbauen, weil wir ja nicht mal eben die nötige dritte Box erfinden können).

Entweder zurück zu 4er-Teilung, aber hier müsste man sehen, ob das Vergrößern der Boxen/Bilder hilft oder eher eine zentrierte Einrückung (das wäre die Rückkehr zur alten Spalte).

Oder eine harmonische andere Anordnung finden, wobei das Minima und Maxima aus dem ursprünglichen Design zu beachten sind, die als inhaltsabhängiger Status quo nicht einfach aufgelöst werden können (betrifft alle Nutzer).

**Comment by wrkb** [comment]
Startseite:

- Der Spaltenlauf im blauen Bereich mit den zentralen Links unter der Bühne wurde bereits bemängelt. Mir ist hier die Schrift im Vergleich auch zu klein - hier sollte beides angepasst werden.
- Auch betroffen: Alle ähnlich kleinen Link-Schriften - z.B. im Portalmenü unten. (Das so übrigens mit Links auch auf der FAU-Startseite kommen könnten)

**Comment by wrkb** [comment]
Social-Media-Footer:

Grundsätzlich gut ist, dass die Links horizontal angeordnet angeordnet werden, wenn keine Videos vorhanden sind. Aber es sieht nicht gut derzeit - zu gestreckt:

![unbenannt](https://user-images.githubusercontent.com/9445370/30751067-8b844488-9fb8-11e7-8550-3b5d08e9d928.PNG)

Der häufigere Fall, dass nur max. 2 oder 3 Angebote da sind, sind noch unschöner aus: 

![unbenannt2](https://user-images.githubusercontent.com/9445370/30751168-d7f91104-9fb8-11e7-914b-9edba9d42c05.PNG)

Vielleicht hilft hier ein flacherer Bereich. Oder ein Blick darauf, wie es denn bisher gemacht wurde. Hab selber noch keine Lösungsidee.

**Comment by wrkb** [comment]
Blogbeitrag, full-post-Ansicht:

Das Suchfeld ist neu, wirkt nicht ganz stimmig. Ist schmaler als die Spalte (sieht es in voller Breite besser aus?) und hat andere Farben als das identische Feld oben. Oder es wirkt andersfarbig durch den Hintergrundkontrast:

![unbenannt](https://user-images.githubusercontent.com/9445370/30751424-96771234-9fb9-11e7-97f8-7b577a10cc90.PNG)

Vergleich zur bisherigen Lösung:

![unbenannt2](https://user-images.githubusercontent.com/9445370/30751450-9f557166-9fb9-11e7-9ca1-b2f87bd2e6f9.PNG)

Die bisherige Lösung ist nicht schöner, funktioniert aber grundsätzlich. Zwei verschiedene Suchfelder sind akzeptabel - könnte als Fallback-Lösung herhalten, falls die neue Variante noch ein Release geschoben wird?

**Comment by xwolfde** [comment]
Alle oben gemeldeten Probleme wurden in einzelne Issues ausgelagert.
Die Issues wurden entsprechend ihrer Auswirkung getaggt. Es gibt 2 klare Blocker-Bugs, einige Bugs, die das optische Erscheinungsbild beschädigen, aber die Bedienung nicht verhindern, sowie einige Issues, welche Themen in DIskussion behandeln.

Ein Stand der Umsetzung ist auch über diese URL abrufbar:
https://github.com/RRZE-Webteam/FAU-Einrichtungen/milestone/4

**Comment by Silsa** [comment]
Das Zerlegen der Probleme in einzelne Issues ändert leider nichts daran, dass die Beta-Version insgesamt ein echtes Designproblem hat. Das wir auch nicht ändern, in dem wir das jetzt jeweils kleinteilig diskutieren. Es geht um einen harmonischen, durchgehenden Gestaltungsansatz.
Und dieser geht gerade ohne echte Notwenigkeit verloren. 

Es war doch prinzipiell angedacht in den kommenden 2 Jahren ggf. einen weiteren Relaunch anzugehen. Zumindest wäre das nötig ^^. Und bis dahin die Mammutaufgabe abzuschließen, alle LS etc. endlich auf Wordpress umzustellen ...
In dem Zeitrahmen haben wir dann auch die übliche Lebensdauer des Designs mehr als erreicht. 

Dann ließe sich doch das ganze Design vor vornherein auf die neuen Bildschirme (5k etc.) abstimmen. Und auch mehr auf Usability optimieren. Warum jetzt in einem mE unkontrollierten Schnellschuss das alles ändern und umschmeißen …?

**Comment by xwolfde** [comment]
Die Aufsplittung ist für mich wichtig, damit ich nicht den Überblick verliere.  Außerdem ist diese Rot-Grün-"Ampel" oben doch auch ganz schön um den Status zu überblicken.

An den Update wird nicht erst seit gestern gearbeitet, sondern schon seit dem Frühjahr. Es ist notwendige Grundlage viele wichtige Anforderungen, die wir erfüllen müssen und auf die einige Leute dringend und mit Nachdruck warten. Es hängt da nun mal mit viel zusammen...  Auch wenn die Beta jetzt ziemlich "Broken" aussieht - genau das ist ja der Sinn der Sache einer Beta. 
Am Ende müssen diese Bugs behoben werden: Alle obigen Referenzen müssen "Closed" sein.

**Comment by xwolfde** [comment]
Alle Bugs behoben. Jetzt noch Feinschliff/Kleinigkeiten.

**Comment by xwolfde** [comment]
Auf der Beta findet sich ab sofort der neue "Release Candidat 2".
Alle obigen Probleme wurden mEn behoben. Der offene Bugs ist nur deswegen nicht geschlossen, da dieser noch zur Dokumentation verwendet werden soll.

**Comment by xwolfde** [comment]
WICHTIG: Cache löschen nicht vergessen! 
Wenn auf der Startseite das Artikelbild mit Passepartout so richtg breit ist, dann ist der Browsercache nicht gelöscht worden.

**Comment by xwolfde** [comment]
Alle oben aufgeführten Probleme sind gelöst.  AB sofort steht eine neue Version auf dem Testportal zur Verfügung.  Issues bitte in den Problemsammler: #334
