### ISSUE TITLE
Top-Veranstaltung: Text fließt nicht ums Bild.

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#284]
War da Floating wirklich gewollt? Egal, machen.
Ref: https://github.com/RRZE-Webteam/FAU-Einrichtungen/issues/276#issuecomment-329769919

**Comment by xwolfde** [comment]
Pointer zur Info: @RRZE-Webteam/fau-webredaktion

**Comment by lagerlit** [comment]
Hallo Wolfgang, ich glaube hier muss es gar nicht floaten, sondern das Bild größer. Oder Karsten?

**Comment by xwolfde** [comment]
Hat bislang auch nie gefloatet.
Anbei Screenshot von einer Site im Februar 2016
![screenshot-rw-fau de-20160201](https://user-images.githubusercontent.com/1070669/30924718-df69695c-a3af-11e7-9b5c-3e4548976656.jpg)


Sorry, kein Bug.
