### ISSUE TITLE
Stufe zwischen Blogroll und Portalboxen-Menü auf der Startseite - das Menü ist nicht in der Flucht

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#285]
ref https://github.com/RRZE-Webteam/FAU-Einrichtungen/issues/276#issuecomment-329770515

**Comment by xwolfde** [comment]
> "Post scriptum: Die Menüaufteilung macht uns auch nicht glücklich. Wir haben ja immer 2 bis 4 Bilder/Boxen in einer Reihe, durch die Skalierung kommen nur noch unrunde Zahlen zustande. Zwar muss das Layout flexibel sein durch breaking points, aber gäbe es einen Weg, bei durch zwei teilbaren Anordnungen zu bleiben? Die Flucht mit Blogroll und Slider unten wäre dann nicht mehr Prio. Meinungen?"

Ja. machbar. 
Sag mir bitte wieviele "Boxen" bei:
a) <768
b) >=768 bis < 1200
c) >= 1200 bis < 1720
d) > 1720


Momenten haben die Boxen eine feste maximale Breite und passen sich demenstprechend an den verfügbaren  Platz an.  Das läuft im Prinzip auf dasselbe raus.

**Comment by xwolfde** [comment]
Pointer zur Info: @RRZE-Webteam/fau-webredaktion

**Comment by wrkb** [comment]
a bis d: 4 Boxen pro Zeile bitte :)

**Comment by xwolfde** [comment]
Unter 768px passen keine 4 Boxen hin, wenn jede mindestens 220 Pixel Breit ist.

**Comment by xwolfde** [comment]
fixed
