### ISSUE TITLE
Mobilversion: Beim Slider oben die Pfeile weg

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#289]
Ref https://github.com/RRZE-Webteam/FAU-Einrichtungen/issues/276#issuecomment-329807451

Ähm... not a bug, feature!
Trotzdem prüfen.

**Comment by xwolfde** [comment]
Pointer zur Info: @RRZE-Webteam/fau-webredaktion

**Comment by wrkb** [comment]
Die Pfeile sind ja zu klein zum Drücken - und man muss zwischen die Pfiele zielen, um Pause zu erwischen.
Das Ausblenden mobil funktioniert natürlich nur, wenn auch davon ausgegangen werden kann, dass ein Mobilgerät im Einsatz ist (also sehr kleine Auflösung oder nach ähm... Useragent? Ich komm hier mal wieder durcheinander). Bei kleinem Browser auf kleinen Bildschirmen müssen die Pfeile bleiben.

**Comment by xwolfde** [comment]
Ref #263 

Ich tendiere dazu, bei Auflösungen kleiner 480px den Slider wegzumachen. 
Gerät ist egal, es geht um die Bildschirmbreite.

**Comment by xwolfde** [comment]
Anmerkung: Usability-Tests sagen: Daumen/Finger auf Smartphones braucehn ca. 72px Tippfläche.

**Comment by wrkb** [comment]
Könnte mir vorstellen, dass niemand wirklich am automatischen Sliden auf dem Mobilgerät hängt (ich tus nicht) - ich frag mal hier rum.
Tippfläche: Es geht natürlich, die Touch-Tastaturen sind auch irre kleinteilig und funktionieren. Aber ein isolierter Pauseschalter wäre praktischer :) Kein große Sache allerdings, anderes ist wichtiger grad.

**Comment by xwolfde** [comment]
Slider entfällt unter 768.

Unter diesem Wert ließe sich aufgrund der gestiegenen Schriftgröße im Vergleich zu dem Bild nicht merh verhindern, daß die Schrift des Titels z.B. in Gesichter reinwandert.
