### ISSUE TITLE
FAU-Modus

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#29]
Modus anpassen, dass man mit dem Theme auch das FAU-Theme nachbilden kann.
IMHO fehlt da nur noch das einschalten der 4 Spalten unter der Hero und
eine Prüfung zur Abwärtscomptabilität der Kontakte.

**Comment by xwolfde** [comment]
Beispiel der RW zeigt, dass die gefahr groß ist, daß auch Untereinrichtungen das Design der Fakultäten nehmen um ihr bevorzugten Design zu holen. Das würde auch hier der Fall sein. Daher ggf. hardcodiert die option abhängig von der Domain machen?

**Comment by AstridSemm** [comment]
Halte ich für nicht praktikabel; wenn ihnen irgendetwas nicht passt, holen sie sich einfach Webspace und verbiegen das Theme eben selbst. Natürlich supporten wir das nicht etc, aber der Schaden für die CI ist dann mE größer.

**Comment by xwolfde** [comment]
Die Alternative ist allerdings das Pflegen eines eigenen Themes für die ZUV; Da läuft die Entwicklung dann auseinander. :(

**Comment by xwolfde** [comment]
In nächster version drin.  
Option wird nur bei definierten URLs frei geschaltet.
