### ISSUE TITLE
Mobilversion: Menü aus dem blauen Balken aus dem Desktop-Header hängt unten an der Seiten

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#291]
Das ist genauso gewollt.
In der mobilen Ansicht muss erst recht das wichtige oben. Alles andere und dazu zählen insbesondere Links, die von der Website wegführen, müssen nach unten.
Über ein weiteres Aufklappmenü kann aber diskutiert werden.

Trotzdem gilt hier: Optisch weniger ist mehr.

**Comment by xwolfde** [comment]
Pointer zur Info: @RRZE-Webteam/fau-webredaktion

**Comment by wrkb** [comment]
Auf dem Desktop sind das die meistgeklickten Links, danach/daneben die News. Hängt auch ein wenig von der Zielgruppe ab - auf dem Mobilgerät müsste man sich mehr entscheiden: Studierende und Externe ansprechen und diese Linksektion höher (oder ausfahrbar?) oder mehr Schwerpunkt auf die News, die auch sehr viel intern gelesen werden (mangels interner Kommunikationsplattform).

Diskussion wäre gut, wir könnten die Zahlen mal hernehmen dazu.

**Comment by wrcg** [comment]
Ein weiteres Aufklappmenü für die "Quicklinks" wäre aus meiner Sicht tatsächlich sinnvoll (siehe auch https://www.uni-greifswald.de/). Zu überlegen wäre dann, mit welchem Text/Symbol das Menü angezeigt wird.

**Comment by xwolfde** [comment]
Wo soll das bei Greifswald sein?
![2017-09-27-10-45-www uni-greifswald de](https://user-images.githubusercontent.com/1070669/30904055-0f4f3c08-a371-11e7-9a2b-d9db7b55f08e.png)

**Comment by wrcg** [comment]
oben bei "Wegweiser" (Kompassnadel-Symbol)- dort sind zumindest die Zielgruppen erwähnt. Bei uns würde ich da auf  jeden Fall noch die Fakultäten reinpacken.

**Comment by wrkb** [comment]
Du meinst den Wegweiser? Find ich auch gut, andere Unis haben die Zielgruppennavi auch auf dem Desktop) ausgelagert.

Name müssen wir mal überlegen - auf keinen Fall Quick links oder Quick navi oder so, Schnelleinstieg ist oll. Letztendlich sind es die wichtigsten und die meistgeklickten Links auf Start... Das muss in ein Wort übersetzt werden. Melden uns.

**Comment by xwolfde** [comment]
Wir sollten -gerade bei Mobildarstellung- die Primässe in Vordergrund lassen: Weniger ist mehr.
Wir können zwar viele Bedienicons hinzufügen, aber das verwirrt.

Wir haben bei einer mehrsprachigen Site jetzt bereits folgende Pflichtelemente:
- Hamburger
- Suche
- Sprachschalter
- FAU-Link
- Titel der eigenen Site (der lang werden kann und auch die hälfte des Bildschirmes einnehmen kann bei langen Titeln, weil ja derzeit das Logo verpönt ist)


Noch ein Bedienelement mehr macht das ganze noch viel dichter.
Und das auf jeder Seite.
Dabei ist das, was der User will dieses: Content. Der ist auf die Seite gekommen um dort was zu lesen. Nicht um fremde Websites zu besuchen.

**Comment by wrkb** [comment]
Was meinst du mit fremde Webseiten? Abgesehen vom Klinkikum und den Fakultäten sind da unsere eigenen Seiten drin? Auf den Fakultätsseiten sowieso. "Fremd" und "unser" sind aber auch keine zulässigen Kategorien, da alles FAU ist und der Nutzen für den Nutzer entscheidet. Nur nach dem wurden die Menüs gebaut (und entsprachen übrigens beim Neubau beim Relaunch ohne Abgleich fast komplett den Einstiegen der alten Seite).

Vielleicht muss es kein betextetes großes Bedienelement werden, sondern - ähnlich dem Hinweis-Haken in der Desktopversion - einfach ein Button mit ein einem deutlichen Icon. Ein Pfeil, ein Fragezeichen, ein Symobil für Links (gibt es bestimmt) - fertig. Nimmt weniger Platz weg. 

Oder man packt das ins Hamburger-Menü als ersten Punkt, vielleicht invertiert oder hervorgehoben.

Was meinst du?

**Comment by xwolfde** [comment]
Mit "Fremd" meine ich aus Usersicht jede Website, die von der aktuell besuchten Website weg und auf eine andere führt. Für uns von der FAU sind die anderen Webauftritte natürlich nicht fremd.

**Comment by xwolfde** [comment]
Ich würde jetzt erstmal noch abwarten: Wenn wir in der Version 1.9 dann die Orga-Breadcrumb einführen müssen, dann müssen uns eh ein weiteres Element überlegen.  Das heisst, alles was wir uns jetzt dazu druchgrübeln, wird dann wieder hinfällig

**Comment by wrkb** [comment]
Ja, dann lieber warten

**Comment by xwolfde** [comment]
Hab den Issue in den 1.9er Milestone verschoben
