### ISSUE TITLE
Logo-Slider

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#298]
> Zu viel Abstand zwischen den einzelnen Bildern (horizontal)

Ref https://github.com/RRZE-Webteam/FAU-Einrichtungen/issues/276#issuecomment-331450111

@lagerlit
Kannst du das bitte genauer beschreiben? ggf. anhand von Screenshots?

**Comment by lagerlit** [comment]
Klaro: ![logo-slider](https://user-images.githubusercontent.com/9449835/30812548-5468aab6-a20b-11e7-9750-c733dfd1caa0.JPG)

**Comment by xwolfde** [comment]
zu "viel" Abstand?  Also da würde ich keinen kleineren Abstand nehmen wollen...

**Comment by xwolfde** [comment]
Nope.
Da ist kein Unterschied vorhanden zwischen alt und neu:

Beta:
![beta-bildslider](https://user-images.githubusercontent.com/1070669/30974911-29ee101a-a471-11e7-964b-fac5b2d91a49.jpg)

FAU.de:
![fau-bildslider](https://user-images.githubusercontent.com/1070669/30974918-2f582cac-a471-11e7-94f0-2d616e779028.jpg)

In beiden Fällen nehmen die Bilder inkl. der Randabstände jeweils 156px ein.
