### ISSUE TITLE
Meta-Navigation oben IDs und CSS

### ISSUE THREAD

**Issue by uliried** [RRZE-Webteam/FAU-Einrichtungen#3]
Im FAU-Theme haben die einzelnen Links der Meta-Navigation oben eigene IDs. Im Theme Einrichtungen ist das nicht der Fall - Absicht?
Es kann den einzelnen Links auch keine Klasse zugeordnet werden. Trotz Angabe einer Klasse "infodesk" im Backend 
![css](https://cloud.githubusercontent.com/assets/8255127/10883994/d892915c-8175-11e5-9e32-94e2d5f327e9.png)
erscheint diese nicht im Code der Seite
![class](https://cloud.githubusercontent.com/assets/8255127/10884006/e99f69fc-8175-11e5-9860-083aa38f2f38.png)

**Comment by xwolfde** [comment]
ja, ist absicht. was sollte denn passieren, wenn ene neue klasse die das theme nicht kennt, eingegeben wird?

**Comment by uliried** [comment]
Für die Verwendung des Theme in der CM-Instanz des RRZE ist das sicher richtig, da kommt man an das CSS nicht ran. Bei der Verwendung "in freier Wildbahn" wäre es halt hilfreich, wenn man z.B. einen einzelnen Link farblich hervorheben möchte.Kann man dann aber auch selber noch einbauen.

**Comment by xwolfde** [comment]
ist in der nächsten verison drin
