### ISSUE TITLE
Mehr Default-Logos

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#30]
Prüfen, ob und welche weiteren Logos für Anpassen denkbar und nützlich wären.

**Comment by xwolfde** [comment]
Sollte man dabei nochmal das Thema "Englische Logos" angehen?

**Comment by AstridSemm** [comment]
Im Prinzip ja; gibst du mal Beispiele, welche Logos du meinst?

**Comment by xwolfde** [comment]
Referenz zu #81

**Comment by xwolfde** [comment]
Fachbereichslogos der RW einfügen.

**Comment by xwolfde** [comment]
Logos aus RW drin. Müssen aber noch sacken lassen, wie wir es richtig machen. Dringlichkeit abhängig von Bedarf und ENtwicklung
