### ISSUE TITLE
Buttons linkszentriert

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#302]
Ref #https://github.com/RRZE-Webteam/FAU-Einrichtungen/issues/276#issuecomment-331452037
@lagerlit

Bitte genauer sagen, was du meinst? Screenshot?

**Comment by lagerlit** [comment]
Voila Screenshot: 
![abo-button](https://user-images.githubusercontent.com/9449835/30814256-f038d098-a20f-11e7-8b90-21ecdc1c0634.JPG)

**Comment by xwolfde** [comment]
Das ist ein falscher Bug. Da hättest du mich fast in die Irre geführt :)

Der Margin links ist bereits vorher da gewesen und begründet sich aus der Anzeige der Termine:
![2017-09-27-14-12-test8 tindu rrze uni-erlangen de](https://user-images.githubusercontent.com/1070669/30912744-0d21412a-a38e-11e7-8dcc-e0332d34404b.png)

Was hier allerdings falsch ist, ist der nicht vorhandene Margin vor der Meldung "Keine bevorstehenden Termine"

**Comment by xwolfde** [comment]
Ich finde gerade kein Testcase. Hast du ein validen Terminfeed ohne kommende Inhalte?

**Comment by xwolfde** [comment]
Gefunden. War an der Stelle schon immer so, ist aber bislang nicht aufgefallen.
Kann derzeit nicht im Theme gelöst werden.
