### ISSUE TITLE
Videos

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#303]
Ref: https://github.com/RRZE-Webteam/FAU-Einrichtungen/issues/276#issuecomment-331452037
@lagerlit

> 
> Automatische Überschrift über Video, das mit shortcode eingebunden ist, zu groß https://www.beta.wordpress.rrze.fau.de/plugins/seite-mit-video-und-galerie/
> geht Video zentrieren? Ich weiß nicht, was ich im Shortcode verändern muss
> geht Videogröße selbst bestimmen? https://www.beta.wordpress.rrze.fau.de/tests/standard-oembeds/ hier zu klein (youtube und videoportal)

Betrifft Video-Plugin.
Zentrieren geht über CSS-Klassen alignleft, alignright, aligncenter.

**Comment by xwolfde** [comment]
Ref https://github.com/RRZE-Webteam/FAU-Einrichtungen/issues/276#issuecomment-331467374 

@wrbk: "Videos im Social-Media-Footer: Wollte ich testen, kam nicht weiter via Widget. Wenn ich weiß wie, pack ich da 3 Videos aus video.fau.de rein."

Doku ergänzen @bmehler

**Comment by wrkb** [comment]
Doku wäre gut, auch was das Zentrieren angeht - wir haben es nämlich nicht verstanden :)

**Comment by xwolfde** [comment]
wie bei bildern:

&lt;div class="alignright"&gt; ..&lt;/div&gt;
&lt;div class="aligncenter"&gt; ..&lt;/div&gt;
&lt;div class="alignleft"&gt; ..&lt;/div&gt;

drumherum.

Gab es schon.... immer für alle Blocksätze (!). Nicht zu verwechseln mit der Absatzausrichtung von Text.
Dies geht nicht via WYSIWYG-Editor.
Das wäre momentan auch nicht günstig, da diese Methode sehr wahrscheinlich zu Verwirrung führen würde,, welche Art Ausrichtungsfunktion man nehmen soll.
Normale Autoren sollen aber nicht hin- und herausrichten. Da normale AUtoren die Mehrheit sind und nur wenige Leute diese Funktion wirklich brauchen und diese dann hoffentlich fitter sind, sollten diese auch das HTML können.

Ich möchte daher lieber keine entsprechende Funktion für den WYSIWYG aufnehmen (den könnte man als Admin aber auch selbst ergänzen). Wohl aber kann man dies mal dokumentieren in der WordPress-Doku von uns. Am Besten auch in der dortigen FAQ.
@AstridSemm

**Comment by xwolfde** [comment]
Überschrifttyp kann mEn beim Shortcode angegeben werden. Die h2-Größe ist überall im Content gleich und kann nicht nur weil darauf ein Video folgt nun einfach kleiner gemacht werden .

**Comment by xwolfde** [comment]
@AstridSemm Kannst du das bitte in der Doku ergänzen? Das fehlt hier noch
https://www.wordpress.rrze.fau.de/plugins/rrze-video/

**Comment by Albager** [comment]
...betrifft die Videoübersicht für Videos aus der Videothek (https://geographie.cms.rrze.uni-erlangen.de/video/)

Wenn ich über dieses Menü zum Beispiel die "Video-Anhangseite" https://geographie.cms.rrze.uni-erlangen.de/video/wie-entstehen-unterschiedliche-stadtviertel/ auswähle, erscheint nichts im content.

Ist dieser Fehler bereits bekannt? (getestet mit Chrome)

**Comment by xwolfde** [comment]
Uh, die Videos sollten gar keinen eigenen Endpoint /video haben. @bmehler 
Aber andererseits wäre das vielleicht gar nicht so schlecht, eine Indexliste und eigene pages dazu zu haben.

**Comment by xwolfde** [comment]
Hab das Issue in zwei Issues an der richtigen Stelle verschoben. Bitte dort weiter.
