### ISSUE TITLE
Portalmenüs

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#304]
Ref https://github.com/RRZE-Webteam/FAU-Einrichtungen/issues/276#issuecomment-331470562
@wrkb

> Boxenanzahl pro Zeile ändert sich mit Beta und ändert die ganze Menülogik.

Bislang: 4er-Teiler, maximal 8 Boxen (so ists vom Designer gedacht), minimal 2 (bzw. mehr als die Hälfte horizontal gefüllt). War auf Stimmigkeit und Übersichtlichkeit getrimmt - beides ist leider verschwunden.
Neu: 5er Teiler

8 Boxen sieht nicht mehr gut aus: https://www.beta.wordpress.rrze.fau.de/tests/ - mit Links, und https://www.beta.wordpress.rrze.fau.de/theme-shortcodes/ - ohne Links.

2 Boxen sind als Minimum nicht mehr zumutbar eigentlich: https://www.beta.wordpress.rrze.fau.de/bilder/ (Hier müssten wir komplette Seitenbereiche umbauen, weil wir ja nicht mal eben die nötige dritte Box erfinden können).

Entweder zurück zu 4er-Teilung, aber hier müsste man sehen, ob das Vergrößern der Boxen/Bilder hilft oder eher eine zentrierte Einrückung (das wäre die Rückkehr zur alten Spalte).

Oder eine harmonische andere Anordnung finden, wobei das Minima und Maxima aus dem ursprünglichen Design zu beachten sind, die als inhaltsabhängiger Status quo nicht einfach aufgelöst werden können (betrifft alle Nutzer).

**Comment by xwolfde** [comment]
Anmerkung:
" (so ists vom Designer gedacht)"

Da dies das zweite mal ist, wo auf Designkonzept verwiesen wurde, wo mir aber nicht bekannt war, dass an der Stelle irgendwas definiert war: Wo finde ich das und weitere Gedanken? Wir können nur das berücksichtigen, was bekannt /nachlesbar ist.

**Comment by xwolfde** [comment]
Ref #309

**Comment by wrkb** [comment]
Liefern wir :)

**Comment by Silsa** [comment]
Es müsste bei der bisherigen, harmonischen Aufteilung von 4/8 bleiben. So war das Urdesign nicht umsonst gedacht. Und das reicht mE als Referenz und ist ja auch allen hier bekannt.
Die jetzige Lösung ist gestalterisch extrem unvorteilhaft. 

Zudem achten wir bei uns sehr auf diese Aufteilung und auch bei uns müssten sehr viele Bilder neu geschnitten werden.

**Comment by xwolfde** [comment]
Machen wir so.
Durch Hochsetzen des Breakpoints wird die große Darstellung eh nicht mehr auftreten.
Trotzdem prüfen.

**Comment by xwolfde** [comment]
Notiz Self zur späteren Doku: 
* Die Boxen haben eine Breite von 220px.
* Das Image nimmt die 220px voll ein und ist 110 hoch.
* Die erste Box in der SPalte ist ausgerichtet an der Fluchtlinie des Containers und hat ein Margin left 15;  Alle anderen Boxen haben 20px Abstand nach links zur vorherigen Box.

Vorher hab es ein Bug, dass die Fluchtlinie um 5 px verpasst wurde, da auch der ersten Box ein Margin 20 gegeben wurde.  Dadurch waren alle um 5 px nach rechts verschoben. Dies ist bislang nicht aufgefallen.

Neues CSS Grid-System (Flex) kann an der Stelle noch nicht so verwendet werden, daher wird mit nth-of-type gearbeitet um saubere Umbrüche zu erhalten. Geht bis 6 Zeilen.

Gesamte Breite nimmt exakt 970 = Containerbreite ein.
Probleme: 
* Es wird die gesamte Breite des Contents benötigt. Menu links oder Sidebar rechts geht nicht.
* Kleinere Auflösungen verlangen weniger Boxen.

**Comment by xwolfde** [comment]
fixed
