### ISSUE TITLE
Besondere Links - Größen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#305]
> Der Spaltenlauf im blauen Bereich mit den zentralen Links unter der Bühne wurde bereits bemängelt. Mir ist hier die Schrift im Vergleich auch zu klein - hier sollte beides angepasst werden.
Auch betroffen: Alle ähnlich kleinen Link-Schriften - z.B. im Portalmenü unten. (Das so übrigens mit Links auch auf der FAU-Startseite kommen könnten)

ref: https://github.com/RRZE-Webteam/FAU-Einrichtungen/issues/276#issuecomment-331470562
@wrkb

**Comment by xwolfde** [comment]
Die Schriftgröße hat sich an der Stelle nicht verändert und blieb jeweils bei 13px/(0.8125rem auf 16px base)...

Können wir aber gern vergrößern...
Allerdings ist die Größe in den Quicklinks identisch mit der vond en Links in der Meta und der   Breadcrumb.
Eine Vergrößerung würde daher auch dort notwendig sein.

Ich würde empfehlen es so zu lassen, da wir nicht zu viele verschiedenen Schriftgrößen habens ollten.

**Comment by wrkb** [comment]
Ich weiß nicht, welche Klassen dahinter stecken, aber Lesbarkeit geht doch über die Funktion hinter der Schrift, also ob es ein Link ist etwa. Sprich: Die Links oben vergrößern und ggf. in den Portalmenüs, aber die im Footer unten nicht, sollte okay sein, da nictht das Element Link einheitlich sein muss, sondern die Schrift, die man liest.

Zu viele Schriftgrößen will keiner, aber hätten wir damit ja auch nicht.

**Comment by xwolfde** [comment]
Works for me.
