### ISSUE TITLE
Social-Media-Footer

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#306]
Ref https://github.com/RRZE-Webteam/FAU-Einrichtungen/issues/276#issuecomment-331474647
@wrkb

Anmerkung: Keine Änderung zur Vorversion. Diese Darstellung war schon 1 Jahrlang so  :=P
Sieht man natürlich nur, WENN man a) Social Media Icons a hat UND keine Video-Widgets.
Daher keine Einstufung als Bug, sondern als Diskussion.

**Comment by wrkb** [comment]
Dachte ich mir, gerne diskutieren, wenn Interesse. fau.de ist am wenigsten betroffen dank vieler SM-Plattformen.

**Comment by xwolfde** [comment]
Würde ich jetzt erstmal schließen, da keine Änderung zu vorher, es aber schon in dem Issue #270 Überlegungen gibt, den Social Media Footer nochmal anzugehen.
