### ISSUE TITLE
Suchfeld Widget

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#307]
Ref https://github.com/RRZE-Webteam/FAU-Einrichtungen/issues/276#issuecomment-331476401
@wrkb 

Die Suchfelder waren vorher ungleichmässig und je nach Kontext verschieden. Siehe auch selbst das Bild.
Bei Usern mit 1x vergrößerter Schrift hat zudem die vorherige Version das Suchfeld in der Sidebar zu einem Umbruch geführt, der das Submit-Button auf die nächste Zeile brachte.

Ggf. wäre es aber tatsächlich sinnvoll den Button tatsächlich wieder invers zu machen, wenn die Suche in der Sidebar eingeblendet wird.

Werte ich als Diskussion?

**Comment by wrkb** [comment]
Ja, ist ein Nebenschauplatz, ganz am Schluss mit anschauen.

**Comment by xwolfde** [comment]
Wiederkehrende gleiche Elemente/Funktionen sollten gleich sein.
Ich würde es jetzt lieber so versuchen; Sollte sich diese Korrektur (den vorher war es IMHO kaputt - insbesondere in der Sidebar) als nicht optimal erweisen, können wir das gern wieder umstellen.
