### ISSUE TITLE
Doku: Benennung der Bereiche 

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#310]
In der Doku zum Theme müssen unbedingt die Bereiche des Themes/der Webseite klar benannt werden.
Es ist sehr irritierend, wenn die Namen der Bereiche falsch verwendet werden.
(header, meta, hero, footer, sidebar, navbar, ...)

**Comment by xwolfde** [comment]
Header = Gesamter Bereich oben.
Dieser enthält: 
- Metanav (graue Linie oben)
- Branding    
- Hauptmenu
- Hero-Bereich


Die Meta-Nav enthält die Bereiche
- FAU-Link
- Metanav-Menu
- Suche
- Optional Sprachschalter
- Optional Hamburger

Der Hero-Bereich enthält optional:
- Slider (nur Startseiten)
- Quicklinks  (nur Startseiten)
- Breadcrumb (Unterseiten)
- Angepasste Breedcrumb (Spezialseiten 404, 403, Archive)


Content:
Bereiche unterhalb Header

Enthält:
- Subnav optional
- Sidebar Inline optional
- Main Content Bereich
- Sidebar rechts optional bei Startseite und Blogroll
- Portalmenus (templateabhängig, optional)
- Logoslider  (templateabhängig, optional)
- Werbebanner (templateabhängig, optional)

- Social Media Leiste (optional) *(soll in Footer wandern)



Footer
Unterhalb Content

Enthält:
- FAU-Branding
- Adressbereich
- Footer-Menu

**Comment by AstridSemm** [comment]
So, jetzt wird's lustig. Im Customizer heißt "Branding" nämlich einerseits Website-Informationen, andererseits Header-Bild.  Der Hero-Bereich für die Fakultäten heißt seit Ewigkeiten "Bühne", für die Lehrstühle "Banner", was die Startseiten anbelangt. Für die Unterseiten gab's da noch nie eine Bezeichnung. 
"Subnav" war schon immer die Navigation auf den Unterseiten mit Navi, Sidebar Inline Optional war auch schon immer einfach die Sidebar. Main Content Bereich versteht auch keine Sau, das ist der Inhaltsbereich (schon immer gewesen, aber im Handbuch nicht weiter beschrieben, richtig). Sidebar rechts optional bei Startseite und Blogroll war auch schon immer die Sidebar, die Portalmenüs sind so bezeichnet, den Logoslider kennt auch keine Sau, das sind die Bildlinks, Werbebanner nutzt keine Sau (kann ich aber dokumentieren; nur: warum Leute auf blöde Ideen bringen?), Social Media Leiste heißt seit Ewigkeiten Social Media Footer, der Footer ist der Einfachheit halber mit Metanavigation unten bezeichnet, kann ich auch noch ändern, wenn's sein muss.
Ich bin sehr dafür, Dokumentationen grundsätzlich "für Dummies" zu schreiben und mit möglichst wenig Spezialzeugs um mich zu werfen. Insofern konkret die Frage: Was soll ich ändern/neu machen? Oder kann das warten, bis die Theme Options im Customizer sind, damit ich das in einer Rutsche neu machen kann?

**Comment by xwolfde** [comment]
Dieser Teil ist aber für Entwickler gedacht. Die Bezeichnungen kommen aus dem Classnames.
Für normale Autoren reicht es, wenn wir die 4 bereiche "Kopfteil, Fußteil, Hauptteil und Sidebar" bezeichnen.
Von Entwicklern oder Designern, die an der Entwicklung aktiv teilhaben wollen, erwarte und fordere ich die notwendigen Grundkenntnisse die Bereiche aus den Classnamen auszulesen und richtig einzuordnen.

**Comment by AstridSemm** [comment]
Gut, soweit verstanden. Aber: Die Doku (also wordpress.rrze.fau.de) richtet sich ja ausschließlich an Anwender. Soll das wirklich dort rein oder ist es nicht vernünftiger, für Entwickler was eigenes zu haben?

**Comment by xwolfde** [comment]
Ich wollte für Entwickler einen Teil unter beta.wordpress. machen (Im Menü unter Dev)

**Comment by AstridSemm** [comment]
Ach, das bedeutet, dass ich gar nicht gemeint war! *gnaaaaah* Heute ist definitiv nicht mein Tag.

**Comment by xwolfde** [comment]
Dafür hast du einen netten neuen Avatar. Das ist doch auch was :)

**Comment by xwolfde** [comment]
Ausgelagert auf Entwicklerungswebauftritt
