### ISSUE TITLE
Sidebar-Formatierung der Kontakte nicht einheitlich

### ISSUE THREAD

**Issue by endv02** [RRZE-Webteam/FAU-Einrichtungen#315]
über den Shortcode format="sidebar" gibt es eine andere Ausgabe als über Ansprechpartner. Beispiel: 
https://www.beta.wordpress.rrze.fau.de/plugins/personen-shortcodes/seite-mit-kontakten-und-sidebar-rechts/

**Comment by xwolfde** [comment]
Und was ist da jetzt der Fehler?
