### ISSUE TITLE
Standard-Kontakt in Accordion ohne Rahmen und evtl. zu schmal

### ISSUE THREAD

**Issue by endv02** [RRZE-Webteam/FAU-Einrichtungen#316]
Soll das so sein oder nicht? Keine Ahnung:
https://www.beta.wordpress.rrze.fau.de/plugins/accordion-und-personen/
beim Accordion stayopen ist das Standard-Personenformat eingebunden, beim Accordion Phil.Fak. das kompakt-Format

**Comment by xwolfde** [comment]
Sieht IMHO alles richtig aus?
