### ISSUE TITLE
Spanische Sprachdatei fertigstellen und verteilen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#33]
ist bereits angefangen von  @AstridSemm  
Wenn fertig, dann auch bei den anderen Themes reinkopieren.

**Comment by AstridSemm** [comment]
Übersetzung ist erledigt; ich fände es trotzdem gut, wenn Rolf noch drüberlesen könnte, sicherheitshalber.

**Comment by xwolfde** [comment]
Danke. Sollen wir dann auf Rolf warten, oder trotzdem es im nächsten Update einfach so reintun?

Beispielkunde wird hier das BAYLAT sein (http://www.baylat.org/). Die sind noch nicht umgestellt
und basierend noch auf selbst entwickelten "Zeug".
Wollen wir auf die zugehen? Nach der Techfak?

**Comment by AstridSemm** [comment]
Ja, kann rein.

**Comment by AstridSemm** [comment]
Und ja, bitte gern auf BAYLAT zugehen.

**Comment by xwolfde** [comment]
im dev 1.5  branch eingecheckt

**Comment by xwolfde** [comment]
Bitte nochmal auf test8.tindu alle Sprachen durchgehen. Es haben sich zusätzliche Lines of Code/Änderungen ergeben.  Englisch_UK und Spanish reicht

**Comment by AstridSemm** [comment]
Rolf hat bei der Durchsicht der spanischen Version festgestellt, dass da noch einiges fehlt; wir arbeiten jetzt mal mit anderen Tools und sehen, ob wir so alles erschlagen bekommen. Sollte das gut funktionieren, gibt's dasselbe für Englisch.

**Comment by xwolfde** [comment]
In der Version gestern ist die aktuellste Sprachdatei drin
