### ISSUE TITLE
Problemsammler Release Kandidat 1.8

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#334]
Bitte hier alle Probleme, welche der neue Release Kandidat aufweist, vermerken.
**Alle** gemeldeten Probleme aus dem ersten Testlauf (Vgl: #276 ). sind gelöst. Wesentliche Kritikpunkte und Fehler sind bereinigt worden. 

Der neue Release Kandidat ist ab sofort unter https://www.beta.wordpress.rrze.fau.de/ aufrufbar.

(Bitte unbedingt darauf achten, vor dem Tests die jeweiligen Browsercaches zu löschen. )

Wenn es größere Sache sind, bitte als eigene Issues anlegen. 
Stets hilfreich auch immer: Screenshots und Angabe des Browsers, ob man denselben Effekt auch mit anderen Browsern hat und Angabe auf welcher Auflösung/Endgerät das Problem auftrat..

**Tests und Rückmeldungen bitte bis spätestens 8.10., 23:59 Uhr. Geplanter Rollout: 9.10. (+x für Bugfixing) für FAU Einrichtungstheme; Fakultätsthemes ab dem 10.10.**

Eine Gesamtübersicht der Änderungen und der neuen Features kann derzeit nur der Änderungsgeschichte und der geschlossenen Issues abgerufen werden; Eine prosaische Zusammenfassung wird jedoch kommen.

**Comment by wrkb** [comment]
Hier Feedback Webredaktion fau.de:

1. Abschnitt Blocker, danach gesammelt weitere Meldungen im 2. Abschnitt, im 3. Abschnitt Meldungen mit Screenshots

# Blocker

**Textgröße** (Desktop) ist größer als bisher auf fau.de (1 rem vs. 14px) - Firefox und Chrome

**Absatz** <p> horizontaler Abstand zwischen Textzeilen zu groß - line-height raufsetzen 1.5rem/1.6rem – wenn kein Konflikt mit Textgrößenproblem (siehe oben)

**Bühne:** Text unschön. Bsp bei Ehrenamt-Meldung (Slide 4):  Subhead sollte kürzer sein – siehe Screenshots. Schrift zu groß und mit zu viel Abstand zur nächsten Zeile.
Horizontaler Abstand zwischen den Text Zeilen (jeweils innerhalb Head und Subhead) verringern
Breite der Textfelder (Head und Subhead) – Head muss länger laufen dürfen als Subhead (bzw. Subhead kürzer als Head). Schätzung: 60 bis 80 % (wie es vorher aussah)

**Veranstaltungen/Terminliste**: Schriftart zu groß, Kalenderblätter zu hoch (muss wieder zurück zum alten Aussehen)

**Kontaktplugin:** Kurzbeschreibung und Kurzauszug war bisher kleiner: 0.8/0.9rem, bitte zurück zu vorher. Erschlägt einen so, wie es jetzt ist.

**Comment by wrkb** [comment]
# Sammelmeldung
**Topveranstaltung**: Bild ist zu klein, padding kleiner machen, Schrift ist zu groß

**Portalmenü**: neue Shortcodes erlauben Änderungen des ganzen CD - Menü vor Content oben, Content unter Menü…, bislang bewusst nicht vorgesehen... zurückstellen und diskutieren! **_Muss ins Designgremium!_**
https://www.beta.wordpress.rrze.fau.de/theme-shortcodes/shortcode-portalmenu/

**Footer-Menü** rechte Meta (Kontakt/Impressum): Wieder rechtsbündig statt linksbündig 

Text der **Listenpunkte** war bisher immer gleich groß zu Textgröße in <p>, also jetzt 1rem

**Bildergalerie**: Pfeilchen funktionieren nicht bzw. ausblenden, wenn zuwenig Bilder

**RSS-Feed Auszug**: font-size in px angegeben, nicht in rem

**Videos zentrieren:** funktioniert nicht – wie genau geht das – per div-Angaben?

**Seite mit Weiterlesen-Marker** – haben wir nicht verstanden – wofür und wie funktionierts?

In **Meldung: Bild zentrieren** funktioniert noch nicht (nur BU ist zentriert, Bild bleibt liks) https://www.beta.wordpress.rrze.fau.de/2017/09/14/mein-ehrenamt-laesst-andere-die-schoenheit-unseres-universums-erkennen/

**In Meldung: Schriftart** unter den Bildunterschriften unter den Bildern, die NICHT als Artikelbild eingefügt werden zu klein und mit zu viel Abstand (Vgl. Artikelbild) https://www.beta.wordpress.rrze.fau.de/2017/09/14/mein-ehrenamt-laesst-andere-die-schoenheit-unseres-universums-erkennen/ 

**Blogsuche**:

Sucht in allen Inhalten, nicht nur Meldungen. Vor-Einschränken!
Optisch differenzieren von normalem Suchfeld – zurück zu altem Design, Verbesserung des Such-CD im Redesign 2018
Vorfilterung (nur in Nachrichten suchen) reparieren (geht in Beta nicht)

**Blockquote**: Anführungszeichen müssen IMMER vorhanden sein und IMMER links vom Text (Einführung wie bei normaler Nutzung, Duden etc.). https://www.beta.wordpress.rrze.fau.de/texte/blockquotes-und-zitate/

**Überschriften**: Überschrift 1 und 2 darf nicht größer/fetter als h1 im blauen Bereich sein https://www.beta.wordpress.rrze.fau.de/texte/ueberschriften
Verstößt zwar sowieso gegen CD auf normalen Seiten (jenseits von landing pages), aber Größe muss nicht auch noch abweichen (z.B. auf landing pages).

**Video**: Wenn Video klein ist, ist Headline dreispaltig -  unschön (besser: Schriftgröße passt sich mit an?) https://www.beta.wordpress.rrze.fau.de/plugins/seite-mit-video-und-galerie/ 
Dazu: Titel des Upoaders aus Videoportal entspricht nicht automatisch dem Titel, den wir vergeben wollen.
Lösungsvorschlag: Überschrift muss ausstellbar sein, wird dann manuell durch h3 ersetzt. (Schon möglich? dann ist das hier hinfällig)

**Comment by wrkb** [comment]
**3-Spaltigkeit** bei Mobilversion aufgeben! Ist unlesbar Chrome

![3-spaltigkeit](https://user-images.githubusercontent.com/9445370/31281234-22e6ffb8-aaaf-11e7-82a3-885dc0dbe612.PNG)

Personenvisitenkarte  mobil Kontaktbild und Text ist abgeschnitten Chrome

![personenvisitenkarte](https://user-images.githubusercontent.com/9445370/31281252-2b197378-aaaf-11e7-8095-ca5efea5c323.PNG)

**Comment by wrkb** [comment]
Erstes Posting oben um Frage zu IE und Frontmotion und Hinweise zu Browsern ergänzt.

**Comment by xwolfde** [comment]
Danke.
Ich kann die obige erste Meldung aber nicht als Blocker anerkennen: Denn weder ist der Betrieb von Webseiten gestört noch wird verhindert, dass Menschen und Software die Inhalte der Webseite auslesen. Ein Blocker sollte etwas sein, was wirklich richtig Dinge so kaputt macht, dass man keine Inhalte mehr aufrufen kann. Nicht Dinge, die nur subjektiv und diskutabel sind.

Was unter der Definition tatsächlich ein Blocker ist, ist das Screenshot mit den abgeschnittenen Text bei Handy. Bitte hier mal genau angeben welche Seite das war.


Die Vorschläge:

_"Textgröße (Desktop) ist größer als bisher auf fau.de (1 rem vs. 14px) - Firefox und Chrome
Absatz
horizontaler Abstand zwischen Textzeilen zu groß - line-height raufsetzen 1.5rem/1.6rem – wenn kein Konflikt mit Textgrößenproblem (siehe oben)"_

muss ich beide als Blocker ablehnen.

**Der angegebene Screenshot kommt nicht von Beta und ist offensichtlich (dies erkennt man am Anschnitt des Siegels) nicht auf der aktuellen Beta-Version.**
 

Es ist korrekt, dass es vorher anders war. Es ist aber leider so, dass vorher die "Berechnung" der Schriftgröße zu Schriftzeilenhöhe nicht existierte, sondern dass hier aus dem Bauch heraus Werte vorgegeben waren. Diese Werten waren zum großen Teil willkürlich.
Die neue Version beruht bei der Schriftgröße auf aktuelle und berechenbare Methode aus dem professionellen Webdesign. Die Zeilenhöhe ist dabei jeweils abhängig von der Schriftgröße zu setzen.
Die Schriftgröße selbst in der Steigerung von vorher 14px auf nunmehr 16px Base = 1rem entspricht der Standardgröße der Darstellung der  auf modernen Websites, so wie es sich ebenfalls im Webdesign + Usability als State of the art erwiesen hat.
Gern können wir aber im Rahmen eines Tests sehen, ob das neue besser ankommt als das Alte.


Der Issue-Text:
_"Bühne: Text unschön. Bsp bei Ehrenamt-Meldung (Slide 4): Subhead sollte kürzer sein – siehe Screenshots. Schrift zu groß und mit zu viel Abstand zur nächsten Zeile.
Horizontaler Abstand zwischen den Text Zeilen (jeweils innerhalb Head und Subhead) verringern
Breite der Textfelder (Head und Subhead) – Head muss länger laufen dürfen als Subhead (bzw. Subhead kürzer als Head). Schätzung: 60 bis 80 % (wie es vorher aussah)"_

ist teilweise sinnfrei, da die beschriebenen Texte und damit deren Länge in der Hand der Redakteure liegen. Wenn der Text kürzer sein soll, dann schreibt man kürzeren Text.

Über Abstände und verfügbare Maximalbreiten der jeweiligen Bereich kann man aber reden.

**Comment by wrkb** [comment]
@xwolfde schreibst du das noch an die Runde des Designgremiums? Nicht jeder hat Zeit, jede Github-Antwort zu lesen und für solche wichtigen Diskussionen gibt es die Mailingrunde ja.

**Comment by xwolfde** [comment]
"3-Spaltigkeit bei Mobilversion aufgeben! Ist unlesbar Chrome"

Bitte Manual zu Bootstrap Grid lesen oder die Spalten-Shortcodes verwenden! 
https://getbootstrap.com/docs/3.3/examples/grid/

col-xs-* ist genau die Angabe für kleine Auflösung (xs). Du hast durch nutzen von col-xs-* gerade angegeben, dass es auf xs-Auflösung bei 3/12 gespaltet werden soll.
Der Code tut also genau das was es soll.  

Was du wolltest wäre das gewesen:
&gt;div class="col-xs-12 col-sm-3"&lt;
Dann wäre bei einer Auflösung von xs- der Bereich über den 12er Grid gegangen, aber ab sm-Auflösung auf 3/12.

**Comment by xwolfde** [comment]
> _**Topveranstaltung: Bild ist zu klein, padding kleiner machen, Schrift ist zu groß**_

Hast recht. Da ist ein Bug beim Bild. Und die Schriftfarbe ist ja das blau?
Ok, kommt auf Liste.

> _Portalmenü: neue Shortcodes erlauben Änderungen des ganzen CD - Menü vor Content oben, Content unter Menü…, bislang bewusst nicht vorgesehen... zurückstellen und diskutieren! Muss ins Designgremium!_


Wurde auch bereits auf ausdrücklichen Wunsch vom CIO im CRIS Plugin eingesetzt bei dem Import und der Darstellung von Forschungsprojekten und ist unverzichtbar um weitere Kunden zu gewinnen. 
War auch übrigens seit einem halben Jahr in dem Issue https://github.com/RRZE-Webteam/FAU-Einrichtungen/issues/227 und wurde von dir begrüßt: Zitat: "Als zusätzliche Option aber sehr wünschenswert (wir haben da schon einen Anwendungsfalls) :)"
Das der Issue ein halbes Jahr lang unkommentiert war, darin begrüßt wurde, längst in anderer Form auch umgesetzt wurde aber jetzt plötzlich ein Problem sein soll, verwundert.

> _Footer-Menü rechte Meta (Kontakt/Impressum): Wieder rechtsbündig statt linksbündig_


Ok, kommt auf Liste.

> _Text der Listenpunkte war bisher immer gleich groß zu Textgröße_ 


Ok, kommt auf Liste.

> _Bildergalerie: Pfeilchen funktionieren nicht bzw. ausblenden, wenn zuwenig Bilder_


Ok, kommt auf Liste.

> RSS-Feed Auszug: font-size in px angegeben, nicht in rem

Wo ist das zu sehen?

> Videos zentrieren: funktioniert nicht – wie genau geht das – per div-Angaben?

Hab ich in dem dazugehörigen Issue ausführlich geschrieben. Bitte da nachlesen oder warten bis die Manual um den Punkt ergänzt wurde. 

> Seite mit Weiterlesen-Marker – haben wir nicht verstanden – wofür und wie funktionierts?

Ist kein Wunsch/Issue für euch.
Wird benötigt für mehrseitige Artikel, die zu lang sind um sie auf einer Seite (oder auch einer langen Webseite) zu tun. Ist eigentlich gängig Praxis bei News-Seiten und Fachartikeln.
Wenn ihr es nicht versteht und nicht braucht, schadet das niemand.


> In Meldung: Bild zentrieren funktioniert noch nicht (nur BU ist zentriert, Bild bleibt liks) https://www.beta.wordpress.rrze.fau.de/2017/09/14/mein-ehrenamt-laesst-andere-die-schoenheit-unseres-universums-erkennen/

Bedienerfehler. Ihr habt manuell an der Größe des Bildes geändert, statt die verschiedenen möglichen Defaultgrößen zu nutzen. Verwendet die vorgegebenen und damals übrigens festgelegten Standardbildgrößen, dann funktioniert auch die Zentrierung,

Proof:
https://www.beta.wordpress.rrze.fau.de/2017/09/29/bildpositionen-im-beitrag/


> In Meldung: Schriftart unter den Bildunterschriften unter den Bildern, die NICHT als Artikelbild eingefügt werden zu klein und mit zu viel Abstand (Vgl. Artikelbild) https://www.beta.wordpress.rrze.fau.de/2017/09/14/mein-ehrenamt-laesst-andere-die-schoenheit-unseres-universums-erkennen/

Ok, kommt auf Liste.


Blogsuche:

> Sucht in allen Inhalten, nicht nur Meldungen. Vor-Einschränken!
> Vorfilterung (nur in Nachrichten suchen) reparieren (geht in Beta nicht)

Eine Vor-Einschränkung existiert bereits! Voreingestellt wird nur in Artikel und Seiten gesucht und das ist auch genauso wie bisher und soll auch so bleiben.

Die Filterung funktioniert bei mir ohne Probleme.
Suche nach "test": 47 
Nachträglich Haken weg bei Seiten: 21 Treffer


> Optisch differenzieren von normalem Suchfeld – zurück zu altem Design, Verbesserung des Such-CD im Redesign 2018

Abgelehnt. Gleichartige Elemente müssen gleichartig aussehen. Vorherige Darstellung war grob fehlerhaft. 
Für 2018 ist kein Redesign geplant. Da haben auch bekanntlich andere Dinge Priorität.


> Blockquote: Anführungszeichen müssen IMMER vorhanden sein und IMMER links vom Text (Einführung wie bei normaler Nutzung, Duden etc.). https://www.beta.wordpress.rrze.fau.de/texte/blockquotes-und-zitate/

Wie sind eine internationale Universität und Textblockzitate bestehen nicht nur aus Prosatext.
Insbesondere kann es hier auch um mathematische Formeln gehen. In diesen Fällen wären Anführungszeichen falsch.
Die Anforderungen aus der Wissenschaft sind hier eindeutig klar. Daher muss es die neuen OPTIONEN geben. Per Default sind die Anführungszeichen jedoch links.


> Überschriften: Überschrift 1 und 2 darf nicht größer/fetter als h1 im blauen Bereich sein https://www.beta.wordpress.rrze.fau.de/texte/ueberschriften


Die Überschrift ist in beiden Fällen gleich groß (je 2rem).  Bitte genauer prüfen.
Gleichwohl sollte eigentlich auch niemand eine Überschrift 1 im Text verwenden.  Für den Fall, dass dies jedoch doch notwendig sein sollte - z.B. bei Landing Pages - sollten die Überschriften nicht noch all zu unterschiedlich sein, da sie semantisch gleich bedeutet sind.


> Video: Wenn Video klein ist, ist Headline dreispaltig - unschön (besser: Schriftgröße passt sich mit an?) 

Die Überschriften haben grundsätzlich einheitliche Größen. Egal ob darunter ein Textblock oder ein Video kommt.  Wenn der Platz nicht ausreicht, weil man den Platz zu klein macht, muss die Überschrift umbrechen.

> Dazu: Titel des Upoaders aus Videoportal entspricht nicht automatisch dem Titel, den wir vergeben wollen.

Was hat das mit dem Theme zu tun?

> Lösungsvorschlag: Überschrift muss ausstellbar sein, wird dann manuell durch h3 ersetzt. (Schon möglich? dann ist das hier hinfällig)

Ja ist bereits möglich. Und noch mehr, man kann via Option angeben, ob man eine h3 oder eine andere Überschrift haben möchte.
Hat aber trotzdem nichts mit dem Theme zu tun.

**Comment by xwolfde** [comment]
Korrektur:
> Bildergalerie: Pfeilchen funktionieren nicht bzw. ausblenden, wenn zuwenig Bilder

Liegt am alten verwendet JS-Plugin. War bereits vorher so und ist nicht "neu".

**Comment by wrcg** [comment]
Danke für deine Anmerkungen und hier die Antworten auf deine Fragen:

- abgeschnittener Text bei Personenvisitenkarten ist auf folgender Seite zu sehen: https://www.beta.wordpress.rrze.fau.de/plugins/personen-shortcodes/ 
- px-Angabe bei RSS-Feed ist hier zu sehen:
https://www.beta.wordpress.rrze.fau.de/tests/komplexe-testseite/
- Bildergalerie-Pfeile: hier funktioniert's auf fau.de: https://www.fau.de/universitaet/das-ist-die-fau/veranstaltungen/schlossgartenfest/impressionen-schlossgartenfest-2017/

**Comment by xwolfde** [comment]
> Bildergalerie: Pfeilchen funktionieren nicht bzw. ausblenden, wenn zuwenig Bilder
Liegt am alten verwendet JS-Plugin. War bereits vorher so und ist nicht "neu".

> Bildergalerie-Pfeile: hier funktioniert's auf fau.de: https://www.fau.de/universitaet/das-ist-die-fau/veranstaltungen/schlossgartenfest/impressionen-schlossgartenfest-2017/

Diese Bildergalerie enthält nicht "wenige" Bilder, sondern mehrere Dutzend Bilder.

**Comment by xwolfde** [comment]
Bühne:

> Breite der Textfelder (Head und Subhead) – Head muss länger laufen dürfen als Subhead (bzw. Subhead kürzer als Head). Schätzung: 60 bis 80 % (wie es vorher aussah)

Zur Erläuterung:
Das vorherige Maß war schlicht 100% des Containers (und nicht 60% - 80% oder so).
Damit ist der Bühnentext jedoch über die Fluchtlinie der Sidebar und der Suche gekommen, **wenn** der Text mal zu lang war.  Da ihr aber eine gute Redaktion seid, habt ihr die Texte gute gemacht und so ist euch das nie passiert und nie richtig aufgefallen.
Leider ist es bei anderen Websites nicht so sorgfältig gemacht worden von den Autoren, so daß dort der ganze Bereich genutzt wurde und es da negativ auffiel.
In der Beta hatte ich daher die Breite des verfügbaren Bereiches auf die Breite des Content-Containers gesetzt (66%), so daß die Fluchtlinie der Sidebar eingehalten wurde.
Da dies Problem mit den überlangen Texten jedoch nur in wenigen Fällen negativ auffiel und dort auch eher bei den Einrichtungen, die entgegen ihrer Schulung handelten, mach ich es nun wieder 100% nach euren Wunsch.

**Comment by xwolfde** [comment]
_(VORBEMERKUNG: Ich schreibe nicht so lang um euch zu langweilen, sondern weil einige dieser Texte gleich Eingang in eine kommende Dokumentation nehmen sollen)_

Zur Erläuterung Schriftmaß:
Die Version von 2014 enthielt hardcodierte Werte bei allen Schriften für Font-Size, als auch für Line-Height. Eine Berechnung fand nicht statt. Ob die Werte tatsächlich zueinander passten war teilweise Glücksfall. Oft passte es, jedoch nicht immer.
Die Werte waren nicht in Abhängigkeit voneinander, sondern eben hardcodiert. Bei Vergrößerung der Schrift kam/kommt es daher zu Fehlern in der Darstellung, wenn die Schrift zwar vergößert, die LIne-Height jedoch bleibt. 

Was "passend" ist, kann man aus der Schriftlehre ziemlich genau berechnen. Entsprechende Literatur kann ich euch gern liefern, aber das führt jetzt zu weit; Ich denke aber ich werde in der geplanten Styleguide, die ich mit eurer Hilfe machen möchte, dazu ein paar Referenzen einfügen.
Zusammenfassend kann man aber sagen, daß die optimale Line-Height im Web gemäß den gängigen Anforderungen gleich der Schriftgröße multipliziert mit 1.46 ist.
Die seit 2012 (!) für die Darstellung auf Bildschirmen empfohlene Mindestschriftgröße für einfachen Text ist **16px** bei Nutzung der gängigen Voreinstellungen eines Standard-Browsers.
Inzwischen fand die Schriftgröße und deren Anpassbarkeit auch Eingang in die Richtlinie 1.4 des WCAG 2.

Die bisherigen hardcodierten Werte, die teilweise richtig, teilweise falsch waren, mussten daher (und auch aus Bugmeldungen - es zog sich halt immer wieder durch, dass an vielen Stellen Schriftgrößen seltsam waren) vereinheitlicht werden. Auch war die bisherige Standardschriftgröße nicht 16px, sondern im Content 15px für Absatztext.

Dazu wurde eben im Rahmen des neuen Grids ein sogenanntes Mixin (-> vgl. SASS Kurs) eingeführt, mit der die Schriftgrößen und damit die Line-Heights durchgängig korrekt berechnet werden gemäß den o.g. Richtlinien und den bekannten FontStyle-Regeln.
@wrcg war ja in dem vom RRZE finanzierten Workshop indem das SASS-Mixin auch vorgestellt wurde. 

Leider eben bedeutet dies, dass an vielen Stellen nun die Werte in der einen, wie in der anderen Richtung nun negativ auffielen. Dort nämlich wo es vorher eben hardcodiert nicht genau * 1.46 war, sondern wo die vormaligen Macher andere Werte nutzen.
Das war der Grund, warum euch das hier und dort negativ ins Auge fiel. Der Witz ist: Durch das "putzen" fallen nun natürlich Dinge auf, die nie richtig waren. Wie ja auch die willkürliche Positionierung des Siegels erst jetzt aufgefallen ist. 

In der Releaseversion werde ich dennoch die Schriftfont wieder von 16 auf 15 px reduzieren, da sich offenbar ja doch viele nun daran gewöhnt haben. 
"Korrekt" im Sinne der aktuellen Usability-Studien und der Barrierefreiheit ist dies jedoch nicht. Hier tun wir etwas, weil wir uns daran gewöhnt haben und nicht weil es für unsere Leser gut ist.
Wenn jedoch die Berechnung der Line-Heights nun durchgängig korrigiert ist, wird dieses Manko dann nicht mehr so schlimm sein. (Allerdings erhalten wir dafür auch kein AAA-Ranking beim WCAG Test.)

**Comment by wrkb** [comment]
Danke @xwolfde für die ausführlichen Einordnungen. Bei den Portalmenü-Shortcodes hatte ich tatsächlich was anderes gesagt im März - nur kann ich das gar nicht mehr zuordnen.. Mein Fehler. Allerdings: Da war auch die Rede von Text unter Portalmenüs, nicht von Portalmenüs beliebig platzieren - das erweitert das Missbrauchspotenzial deutlich. Ich nehms mit auf die Liste bei uns.

Ansonsten gibt es einige Punkte, die missverständlich sind, und über die wir nochmal sprechen müssen (nicht verbindliche Default-Bildgrößen, Blogsuche in mehr als nur Blogeinträgen, Blockquote jenseits von Zitaten... und noch einiges Weiteres). Rückmeldung folgt.

**Comment by xwolfde** [comment]
Alle Rückmeldungen sofern sinnvoll und verständlich eingearbeitet und in Kürze auf Beta.
