### ISSUE TITLE
Accordion

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Einrichtungen#339]
wenn man von einem Link in einem geöffneten Accordion auf eine weitere Seite kommt und dann mit dem Browser wieder zurück navigiert, wäre es schön, wenn der entsprechende Accordionbalken noch offen ist:-)

**Comment by xwolfde** [comment]
Kurz:
Ist leider nicht umsetzbar.

Lang:
Da der Status ob ein Accordion offen ist oder nicht, nur lokal bei deinem eigenen Browser liegt, müsste diese Information auch in eben diesen abgelegt werden.
Dies ginge mit Cookies oder bei modernen Browsern auch mit dem Local Storage.
In beiden Fällen allerdings müssten wir uns die Erlaubnis einholen, dass "wir" (eigentlich das JavaScript das auf dem Rechner des Users läuft) diese Statusinformation speichern dürfen... 
Dies würde wiederum bedeuten, daß wir den nervigen Cookie-Hinweis auf der Website einbauen müssten. Das würde wieder eine Design-Diskussion nach sich ziehen, wo und wir wir diesen Hinweis anzeigen lassen. Ähm.. nein :)
Der Aufwand des Ganzen wäre es nicht wert, sorry.
