### ISSUE TITLE
Accordion: Alle öffnen/Alle schließen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#344]
Aus Kundenrequests:
Optionalen "Schalter" ermöglichen, mit dem alle Accordions geöffnet und geschlossen werden können.
Ggf. auch über Ansteuerung über URL ermöglichen, die man dann via Suche auch ansteuern könnte um das Problem zu lösen, dass ein Suchtreffer in dem Dokument zwar gefunden, aber beim Aufruf des Treffers aus der Suche dann nicht gleich gesehen wird, weil der Treffen in einem geschlossenen Accordion hängt.

**Comment by wrcg** [comment]
wurde auch bei uns wieder als Wunsch geäußert...

**Comment by xwolfde** [comment]
in FAU Elements verschoben
