### ISSUE TITLE
Überlagerung Rahmen Personen-Shortcodes mit Sidebar

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#354]
Der Rahmen (so gesetzt) der Personen-Shortcode im Content überlagert die Sidebar, wenn rechts davon die Sidebar ist.

**Comment by xwolfde** [comment]
fixed 1.8.1

**Comment by xwolfde** [comment]
reopened:

Das Problem ist leider nicht so einfach lösbar:

Wenn wir die Standard-Shortcodes mit einer flexiblen vom Inhalt abhängigen Breite machen, dann sind die Boxen (weil Rahmen im Default sichtbar) ggf. nicht gleich lang. 
Wenn man es wie vorher will, muss man den format="kompakt" verwenden.

Wenn wir die Standardboxen allerdings per Default auf volle breite setzen, dann kommt es für den Fall, dass rechts eine Sidebar ist, zu einer Überlagerung des Rahmens mit dieser.

Wir können nur eins von beiden machen...

**Comment by endv02** [comment]
Finde es ehrlich gesagt etwas ungeschickt, wenn man jetzt für die gleiche Breite das format="kompakt" nehmen muss. Die unterschiedliche Breite wirkt am störendsten, wenn ganz viele Kontakte auf einer Seite sind, und ggf. müsste man dann eben bei mehreren Shortcodes auf einer Seite überall noch format="kompakt" mit anfügen... Abgesehen kann das bei der Anzeige eines Rahmens immer komisch wirken, wenn die unterschiedlich sind...
Warum kommt es denn bei format="kompakt" nicht zu einer Überlagerung mit der Sidebar?

**Comment by xwolfde** [comment]
Kommt es auch :/  Es kommt leider immer auf die Höhe der Sidebar an.
Momentan tendiere ich auch dazu, es wieder wie früher zu machen und mit der Überlagerung zu leben...

**Comment by endv02** [comment]
Dadurch, dass man jetzt optional den Rahmen weglassen könnte mit hide="rahmen", fände ich das eine gute Idee. Und auf einer Kontaktübersichtsseite mit ganz vielen Rahmen braucht man ja eigentlich keine Sidebar.

**Comment by xwolfde** [comment]
Dann machen wir das so. Ich denke ich werde wegen dem Formular-Bugs #373 bald ein Update nachschieben und es dann so mit reintun.
Wir müssen das nur gut dokumentieren - am Besten unter den FAQs-, nicht das wir das Thema in nem halben Jahr wieder auf der TO haben. @AstridSemm

**Comment by xwolfde** [comment]
Gerade auch mit CIO besprochen: Machen wir so.
