### ISSUE TITLE
Assistant (unklarer Bug)

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#355]
Nach Ausrollen von 1.8 prüfen ob es im Assistant noch ein Problem auf fau.de gibt. Problemmeldung im OTRS vorhanden, konnte aber nach verschiedenen Tests mit aktueller Beta nicht nachvollzogen werden.

**Comment by xwolfde** [comment]
@RRZE-Webteam/fau-webredaktion Könnt ihr bitte checken, ob der Fehler mit dem Assitanten noch auftriott? Ihr hattet da einen Seite gemeldet, die ich nicht nachstellen konnte.

**Comment by wrkb** [comment]
@xwolfde Sind dran, ist leider lästiger/aufwändiger, aber nicht vergessen! Wir prüfen die Unterseiten auf problematischen Code.

**Comment by wrkb** [comment]
...hab's mal vorgezogen. Jetzt ist das Assistent allerding ganz weg im Englischen (evtl. simpler Fehler hier redaktionell), im Deutschen geht es. Logisch ist das hier alles nicht, aber ich schließe erst mal und wir schauen in Ruhe und reparieren erst mal die Seiten an sich.

**Comment by xwolfde** [comment]
du kannst ruhig die Seiten auf Beta kopieren um dort in Ruhe testen zu können.

**Comment by wrkb** [comment]
Naja, es ist eher so: Ich glaube, im jetzt problematischen Teil fehlen einfach die Seiten, als hätte sie jemand gelöscht. Das muss ein Mensch gemacht haben :D 
Die einst problematische Seite läuft jetzt wie gewünscht (Update?). Von daher ist vielleicht wieder alles okay und wir müssen nur etwas restaurieren, was unabhängig vom alten Fehler kaputt ging von Hand.

Wir können hier erstmal schließen, Danke!

**Comment by xwolfde** [comment]
Super
