### ISSUE TITLE
Menülinks bei mobiler Ansicht (Hamburger Menu)

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/FAU-Einrichtungen#36]
Die Links funktionieren nicht. ZUm Beispiel hier https://www.wr1.rw.fau.de/
(mit Wolfgang besprochen)

**Comment by xwolfde** [comment]
Das Problem ist hier auch eine nicht dafür vorhergesehene Nutzung.

Das Hauptmenü ist für Portalseiten gedacht.
Dies setzt voraus, dass es Unterseiten über die Oberpunkte gibt.
So wurde es dann auch programmiert.

Es war nicht vorgesehen, daß es für ganz normale Menüpunkte
ohne Unterpunkt benutzt wird.

Dazu ist auf der Startseite der darin befindliche Portalindex da.

**Comment by xwolfde** [comment]
War so gedacht, dass das Menu nur für Portalseiten verwendet wird .
Jetzt wird es dennoch genutzt für normale Seiten.
Für die Nutzer erscheint es jetzt als Bug, obwohl es kein Bug ist, sondern gewollt.

Bei einem Workaround der das Problem löst, besteht die konkrete Folge, dass dann erst recht Dinge im Portalmenu reingetan werden, die da nicht hingehören. Weil es dann ja geht. 
Lösung muss durchdacht werden.

**Comment by xwolfde** [comment]
Fixed in nächster Version. Wird jetzt einfach enabled.
