### ISSUE TITLE
Überschriften Sidebar kleiner machen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#365]
Trotz Testphase mit Überschriftenseite, werden jetzt nach dem ROllout die Überschriften in der Sidebar als zu groß bemängelt.
Ist nachvollziehbar.
Daher ein Tick kleiner.

**Comment by xwolfde** [comment]
Ref #363

**Comment by xwolfde** [comment]
In dem Zusammenhang: Die h3 eines Personenkontakts hatte bei zu geringen Platz einen Umbruch mitten im Namen. Dies kam nur im Firefox vor. Prüfen, ob hier der hypen korrekt ist und für den Fall, daß de Platz nicht reicht, der Umbruch automatisiert an anderer Stelle erfolgen kann als im Namen.

**Comment by mduven** [comment]
Hier ein Beispiel von uns:
![test1](https://user-images.githubusercontent.com/28564104/31822030-76c77132-b5a7-11e7-81b3-9a9653adbe97.jpg)

Finde aber generell bei den Personenkontakten den Namen zu groß, hat in vielen Fällen vorher ohne Umbruch gepasst, nun sieht es immer wieder so aus:
![2017-10-20 14_58_39-fachbereichsleitung fbl fachbereich wirtschaftswissenschaften](https://user-images.githubusercontent.com/28564104/31822082-b353ba34-b5a7-11e7-8a87-60f042d40385.png)

**Comment by xwolfde** [comment]
D.h. eigentlich müssten wir bei Personen eine Ebene kleiner sein? In dem Fall müssten wir eigentlich das Default der Personenanzeige von h3 zu h4 ändern?

Hier nochmal die Übersicht: https://www.beta.wordpress.rrze.fau.de/texte/ueberschriften/

**Comment by xwolfde** [comment]
Hab nochmal nachgecheckt. Ja im Content ist die Überschrift selbst falsch. Wenn vorher darüber eine h3 ist, muss danach eine h4 kommen. Dann wäre die Größe auch korrekt. Wir haben dazu in der neuen Version des Personen-Plugins das Attribut     hstart="n", wobei n die Überschriftenhierarchie ist.
Trotzdem sollte es auch bei h3 nicht so falsch umbrechen.

**Comment by xwolfde** [comment]
Prio 2

**Comment by xwolfde** [comment]
fix kommt
