### ISSUE TITLE
Synonyme neu: Platzhalter-Content

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#372]
Die jetzige Synonym-Funktionalität wird nicht rein als Nutzung für Synonyme (im technischen Sinne) gesehen.
Vielmehr geht es darum, Platzhalter-Content darzustellen. Dieser Content kann/soll auch mehrzeilig sein können. Und wenn Mehrzeilig kann wahrscheinlich nicht ausgeschlossen werden, dass hier auch multimedialer Inhalt rein können soll.

Dies entspricht eigentlich der Glossar-Funktion.
Der Unterschied ist jedoch, dass auch gewünscht ist, entsprechende wichtige Hinweise damit zu markieren. Dies spricht dafür, die Funktion auch um eine Auswahl der Absatzmarken zu versehen.

Problem ist aber: Was ist mit Texten, wo der Inhalt einzeilig und Teil eines Absatzes ist und als echte Abbrevation verwendet wurde? Wenn nun ein Absatztext bzw. mehrzeiliger Text eingefügt wird, wird der Absatz in dem der Shortcode ist, semantisch und optisch kaputt gemacht.

Ref #166

**Comment by xwolfde** [comment]
Aus Rückmeldung aus Nat: Kann man damit dann auch CSS einfügen, welches die Website-Gestaltung ändert?
 (Ein Lehrstuhl mag die CI-Überschriftfarbe nicht. Bei der TF hat ein anderer Studiengang die Überschriftenfarbe ebenfalls durch diese Möglichkeit auf eine selbe definierte ändern können).

**Comment by xwolfde** [comment]
@RRZE-Webteam/fau-webredaktion

**Comment by wrkb** [comment]
Hinweis, weil immer noch Missverständnis: Wir benötigen diese Funktion/Erweiterung **NICHT**. Wir benötigen nur einen Zeilenumbruch des vorhandenen Textfeldes der vorhandenen Funktion, wenn mal 300 statt 30 Zeichen eingegeben werden. Alles andere funktioniert. Wir wollen keine Formatierung und keine Markierung, keine Absatzklassen, kein Styling - nichts. Nur Text. Wir benötigen kein neues Plugin, die Synonym genannte Textersetzung funktioniert ansonsten einwandfrei.

**Comment by xwolfde** [comment]
ok, das mildert meine Befürchtungen deutlich. In dem Fall versuch ich es in die nächste Version reinzutun.

**Comment by xwolfde** [comment]
In 3 Minuten in der Version auf beta umgesetzt. (V1.8.8)
