### ISSUE TITLE
Newsletterfunktion à la MailPoet

### ISSUE THREAD

**Issue by GeowulfT** [RRZE-Webteam/FAU-Einrichtungen#374]
Liebes Webteam,

es wird eine Funktion benötigt, mit der eine Newslettererstellung aus der Webpage heraus vereinfacht wird. Bisher wurde MailPoet verwendet, was aber durch die Umstellung auf die Uni-weite Standard-HP nicht mehr möglich ist. Wäre es möglich MailPoet zu integrieren? Oder ein vergleichbares Ersatzplugin zu kreieren? Wichtig dabei wäre, dass man Beiträge, News, etc. von der Homepage in einen Newsletter zusammenfasst. Zusammen mit Freifeldern, bei denen dann noch händische Informationen eingetragen werden können. Der Fokus liegt somit also auf der Erstellungs-Seite.

Besten Dank und
VG

**Comment by xwolfde** [comment]
MailPoet hatten wir schon geschaut. Das ist ein "Monster" und wir würden uns damit massig Probleme einholen. Insbesondere was den effizienten Mailversand anginge.  
Wir haben eine Alternative, die wir mangels Zeit aber noch nicht dokumentieren und damit nicht offiziell rausgeben konnten. Schauen Sie mal dies an:  https://www.feedmailer.rrze.fau.de/
(Login via IdM).

Damit versenden wir u.a. unsere eigenen "Aktuelles"-Meldungen (Quelle Feed) und unsere Kalender-Ankündigungen (Quelle ICS).
Ggf. könnten wir ein individuelles Template zum Versand hinterlegen.

Bei Fragen am besten direkt via Mail an webmaster@fau.de
