### ISSUE TITLE
Hamburger-Icon checken

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#38]
Probelmmeldung mit einem Android 5.1
https://github.com/RRZE-Webteam/fau-events/issues/14

**Comment by csw-** [comment]
Hier noch der gewünschte Screenshot. 

![screenshot_2016-04-08-21-44-19](https://cloud.githubusercontent.com/assets/6545158/14395757/dd70cace-fdd3-11e5-8f1b-9cc695d6fae3.png)

**Comment by xwolfde** [comment]
Plugin..
