### ISSUE TITLE
Formular 7 Recaptcha Funktion disablen?

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#385]
Contact Form 7 bietet die Option ein Recaptcha einzubauen.
Leider quasi auf Klick.
Das Recaptcha funktioniert aber zum einen nicht richtig, ist nicht uneingeschränkt Barrierefrei, zum anderen ist es aus verschiedenen Gründen ein Bruch der Sicherheit und liefert den Benutzer der Site ein Tracking durch den Anbieter aus.

Sollten wir versuchen, diese Funktion zu disablen?

**Comment by AstridSemm** [comment]
Wenn der Benutzer einem Tracking durch den Anbieter ausgeliefert ist, sollte man checken, ob das datenschutzrechtlich ok ist. Ich finde generell, dass man solche Dinge sein lassen sollte, wenn es möglich ist.

**Comment by xwolfde** [comment]
Wenn der Button da ist, wird es heißen, wir bieten es an. Also sind wir schuld...

**Comment by AstridSemm** [comment]
Eben. Genau deshalb würde ich das weglassen.

**Comment by xwolfde** [comment]
wird in den FAU Designs ausbelendet.
