### ISSUE TITLE
Obskurer Anzeigefehler im Chrome

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#387]
Bei manchen Webseiten mit kurzer Hauptnavi (nur 3 Punkte) bricht der Chrome bei einer Vergrößerung des Textes auf 120% den dritten Punkt um (obwohl es rechts noch genügend Platz gäb) und lässt diesen so verschwinden.
Dies tritt nur bei Chrome auf und nur bei einigen Webseiten, wie der https://www.cs12.tf.fau.de/
Bei der Webseite der tf, welches mehr Elemente in der Hauptnavi hat, tritt das Problem nicht auf!

**Comment by xwolfde** [comment]
Tritt auch auf, wenn man im Chrome auf 90% verkleinert. 
Auch wenn es mehrere Punkte sind.
Bei 80% ist der Navipunkt dann wieder da.

**Comment by xwolfde** [comment]
Im Rahmen der Änderungen des Navigationsverhaltens prüfen.

**Comment by jkphl** [comment]
@xwolfde Ist der Fehler tatsächlich noch aktuell? Ich kann ihn mit aktuellen Chrome-Versionen (71.0.3578.98 / 72.0.3626.96) unter Windows nicht reproduzieren. Sind es eventuell andere Plattformen / Kombinationen, die problematisch sind?

Ferner: Von welchem Zoom sprichst du? Das Seitenzoom lässt bei mir 120% nicht zu (Schritte sind 100%, 110%, 125%, etc.) und bei allen (auch 90%) tritt das Problem nicht auf. Auch über das Textzoom kann ich den Fehler bei keiner Einstellung nachvollziehen (hier sind die Schritte "klein", "mittel", "groß" usw.), und auch über das explizite Verstellen der Textgröße gibt's den Fehler nicht. Hat sich vielleicht erledigt?

**Comment by xwolfde** [comment]
Du hast recht, ich kann den Fehler derzeit auch nicht mehr nachvollziehen. Auch nicht auf der o.a. Kundensite, bei der es anfangs gemeldet wurde.
Dann wurde es mgw. zwischendrin schon durch eine andere Änderung gelöst.
