### ISSUE TITLE
Breadcrumb-Banner: Anzeige hierarische Oberseite als CI-Element im Hintergrund

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#389]
Es geht um die Frage, ob das Design-ELement, mit dem im Hintergrund des Breadcrumb-Balkens auf Unterseiten,  das hierarisch höhere Element gezeigt wird, sinnvoll ist:

https://github.com/RRZE-Webteam/FAU-Einrichtungen/issues/63#issuecomment-339690799

![kannweg](https://user-images.githubusercontent.com/11296947/32059774-6d8abf0a-ba6d-11e7-9c1d-48892da4b1ad.png)

Bitte hier, statt im vorherigen Issue weiter diskutieren, damit es nicht vermischt.
@RRZE-Webteam/fau-webredaktion @AstridSemm

**Comment by xwolfde** [comment]
Wichtig zur Einordnung: Es geht um den Titel der Oberseite, nicht um den Titel der Seite.
Der Titel der Seite wird korrekt umgebrochen.
Wenn der Titel der Oberseite jedoch lang ist und umgebrochen werden muss, reicht der Platz nicht und es kommt zu einer Verschiebung außerhalb des Viewports.

Hier eine SImulation für einen Worst Case:
![test-lange-titel-breadcrumb](https://user-images.githubusercontent.com/1070669/32098326-98ac3232-bb0c-11e7-901a-427b894296a7.png)

Der Titel der Seite ist schlicht "Testseite".
Der Hierarchisch höchste Titel der zugehörigen Portalseite ist "Testen und Fluchen gehören zum Tagewerk". 
Es gibt noch ein der Portalseite untergeordnete Zwischenseite, die aber nicht in die Breadcrumb kommt.

**Comment by xwolfde** [comment]
Im Prinzip geht es um die Frage: Versuchen wir eine andere Lösung, die auch bei _unguten_ Entscheidungen der Redakteure noch funktioniert?

**Comment by wrkb** [comment]
@xwolfde Ich sehe keine gute. Man kann nicht alle unguten Entscheidungen ausbessern - gewissen Dinge müssen Redakteure auch einfach sehen. Ich denke, oft sind die Entscheider andere Personen als die Redakteure.

Dazu kommen typische Phänomene, man niemandem konkret vorwerfen kann (Überforderung), die aber auch das beste System der Welt nicht abfangen kann. Wie weit muss man das System verbieben, um jedes noch so vermeidbare Problem zu lösen? Ist eine Frage, keine Einschätzung irgendeiner Lage.

Auch mit dem Webbaukasten wurden früher die irrsinnigsten Dinge angestellt.

**Comment by xwolfde** [comment]
Bedarf gering, wie rege Diskussion zeigt.
Andere Dinge haben höhere Gewichtung.
Woraround: Optionale Customizer-Einstellung.
