### ISSUE TITLE
Abstand von Linklisten in der Sidebar zu gering

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Einrichtungen#395]
Mit Ticket https://www.helpdesk.rrze.fau.de/otrs/index.pl?Action=AgentTicketZoom;TicketID=612435 kam folgender Hinweis:
In der Sidebar ist der Abstand zwischen dem ersten Linkblock und der Überschrift des zweiten Linkblocks zu gering, das ist optisch ungünstig.

Screenshot:
![bildschirmfoto 2017-11-02 um 07 09 09](https://user-images.githubusercontent.com/11296947/32312202-c5906a54-bf9c-11e7-9be5-b2d66ec70114.png)

**Comment by xwolfde** [comment]
Ja, betraf nur die Seiten, die keine Inhaltsseiten waren.Ist gefixt & wird heute noch ausgerollt.
