### ISSUE TITLE
Nach oben/Scroll to top-Animation scrollt nicht zum Seitenanfang

### ISSUE THREAD

**Issue by csw-** [RRZE-Webteam/FAU-Einrichtungen#40]
Einer Kollegin ist gerade aufgefallen, dass man bei einem Klick auf den "Nach oben"-Button nicht sofort ganz nach oben zum Seitenanfang kommt, sondern immer nur ein kleines bisschen. Ich nehme nicht an dass das beabsichtigt ist - oder?
Das gilt für die aktuellen Fakultäts- und das Einrichtungsstheme.

**Comment by xwolfde** [comment]
Bestätigt

**Comment by xwolfde** [comment]
In der nächsten verison gefixt
