### ISSUE TITLE
Umleitungs-Hack bei Navi Links

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#404]
Für dIe Navi links war vorgesehen, daß diese nur für die Inhalte aufgebaut wird, die auch auf der Website vorhanden sind und der gewählten Portalseite ungeordnet sind. Dem entsprechend baut es sich auch nun automatisch auf. 
(Es gab auch mal eine rege Diskussion, ob man die Navi über eine optionale Menu machen könnte.
Im Rahmen vom CRIS-Plugin kommt zudem die Forderung, daß Navi-Menu automatisiert  zu bauen).

Beim Testen hab ich nun zufällig eine Variante gesehen, wo die aktuelle Umsetzung ausgetrickst wurde, um einen externe Seite zu verlinken:

Auf der Seite:
https://www.rw.fau.de/forschung/forschung-rechtswissenschaft/

verweist der Link "Forschung an der FAU" auf die Seite
https://www.rw.fau.de/forschung/forschung-an-der-fau/

Nun kommt der Trick: Mit dem Redirection-Plugin wurde nun eingestellt, daß Zugriffe auf diese Seite auf die externe URL https://www.fau.de/forschung/forschungsprofil/ umgeleitet werden.

Wie wollen wir damit umgehen?

**Comment by wrkb** [comment]
Hm, ist nicht direkt verboten, aber ein Usability-Bruch. Eins der Dinge, die in der Verantwortung der Webmaster liegen. Mildern könnte man es vielleicht, wenn man bei Umleitungen weg von fau.de das Icon für externe Links dranpappt. Aber ich weiß gar nicht, ob das technisch möglich ist (ob die Weiterleitung erkannt wird) und ob das wieder der Logik von 301 und Icon zuwider läuft. Und man würde das irgendwie auch legitimieren...

**Comment by wrkb** [comment]
achso, noch ein Nachtrag: Ich verstehe das Anliegen hinter diesen Themen schon ein wenig. Denn eigentlich sind FAU-Webseiten ja ein Auftritt, auch wenn die Fakultäten eigenständig agieren, auch farblich. Wie kriegt man also globale FAU-Themen in den Auftritt integriert, ohne jedesmal eine landing page zu machen oder viel weniger repräsentative Links in Kontext oder Content zu nutzen?

Das Problem haben wir hier auch ab und an, betrifft auch die interne Suche, die Stichworte braucht auch bei Themen, die auf anderen FAU-Web-Instanzen fau.de liegen. Wir machen dann landing pages, ohne glücklich damit zu sein...

Es wäre interessant, ob der "usability-Bruch" vielleicht jenseits der Webmaster-Sicht gar nicht auffällt, solange es FAU-Seiten im FAU-CD sind. Ich bin hier betriebsblind, Nutzertests würden helfen. Und Benchmarking vielleicht auch.

**Comment by xwolfde** [comment]
Regeln zur Barrierefreiheit und der Usability sagen ziemlich genau, daß man Links, die von der eigenen Website wegleiten also solche kennzeichnen muss. Das brauchen wir da eigentlich nicht mehr zu testen, das wurde schon festgelegt. 
Das Problem hier: Wir können es nicht technisch nicht lösen, da durch die Umleitung das Theme gar nicht mehr greift.  Auch das Plugin, welches externe Links kennzeichnet funktioniert hier nicht. WENN wir statt bisher dort ein Menü hätten und dort im Menü ein externer Link wäre, dann könnte das Theme das erkennen bevor der Klick erfolgt und dann könnte man auch eine Markierung machen.

Ich würde jetzt erstmal nichts tun und abwarten.  Ansprechen wollte ich es trotzdem mal.
Solange sich dieser Trick nicht verbreitet und massenhaft verwendet wird, ist der Bedarf was zu tun nicht so hoch...  Letztlich ist es auch so wie du sagst: Wir können nicht alles verhindern, was Redakteure machen auch wenn es unschön ist. 
Manchmal kommen durch kreative Lösungen auch Dinge heraus, die wir übernehmen sollten (wie die Sache mit den Personen-Index oder die Auflistung der letzten Publikationen eines Lehrstuhl in der Sidebar, was ich heute beim LKT sah).

**Comment by wrkb** [comment]
Ja, ich meinte auch eher, dass man die Definition von "eigener Webauftritt" auch anders vornehmen kann. Eigentlich ist alles eine Uni, unabhängig von den technischen Instanzen.
Fühlt sich merkwürdig an aus unserer Arbeitssicht, aber vielleicht ist die eben auch sehr eng. Aber dieser ganzheitliche Blick funktioniert natürlich nur in solchen Themenbereichen wie im Beispiel oben - Sprünge innerhalb von Sinneinheiten innerhalb eines Webauftritts erlauben wir ja in der Navigation auch nicht - etwas in Portalmenüs. Man darf also nicht über Menüs, die vom Seitenbaum stammen willkürlich von Studium in Universität springen, das hat uns selbst schon verwirrt damals.

Letztendlich ist eine offizielle Funktion (und optische Kennzeichnung dazu) vielleicht wirklich das Beste, wenn der Bedarf zunimmt. Redesign-Frage?
