### ISSUE TITLE
Listenelemente im Main-Content

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#408]
Zur Diskussion:
Im Content sind die normalen unsortierten Listen derzeit ohne besondere Änderungen: 
![2017-11-02-15-51-www beta wordpress rrze fau de-listen](https://user-images.githubusercontent.com/1070669/32332446-c893793c-bfe5-11e7-93aa-c97b83077553.png)

In der Sidebar und den Menüs verwenden wir als Listen-Symbol statt dem Kreissymbol das spitze Pfeilzeichen.
![2017-11-02-15-53-test8 tindu rrze uni-erlangen de-linkliste](https://user-images.githubusercontent.com/1070669/32332551-120c62d6-bfe6-11e7-849f-b4a7b6813039.png)

Warum diesen Unterschied? Gab es damals dazu eine DIskussion? (Wenn ja, hab ich sie nämlich vergessen). Wäre es nicht besser zur Einheitlichkeit auch bei den unsortierten Listen im Contentbereich (auch dann wenn es keine Links sind), die Pfeilsymbole zu nutzen?

**Comment by AstridSemm** [comment]
Du hattest mir weiland gesagt, dass das mit den Kreissymbolen so beschlossen gewesen sei (weil ich damals mal eine Liste hatte, bei der das richtig blöd aussah). Insofern denke ich, dass das durchaus besprochen und auch beschlossen war.

**Comment by wrkb** [comment]
Die Pfeile waren immer für Links in Listenform gedacht, wo sie vom Template erzeugt werden (also nicht manuell als Liste angelegt via Editor, sondern durch Eingabemasken (Sidebar) oder Menüs) - und auch als Template-Bestandteil wahrgenommen werden. Hervorhebung bei Design quasi.

Ist eine Liste im Content, mit verlinktem Text dahinter ist also nicht das Gleiche und durch Alltag-gelernte Bullet-Point-Listen (Mail, Word, Powerpoint) wird das m.E. auch als Content-Element wahrgenommen.

Würden wir auch für Content die Häkchen nutzen, wäre das kontraproduktiv - die bewusste und okaye Trennung von Content und Kontext/Template-Stilelementen würde verwaschen und außerdem würde die Seite langweiliger.

**Comment by AstridSemm** [comment]
Wobei die Bulletpoints tatsächlich abgrundtief hässlich sind; ich finde ja, man sollte sie zumindest unterdrücken können.

**Comment by wrkb** [comment]
Aber dann geht ja ein Merkmal der Liste verloren. Ich finde sie auch nicht besonders schön, sind halt Standard/gelernt., vielleicht gibt's was Passenderes, was nicht aufdringlicher ist?

**Comment by AstridSemm** [comment]
Man könnte ja mal sehen, was awesome fonts da so zu bieten hat...

**Comment by xwolfde** [comment]
- Hat nichts mit dem Font zu tun.
- Die Änderung der Bullet Points ist heutzutage bei vielen Designs üblich. Ganz unabhängig von dem Inhalt. Das es Links sind, spielt da bei modernen Designs kaum eine Rolle. 
- Ganz häufig findet man die Form (auch zu sehen in den Abendnachrichten) mit einem runden Kreis einer definierten CI-Farbe, worin dann der spitze Pfeil auf weiß gesetzt wird:
![listitems](https://user-images.githubusercontent.com/1070669/33933748-fa0367b2-dff6-11e7-998c-a3cbf94b395a.jpg)

**Comment by xwolfde** [comment]
Diskussion ohne Ergebnis. Bedarf offenbar gering. Andere Aufgaben haben höhere Prio. Daher schließe ich dies als wontfix.
