### ISSUE TITLE
Copyright-Info Einstellungen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#41]
Theme OPTIONEN - ERWEITERT  - DESIGN

Die Optionen führen offenbar zu unnötigen Folgefragen.
Überlegen, ob die Optionen wieder entfernt werden und zwangsweise nur noch Copyright-Info aus dem Bild Priorität erhält?

**Comment by AstridSemm** [comment]
Ich bin sehr dafür, auch wenn das natürlich wieder andere Probleme auslösen wird (wenn nämlich die Copyright-Info aus dem Bild grottig ist).

**Comment by xwolfde** [comment]
Problem anders gelöst: Die erweiterteten Optionen werden nur für Experten sichtbar
