### ISSUE TITLE
Tabellenplatz zu knapp

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#414]
Da der Contentbereich mit ca. 700px (bei Navi links) zu klein ist für richtige Datentabellen, sollte bei Gelegenheit nochmal über die Verbesserung der Darstellung breiter Tabellen nachgedacht werden. 
Das horizontale Scrollen ist nicht sehr Benutzerfreundlich.

Ein responsiver und barrierefreier Ansatz ist hier zu sehen:
https://codepen.io/gunnarbittersmann/pen/BmjPGr

**Comment by mduven** [comment]
Habe von einem Lehrstuhl diesbezüglich Rückmeldung bekommen, da viele Studierende die notwendigen Downloads übersehen und nicht finden:

https://www.institut-wipaed.rw.fau.de/studium/bachelorstudium-wirtschaftswissenschaften/uebersicht-ueber-die-zweitfaecher/

https://www.institut-wipaed.rw.fau.de/studium/bachelorstudium-wirtschaftswissenschaften/lehrveranstaltungen/

https://www.institut-wipaed.rw.fau.de/studium/masterstudium-wirtschaftspaedagogik/lehrveranstaltungen/

https://www.institut-wipaed.rw.fau.de/studium/masterstudium-wirtschaftspaedagogik/uebersicht-ueber-die-zweitfaecher/

Eine andere Darstellung ist dann momentan quasi nicht möglich?

**Comment by xwolfde** [comment]
Eine Verbreiterung der Darstellung des FAU Designs wurde von den anderen Mitgliedern des Design-
 Ausschusses leider abgelehnt. 
Die Tabellen sind schlicht mit weniger Spalten aufzubauen oder das Template ohne Navi links nehmen.
Alternativ Accordions.

**Comment by xwolfde** [comment]
Anmerkung: Bei obigen Beispielen sind in vielen Fällen die Linktexte semantisch nicht einem Ziel zuordbar. Das "Bachelormodule" oder "zur vhb" sind keine eindeutigen LInktexte aus die sich das Ziel klar ergibt und unterschieden wenn den selben Links mit denselben Titel.
Dies ist aus Sicht der Barrierefreiheit ein Fehler, solange nicht vorher eine semantisch korrekte Überschrift (z.B. in der ersten Spalte mit th) den Kontext vorgibt.
