### ISSUE TITLE
Bildunterschriften 

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Einrichtungen#415]
Bitte die Größe der Bildunterschrift bei Beitragsbildern (.post-image-caption) an die Größe der Bildunterschrift der Bilder im Text (.wp-caption-text) ) anpassen.
Diese sind zur Zeit nicht gleich.

Beispiel:  https://www.fau.de/2017/11/news/panorama/eine-chance-fuer-kayan/

**Comment by xwolfde** [comment]
in 1.9.1
