### ISSUE TITLE
Beiträge auf externen Link umleiten ist nicht mehr möglich

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Einrichtungen#416]
Wenn man in einem Beitrag nur einen Anleser und einen externen Link eingibt, soll im Frontend vom Beitrag auf den externen Link geleitet werden. Das hat bisher auch sehr gut geklappt. Nun wird der Link herausgelöscht, sobald man den Beitrag speichert.

**Comment by xwolfde** [comment]
fixed in 1.9.1
