### ISSUE TITLE
RSS-Fehler bei Shortcode auf eigenen Blog

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Einrichtungen#417]
Shortcode [rss url="http://fau.de/category/news/studium/feed"  items="2" show_description="1" show_date="0"]
meldet folgenden Fehler:
RSS-Fehler: This XML document is invalid, likely due to invalid characters. XML error: > required at line 2372, column 44

**Comment by rvdforst** [comment]
Es sollte jetzt funktionieren. Ich musste Anpassungen an folgendem Plugin vornehmen:
rrze-thumbnails2rss
fau-oembed
fau-video
