### ISSUE TITLE
Nutzung des shortcodes blogroll führt zu Unerreichbarkeit

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Einrichtungen#418]
Wenn man den shortcode [blogroll cat="kategorie"] in einem Beitrag nutzt, entsteht (wohl) eine Endlosschleife. Auch wenn es natürlich im Grunde sinnfrei ist, das zu tun, sollte das nicht passieren. Ich habe das zufällig entdeckt, weil ich das Feature in einem Artikel beschrieben habe und selbstverständlich ein Beispiel einbinden wollte, was genau zu diesem Verhalten führte.

**Comment by AstridSemm** [comment]
Der ganz große Witz ist, dass das nicht nur passiert, wenn man den Shortcode an sich nutzt, sondern auch, wenn man den shortcode-Text anzeigen möchte (also [[blogroll cat="kategorie"]]). Es läßt sich in der Tat nur beheben, wenn man dem Wort "blogroll" etwas hinzufügt, wie zB. "blogroll2". Rolf äußerte den Verdacht, dass "blogroll" ein WordPress-internes geschütztes Wort ist, auf das WP in Beiträgen eben etwas nickelig reagiert. Das sollte bitte geprüft werden.

**Comment by cassandre** [comment]
Es gab mal eine Blogroll in WP, die aber mit 3.6. abgeschafft wurde. Der Begriff taucht aber momentan im Core nicht in irgendeinem kritischen Zusammenhang auf. 
Mein Vorschlag wäre einfach ein `if (!is_page()) return;` o.ä. an den Anfang vom Shortcode zu setzen

**Comment by xwolfde** [comment]
in 1.9.1
