### ISSUE TITLE
Sprache des Default-Texts der Suchmaske wird nicht umgestellt

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Einrichtungen#421]
auf https://www.lpt.tf.fau.eu/ wird auch nach Umstellung der Sprache im Backend der Text in der Suchmaske auf Deutsch angezeigt. Ich gehe davon aus, dass das im Theme nachgezogen werden muss.

**Comment by xwolfde** [comment]
Das Englisch Standard ist en-uk. Nicht en-us.
Bei en-uk funktioniert die übersetzung. 

Am 20. November 2017 00:58:49 GMT-06:00 schrieb Astrid <notifications@github.com>:
>auf https://www.lpt.tf.fau.eu/ wird auch nach Umstellung der Sprache im
>Backend der Text in der Suchmaske auf Deutsch angezeigt. Ich gehe davon
>aus, dass das im Theme nachgezogen werden muss.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/RRZE-Webteam/FAU-Einrichtungen/issues/421

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by xwolfde** [comment]
Der Website-Admin muss die richtige Sprache wählen: EN-UK
