### ISSUE TITLE
Umbruch Social-Media-Buttons bei linksbündigen Bildern

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Einrichtungen#422]
...da stimmt was nicht, die Social-Media-Sektion floatet in den Content rein:

![unbenannt](https://user-images.githubusercontent.com/9445370/33078349-b177d292-ced2-11e7-8f8e-7263ef44ee31.PNG)

**Comment by xwolfde** [comment]
Nö, das ist richtig so. Die Bilder sind floatend gewählt. Also floatet auch der nachfolgende Content. 
Wenn kein Floating nach den Bildern oder nach Absätzen gewünscht ist, dann kann ein &lt;hr&gt; gesetzt werden um den floatenden Bereich zu reseten.

**Comment by wrkb** [comment]
Nanu, wieso sind die Buttons Content? Die sollten vom Template gesetzt werden ans Ende einer Seite/eines Beitrags. Nicht manuell. Kann das umgesetzt werden?

**Comment by xwolfde** [comment]
Die Buttons kommen vom Social Media Plugin. Das Social Media Plugin hängt seinen "Content" am Ende (und nicht hinter) dem Content-Bereiches an.

Das kann nicht geändert werden und ist auch nichts neues.

**Comment by wrkb** [comment]
Klaro, Content war aus redaktioneller Sicht gemeint, kann man ja verschiedentlich. Die Buttons sind ja immer gleich, weil zentral eingestellt, damit ein einpflanzbarer Teil des Templates. Content aus redaktioneller Sicht ist, was ich ändere und was jedesmal anders ist bei Beiträgen.
Ergo: Kann man stylen, dass vor den Buttons immer ein <hr> erscheint? Das jedesmal händisch zu machen, wenn wir nicht mit einer Textzeile abschließen, ist ja nicht die Lösung und das Gegenteil dessen, was ein CMS tun soll :)

**Comment by xwolfde** [comment]
Nein, sonst hätte ich das längst gemacht :(   Genau dieses Problem hab ich schon mehrfach gehabt und nach Lösungen gesucht. Die einzige Alternative wäre, die SoMe-.Icons nicht unter den Beitrag zu tun, sondern bspw. in die Sidebar als Widget.

Das CMS hat hier auch keine Schuld, es wird eben bei dem Plugin im Backend ja ausgewählt, wo die Buttons erscheinen sollen. Und dort ist nunmal ausgewählt, dass es am Ende des *Inhalts* kommt. Das können wir vom Theme nicht beeinflussen.

**Comment by wrkb** [comment]
Okay, dann ist es so. Ich frag mal hier, ob die Widgets auch in der Sidebar gehen. Das könnte gehen.
Danke!
