### ISSUE TITLE
Bug: Suche im Blog/Blogroll auf (Blog-)Beiträge begrenze

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Einrichtungen#423]
Wenn ich in der Beitragsübersicht der Blogfunktion die Suche benutze, werden auch Seiten mit durchsucht. Da dürfen im Gegensatz zur normalen Seitensuche oben im Header-Bereich aber nur Beiträge durchsucht werden, alles andere ergibt keinen Sinn.

Das Problem in Bildern:

![1](https://user-images.githubusercontent.com/9445370/33078748-ed15ac06-ced3-11e7-8797-d8121a9223d4.PNG)

![2](https://user-images.githubusercontent.com/9445370/33078752-f140cdec-ced3-11e7-850d-c933880102fc.PNG)

**Comment by cassandre** [comment]
An der Stelle ist das Standard-Such-Widget von WordPress als Widget eingebunden. Das lässt sich aber nicht konfigurieren und sucht eben nach allem, wo nach WordPress von sich aus sucht: Beiträge und Seiten.
Möchte man das ändern, müssten wir das programmieren: Entweder ein neues anpassbares Such-Widget, oder (falls möglich) einen Filter für Suchen die von der Blog-Seite aus gestartet werden.

Kurzfristige Besserung: Einfach die "Meldungen" aus dem Titel des Widgets entfernen.

**Comment by wrkb** [comment]
Stimmt, danke cassandre. Dann ist das wohl ein Bug in der Logik der Wordpress-Entwickler... Ich überleg mal, wie wir damit umgehen, Neuprogrammierung ist grad nicht zu rechtfertigen, wir haben andere Baustellen.

**Comment by xwolfde** [comment]
Das ist so nicht ganz korrekt. 
Für die Widget gibt es die searchform.php in der man entsprechende Bedingungen einstellen kann.
Im Update kommt es.
