### ISSUE TITLE
Google Site Verification (Themes Options)

### ISSUE THREAD

**Issue by rvdforst** [RRZE-Webteam/FAU-Einrichtungen#424]
Der Meta-Tag zur Identifikation der Inhaberschaft gegenüber Google kann wegen des wp_filter_nohtml_kses-Filters nicht eingegeben werden.

**Comment by xwolfde** [comment]
hä? da soll keine META eingegeben werden, sondern nur die ID aus dem Meta-Tag.
Ich werde aber mal die Beschreibung  besser formulieren.

Und zwar wie folgt:

"Zur Verifikation der Website als Property in den Google Webmaster Tools wird die Methode über den HTML-Tag ausgewählt. Google erstellt dann auf der Einrichtungsseite eine HTML-Anweisung. Von dieser Anweisung kopiert man den Bestandteil, der im Attribut "content" angegeben ist. 
Beispiel: 
Google gibt den HTML-Code:    <meta name="google-site-verification" content="BBssyCpddd8" />
Dann geben Sie dies ein: BBssyCpddd8 ."
