### ISSUE TITLE
Zusatzfunktionen zu blogroll

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Einrichtungen#425]
Per Mail kam folgende Anfrage von einem Kunden:
"ich finde dieses [blogroll] sehr nützlich. Ich kann es aber meinen
„Spezialisten“  nicht verkaufen, weil da in der Liste der Beiträge die
Kategorie und das Erstellungsdatum angezeigt wird. Vielleicht (wenn der
Entwickler am RRZE sitzt) können da noch ein paar Optionen programmiert
werden? Ich fände es z.B. nicht schlecht, wenn man den Autor/Verbrecher
eines Beitrags anzeigen lassen könnte…"
Ich denke, das wäre ein nettes nice to have.

**Comment by xwolfde** [comment]
wird das Attribut hidemeta="true"

**Comment by xwolfde** [comment]
Bitte Dokumentation ergänzen

**Comment by mduven** [comment]
Guten Morgen, ich poste das einfach mal mit in den Zusatzfunktionen-Issue mit rein: Gibt es die Möglichkeit unter die Beiträge eine "Ältere Beiträge/Mehr Meldungen"-Schaltfläche einzubauen bzw. wäre das nicht auch sinnvoll?

**Comment by AstridSemm** [comment]
Doku erledigt: https://www.wordpress.rrze.fau.de/redaktion/artikelkategorien-einbinden-wie-auf-der-startseite/

**Comment by mduven** [comment]
Das Ausblenden scheint nicht zu greifen:

[blogroll cat="nachhaltigkeit" num=3 hidemeta="true"]

--> https://www.wiso.rw.fau.de/dev/profpubl/

![2017-12-19 09_28_39-profpubl fachbereich wirtschaftswissenschaften](https://user-images.githubusercontent.com/28564104/34147765-1dac7ddc-e49f-11e7-844b-19e3b3d84868.png)

**Comment by AstridSemm** [comment]
Aber es steht schon mal in der Doku!!!

**Comment by mduven** [comment]
Na gut :)

**Comment by wrkb** [comment]
hier hat es funktioniert: https://www.275.fau.de/wissen-erleben/
auf fau.de und fau.eu fehlen uns Anwendungsfälle.

**Comment by wrkb** [comment]
wir haben auch keine anführungszeichen verwendet --> hidemeta=true

**Comment by mduven** [comment]
hm, gleiches ergebnis.. wobei das für uns erstmal nicht relevant ist, ist mir nur so aufgefallen ;) der oben erwähnte button wäre hier hilfreicher ;) :)

**Comment by AstridSemm** [comment]
@wrkb Ich hab's so dokumentiert wie es hier notiert ist. Und wenn - wie @mduven sagt - beides nicht funktioniert, sollte man mal schauen, denke ich... ^^

**Comment by wrkb** [comment]
@AstridSemm Klar, irgendwas muss ja haken, nachdem es auf 275 läuft und auf Beta lief. Liegt's am Wiwi-Theme? Wenn ich auf fau.de mal testen soll, sag Bescheid!

**Comment by AstridSemm** [comment]
@wrkb @xwolfde @mduven Ich hab's durchgecheckt: Es funktioniert derzeit nur auf FAU-Einrichtungen, auf allen anderen Themes noch nicht.

**Comment by xwolfde** [comment]
Hab ich denn irgendwo geschrieben, dass es schon auf den Fakultätsdesigns ausgerollt ist? 

Hier steht: https://blogs.fau.de/webworking/2017/12/15/update-theme-fau-einrichtungen-auf-version-1-9-1/ "in Bälde".  Und eine Meldung, dass es ein Update für die Fakultätsthemes gab, gab es noch nicht.

Und die Tester können hier lesen:
https://www.beta.wordpress.rrze.fau.de/2017/12/14/beta-version-1-9-1/
"Dabei aber nur das FAU-Einrichtungen-Theme. Die Fakultätsthemes müssen noch warten."

**Comment by xwolfde** [comment]
Zu oben: "Gibt es die Möglichkeit unter die Beiträge eine "Ältere Beiträge/Mehr Meldungen"-Schaltfläche einzubauen bzw. wäre das nicht auch sinnvoll?"

Es ist ein Shortcode. Ergo kannst du auch nach dem Shortcode von Hand ein Link einfügen, der zu einer beliebigen Kategorie- oder Indexseite führt.

Die Archiv-Funktion, die den Kategorieindex einführt möchte ich aber nicht nachbauen.

**Comment by mduven** [comment]
Vielen Dank für die Rückmeldung(en), hatte das in der Meldung schlicht überlesen, mir ist es dann als ich damit herumgespielt habe halt aufgefallen. Habe mich in die Testerliste eingetragen, damit mir da nichts mehr durchrutscht.

Habe die Links nun von Hand eingefügt. Finde die blogroll insgesamt sehr nützlich! :)
