### ISSUE TITLE
Missverständlicher Text in der Metabox "Beitragsoptionen"

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Einrichtungen#430]
Mir war gar nicht aufgefallen, dass in den Beitragsoptionen steht, dass ein Artikel das Schlagwort "startseite1/2/3" enthalten müsse, damt er auf der Startseite angezeigt wird. Das ist nicht richtig und sollte möglichst bald geändert werden.
![bildschirmfoto 2018-01-15 um 16 39 27](https://user-images.githubusercontent.com/11296947/34950368-454fe46c-fa13-11e7-974b-28f72c7d56df.png)

**Comment by wrkb** [comment]
Wieso ist das nicht richtig? Wir arbeiten nach wie vor so und ich wüsste nicht, wie es sonst gehen sollte? Gab es Änderungen?

**Comment by AstridSemm** [comment]
Damit ein Artikel auf der Startseite angezeigt werden soll, muss in den Theme Options die entsprechende Kategorie angegeben werden; das Schlagwort "startseite1/2/3" dient dazu, bestimmte Arikel *dauerhaft* auf der Startseite anzuzeigen, obwohl es aktuellere Artikel aus der Kategorie gibt, die auf der Startseite angezeigt werden, Karsten.

**Comment by wrkb** [comment]
Verstehe. Ja, die Anleitung war wohl noch für fau.de damals verfasst worden, wo die Kategoriefrage nicht so im Raum stand. Danke für die Aufklärung.

**Comment by xwolfde** [comment]
Also ich verstehe das Problem auch nicht so ganz; Aber vielleicht bin ich betriebsblind.
Im Backend unter den Theme Options ist die Funktionalität des "Positionierungs-Tags" ausführlicher erklärt.
Sowohl im bisherigen Theme Options
![theme-options-tenplates-20180213](https://user-images.githubusercontent.com/1070669/36147257-de9df54a-10b7-11e8-8ffd-fcc21ff8c15e.png)


als auch in der kommenden Customizer-Sicht.
![customizer-templates-20180213](https://user-images.githubusercontent.com/1070669/36147251-d34bf3e0-10b7-11e8-9231-b4ad9c65534c.png)

Da steht recht eindeutig, daß zunächst die Artikel mit den Tags genommen werden (und dort auch nach gegebener Anzahl). Dies dann unabhängig von der Kategorie.

Erst nachdem die Tags abgearbeitet wurde, kommen danach weitere Artikel die aus einer Artikel-Kategorie gewählt werden.

Wenn also angegeben ist, daß 
-max. 5 Newsartikel angezeigt werden sollen 
- max 2 Artikel mit selben Positionierungstag angezeigt werde
- es 2 Artikel mit "startseite1" und 1  Artikel mit "startseite3" vorhanden sind 
und 
- als Kategorie "Blafasel" angegeben ist

dann werden
zuerst die beiden Artikel mit den Tag startseite1 gezeigt, dann der eine Artikel startseite3 und dann  noch 2 Artikel der Kategorie "Blafasel".

Die Metabox bei der Artikeleingabe soll die ganze Erklärung  natürlich nicht wiedergeben. Deswegen stehen dort nur die wesentlichen Dinge.

**Comment by AstridSemm** [comment]
Der Text in der Metabox ist eben so verkürzt, dass man meinen könnte, Artikel, die auf der Startseite angezeigt werden sollen, müssten das Tag "startseite" haben. Das ist missverständlich und gehört in der Metabox umformuliert. Zum Beispiel: "Damit ein Artikel dauerhaft oberhalb der neueren nachfolgenden Artikel angezeigt werden kann..."; sowas in der Art.

**Comment by xwolfde** [comment]
das wird bei dem customizer nicht mehr notwendig sein, da beim customizer die änderung sofort sichtbar wird. 

ab der neuen version drin. Und auf Beta
