### ISSUE TITLE
News auf Unterseiten in Galerie

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Einrichtungen#431]
Als Anfrage kam der Wunsch herein, die News nicht untereinander, sondern in einer Art animierter Galerie anzeigen zu können. Als Beispielseite wurde http://islandlab.uac.pt/ genannt. Auch wenn wir diesen Wunsch sicher derzeit nicht erfüllen können, ist die Idee nicht schlecht und kann auf die nice-to-have-Liste.

**Comment by xwolfde** [comment]
Wird über eine kommende Funktion in rrze-elements bereit gestellt.
