### ISSUE TITLE
Menü "Weitere Webauftritte"

### ISSUE THREAD

**Issue by rvdforst** [RRZE-Webteam/FAU-Einrichtungen#433]
Dies ist ein Vorschlag eines unserer Kunden:

Das Headermenü "Weitere Webauftritte" rutscht in der mobilen Ansicht nach unten, ordnet sich jedoch über den individuellen Menüs "Aktuelles" und "Informationen für" ein. Es wäre gut, wenn "Weitere Webauftritte" in der mobilen Ansicht stets ganz nach unten rutscht.

![weitere_webauftritte](https://user-images.githubusercontent.com/299916/35614562-d1183086-066f-11e8-8836-996ba954800f.png)

**Comment by wrcg** [comment]
es wäre auch gut, wenn die Überschrift "Weitere Webauftritte" gar nicht auftaucht, wenn es keine weiteren Webauftritte gibt (Beispiel: https://research-future.fau.de)

**Comment by xwolfde** [comment]
Position: Ist in Diskussion dies in das Overlay-Menü zu tun. Zur Neugestaltung der responsiven Darstellung wird es vor Ostern ein Entwirf geben.
Kein Titel bei leerer Liste: Ist in der nächsten Version drin

**Comment by xwolfde** [comment]
Neues resp. Design wird in Auftrag gegeben. Wird aber noch dauern.
