### ISSUE TITLE
Accordionbalken offen lassen bei Browser-Zurück

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Einrichtungen#435]
Wunsch: Wenn man aus dem Accordion heraus einen Link anklickt und anschließend wieder mit dem Browser-Zurück-Button auf die Ursprungsseite geht, wäre es schön, wenn das vorher angesprochene Accordion noch geöffnet wäre.

**Comment by xwolfde** [comment]
Geht nur bei Speicherung der Status in Cookies oder Browser-Store. => Datenschutzrelevanz => Zwang zum Cookie Hinweis auf der Website gemäß EU Richtlinie. 
Ist es das wert?

**Comment by AstridSemm** [comment]
Um ehrlich zu sein: Nein, das ist es nicht wert.

**Comment by xwolfde** [comment]
Wir hatten es auch schon einmal geklärt. Da wir die Accordions eh ausbauen und in Elements auslagern werden, welches mehr Funktionen mitbringt, kann man es da noch einmal aufbringen.

**Comment by xwolfde** [comment]
moved here https://github.com/RRZE-Webteam/rrze-elements/issues/3
