### ISSUE TITLE
Hauptnavigation in der mobilen Ansicht

### ISSUE THREAD

**Issue by rvdforst** [RRZE-Webteam/FAU-Einrichtungen#437]
Es gibt einen Bug in der Hauptnavigation/mobile Ansicht: Menüpunkte von Ober-Navigationspunkten rutschen über den Portal-Menü-Button, aber nur, wenn der Ober-Navigationspunkt weiter hinten in der Reihenfolge ist. Könnte es daran liegen, dass die Menüpunkte unter „Institut“ im Backend nicht als Unterseiten von „Institut“, sondern als Kinder der Hauptseite eingestellt sind? Jedenfalls sollte es so nicht sein (rechts).

(vgl. https://geographie.cms.rrze.uni-erlangen.de/)
Das Problem tritt sowohl in Chrome und Firefox (Android) als auch in Safari (iOS) auf.

<img width="699" alt="bildschirmfoto 2018-02-12 um 16 07 56" src="https://user-images.githubusercontent.com/299916/36103275-32d6e24c-100f-11e8-92ec-3aa9811484d3.png">

**Comment by xwolfde** [comment]
Strange. 
Muss geschaut werden. Trotzdem ist der Kunde unabhängig davon darauf hinzuweisen, daß man nie mehr als 7 Elemente auf einer Navigationsebene haben sollte.  
Im obigen Beispiel wäre eine bessere Aufteilung der Struktur auch inhaltlich sinnvoll.

**Comment by Albager** [comment]
Bisher wurde über die Menüpunkte in der Hauptnavigation intern noch nicht weiter beraten. Persönlich finde ich jedoch die Darstellung der aktuell 10 Menüpunkte unter "Institut" in der Hauptnavigation _in der normalen Ansicht_ (siehe Screenshot) eigentlich ganz gut - es erscheinen zwei Spalten, inhaltlich sind die Spalten in der normalen Ansicht m. E. dann auch durchaus sinnvoll gruppiert (es gibt ja kein Zitat/Bild, das den leeren Raum im Dropdown bei "Institut" füllen würde).

![hauptnavigation_institut](https://user-images.githubusercontent.com/11389126/36215160-9f5d65ec-11ab-11e8-90ee-30067b361246.png)

**Comment by xwolfde** [comment]
Jupp, da bin ich auch noch nicht zufrieden mit der Aufteilung - die Spalten sollten eigentlich bündiger sein. Da ist noch ein Problem im CSS.

**Comment by xwolfde** [comment]
Wird von Extern neu gestaltet.

**Comment by xwolfde** [comment]
erledigt, kommt ab neuer Version. Abnahme durch VP morgen avisiert
