### ISSUE TITLE
Darstellung von Kontaktseiten (Bilder, mobile Ansicht)

### ISSUE THREAD

**Issue by rvdforst** [RRZE-Webteam/FAU-Einrichtungen#438]
Die Kontaktbilder werden auf Kontaktseiten im Verhältnis zum Rest m. E. überproportional groß dargestellt.

In den Kontaktübersichten (links) könnte die Darstellung der Kontaktbilder ebenfalls noch ein bisschen kleiner sein (betrifft mobile Ansicht), so dass der Univis-Infoblock rechts daneben rutschen kann.

In der mobilen Ansicht der Kontaktseiten (rechts) nehmen die Kontaktbilder fast den ganzen Bereich ein.

Allgemein ist die Dopplung des post names („Achim Bräuning“ im grünen Header) mit dem aus UnivIS verknüften Kontaktnamen („Prof. Dr. Achim Bräuning“ in der Überschrift) unschön. Man müsste für Personen- und Einrichtungsseiten den post name durch den UnivIS-Namen ersetzen (natürlich nur, wenn für einen Kontakt eine UnivIS-Verknüpfung besteht).

(vgl. https://geographie.cms.rrze.uni-erlangen.de/personen/)
Browser-Ansichten in Chrome und Firefox (Android) und in Safari (iOS).

<img width="698" alt="bildschirmfoto 2018-02-13 um 09 00 05" src="https://user-images.githubusercontent.com/299916/36139050-58d9ce0e-109c-11e8-9bb6-297ac2bf64ab.png">

**Comment by xwolfde** [comment]
1. Zum Titel in der Breadcrumb.

Da haben wir widersprüchliche Anforderungen:
Wir zeigen oben in der Breadcrumb den Titel der Seite (bzw. des Posttypes an).
Der Titel des Personeneintrags ist absichtlich nicht identisch mit den zusammengebauten Feldern "Titel Vorname Nachname". So wollen einige Einrichtungen als Titel beispielsweise sowas haben: "Lehrstuhlinhaber Prof. Dr Name".  
Außerdem gibt es auch den Bedarf Pseudonymer Kontakteinträge, bei denen der Titel ebenfalls nicht identisch mit "Titel Vorname Nachname" sein kann. Bspw: "Sekretariat Forschungsgruppe Wahlen".

Um dieses Problem zu lösen und dabei auch das Problem der Zuordnung zu einer anderen Seitenhierarchie zu lösen, ist vorgesehen, dass man stattdessen eine normale neue Seite anlegt. DIeser kann man einen beliebigen eigenen Titel geben und sie dann einer belieben Hierarchie zuordnen.
Als Inhalt dieser Seiten wird dann der Shortcode [kontakt id="" format="page"] eingefügt.
Der format="page" ist genau dafür gedacht, daß man die Darstellung der Personenseite auf einer beliebigen Seite einfügen kann.

2. Zu den Bildgrößen: Da müssen wir schauen. Momentan ist es so gelöst, dass bei der Seitendarstellung eines Kontakts ein großes BIld verwendet wird - die responsive Darstellung auf Smartphones wurde aber da wohl leider vergessen.

**Comment by Albager** [comment]
Der Workaround zum Titel in der Breadcrumb wäre aber für unseren Fall ziemlich aufwendig, denn alle Kontakt-Seiten müssten in normale Seiten überführt und entsprechend umgebaut werden. Wäre es nicht eine sinnvolle Option, im Bearbeitungsmodus von Kontakt- oder Einrichtungsseiten eine Checkbox hinzuzufügen, wie der Breadcrumb-Titel lauten soll bzw. dass dieser auf Wunsch auch durch den Namen inkl. Titel bei UnivIS-Verknüpfung ersetzt werden kann?

**Comment by xwolfde** [comment]
Die Idee gefällt mir. Können wir uns überlegen. Aber das würde trotzdem die URI nicht ändern...

**Comment by Albager** [comment]
Meinen Sie mit URI den "Endpunkt" der Breadcrumb-Navigation (=Seitentitel) im grünen Bereich oder die URL der Personenseite? Ersterer könnte ja dann wie gesagt ersetzt/überschrieben oder ausgeblendet werden (oder verstehe ich etwas falsch?).

**Comment by xwolfde** [comment]
Mit URI meine ich den Teil der URL nach dem Domainnamen.

Die Kontaktenseiten würden bei
     $einrichtung.fau.de/person/$vorname-$nachname/
bleiben, auch wenn wir in der Darstellung der Seite den Titel ändern.

**Comment by Albager** [comment]
OK, aber das wäre ja so in Ordnung - dass in den URLs für Einrichtungsseiten sinnvollerweise .../einrichtung/... stehen sollte, ist glaube ich schon in einer anderen Issue vermerkt.

**Comment by xwolfde** [comment]
in der nächsten version gefixt
