### ISSUE TITLE
Bildlinks ohne Box-Shadow

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#441]
Beim Ili wurde eine Adaption der Bildlinks gemacht, in dem der Box-Shadow der Bilder weggenommen wurde.

Zum Vergleich hier fau.de:
![bildlinks-fau de-20180215](https://user-images.githubusercontent.com/1070669/36269139-aa0e85c0-1278-11e8-97c0-8eefa6dab669.png)

Und hier ili.fau.de:
![bildlinks-ili fau de-20180215](https://user-images.githubusercontent.com/1070669/36269145-ae331af8-1278-11e8-8bfe-8351b99459b2.png)

Ohne Box-Shadow sähe es bei uns so aus:
![bildlinks-fau de-ohnebs-20180215](https://user-images.githubusercontent.com/1070669/36269281-18fef758-1279-11e8-9f12-dea361585fc8.png)

Wäre dafür, es so zu machen. Meinungen?

**Comment by wrkb** [comment]
Dafür. Die Boxshadows bei den Portalbildern (also den bebilderten Menüs auf Portalseiten) sollen bleiben, dort ist es einheitlich. Aber der Logoslider ist gerade auf fau.de so unregelmäßig, die Schatten bringen tatsächlich keine Vorteile.

**Comment by xwolfde** [comment]
im dev umgesetzt, kommt in der nächsten Version
