### ISSUE TITLE
Widgets im Inhaltsbereich von Seiten?

### ISSUE THREAD

**Issue by Albager** [RRZE-Webteam/FAU-Einrichtungen#448]
Wie kann man das Seiten-Widget (oder generell jedes Widget) in den Inhaltsbereich einer Seite (und nicht nur in die Sidebar/in den Footer o. ä.) bringen?

https://premium.wpmudev.org/blog/widgetize-page-post-template-wordpress/

**Comment by xwolfde** [comment]
Gar nicht. Wozu sollte das gut sein?

**Comment by Albager** [comment]
Zum Beispiel könnte man damit - vorausgesetzt, es gibt enstprechend viele Beiträge mit entsprechend vielfältigen Schlagwörtern - eine coole, große Schlagwort-Wolke als alleinigen Seiteninhalt einstellen (das wäre meine Idee für die Darstellung unserer studentischen Projekte und Exkursionen statt eines schnöden Menüs). Kann ich das mit dem TinyMCE realisieren?

**Comment by xwolfde** [comment]
Jetzt ohne zu schauen, nur aus der Erinnerung: Um eine Tagcloud zu machen, braucht man schlicht eine normale unordered list. Dieser gibt man dann die <ul class="tagcloud">..  </ul>.
Ich glaub wir haben das damals generisch als ul-Klasse gemacht egal wo die ist.

**Comment by Albager** [comment]
OK, da scheint es was zu geben. https://github.com/search?q=org%3ARRZE-Webteam+tagcloud&type=Code

Ich verstehe nur nicht ganz, ob und wenn ja wie ich dann die gewünschten Tags bzw. Kategorien einstellen muss. Sollen die als `<li>`-Elemente der unordered list genannt werden?

**Comment by xwolfde** [comment]
Die Liste müsste man von Hand eingeben. Wenn man eine tag Cloud will, dann will man die Items eh beeinflussen...
Aber Sie haben recht, handlich ist das nicht.

Aber trotzdem geht die ursächliche Frage zurück? Wozu soll das gut?  Lohnt sich der Aufwand?
Wir haben es mit Inhaltsseiten zu tun. Und Navigationen sollen einheitlich sein. Es wäre nicht gut, wenn Dinge, die nicht als Navi vorgesehen sind, als solche in Verwendung gerieten. Die Tagclould könnte aus optischen Gründen Verwendung finden. Das wäre ein Grund in Ausnahmefällen. 
Nur: Die Tagcloud bringt auch Nachteile, die wir lösen müssen: Semantisch ist es nur eine lange Liste. Für jemand mit Optik&Maus ist das kein Problem. Aber das sich vorlesen lassen als Liste oder da durchtabben wäre ungut.

tl;dr: Ich bin mir nicht sicher, ob das nicht mehr Nachteile bringen würde als Vorteile und uns viel Aufwand kosten würde um es "sauber" und einfach bedienbar zu machen.

**Comment by Albager** [comment]
Könnten Sie bitte mal ein HTML-Beispiel für die Struktur der `<li>`-Elemente der Schlagwörter 'startseite' und 'bolivien' zur Darstellung in einer tagcloud mit `<ul class="tagcloud">...</ul>` geben?

**Comment by xwolfde** [comment]
Hab mir das nochmal angeschaut: Wenn wir da was umsetzen, wäre das in Form eines Shortcodes zur Einblendung eines Menüs denkbar. Diesen müsste man dann ein Darstellungstyp geben. Es gibt bereits ja eine Darstelluing des "Organigramms", was auch nur ein Menu ist in der Ausgabeform.

Das Problem bei einer Tagcloud ist aber, daß hier irgendwo eine Wertung / Größenangabe herkommen muss. Bei den Kategorien wird schleicht die Zahl der Beiträge hergenommen.

Wenn man aber eine Tagcloud als Linklist zu Seiten machen will, muss man eine andere Zählerung/Priorisierung definieren. Die Frage ist also wo? Und zwar auf eine "Autorfreundliche" Art.

**Comment by Albager** [comment]
Die gewünschte Tagcloud im Seitencontent würde ich mir exakt so vorstellen, wie es jetzt im Widget / in der Sidebar funktioniert, sprich: erzeugt aus den Schlagworten von Beiträgen einer entsprechenden Beitragskategorie.

**Comment by Albager** [comment]
Bzgl. des Seiten-Widgets ist die selbe Frage offen: Es wäre toll, wenn man das einfach nur in den content einer statischen Seite bringen könnte.

**Comment by xwolfde** [comment]
WIdget in dem Contentbereich werden wir erstmal nicht umsetzen, da dies mit Blick auf kommende Editor-Blocks und den neuen Shortcodes aus RRZE Elements redundante Arbeit wäre
