### ISSUE TITLE
Publikations-Galerie mit externen Bildquellen+Links, anpassbare Vorschaubilder (WP Gallery Custom Links Plugin?)

### ISSUE THREAD

**Issue by Albager** [RRZE-Webteam/FAU-Einrichtungen#449]
Es wäre toll, wenn man für Publikationen eine Bildergalerie mit externen Bildlinks und externen individuellen Links zu den jeweiligen Publikationen erstellen könnte. Idealerweise sollte man (auch allgemein) den Bildausschnitt des Vorschaubilds anpassen und/oder eine absolute Höhe für alle Bilder in der Galerie definieren können. Vgl. https://wordpress.org/plugins/wp-gallery-custom-links/

![publikationsgaleriewp](https://user-images.githubusercontent.com/11389126/36946063-779c6ebc-1fb7-11e8-89a6-f509de43696c.png)

Sollte es prinzipiell nicht gewünscht sein, eine wp-gallery mit externen Bildquellen zu erstellen, wäre es wenigstens gut, einen individuellen Link zur Website der Publikation für das entsprechende Publikations-Bild definieren zu können, so dass das anklickbare Bild in der Galerie nicht nur die Mediendatei/Anhangseite zeigt.

**Comment by xwolfde** [comment]
Externe Bilder würde das Abmahnrisiko bei unaufmerksamer Benutzung enorm steigern. Die gefahr können wir nicht riskieren.
Und Gegenfrage: Wie sollen denn die Alternativen Bildbeschreibungen der Bilder übernommen werden, die man zwingend braucht?

Eine Alternative bietet aber das Remoter-Plugin, wenn die Bilder auf bekannten Uni-Servern liegen.

**Comment by Albager** [comment]
Ok. Was genau meinen Sie mit dem Remoter-Plugin?

**Comment by Albager** [comment]
Das sieht ja sehr interessant aus. Kann man das Remoter-Plugin schon auf der CMS-Instanz verwenden? Es scheint noch nicht installiert zu sein.

**Comment by xwolfde** [comment]
Bitte hierzu via Mail an webmaster - @bmehler kann dann helfen. Das betrifft ja das Theme an sich nicht
