### ISSUE TITLE
Responsive Image Maps (<map>-tag)

### ISSUE THREAD

**Issue by Albager** [RRZE-Webteam/FAU-Einrichtungen#450]
Image-Maps funktionieren in der mobilen Ansicht nicht mehr. Kommt bei uns bisher allerdings nur an einer Stelle vor: https://geographie.cms.rrze.uni-erlangen.de/forschung/#collapse_0 (Bild unten)

Könnte evtl. mit jquery gelöst werden: https://github.com/stowball/jQuery-rwdImageMaps

![responsiveimagemap](https://user-images.githubusercontent.com/11389126/36946105-f58ad642-1fb7-11e8-8843-fcec5c200776.PNG)

**Comment by xwolfde** [comment]
Grundsätzlich:
Die Bildbeschreibung sagt "Tippen Sie links oder rechts". Was bedeutet das für jemand, der die Seite mit dem Screenreader vorlesen muss und was für eine Suchmaschine?
Von daher funktioniert diese Image-Map schon jetzt nicht...  
Wegen den mangelnden Kontrasten können sicherlich auch Menschen die nur ein wenig Farbsehschwäche haben oder einfach nur bei schlechten Lichtverhältnissen arbeiten, da nichts erkennen...

Für responsive Darstellung: Wie soll es denn gehen, wenn das Bild so feingranular ist und bei Handy dann alles unleserlich ist? Da müsste man vielleicht andres rangehen.  Nämlich indem man für die kleine Auflösung entweder gar kein oder ein andrees Bild verwendet. Dazu kann man gar normal z.B. srcset als Attribut verwenden.  Tipp: Versuchen Sie hier ein alternatives Bild im srcset zu setzen.

Zur Steuerung der Auflösungen können Sie auch die Bootstrap-Klassen verwenden: col-xs-** und col-sm-** und so weiter. Ggf. wäre das eine Alternative.

Trotzdem schönes Beispiel, das zeigt, dass Imagemaps durchaus gehen.

**Comment by Albager** [comment]
Danke für die Hinweise. Das Thema Barrierefreiheit steht auf unserer Agenda - aber bisher wurden nur die alten Inhalte übertragen. Ich werde mal weiter mit den vorgeschlagenen Lösungen experimentieren!

**Comment by xwolfde** [comment]
Auch wenn meine Meinung vielleicht nicht überschwenglich klingt: Wenn was gutes rauskommt, dass wir auch an Leute geben könnten, die eher wenig Affinität zu IT hat, dann immer her damit.

**Comment by wrkb** [comment]
Wir werden wohl übergangsweise Imagemaps einsetzen mangels Alternativen, aber eigentlich sind sie unbrauchbar. Abgesehen von wenigen Ausnahmen, erfasst man nicht intuitiv, dass man in diesem Bild was klicken kann oder es muss erklärt werden (Fahren Sie über das Bild, um...), was guter Usability widerspricht oder eine Erklärung lohnt sich nur für komplexe Inhalte, die quasi unbedienbar werden (kleinteilig, Mobilgeräte etc.). Ist es nicht komplex, ist der Nutzen fragwürdig oder ein Bild wird als Navigationselement missbraucht.

Wir suchen für unseren bestimmten Zweck eine zeitgemäße Alternative und schauen, ob diese so gestaltet werden kann, dass sie auch für andere Zwecke/von anderen wieder genutzt werden kann.

**Comment by xwolfde** [comment]
Die jQuery-Lösung wird aber von den Suchmaschine nicht unterstützt :/
Und wenn wir die Suchmaschinen vernachlässigen und keine Alternative anbieten würde das im Worst Case dazu führen, daß die verlinkten Seiten gar nicht mehr von Suchmaschinen indiziert werden.  Für den Desktop-User ist alles toll. Aber leider kommen ~60% der externen Besucher (und um diese geht es ja) nun mal über eine Suchmaschine rein.

**Comment by Albager** [comment]
OK - wegen dem konkreten Fall halte ich nochmal Rücksprache ob man die Imagemap an der Stelle wirklich braucht; das Bild ist ohnehin nicht ideal und sollte mal aktualisiert werden.

**Comment by xwolfde** [comment]
Ggf. wäre eine Lösung über ein modifiziertes Portalmenu (Shortcode) denkbar, bei dem aber nur ein Bild für alle Kacheln verwendet werden und die Linkziele / Titel dann über der jeweiligen Kachel als Text plaziert sind.

**Comment by Albager** [comment]
Ok - verstehe noch nicht ganz, wie Sie das genau meinen, aber ich bastele mal :wrench:

**Comment by xwolfde** [comment]
Mangels weiteren Bedarf, schliesse ich den Bug erstmal.
Wenn es wieder benötigt wird, muss eine Umsetzung als eigenes Plugin erfolgen und nicht in diesem Theme.
