### ISSUE TITLE
Frage: Externes Bild lädt nicht beim Seitenaufbau

### ISSUE THREAD

**Issue by Albager** [RRZE-Webteam/FAU-Einrichtungen#451]
Nur zum Verständnis: Wenn ich die Seite https://geographie.cms.rrze.uni-erlangen.de/studium/studieninteressierte/ neu aufbaue (Strg+F5), lädt das externe MeinStudium-Logo im unteren Bereich (src="https://meinstudium.fau.de/wp-content/themes/meinstudium/img/logo.png") nicht. Klickt man einmal darauf und wechselt zurück zur CMS-Instanz, wird es jedoch wie vorgesehen angezeigt. Wenn man das Bild aus der eigenen Mediathek einbindet, klappt es problemlos. Mache ich irgendwas falsch?

**Comment by xwolfde** [comment]
Das hat nichts mit unserem Theme zu tun.
![logo-failure-403](https://user-images.githubusercontent.com/1070669/37107344-6382c532-2234-11e8-9729-1e6853154af1.jpg)

Wahrscheinlich eben eine Sicherheitsmassnahme auf der dortigen Seite.
