### ISSUE TITLE
Designfrage zu oembed vs. fauvideo

### ISSUE THREAD

**Issue by Albager** [RRZE-Webteam/FAU-Einrichtungen#452]
Die einzelnen Player der "Videogalerie" unter https://geographie.cms.rrze.uni-erlangen.de/studium/studieninteressierte/ werden nur nebeneinander angezeigt, wenn ich es mit
`<div style="text-align: center">[fauvideo id="20313" width="210" youtube-support="1" showtitle="2"]
[fauvideo id="20318" width="210" youtube-support="1" showtitle="2"]
[fauvideo id="20319" width="210" youtube-support="1" showtitle="2"]
[fauvideo id="20320" width="210" youtube-support="1" showtitle="2"]</div>` mache.

Wenn ich das selbe mit dem oembed-Shortcode `[embed width="210"]https://youtu.be/3dMLwu8V3tI[/embed]` mache, werden die Player übereinander gestapelt.

Gibt es eine inline-style-Lösung, um das auch mit den oembed-Shortcodes hinzubekommen? `style="display: block;"` wird automatisch entfernt...

![image](https://user-images.githubusercontent.com/11389126/37109857-904e3a22-223b-11e8-8ea8-98829b708c06.png)

**Comment by xwolfde** [comment]
Kurz erklärt:
Bei der Darstellung aus FAUVideo wird nicht wirklich das Video eingebettet, sondern ein Bereich mit einem PLatzhalterbild. Bei der oEmbed-Darstellung kommt der HTML-Code in ganzen Teilen vom Provider des Codes mit der Folge, daß dieser auch aus dem Inline-Block ausbrechen kann.

Lösung: 
Die Darstellung aus unserer FAUVideo-Plugin ist die bessere (und neuere) und sollte daher bevorzugt verwendet werden.  Auch für YouTuve-Videos.


Eine Bitte: Hier nicht unbedingt so viele Verständnisfragen rein tun. Das GitHub ist eigentlich für die Weiterentwicklung/Programmierung des Themes gedacht und nicht für Verständnisfragen von Plugins. Fragen zur Nutzung bitte direkt via Mail an webmaster oder auf der Doku-Seite schauen.
