### ISSUE TITLE
Wochentagsinformationen im Kalender und in Feed-Terminen anzeigen

### ISSUE THREAD

**Issue by Albager** [RRZE-Webteam/FAU-Einrichtungen#456]
Bei uns kam intern der Wunsch auf, eine Info über die Wochentage im Kalender standardmäßig mitanzuzeigen - siehe Screenshots. Betrifft die farbigen Täfelchen der Kalender "Anstehende Termine" auf der Startseite, die Listenansicht des Terminkalenders und die Darstellung von Feed-Terminseiten (im Beispiel ein ICS-Feed-Termin). Wäre es möglich dieses Feature miteinzubauen?

![kalender_startseite](https://user-images.githubusercontent.com/11389126/37255770-662b9398-2551-11e8-9e2e-49c66a038953.PNG)

![kalender_terminkalender](https://user-images.githubusercontent.com/11389126/37255773-6caea548-2551-11e8-8c22-1288ae14e76f.PNG)

![kalender_feedtermin](https://user-images.githubusercontent.com/11389126/37255775-761d81ee-2551-11e8-914e-25e03286dfa3.PNG)

**Comment by xwolfde** [comment]
Wir haben ausgehend von dem WCAG-Test ohnehin die Notwendigkeit dort was zu ändern.

Da das Datumsviereck nicht das vollständige Datum enthält, aber nur repräsentative/optischen Zweck hat, soll das Datum entwedre als vollständiger Wert für Screenreader noch hinzukommen oder aber das vollständig ausgeschriebene Datum im Text rechts angezeigt werden.

**Comment by xwolfde** [comment]
Verschoben nach https://github.com/RRZE-Webteam/rrze-calendar/issues/40
