### ISSUE TITLE
Top-Navigation restriktiver behandeln

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#47]
Eigene Klassenangaben für CSS ignorieren und nicht mehr berücksichtigen.
Problem ist:
* Wenn man CSS-Klassen für Elemente eingeben kann, kann man CSS-Klassen nutzen, die nicht dafür vorgesehen sind, die aber auf die Optik deutliche Auswirkungen haben. Z.B. Klassen die Positionierung machen wie bpsw. "pull-left" oder Klassen mit denen die FAU-Homepage markiert werden "fauhome" könnten verwendet werden. Auch andere Klassen, wie bspw. "unsichtbar" etc pp. könnten verwendet werden-
* Die Einheitlichkeit kann nicht mehr gewährleistet werden.

Beispiel siehe Screenshot. (wurde nicht so gemacht, ich hab via Firefox mal rumprobiert)
![screenshot-css-abuse-metamenu](https://cloud.githubusercontent.com/assets/1070669/15007469/9980078e-11d9-11e6-8d46-28e5362e3108.jpg)

**Comment by xwolfde** [comment]
Das nimmt allerdings auch Möglichkeiten, gezielt gewünschte Klassen einzutragen :/
Daher ggf. eher doch nicht?

**Comment by xwolfde** [comment]
Man könnte auch jetzt nichts tun, aber wenn wir die Entscheidung später erst treffen, trifft es im Worst Case dann viel mehr Leute...

**Comment by csw-** [comment]
Hm, eine Whitelist erscheint mir hier gerade am sympatischsten, wenn man es nicht gänzlich deaktivieren will. 

Meine Nutzung beschränkte sich bisher auf "fauhome" um Zugehörigkeiten/Hierarchie herauszustellen bzw. zu verlinken (das heraustellen geschieht ja durch das Logo - dieser ist aber nicht verlinkt), also im Falle der Infothek wird der Link zum Fachbereich (als nächsthöhere Orga) mit dem Pfeilchen versehen.
Das halte ich auch für einen wichtigen Punkt damit der Nutzer zuimindest mit wenig Klicks in der Hierarchie nach oben gehen kann - mögen andere auch anders sehen. 
Andere Formatierungen wie "Fakultätslinks mit Farben" oder "Zeitlich befristete Notizlinks mit Hintergrundfarbe und Styling" halte ich allerdings dann auch schon für kritisch weil das ja in das Farblayout eingreift.
(~~Wenn dieses Hierarchie-Thema auch für andere wichtig genug ist, wie wäre es denn dann mit einer Auswahlliste "Departements" je FakTheme? Dann könnte man die Klassen-Nutzung durch den User auch gänzlich deaktivieren - wenn das dann über die Theme-Konfiguration geschieht. Aber wenn man damit anfängt öffnet man sicher auch wieder die Büchse der Pandora.~~) 
Also im Endeffekt käme man mit einer Whitelist sicher auch aus. Man kann ja mit fauhome anfangen (*hust*) das beeinflusst das Design und Farblayout ja eigentlich nicht und andere Klassen können dann nach public demand ergänzt werden.

**Comment by xwolfde** [comment]
Via Mail hab ich von anderen kollegen auch Zustimmung zur Whitelist bekommen.

**Comment by xwolfde** [comment]
Erlaubte CSS-Klassen in der White wären dann wohl erstmal:
* fauhome
* external

Weitere?  Spezielle Bootstrap-Klassen? Wir können ja den ganzen Bootstrap-Iconschatz nutzen... *hüstel* *geheim* *wink*

**Comment by csw-** [comment]
Hm, Icons sollten lieber nicht freigegeben werden. Am Ende gibt es dann für den gleichen verlinkten "Content-Typ" verschiedene Icons - oder schlicht allgemein unpassende Icons....

**Comment by xwolfde** [comment]
Nach den Feedback und den Erfahrungen mit anderen Kunden ist das ganze etwas problemhefatet: Wir können da zwar eine solche Einschränkung machen, jedoch führt das oft nicht zu einer Einsicht, das man die Dinge die nicht funktionieren, nicht machen soll, sondern es führt zu vermehrten Rückfragen, ob man den Bug nicht behebt...
Wir hatten das ja bei der Hauptnavi auch, wo ich extra die JS-Alertboxen nachträgliche inführen musste...

tl;dr: ich würde es erstmal so lassen wie es jetzt ist.
