### ISSUE TITLE
Schwarze Balken bei Videos im Social Media Footer?

### ISSUE THREAD

**Issue by Albager** [RRZE-Webteam/FAU-Einrichtungen#479]
Videos, die mit dem `[fauvideo]`-Shortcode im content von Seiten eingebunden werden, zeigen das gewünschte Vorschaubild. Fügt man das RRZE-Video-Widget jedoch zum Social-Media-Footer hinzu, wird ober- und unterhalb des Vorschaubildes ein schwarzer Balken generiert - ist das Absicht oder ein Bug?
Vgl. https://www.wordpress.rrze.fau.de/2016/03/18/tipp-ein-video-in-den-social-media-footer-einbinden/
-> da sind die schwarzen Balken links und rechts. Ggf. sollte man den Container, in dem das Vorschaubild landet, im CSS einfach transparent einstellen?

Im Seiten-Content ok:
![rrzevideo_studiumok](https://user-images.githubusercontent.com/11389126/37569024-1fe71a06-2add-11e8-83d8-06035bf35b14.PNG)

Im Social Media Footer nicht ok:
![socialmediafooter_schwarzebalken](https://user-images.githubusercontent.com/11389126/37569019-193233c6-2add-11e8-96d4-3ee998b6552f.PNG)

**Comment by xwolfde** [comment]
Issue verschoben nach https://github.com/RRZE-Webteam/rrze-video/issues/17
