### ISSUE TITLE
Anpassung single-person.php

### ISSUE THREAD

**Issue by endv02** [RRZE-Webteam/FAU-Einrichtungen#48]
Ab Version 2.1.3 von fau-person sollte die Zeile 28 angepasst werden (Umstellung auf Klassen wegen FAU-Theme):
echo FAU_Person_Shortcodes::fau_person_page($id);
Bitte Bescheid geben wenn es drin ist, dann nehme ich den Workaround aus dem Plugin raus.

**Comment by xwolfde** [comment]
Ist im Master-Zweig gemergt. Die neue Theme Verison ist damit 1.5.6
