### ISSUE TITLE
Link auf collapse funktioniert nicht im Linkblock

### ISSUE THREAD

**Issue by Albager** [RRZE-Webteam/FAU-Einrichtungen#480]
Wenn im Linkblock einer Seite ein Link wie https://geographie.cms.rrze.uni-erlangen.de/institut/#collapse_1 gesetzt wird, wird auf der Seite ein Link ohne die collapse-Referenz ausgegeben. Ist das Absicht oder handelt es sich um einen Bug?

Siehe https://geographie.cms.rrze.uni-erlangen.de/personen/

Einstellung im Backend
![linkblock_collapselink](https://user-images.githubusercontent.com/11389126/37570501-c678c988-2af0-11e8-81ce-424162cd2647.PNG)

Ausgabe im Frontend
![linkblock_collapselinkgehtnicht](https://user-images.githubusercontent.com/11389126/37570503-c873f302-2af0-11e8-827a-e34cb646da3f.PNG)

**Comment by xwolfde** [comment]
Feature :/

custom-fields.php, Zeile 1035. 
https://codex.wordpress.org/Function_Reference/esc_url
_"Please note that relative urls (/my-url/parameter2/), as well as anchors (#myanchor) and parameter items (?myparam=yes) are also allowed and filtered as a special case, without prepending the default protocol to the filtered url."_

Konzeptionell sollen an der Sidebar nur Links auf Seiten hin. Für Kontakte sollte man an der Stelle der Kontakt über der Linkliste als ebensolche darstellen, indem man die Funktion zur Einblendung der Kontaktinfos verwendet.

In dem Fall würde ich aber schon sagen, daß es sinnvoll ist.
Aber andererseits werden wir die Akkordions eh neu anfassen müssen, so daß sich möglicherweise die Links eh ändern.

Ich halte das mal offen.  Akkordion-Themen aber bitte bei dem Plugin rrze-elements rein. (Dies ist aber in der Tat ein Thema sowohl von dem Plugin als auch vom Theme).

**Comment by xwolfde** [comment]
Bitte nochmal prüfen, ob es jetzt nach dem Update besser geht.

**Comment by Albager** [comment]
Nein, leider funktioniert der Link auf https://geographie.cms.rrze.uni-erlangen.de/institut/#collapse_1 im Linkblock unter https://geographie.cms.rrze.uni-erlangen.de/personen/ (Beratung & Kontakt -> Sekretariat) auch nach dem Update noch nicht (sofern das Update schon installiert ist?).

**Comment by xwolfde** [comment]
Ok, dann muss das mit der Erneuerung des Akkordions angegangen werden: https://github.com/RRZE-Webteam/rrze-elements/issues/4
