### ISSUE TITLE
CSS-Problem mit Template "Portalindex" vs. Linkblock in mobiler Ansicht

### ISSUE THREAD

**Issue by Albager** [RRZE-Webteam/FAU-Einrichtungen#481]
Wenn für eine Seite mit Template "Portalindex" ein Linkblock eingestellt ist, rutscht dieser in der mobilen Ansicht nicht nach unten, sondern landet ganz oben und überdeckt  den Seitencontent (wie im **[Beispiel](https://geographie.cms.rrze.uni-erlangen.de/personen/)** - habe es dort allerdings wieder umgestellt - den collapse "Alle Mitarbeiter/-innen (A-Z)"). Mit den Templates "Standardtemplate", "Inhaltsseite mit Navi" und "Portalseite" scheint dieses Problem nicht aufzutreten.

Mobile Ansicht mit Template "Portalindex" (nicht ok)
![cssbug_linkblockportalindexmobileansicht_nichtok](https://user-images.githubusercontent.com/11389126/37571605-2b0d75c0-2aff-11e8-98c4-1848eb95b9d8.PNG)

Mobile Ansicht mit Template "Standardtemplate" (ok)
![cssbug_linkblockstandardmobileansicht](https://user-images.githubusercontent.com/11389126/37571627-912ac1d2-2aff-11e8-8326-bfd8168ef522.PNG)
...
![cssbug_linkblockstandardmobileansicht_ok](https://user-images.githubusercontent.com/11389126/37571628-9141e38a-2aff-11e8-9f63-0c09d2b9af80.PNG)

**Comment by xwolfde** [comment]
Naja, der Portalindex ist explizit als Template für ein Portalmenü gemacht, welches eben kein Content oberhalb oder an der Seite hat...

Trotzdem ärgerlich. Müssen wir schauen.

**Comment by xwolfde** [comment]
Mobile Device Ansicht wird im Mai umgestaltet. 
Daher wontfix
