### ISSUE TITLE
News-Sidebar: Unterkategorien einrücken

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Einrichtungen#485]
In der News Sidebar werden Unterkategorien auf derselben Stufe angezeigt wie die darüberliegende Kategorien. Das kann, vor allem, wenn es viele Kategorien gibt, unpraktisch sein und zu einer extrem langen Sidebar führen. Gibt es die Möglichkeit, die Unterkategorien einzurücken und eventuell auch in der Defaultansicht zu verbergen, so dass man die Oberkategorie aufklappen kann?

**Comment by xwolfde** [comment]
SIcher geht das. 
Hier ebenfalls Zusammenhang: #429

**Comment by xwolfde** [comment]
Technisch geht alles. Falls jemand aber optisch was dagegen hat oder bessere Vorschläge, möge er es hier beitragen.

**Comment by Albager** [comment]
Ich würde als einfache Lösung vorschlagen, für das Sidebar-Menü einfach das selbe CSS bzw. Einrückungs-Schema zu nehmen, wie für das Seiten-Widget:
![image](https://user-images.githubusercontent.com/11389126/38032833-d71bb600-329e-11e8-9804-a9db4476cd4c.png)

Ggf. könnte man die Überschriften/Haupt-Punkte ja noch fett machen und farblich abgestufte divs in der jeweiligen Theme-Farbe hinter die Menüpunkte ausgeben (im Prinzip so, wie es jetzt schon ist).

**Comment by xwolfde** [comment]
Beim nächsten update
