### ISSUE TITLE
customizer -Änderung hat keine Auswirkung

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Einrichtungen#486]
![2018-03-21 11_53_33-customizer_ wissen erweitern](https://user-images.githubusercontent.com/9526974/37706107-90c0402c-2cfe-11e8-9ae1-72bb59f5685f.jpg)
Im Bereich "Bühne und Breadcrumb" wird der individuelle Eintrag bei "Titel Startseite in Breadcrumb" nicht übernommen.

**Comment by xwolfde** [comment]
Oh, die Option wurde nicht aus dem Customizer entfernt :(
Schade das die Meldung jetzt erst kommt und nicht in der 2,5 wöchigen Testphase. Jetzt ist es zu spät, dass zu ändern.  
Ein Schaden ist aber nicht vorhanden, da der Text für alle einheitlich sein soll:  Mit dem kommenden Redesign durch die ORGA-Breadcrumb ist vorgesehen, dass diese Option komplett entfällt.

**Comment by xwolfde** [comment]
Anmerkung: Mit der kommenden ORGA-Breadcrumb wird auch die aktuell noch vorhandene Möglichkeit der Abkürzung der Fakultät in der Meta entfallen.
![2018-03-23-10-37-test8 tindu rrze uni-erlangen de](https://user-images.githubusercontent.com/1070669/37822295-5562b77e-2e86-11e8-9c76-f56a671f8502.png)

Sobald die ORGA-Breadcrumb eingebaut und aktiviert wird, wird in den Website-Daten eine Auswahlliste erscheinen (wie im obigen Screensnip), bei dem man die nächsthöhere Orga auswählen kann.

**Comment by AstridSemm** [comment]
Ist das nicht-abkürzen-können des Fakultätsnamens in der Metanavi technisch bedingt oder Designwunsch? Wenn letzteres, bitte ich darum, das noch einmal zu überdenken, wegen des Platzbedarfs für "Rechts- und Wirtschaftswissenschaftliche Fakultät" sowie "Philosophische Fakultät und Fachbereich Theologie". Bei solchen Dingern ist dann der Umbruch und die damit verbundenen Probleme nicht weit.

**Comment by xwolfde** [comment]
Option wird in der nächsten Version aus dem Customizer entfernt sein.
