### ISSUE TITLE
Absatztyp Lead-In

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#487]
Issue über Mail:

> ohne das jetzt irgendwie live ausprobiert zu haben...

```
.lead-in {
        margin: 0;
        padding: 0;
        color: $colorPrimary;
        font-size: $font-size-quotes; /* beinhaltet das bereits die line-height? wenn nicht: line-height: 1.5; */
        font-family: $fontStackSerifs;
        font-weight: 300;
        font-style: italic;
        position: relative;
        @include px2rem($font-size-quotes);
        }
```

Diese Klasse sollte in der _paragraphs.css die gewünschte Optik erzeugen (orientiert an _quotes.css, _notices.css).

Hintergrund:
Der Wunsch geht dahin, dass man bei Seiten/Artikeln einen EInführungsabsatz machen kann. Dieser soll optisch wie ein Blockquote aussehen (außer der Einrückung, die nicht vorhanden sein soll), allerdings semantisch kein Blockquote sein.

**Comment by xwolfde** [comment]
in 1.10.11

**Comment by Albager** [comment]
Nochmal ein kurzes Feedback dazu:

Die Absatzklasse lead-in funktioniert jetzt, allerdings unterscheidet sich der font des Texts im Vergleich zum Blockquote:

![image](https://user-images.githubusercontent.com/11389126/47998157-9a4f3f80-e0fe-11e8-9114-56d8c62bd13b.png)

Könnte man das noch anpassen oder ist der Unterschied im Schriftstil bewusst gewählt?
