### ISSUE TITLE
WCAG 1.3.1. Info und Beziehungen - Ungültige Tabellennutzung

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#488]
Auf verschiedenen Seiten wurden Tabellen dazu missbraucht, einen Text einen hellgrauen Hintergrund zu geben.
Beispiel:
![table-fuer-hintergrund](https://user-images.githubusercontent.com/1070669/37721428-b88d9e4e-2d29-11e8-83b3-5edc9e8ee14a.png)

Offensichtlich gibt es einen "Bedarf" für einen entsprechenden Hintergrund, der so stark ist, daß sich Autoren eines solchen Tricks bedienen. Auch wenn dieser negative Auswirkungen auf Textverständnis und Darstellung (insbes. mobile Darstellung der Seite) haben.

**Comment by xwolfde** [comment]
Mögliche Lösung: Absatzklasse schaffen, die einen entsprechenden Hintergrund setzt.

**Comment by Albager** [comment]
Der gewünschte Effekt kann bis dahin _ohne eine Tabelle zu verwenden_ ganz einfach manuell erzeugt werden. Zum Beispiel:

`<div style="background-color: #F4F6F8;padding: 10px">Das ist ein div mit grauem Hintergrund</div>`

![image](https://user-images.githubusercontent.com/11389126/38028796-4459868a-3294-11e8-86d7-a69060c7886b.png)

**Comment by xwolfde** [comment]
Bitte NIEMALS Inline-Styles verwenden und erst recht nicht für Farben - damit erzeugt man bei Menschen die aufgrund von Farbfehlschwächen darauf angewiesen sind, den Hintergrund selbst zu ändern, eine Barriere, die viel schlimmer ist als eine Semantik-Fehlbenutzung.

**Comment by Albager** [comment]
Ja, ok... Aber kann im CSS klassisch mit ["background-color"](https://www.w3schools.com/cssref/tryit.asp?filename=trycss_text_background) gearbeitet werden oder gibt es da auch eine [bessere Lösung](https://www.w3schools.com/cssref/playit.asp?filename=playcss_display)?

**Comment by xwolfde** [comment]
Das hab ich nicht geschrieben. Es ist kein Problem die Anweisungen in CSS Files zu verwenden . Es kommt aber darauf an, wann: Inline-Styles werden von der Ladereihenfolge als letztes geladen, nach den Userstylesheets. Sie überschreiben daher Userbezogene Modifikationen und dies ist eben nicht erlaubt.

**Comment by xwolfde** [comment]
Die vorhandenen Absatzklassen (ganz unten) um eine mit grau ergänzen:
https://www.beta.wordpress.rrze.fau.de/texte/absatzklassen/

**Comment by Albager** [comment]
Wäre es denkbar, das ggf. mit bootstrap-klassen zu lösen? Etwa https://getbootstrap.com/docs/3.3/components/#panels-alternatives

**Comment by xwolfde** [comment]
Möglich wäre es. Guter Hinweis. 
Da das aber bei den Panels sehr ähnlich zu den Accordions ist, würde ich da lieber noch abwarten, wie sich die neue Accordion-Lösung entwickelt, damit es dort keine Verwechslungsgefahr gibt

**Comment by Albager** [comment]
OK. Dann erstmal simpel grau - soll die Textfarbe wie bei den Tabellen sein oder wie bei den anderen Absatzklassen (schwarz)?

**Comment by xwolfde** [comment]
Alertboxes sind in RRZE-Elements dafür geeignet und verfügbar: https://www.wordpress.rrze.fau.de/plugins/elements/alerts-hinweisboxen/
