### ISSUE TITLE
"Startseite" nicht übersetzt

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#489]
Die Bezeichnung "Startseite" in der Breadcrumb ist auf der englischen  Sprachversion nicht korrekt in "Home" übersetzt.

**Comment by AstridSemm** [comment]
Ja. Toll. Man sieht auch nicht, wo die übersetzten Klamotten dann angezeigt werden. Ich wüßte gern, wo ich genau diesen Punkt finde, bitte.

**Comment by xwolfde** [comment]
Diesen Punkt gibt es so nicht. Loco Translate findet aus den ganzen PHP-Files nur die Begriffe. Aber Loco kann nicht ermitteln, wie das später optisch aussieht.

**Comment by AstridSemm** [comment]
Super. Und woher soll ich jetzt wissen, welches "start page" ich in "Home" umbenennen muss?

**Comment by xwolfde** [comment]
AAAAAAhhh...
vergiss alles.

Die Site war nicht auf English-UK gestellt sondern auf English-US. Und daher wirkt die Übersetzung nicht.
