### ISSUE TITLE
Darstellung Bild in Sidebar bei Personen

### ISSUE THREAD

**Issue by endv02** [RRZE-Webteam/FAU-Einrichtungen#49]
Beim Standardtemplate ist das Bild in der Sidebar über den Kontaktinfos, bei Portalseite und Startseite aber daneben. Ist das Absicht?

**Comment by xwolfde** [comment]
Wurde bei der ENtwicklung nicht berücksichtig, weil diese Nutzung nicht vorgesehen war. Wird gefixt.

**Comment by xwolfde** [comment]
Ok, retour. Das soll so sein.
Habs aber vereinheitlicht, so dass es bei Nutzung vom Shortcode da genauso erscheint
