### ISSUE TITLE
Banner Startseite Einrichtungen

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Einrichtungen#490]
Wenn man eine Website mit der Startseite für Einrichtungen aufruft, dann wird das Banner nicht herunterskaliert; das ist auch gar nicht schlecht so, denn wenn es sich um Fotos handelt, kann man am Ende nichts mehr erkennen. In dem Fall wäre es aber ganz gut, wenn das Banner sowohl horizontal als auch vertikal zentriert werden könnte, damit man den wesentlichen Bildinhalt erfassen kann. Alternativ wäre auch denkbar, dass man das als Admin entsprechend einstellen kann. Wie sehen die Möglichkeiten dafür aus?

**Comment by xwolfde** [comment]
Die Größe und die Dimension der Sidebar ist ganz definiert festgelegt und wird angezeigt. Dies wurde bereits mehrfach von einigen Anwendern genutzt um das Bild genau auf die Maße zu gestalten. Ein automatisches Covern bei falschen Auflösungen würde dazu führen, dass die Leute, die es genau abgestimmt haben und so haben wollen wie es nun ist, plötzlich Probleme haben.
Wir hatten selbes letztes Jahr mal, also wir bei dem Template Fakultätsstartseite das Coververhalten geändert haben. Das gab danach einige Beschwerden.

Den Stress tu ich keinem Entwickler an. Wer auch immer der Entwickler dieser Sache sein sollte.
