### ISSUE TITLE
CSS-Problem mit Seitentitel in mobiler Ansicht

### ISSUE THREAD

**Issue by Albager** [RRZE-Webteam/FAU-Einrichtungen#491]
Wenn im Seitentitel Buchstaben wie (klein) g, p, q vorkommen, werden diese in der mobilen Ansicht vom CSS abgeschnitten, obwohl noch ausreichend Platz nach unten wäre:
![cssmobileansichtnamewirdabgeschnitten](https://user-images.githubusercontent.com/11389126/39259784-a99273a2-48b7-11e8-9776-668ed63bf4d8.png)

**Comment by xwolfde** [comment]
in 1.10.9 drin (auf Beta)
