### ISSUE TITLE
Englische Übersetzung: Großschreibung bei alleinstehenden Begriffen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#493]
Insbes bei Suche sichtbar:
- "documents and images"
- " search website"

sind klein geschrieben.
Eigentlich korrekt, jedoch im Kontext nicht.

Entweder via CSS ein upcasefirst machen oder Übersetzungsdatei anpassen.

**Comment by AstridSemm** [comment]
Ich bitte um upcasefirst, sonst passiert das bei zukünftigen Übersetzungen immer wieder. Man kann nämlich im Übersetzungstool den Kontext nicht sehen und ich bin da aufs Raten angewiesen.

**Comment by xwolfde** [comment]
Geht so nicht. Man muss bei der Übersetzung eben den Kontext beachten.
