### ISSUE TITLE
Individuelle Link-URL für Beitragsbilder und/oder Unterdrückung Beitragsbild im Beitrag

### ISSUE THREAD

**Issue by Albager** [RRZE-Webteam/FAU-Einrichtungen#496]
In der aktuellen Version des Themes ist es nicht möglich, entweder a) für ein Beitragsbild eine individuelle Link-URL (oder eine pdf-Vorschau als Bild mit Link zum pdf) zu setzen und/oder b) die Anzeige eines eingestellten Beitragsbildes IM BEITRAG zu unterdrücken. Diese Optionen wären m. E. dringend erforderlich, um eine höhere Flexibilität bei den Beitragsbildern und dem Erscheinungsbild von Beiträgen im Allgemeinen zu erreichen (betrifft nicht nur pdfs).

Beispiel: Es geht darum, dass wir bei https://geographie.cms.rrze.uni-erlangen.de/workshop-politische-geographien/ als Beitragsbild die erste Seite des Flyers haben wollen (https://geographie.cms.rrze.uni-erlangen.de/files/2018/04/Flyer_A5_Update_Seite_1.jpg), beim Anklicken (IM BEITRAG!) soll man jedoch auf das pdf des Flyers (https://geographie.cms.rrze.uni-erlangen.de/files/2018/04/Flyer_Workshop_NeueRechte.pdf) und nicht auf das Beitragsbild weitergeleitet werden. So sollte der Beitrag aussehen (im Beispiel ein Kalendertermin, der via ICS-Feed aus der Outlook WebApp eingebunden wurde): https://geographie.cms.rrze.uni-erlangen.de/events/workshop-politische-geographien-der-neuen-rechten-von-nation-und-nationalismus-03-04-05-2018/

Ich hoffe es ist verständlich, was ich meine - falls nicht, kann ich gerne noch Screenshots erstellen. Die momentane 'ganz oder gar nicht'-Lösung ist leider sehr unflexibel/unbefriedigend.

**Comment by xwolfde** [comment]
Also in kurz:
Sie wollen Besucher der Seite mit einem Bild auf einen Artikel locken - und dann wenn man auf dem Artikel ist, steht da plötzlich was anderes und das, weswegen man gekommen ist, ist nicht mehr da? ^^

**Comment by Albager** [comment]
Nein :-) Ich möchte, dass man für das Beitragsbild, welches dann IM BEITRAG stets oben rechts ausgegeben wird, sofern es aktiviert ist, einen individuellen link (bspw. auf ein pdf mit dem Veranstaltungsprogramm) setzen kann. Die Weiterleitung von der Blogroll auf den Beitrag und die Präsentation desselben sollen davon unberührt bleiben. Soll ich einen Screenshot machen?

**Comment by xwolfde** [comment]
Publikationen sind im CRIS einstellen.  Dies ist eine Vorgabe der UL an der sich alle Einrichtungen halten sollen. Und dafür gibt es dann eine abgesprochene und definierte Ausgabe. Daher wäre dieser Fall kein Argument. Wer direkt PDFs verlinken will, kann dies über Links im Text oder in der SIdebar tun. Hier wird ja die Artikelfunktion verwendet für Publikationen. Das ist ursächlich schon eine Fehlbenutzung.

**Comment by Albager** [comment]
"Hier wird ja die Artikelfunktion verwendet für Publikationen" - Das verstehe ich nicht ganz. Heißt das, es sollen (oder gar: dürfen?) von den Mitarbeitern keine aktuellen Beiträge mit Hinweisen auf ihre aktuell erschienenen Publikationen (ggf. mit pdf-Anhang) eingestellt werden?

**Comment by wrkb** [comment]
Wir stehen öfter vor der Frage, wie man Bilder verlinken kann/darf/sollte. Gelerntes Verhalten im Web ist, dass ein Klick auf Bilder das Bild vergrößert. Daneben gibt es Bilder mit Navigationsfunktion (Menü, Teaser von Beiträgen), aber um die geht es hier nicht. 

PDFs hinter Bildern finden wir auch problematisch (Usability) und machen wir nur, wenn der Kontext eindeutig ist. Also wenn das Bild auch den Inhalt/das Deckblatt zeigt und ein deutlicher Texthinweise auf die Funktion des Bildes hinweist - oder es sich um eine Liste mit Publikationen handelt (ich prüfe gleich noch mal auf Altlasten). Mit Beitragsbildern darf so etwas gar nicht gemacht werden.

@xwolfde hat also im Sinne von Usability und Corporate Design völlig Recht.

**Comment by AstridSemm** [comment]
Grundsätzlich sicherlich; dann sollten sie aber das PDF höchstens als Bonusmaterial (z. B. zum Ausdrucken) mit einstellen. Dem Wunsch, das Beitragsbild mit dem Link aufs PDF zu unterlegen kann tatsächlich aus Designgründen nicht nachgekommen werden.
Im Übrigen rate ich dringend dazu, Texte auf der Website selbst zu veröffentlichen und - wie oben bereits erwähnt - PDFs nur zusätzlich anzubieten. Das spart dem Besucher an sich einen Klick und einen Ladevorgang und tut zusätzlich der Barrierefreiheit noch einen guten Dienst.
Just my 2cents. ;o)

**Comment by Albager** [comment]
Ich illustriere nochmal, was ich meine. Irgendwie kann ich die Argumente nicht recht nachvollziehen. Welchen Pluspunkt für die Usability bringt es, wenn der User ein verpixeltes, kleines Beitragsbild angezeigt bekommt und im Text erst nach Links suchen muss? Ich illustriere nochmal, was ich meine...

![image](https://user-images.githubusercontent.com/11389126/39574453-936daef4-4ed7-11e8-8508-363588d68885.png)

**Comment by xwolfde** [comment]
Im obigen Bild wäre der korrekte Weg gewesen, im Text wo der Titel der Publikation in fett gesetzt wurde einen Link hinter genau den Text zu setzen, der auf das PDF verweist.
Der LInktext ist dabei dann der Titel.

Dann findet es sogar Google gut,.

**Comment by Albager** [comment]
Ja gut, dann werde ich das den Leuten gerne so vermitteln. Aber es ging ja ursprünglich gar nicht um Publikationen, sondern generell um flexiblere Möglichkeiten im Umgang mit den Beitragsbildern bzw. deren Ausgabe IM BEITRAG. Diesen Fall werden wir wohl noch recht oft haben, da wir auf unserer Website sehr häufig pdfs mit Veranstaltungsprogrammen oder Hinweisen für Studis verlinken / ansprechend präsentieren wollen. Da wäre es schon toll, wenn man die Ausgabe des Beitragsbildes IM BEITRAG zumindest per option unterdrücken könnte. Oder steh' ich irgendwie auf dem Schlauch?

**Comment by wrkb** [comment]
Die Gundfrage ist doch immer, was der Nutzer erwartet. Was anderswo beim Klick auf Bilder passiert. Sobald ein Bild Details enthält, die es sich zu zoomen lohnt oder die man nur durch Vergößerung erkennt, kommen erlernte Muster zu Einsatz (UI Patterns). In diesem Fall Bilderzoom: http://ui-patterns.com/patterns/ImageZoom

Davon abzuweichen bei einem Bild, dass im Design an einem bestimmten Platz eine bestimmte Funktion erhält, geht in Richtung schlechtes Design, weil Nutzererwartungen enttäuscht werden.

Im vorliegenden Fall kann man den Titel nicht lesen. Statt einer größeren Darstellung erhalte ich plötzlich ein neues Browsertab. Das ist schlecht.

Bilder können andere Funktionen haben, aber das muss klar erkennbar werden und ist hier gar nicht ohne Weiteres möglich.

Das Problem kann tatsächlich durch ordentliche Textlinks mit sprechenden Linktiteln gelöst werden. Das Bild, wenn zu Illustrationszwecken gewünscht, kann tatsächlich vergrößern. Einen Link erwarte ich dort nicht.

**Comment by xwolfde** [comment]
Das wars Karsten richtig schreibt.

Ergänzend kommt hinzu: Die  Beiträge  werden nicht nur auf der Startseite gesehen, sie werden auch als Feed bereit gestellt. Dieser Feed wird in andere Websites oder auch in Apps integriert.
Der Feed hat eine definierte Syntax, die ganz klar festsetzt, was Title, Text, UID, URL und als optional zusätzlich das Symbolbild hat. Das Symbolbild wird dabei nicht nur in einer einzigen Auflösung bereit gestellt, sondern in vielen. 
Grundlegend ist jedoch, dass es pro Feed nur eine einzige Quellurl gibt. Dies ist Grundlage der Feed-Syntax. Es macht da auch keinen SInn im XML Zusatzfelder einzubauen für weitere URLs, denn die Feedreader kennen und berücksichtigen nur den Standard.

tl;dr: These are not the droids you are looking for.
Dies ist nicht die Lösung.

**Comment by xwolfde** [comment]
Korrekt. Die Corporate Identity ist da nun mal so.
Wir erlauben schon viel Individualität, aber an der Stelle wäre es zu viel.

Forschungsprojekte kommen auch über CRIS und haben von daher auch bei der Ausgabe bereits ein abgestimmtes Erscheinungsbild.

**Comment by Albager** [comment]
Klar so weit. Dann hoffe ich, dass die Leute dann bereit sind, CRIS entsprechend zu betanken :see_no_evil: :hear_no_evil: :speak_no_evil:
