### ISSUE TITLE
Feedback zu Beta 1.10.8

### ISSUE THREAD

**Issue by Albager** [RRZE-Webteam/FAU-Einrichtungen#507]
- Punkt 1 verstehe ich nicht so ganz - genauso wie Punkt 3. Bezieht sich das auf das Backend? Oder die Übersetzungsfunktion? Jedenfalls kann ich beides als regulärer Besucher von https://www.beta.wordpress.rrze.fau.de/ ja nicht sehen, und die Breadcrumb heißt immernoch "Startseite".

![punkt1_breadcrumbhome](https://user-images.githubusercontent.com/11389126/41489091-f2a9cbbc-70ee-11e8-8c42-d3532e631fb2.png)

![punkt3_breadcrumbstartseite](https://user-images.githubusercontent.com/11389126/41489174-4c3eb5ac-70ef-11e8-8a45-94a5dca3e442.png)

- Punkt 2: OK. Wo wird diese Option denn gewählt?

- Punkt 4: Da kein Zugriff auf das Backend von https://www.beta.wordpress.rrze.fau.de/ besteht, kann man das nicht testen. Interessant wäre auch zu wissen, welche sich genau verändert haben.

- Punkt 5: Wie wär's mit einer Kombination von einem sich wechselnden Play/Pause-Button-Symbol + wechselndem Text?
![image](https://user-images.githubusercontent.com/11389126/41489351-03fdcbf6-70f0-11e8-91fa-46e6b6822fe0.png)

- Punkt 6: Ist das damit gemeint? Find' ich schön. 
![image](https://user-images.githubusercontent.com/11389126/41489510-8de1bdaa-70f0-11e8-8741-74d5fac764b9.png)
Noch schöner wäre es, wenn die farbigen Balken immer nur eine Zeile hoch wären und bei Zeilenumbruch des Texts automatisch vertikal am Absatz/Menüpunkt zentriert würden - dann hätte man nicht das Problem, dass z. B. die Rechts- und Wirtschaftswissenschaftliche Fakultät so einen großen roten Balken erzeugt.

- Punkt 7: OK - kann man auch nicht testen, aber gut zu wissen 😄 

-Slider vs. WCAG (siehe auch Punkt 5): 

> Daher wurde nun auf den „Slick“-Slider in der Version 1.9.0 umgestellt, der wesentliche Dinge erfüllt. Leider erfüllt er dennoch nicht alle Anforderungen an die Barrierefreiheit. Hier müssen wir ggf. nochmal genauer hinschauen. Ebenfalls wurde im Rahmen der Korrekturen festgestellt, dass die Art der Animation nicht ganz problemlos ist. Daher wurde als zusätzliche Option die Animation „Slide“ ergänzt, bei der die SLides auch von rechts in das Bild einfahren.

OK. Hat sich an der Funktionsweise des Sliders im Backend (fixe Kategorien, Sortierung etc.) denn auch was geändert?

---
Mir sind abseits davon noch ein paar optische Dinge aufgefallen:

- ![image](https://user-images.githubusercontent.com/11389126/41490071-a5c19e98-70f2-11e8-99a1-66ccfaee57f7.png)
sieht nicht ideal aus.

- ![image](https://user-images.githubusercontent.com/11389126/41490141-f9ff598c-70f2-11e8-9e64-0224c7dd6ca8.png)

- ![image](https://user-images.githubusercontent.com/11389126/41490184-327ed634-70f3-11e8-95da-b7fcd5557745.png)
wird/wurde der nach-oben-spring-Knopf nicht eigentlich nach kurzer Zeit transparent und erst wieder sichtbar, wenn man scrollt? Bleibt jetzt immer an.

- Man muss bei Touchbedienung immer zwei oder mehrmals mit dem Finger scrollen, bevor die Seite wirklich auch nach unten scrollt. Evtl. passiert das auch nur unter Chrome (Win10/Android)?

**Comment by xwolfde** [comment]
Uh, alles in einem Issue. Jetzt könnte ich Zuckerbergen und mir die mir liebsten Fragen auswählen und den Rest unterm Tisch fallen lassen :)


Zu Punkt 1: Das kann man auf dem Testwebauftritt selbst nicht sehen. Dort sieht man in der Breadcrumb der Unterseiten stets nur "Startseite". Erst bei einem englischen Webauftritt wird dort stattdessen "Home" stehen.

zu Punkt 2: Im Customizer: Daten zur Website

zu Punkt 5: Hatte ich auch bedacht. Leider macht es das ganze dann zu "fett"; Es lenkt dann doch zu sehr vom Inhalt ab. Außerdem ist es damit nicht mehr passend zum Copyrighttext. 
Es wurden mehrere Varianten geprüft und ich hab auch im Internet bei anderen guten Sites geschaut, wie die Lösung am Besten aussehen kann.  Leider gibt es kaum gute Websites, die bei einem Slider eine sichtbare Stopp-Funktion bauen. Ganz glücklich bin ich mit der Lösung auch nicht.

zu Punkt 6: Ja, konkret geht es zurück auf diesen Issue: #498 . Die Abstände wurden beim letzten Update zu groß. Das wurde einfach zurück gemacht. Das die Zeilenhöhe abhängig vom INhalt ist, ist klar. Da könnten die Redakteure sehr wihl erzwungene Umbrüche einbauen.


zu "OK. Hat sich an der Funktionsweise des Sliders im Backend (fixe Kategorien, Sortierung etc.) denn auch was geändert?"
Siehe Screenshot.
Man kann jetzt auf "Slide" statt "Fade" wechseln und es ist nicht (bereits seit der 1.9.7) mehr notwendig eine spezielle Kategorie der Beiträge anzuwählen. Außerdem kann man den Textauszug in der Länge anpassen.


Die anderen Dinge haben jetzt nichts mit diesem Update zu tun, das sollten eigene Issues sein.
Die Broken Images sind Broken Images, weil auf der Testsite nun mal auch Dinge getestet werden ;)
Hat nichts mit dem Theme, sondern mit Inhalten zu tun :)

**Comment by xwolfde** [comment]
Den Issue bgl. der Darstellung von Kategorien in Artikeln haben wir schon hier:
#429
(De aktuelle Stand gefällt mir auch nicht).

**Comment by xwolfde** [comment]
Aus Mail:
"Mir persönlich gefällt der Ausdruck „Stoppe Animation“ nicht. Schöner wäre Animation stoppen/Animation starten"


Finde ich eine gute Idee.

**Comment by wrkb** [comment]
Muss der Text zum Stoppen der Animation laut WACG also sein? Ist leider furchtbar - es sieht aus, wäre da was defekt oder wie deaktiviertes Javascript.. Wenn es so sein muss, dann sollte bitte unbedingt ein Start/Stop-Button hin - unten rechts, wie vorher und wie auch eingängig mMn. Unter den Button kann der Text, der die gleiche Funktionalität wie der Button hat. Passt das zur Tastaturbedienung?

**Comment by wrkb** [comment]
Die Pfeile links und rechts neben der Bühne passen nicht gut ins Design. Der Schatten ist zu heftig, sie sind - für meinen Geschmack - zu dominant. Die Anlehnung an die Haken in den Menüs finde ich nicht schön (wie schon mal erwähnt), die Menühaken sollten nicht anderswo im Design auftauchen. Es gibt ja keine Regel, dass man nur einen Haken haben darf, er muss nur mit anderen Elementen harmonieren. Ich hätte hier lieber dezentere und höhere Blätter-Elemente.

Farblich sehen die Haken bei mir übrigens verschieden aus (links und rechts) oder beide nicht weiß - je nach Laptop-Bildschirm. Kann das bitte jemand mit SRGB-Hardware und an verschiedenen Geräten prüfen? Ich hab gerade nur 2 hier, ohne SRGB. Das ist wohl abhängig vom umgebenden Verlauf des Headers (Täuschung, aber auffallend).

**Comment by wrkb** [comment]
@mduven stimmt. Die Animation beim Mouseover ist auch nicht schon, der Pfeil sollte nicht so heftig springen. Evtl. ist das an das Verhalten bei den Beiträgen angelegt, aber da ist viel viel kleiner.

**Comment by mduven** [comment]
Seh ich auch so!

**Comment by wrkb** [comment]
Der Hinweistext an der Suche braucht noch das Wort bitte:

Es wird nur in diesem Webauftritt gesucht. Um Dokumente und Seiten aus anderen Webauftritten zu finden, nutzen Sie **BITTE** die jeweils dort zu findende Suchmaschine oder verwenden eine Internet-Suchmaschine.

**Comment by xwolfde** [comment]
> Muss der Text zum Stoppen der Animation laut WACG also sein? Ist leider furchtbar - es sieht aus, wäre da was defekt oder wie deaktiviertes Javascript. Man schaut da auch nicht gleich hin - es sieht auch aus wie eine Art Teilüberschrift o.ä.. Wenn es so sein muss, dann sollte bitte unbedingt ein Start/Stop-Button hin - unten rechts, wie vorher und wie auch eingängig mMn. Unter den Button kann der Text, der die gleiche Funktionalität wie der Button hat. Passt das zur Tastaturbedienung?


Das ganze ist ja genau das Problem:
Einerseits wollen wir es nicht heftig und ablenkend haben, andererseits muss es erkennbar sein.

Ich hab in mehreren Ansätzen versucht das Play/Stop-Icon (ihr kennt es ja?) allein zu nutzen. Je nach Hintergrund ist das gar nicht erkennbar. 

Wenn ich den Button rechts über den Text mit dem Copyright tut (kein Problem) sieht das ganze unsymetrisch aus. 

Bzgl. der Pfeile:
Der Schatten braucht da nicht wirklich zu sein bei der AUflösung. Den Schatten hatte ich nur deswegen hinzugefügt, weil bei der AUflösung von 768 bis 1260 die Pfeile auf dem Bild liegen. Wenn das Bild dann aber einen weißen Hintergrund hat, waren sie nicht mehr sichtbar.

![2018-06-18-12-47-test8 tindu rrze uni-erlangen de](https://user-images.githubusercontent.com/1070669/41532075-d0303464-72f5-11e8-9e3f-a1305ad9c433.png)

Klar könnte man den Schatten auf der großen Auflösung wegmachen. Also 2 sind dafür?

**Comment by xwolfde** [comment]
> Der Pause-Button im Logo-Slider sollte übrigens den gleichen Text wie oben der Stop-Hinweis für die Bühne erhalten.

Ja. Für die Umbauten des Sliders auf für die anderen Fälle hab ich noch den Issue offen: #501

**Comment by xwolfde** [comment]
> Der Hinweistext an der Suche braucht noch das Wort bitte:

Den Text kannst du im Backend (jetzt schon) ändern.Das kam schon letzte Version.  Ich tu das aber mal ins Theme als Default. (Das ganze an der Stelle wird eh bald geändert).

**Comment by xwolfde** [comment]
> @mduven stimmt. Die Animation beim Mouseover ist auch nicht schön, der Pfeil sollte nicht so heftig springen. Evtl. ist das an das Verhalten bei den Beiträgen angelegt, aber da ist viel viel kleiner.

Hängt wohl an der Prozessorgeschwindigkeit. Bei meinen Geräten zappelte da nichts. Ich nehm die Transition einfach raus.

**Comment by xwolfde** [comment]
(Add: Ich werde mal die Dev-Doku ergänzen um eine Beschreibung, wie man auf eigenem L/XAMPP seine eigene Testumgebung baut bzw. was man dazu braucht. Dazu wäre aber Feedback willkommen)

**Comment by Albager** [comment]
> Es wird nur in diesem Webauftritt gesucht. Um Dokumente und Seiten aus anderen Webauftritten zu finden, nutzen Sie die jeweils dort zu findende Suchmaschine oder verwenden eine Internet-Suchmaschine.

Braucht es diesen Hinweis überhaupt? Ich finde das irgendwie unnötig. Abgesehen davon funktioniert die Suchfunktion an sich sowieso eher semi-optimal, insb. wenn man nach Personen sucht! (ich meine, das hatte ich schon mal per Mail geschrieben)

**Comment by wrkb** [comment]
> Braucht es diesen Hinweis überhaupt? Ich finde das irgendwie unnötig.

Unbedingt. Es ist nicht logisch für Nutzer, dass man auf einer Universitätswebseite sucht und nur Inhalte von Teilen der Universität erhält. Das git top-down für ZUV-Seiten und bottom-up für Lehrstühle. Nur, weil wir die Fragmentierung gewöhnt sind, ist das außerhalb unseres Mikrokosmos' immer noch etwas sehr Ungewöhnliches.

**Comment by xwolfde** [comment]
Der Text ist optional. Zu finden im Backend unter Customizer: Inhaltsbereiche->Suchergebnisse
![customizer-suchergebnisse](https://user-images.githubusercontent.com/1070669/41535422-89be4612-7302-11e8-9c77-28103dcab59c.png)

Es kam zu dem Text, weil wir von Leuten Anfragen erhielten, warum die Suche keine Ergebnisse anderer Seiten fand. Man kann den Text auch weglassen.

Es ist aber geplant, die gesamte Suchfunktionalität der Website zu bessern. Dazu aber gesondert; das würde das Thema dieses Issues sprengen.

**Comment by xwolfde** [comment]
Hier die Screenshots für die Pfeile mit und ohne Text-Shadow:

Große Darstellung (ab 1350 Pixel Breite):
![slider-mit-textshadown-pfeile](https://user-images.githubusercontent.com/1070669/41536449-ead49b74-7305-11e8-9219-1dc8ee8fb526.png)
Mit Shadow

![slider-ohne-textshadown-pfeile](https://user-images.githubusercontent.com/1070669/41536456-f13070f6-7305-11e8-9f57-a96cad30ae55.png)
Ohne Shadow

Kleinere Darstellung (768 bis 1350) mit Shadow:
![slider-768bis1260-mit-textshadown-pfeile](https://user-images.githubusercontent.com/1070669/41536473-0384685c-7306-11e8-9582-ab85129720f7.png)

**Comment by xwolfde** [comment]
Die Änderungswünsche wurden umgesetzt und sind auf beta sichtbar.

**Comment by xwolfde** [comment]
> Braucht es diesen Hinweis überhaupt?

Am kommenden Donnerstag werde ich auf dem Webmaster-Campustreffen ein paar der kommenden Änderungen "skizzieren", die wir an der Stelle vorhaben (aber nicht selbst umsetzen werden). In Details kann ich noch nicht gehen, da das Endergebniss sich erst am Ende eines Prozesses ergeben wird. Aber über die Richtung des ganzen kann ich schon etwas erzählen.

**Comment by xwolfde** [comment]
Nach Rücksprache mit den Kollegen aus der Webredaktion werde ich diese Version nun die nächsten Tage ausrollen. Wie üblich zuerst Testweise nur mit den "blauen Seiten", erst danach mit den Fakultäten.

**Comment by xwolfde** [comment]
Hab ich noch irgendwas an Feedback für die neue Version und deren Änderungen vergessen? Wenn ja, bitte melden, sonst würde ich den Issue schließen wollen.

**Comment by Albager** [comment]
Hab' jetzt leider nicht alles genau mitverfolgt, aber gerade fällt mir zumindest nichts mehr ein.
