### ISSUE TITLE
Übersetzung im Customizer

### ISSUE THREAD

**Issue by Albager** [RRZE-Webteam/FAU-Einrichtungen#509]
Wenn man die Sprache der Website auf English (US) umstellt, fehlen mit dem Theme 1.9.19 im Customizer die Übersetzungen für folgende Menüstrukturen:
![image](https://user-images.githubusercontent.com/11389126/41561534-788c128c-734a-11e8-846d-d43f9c72e970.png)

Gibt es das schon als Issue / als Punkt auf der todo-Liste / ist es in [Beta 1.10.8](https://www.beta.wordpress.rrze.fau.de/2018/06/15/beta-1-10-8/) bzw. #507 drin?

**Comment by xwolfde** [comment]
Nö, ist noch nicht voll umgesetzt. Es fehlen noch etwa 5% der Übersetzungen. Frontend-Texte sind zu 100% da. Backend dagegen fehlen insbesondere die Erläuterungstexte im Customizer.
Wo/Man-Power und Prioritäten Problem :/ 

Als eigener neuer Issue ist es genau richtig.

**Comment by xwolfde** [comment]
Die wesentlichen Einstellungen im Customizer sind jetzt auch übersetzt.
Es fehlen noch etwa 30 Erklärungstexte.  Aber wer als Admin einer Website für die FAU tätig ist sollte eigentlich auch soweit Deutsch können, dass er/sie da weiterer kommt.

**Comment by Albager** [comment]
Ja, das ist klar - nur hier als Issue, damit es "auf'm Schirm" bleibt 😏

**Comment by xwolfde** [comment]
in der nächsten Version ist die Übersetzung im englischen (UK & US) wieder bei 100%
