### ISSUE TITLE
Shortcode "notice-XYZ" in rrze-elements

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#513]
die notice-Shortcodes sind jetzt auch in der aktuellen Version von rrze-elements. 
Daher diese aus dem Theme entfernen (functions/shortcodes.php, Z.34-49 und 378-412).
 Dann funktionieren auch die Notices mit Titelzeile im FAU-Theme: 
http://www.test.rrze.uni-erlangen.de:2175/rrze-elements/absatzklassen/ vs. https://www.wordpress.rrze.fau.de/plugins/elements/notices-absatzklassen/

**Comment by cassandre** [comment]
Bitte noch die TinyMCE-Menü-Einträge aus dem Editor entfernen.

**Comment by xwolfde** [comment]
ab 1.10.38 aus Code entfernt
