### ISSUE TITLE
Inhalt Überlagerung, Kalender und Sidebarkontakt

### ISSUE THREAD

**Issue by xy23vaja** [RRZE-Webteam/FAU-Einrichtungen#514]
![bildschirmfoto 2018-07-27 um 13 57 11](https://user-images.githubusercontent.com/19708839/43319776-4a92a6fa-91a6-11e8-889b-9a036552f0df.png)
hallo liebes Webteam,
bei der Darstellung eines Kalenders und dem Einblenden der Ansprechpartner in der Sidebar gibt es eine Überlappung.
Vielen Dank schon einmal für die Fehlerbehebung, viele Grüße  von Martina

**Comment by xwolfde** [comment]
Sollte durch Umstellung auf flex grid behoben sein
