### ISSUE TITLE
Contact Form 7 mit double-opt-in erweitern

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Einrichtungen#519]
Es gibt bei uns Formulare, die für die Anmeldung von Newslettern verwendet werden. Hier wäre es gut, eine double-opt-in-Funktion zu haben.

**Comment by xwolfde** [comment]
Das CMS kann nicht in die Verwaltung der Mailsysteme reinschauen, daher in diesen derzeit nicht machbar
