### ISSUE TITLE
Hauptnavigation verdeckt angesprungene Überschrift

### ISSUE THREAD

**Issue by Albager** [RRZE-Webteam/FAU-Einrichtungen#520]
Wenn man z. B. via `href=".../#id"` auf eine Überschrift verlinkt, dann wird diese Überschrift auf der Zielseite zunächst optisch vom Header verdeckt (bis man anfängt, verwirrt nach unten / oben zu scrollen. Betrifft ausschließlich die Desktopansicht, mobile Ansicht OK (s. https://www.geographie.nat.fau.de/datenschutz/#formular).
![image](https://user-images.githubusercontent.com/11389126/45500348-bed20f80-b77e-11e8-9a07-789261b5a104.png)

**Comment by xwolfde** [comment]
Danke für den Hinweis. Müssen wir bei den Bugfix des mobile Layouts angehen.

**Comment by xwolfde** [comment]
In der nächsten Version gefixt. Ist aber etwas "Browsercachewacklig".
