### ISSUE TITLE
Bilder auf Beitragsseiten flexibel einbinden

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Einrichtungen#547]
Zur Zeit werden Beitragsbilder automatisch immer rechts oben im Beitrag angezeigt. 
Es wäre schön, wenn es die Möglichkeit gibt, das Beitragsbild individuell (Position und Größe) im Beitrag zu platzieren, um die Beiträge individueller gestalten zu können.

**Comment by xwolfde** [comment]
Individuell pro Beitrag oder pro Website gesamt?

**Comment by xwolfde** [comment]
Ping für Rückfrage @wrcg

**Comment by xwolfde** [comment]
Issue wird in #703 generalisiert
