### ISSUE TITLE
WP Embeds müssen gestaltet werden

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#55]
- Feste Breite auf 500px suboptimal
- WP Logo im Footer unschön, da müsste eher das Sitefavi sein

**Comment by xwolfde** [comment]
Derzeit leider nur rudimentäre Funktionen dokumentiert :(

Über !important im CSS arbeiten und über Inline-Styles.
http://amaze.website/customizing-wordpress-embed-links-preview/

Was für ein Murks.

**Comment by xwolfde** [comment]
Vielleicht wäre es bei den Murks-HTML was da kommt für alle besser, wenn die Funktion schlicht deaktiviert wird...

**Comment by xwolfde** [comment]
Arg, die Arschlöcher holen sich ja auch noch Google Fonts

`<link id="open-sans-css" media="all" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans%3A300italic%2C400italic%2C600italic%2C300%2C400%2C600&subset=latin%2Clatin-ext&ver=4.5.1" rel="stylesheet">`

**Comment by xwolfde** [comment]
Wir deaktivieren den Scheiss, solange es diesen Schrott reinbringt. EOD.

https://github.com/swissspidy/disable-embeds/blob/master/disable-embeds.php
http://www.netprofit.de/blog/wordpress-oembed-deaktivieren.html

**Comment by xwolfde** [comment]
Plugin https://wordpress.org/plugins/disable-embeds/ tut was es soll und die andeen Embed funktionieren weiter.
http://test8.tindu.rrze.uni-erlangen.de/tests/shortcodes/standard-oembeds/

**Comment by xwolfde** [comment]
@AstridSemm Das "Nichtfunktionieren" von WordPress-Embeddings sollten wir ggf. irgendwo dokumentieren?

**Comment by AstridSemm** [comment]
Wie macht man da ein Label "Für Doku"?

**Comment by xwolfde** [comment]
Wenn du im GitHub auf die Issue-Übersicht gehst, hast du oben eine Lasche "Labels". Da drauf gehend, siehst du dann alle Labels und kannst weitere hinzufügen
