### ISSUE TITLE
Problem mit der Ausgabe der Quicklinks

### ISSUE THREAD

**Issue by rvdforst** [RRZE-Webteam/FAU-Einrichtungen#553]
Wenn ein Quicklink eine URL der aktuellen Website enthält, konvertiert die Ausgabe im Frontend den Quicklink in eine relative URL und Sonderzeichen wie Sprungmarken (# Fragment) werden gefiltert. Zusätzlich zur ungeordneten Liste der Quicklinks wird die CSS-Klasse "tagcloud" hinzugefügt.

**Comment by xwolfde** [comment]
fixed in der nächsten version
