### ISSUE TITLE
Fehler (vermutlich) aufgrund verschachtelter Accordions

### ISSUE THREAD

**Issue by endv02** [RRZE-Webteam/FAU-Einrichtungen#555]
Kunde produzierte weiße Seite (eigentlich viele Accordions drauf, die auch funktionierten), Fehlermeldung im Log:

PHP Fatal error:  Uncaught Error: Function name must be a string in .../themes/FAU-Einrichtungen/functions/template-functions.php:1644\nStack trace:\n#0 .../themes/FAU-Einrichtungen/functions/shortcode-accordion.php(77): getAccordionbyTheme(0, '', '', '', '', '\\r\\n\\r\\n[collapsibl...')\n#1 .../wp-includes/shortcodes.php(319): fau_collapse(Array, '\\r\\n\\r\\n[collapsibl...', 'collapse')\n#2 [internal function]: do_shortcode_tag(Array)\n#3 .../wp-includes/shortcodes.php(197): preg_replace_callback('/\\\\[(\\\\[?)(collap...', 'do_shortcode_ta...', '\\r\\n\\r\\n[collapse t...')\n#4 .../themes/FAU-Einrichtungen/functions/shortcode-accordion.php(42): do_shortcode('\\r\\n\\r\\n[collapse t...')\n#5 ...\n'

**Comment by endv02** [comment]
Scheint reproduzierbar zu sein wenn der Titel im Collapsible leer ist.

**Comment by iamwebrocker** [comment]
hm, 

kann es sein, dass das "$empty(...)" hier das Problem ist (template-functions.php:[1644](https://github.com/RRZE-Webteam/FAU-Einrichtungen/blob/master/functions/template-functions.php#L1644)) ?

```
	if (empty($title) && ($empty($content))) { ... 
```
Das wird nirgends im Code definiert, ich vermute, es ist ein Vertipper.

**Comment by xwolfde** [comment]
+1

@endv02 Wir wollen eigentlich das die Accordions gar nicht mehr vom Theme kommen, sondern von RRZE Elements. Die Accordions aus dem Theme sind nur noch ein Fallback (der auch bald wegfallen sollen). Kannst du RRZE Elements einschalten und schauen ob das Problem dann nmoch existiert?

**Comment by endv02** [comment]
Wenn RRZE Elements aktiviert ist gibt es keinen Fehler.

**Comment by xwolfde** [comment]
Fixed in dev.
Wir sollten aber "bald" den ganzen alten Code rauswerfen und als Prompt stattdessen die Aktivierung von dem Plugin erfordern.
