### ISSUE TITLE
BETA (1.10.33): PHP-Notices und -Warnings

### ISSUE THREAD

**Issue by rvdforst** [RRZE-Webteam/FAU-Einrichtungen#563]
PHP Warning:  Invalid argument supplied for foreach() in /wp-content/themes/FAU-Einrichtungen-BETA/functions/constants.php on line 329
Warning: Invalid argument supplied for foreach() in /wp-content/themes/FAU-Einrichtungen-BETA/functions/constants.php on line 329
PHP Notice:  Undefined variable: wp_embed in /wp-content/themes/FAU-Einrichtungen-BETA/functions/widgets.php on line 66
Notice: Undefined variable: wp_embed in /wp-content/themes/FAU-Einrichtungen-BETA/functions/widgets.php on line 66
PHP Notice:  Undefined variable: wp_embed in /wp-content/themes/FAU-Einrichtungen-BETA/functions/widgets.php on line 67
Notice: Undefined variable: wp_embed in /wp-content/themes/FAU-Einrichtungen-BETA/functions/widgets.php on line 67
PHP Warning:  ksort() expects parameter 1 to be array, null given in /wp-content/themes/FAU-Einrichtungen-BETA/functions/menu.php on line 72
Warning: ksort() expects parameter 1 to be array, null given in /wp-content/themes/FAU-Einrichtungen-BETA/functions/menu.php on line 72
PHP Warning:  Invalid argument supplied for foreach() in /wp-content/themes/FAU-Einrichtungen-BETA/functions/menu.php on line 81
Warning: Invalid argument supplied for foreach() in /wp-content/themes/FAU-Einrichtungen-BETA/functions/menu.php on line 81
PHP Warning:  Invalid argument supplied for foreach() in /wp-content/themes/FAU-Einrichtungen-BETA/functions/menu.php on line 104
Warning: Invalid argument supplied for foreach() in /wp-content/themes/FAU-Einrichtungen-BETA/functions/menu.php on line 104
PHP Notice:  Trying to get property of non-object in /wp-content/themes/FAU-Einrichtungen-BETA/functions/menu.php on line 123
Notice: Trying to get property of non-object in /wp-content/themes/FAU-Einrichtungen-BETA/functions/menu.php on line 123
PHP Warning:  Invalid argument supplied for foreach() in /wp-content/themes/FAU-Einrichtungen-BETA/functions.php on line 338
Warning: Invalid argument supplied for foreach() in /wp-content/themes/FAU-Einrichtungen-BETA/functions.php on line 338

**Comment by xwolfde** [comment]
We live on the edge. We deploy on Friday.  :)

**Comment by xwolfde** [comment]
Welche PHP Version nutzt du?
Bei meiner (7.1.23-2+ubuntu16.04.1+deb.sury.org+1) krieg ich keine Meldung...

**Comment by rvdforst** [comment]
PHP 7.1.24 aber die Fehler waren diejenigen, die ich bei WP-CLI direkt auf dem CMS-Server bekommen habe. Bspw. wp core check-update --debug

**Comment by xwolfde** [comment]
Konnte keine Warnings und Infos mehr feststellen
