### ISSUE TITLE
Bühne // mobile Ansicht

### ISSUE THREAD

**Issue by mduven** [RRZE-Webteam/FAU-Einrichtungen#568]
Hallo, uns ist aufgefallen, dass in der moblien Ansicht die Bühne auf z.B. wiso.fau.de anders dargestellt ist als auf fau.de. Da die Höhe hier geringer zu sein scheint, ist der Text nicht lesbar:

![header_wiso](https://user-images.githubusercontent.com/28564104/49427141-dc71ac80-f7a2-11e8-9995-3703b0278859.png)
![header_fau](https://user-images.githubusercontent.com/28564104/49427184-f7442100-f7a2-11e8-8acb-ec7f32966074.png)

**Comment by xwolfde** [comment]
Ja, weil ihr noch nicht das update habt, welches wir erst kürzlich für die FAU einspielten ...
Ist für heute auch geplant.
Die blauen Themes sind immer Testbed. Erst wenn da alles passt, dann wird es auch an die Fakultätsthemes ausgerollt, da dort vielmehr betroffene sind.

**Comment by mduven** [comment]
Ah gut zu wissen, vielen Dank! :)

**Comment by xwolfde** [comment]
Update ist raus
