### ISSUE TITLE
Beitragskategorie in Portalmenü lässt sich nicht anklicken

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/FAU-Einrichtungen#573]
Ich habe im Portalmenü unter https://www.nat.fau.de/forschung/ bei Nachwuchsförderung eine Beitragskategorie "Ausschreibungen" eingefügt. Der Link lässt sich jedoch nicht anklicken. Auch eine andere Kategorie, die ich versuchsweise eingefügt habe, ließ sich nicht anklicken. Ist das ein Bug? Die Kategorie direkt aufzurufen geht aber: https://www.nat.fau.de/category/ausschreibungen/

**Comment by xwolfde** [comment]
Problem noch vorhanden, aber workaroundable.

**Comment by xwolfde** [comment]
Ab 1.10.39
