### ISSUE TITLE
Sortierung der Beiträge

### ISSUE THREAD

**Issue by anbininf12** [RRZE-Webteam/FAU-Einrichtungen#574]
Aktuell werden die Beiträge nach dem Datum der Veröffentlichung sortiert angezeigt. Nun kann es sein, dass man einen News-Eintrag eines zukünftigen Ereignisses X heute einträgt und morgen ein Ereignis Y, das vor zwei Tagen statt fand. In der Anzeige wird dann das Ereignis Y über X stehen, weil Y nach X veröffentlicht wurde.
Eine Möglichkeit ist, manuell das Veröffentlichungsdatum anzupassen. Sollten aber zwischen X und Y mehrere Ereignisse liegen, müssten im schlimmsten Fall alle Ereignisse inkl X und Y angepasst werden.
Im Backend gibt es den Bereich Top-Event. Dieser beinhaltet auch ein Datumsfeld. Wäre es möglich, über einen Schalter die Sortierung zu ändern, so daß, wenn das Datumsfeld im Bereich Top Event ausgefüllt ist, auch danach sortiert und wenn nicht, dann wird die normale Sortierung nach Veröffentlichkeitsdatum verwendet?
Zusätzlich könnte man dann auch dieses Datum im Titel mit einbeziehen:

6.11.2017: Event

Hier könnte dann der Datumsstring aus dem Datumsfeld des Top-Event-Bereichs generiert werden.

![top_event](https://user-images.githubusercontent.com/20298307/31723753-01c6be8e-b420-11e7-8d07-7d817f0bcb83.png)

**Comment by xwolfde** [comment]
Das kriegen wir leider erstmal nicht gebacken. Die Top Event Liste soll eigentlich auch gerade nicht für mehrere Dinge verwendet werden, sondern nur für einzelne gaanz wenige DInge die man ausnahmsweise in den Vordergrund heben will. 
Für alles andere sollte man entweder den Event-Import unten nutzen oder eben die Sidebartexte
