### ISSUE TITLE
Untertitel verschwindet bei mehrzeiligem Website-Titel

### ISSUE THREAD

**Issue by endv02** [RRZE-Webteam/FAU-Einrichtungen#577]
Wenn der Titel der Website aufgrund der Länge zweizeilig ist, wird der Untertitel nicht mehr angezeigt - innerhalb div class="slogan" erhält dann p class="description" noch die Klasse "screen-reader-text"

**Comment by xwolfde** [comment]
Ja, ist so gewollt. Kam irgendwann letztes Jahr?
Hier ist der Spruch: "Its not a bug, its a feature" wahr,
