### ISSUE TITLE
Überschrift in der Sidebar wird nicht angezeigt

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Einrichtungen#578]
Die Überschrift über der oberen Textbox der Sidebar wird nicht mehr angezeigt. Siehe auch: https://www.helpdesk.rrze.fau.de/otrs/index.pl?Action=AgentTicketZoom;TicketID=687121

**Comment by endv02** [comment]
Liegt daran, dass die schließende Klammer beim h2-Tag von "Titel oben" in der Sidebar fehlt.

**Comment by xwolfde** [comment]
Ab 1.10.37 korrigiert
