### ISSUE TITLE
Optische Gestaltung Submenupunkte des Hauptmenüs

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#582]
Die optische Gestaltung des Untermenüs, welches sich unter den  Hauptmenüpunkten öffnet, ist unabhängig vom unter 1 gegebenen Verhalten, zu ändern:
Die Inhalte darin sind auf oberer Ebene Fett, Unterpunkte eingerückt  und weniger fett.
Zeilenabstände sind hinreichend großzügig und luftig.   Die bisher vorhandenen Bilder und Zitate von Humbold, Einstein und co    entfallen.
 Im Prinzip soll es so umgesetzt werden wie bei der Uni Köln. Vgl. auch #580 .

Auch dies soll nur passieren, wenn im Body-Tag eine Klasse vorhanden ist. Klasse "mainnav-plainview". Ist diese Klasse nicht gesetzt, soll die optische Darstellung so bleiben, wie sie aktuell ist.

**Comment by xwolfde** [comment]
Die bisherige Darstellung des Submenus mit Stand des FAU Theme Designs 1.10 ist wie folgt:
![menu-rollout-fau-2018](https://user-images.githubusercontent.com/1070669/50980446-fe282700-14f8-11e9-8e22-ea635cb62325.jpg)

Die gewünschte Darstellung soll dagegen in Richtung der Uni zu Köln  bzw zu dem RRZE gehen:

Uni zu Köln:
![menu-rollout-unizukoeln](https://user-images.githubusercontent.com/1070669/50980774-c372be80-14f9-11e9-876d-ac29a08b7137.jpg)


RRZE:
![menu-rollout-rrze](https://user-images.githubusercontent.com/1070669/50980730-b2c24880-14f9-11e9-8e6e-f5dad702580b.jpg)



In beiden Fällen sind jedoch bei genaueren Betrachten der Websites Probleme erkennbar:
Wenn bei Köln z.B. beim Punkt dabei ist (Alumni) oder aber ein anderer Unterpunkt zu viele Unterelemente auf einer Untermenüliste hat, sieht es dort uneinheitlich aus.
![menu-rollout-unizukoeln-zuviel](https://user-images.githubusercontent.com/1070669/50980817-d9807f00-14f9-11e9-88fc-2ea1f631c6d6.jpg)



Im Falle dessen, daß das Menü nur aus einem einzigen Punkt ist, wird der Benutzer auch ohne Not dazu verleitet, 2x zu klicken um auf die Seite zu kommen.
![menu-rollout-unizukoeln-einelement](https://user-images.githubusercontent.com/1070669/50980790-cd94bd00-14f9-11e9-943a-b9791e553888.jpg)

**Comment by jkphl** [comment]
@xwolfde Wie kann ich mir Menüs herkonfigurieren, die (wie hier beschrieben und erforderlich) 3 Ebenen haben bzw. das Markup dafür rendern? Wenn ich mir eine Hauptnavigation mit 3 Ebenen anlege, dann werden im Frontend nur die ersten beiden ausgegeben. Übersehe ich eine Einstellung?

**Comment by xwolfde** [comment]
Die Einstellung gibt es noch nicht ;)
Sag mir das HTML, welches die Menufunction ausgeben soll bei der Liste der 3. Ebene und ich bau es ein.

**Comment by jkphl** [comment]
@xwolfde Alles klar, kommt morgen!

**Comment by jkphl** [comment]
@xwolfde Ist es vorgesehen, dass es

a) gleichzeitig Menüpunkte zweiter Ebene gibt, die mal Unterpunkte dritter Ebene haben, mal nicht, und
b) sollen Menüpunkte zweiter Ebene verlinkt sein, auch wenn sie ihrerseits Unterpunkte haben?

**Comment by xwolfde** [comment]
erledigt
