### ISSUE TITLE
HTML der Submenüpunkte einstellen bei Planinview-Darstellung

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#583]
Ist die "plainview"-Darstellung der Submenüs aktiv /(vgl. #582), so ist das HTML des Submenüs leicht anzupassen (Teile des bisherigen HTML-Codes können wegfallen, andere werden anders angeordnet).

**Comment by xwolfde** [comment]
Zur Aktivierung der Darstellung: Customizer -> Erweitert -> Hauptmenu 
![screenshot_2019-01-30-customizer-erweitert-hauptmenu](https://user-images.githubusercontent.com/1070669/51986476-9a15d480-24a0-11e9-9f34-59fd7bd30dea.png)

**Comment by jkphl** [comment]
@xwolfde Im Fall von Menüs dritter Ebene sollte das Markup für einen Punkt zweiter Ebene etwa so aussehen:

```html
<li class="has-sub">
    <a href="#">Link text</a>
    <ul class="level3">
        <li><a href="#">Sublink text</a></li>
        <li><a href="#">Sublink text</a></li>
    </ul>
</li>
```

Zusätzliche Klassen dürfen natürlich gerne ergänzt werden, das ist nur das Minimum.

**Comment by xwolfde** [comment]
Ich hab dir eben nochmal ein Merge-Request geschicht geschickt (https://github.com/tollwerk/FAU-Einrichtungen/pull/2) .

Der HTML-Code ist nun aufgeräumter und enthält nur noch die wichtigen CSS-Classes bei dem ```<li>```-Element.

Folgende CSS-Classes gibt es im ```<li>```-Element :
* menu-item-has-children - nur dann, wenn das aktuelle Element Kinder hat
* current-menu-item - nur dann, wenn das aktuelle Element im Menu identisch ist mit dem aufgerufenen Menuelement
* current-menu-parent - nur dann, wenn die aufgerufene Seite eine Unterseite  im Menu ist.
* current-page-item - nur dann, wenn das aktuelle Element im Menu identisch ist mit der aufgerufenen Seite

Wenn eine Seite aufgerufen ist, wird zusätzlich im ```<a>``` des Menus der aktuellen Seite ein aria-current="page" gesetzt.


Bei dem umrandenden ```<ul>``` wird stets folgendes als Class gegeben sein:
```<ul class="sub-menu level'.$this->level.'">```

In dem Fall, daß die Ebene die erste ist, wird beim Aufbau des Flyouts ausserdem der bekannte Div- drum herum gebaut.

**Comment by xwolfde** [comment]
erledigt
