### ISSUE TITLE
Navigation in der mobilen Darstellung

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#585]
Bei einem Aufruf des Hamburger-Menuicons auf dem Handy  soll das Hauptmenü ebenfalls in Form eines breiten Megamenüs  angezeigt werden anstelle einer schmalen Ansicht auf der rechten Displayseite.

Für etwaige Untermenüs auf Unterseiten (beispiel hier:  https://www.fau.de/studium/im-studium/analyse-der-studiensituation/ )  ist ein optisch angemessener Vorschlag zu machen und danach umzusetzen.
 Hier geht es auch darum, daß die bisher verwirrende Anordnung von weiteren Navigationslinks aufgeräumt wird.

Auch die Metanav-Links die im jetzigem mobilen Design beim Aufruf der  Suche erscheinen, sollen in das Hamburger-Menü wandern.

**Comment by jkphl** [comment]
Mit dem demnächst verfügbaren Update der mobilen Navigation wird es möglich sein, das Verhalten bzw. den Austausch des Logos bei kleinen Bildschirmgrößen über eine CSS-Klasse auf dem `<body>`-Element zu steuern:

* `<body>` ohne Klasse zeigt das Verhalten wie gehabt (Austausch des Logos auf auf kleinen Bildschirmen gegen seinen `alt`-Text)
* `<body class="md-showsitelogo">` unterdrückt den Austausch und hält das Logo auch auf kleinen Bildschirmen sichtbar

**Comment by xwolfde** [comment]
Leider gibt es ein Bug, wenn im Meta-Header das Sprachwidget eingeschaltet ist:
Das Suchicon rutscht sowohl im geöffneten als auch im geschlossenen Zustand des Hamburgers auf die nächste Zeile.

![Screenshot_2019-04-23-Responsive-Bug-Suchicon-HH-zugeklappt](https://user-images.githubusercontent.com/1070669/56592722-81264680-65eb-11e9-8808-0105c4097f1e.png)
![Screenshot_2019-04-23-Responsive-Bug-Suchicon](https://user-images.githubusercontent.com/1070669/56592723-81264680-65eb-11e9-9e1c-0f8d8c7830e5.png)

**Comment by jkphl** [comment]
@xwolfde Ok, sollte zu lösen sein, ist mir durchgerutscht. Ich gehe aber davon aus, dass noch mehr von dir kommt, oder? Das warte ich dann ab, bevor ich hinfasse ...

**Comment by xwolfde** [comment]
Ja, ich teste morgen noch mehr.
Und Donnerstag sind noch andere dabei.
Soll ich für die Rückmeldungen eigene Issues machen oder die an einem bestehenden Issue anhängen?

**Comment by jkphl** [comment]
@xwolfde Kommt darauf an, wieviele es sind, würde ich sagen. Bei 2-3 Kleinigkeiten lohnen sich eigene Issues vermutlich nicht. Ansonsten wären Issues zum abarbeiten vermutlich sinnvoller. Entscheide einfach aus der Situation heraus, würde ich sagen. ;)

**Comment by xwolfde** [comment]
Ich hab aktuell nichts weiter gefunden. Ich werde jetzt aber nochmal eben den Schalter für `<body class="md-showsitelogo">` im Customizer  einbauen.

Eine "Unschönheit" höchstens:
Wenn das Menü von der Zahl der Inhalte gering ist, dann ist das Menü im aufgeklappen Zustand unschön, wenn man sich gleichzeitig auf einer Unterseite befindet und so der blaue Bereich (Hier Bredcrumb + Menüoberlay) doppelt und nur teilweise überlagert erscheint.
![Screenshot_2019-04-24-Bildergalerie – Institut für World Wide Web und kontextbezogener Unicodeforschung](https://user-images.githubusercontent.com/1070669/56644443-f3466c00-667b-11e9-9ee8-6b0fd4b341e5.png)

Wäre es hier vielleicht sinnvoll, eine Mindesthöhe des Menü-Overlays zu setzen, der dem Höhe des Breadcrumb-Bereiches entspricht? Dann würde der Breadcrumb-Bereich stets überlagert sein.

**Comment by xwolfde** [comment]
Nb scheint das Signal auf right: 0px  zu sein statt auf 10%, wie es bei der Breadcrumb der Fall ist?

**Comment by xwolfde** [comment]
Ich denke mal, dies sollte die MIndesthöhe stellen und das Siegel in dem richtigen Abstand nach rechts setzen, oder?

```
.mainnav-plainview .nav .nav-flyout {
    background: url(./img/siegel-zuv-schnitt.png) no-repeat 95% bottom,linear-gradient(to top, #059 0%, #036 100%);
    min-height: 199px;
}
```

**Comment by jkphl** [comment]
@xwolfde Sieht danach aus, ja. Wenn ich es richtig im Kopf habe, dann hatte ich die Einbindung des Siegels auf deine Anregung hin von einem anderen Einsatzort übernommen.

**Comment by xwolfde** [comment]
Ich tu das mal rein. Wobei ich die min.height aber noch mit einem 
`@media (min-width: $screen-md) { } `
kappsele

**Comment by xwolfde** [comment]
Ok, soweit ich sehe bleibt es bei dem Bug mit dem verschobenen Suchicon, wenn der Sprachschalter aktiv ist.

Aber bitte warte tritzdem noch ab @jkphl : Ich werde es gleich auf beta ausrollen zum testen durch andere und morgen wird es im Team mit der VP noch besprochen.

**Comment by jkphl** [comment]
@xwolfde Alles klar, danke! Dann sehe ich für Freitag eine Bugfixing-Runde vor!

**Comment by xwolfde** [comment]
In der mobilen Darstellung gibt es ein Fehler in dem Fall: 
- Man ist als Autor abgemeldet 
- Man ruft die Seite mit Handy auf

Dann wird der Hamburger durch WordPress Icons überlagert.

**Comment by xwolfde** [comment]
Ich mach mal der Übersicht halber einzelne Issues der Bugs. Ich werde sie alle dem MIlestone zuordnen und hier verlinken.

**Comment by xwolfde** [comment]
Gefunden wurden folgende Probleme/Bugs:
#614 
#613 
#612 
#611 

Und eine Rückfrage:
#615

**Comment by xwolfde** [comment]
Bitte vor dem Bugfixen die letzte Version des Dev Branches aus unserem Repo ziehen.

**Comment by xwolfde** [comment]
passt
