### ISSUE TITLE
Falsche Reihenfolge bei Listenansicht von Kontakten in mobiler Ansicht

### ISSUE THREAD

**Issue by endv02** [RRZE-Webteam/FAU-Einrichtungen#587]
In mobiler Ansicht wird die Reihenfolge von Kontakten bei Listenansicht mit Kurzbeschreibungen vertauscht (zu sehen bei https://geographie.cms.rrze.uni-erlangen.de/forschung/ag-moelg/#collapse_0). Siehe auch https://github.com/RRZE-Webteam/fau-person/issues/228

**Comment by xwolfde** [comment]
dup
