### ISSUE TITLE
Listenansicht mit Kurzbeschreibung wird in mobiler Ansicht zerhauen

### ISSUE THREAD

**Issue by Albager** [RRZE-Webteam/FAU-Einrichtungen#589]
Im CSS scheint die mobile Ansicht für die Listendarstellung bei Kontaktübersichten für Kontakte mit Einträgen im Feld "Kurzbeschreibung" vergessen worden zu sein. In der mobilen Ansicht wird ein komischer Zeilenumbruch der Kurzbeschreibung gemacht, dazwischen landen das Foto und der Kontaktdatenblock.  Da es gewünscht wurde, für AG-Mitarbeiter, Studienberater etc. eine solche Funktionsbezeichnung in den Listenansichten zu haben, wäre es toll, wenn die Darstellung in der mobilen Ansicht wie vorgeschlagen funktionieren würde:

![kurzbeschreibung_mobileansichtsosollteessein](https://user-images.githubusercontent.com/11389126/37557286-83da4640-2a02-11e8-946e-4694041e3f0f.png)
_siehe https://geographie.cms.rrze.uni-erlangen.de/forschung/ag-moelg/#collapse_0_
Das verwendete Format des `[kontakt]`-Shortcodes im content-Bereich der Seite:
`[kontakt category="agmoelg" hide="telefon, organisation, adresse, position, abteilung" show="bild, kurzbeschreibung, email" sort="nachname"]`

**Comment by xwolfde** [comment]
Reopened im richtigen Repo

**Comment by xwolfde** [comment]
Ab nächster Version behoben
