### ISSUE TITLE
Stylingproblem bei [content-slider] in Sidebar

### ISSUE THREAD

**Issue by endv02** [RRZE-Webteam/FAU-Einrichtungen#596]
Wenn in der Sidebar der Shortcode [content-slider] verwendet wird (Textbereich), werden spitze Klammern hinzugefügt. Ist bei anderen Themes nicht der Fall, drum hier das Issue.
![institut fur biochemie homepage institut fur biochemie der friedrich-alexander universitat](https://user-images.githubusercontent.com/5851793/51917056-f44e6100-23de-11e9-8a7d-5ee1d2975494.jpg)

**Comment by xwolfde** [comment]
DIe Sidebars im Theme sind aber keine SIdebars in dem Sinne es Namens von WordPress, wo man normale Widgets setzt. Die "Sidebars" sind da eigentlich Bereiche für Texte oben und unten, sowie Links. Sie haben bei dem CI haben auch einen ganz streng definierten Zweck.
Dementsprechend sind dort die Gestaltungselemente auch in einer Form formatiert, die mit den Einsatz des Content-Slides kollidieren.

Problem ist also: Wir haben die Texte im Theme mit CSS formatiert. Die anderen Themes haben dort keine CSS-Angaben.
Daher fällt es bei den anderen Themes nicht auf.
Lösung: Im rrze-elements müsste die Darstellung über die Klassen hierarisch so gesetzt werden, daß sie nicht von im Theme gegebenen Anweisungen überlagert werden.
