### ISSUE TITLE
Schriftfarbe bei Portal-Links weiß auf weißem Grund

### ISSUE THREAD

**Issue by endv02** [RRZE-Webteam/FAU-Einrichtungen#6]
Kam per Ticket:

"bei dem Theme FAU-Einrichtungen ist mir aufgefallen, dass die Schriftfarbe in der Hauptnavigation bei Portal-Links per default der Ostfriesenfahne ähnelt (weiße Schrift auf weißem Grund). Ist das so beabsichtigt?
Vgl. http://heinze.fim.uni-erlangen.de/wp/wp_iz/ (rechts neben „Mitglieder“ ist noch ein  Link „Forschung und Lehre“)."

und die Antwort kam gleich mit:

"Behoben durch:
li.level1.focus.has-sub>a,
.no-js #nav li.has-sub>a {
    color: #036;
}"

**Comment by xwolfde** [comment]
Das müsste mit dem kommenden Design Fix behoben sein. Dann testen...

**Comment by xwolfde** [comment]
fixed
