### ISSUE TITLE
Print-Ansicht

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#60]
Die Print-Ansicht der verschiedenen Templates ist zu prüfen und ggf. zu korrigieren.
Zu viel Weißraum z.b. durch die nicht sichtbare Bühne dann beseitigen. Menü anpassen etc.

**Comment by xwolfde** [comment]
Da muss nachgebessert werden.
Das wird sehr aufwendig, wenn es schön und CI-gerecht werden soll, da wir da ggf. das gesamte Design für Print neu machen müssen, da dies damals offenbar versäumt wurde.

**Comment by xwolfde** [comment]
Rückmeldungen aus Servicetheken vorhanden, wonach eine Lösung erbeten wird.

**Comment by wrkb** [comment]
Wir hatten mal die Anforderung, dass die Webseiten auf Vordrucken mit Logo und farblichem Hintergrund gut aussehen müssen. Möglich wurde das mit einem portablem Browser (der als zweite Instanz neben dem individuellen gleicher Herkunft laufen kann) und Anpassungen in den Layouteinstellungen für den Druck (Firefox in dem Fall).  --> Seite einrichten --> Farben/Hintergrund, --> Ränder/Fuß-/Kopfzeilen...

Könnte ein Workaround sein (mit oder ohne eigenes Papier), wenn nur die Servicetheken und andere geschlossene Nutzergruppen betroffen sind. Einfacher als Redesign.

**Comment by xwolfde** [comment]
Die Probleme wurde behoben.
