### ISSUE TITLE
Improve Workflow: May you create a release for every new version?

### ISSUE THREAD

**Issue by jbhs** [RRZE-Webteam/FAU-Einrichtungen#602]
Hello Webteam, we are using the Plugin GitHub Updater to stay in sync with your latest version of this Theme. The GitHub Updater is looking for new versions via the version # within the style.css if we push update in our WP instances GitHub Updater will update to the latest release version which is 1.8.4 in your repository, therefore we have to force a branch change on every update which will re pull the master. It would be very nice if you could create a new release for every new version number you create. This would improve our update task a lot. Thank you very much for all your improvements 👍

**Comment by xwolfde** [comment]
Hallo,

wir können ruhig auf deutsch schreiben - Sie kommen ja auch aus Hannover .)

Die Releases nutzen wir eigentlich gar nicht wirklich. Dadurch vergessen wir die dann auch...
Wir haben uns darauf geeinigt, den aktuellen Master-Branch als produktiven Zweig zu sehen und checken diesen auch auf unseren Instanzen aus.

Entwickelt wird stets in Dev-branches. Die ggf. auch neu angelegt werden können. 
Wenn die neue Entwicklung von dem jeweiligen Entwickler als "reif" genug angesehen wird um sie auszurollen, wird dieser Dev-Branch in den Beta-Branch gemergt.

Der Beta-branch wird danach (semimanuell: Unser git-Updater merkt dass es eine neue version gibt, erwartet aber ein manuellen Klick auf das Update) auf unseren Beta-Webauftritt https://www.beta.wordpress.rrze.fau.de/ 
ausgecheckt und dort im theoretischen idealfall mindestens Woche von allen Interessierten mit den dortigen Beispiel- und Musterseiten geprüft.

Wenn bei der Prüfung nichts aufgefallen ist, wird der Beta-Branch danach in den Master-Branch gemergt. Und dieser wird dann ebenso semiautomatisch auf unseren Servern ausgerollt.

Hier unser Verfahren:
https://www.beta.wordpress.rrze.fau.de/entwicklung/git/versionsnummern/
