### ISSUE TITLE
Einrichtungstheme ohne Uni-Siegel

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Einrichtungen#603]
Ein Kunde wünscht sich, im Theme FAU-Einrichtungen das Uni-Siegel herausnehmen zu können, für den Fall, dass das Theme für Kooperationen genutzt wird, in denen die FAU als gleichberechtigter Partner (also nicht führend) arbeitet. Nachdem das ein meiner Ansicht nach legitimer Wunsch ist, gebe ich das mal als Frage weiter: Kann man das Logo "abschaltbar" machen? (In dem Fall müsste wohl auch das FAU-Logo aus dem Footer und der Backlink auf die FAU aus der Metanavi oben herausgenommen werden können).

**Comment by xwolfde** [comment]
Ist/war bereits in Planung, musste aber aufgrund anderer Prioritäten zurückgestellt werden.

Frühestens ab Mai kann hier nochmal drüber nachgedacht werden und ggf, ein Auftrag erteilt werden.

**Comment by xwolfde** [comment]
Im nächsten Update enthalten.
Hierzu muss eine Website vom Typo Kooperation sein.
Dann und nur dann wird die Option frei geschaltet im unteren Bereich zwei Widgets zu nutzen.
