### ISSUE TITLE
Ein Break, der da nicht sein sollte

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Einrichtungen#605]
Ticket: https://www.helpdesk.rrze.fau.de/otrs/index.pl?Action=AgentTicketZoom;TicketID=706992
Der Kunde bindet zwei Videos mit Überschrift darüber ein.

Zwischen der Überschrift des ersten Videos und dem Video selbst ist der Abstand größer als zwischen der Überschrift des zweiten Videos und dem darunter eingebundenen Video. Anfrage bei Rolf ergab, dass da im div ein br vorhanden ist, der da nicht sein sollte. Ich bitte um Pfüfung und ggf. Reparatur.
![break_zuviel](https://user-images.githubusercontent.com/11296947/55611014-89295e00-5784-11e9-8d77-0df4e435722d.jpg)

**Comment by xwolfde** [comment]
Wie erfolgt die Einbindung? Via Video-Plugin (welches?) oder via oEmbed?

**Comment by AstridSemm** [comment]
Verlinkt im Ticket unter: https://www.unternehmensfuehrung.rw.fau.de/master-in-management/studieninteressierte/bewerbungsverfahren-2/

Methode dort: [video width="1920" height="1080" mp4="https://www.unternehmensfuehrung.rw.fau.de/files/2019/04/Einführungsvideo-Bewerbungsprozess-MiM-Du-Form.mp4"][/video]

**Comment by xwolfde** [comment]
Hm... Ist das nicht WordPress-Native @rvdforst ?
Wenn ja, ist das nicht unser Ding.

**Comment by rvdforst** [comment]
> Hm... Ist das nicht WordPress-Native @rvdforst ?
Nein. WP erzeugt kein Break-Tag.

**Comment by xwolfde** [comment]
Ich meine den  [video]  Shortcode. Wo kommt der her? Unsere Plugins haben doch als Shortcode [fauvideo...] ?

**Comment by rvdforst** [comment]
> Ich meine den [video] Shortcode. Wo kommt der her? Unsere Plugins haben doch als Shortcode [fauvideo...] ?

Siehe https://codex.wordpress.org/Video_Shortcode

**Comment by xwolfde** [comment]
OK.. Aber dann ist der doch WP-native und das ganze ist nicht unser Problem?

**Comment by xwolfde** [comment]
Closed, da: Nicht unser Problem. Die Kunden sollen lieber auf unser Video Plugin umstellen, welches optimiert für unsere Bedürfnisse ist und im Gegensatz zur nativen Lösung Datenschutzfreundlicher ist-
