### ISSUE TITLE
media printer bug

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Einrichtungen#608]
Kunde meldet Bug (siehe https://www.helpdesk.rrze.fau.de/otrs/index.pl?Action=AgentTicketZoom;TicketID=708261).

Im Stylesheet _printer.scss sieht der Kunde den Grund für ein (/), das im Ausdruck oben neben dem Logo erscheint. Er macht folgendes Fragment verantwortlich dafür:

@media print {
@page {
  size:landscape;
  margin:1cm
}
abbr[title]:after {
  content:" (" attr(title) ")"

Screenshot aus dem Ausdruck mit Hervorhebung meinerseits:

![issue_print_bug](https://user-images.githubusercontent.com/11296947/55959721-9dc99280-5c6b-11e9-8fa4-0699b1021e4d.gif)

**Comment by xwolfde** [comment]
Wird in der nächsten Version behoben sein
