### ISSUE TITLE
Hover im Overlay hat falsches Margin-Left bei Oberpunkten 

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#611]
Die Mouse-Over-Boxen sind bei den gefetteten Oberpunkten links 
zu nah an der Schrift. Das wirkt arg angeklatscht. Bei den Unterpunkten sieht es hingegen gut aus.

<img width="250" alt="hover-overlay" src="https://user-images.githubusercontent.com/1070669/56747297-fb86d000-677d-11e9-96fd-dd971fcfa8c8.png">

**Comment by jkphl** [comment]
Hab da jetzt mal einen Fix dafür gebaut, allerdings müssen wir aufpassen, dass wir nicht in Scope Creep reinrutschen. Der abstandslose Hinterleger ist bereits Merkmal der aktuellen fau.de-Navigation, das ist nur bislang nicht so stark ins Gewicht gefallen, weil den Menüpunkten immer die kleinen Pfeilchen vorangestanden haben (gegen die sich nun entschieden wurde). Es kann sein, dass Änderungen daran noch weitreicherendere Folgen haben und man mehr Zeit investieren müsste.

Ich habe ein horizontales Padding ergänzt. In dem Fall würde ich dann allerdings davon abrücken, die Menüpunkte dritter Ebene dann nochmal zusätzlich einzurücken — das sieht einfach nicht gut aus. Ich habe sie daher nun in eine vertikale Flucht mit den Menüpunkten zweiter Ebene gestellt und finde, der leichtere Schriftschnitt sowie die Trennlinie zwischen zweiter und dritter Ebene sind zur Differenzierung ausreichend. Wenn das partout nicht gewünscht wird, dann ist das schnell wieder umgestellt.

**Comment by xwolfde** [comment]
passt so
