### ISSUE TITLE
Großes Overlay ist nicht Scrollbar auf mittelgroßen Displays

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#612]
Auf kleinen Bildschirmen ist das Overlay manchmal zu groß für einen Bildschirm. Allerdings kann man nicht runterscrollen, weil nur die Seite darunter scrollt.

**Comment by jkphl** [comment]
@xwolfde Zur Info: Habe jetzt eine ganze Weile gebraucht, um zu verstehen, dass du mit "kleinen Bildschirmen" keine so kleinen Bildschirme meinst, dass die Mobildarstellung greift ... Begrifflichkeiten ... ;)

**Comment by jkphl** [comment]
Die Behandlung dieses Bugs ist sehr problematisch, weil man hier unmittelbar in ein Wespennest stochert: Der ganze Kopfbereich der Desktopansicht ist mit wüsten Konstruktionen hingemarged und absolut bzw. fix positioniert, damit der weiße Menüstreifen beim Scrollen oben im Fenster stehen bleibt. Die Menü-Overlays sind damit ebenfalls dieser Mechanik unterworfen und damit per Definition fix platziert. Der Browser hat keine Wahrnehmung, dass Teile davon außerhalb des Viewports liegen könnten.

Einzige halbwegs taugliche Lösung: Die Maximalhöhe der Overlays muss so beschränkt werden, dass sie höchstens bis zur unteren Fensterkante gehen, und dann müssen die Overlays selbst scrollbar gemacht werden, wenn sie zuviel Inhalt haben. Um einen doppelten Scrollbalken zu vermeiden (Dokument insgesamt und Menü-Overlay) muss zudem dem kompletten Dokument die Möglichkeit zum Scrollen genommen werden, solange das Menü-Overlay offen ist. Ich habe das jetzt mal so umgesetzt — wirklich glücklich bin ich aber nicht. Die einzige anständige Lösung mit sinnvollem Scrollverhalten für das ganze Dokument wäre nur mit einem Totalumbau der Struktur des Kopfbereichs verbunden und liegt definitiv außerhalb des aktuellen Scopes.

**Comment by xwolfde** [comment]
passt so
