### ISSUE TITLE
Überlagerung der Metanav durch WordPress bei kleinen Screens im eingeloggten Zustand

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#613]
Auf Handybildschirmen verdeckt die Wordpress-Toolbar das 
Burgermenü, man kann es eingeloggt nicht klicken und auch nicht sehen.

(Anmerkung: Wenn man eingeloggt ist, ist im Body eine Class "logged-in" vorhanden. Wenn WordPress die Navigation-Bar setzt, ist eine weitere KLasse vorhanden "admin-bar")

**Comment by jkphl** [comment]
@xwolfde Im Moment kann ich das Problem leider nirgends nachvollziehen — vielleicht verstehe ich aber auch etwas nicht richtig. Auf allen Plattformen, die ich testen kann (= meine Entwicklungsinstallation, in die ich mich auch einloggen kann) ist das Menü dort positioniert, wo es hin soll, und funktioniert auch einwandfrei.

Tatsächlich musste ich aber aus genau aus dem Grund die Positionierung des Burgermenüs von `fixed` auf `absolute` umstellen (in einem der Commits der letzten wochen). Ist es möglich, dass ihr das noch mit altem CSS diagnostiziert habt?

Kannst du mir Zugang zu einer Installation verschaffen, in der ich das Problem nachvollziehen kann?

## Screenshot Android

![Screenshot_20190427-090628](https://user-images.githubusercontent.com/4446936/56846165-f20b7e00-68cb-11e9-8c86-ef1b7fb10efc.jpg)

## Screenshot Desktop-Chrome mit Mobil-Simulation

![Schnappschuss_042719_090913_AM](https://user-images.githubusercontent.com/4446936/56846178-1f582c00-68cc-11e9-904d-def01dd5cb81.jpg)

## Sonstige

Auch im Firefox sieht es so aus und funktioniert, andere Browser vermutlich auch ...

**Comment by xwolfde** [comment]
Ich hab es gerade nochmal getestet:
Bei Chrome tritt es bei mir ubnter 370 Pixel auf, bei FF unterhalb 405 Pixel. Beide Desktop, Win)

![grafik](https://user-images.githubusercontent.com/1070669/56852752-3d02b100-691f-11e9-90e6-9456617e2dda.png)


Auf dem Android Handy hab ich es ohne zusammenschieben:

![Screenshot_20190427-190438 1](https://user-images.githubusercontent.com/1070669/56852770-9074ff00-691f-11e9-8630-8df96da12dc4.png)

**Comment by jkphl** [comment]
@xwolfde OK, danke! Ich werde morgen mit diesen Angaben nochmal versuchen, den Fehler zu reproduzieren.

**Comment by jkphl** [comment]
@xwolfde Ich habe jetzt alles nochmal durchgetestet, gerade auch im Hinblick auf die Größenangaben, die du gemacht hast. Leider bleibt es bei mir dabei: Ich kann den Fehler nicht reproduzieren, mit und ohne Sprachschalter nicht (der in deinen und meinen vorherigen Screenshots nicht aktiv war). Es muss irgendeinen sehr instanzspezifischen Unterschied geben. Siehst du eine Möglichkeit, mir Zugang zu einer Instanz zu verschaffen, bei der das Problem auftritt und in die ich mich gleichzeitig einloggen kann? Ich sehe nicht, wie ich das Problem sonst untersuchen und beheben könnte ... :/

**Comment by xwolfde** [comment]
ich schau morgen mal. Könnte es sein, dass die Issuelösung zu den Suchicon/Widget das Problem mit gelöst hat?

**Comment by jkphl** [comment]
@xwolfde Njein, denke ich nicht. Ich hatte das Problem ja vorher schon nicht, und du hast es jetzt auch noch (oder hast du in deiner Instanz noch gar nicht neu ausgecheckt? Dann könnte sich das Problem eventuell tatsächlich schon in Wohlgefallen auflösen ...)

**Comment by xwolfde** [comment]
Die letzte Version von dir hab ich noch nicht gegengepüft: Das eben morgen.

**Comment by xwolfde** [comment]
Ist behoben
