### ISSUE TITLE
Suchicon verrutscht, wenn Sprachwidget aktiv ist

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#614]
Wenn im Meta-Header das Sprachwidget eingeschaltet ist, rutscht das Suchicon auf die nächste Zeile.
Das Suchicon rutscht sowohl im geöffneten als auch im geschlossenen Zustand des Hamburgers auf die nächste Zeile.

![Screenshot_2019-04-23-Responsive-Bug-Suchicon-HH-zugeklappt](https://user-images.githubusercontent.com/1070669/56592722-81264680-65eb-11e9-8808-0105c4097f1e.png)
![Screenshot_2019-04-23-Responsive-Bug-Suchicon](https://user-images.githubusercontent.com/1070669/56592723-81264680-65eb-11e9-9e1c-0f8d8c7830e5.png)

**Comment by jkphl** [comment]
Dasselbe Problem hat nebenbei auch den Sprachumschalter betroffen. Änderung der Positionierungsmethode (von `fixed` auf `absolute`) plus ein paar kleinere Anpassungen haben das Problem gelöst.

**Comment by xwolfde** [comment]
Ok, jetzt tritt das nicht mehr auf.


Allerdings ist unter Handyauflösung nun bei Klick auf das Suchicon die Überlagerung der Sucheingabe nicht ganz schön: Der "Finden"-Button wird semitransparent von dem Hamburger-Menu überlagert

**Comment by xwolfde** [comment]
Siehe Screenshot: (oben)
![Screenshot_2019-04-29 Institut für World Wide Web und kontextbezogener Unicodeforschung – Untertitel der Testsite](https://user-images.githubusercontent.com/1070669/56882550-39c50d80-6a64-11e9-931f-bb73bc923c79.png)

**Comment by jkphl** [comment]
@xwolfde Ich habe nach wie vor das Problem, dass ich diese Thematik (auch die neue) bei mir nicht reproduzierren kann, siehe Screenshot. Könnten wir vielleicht mal eine Teamviewer-Sitzung machen, so dass ich mir das Problem direkt in deiner Instanz ansehen kann?

![Screenshot_20190430-215137](https://user-images.githubusercontent.com/4446936/56989474-cec62480-6b92-11e9-992f-c7fc4508a724.jpg)

**Comment by xwolfde** [comment]
Schau auf meiner Testinstant ( SIehe Mattermost) Bei deinem Screenshot fällt mir aber auch auf, daß bei dir das Edit-Symbol von WP fehlt.

Und auch unabhängig vom Login-Status: Prüf mal bitte die Variante bei der Suche ohne das Suchplugin. (Mal deaktivieren).

**Comment by xwolfde** [comment]
Die Ursache des Bugs ist, dass das Sprachwidget nicht berücksichtigt wurde. Sobald das Sprachwidget mit dem Umschalter für Sprachen aktiviert wurde , wird beim Klick auf das Suchicon die Sucheingabe nicht auf eine neue SPalte unter der Metanav angezeigt, sondern auf der Zeile selbst - wo es dann einerseits die Metanav, andererseits durch das fest positionierte Hamburger wiederum beim Suchbutton selbst überlagert wird.

Ich kümmere mich jetzt selbst um den Bug, da ich nicht weiter warten möchte.

**Comment by xwolfde** [comment]
fixed
