### ISSUE TITLE
Abstand des Overlays von den Menü-Oberpunkten

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#615]
Bei großen Aufflösungen ab md ist der Abstand des Overlay-Menus zu dem Oberpunkten sehr eng.

Es kam die Frage auf, ob man diesen Abstand nicht vergrößern können. 
Bei einer Unterseite mit BReadcrumb beginnt der blaue Bereich der Breadcrumb auch weiter unten.

**Comment by jkphl** [comment]
@xwolfde Ich habe Sorge, dass ich die Beschreibung missverstehen könnte, weil ich Begrifflichkeiten anders verwende. Wäre es dir möglich, mir einen markierten Screenshot zur Verfügung zu stellen, welcher Abstand zwischen welchen Elementen genau gemeint ist? Danke!

**Comment by xwolfde** [comment]
Bei einer Standardseite fängt der Breadcrumb-Bereich (der blaue Teil) unterhalb des Menüs bei eta 190px von top an.
![image](https://user-images.githubusercontent.com/1070669/56882690-9de7d180-6a64-11e9-8b87-f0d5c62527f7.png)


Wenn das Menü aufgeklappt ist, dann startet der Overlay von Top bei 130px.
![image](https://user-images.githubusercontent.com/1070669/56882792-f323e300-6a64-11e9-903f-714b97e05a12.png)

Würde man nun das Overlay nun bei 190px starten, wäre das nicht gut, oder?

**Comment by jkphl** [comment]
Jetzt verstanden, danke.

Ja, sehe ich auch so — der visuelle Zusammenhang zwischen dem aktiven Primärmenüpunkt und dem Fly-Out ist essenziell. Die Anordnung folgt dem Motiv von Registerkarten, der Primärmenüpunkt ist also eine "Lasche nach oben" des Fly-Outs. Eine räumliche Trennung der beiden Elemente macht überhaupt keinen Sinn.

Daneben haben für mich das Kopfbanner (in dem der Seitentitel und die Breadcrumb-Navigation liegen) und die Navigations-Fly-Outs vollkommen unterschiedliche Aufgaben. Die einzige "zufällige" Gemeinsamkeit ist das Blau. Ich sehe deshalb keinerlei Veranlassung, die beiden vereinheitlichen zu wollen, eigentlich eher sogar im Gegenteil.

**Comment by xwolfde** [comment]
ok. Danke
