### ISSUE TITLE
Menüoptionen Navileiste Ebene

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#62]
Die Menüoptionen zur Navileiste (Ebene) sind schwer verständlich. Sind sie notwendig?

Aus einer Mail von @RRZE-Webteam/fau-webredaktion 

> 
>  Die Menüebene steuert auf Inhaltsseiten, was als Link über der linken Navigation angezeigt wird. Das ist eine übergeordnete Seite. Bei üblicher Umsetzung ist das eine Portalseite in 1. Ebene wie z.B. Universität. Oder eine Subportalseite 2. Ebene wie Leitung und Struktur.
>  
> Gedacht ist…
>  
> ….dass der User so immer weiß, in welchem Portal er sich befindet (Universität, oder Forschung, oder Studium) und, wenn er auf einer Inhaltsseite ist, auch noch versteht, in welchem Subportal unter Universität er ist (hier: Leitung und Struktur, aber auch „Vor dem Studium“ oder „Forschungsprofil“).
>  
> Es wirkt sich so aus, dass…
>  
> ….die Menütiefe/-komplexität steigt, wenn man Ebene 1 statt 2 verwendet, es werden mehr Unterseiten in der linken Navi angezeigt. Anstatt hier schön zu reduzieren für bessere Übersicht.
>  
> Besonderheiten:
>  
> Ebene 3 haben wir noch nie benutzt.
>  
> Im Intranet https://www.fau.de/intranet/fau-repraesentieren/ verstoßen wir bewusst gegen die Praxis und haben die falsche Ebene 1 eingestellt, die eigentlich zu viel anzeigt. Aber ohne diesen Kniff, hätte man auf der so schon sehr chaotischen Intranetseite (Übergangslösung!) noch weniger Überblick, wo man gerade ist. Stichwort Google-Treffer…
>  
> War das verständlich?
>  
> Man könnte die Funktion und die Optionen auch umbenennen, wenn das anderen Nutzern hilft. Man versteht das Ganze als Admin tatsächlich erst, wenn man es probiert und die Seiten kurz durchdenkt. Für den Nutzer ist die Orientierung bei korrekter Einstellung leichter/die Seite sieht gut aus. Bei falscher Einstellung ist die Orientierung schwer/das Menü sieht unschön aus.
>

**Comment by xwolfde** [comment]
Zusammenhang mit https://github.com/RRZE-Webteam/FAU-Theme/issues/265

**Comment by xwolfde** [comment]
> Die Menüebene steuert auf Inhaltsseiten, was als Link über der linken Navigation angezeigt wird. Das ist eine übergeordnete Seite. Bei üblicher Umsetzung ist das eine Portalseite in 1. Ebene wie z.B. Universität. Oder eine Subportalseite 2. Ebene wie Leitung und Struktur.

Aber das ist doch redundant und damit an der Stelle unnötig!  Denn diese Funktion erfüllt die Breadcrumb und die hinterlegte Schrift mit der Oberebene im Farbbalken!

ich würde die Optionsmöglichkeit einfach rausnehmen und schleicht in der Navi die Seitenstruktur bis zur aktuellen Seite +1 Ebene nach unten wenn vorhanden anzeigen und nach oben bis zum definierten Root.

**Comment by wrkb** [comment]
Der Sinn des ganzen in einem Satz: Wir wollten die linke Seitennavigation übersichtlich halten.

Hintergrund sind Erfahrungen und Empfehlungen aus der Web-Usability. Die scheinbar verbreitete 7-plus-minus-2-Regel bei der Anzahl von Links/Navigationsoptionen ist damit gar nicht mal gemeint. Es geht schlicht um "weniger ist mehr".

Würden wir die Option ersatzlos abschaffen, hätten wir im Bereich Universität endlos lange Menüs, und die wollten wir mit dem Relaunch ja unbedingt loswerden. Auch auf anderen, moderenen Uni-Seiten ist uns das negativ aufgefallen beim Benchmarking (z.B. Leuphana: Schöne Seite, schwer zu überblickende Navi: http://www.leuphana.de/college/studium/pruefungen.html)

Man könnte den Standardwert auf 2 setzen (typische Inhaltsseite auf der 3. Ebene), aber die manuelle Einstellung ist momentan nicht ersatzlos streichbar.

**Comment by wrkb** [comment]
Nachtrag, um Missverständnissen vorzubeugen: Die **Funktion** ist nicht redundant, da es sich um eine Einstellung mit Auswirkungen auf das Theme pro Seite handelt.

Die **Darstellung** ist natürlich redundant - by Design. Das ist so gewollt und war ein Teil der Redundanz, die wir ja bewusst mit dem Relaunch eingeführt haben. Auch, um nicht nur auf minikleine Hinweise wie Breadcrumbs setzen zu müssen. Die im Falle z.B. dieser Unterseite nicht mehr wirklich helfen: https://www.fau.de/studium/vor-dem-studium/bewerbung/zulassungsbeschraenkte-faecher-nc-bewerbung-wintersemester/unterlagen-fuer-die-bewerbung/ Landet man via Suchmaschine auf dieser Seite, so erschließt sich einem nicht unbedingt sofort, worum es geht (und das ist nicht immer mit Seitentiteln lösbar). Der Hinweis und Link in der linken Navi "Vor dem Studium" macht klar, dass es hier um Informationen für Studieninteressierte geht. Es gibt noch bessere Beispiele, aber hier haben wir eine sehr tiefe Menüebene. Würden wir das Menü nicht einschränken, stünde links oben nur "Studium" und das Menü wäre **noch** länger.

**Comment by wrkb** [comment]
Ändert an die Einstellung so, dass die linke Navi auf der 1. Ebene beginnt, sieht es so aus wie im Screen. Im Bereich Universität wird es extrem - da ist noch viel mehr los.

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/15252214/1dc9726e-192d-11e6-81d2-764594b31a19.JPG)

**Comment by xwolfde** [comment]
Ich verstehe den Sinn. Aber im Prinzip führt ihr damit eine für einen user der Webseite nicht vorhersehbare Willkürlichkeit ein:
Je nachdem was der Bearbeiter der Seite einstellt, ist das Menü entweder vollständig oder nicht.
Wenn es wenige Bearbeiter gibt, werden diese sich auf ein Schema einigen. Bei vielen Bearbeitern jedoch wird der ein langes Menü bevorzugen, der nächste ein kurzes, bei dem Oberpunkte weggefiltert werden.

Wenn man über den tellerrand seines eigenen Webauftritts schaut ist es schlimmer: Auf der einen Website wird es vielelicht nach dem Schema "alles ausgeklappt von Ebene 1" gehalten, bei der nächsten wird flexibel ab Ebene 2 geschaltet.

Das ist nicht einheitlich. Und das geht gar nicht.

**Comment by wrkb** [comment]
Was kann man tun?

Schulen?
Ein Plugin für fau.de und fau.eu draus machen, das für alle zur Verfügung steht, die sehr umfangreiche Navigationen haben? Die Fakultäten sind uns da doch dicht auf den Fersen...

**Comment by wrkb** [comment]
Auf der Suche nach einem krasseren Beispiel habe ich eine Seite gefunden, bei der die Einstellung falsch ist (wie via Mail als Phänomen bereits gemeldet). Hier.

Falsch:

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/15252955/6e34cfc0-1930-11e6-8548-a563e1b39887.JPG)

Richtig:

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/15252994/9748a404-1930-11e6-8f38-e3c9b2f6dddb.JPG)

Man könnte das Menü sogar noch weiter reduzieren, nur auf Veranstaltungen und oben links bleibt trotzdem das Überportal stehen. Aber soweit sind wir noch nicht gegangen.

**Comment by wrkb** [comment]
Achja: Man denke bitte auch an die responsive-Darstellung. Zumindest bislang sind da die Menüs in analog abgebildet und die Einstellung wirkt auch da.

Ich verstehe, dass die Einstellung für manche Nutzer zu komplex ist und unnötig, aber bei uns ist sie nötig und es gibt keine funktionierende Standardeinstellung. Man müsste die ganze Navigationslogik anpassen.

Ich bin für die Auslagerung in ein Plugin oder für eine Freischaltung der Funktion in den Theme Options. Ist sie deaktiviert, greift dein Vorschlag (Darstellung ab Ebene 1).

**Comment by xwolfde** [comment]
Bei den Updates ist das Menü im responsiven Layout schon berücksichtigt.

**Comment by xwolfde** [comment]
Können wir irgendwie eine "Regel" finden, die automartisch funktioniert, welche entscheidne kann, ab wann ein Menü reduziert ist und wann nicht? Dahin müssen wir kommen, darum geht es.

**Comment by wrkb** [comment]
Lass uns nächste Woche mal nachdenken. Aus dem Bauch heraus würde ich nein sagen, aber es hängt schon mit der Ebenentiefe und der Existenz eines Subportals zusammen, evtl. kann man das also konditional machen.

Ein Problem bleibt: Es gibt sinnvolle Ausnahmen - man möchte mehr anzeigen. Was dann?
(Wir tun das gerade auf fau.de/intranet, auch wenn das eine absolute Notlösung ist)

**Comment by xwolfde** [comment]
Ein Kompromiss könnte sein, die Ebenangabe durch ein einzigen Schalter zu ersetzen: Oberebenen anzeigen ja/nein.
Sprich: Wenn man bei einer Ebene 3 wäre und das Menü hat 5 Ebenen, dann werden bei "ja" die Ebene 1 bis 4 angezeigt. Wenn nein, eben nur Ebene 3 und 4 und darunter.

Grundsätzlich wird immer die eigenen Ebene und die folgende Unterebene gezeigt.

**Comment by wrkb** [comment]
Wir müssen das durchdenken. Aber eigentlich sollte ein Schalter funktionieren, denn die Einstellungen 3. Ebene ist ohne Funktion scheinbar, wir nutzen sie bislang auch nicht und schalten also nur zwischen zwei Optionen hin und her.

**Comment by xwolfde** [comment]
Wir haben lange Erfahrung und Tests mit dem Menü auf der RRZE Seite gemacht. Wir hattena uch die Form in der alle Obverelemente bis auf die Klicklinie einglendet waren.
Die jetzige Variante (alles aufgeklappt), wie auch in dein Bild oben, wo du "Falsch" drüber geschrieben ist, ist die Variante, die sich nach viel user-feedback als die einzig richtige erwiesen hat.

**Comment by xwolfde** [comment]
Hm... Idee: 
* Per Default wird das aufgeklappte Page-Menü gezeigt.
* Optional kann man jedoch ein eigendefiniertes/manuell gepflegtes Menü angeben, dass angezeigt werden soll.

Das würde alles erlauben was man will und es wäre leicht vermittelbar.

**Comment by wrkb** [comment]
Manuell gepflegte Menüs als Ersatz würde bedeuten, dass wir für hunderte Seiten Menüs bauen müssen? Oder fast alle? Unmöglich zu leisten...

Der wahrscheinlich beste Vorschlag kam von dir oben, ich weiß nur nicht, ob ich ihn richtig verstanden habe, Zitat:

> "Ein Kompromiss könnte sein, die Ebenangabe durch ein einzigen Schalter zu ersetzen: Oberebenen anzeigen ja/nein".
Ich verstehe das so:

1. bei Nutzern des Einrichtungs-Themes wird per default einfach das Menü in voller Länge angezeigt, ab Ebene X (noch zu definieren). Was dann über der linken Navi stehen soll, habe ich aber noch nicht verstanden. 
2. in den Theme Options kann - z.B. für fau.de und fau.eu - die spezielle Menüdarstellung und -verkürzungsmöglichkeit auf Inhaltsseiten aktiviert werden.
3. Wenn 2. aktiv ist, dann kann man an einer Webseite im Backend einstellen, welche Ebene als Link über der Seitennavigation angezeigt wird. Ebene 1 nach der Startseite (üblicherweise ein Portal) oder 2 (üblicherweise ein Subportal, aber eben nicht immer).
4. Die zweite Variante (zeige Ebene 2 an) sollte Standard sein.

Weil das alles so kompliziert ist, sollten wir kurz telefonieren, um Missverständnisse auszuschließen und das Substrat kann ja wieder hier rein :)

**Comment by xwolfde** [comment]
Ähm. mal ne dumme Frage: Du weißt doch, daß die Page-Nav den Tree nur von seiner Wurzel aus zeigt und die Wurzel jederzeit durch die Änderung der Hierarchieebene geändert werden kann?

Veranschaulichung:

Dein Page-Tree sieht so aus:
`Root
    -- Elternelement1
      -- Elternelement 1.1
         --Child 1.1.1 
        -- Child 1.1.2
     -- Elternelement 1.2
    -- Elenterelemnt 1.3`

Du bist dann auf der Seite "Elternelement 1.1":

Dann zeigt die Page-Nav den ganzen obigen Tree an.
Wenn du aber nun sagst, du willst ab Ebene "1" machen, dann bedeutet das doch nur, dass du den Root von Elternelement 1 löst und Elnternelement 1 zum Root machst?

Dazu braucht man doch nichts extra programmieren... Dazu muss man nur die Seitenhierarchie korrigieren.
Von daher verstehe ich den Hintergrund der Diskussion nicht. 

Wichtig bei allen ist aber eines: Die Breadcrumb die oben in Bannerleiste ist MUSS in der Navigation enthalten sein. Da geht kein Weg dran vorbei. Und die Breadcrumb basiert auf der Hierarchie.

**Comment by wrkb** [comment]
Ich glaube, wir reden aneinander vorbei oder ich verstehe etwas nicht, ich kenne die Anpassung des Menüs ja nicht auf Code-Ebene.

Die Agentur hat die Darstellung des Menüs beeinflusst, ohne Seiten zu verschieben und das funktioniert für uns wunschgemäß. Die Baumlogik wird dadurch nicht beeinflusst - und die Breadrcumb ist ergänzend da und wird auch immer bleiben.

Was wir erhalten wollen, ist die reduzierbare Darstellung der Menüebenen in der linken Navi.

**Comment by xwolfde** [comment]
Also gut. Ich werde es für euch so drin lassen.
Aber... : Nur via Extra-Option einschaltbar (bei euch ists dann an); Für alle anderen ist per default aus und dann nicht sichtbar bis man es einschaltet. Und ich werde eine Notiz dazuschreiben, dass der Einsatz dieser Funktion nicht empfohlen wird und wir (als Webteam) keinerlei Support dazu leisten. 
Wenn das Ding Sachen tut, die unerwartet oder falsch sind, kümmern wir uns nicht drum. Das gilt auch für den gemeldeten Bug(?).

**Comment by xwolfde** [comment]
Die Inline-Menüoption wird ab der nächsten Version der Themes nur noch dann aktiviert, wenn das Theme auf den Modus der FAU-Startseite gestellt wird. Dies ist nur definierten Webauftritten unter fest definierten ULs möglich.
Bei allen anderen Websites steht diese Funktion nicht mehr zur Verfügung.

Sprich: Für die zentrale FAU-Website ändert sich nichts. Für alle anderen ists weg.

**Comment by csw-** [comment]
Eine kurze Nachfrage @xwolfde Es gibt jetzt auch keine Extra-Option die Menüebenen manuell anzupassen?

**Comment by xwolfde** [comment]
Nein, derzeit nicht. Die Gefahr der Fehlbenutzung (und damit der dadurch generierte Supportaufwand zur Korrektur) ist viel zu groß als dass ich dies anbieten will.

**Comment by csw-** [comment]
Alles klar.

**Comment by csw-** [comment]
@xwolfde Nur eine kurze Frage, was machen wir mit solchen Fällen? ("Studieninhalte" und "FAQ und Downloads" sind Unterseiten von Sozoek) 

![menu-lvl6](https://cloud.githubusercontent.com/assets/6545158/18749265/58cee1c6-80d6-11e6-9408-7eb5b85c1bb7.jpg)

**Comment by xwolfde** [comment]
Hm,. ich würde sagen: Den Webmaster, der eine so tiefe Menüstruktur entwarf, nochmal zur Nachschulung über sinnvolle Taxonomien schicken :=P    Sechs Hierarchieebenen ist einfach viel zu viel. 

Die Studiengänge würde ich alle direkt unter Studium legen. Aber nicht noch unter den zwei Ebenen Studienprofil->Studienangebot.

**Comment by csw-** [comment]
Danke für die Anregung, ich werde sie dem zuständigen Webmaster mitteilen und auch nochmal den Kurs nahelegen. Sechs Ebenen, was hat der sich dabei Gedacht?... 
Am 22.09.2016 16:44 schrieb Wolfgang Wiese <notifications@github.com>:Hm,. ich würde sagen: Den Webmaster, der eine so tiefe Menüstruktur entwarf, nochmal zur Nachschulung über sinnvolle Taxonomien schicken :=P    Sechs Hierarchieebenen ist einfach viel zu viel. 

Die Studiengänge würde ich alle direkt unter Studium legen. Aber nicht noch unter den zwei Ebenen Studienprofil->Studienangebot.
