### ISSUE TITLE
Umgestaltung Banner Startseite und Balken Unterseiten

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#63]
Es gibt Wünsche danach, dass die FAU auf den Unterseiten stärker zur Geltung kommt ("Man erkennt nicht, dass man auf einer Seite der Universität ist!"). Die Logografik oben links reiche nicht aus.

Eine grundlegende Änderung des Designs ist zu diesem Zeitpunkt natürlich völlig ausgeschlossen. Trotzdem sollte ein modernes Design flexibel genug sein, um Lösungsvorschläge zu finden.

Folgende Lösungsvorschläge sind meines Erachtens (im Vergleich zu anderen, bei der das Unilogo noch präsenter ist) denkbar. (Auch wenn es auch dann sicherlich Beschwerden geben wird).
1. Default Startseite einer Einrichtung unterhalb Fakultätsebene
   Der Schriftzug der Uni wird als Grafik im Bannerbereich überblendet.

![entwurf-default-like-20160518](https://cloud.githubusercontent.com/assets/1070669/15390373/d6019324-1dbb-11e6-860d-8c20ab1e4f65.jpg)
1. Unterseite
   
   Variante a)  Sanfte Überlagerung ohne Umrandung bei Schrift,  dafür leider sehr überlagernde Schriftfarbe, die leider den Text  "(Lehre") mit der aktuellen Position (in diesem Beispiel leider ausgeblendet, bitte reindenken) in der Lesbarkeit stören könnte

![entwurf-unterseite-like-20160518](https://cloud.githubusercontent.com/assets/1070669/15471350/c41e6ff0-20f5-11e6-8d28-e10f2f3a81a0.jpg)

  Variante b)  Schrift auf Siegel mit Siegelfarbe, dafür aber mit Umrandung, die es lesbar macht,

![entwurf-unterseite-like-20160519](https://cloud.githubusercontent.com/assets/1070669/15390494/59aef1e4-1dbc-11e6-9b6c-892066f959d2.jpg)

  Diese Variante wäre auch für Fakultätsseiten und fau.de denkbar. Im Sinne des Corporate Designs wäre es ggf. sogar notwendig, dass dies auch für diese erzwungen wird.

Welche anderen Möglichkeiten wären sonst noch vorhanden?
Es muss ein Kompromiss sein zwischen den Anforderungen eines zentralen Designs aus der Sichtweise einer zentralen Welt einerseits, aber großer Flexibilität und Eigenständigkeit der Einrichtungen von denen wir möchten, dass sie es freiwillig nutzen, andererseits!

**Comment by AstridSemm** [comment]
Die Startseite finde ich sehr schick - vor allem wegen des transparenten Hintergrunds hinter der Schrift. Für die Unterseite finde ich des Kontrasts wegen die erste Variante deutlich besser, bei der zweiten wird's ein visueller Mischmasch, der deutlich schwerer zu erkennen ist.

**Comment by xwolfde** [comment]
Nicht vergessen:  Bei dem ersten Beispiel mit den Banner fehlt das überlagernde "Lehre".

**Comment by AstridSemm** [comment]
Tja; das müsste dann allerdings eher nach links (wo es eigentlich auch logischer wäre). Schwierig...

**Comment by xwolfde** [comment]
IMHO überlastet der Schriftzug das Design jetzt. Wenn wir das in der Größe machen, ist der Titel der Ebene (hier "Lehre") entweder zu viel, wirkt zu klein oder überlagert das ganze. Man muss auch bedenken, daß anstelle "Lehre" auch mal ein langer Begriff oder mehrere Worte da stehen können, die den ganzen Raum einnehmen.

**Comment by Silsa** [comment]
![ls_3](https://cloud.githubusercontent.com/assets/19662415/15666587/d08ccb8e-2711-11e6-8ba8-27fda30c6074.jpg)
![ls_1](https://cloud.githubusercontent.com/assets/19662415/15666589/d0a60428-2711-11e6-8af3-b7e95c390ceb.jpg)
![ls_2](https://cloud.githubusercontent.com/assets/19662415/15666588/d0a0efec-2711-11e6-823e-dba8e53daf7e.jpg)

**Comment by Silsa** [comment]
Hallo Ihr Lieben,
habe mal darüber gebrütet. 
Hier eine Variante (siehe Bilder oben), die ggf. funktionieren würde. Das FAU Logo oder auch das Fachbereich / Fakultätslogo kann auf freiwilliger Basis rechts über den Seiteninhalten platziert werden. Das ist inhaltlich sinnig, da es als Link zur nächsten Hierarchieebene verstanden werden kann und zudem sieht man eben die Zugehörigkeit. 
Da es freiwillig ist, müsstest Du es nur in das Template als Option integrieren, wer es dann später nutzt, bleibt offen und so entsteht bei den bisherigen Nutzern kein Problem.
Etwas oben zum anderen Logo oder gar über die mittlere Contenebene hinaus zu integrieren, würde ich aus gestalterischer Sicht in jedem Fall ablehnen.
Ansonsten hiermit frei zur Diskussion :), LG, Silke

**Comment by xwolfde** [comment]
Kurze Rückfrage: Bei den normalen Seiten würde das ja dann auch unterhaqlb der dortigen Breadcrumb-Leiste sein? Die betrifft es ja noch mehr...

**Comment by csw-** [comment]
Das FAU-Logo sollte dann auch nur die Startseite betreffen. Auf den Unterseiten wäre es ja eigentlich ziemlicher Overkill und würde auch ziemlich stark in das individuelle Konzept eingreifen (denn es müsste ja dann zwanghaft eine Sidebar geben). Oder habe ich deine Frage vllt. falsch verstanden? @xwolfde

**Comment by xwolfde** [comment]
Leider ist die Kommunikation an der Stelle sehr ... ungenau. Mal geht es um die Unterseiten, mal um die Startseiten. Als ich ganz oben angefangen hab, ging es zunächst um die Unterseiten!
Inzwischen geht es um die Startseite. Bei den Startseiten kann man das "Problem" auch bequem mit einer Bildlösung beheben.
Aber es ging Eingangs um die Unterseiten.

Und auf die Frage, wie es dann für Small Screen Devices sein soll, hat da auch keiner gedacht. Ich muss derzeit davon ausgehen, dass die betreffenden Leute nur Dinge im ihren Sinne fordern, aber keinen Gedanken an andere Einsatzszenerien zu denken. Wir müssen es dann leider irgendwie ausbaden und eine Lösung für die damit verursachten Probleme finden...Die Lösung wird dann vielleicht in einem Jahr von denselben Late Adoptern entdeckt und trifft deren persönlichen geschmack dann auch nicht. Weswegen wir dann wieder alles ändern müssen

**Comment by Silsa** [comment]
Würde es nur auf die Startseite packen. Bei den restlichen Seiten ist doch auch noch unten in der Meta. Das braucht doch nicht dreifach abgebildet sein.
Zudem eine Startseite ja auch eben den Türcharakter hat. Da muss es klar sein, nicht wenn ich schon im Haus bin.

LG, Silke

Von meinem iPhone gesendet

Am 05.06.2016 um 13:37 schrieb Wolfgang Wiese <notifications@github.com<mailto:notifications@github.com>>:


Leider ist die Kommunikation an der Stelle sehr ... ungenau. Mal geht es um die Unterseiten, mal um die Startseiten. Als ich ganz oben angefangen hab, ging es zunächst um die Unterseiten!
Inzwischen geht es um die Startseite. Bei den Startseiten kann man das "Problem" auch bequem mit einer Bildlösung beheben.
Aber es ging Eingangs um die Unterseiten.

Und auf die Frage, wie es dann für Small Screen Devices sein soll, hat da auch keiner gedacht. Ich muss derzeit davon ausgehen, dass die betreffenden Leute nur Dinge im ihren Sinne fordern, aber keinen Gedanken an andere Einsatzszenerien zu denken. Wir müssen es dann leider irgendwie ausbaden und eine Lösung für die damit verursachten Probleme finden...Die Lösung wird dann vielleicht in einem Jahr von denselben Late Adoptern entdeckt und trifft deren persönlichen geschmack dann auch nicht. Weswegen wir dann wieder alles ändern müssen

**Comment by xwolfde** [comment]
Bin derselben Meinung und hab das auch mehrfach gesagt... Leider wurde das nicht akzeptiert.

**Comment by xwolfde** [comment]
Wird zurück gestellt und extern vergeben.

**Comment by xwolfde** [comment]
Die Argumentation, dass man erkennen muss, das man auf der Uni ist und dies nicht anhand des Markenbegriffes (Logo und "FAU") im Kopf nicht deutlich genug gegeben sei, wird weiterhin verfolgt.
Daher wurde auf Wunsch des CIOs der folgender Entwurf entwickelt:

![screenshot-entwurf-fauorg-untermeta-20170214](https://cloud.githubusercontent.com/assets/1070669/22933210/1e7db148-f2cb-11e6-9500-7af8c22be06e.png)

Unterhalb der Meta-Navigation wird auf 
* "FAU-Ebene" nichts gezeigt
* "Fakultätsebene" der LInk  "Friedrich-Alexander-Universität Erlangen-Nürnberg (FAU)" als ausgeschriebener Text angezeigt.
* "Departmentebene die Links "Friedrich-Alexander-Universität Erlangen-Nürnberg (FAU)" | "Ausgeschriebner Fakultätsname"
* Lehrstuhlebene die Links  "Friedrich-Alexander-Universität Erlangen-Nürnberg (FAU)" | "Ausgeschriebener Fakultätsname" | "Fachbereichsname/Departmentsname" gemäß FAU.ORG-Eintrag.
angezeigt.

Alles darunter rutscht entsprechend runter.
Die Umsetzung bei Small Screen Devices ist noch zu diskutieren; Wunsch ist hier, dass auch hier die Unibezeichnung + Orgapfad vollständig gezeigt und nicht in dem Hamburgermenu verdeckt wird.

Dieses nun als Protokoll-Info ohne eigene Wertung.

**Comment by AstridSemm** [comment]
Ok, dann werte ich mal:
Das Ding ist mE einfach unnötig. Wenn man dringend darauf hinweisen möchte, dass man sich an der FAU befindet, kann man vorschreiben, dass links oben nicht das Lehrstuhllogo, sondern das Fakultätslogo sein soll. Das Lehrstuhllogo läßt sich grundsätzlich auch anderenorts (zB im Banner) unterbringen.
Das sehr angenehme Design durch diesen Stilbruch anzuknacksen halte ich für den absolut falschen Weg.
Im Übrigen war ich der Ansicht, dass es sich bei den Themes um ein von allen Fakultäten und der Unileitung abgestimmtes Design handelt. Deswegen waren doch auch Sonderwünsche wie die aus der TechFak nicht möglich. Hat sich daran etwas geändert?

**Comment by csw-** [comment]
Auch ein paar Anmerkungen meinerseits:

Diesem Entwurf zufolge wird die Funktion der Metanavigation für alle Organisationen unterhalb der Universitätsebene stark eingeschränkt bis blockiert. Insbesondere Organisationen mit langen Organisationsbezeichnungen werden hier stark benachteiligt:

Neben der Navigationsmöglichkeit zur nächsthöheren Ebene enthält die Metanavigationsleiste weitere Verlinkungen und Funktionen die für die jeweiligen Webauftritte von hoher Wichtigkeit sind. (Aus diesem Grunde werden diese ja überhaupt in der Metanavigation aufgenommen, die von jeder einzelnen Seite eines Webauftritts aus erreichbar und gleichbleibend ist.) 
Neben der Suchfunktion finden sich dort meist auch Verlinkungen zu wichtigen Ansprechpartnern der jeweiligen Organisation (Kontakt, Anfahrt) sowie zu UnivIS und/oder MeinCampus als wichtige Universitätsweite Portale.

Die Anzahl dieser Elemente in der Metanavigation sind durch die vorgegebene Breite der Metanavigationsleiste im Webdesign allerdings beschränkt. Dies bedeutet: Je mehr Platz die Hierarchie-Navigation einnimmt, desto weniger Platz bleibt für Positionierung von weiteren Elementen.

Als Beispiel habe ich einmal den Link-Text, den die Hierarchie-Navigation bei einem unserer Lehrstühle einnehmen würde, in das bestehende Layout eingesetzt.

![fau-meta-erweitert-lehrstuhlebene](https://cloud.githubusercontent.com/assets/6545158/23019204/6807e4f6-f441-11e6-862c-41a4142945c1.png)

Wie man sehen kann, sprengt die Hierarchie-Navigation den Rahmen. Wenn sie denn überhaupt vollständig abgebildet werden könnte, bliebe anschließend kein Platz mehr für weitere Link-Elemente.

Diese Methode, die Zugehörigkeit zur Universität zu verdeutlichen, könnte nur mit einem größeren Eingriff in das bestehende Webdesign der Universität zu bewerkstelligen sein. 

**Zusatz SmallScreen**
Diese Idee für die Umsetzung bei Small Screen ist sogar noch kritischer, da hier sogar die Inhalte der einzelnen Webseiten, wie z.B. Nachrichten-Artikel, Beiträge, etc. noch weiter nach unten aus dem Viewport verdrängt werden:
Denn wenn die Hierarchie-Navigation, wie oben beschrieben **nicht** in das Hamburger-Menü gesetzt werden darf gibt es nur eine andere Möglichkeit: Eine Mehrzeiligkeit der Metanavigation (diejenige, die derzeit unterhalb des Logos/Headers zu finden ist und die Suchfunktion sowie den Sprachwechsler enthält). 
Diese wird dadurch in den Vordergrund gerückt und die eigentlichen wichtigen **primären** Inhalte werden aus dem Viewport geschoben.

--- 

Ließe sich die Zugehörigkeit zur FAU bewerkstelligen **ohne** einen so drastischen Eingriff in das Webdesign?
Ja. Man **verpflichtet** die Organisationen, die offiziellen Logos der Universität, der Fakultäten und Lehrstühle zu verwenden.

**Comment by csw-** [comment]
Verstehe ich das jetzt richtig, dass die Hierarchi-Navi unterhalb der bestenden Meta-Nav erscheinen soll, oder soll diese dadurch ersetzt werden?

**Comment by xwolfde** [comment]
Unterhalb. Genau da wo sie im Beispiel gezeigt wird.
Aus der Meta-Nav würde dann die Fakultätsbezeichnung entfernt werden, so daß dort Platz gewonnen wird

**Comment by xwolfde** [comment]
Nach Beschluss im Design-Ausschuss:
Für Desktop werden noch weitere Wireframes erstellt.
Für Mobile Devices wird eine Variante des folgenden Entwurfes verwendet:
![2 front](https://user-images.githubusercontent.com/1070669/29870887-ed11d6ac-8d89-11e7-9e78-79a1196a33a3.png)

Hier wird jedoch die noch zu bestimmende "Orga-Breadcrumb" in das Flyout des Hamburger-Menüs verschoben.

**Comment by xwolfde** [comment]
Folgender Entwurf für die mobile Ansicht zeigt nun die Variante ohne Orga-Breadcrumb.
![6](https://user-images.githubusercontent.com/1070669/29871802-716f13bc-8d8d-11e7-89a2-cefd77362e1d.png)

Zu beachten ist, daß ich auch die Lupe und das Sprachschaltersymbol tauschte. Dies deswegen, da der Sprachschalter nicht auf jeder Website existiert. Die Lupe jedoch schon.
Wenn der Sprachschalter also nicht da wäre, würde die Symmetrie nicht mehr vorhanden sein, wenn die Lupe auch rechts neben den Hamburger bliebe.

Ebenfalls zu bemerken ist,
* die Grundfarbe würde anstelle Blau bei Fakultätszugehörigen EInrichtungen der dortigen Grundfarbe entsprechen.
* die Darstellung der Slider auf der mobilen Startseite ist an dieser Stelle nur angedeutet. Diese wird noch optisch etwas verbessert.

**Comment by xwolfde** [comment]
Ref #199

**Comment by xwolfde** [comment]
In der nächsten Version ist eine Umsetzung des mobilen Entwurfs vorhanden

**Comment by xwolfde** [comment]
Problem aus Usability-Tests: Wenn das FAU-Logo so groß ist, kommt es zu häufiger "verklickern" mit dem Daumen/Zeigefinger. Es muss daher kleiner sein.
Hier müssen wir aber ggf. evaluieren und dann ggf. anpassen.

**Comment by wrkb** [comment]
Hab ich neulich schon nicht verstanden: Womit kann man das FAU-Logo denn verwechseln auf dieser breiten Leiste? Kleiner als im Screenshot oben sieht nicht so schön aus, wäre prima, wenn wir da möglichst nah am Entwurf bleiben können.

**Comment by AstridSemm** [comment]
Nur, weil ich mal wieder am issues Lesen bin und hier darüber gestolpert bin: Diese Wiederholung des Portaltitels auf den jeweiligen Unterseiten ist recht vielen Kunden im Weg (großer gelber Kasten im Screenshot). Zumal der Weg zum Portal ja in der Breadcrumb ist (kleiner gelber Kasten) oder, wenn es Inhaltsseiten mit Navi sind, was fast immer der Fall ist, ganz oben in der Unterseitennavigation. Von daher meine Frage als Profi-Ketzer: Das Ding kann doch eigentlich weg, oder?
![kannweg](https://user-images.githubusercontent.com/11296947/32059774-6d8abf0a-ba6d-11e7-9c1d-48892da4b1ad.png)

**Comment by wrkb** [comment]
Wenn man der Meinung ist, dass eine winzige Breadcrumb als Orientierungshilfe okay ist... und Nutzer, die über Suchmaschinentreffer kommen, sich auch ohne perfekt auf beliebigen Unterseiten zurecht finden... Ich halte es natürlich für einen groben Fehler.

Wissen tut man das alles freilich erst, wenn man genaue Usertests macht - wir hatten das Element bewusst eingeführt und in unserem bescheidenen, aber durchdachten Test hat es funktioniert und geholfen, wenn ich mich recht entsinne. Müsste die Unterlagen rauskramen.

Man könnte natürlich auch über die optische Gestaltung nachdenken, um Kollisionen zu vermeiden, ohne gleich alles zu entfernen... ;)

**Comment by xwolfde** [comment]
Ich bin da leidenschaftslos. 
Bei solchen Websites, wo die Redakteure und Webleute eine saubere und gute Taxonomie haben, z.B. bei den Blogs der fau.de, wirkt es gut:
![2017-10-26-16-54-www fau de](https://user-images.githubusercontent.com/1070669/32060377-d985e468-ba6e-11e7-8c7e-c1a36618538c.png)

Leider gibt es aber auch andere Sites, wo der Kategorietitel oder die Oberseite nicht so gut durchdacht sind und dadurch in manchen Fällen auch mehrspaltig wird. In den Fällen sieht das bescheiden aus... 
Kompromissvorschlag: Man könnte das als Element ja auch auf Beitragsseiten (Artikel, Meldungen) beschränken.

**Comment by wrkb** [comment]
Für Beiträge in Blogs ist es gar nicht gedacht, es war nur einfacher, es drin zu lassen, programmiertechnisch. Es ist dort auch nicht konsequent eingesetzt - wenn da nicht die Kategorie auftaucht, ist es nicht spezifisch genug. Jenen Leute, die die Beiträge nicht als Blog erkennen ("Sie haben da die Webseite"), hilft offenbar auch das "FAU aktuell" nicht weiter. Es störte aber nicht bislang (hier), daher war es nie Thema.

Zu den Seiten:
Der Gedanke für dieses Element war simpel: Bei den zahllosen Unterseiten verliert man schnell den Überblick, in welchem Bereich man sich befindet - insbesonderen auf fau.de zwischen den Bereichen Universität, Studium und International ist das ein Problem. Auch versursacht durch viele formelle Begriffe, die relevante Suchtreffer in allen Bereiche erzeugen. Wer sich auf einer Seite orienteren muss, dem fällt das ins Auge, so die Strategie, wo die Breadcrumb viel schwerer zu erfassen ist - besteht ja auch nicht nur aus einem Begriff.

Ansatz 1: Wenn die Vergabe von Seitentiteln irgendwo so undurchdacht erfolgt in Bezug auf die Länge, dann darf nicht anderswo einfach das Design kaputt gemacht werden. Es ist ein Schulungs- oder ein Durchsetzungsproblem.

Ansatz 2: Wenn diese Funktion nicht zur Realität der gesamten FAU passt (entwickelt wurde das einst alles für den Relaunch von fau.de/fau.eu), dann sollte die Darstellung überdacht werden (ist scheinbar nie passiert). Kleiner, anders platzieren, den übergeordneten Portal-Eintrag in der Breadcrumb sehr viel größer und dicker hervorheben (nur das macht die Funktion ja).

Alles denkbar. Aber gleich entfernen?

**Comment by wrkb** [comment]
zu Ansatz 2: Kann auch je nach Organisationseinheit anders gestaltet sein, es muss sich nur ins Gesamtdesign einfügen.

**Comment by AstridSemm** [comment]
Karsten, die einzigen die derart zahllose Unterseiten haben, seid ihr - und da müßt ihr entscheiden, denke ich. Insgesamt ist ja bei den meisten Seiten neben der Brotkrümelnavi noch eine Seitennavi dabei, da steht der Link zurück aufs Portal ja üblicherweise drin. Nichtsdestoweniger: Ich hänge nicht an der Idee - aber eine Überlegung wär's wert, weil die meisten meiner Schöler, die diesen Aspekt ansprechen, finden, dass das weg kann (sowieso schlecht zu erkennen, im Weg, dergleichen). Ich selbst seh's emotionslos, dachte mir aber, ich geb's mal weiter.

**Comment by wrkb** [comment]
`Insgesamt ist ja bei den meisten Seiten neben der Brotkrümelnavi noch eine Seitennavi dabei, da steht der Link zurück aufs Portal ja üblicherweise drin.`

Der Text im blauen Balken ist immer der Link aufs Portal, auch wenn man sich bereits im Subportal befindet. Das leistet die linke Navi ja eben nicht, darum wurde der Text im blauen Balken überhaupt eingeführt. Und Portal sollten eigentlich immer einen griffigen und kurzen Namen haben, sie müssen ja auch in diverse Menüs passen. Daher auch die Behauptung, das wäre durchdacht :) In die Anwendung auf Einrichtungsebene habe ich zu wenig Einblick - das kann dort ja ganz anders sein.
Die Sichtbarkeit kann man feinjustieren - es hängt auch sehr von den Monitoreinstellungen ab... wie so vieles.

Die einfachste Lösung bei einem Interessenskonflikt wäre wie immer, das optional einblendbar zu machen. fau.de verliert keine Usability, andere Nutzer müssen es nicht benutzen.

Ein willkürliches Beispiel - es gibt bessere: Wer über einen Suchmaschinentreffer auf der Seite https://www.fau.de/studium/career-service/veranstaltungen/infoveranstaltungen/ landet und kein Student ist, jenseits von URL (kein gutes Merkmal), der Breadcrumb (zu klein) ist der Text im blauen Balken der deutlichste Hinweis darauf, dass man sich im Bereich Studium befindet und nicht etwa bei den Jobangeboten oder der Stellenbörse o.ä. Es gibt bessere Beispiele...

**Comment by wrkb** [comment]
Nachtrag: Bei uns brechen längere Titel auch gut um - ich weiß nicht, ob das im Einrichtungs-Theme auch der Fall ist: https://www.fau.eu/graduate-centre/doctoral-degrees/structured-doctoral-programme/

**Comment by xwolfde** [comment]
Ich schiebe die DIskussion hinsichtlich der Anzeige des Titels der Oberseite als CI-Element mal in einen Issue, da es in diesem Thread ja eigentlich um was anderes geht. Bitte dort weiter: #389

**Comment by AstridSemm** [comment]
Ja, sorry - keine Ahnung, warum ich das hier hineingeschrieben hatte.

**Comment by xwolfde** [comment]
Auftrag wurde nach interner Absprache gesondert/extern vergeben und wird hier nicht weiter diskutiert.
