### ISSUE TITLE
Darstellungsbesonderheiten im Safari

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Einrichtungen#64]
Safari setzt das Lehrstuhllogo über das Menü, womit wegen des dann entstehenden Umbruchs Bild und Balken darunter zur Hälfte verschwinden:
![bildschirmfoto 2016-05-19 um 14 53 37](https://cloud.githubusercontent.com/assets/11296947/15394292/61745ade-1dd2-11e6-9e2d-211b413b78cb.png)
In allen anderen Browsern funktioniert's klaglos.
Außerdem liefert er für ein durchaus vorhandenes Bild einen 404er:
![bildschirmfoto 2016-05-19 um 14 53 58](https://cloud.githubusercontent.com/assets/11296947/15394310/7d6d87ec-1dd2-11e6-9f19-c0dbed6b1ed9.png)
In allen anderen Browsern funktioniert's (Firefox, Chrome, Opera). Was mag das sein?

**Comment by xwolfde** [comment]
Ah, auch auf markting.rw.fau.de  (Ist zwar nicht dieselbe Domain, aber egal).

Ursache: Safari ist ein Arschloch.

**Comment by xwolfde** [comment]
Verbreitung Safari: 12.05 % . Mist. Wir können es noch nichtmal ignorieren.

**Comment by xwolfde** [comment]
Ref #67

**Comment by xwolfde** [comment]
Sollte in der nächsten version behoben sein.
