### ISSUE TITLE
Rechtschreibfehler

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/FAU-Einrichtungen#641]
Ist nur eine Kleinigkeit, aber Siteimprove markert es auf jeder Seite als Rechtschreibfehler an... 

```
<div class="footer-meta">
<nav aria-labelledby="footer-nav-title">
<h2 class="screen-reader-text" id="footer-nav-title">Contact, Imprint and other legal informations</h2>
```

informations ohne s, im Englischen gibt's keinen Plural. Danke!

**Comment by xwolfde** [comment]
in der nächsten version gefixt
