### ISSUE TITLE
Bilder vergrößern in grid-Galerie

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/FAU-Einrichtungen#671]
Bei grid-Galerien sollten sich Bilder auf Klick vergrößern lassen, ähnlich wie bei der "normalen" Bildergalerie.

Das ist vor allem dann wichtig, wenn wir die Bilder in Großformat zum Download anbieten wie z.B. hier: https://www.fau.de/presseportal-der-fau/pressebilder-zum-download/

**Comment by xwolfde** [comment]
Das ist eine Nutzung der Galerie_Funktion für etwas (Download-Verzeichnis), wozu sie nicht gedacht ist.
Ich werde aber eine Option einbauen, die den Link über ein Attribut ermöglicht.

Aber bitte beachtet trotzdem die angebotenen Dienstleistungen der FAU: Für Einzel-Downloads etwa gibt es den Dienst der FAUbox. DIeser Dienst ist verbindlich und für den gesamten Nordbayerischen Raum (für die Hochschulen) eingerichtet wurde, genau auch für so etwas. Für viele Downloads verschiedener Files gibt es den FTP-ARCHIV-Dienst. Für Bildersammlungen hätte es einen Bildarchiv geben können (und vielleicht gibt es ja doch noch einen - allerdings nur dann, wenn niemand stattdessen sagt er bruahct es doch nicht dringend, weil er ja seine Homepage dazu nutzen könne :) ).

**Comment by xwolfde** [comment]
Im Galerie-Wizzard von WordPress werden die Optionen für den Link angegeben (Attachment, Datei und Kein). Diese werden nun berücksichtigt. Bei Wahl von Attachment wird die Bild-Attachment-Seite aufgemacht, bei Datei wird die LIghtbox aufgerufen, die die Datei vergrößert.

Ab der nächsten Version online.
