### ISSUE TITLE
Imagelink-Slider rutscht an den Seitenbeginn

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/FAU-Einrichtungen#672]
Auf der Seite vom Schlossgartenfest ist ein imagelink-Slider eingebaut. Im Backend ist der Shortcode in der Mitte der Seite. Im Frontend rutscht der Slider nach oben unter die H2.

Diesen Shortlink habe ich verwendet: [imagelink catid="5923" order="rand" size="logo-thumb"]
Hier ist die URL: https://www.fau.de/universitaet/das-ist-die-fau/veranstaltungen/schlossgartenfest/

**Comment by xwolfde** [comment]
AB 1.11.24 gefixt
