### ISSUE TITLE
alt-Text bei Bilder-Galerien

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/FAU-Einrichtungen#673]
Bei Bildern in Bilder-Galerien werden keine alt-Texte angezeigt.

Galerien, die aus der Medienbibliothek in Wordpress entstehen, sollten den alt-Text eigentlich aus den Bild-Dateien beziehen können.

Bei Galerien, die aus dem Remoter-Plugin über die FAUBox generiert werden, sieht es anders aus. In den IPTC-Dateien der Bilder gibt es kein Feld "alt-Text".
Eine Möglichkeit das zu lösen, wäre das IPTC-Feld "Special Instructions", das könnte als alt-Text für Wordpress übersetzt werden.

Seite mit Wordpress-Galerie: https://www.fau.de/universitaet/geschichte-und-erfolge/sammlungen-der-fau/ 
Seite mit Remoter-Galerie: https://www.fau.de/2019/07/news/wissenschaft/kosmischen-giganten-auf-der-spur/

**Comment by xwolfde** [comment]
Das alt-Attribut wurde bei den Galerien absichtlich leer gemacht, da Galerien rein dekorative Elemente sind und daher gefülltes alt sich als negativ für Screenreader-User auswirken würde.

Ich werde das aber nochmal nachprüfen.

**Comment by xwolfde** [comment]
Alles Gut.

Bei normalen Galerien (Slides) ist der gesamte Bereich als Dekorativ markiert. Daher kann und soll dort der alt="" leer bleiben
Bei der Grid-Darstellung hingegen, die in der nächsten Version auch wieder verlinken lässt wird der alt ausgefüllt entsprechend den vorhandenen Metadaten.
