### ISSUE TITLE
Bei Sprechzeiten bei Personen wird Listenformatierung nicht übernommen

### ISSUE THREAD

**Issue by endv02** [RRZE-Webteam/FAU-Einrichtungen#68]
siehe auch https://github.com/RRZE-Webteam/fau-person/issues/127
in anderen Themes funktioniert das

**Comment by xwolfde** [comment]
Hä?

**Comment by endv02** [comment]
Na, die Listenpunkte erscheinen nicht bei Verwendung von <ul>, sondern die Punkte werden einfach nur eingerückt mit weißem Abstand davor…

Von: Wolfgang Wiese [mailto:notifications@github.com]
Gesendet: Mittwoch, 29. Juni 2016 15:05
An: RRZE-Webteam/FAU-Einrichtungen
Cc: Kimpan, Karin (RRZE); Author
Betreff: Re: [RRZE-Webteam/FAU-Einrichtungen] Bei Sprechzeiten bei Personen wird Listenformatierung nicht übernommen (#68)


Hä?

**Comment by xwolfde** [comment]
Wen jemand keine Liste verwendet, sollten doch auch keine Listenpunkte einfach so vom Himmel fallen :P

**Comment by endv02** [comment]
Also nochmal... Es wird <ul> und <li> verwendet, aber es kommen trotzdem keine Punkte... Probier das doch einfach mal mit Fau-Einrichtungen und Blue Edgy im Vergleich aus... :-)

**Comment by xwolfde** [comment]
Wieso darf man da HTML eingeben?

**Comment by endv02** [comment]
Weil es nicht verboten ist...
Z.B. um Zeilenumbrüche einzufügen... Oder Listen...

**Comment by xwolfde** [comment]
Also hier sieht es sogar ohneBöpelchen schöner aus:
https://izn.cms.rrze.uni-erlangen.de/

**Comment by endv02** [comment]
Hm...  Ansichtssache... :-) sollten wir mal eine Mehrheitsabstimmung machen...

**Comment by xwolfde** [comment]
im nächsten update gibnt es listelemente bei unterlistelementen :)
