### ISSUE TITLE
Glossar kaputt?

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Einrichtungen#69]
Ich habe ja vor Ewigkeiten im Handbuch ein Glossar angelegt (siehe https://www.wordpress.rrze.fau.de/allgemeines/glossar/). Dummerweise scheint es da das Accordion zerlegt zu haben. Nachdem das über den shortcode [[glossary]] erzeugt wird, bitte ich um Prüfung, was da sein könnte. Danke!

**Comment by csw-** [comment]
Seit heute haben wir auch ein Problem mit dem Glossar des FBV - Die Seiten auf dem der Glossary-Shortcode eingesetzt wird, werden nicht richtig gerendert bzw. der Dom ist schlicht zerschossen. Das betrifft die Service-Seiten "Beschäftigte" und "Gäste" komischerweise aber nicht "Studierende".
[https://www.fbv.rw.fau.de/service/beschaeftigte/](https://www.fbv.rw.fau.de/service/beschaeftigte/)
Der einzige offensichtliche Unterschied ist die Verwendung von Umlauten in der Glossar-Kategorie & Shortcode; daher habe ich mal eine Kategorie umbenannt, das hat aberleider nicht geholfen..

**Comment by xwolfde** [comment]
Seit heute? WTF? Themes wurden seit Mai nicht geändert...

**Comment by AstridSemm** [comment]
Nein, das ist schon seit längerem kaputt - siehe oben. ^^

**Comment by csw-** [comment]
Mittlerweile funktioniert es wieder. Lag vllt an der Datenbank...
(Das Problem bei uns kam wirklich erst seit gestern abend/heute früh zustande, Glossar wurde nicht korrekt geladen)

**Comment by AstridSemm** [comment]
Bei mir ist es immer noch im Eimer. *GRMBL*

**Comment by xwolfde** [comment]
Bei Glossar sehe ich kein Fehler. Allerdings sind verschachtelte Accordions kaputt. ABer das ist ein anderer Fall.
