### ISSUE TITLE
Navigation Whitespace

### ISSUE THREAD

**Issue by SebastianHonert** [RRZE-Webteam/FAU-Einrichtungen#7]
Wenn das Theme mit einer Auflösung > 767px geladen und das Fenster anschließend verkleinert wird, gibt es bei Mouseover einen sehr störenden Whitespace-Bug in der Navigation (betrifft auch FAU.de).
 
![nav-bug](https://cloud.githubusercontent.com/assets/7110206/12810862/20a4e1a0-cb29-11e5-975e-6a5e4f4e377c.jpg)

Das Problem liegt in der /js/scripts.js . Die Variable isMobile wird nur einmal nach $(document).ready initialisiert. Dadurch ist isMobile statisch:

`var isMobile = windowWidth < 767;`

Lösungsvorschlag:

`var isMobile = function() {
    return windowWidth < 767;
}`

**EDIT: Moved to FAU-Theme issues**

**Comment by xwolfde** [comment]
Der bereich wird gerade vollständig für alle Themes neu gebaut. Hab das aber übernommen.
