### ISSUE TITLE
Ausgabeschriftgröße von Shortcode kontakt unterschiedlich

### ISSUE THREAD

**Issue by endv02** [RRZE-Webteam/FAU-Einrichtungen#70]
Bei format="sidebar" und format="page" wird der Content bzw. der Inhalt des Feldes Kurzauszug in größerer Schrift angezeigt.
Beispiel: 
![shortcode-ubersicht die wordpress-themes fur fakultaten lehrstuhle und einrichtungen](https://cloud.githubusercontent.com/assets/5851793/15741672/00bc108a-28bb-11e6-82f4-3443d3db61b6.png)
![shortcode-ubersicht die wordpress-themes fur fakultaten lehrstuhle und einrichtungen-1](https://cloud.githubusercontent.com/assets/5851793/15741699/249c6176-28bb-11e6-8f01-8774550f7aa7.png)

**Comment by xwolfde** [comment]
Im Hauptcontentteil  ist die Schriftgröße nun auf der Defaultgröße des Contentbereiches.
