### ISSUE TITLE
Kontaktbilder in der Suche verzerrt

### ISSUE THREAD

**Issue by cassandre** [RRZE-Webteam/FAU-Einrichtungen#704]
Bilder von Kontakten (Person-Plugin) werden in den Suchergebnissen verzerrt dargestellt. Liegt an `.search-result, .searchresult-image img { width: 100%; ... }`

![Bildschirmfoto 2019-10-10 um 10 05 26](https://user-images.githubusercontent.com/4435815/66550578-007de700-eb46-11e9-9d5c-4ec847dcc753.png)

**Comment by xwolfde** [comment]
"Das ist Design!"



Verflixt.

**Comment by xwolfde** [comment]
ab der nächsten version gefixt
