### ISSUE TITLE
Bilder in Visitenkarten werden außerhalb des Kastens platziert

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/FAU-Einrichtungen#711]
Bei Visitenkarten mit Bildern gibt es einen Darstellungsfehler: Die Bilder sind um ein paar Pixel verrutscht und ragen damit aus dem Kasten hinaus:
https://www.fau.de/presseportal-der-fau/kontakt/

**Comment by xwolfde** [comment]
Alles was erst nach der Test- und Betaphase entdeckt wird, ist ein Feature...  :/

Ok. Muss in der nächsten Version behandelt werden. Damit es nicht sichtbar ist, könntet ihr den Border verstecken, wenn ihr wollt. Der ist eh old school.

**Comment by xwolfde** [comment]
Ist in der nächsten Version behoben.
Inklusive weiterer Unschönheiten bei der Darstellung von Kontakten.
