### ISSUE TITLE
Umbrüche in Sidebars werden unterschiedlich dargestellt

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Einrichtungen#723]
Beim Template Portalindex und Portalpage werden die Sidebars unterschiedlich dargestellt. Ist das Absicht? Warum gibt es eigentlich zwei verschiedene Templates dafür?
Wenn die Klasse sidebar-inline verwendet wird, funktioniert der Umbruch innerhalb eines Links nicht (Beispiel: https://www.fau.eu/people/students/) 
Wenn die Klasse partalpage-sidebar verwendet wird, klappts (das ist beim Template Portalpage der Fall).

**Comment by xwolfde** [comment]
Das Portalpage-Template hat ein Fehler. Der ist im nächsten Update behoben.

"Warum gibt es eigentlich zwei verschiedene Templates dafür?": Das eine Template verwendet eine feste Sidebar, unter der eine HR-Linie folgt.
Bei dem anderen Template wird ein Floating verwendet und es gibt keine trennende HR-Linie.
Je nach Anwendungsfall wird entweder das eine oder das andere verlangt. Weil es zwei Anwendungsfälle sind, sind es auch zwei Templates.

**Comment by xwolfde** [comment]
Bugfix ist auf Beta. 
Bitte testen.
https://www.beta.wordpress.rrze.fau.de/templates/portalseite/
