### ISSUE TITLE
 Allgemeine Vorlage für das Impressum

### ISSUE THREAD

**Issue by xy23vaja** [RRZE-Webteam/FAU-Einrichtungen#73]
Für das Impressum bitte eine allgemeine Vorlage wie im Webbaukasten bereitstellen ☺
http://www.vorlagen.uni-erlangen.de/impressum.shtml

**Comment by csw-** [comment]
Im Wordpress-Handbuch des RRZE gibt es eine [Kurzanleitung für das Anlegen eines Impressums](https://www.wordpress.rrze.fau.de/administration/rechtliches/impressum/).

**Comment by xwolfde** [comment]
Jupp, aber ich denke auch wir sollten ein eigenes Plugin bauen, welches das ganze automatisiert.

**Comment by AstridSemm** [comment]
@csw Die gibt es übrigens wegen dieses issue. ;oD

**Comment by csw-** [comment]
Oh. *hust* Da habe ich nicht auf das Datum geachtet XD

**Comment by AstridSemm** [comment]
Nee, ich habe mich vertan. Ich dachte, du meinst das hier: https://www.wordpress.rrze.fau.de/2016/06/02/tipp-wie-kommt-das-impressum-in-den-seitenfuss/ - Sorry, habe den ganzen Tag mit Kopfweh zu tun gehabt, da kommt sowas schon  mal vor. :o)

**Comment by xwolfde** [comment]
Kosten/Nutzen momentan zu gering.
