### ISSUE TITLE
Anzeige Beitragsbild/Bildunterschrift wird nicht korrekt angezeigt

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Einrichtungen#737]
BU läuft breiter als das Bild. 
Beispiel: https://www.beta.wordpress.rrze.fau.de/2019/12/11/beta-version-1-12-1/

**Comment by migrosch** [comment]
Würde es nicht genügen, wenn man beim Selektor `.post-image .post-image-caption` "einfach" die Deklaration `width: 300px;` entfernt?

**Comment by xwolfde** [comment]
War schon ein bißchen mehr. In der nächsten Version behoben
