### ISSUE TITLE
RSS Feed Fehler

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/FAU-Einrichtungen#738]
Die RSS Feeds funktionieren nicht mehr.

Im Wordpress-Dashboard wird bei den RRZE Fehler- und Wartungsmeldungen z.B. die Fehlermeldung "RSS-Fehler: WP HTTP Error: Es wurde keine gültige URL übermittelt." ausgegeben.

Auch in unseren "Maps" funktionieren die Feeds nicht mehr: energie-klima.fau.de (ganz unten im Footer).

**Comment by xwolfde** [comment]
Ja, ist ein bekanntes Problem, welches jedoch größeren Umfang hat - es hat aber nichts mit den Themes zu tun (daher hier wontfix).
Die Ursachensuche läuft bereits seit längerem. Eine Lösung wird wahrscheinlich urlaubsbedingt erst nächstes Jahr kommen.
