### ISSUE TITLE
Unterschiedlich große H2s ind er Sidebar

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/FAU-Einrichtungen#74]
https://ezire.cms.rrze.uni-erlangen.de/
 Gleich auf der Startseite zu sehen, dass es da 4 Überschriften gibt, aber unterschiedlich groß. 
Größe soll (was uach reicht) im Format h2small (eine Css-Klasse) sein. 

Danke

**Comment by csw-** [comment]
Jepp. Wurde auch schon von mir angemerkt. Siehe #56  bzw. [RRZE-Webteam/FAU-RWFak#23](https://github.com/RRZE-Webteam/FAU-RWFak/issues/23)

**Comment by csw-** [comment]
#56

**Comment by xwolfde** [comment]
In der nächsten Version gefixt
