### ISSUE TITLE
Beschreibung Beitragsbild

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/FAU-Einrichtungen#743]
Beim Beitragsbild wird die Beschreibung rechts von der Sidebar überdeckt, siehe:

![grafik](https://user-images.githubusercontent.com/8234890/72055097-7838ea80-32ca-11ea-861d-28137533bfbb.png)

Problem tritt auch auf fau.de auf:

![grafik](https://user-images.githubusercontent.com/8234890/72055228-bcc48600-32ca-11ea-95fe-728aea4d32d0.png)

Sowohl mit Firefox als auch Chrome.

**Comment by xwolfde** [comment]
Dup #737

**Comment by xwolfde** [comment]
In der nächsten Version behoben.
In Kürze auf Beta.
