### ISSUE TITLE
Widget Menu in Post Sidebar

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#747]
Wenn man die Kategorieanzeige nutzt, werden die Kategorien wie gewünscht wieder mit Pfeil gezeigt; Eben wie alle anderen Links in der Sidebar auch. Das funktioniert:
![grafik](https://user-images.githubusercontent.com/1070669/72085715-b3a0dc80-32fd-11ea-8849-1a70ac1fd425.png)

Nun nutzen aber einige Einrichtungen stattdessen die Menu-Funktionalität und haben sich dann für die Kategorien Menüs gemacht.
Diese werden aber nun dann mit den alten Farbhintergründen versetzt.

vgl nat.fau.de:

![grafik](https://user-images.githubusercontent.com/1070669/72085569-73d9f500-32fd-11ea-816a-df8530b3fcf5.png)

Gibt es hier überhaupt  Handlungsbedarf?

**Comment by xwolfde** [comment]
HIermit zusammenhängende vergangene Issues, anhand deren damals ebenfalls disktutiert wurde
#429 
#507

**Comment by cibsell** [comment]
Generell finde ich es mit Pfeilen hübscher, übersichtlicher und besser lesbar. Allerdings habe ich manche Kategorien, die in der Auflistung bei den Beiträgen nicht auftauchen sollen, z. B. "Allgemein", wo die Bühnenbeiträge drin stehen. Auch kann ich beim Menü die Reihenfolge der Kategorietitel ändern, während sie mir bei der Kategorieanzeige alphabetisch angezeigt wird.

**Comment by xwolfde** [comment]
Das heißt, du fändest es gut, wenn wir die Pfeil-Optik auch bei den Menüs in der Sidebar nachziehen?  Nur dann gibt es halt kein Weg zurück...

**Comment by cibsell** [comment]
Ich habe mal bei meinen Departments geschaut, die nutzen bei den Beiträgen in der Sidebar Kategorien und andere Widgets. Insofern betrifft es überwiegend die Fakultätsseite. Da fände ich es gut, wenn in der Sidebar das Menü auch die Pfeiloptik hätte, aus oben genannten Gründen, v. a. weil es dann besser lesbar ist und sich optisch besser einfügt als die dunkler hinterlegten Kästen.

**Comment by xwolfde** [comment]
Ok, dann machen wir das bei nächster Gelegenheit so

**Comment by xwolfde** [comment]
In nächster Version enthalten
