### ISSUE TITLE
Sichtbare Trennlinie

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Einrichtungen#75]
In den Schulungen kommen immer wieder Irritationen auf, weil die Trennline (der grafische Papierfalz) visuell praktisch nicht wahrgenommen wird; es gibt sehr wenige Kunden, deren Monitore so eingestellt sind, dass man die Linie tatsächlich sieht.
In der Folge wünschen sich sehr viele Kunden, dass doch eine sichtbare Trennlinie zur Verfügung stehen möge. Diesen Wunsch gebe ich mit diesem issue weiter.
@wrkb: Sorry, Karsten, so hübsch diese Linie ist, wenn der Monitor entsprechend kalibriert ist, so unpraktisch ist das tatsächlich auf den meisten Geräten. :o)

**Comment by csw-** [comment]
Das Problem hatten wir ja auch noch relativ am Anfang unseres Relaunches angesprochen. Durch das Feedback der Schulungsteilnehmer wird dies nur noch deutlicher gemacht/verifiziert. Ich wäre auch dafür die Trennlinie deutlicher hervorzuheben.

**Comment by wrkb** [comment]
Wir verstehen, worum es geht, aber es gibt Fragen und Einwände:

Interne Rückmeldungen sind eine schwierige Änderungsgrundlage, wenn, dann müsste man von Rückmeldungen tatsächlicher Nutzer ausgehend schauen (vor allem externe, aber auch interne). Denn:

- Die  uni-internen Geräte repräsentieren eben _nicht_ die typischen Geräte der Nutzer außerhalb der FAU. An der FAU sind auch teilweise Thin-Clients im Einsatz, die nicht mal 16 Millionen Farben (und damit die genutzten Farbverläufe) richtig darstellen können. Die tatsächlichen Nutzer sitzen nicht alle am 24-Zoll-Desktop, sondern haben (nicht wirklich verstellbare) Mobilgeräte-Display, die den Falz ganz normal darstellen. Die allermeisten Laptops tun das auch. Wir haben hier bei uns auch mehrere Generationen der an der FAU verbreiteten Dell-Laptops, auch hier wird der Falz optimal angezeigt (also auch bei vielen internen Nutzern).
- Man kann und sollte von Beschäftigten/Webmastern/Kunden, die mit Templates umgehen, durchaus verlangen, dass sie ihren Monitor richtig einstellen (z.B. als Teil der Schulung, wenn es wirklich Probleme gibt). Die Rede ist nicht von Kalibrieren (!), sondern von simplem Anpassen des Kontrasts und ggf. ein wenig der Helligkeit.
- Auf welchen Geräten genau haben denn die Kunden/Beschäftigten die Trennlinie nicht erkannt? Beamer/Projektoren in Schulungsräumen, Thin Clients und ähnliches sind natürlich keine Geräte, die zur Beurteilung genutzt werden dürfen, wenn es sachlich und fair im Hinblick auf den eigentlichen Anwendungsfall sein soll (und das muss es)!
- Der Falz benutzt dem CD entsprechend die Rasterfarben/Grauabstufungen - und ist z.b. auch nicht viel heller als die Schrift im Footer. Wie wird letztere denn bei den kritisierenden Kunden dargestellt? Gibt es vielleicht auch Verständnisprobleme zur Funktion des bewusst dezent trennenden Falzes oder in HInsicht auf Design?

Aktuell haben wir Schwierigkeiten, das Problem so nachzuvollziehen und die Befürchtung, dass aus dem falschen Blickwinkel heraus und/oder von nicht repräsentativen Geräten aus kritisiert wird. Daher die ganzen Einwände. Eine Detail-Rückmeldung dazu wäre schön, gern auch telefonisch.

Der Vollständigkeit halber hier noch einmal: Schon besprochen hatten wir im Jour fixe den etwas zu großen Abstand nach oben (Weißraum) über dem Strich, der soll verkleinert werden.

**Comment by wrkb** [comment]
Noch ein Hinweis, um Missverständnissen vorzubeugen:

Bei der Entwicklung des Webdesins wurde weder bei der Auflösung noch bei der Farbgestaltung von einem Idealzustand/einem Idealgerät ausgegangen, sondern die Vielzahl an Darstellungsproblemen bei Endnutzern mit einbezogen. Daher die ganzen Rückfragen, bevor wir aufgrund - pardon - noch recht unspezifischer Rückmeldungen, gleich ein visuelles Kernelement umbauen.

**Comment by wrkb** [comment]
Es geht nicht um "geliebt", sondern um das CD, dass Stück für Stück demontiert wird, wenn wir so vorgehen. Daher können wir das hier gar nicht lösen, das muss anders besprochen werden und dann hier dokumentiert werden für alle. Ich rufe dich gleich nochmal dazu an. Aber als kurzes Statement zur Sache aus unserer Sicht:

Wenn ein Designelement nicht funktioniert, kann und muss es natürlich diskutiert werden. Aber die Wahrnehmung auf Geräten wie typischen Office-Beamern (kontrastoptimiert und nicht für korrekte Farbdarstellung geeignet!) und farbkastrierten Thin Clients ist zur Designbeurteilung inakzeptabe. Wenn man das Webdesign von öffentlichen Webseiten für interne Sonderzwecken optimieren soll, dann führt das das ganze Anliegen von Webdesign ad adsurdum ;)

**Comment by AstridSemm** [comment]
Lieber Karsten,
ich sprach von allen Arten von Monitoren (und daneben ein paar Beamern und Thin Clients). Dieses Element wird nicht als Trennlinie wahrgenommen und die Intention (grafische Darstellung eines Papierfalzes) geht vollständig ins Leere.
Sicher ist darauf zu achten, dass das Corporate Design erhalten bleibt - wenn man aber erkennt, dass ein Element desselben schlicht nicht wahrgenommen wird oder Irritationen verursacht, sollte man doch überdenken, ob hier nicht eine Bearbeitung grundsätzlich wünschenswert wäre.
Telefon geht heute übrigens nicht, ich bin auf dem Sprung und habe gleich für den Rest des Tages Schulung.

**Comment by wrkb** [comment]
Die Diskussion wird erst einmal verlagert, da hier nicht abschließend möglich. Es sollte dann hier wie üblich ein Update für @csw- und andere Nutzer geben.

**Comment by wrkb** [comment]
Ergänzung. Ich wollte hier keinesfalls versuchen, eine Sach-Diskussion abwürgen, ist ja ein offener Github-Thread für alle :) Aber verlagert werden muss die Diskussion, wie Änderungswünsche gehandhabt werden in Bezug auf Wertung, Gewichtung und Gültigkeit des CD.

Zur Sache wäre noch die Frage, ob es sich um Probleme mit der optischen Wahrnehmung handelt, oder um fehlendes Verständnis zur Funktion des Falzes. Das ist aus obigen Ausführungen mir noch nicht klar.

**Comment by Silsa** [comment]
Kurze Anmerkung: was wir online haben ist kein CD. Wenn ein Element aus Usersicht nicht funktioniert ist nicht der User schuld sondern wir. Handhabt man mW überall in der Onlineentwicklung so. 
Daher ob Sachdiskussion oder nicht, wenn unsere User mit was Probleme haben müssen wir es fixen.

Und wir haben diesen Balken bei unseren Seiten überall ausgeblendet.

**Comment by wrkb** [comment]
Die Regel "Der Nutzer hat immer recht" ist bekannt und akzeptiert :) Was nicht funktioniert, muss geändert werden.

Wir in der Webredaktion sind allerdings noch an dem Punkt, dass wir erst einmal genauer herausfinden müssen, ob es wirklich nicht funktioniert und welche Nutzer Probleme haben. Webseitenbesucher, die das Element nicht sehen oder die Autoren, die die Funktion nicht verstehen oder nicht mögen?. Geht es um optische Erkennbarkeit oder um Akzeptanz der Funktion?

Der Falz sollte übrigens nie 1:1 ein hr ablösen, ein klassisches hr ist in den Templates nicht mehr vorhanden (weil hässlich). Es wäre also auch interessant, ob vielleicht einfach etwas fehlt.

Nochmal der Hinweis, dass das Problem mit dem zu großen Weißraum über dem Falz bekannt ist, das soll sich ändern.

Astrid und ich waren einig, dass wir das zu gegebener Zeit mal besprechen müssen, es gibt sehr verschiedene Erfahrungen mit dem Balken.

**Comment by Silsa** [comment]
Ja, viel Erfahrung davon liegt auch bei uns ... Wir stellen dauernd Seiten neu um, haben es also eben auch dauernd wieder mit Anfängern zu tun. Und diese haben das Falzproblem häufig ...

Und letztendlich ist es nun mal so, dass wenn ein Element nicht akzeptiert wird, man eine Nutzung eben überdenken muss. Aber das wird ja dann ...

**Comment by wrkb** [comment]
Aber welches Problem haben Sie denn nun genau? Wird die Funktion nicht verstanden? Oder wird das Element abgelehnt (optisch oder funktional?). Geht es um Geschmacksfragen beim CD (oder von mir aus der Vorstufe, die hoffentlich mal in eines mündet) oder geht es um Behinderungen beim Arbeiten? Wer von einem statischen Design in das neue wechselt, muss ja auch umlernen und das neue Design anwenden lernen. Und bitte nicht vergessen: Letztendlich ist das Design für Webseitenbesucher entwickelt worden und _die_ müssen es akzeptieren, erkennen, verstehen...

Astrid sprach teils auch von Erkennbarkeitsproblemen, aber irgendwie auch vermischt mit Verständnisschwierigkeiten für das Element

Ich weiß nicht, wie ihr schult. Unsere Autoren erhalten bei der Vorstellung des CD die Information, dass der Falz ein starker optischer Trenner ist, der mit Bedacht einzusetzen ist, weil er viel Abstand schafft (der noch etwas kleiner wird, aber es bleibt genug). Auf Inhaltsseiten wird er auch nur selten genutzt und das by design.

Zur Erläuterung:

Design: Der Falz trägt die Startseite, die Portalseiten (das ist im Einrichtungs-Theme deaktivierbar) und landing pages und. spezielle Inhaltsseiten (Bsp.: https://www.fau.de/universitaet/leitung-und-struktur/leitung/) Er ist nicht als klassisches hr gedacht (der Shortcode heißt aus Entwicklungsgründen so). Das klassische hr wurde auf statischen Seiten zusammen mit Tabellen zu oft zur Gestaltung genutzt (oft noch nicht mal zur Strukturierung) und wirkt daher altbacken bis antiquiert.

Wir haben daher bislang auch keinen echten Ersatz für eine horizontale Linie. Abhängig davon, worin genau das Problem denn nun besteht (?), könnte man als über etwas Zusätzliches reden - also einen echten Trenner im Content.

**Comment by xwolfde** [comment]
Ok. Wenn es so ist, wie Karsten schreibt, wird die hr auf der fau.de nur als grafisches Element verwendet, nicht als inhaltliche Trennung. Zudem erfolgt der Einsatz nur auf Portalseiten, nicht auf Inhaltsseiten.

Der Einsatzzweck bei anderen Einrichtungen liegt offenbar eher in der Form der inhaltlichen Trennung von Textbereichen. Dafür ist ein hr auch gedacht.
Egal, was aus guten Gründen speziell für den Einsatz auf  www.fau.de gedacht war, aus optischen Gründen mag es nachvollziehbar sein, semantisch war es falsch:  Einrichtungen, die diese Trennung für eine inhaltliche Trennung nutzen wollen, also dafür wozu eigentlich semnatisch auch verwendet werden sollte, haben nun Probleme.
Der Fokus des Projekts geht jedoch über eine einzelne Website www.fau.de weit heraus und betrifft mehrere Hundert weitere Websites der FAU. Die berechtigten Anforderungen aus den Einrichtungen der FAU sind ebenfalls zu berücksichtigen. Dies kann im Gegenfluß durchaus die Konsequenz haben, daß die Website www.fau.de wiederum im Sinne einer besseren Corporate Identity ausgehend den dezentralen Anforderungen nachgebessert werden muss und Dinge, die für diese zentrale Seite mal gedacht und gewünscht waren wieder hinterfragt und auch geändert werden müssen.

Dies ist ein ganz normaler Vorgang im Sinne von agilen Arbeitsmethoden und des Continuous Improvement.

Folgende Lösung würde ich vorschlagen:
Das hr wird neu gestaltet unter Bezug dessen, daß das hr auch als tatsächliche semantische Trennung von Texten verwendet wird. 
Bei den Portalseiten hingegen, die ohnehin nicht dafür gedacht sind, daß diese lange und umfangreiche Textbestandteile haben, ist eine semantische Trennung unnötig. Daher kann man dort entweder für das jetzige hr eine spezielle Klasse ergänzen oder aber man führt dort ein neues Element ein, welches man via Shortcode einfügen kann.

Wie die gestalterische Umsetzung von hr in normalen Inhaltsseiten aussehen sollte, muss gleichwohl diskutiert werden. Wer in Zukunft designerische Entscheidungen treffen kann, ist gerade Gegenstand einer anderen Diskussion. Solange diese nicht abgeschlossen ist (und das verlässlich), möchte ich -selbst wenn ich es jetzt einfach so als Projektleiter durchziehen könnte- nichts mehr am Design ändern.

**Comment by wrkb** [comment]
Verstehe ich das so richtig?

- Der Falz erhält eine andere Form der Einbindung (nicht mehr das missverständliche hr) via Shortcode oder css, bleibt aber erhalten. Darstellungsprobleme können in einer eigenen Diskussion erörtert werden.
- Es soll für ein neues Trennelement entwickelt werden, das wieder dem ursprünglichen Sinn des hr entspricht

Das entspräche dem Vorschlag und der Sicht hier bei uns. Zwar vermisst hier bislang keiner das hr, da eine solche semantische Trennung unserer Meinung nach besser mit Überschriften oder mit neuen Webseiten gelöst wird. Aber das ist anderswo wohl anders und vielleicht hat der neue Trenner ja auch für uns einen Nutzen.

Für den Rest gibt es die übergeordnete Diskussion, richtig.

Nur den letzten Satz verstehe ich nicht (und frage nur ungern öffentlich nach, aber es steht nunmal da): Die Projektleitung fau.de/eu lag/liegt doch gar nicht bei dir?

**Comment by xwolfde** [comment]
1. Ja.
2. Ist ja kein Geheimnis und ich bin Transparenz-Fan. Eine Projekt "fau.de" gibt es mWn nicht. Du meinst wahrscheinlich die **inhaltiche** Betreuung der Webseite www.fau.de. Das ist Aufgabe der Web-Redaktion (und damit deine Feld), so wie die Inhalte von Webauftritten auch Sache der lokalen Webmaster ist.  Bzgl. Rollout ist der Auftrag (vgl. Ergebnisprotokoll des Treffens mit der Kanzlerin vom 14.10.14, welches auch Blandina damals erhielt und hoffentlich an dich weiter leitete) eindeutig: 
>  "Das RRZE betreut und koordiniert den Rollout der neuen Webdesigns innerhalb der FAU."

Auf Wunsch kann ich das Protokoll als ganzes gern gesondert schicken.

**Comment by xwolfde** [comment]
Ab der nächsten Verison wird die hohe Version von hr (60 Px höhe + 60px Margin-bottom) nur noch auf der Startseite aktiv, auf der Startseite Template Fakultät und dort wo via SHortcode [hr siize="big"]  diese Höhe angegeben ist.
Überall sonst wird es nur noch halb so hoch sein.

Demo:
http://test8.tindu.rrze.uni-erlangen.de/tests/shortcodes/hr-die-schoene-trennlinien/
