### ISSUE TITLE
Logo und Header-Bild im WordPress-Sinn verwenden

### ISSUE THREAD

**Issue by cassandre** [RRZE-Webteam/FAU-Einrichtungen#752]
Bislang wird das native WordPress-Setting "header-image" für das Logo missbraucht. Das Headerbild wird mit einem eigenen Setting eingebaut. 

Sinnvoller wäre es, jeweils die nativen Funkionen custom-logo und header-image so zu verwenden, wie sie gedacht sind. Das ist auch für die User weniger verwirrend. 

Wird allerdings ein Problem der Abwärtskompatibilität schaffen.

**Comment by xwolfde** [comment]
Also gerade an den Stellen des Logos und der Bannergrafik haben wir bislang so gut wie keine Kundenprobleme gehabt...

Ich würde das an der Stelle erstmal so lassen.

**Comment by xwolfde** [comment]
custom_header in custom_logo überführen
https://developer.wordpress.org/themes/functionality/custom-logo/

custom_header dann für Banner verwenden, d.h. vorhandene Variable nutzen

**Comment by xwolfde** [comment]
Umgesetzt in V2
