### ISSUE TITLE
Footer Logo unscharf

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/FAU-Einrichtungen#753]
Auf Bildschirmen mit hoher Auflösung ist das Logo im Footer unscharf und verschwommen. Siehe Foto anbei:
<img width="372" alt="Bildschirmfoto 2020-04-06 um 12 36 21" src="https://user-images.githubusercontent.com/53909165/78550417-56390080-7804-11ea-849e-318a16c1a29b.png">

Ich hab im Customizer nix gefunden, wie ich das Logo anpassen könnte. Können wir das tatsächlich nicht oder hab ich es einfach nicht entdeckt?

**Comment by xwolfde** [comment]
In der nächsten version behoben durch Umstieg auf SVG
