### ISSUE TITLE
Menü nicht scrollbar auf Smartphones

### ISSUE THREAD

**Issue by thenickless** [RRZE-Webteam/FAU-Einrichtungen#755]
Beispiel: 

https://www.wordpress.rrze.fau.de/plugins/fau-und-rrze-plugins/rrze-faq/beispiele/

Ab dem 3. Untermenüpunkt von "Beispiele" kann das Menü nicht weiter nach unten gescrollt / gewischt werden -> alle danach folgende Menüpunkte sind dadurch nicht erreichbar.

**Comment by xwolfde** [comment]
Weiterhin vacant.
Betrifft nur Menus in der großen Ansichtsoption.

**Comment by xwolfde** [comment]
in der beta gefixt
