### ISSUE TITLE
Breite der Rollbalken

### ISSUE THREAD

**Issue by lms-BeFe** [RRZE-Webteam/FAU-Einrichtungen#756]
Im Standard Template mit rechts angeordneter Sidebar verändert sich die Bereite der Rollbalken
![Rollbalken](https://user-images.githubusercontent.com/64403571/82210127-bd22fc80-990e-11ea-99fe-4e39490d8543.png)
![Rollbalken_01](https://user-images.githubusercontent.com/64403571/82210141-c1e7b080-990e-11ea-9e43-febd37f50915.png)
Schöner wäre es wenn diese eine Enheitliche Breite beibehalten würden.

Edit: Links vergessen -> https://www.lms.tf.fau.de/lehrstuhl/personen/#collapse_0
Beispiel auch hier zu sehen -> https://www.rrze.fau.de/internet-e-mail/e-mail/fau/

**Comment by xwolfde** [comment]
Äh, es war vorher lange Zeit mit einer einheitlichen Breite ;) 
Aber wir haben aufgrund vieler Beschwerden, die sich darüber beklagten, dass der Platz unterhalb der Sidebar nicht genutzt wurde, die Anpassung an den verfügbaren Platz gemacht.

**Comment by lms-BeFe** [comment]
Okay, dann akzeptiere ich das so ;-)

**Comment by xwolfde** [comment]
Eein Hauch einer Hoffnung auf eine Chance einer Möglichkeit: Ich plane die EInführung einer Option zur Verbreitung der Views auf zeitgemäße Desktop-Displays. Dann erübrigt sich das ganze von selbst, weil damit das Problem der geringen Inhaltsbreite behoben wird :)

**Comment by lms-BeFe** [comment]
Ja das klingt doch gut, dann warte ich gespannt ;-)
