### ISSUE TITLE
Vorschlag: Abstand zum Menü vergrößern (mobil-Version)

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/FAU-Einrichtungen#758]
In der mobilen Ansicht von Seiten mit Portalmenü, steht die H2 sehr nah am Portal-Menü. Den Abstand könnte man etwas vergrößern, dann sieht es nicht so gedrängt aus.

**Comment by xwolfde** [comment]
abstände sollten ok sein
![grafik](https://user-images.githubusercontent.com/1070669/117646157-fa654780-b17a-11eb-9488-72c8a4c659c7.png)
