### ISSUE TITLE
Top-Event "heute" wird nicht angezeigt

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/FAU-Einrichtungen#76]
Ein Top-Event wird am Tag des Events (Datum) nicht angezeigt auf der Startseite. Alles anderen Daten funktionieren. 

Bitte korrigieren.

**Comment by xwolfde** [comment]
ah, doch. 
er schaut nur auf die sekunde genau und nicht nur nach dem Tag.

Wenn der Termnin um 15:00:00 startet und aktuelle Uhrzeit ist 15:00:01 wird es nicht angezeigt, weil Termin abgekaufen :)
Hab dem ganzen einen Offset von 12 Stunden gegeben.

In der nächsten version
