### ISSUE TITLE
Beim internen Link setzen wird der Link-Title gedoppelt

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/FAU-Einrichtungen#761]
In einem Text markiere ich einen Abschnitt, zum Beispiel die Worte "auf unseren Corona-Seiten", um einen internen Link zu setzen. Ich klicke auf das Zahnrad, suche die Seite, die ich verlinken will und setze den Link. Danach wird der markierte Text aber gedoppelt und erscheint zweimal. Einmal mit Link und einmal ohne, etwa so:

auf unseren Corona-Seiten[auf unseren Corona-Seiten](https://www.frau.de/corona)

**Comment by xwolfde** [comment]
Was erwartest du dir von uns nun? Das ist eine Funktionalität des TinyMCE Editors; An der können/werden wir nichts ändern.

**Comment by AndiWebred** [comment]
Naja, ich würde mir wünschen, dass das Setzen von internen Links genauso gut funktioniert, wie das Setzen von externen Links. Bei den externen Links wird nämlich der markierte Abschnitt nicht gedoppelt. Da wird einfach nur das verlinkt, was ich markiert habe.
Wofür soll denn diese Funktionalität gut sein? Vielleicht versteh ich das ja nur falsch.
