### ISSUE TITLE
Bildunterschrift im Popup Menü?

### ISSUE THREAD

**Issue by andreasrexlms** [RRZE-Webteam/FAU-Einrichtungen#762]
Wir haben ein Bild im Popup Menü bei welchen wir eine Bildunterschrift anzeigen müssen, um die Bestimmungen vom Autor zu erfüllen. Ich habe im Customizer die Copyright Anzeige aktiviert, diese greift aber nur im Slider. Ich habe ein Beispielbild mit angehängt. Unter dem kleinen Bild im Popup Menü rechts oben müsste stehen "colourbox.de / #232319". Vielen Dank und viele Grüße.
![copyright-hinweis](https://user-images.githubusercontent.com/44059562/87416245-b7742b00-c5ce-11ea-8ae5-8fa9256b9237.jpg)

**Comment by xwolfde** [comment]
Das ist ein großer Irrtum zu glauben, dass ihr damit die Bedingungen erfüllt.
Denn selbst wenn bei der Darstellung dann der Text dabei geschrieben wird, wird man trotzdem das Bild (rechtsklick, Bildadresse aufrufen) direkt aufrufen können ohne dass dann der Text dabei steht.

 Genau dies wurde und wird bereits ausgenutzt um Abmahngebühren einzutreiben. Daher Finger weg von Bildern mit solchen Lizenzbedingungen!!!

Was den konkreten Fall angeht:  Die EInstellung war falsch; Die betrifft nur Bildern in Texten.
Hier geht es um ein Menü und das stellt man in: 
Erweitert - Hauptmenu -  Zeige Credits der Menübildern
