### ISSUE TITLE
Beitragsseite mit externem Link/ verschiedene Link-Ziele

### ISSUE THREAD

**Issue by xy23vaja** [RRZE-Webteam/FAU-Einrichtungen#77]
![beitrag-externer-link](https://cloud.githubusercontent.com/assets/19708839/15894555/c8a56d56-2d86-11e6-9eff-122902249b57.png)

Unterschiedliches Link-Ziel, bei Eingabe eines Externen Links auf einer Beitragsseite.
1 x zu Beitragsseite (Sidebar)
1 x direkt zur verlinkten Seite
[https://izn.cms.rrze.uni-erlangen.de/]

**Comment by AstridSemm** [comment]
Wenn im Beitrag ein externer Link eingegeben wird, dann verlinkt die Beitragsüberschrift auf der Startseite dann auf die externe Seite. Lösung: Nicht direkt verlinken, sondern im Beitrag.
![beitrag-externer-link](https://cloud.githubusercontent.com/assets/11296947/15894812/4e214972-2d88-11e6-84af-9b5acf0f9afa.png)
Zusatzfrage an @xwolfde: Soll das tatsächlich so sein? Wenn ja, dann schreibe ich einen Tipp dazu.

**Comment by xwolfde** [comment]
Ja, das soll so sein. 
Bei dieser Textbox trägt man ja nicht aus versehen mal einen Link ein, oder? Und da steht ja auch ne Überschrift und eine Erklärung drunter :))

**Comment by endv02** [comment]
Hm... verstehe ich nicht... warum wird denn nur in manchen Fällen die Beitragsüberschrift mit dem externen Link versehen und nicht an allen Stellen, also nicht auch in der Sidebar? Wenn ich im Feld "Externer Link" absichtlich was eintrage und weiß was das bewirkt, will ich doch eigentlich genau dieses Verhalten an allen Stellen haben, an denen der Beitrag auftritt, und nicht an der einen schon und an der anderen nicht... das war das eigentliche Problem dran!

**Comment by xwolfde** [comment]
Sidebar? Oh... 
Wer macht denn sowas als Top-Event?

**Comment by AstridSemm** [comment]
Menschen, die testen. Wobei es in der Sidebar so funktioniert, wie man es erwartet. :o)

**Comment by xy23vaja** [comment]
Dann fehlt mir in der Erklärung der Textbox, für den Externen Link, dass die Überschrift, sprich der Beitragsseitenname die externe Verlinkung enthält.
So erwarte  ich  einen zusätzliche Link-Zeile unterhalb des Beitragstextes.
vllt. stehe ich ja auch nur auf einem unglaublich großen Schlauch;)

jedenfalls schonmal vielen Dank. Die Informationen haben mir weiter geholfen.

**Comment by xy23vaja** [comment]
Für mich wäre ein Hinweis, in der Erklärung für die Textbox hilfreich, der darauf hinweist,  dass der Beitragsseitenname mit der externe Verlinkung  verknüpft wird.
Sonst erwarte ich einen zusätzliche Link-Zeile unterhalb des Beitragstextes.
Jedenfalls schonmal vielen Dank. Die Informationen haben mir gut weiter geholfen.

**Comment by xwolfde** [comment]
Aber das steht doch schon unter der Texteingabebox :)
