### ISSUE TITLE
Techfak Template: WP Media Library not shown for some users

### ISSUE THREAD

**Issue by georg-schwarz** [RRZE-Webteam/FAU-Einrichtungen#776]
The media library does not load at all for some users on our WP instance. Used template: [TechFak](https://github.com/RRZE-Webteam/FAU-Techfak)

What we did so far:
* check different browsers firefox and chrome: similar behavior
* check different users: some work, some don't

![image](https://user-images.githubusercontent.com/28054628/95830818-8a075c80-0d38-11eb-962a-767e02d08826.png)

**Comment by xwolfde** [comment]
You are using an outdated version of the theme.  Please update to the last version in master branch.

**Comment by georg-schwarz** [comment]
Thanks! 

So it is best practice to use the latest master state instead of releases? Is it stable?

**Comment by xwolfde** [comment]
yes.

master (or main) ist our branch for "productive" situations, while "dev" and "beta" are our development branches.
The release versions are just old milestones.
