### ISSUE TITLE
Menüdarstellung fehlerhaft in Chrome

### ISSUE THREAD

**Issue by ej64ojyw** [RRZE-Webteam/FAU-Einrichtungen#778]
Darstellungsfehler in Google Chrome Version 87.0.4280.66 (Offizieller Build) (64-Bit)
Seite: http://wordpress.rrze.de/
![image](https://user-images.githubusercontent.com/58593037/99808857-c604bd00-2b41-11eb-9db0-08956f27b021.png)
Menü wird umständlich umgebrochen.

während in Firefox die Darstellung korrekt funktionierte:
![image](https://user-images.githubusercontent.com/58593037/99809035-09f7c200-2b42-11eb-8dd3-8dbdd31f2eda.png)

**Comment by ej64ojyw** [comment]
Darstellungsproblem bei zu vielen Menüpunkten und geteilter Fensteransicht (Halbe Fenstergröße) unter Firefox neuste Version / Windows 10
![grafik](https://user-images.githubusercontent.com/58593037/109171414-0ea3c600-7782-11eb-8f8c-5c9aeb4d969d.png)

Die unteren Menüpunkte können auch nicht durch scrollen ereicht werden.

**Comment by xwolfde** [comment]
nicht mehr feststellbar
