### ISSUE TITLE
Menü-Bearbeitung Top-Menü: Externe Links und Home-Link

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#78]
Aufgrund von Usability-Problemen und Fehlern bzgl. der Barrierefreiheit werden ja seit dem letzten Release 
* ein Link auf die Startseite selbst ("z.B. "Home") weggeblendet (weil redundant durch das Logo, welches genau das auch tut)
* externe Links nicht angezeigt. (weil externe Links an der Stelle ein No-Go für die Usability sind)

Leider sind nun die Webmaster zu recht verwirrt, die das nicht gelesen haben...
Es sollte daher geschaut werden, wie man das im Backend sinnvoll anzeigt, wenn jemand das Menü bearbeitet.

Oder andere Vorschläge?

**Comment by csw-** [comment]
Beim Speichern des Menüs prüfen ob einer der oben genannten Fälle vorliegt. Falls ja -> entsprechende Update Notice posten. 
Die Kontrolle wird ja schon existieren, man müsste die dann "nur" an dieser Stelle einbinden/nutzen.

**Comment by xwolfde** [comment]
Haben jetzt mehrere Rückmeldungen dazu. Zwar nicht übermässig und einstellig, aber trotzdem ärgerlich.  Insbesondere externe Links werden verwendet.
Das man externe Links in das eigene Hauptmenü tut ist mMn ein Fehler. 
Die Frage ist, ob wir die Leute da "gängeln" sollen, oder wenigstens eine Option lassen. (Ich mag es, für alles Optionen zu machen). Ich könnte mir also vorstellen, es so zu machen, daß es per Default aus ist und man eine Warnmeldung bekommt, daß man da Mist gebaut hat (ggf. sogar auf der Live-Seite ein Hinweistext, dass der LInk nicht geht). Aber im Backend bei den Advanced Option eine Möglichkeit dies explizit abzuschalten.
Letztere Option würde dne Admins drauf stossen, daß das was sie da tun, ggf. nicht gut ist.  Sie müssten es also willentlich tun.
Andererseits bleibt der Lerneffekt aus, wenn dann der Admin irgendwann mal wechselt und die Nachfolger davon nichts wissen. Und aus einer Ausnahme wird dann wieder Alltag.

**Comment by xwolfde** [comment]
In der nächsten version wird es eine entsprechende Warnung im backend geben
