### ISSUE TITLE
Chrome und Edge: h2 in Beiträgen wird falsch dargestellt

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/FAU-Einrichtungen#780]
In Chrome und Edge kommt es bei Beiträgen imemr wieder zu fehlerhaften Darstellungen der h2: Lange h2 werden etwa in der Mitte geteilt. Der zweite Teil steht dann direkt unter dem Bild. Kurze h2 stehen komplett unter dem Bild.

Beispiele:
https://www.fau.de/2020/12/news/studium/die-uni-steht-auf/
https://www.fau.de/2020/12/news/wissenschaft/bioaktive-glaeser-als-neuer-ansatz-in-der-knochenkrebstherapie/

**Comment by xwolfde** [comment]
nicht mehr feststellbar
