### ISSUE TITLE
Keine Hierarchiedarstellung in der Seitenübersicht

### ISSUE THREAD

**Issue by csw-** [RRZE-Webteam/FAU-Einrichtungen#79]
Seit einiger Zeit haben wir in der Seitenübersicht im Backend keine hierarchische Ansicht mehr (vorangestellte Bindestriche bei Unterseiten). Die Seiten werden automatisch nach Änderungsdatum sortiert - vielleicht liegt hier das Problem.. Hat jemand eine Idee was hier passiert sein könnte? Es erschwert die Arbeit schon sehr wenn die Hierarchie nicht auf einen Blick ersichtlich ist :/

![seitenhierarchie](https://cloud.githubusercontent.com/assets/6545158/15956382/78ac68b4-2ee8-11e6-88cd-8e65a032377a.png)

**Comment by AstridSemm** [comment]
Das ist bei mir übrigens dasselbe; kommt das von einem WordPress-Update oder haben wir da irgendetwas rausgeschmissen?

**Comment by xwolfde** [comment]
Das ist etwas, was ich bei eigenen WP-Installationen kenne und das eigentlich nichts mit dem Theme zu tun hat...
Bei meiner Testinstallation ist das auch alles noch da. 

Mglw ein Zusammenhang mit dem Workflow-Plugin, da bei dem Bild ja auch neue Spalten hinzugekommen sind? @rvdforst

**Comment by rvdforst** [comment]
Das hierarchisches Zeichen ( &#8212; ) wird nicht mehr angezeigt. Dummerweise WP erzeug dieses Zeichen in der Liste nur bei der Standardansicht ( 'menu_order title' === $wp_query->query['orderby'] ) und wird nicht mehr angezeigt wenn beispielsweise die Spalten sortiert werden.

**Comment by AstridSemm** [comment]
Hmmmm.... das ist aber nicht so wirklich optimal. Kann man da etwas tun?

**Comment by xwolfde** [comment]
Dann macht es sinn. D.h. wer die Hierarchie sehen will, muss oben auf Titel klicken.

**Comment by csw-** [comment]
Die Sortierung nach Titel ist leider nicht ausreichend - dannw erden die Seiten nur nach Alphabet sortiert, nicht nach Hierarchie. Die "Standard"-Ansicht wurde in unserem Fall durch eine Sortierung nach Änderungsdatum ersetzt.

**Comment by rvdforst** [comment]
OK. Mal schauen, ob ich eine Lösung finde.

**Comment by rvdforst** [comment]
Ich habe gerade eine neue custom column (Hierarchie) hinzugefügt.

**Comment by csw-** [comment]
Vielen Dank. Die Hierarchie-Ansicht geht seit heute auch wieder... (Wurde noch etwas anderes am System geändert? Gestern wurde trotz der Spalte zumindest noch keine Hierarchie angezeigt - oder vielleicht war die Umsetzung noch nicht komplett abgeschlossen als ich nachgesehen hatte...)

**Comment by rvdforst** [comment]
Ja, gestern habe ich noch einige Anpassungen gemacht. Die Einstellungen für die Verwaltung der benutzerdefinierte Spalten ist geplant.
