### ISSUE TITLE
Blogroll/Indexseite mit Header von der Startseite

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#799]
Es soll möglich sein, die Indexseiten (archiv/index) mit dem Banner von der Startseite auszustatten.
Da es zwei Startseiten-Templates gibt, hier ggf. eine Wahl vorsehen.

Wunsch von Riehle/OSR; @dirkriehle Bescheid geben, bei Beta als Tester.

**Comment by xwolfde** [comment]
In der nächsten Version des Themes enthalten.

Über Customizer einstellbar.

**Comment by dirkriehle** [comment]
Super, danke. Waren wir also auf die nächste Version. Dann 1.13?

**Comment by xwolfde** [comment]
jepp. bzw. im beta-Branch schon durchtestbar.
