### ISSUE TITLE
Einstellungen/Theme Options

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Einrichtungen#80]
In den WordPress-Einstellungen und auch den Theme Options kann man vieles einstellen - zum Teil sinnhaft, zum Teil auch eher nicht. Wenn man da mit Ahnungslosigkeit geschlagen ist, kann es passieren, dass man Dinge tut, die so niemand wollen kann (zB 15 Artikel vor dem Newsfeed auf der Startseite festnageln). Um das zu verhindern, könnte es sinnvoll sein, hier eine Art Barriere einzubauen. Das könnte zum Beispiel ein JavaScript-Alert sein, der darauf hinweist, dass man jetzt in den "Experten-Modus" wechselt oder ein entsprechender Hinweis über den jeweiligen Einstellungen.

**Comment by xwolfde** [comment]
Welche Einsetllungen konkret sollten per Default sichtbar sein und welche erst nach Freischaltung?

**Comment by xwolfde** [comment]
Mit der neuen Version wird es diesbezug eine Lösung geben.
Zu testen auf test8
