### ISSUE TITLE
Fakultätslogos in der Default Auswahl (entfernen/ergänzen)

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#81]
Die Fakultätslogos und das FAU-Logo sollen für Einrichtungen unterhalb Fakultäte nicht mehr verfügbar sein, damit man diese nicht aus versehen nutzt.
Die Logos sollen diesen Einrichtungen und der Startseite der Uni vorbehalten sein für die Position oben links.

**Comment by xwolfde** [comment]
Uh, wird leider in RW verwendet... Hm...

**Comment by csw-** [comment]
Dieser Vorschlag bezieht sich doch auf die Vorauswahl im Theme oder? Die Möglichkeit eigene Logos zu verwenden bleibt dabei also erhalten (?)

**Comment by xwolfde** [comment]
Ha, man kann weiter eigene Logos hochladen. Das gemeldete "Problem" liegt darin, daß Webmaster wohl der Einfachheit halber einfach das Fakultätslogo für ihre eigene Website nutzen, auch wenn es eben nicht die Fakultätssite ist.
Oder noch schlimmer. sie nutzen das FAU-Logo. Die Folge davon ist, das man auf unterseiten gar nirgends mehr erkennt, dass man auf einer Lehrstuhlseite ist, weil ja der Lehrstuhltitel nicht angezeigt wird.

**Comment by xwolfde** [comment]
Bei teilen der RW ist es gewollt, daß dort das Fakultätslogo steht... Wenn ich nun das RW-Logo aus der Auswahl entferne, wirkt das dort schlecht.

**Comment by xwolfde** [comment]
@csw-  In teilen eures Fachbereiches gebt ihr ja vor, daß die Leute das RW-Logo verwenden sollen. Dies ist in der Auswahl auch drin. Wäre es sehr schlimm, wenn man keine Unilogos mehr zur Auswahl hat, sofern man bei der Website nicht den Typ der Fakultätsseite hat?
Hochladen kann man immer. 
Die gefahr: jemand der partout anstelle seiner eigenen lehrstuhlbezeichnung das Unilogo da haben will, wird es auch hochladen können. Und dann vielleicht auch ein Bild mit schlechter Auflösung wählen können...

**Comment by AstridSemm** [comment]
Wir haben doch auf Unterseiten den schicken farbigen Balken. Kann man da nicht den Einrichtungsnamen/Websitetitel reinschreiben? (Schnellschuss aus der Hüfte, einfach mal hingeschrieben, damit ich's nicht vergesse)

**Comment by xwolfde** [comment]
das passiert doch schon. es geht um den Logobereich links oben neben den menü.

**Comment by AstridSemm** [comment]
Ja, aber wenn dort schon das Uni-/Fakultätslogo steht, ist ja nicht ersichtlich, dass es sich um eine Einrichtungsseite handelt oder habe ich das jetzt alles völlig falsch verstanden?

**Comment by xwolfde** [comment]
Genau das ist das Problem!  Wenn jemand kein Logo hat, soll er auch keines auswählen. DANN erscheint nämlich anstelle des Logos der Name der Einrichtung an der Stelle.
Aber leider gibt es Leute, die aus unverständlichden Gründen dann trotzdem das FAU Logo nehmen

**Comment by AstridSemm** [comment]
Beziehungsweise gibt es zT Vorgaben, das zu tun. Von daher könnte man... aber das ist vermutlich wieder eine Höllengeschichte, das alles abzufragen.

**Comment by csw-** [comment]
Was wäre denn eigentlich wenn man die Uni-Logos ergänzt statt rauszunehmen? 

Bei uns ist es ja einfach das "Problem" das die reguläre "Fakultätsebene" eigentlich bei den Fachbereichen liegt. Durch die fehlende Auswahl wird auf Lehrstuhl/Departement-Ebene dann meist einfach fälschlicherweise das Fakultätenlogo verwendet (oder eben das eigene LS/Dep-Logo). Dann gibt es natürlich noch Einrichtungen die organisatorisch entweder auf Fachbereichs- oder Fakultätenebene aufgehangen sind.

**Comment by xwolfde** [comment]
Dann reich mal ein paar Logo-Dateien rüber :)

**Comment by csw-** [comment]
Bitte sehr ;) 

![logo_rewi_cropped](https://cloud.githubusercontent.com/assets/6545158/17509530/ab67b162-5e1a-11e6-93dc-502be40758fd.jpg)
![logo_wiwi_cropped](https://cloud.githubusercontent.com/assets/6545158/17509529/ab5b1204-5e1a-11e6-9d47-8a3ff80858c2.jpg)

**Comment by xwolfde** [comment]
cropped? ^^

**Comment by csw-** [comment]
Ich weiss..... Aber wenn ich die originalen FAU-Logos nehme kommt es zu einem Überstand mit dem aufklappbaren Hauptmenü an der unteren Logokante.

Am 09.08.2016 3:38 PM schrieb Wolfgang Wiese <notifications@github.com>:cropped? ^^

**Comment by xwolfde** [comment]
hab die beiden Logos in der nächsten version in der Defaultauswahl unter Anpassen. 
Hier muss aber nochmal drüber nachgedacht werden, ob es so Sinn macht, denn im Prinzip schleppen wir dann ja später alle Logos immer in den Themes mit. Und wenn wenn diese beiden nun dabei sind, dann würden mglw. auch andere folgen...
Ggf. müssen wir die Lösung daher in Zukunft nochmal ändern.
