### ISSUE TITLE
Beta - Padding fehlt bei Untertiteln in mobiler Version der Seite

### ISSUE THREAD

**Issue by ej64ojyw** [RRZE-Webteam/FAU-Einrichtungen#813]
Auf https://www.beta.wordpress.rrze.fau.de/tests/komplexe-testseite/ 
fehlt beim Untertitel das Padding auf der linken Seite in der Handy-Version

![grafik](https://user-images.githubusercontent.com/58593037/117110358-4765aa00-ad86-11eb-8ba8-52aca1695ffb.png)

**Comment by xwolfde** [comment]
in nächster beta, 1.12.74
