### ISSUE TITLE
Beta: Fehlender Abstand unter Tabellen am Seitenende

### ISSUE THREAD

**Issue by ej64ojyw** [RRZE-Webteam/FAU-Einrichtungen#814]
Am Seitenende fehlt über dem Footer etwas Abstand, bei Tabellen und bestimmten Inhalten sieht es so aktuell etwas unschön aus:
![grafik](https://user-images.githubusercontent.com/58593037/117110677-cb1f9680-ad86-11eb-808c-6fcee3cd7e06.png)

Seite: https://www.beta.wordpress.rrze.fau.de/entwicklung/design/farben/

**Comment by xwolfde** [comment]
in nächster beta, 1.12.74
