### ISSUE TITLE
Beta: FAU-Logo im Footer könnte minimal mehr Abstand benötigen (Mobile)

### ISSUE THREAD

**Issue by ej64ojyw** [RRZE-Webteam/FAU-Einrichtungen#815]
Im Footer hat das neue FAU-Logo weniger Abstand zur Footer-Oberkante als im bestehenden Fau.de Footer.
Sieht etwas unschön aus, mit dem kleineren Abstand nach oben. 

![grafik](https://user-images.githubusercontent.com/58593037/117111002-44b78480-ad87-11eb-9279-abafbb6f4a1a.png)

zum Vergleich:
![grafik](https://user-images.githubusercontent.com/58593037/117111041-539e3700-ad87-11eb-9a5e-905c89ee1ee5.png)

**Comment by xwolfde** [comment]
in nächster beta, 1.12.74
