### ISSUE TITLE
Werbung in der Sidebar kollidiert mit Footer

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Einrichtungen#82]
Das Werbebanner in der Sidebar kollidiert bei bestimmten Skalierungsstufen (z.B. 1920x1080-Monitor) auf kürzeren Seiten mit dem Footer. Hier wäre eine höhere Mindesteshöhe für den weißen Bereich wünschenswert (zu streckender Bereich: nach dem Portalmenü).

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/16193733/22af0370-36f1-11e6-8a69-7d158ab004e4.JPG)

(Die Seite im Screenshot ist eine durchaus typische, denn Portalseiten müssen nicht zwingend zwei Reihen in der Navigation haben. Der Textbereich hat genau die richtige Länge oder könnte sogar noch kürzer sein für diesen Seitentyp.)

**Comment by xwolfde** [comment]
Ja, der Code wurde damals nachträglich hinzugepfriemeltm und ist deswegen grauslig.
Wenn wir das schon reparieren, dann richtig. Daher bitte ich um Vorschlag, wie die Skyscraper-Werbung auf kleinen Displays (bis 320px, bis 480px aussehen soll. Und an welcher Stelle -über Text, unter Text, über Menü in der Seite..?

**Comment by wrkb** [comment]
Gern, Vorschlag kommt. Wir müssen dazu aber mit der Leitung Marketing sprechen, das dauert wegen Urlaubs ca. 2 Wochen. Falls das zu lang dauert, melde dich bitte. Wir haben ja fürs Erste einen Workaround.

**Comment by xwolfde** [comment]
Für mich kein Problem  -  die nächste Version würde eh nicht früher kommen. Und als Workaround einfach ein bisschen mehr Content im Inhaltsteil schreiben kriegt ihr schon hin.

**Comment by xwolfde** [comment]
Notice: http://www.perun.net/2016/09/13/wp_is_mobile-wordpress-inhalte-nur-fuer-mobile-geraete/

Nur Semierkennung über Browseragent. Funktioniert keinesfalls für alle Browser, da sehr viele Handy-Browser inzwischen dazu übergegangen sind, sich nicht als Handy erkennen zu geben.

**Comment by xwolfde** [comment]
Ref #132 . 
Es bleibt weiterhin die Frage offen der Reihenfolge der Inhalte. Aus den bisherigen Rückmeldungen wurde dieses Problem trotz Erklärung nicht verstanden.  Daher lieber selbst in kleinen Expertenkreis eine Lösung ausdenken.

**Comment by xwolfde** [comment]
Wird Thema in der Design-Runde

**Comment by xwolfde** [comment]
Kein Vorschlag binnen eines Jahres gekommen.
Wurde auch danach nicht nochmal angesprochen.
Worarounds:
* Breites Banner im Content nutzen.
* Seiten mit sinnvollen Inhalt schreiben. Seiten mit so kurzen Inhalt sind keine sinnvollen Seiten und Nullnummern fürs SEO.

War offenbar nicht wichtig. Daher Fall nun geschlossen.
