### ISSUE TITLE
Fehlendes Padding auf Kontaktseiten (Person-PlugIn)

### ISSUE THREAD

**Issue by ej64ojyw** [RRZE-Webteam/FAU-Einrichtungen#826]
Problem:

Die mobile Ansicht besitzt kein Padding.

--
Beispielseite:
https://www.xquant.nat.fau.de/person/dr-pavlo-bilous/

![grafik](https://user-images.githubusercontent.com/58593037/118446340-d1e7cb00-b6ef-11eb-9931-575b139d002a.png)

**Comment by xwolfde** [comment]
im nächsten update gefixt
