### ISSUE TITLE
Rechte Spalte verlängert sich auf gesamte Seitenlänge

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/FAU-Einrichtungen#828]
Auf Seiten mit den Templates Portalseiten, Portalindex und Standard-Template wird die rechte Spalte bis nach unten durchgezogen, was nur noch ein zweispaltiges (Shortcode-)Menü erlaubt.

Nur beim Portalindex gibt es einen durchgezogenen blauen Trennungsstrich,

Beispiele
https://www.fau.de/education/bewerbung/
https://www.fau.de/education/international/
https://www.fau.de/research/service-fuer-forschende/

**Comment by xwolfde** [comment]
fixed in update
