### ISSUE TITLE
CSS img.size-full: Falscher margin bei Einbindung eines Bildes in "vollständiger Größe"

### ISSUE THREAD

**Issue by csw-** [RRZE-Webteam/FAU-Einrichtungen#83]
Beim Einbinden eines Bildes in vollständiger Größe und mit Bildunterschrift, erhält das Bild einen margin-right von 10px. Dadurch steht die Bildunterschrift rechts über. (siehe Bild)

Soweit ich das sehen kann kommt das durch "display: block;" in der size-full-Klasse. Bin mir jetzt nicht sicher ob das in anderen Szenarios ok geht, ich werde vorläufig aber einfach "mittelgroß" verwenden - in diesem/meinem Fall spielt das hier keine Rolle da das Bild ohnehin nicht größer als 300x200px ist.

![margin](https://cloud.githubusercontent.com/assets/6545158/16448294/032ee6d0-3df1-11e6-866c-2094ac37e909.png)

**Comment by xwolfde** [comment]
Danke für den Hinweis. An den Stellen bin ich gerade auch anderweitig dran.

**Comment by xwolfde** [comment]
Du hast recht, auch mit der Lösung.
Das war noch in den Tiefen des Original***codes enthalten :)

Hier hab ich es bereits in meiner ENtwicklungsversion:
http://test8.tindu.rrze.uni-erlangen.de/tests/medien-und-grafiken/
