### ISSUE TITLE
Regression in Version 1.13 bei PHP 8.0.6?

### ISSUE THREAD

**Issue by zu83buka** [RRZE-Webteam/FAU-Einrichtungen#838]
Hallo,

ich unterstütze ein An-Institut (Art. 103 Abs. 2 BayHSchG) der FAU bei ihrer WordPress-Administration. Dort kommt WordPress 5.7.2 und PHP 8.0.6 zum Einsatz. Ich habe beobachtet, dass FAU-Einrichtungen in Version 1.13 überhaupt keine Anzeige produziert, während 1.12 auch mit PHP 8.0.6 tadellos funktioniert. Bei einem anderen Webhoster, ebenfalls mit PHP 8.0.6 und WordPress 5.7.2, kommt es zu einem Server-Fehler 500 in Version 1.13, während 1.12 tadellos funktioniert. Mit Blick auf den PHP-Lebenszyklus (https://www.php.net/supported-versions.php) würde ich nur äußerst ungern auf PHP 7.4 zurückgehen...

Viele Grüße
Roman Kindl

**Comment by xwolfde** [comment]
Können Sie uns die Warn/Error-Meldung zukommen lassen, die in der Errorlog ausgegeben wird?

**Comment by zu83buka** [comment]
Leider gibt der Webhoster, den das Institut verwendet, keine PHP-Fehlermeldung aus, auch, wenn das in der php.ini angewiesen ist ("error_reporting = E_ALL display_errors = On"). Der Fehler ist aber reproduzierbar, wenn ich zwischen den PHP-Version 7.4.19 und 8.0.6 wechsele (7.4.19: keine Beanstandung). Vielleicht hilft der HTML-[Quelltext](https://github.com/RRZE-Webteam/FAU-Einrichtungen/files/6528577/Quelltext.txt) weiter, der ausgegeben wird, wenn das Theme geladen wird.

Gab es denn einen Test des Themes in Version 1.13 mit PHP 8.0.x? Ich will gar nicht ausschließen, dass der Fehler auf der Seite des Webhosters oder bei mir als Anwender liegt.

**Comment by zu83buka** [comment]
Es scheint einen Zusammenhang mit BackWPup in Version 3.8.0 zu geben: Bei Deaktivierung des Plug-Ins tritt der Fehler nicht mehr aus.

**Comment by xwolfde** [comment]
Na dann haben wir ja Glück gehabt ;)

Es hätte mich auch etwas gewundert: Wir haben nämlich in den Funktionen eher aufgeräumt und gelöscht, aber  keine neuen eingefügt.
