### ISSUE TITLE
Shariff-Buttons rutschen in mobile über die Sidebar

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#842]
Aus einem Helpdesk-Fall:
http://go.fau.de/9qx7d

Bsp-Seite, auf der das Problem auftritt:
https://www.geographie.nat.fau.de/forschung/ag-baeumler/

Die Social-Media Buttons rutschen in Kombination mit dem
Template Portalseite über die Sidebar.

![grafik](https://user-images.githubusercontent.com/58593037/119772382-56d89e80-bebf-11eb-854d-b66ac70dda5a.png)

**Comment by Albager** [comment]
M. E. ist das unabhängig vom Seitentemplate - selbes Verhalten mit "Portalindex" und "Standardtemplate". Wenn die Seite in der vollen Breite angezeigt wird, sind die SoMes unten:
![image](https://user-images.githubusercontent.com/11389126/119978448-f24e3a00-bfb9-11eb-8a50-250027b0b874.png)


 Nur wenn das responsive Design greift rutschen sie über die Kontaktinformationen.

**Comment by xwolfde** [comment]
Ich glaub wir reden hier aneinander vorbei:
Die Sharif-Icons werden und wurden immer im Content plaziert. (Außer sie wurden als WIdget eingebaut-)
Das heißt, sie sind IMMER im COntent-Teil und dort am Ende.

Bei mobile wird die Sitebar unter den Content-Teil positioniert.
Und damit ist dann die SItebar auch unter den Icons.

Ich sehe und verstehe nicht was sich hier geändert haben sollte?

**Comment by Albager** [comment]
Hallo, ich glaube gar nicht, dass sich da etwas geändert hat - vermutlich war es schon immer so, wie Sie ja auch schreiben.

Semantisch würde ich persönlich sagen, dass die SoMe-Buttons ja eigentlich eher "meta" sind (also nicht Teil des eigentlichen contents), die Kontaktinformationen (bzw. die Sidebar) hingegen schon. Aber das ist wohl Definitions- bzw. Geschmackssache.

Es sieht unserer Meinung nach nur irgendwie ein bisschen doof aus, wenn die Buttons bei mobile dann plötzlich gefühlt "dazwischen" rutschen.

**Comment by xwolfde** [comment]
Diese Möglichkeit (im WIdget einbauen) besteht ja schon. Siehe Widgets: News Sidebar


Wie auch immer: In der neuen V2  ab Ende Januar werden die Abstände durch den Neubau der Grid etwas verbessert.
