### ISSUE TITLE
Verborgenes Element hat fokussierbaren Inhalt

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/FAU-Einrichtungen#853]
Siteimprove zeigt für ein paar Seiten ein Accessibility-Problem an: "Verborgenes Element hat fokussierbaren Inhalt"
Beispiel-Seite: https://www.fau.de/presseportal-der-fau/pressebilder-zum-download/pressebilder-prof-dr-joachim-hornegger/

**Comment by xwolfde** [comment]
In V2 gefixt
