### ISSUE TITLE
FAUbox-Galerien: alt-Text fehlt

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/FAU-Einrichtungen#854]
Wenn Galerien über die FAUbox eingebunden werden, haben die Bilder keinen alt-Text.
Beispiel: https://www.fau.de/2021/04/news/himbeerpalast-offiziell-an-fau-uebergeben/

Es könnte die Beschreibung (description) aus den Metadaten übernommen werden.

Anmerkung: Ich glaube, dieses Problem gab es schon mal, ich dachte aber, es sei mittlerweile schon behoben worden.

**Comment by xwolfde** [comment]
Ja, da hatten wir schon mal drüber gegrübelt.
Das Problem ist aber mEn nicht lösbar (hat auch nichts mit dem Theme zu tun, sondern mit dem Remoter-Plugin), da die Bilddateien aus der FAUbox nicht mit beschreibenden Texten ausgestattet sind, die man für den ALT-Tag nutzen kann.

**Comment by AndiWebred** [comment]
In den IPTC-Daten müsste eigentlich bei allen Bildern die Description ausgefüllt sein. Kann man die nicht hernehmen?

**Comment by xwolfde** [comment]
Die IPTC Daten können leider nicht ausgewertet werden, da das Bild als externe Datei nicht von WordPress verarbeitet wird, sondern nur verlinkt/gesourced wird.
