### ISSUE TITLE
Wunsch auf alternatives Linkziel für Startseiten-News Button (Gesamte Blogroll statt Kategorien)

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#855]
aus http://go.fau.de/9q9ih
Es besteht der Kundenwunsch, dass man auf der Startseite
für den Button unter der Blogroll auch die gesamte Blogroll verlinken kann statt nur einzelner Kategorien.

**Comment by xwolfde** [comment]
Das ist (mit V2) nur möglich, wenn als Startseitentyp die Blogroll gewählt wird. Dann kommt unten die Taxonomie automatisch.
In dem Fall kann aber oben kein Introtext-Content gegeben werden und auch nicht der Slider. Es erscheint dann aber der Banner.

Als eigenes Template oder Option ist es aber nicht möglich.
