### ISSUE TITLE
Link "Zum Hauptinhalt springen" ist nicht der erste Link (?)

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/FAU-Einrichtungen#856]
Siteimprove zeigt für alle Seiten den Accessibility-Fehler "Link "Zum Hauptinhalt springen" fehlt" an. Ich hab das als false-positive an siteimprove gemeldet und die Antwort bekommen: Nein, das ist ein Fehler, weil: "It appears that the first reachable element is not the link to the main content but instead the search bar element, which means that the error is legit and not false positive."

Ich hab das überprüft und kann die Antwort bestätigen. Oder ist das schon so korrekt von unserer Seite aus?

**Comment by xwolfde** [comment]
Ursache ist tabindex="0" im der Search-Input.  Prüfen, ob diese da sein muss.

**Comment by xwolfde** [comment]
Ab V2 behoben

**Comment by AndiWebred** [comment]
Könntet ihr das nochmal prüfen? Siteimprove zeigt mir den Fehler für alle Seiten immer noch an. Danke!
