### ISSUE TITLE
Siteimprove: "Text wird abgeschnitten, wenn sein Größe verändert wird"

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/FAU-Einrichtungen#857]
Siteiimprove zeigt uns den Fehler "Text wird abgeschnitten, wenn sein Größe verändert wird" auf allen Seiten an. Wir dachten, das wäre ein false positive, weil wir ja ohne Probleme reinzoomen können. Sieht so aus, als sei hier was anderes gemeint. Es geht wohl darum, dass nur(!) der Text auf 200% vergrößert wird. Und das sieht dann so aus wie im Screenshot (hat Siteimprove geschickt).

<img width="947" alt="mozilla 200%" src="https://user-images.githubusercontent.com/53909165/126319706-a49a0931-c764-42fe-b3f8-0eb64e31ef88.png">

Ich zitiere:
A way to test that is if you open Mozilla -> zoom to 200% -> Settings -> Select Default zoom 200% as it is shown on the second screenshot. 
Or change the font size in Chrome settings -> chrome://settings/fonts and change the font size from the default 16px up to 32px (200% of 16px).

Ich habs so ausprobiert und kann dann den Fehler bestätigen.

**Comment by xwolfde** [comment]
Es wird bereits rem verwendet...

**Comment by jkphl** [comment]
@xwolfde Nicht für die Höhe der fraglichen Links …

![fau-height](https://user-images.githubusercontent.com/4446936/142198259-2dacb023-41fa-4905-8c5d-49f5db4496ee.jpg)

**Comment by xwolfde** [comment]
Args, hast recht. ich war fixiert auf line-height und font-size

**Comment by krokodok** [comment]
@xwolfde Hast du hier schon etwas unternommen? Ich kann den Screenshot mit der Anleitung weder in Chrome noch Firefox reproduzieren.

**Comment by krokodok** [comment]
Wir haben das auf `rem` umgestellt, sodass es jetzt passen sollte.

**Comment by xwolfde** [comment]
Passt. Nur die Höhe der Meta ist nun zu hoch. Padding-top/bottom ändern?

**Comment by krokodok** [comment]
Hat damit eigentlich nichts zu tun; ist wahrscheinlich eher im Zuge der Menü-Anpassungen passiert. Korrigieren wir dort dann wieder.

**Comment by xwolfde** [comment]
Also aktuell ist die Padding von .meta-links noch immer bei 15px bei Auflösungen über 768px.

Aber das kann ich selbst im Nachgang noch anpassen.
Sonst passt alles im Issue.
