### ISSUE TITLE
Blockquotes verdecken Klickfläche der Links in der Sidebar

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#860]
Die Blockquotes verhindern, dass man als Nutzer die betroffenen Links in der Sidebar klicken kann.

![grafik](https://user-images.githubusercontent.com/58593037/129539368-43aa2ae9-6787-4794-bb2d-d65cf93b14b9.png)

Aus Helpdesk: http://go.fau.de/9rd7l

**Comment by cassandre** [comment]
Momentaner Workaround im Customizer > Additional CSS:
`````
@media (min-width: 768px) {
	#content blockquote {
		position: static;
		padding-left: 0;
	}
	#content blockquote:before {
		position: relative;
		display: block;
		float: left;
		left: -5px;
		margin-right: 5px;
	}
}
`````

**Comment by krokodok** [comment]
Konnte nicht mehr reproduziert werden.

**Comment by xwolfde** [comment]
ja, passt
