### ISSUE TITLE
Neue Fehlergrafiken

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#865]
Durch Wegfall des Siegel-Bestandteiles #864 bei den Fehlerseiten soll dort ein Ersatz gefunden werden.

Insbesondere für 
- "File not Found"
- "Permission denied"
- Andere Fehler

**Comment by xwolfde** [comment]
Ggf. brauchen wir eine Option zur Auswahl der Art der Grafiken:
- "Formelle Fehlerseite" 
- "Lustige Fehlerseiten"  oder
-  "Wissenschaftliche Fehlerseiten"

**Comment by lukasniebler** [comment]
Die Idee mit den wissenschaftlichen Erklärungen finde ich super. Zwecks Grafik müsste man die vermutlich selbst basteln. (Vielleicht lässt man die Wissenschaftler ja eine kleine Skizze dazu runterkritzeln. (Mit Kugelschreiber einfach auf ner DinA4 Seite. Dann scannen und es wird digitalisiert und zur SVG konvertiert) - Wäre zumindest unterhaltsam zu sehen, was Sie dazuzeichnen zur schriftlichen Erklärung.. 


____
Zwecks Grafiken hatte ich mal auf Shutterstock im August geschaut. Allerdings hat mich da nichts richtig überzeugt, was als 404-Grafik für die FAU herhalten könnte.

(Die magere Ausbeute damals bei Shutterst. - Der Roboter ist Google's 404 Lösung. Gabs aber auch bei Shutterstock:)
![grafik](https://user-images.githubusercontent.com/58593037/134192288-3ef03cb5-5112-4d21-87bc-a503c939f588.png)
(Die zweite Grafik fand ich vom Konzept richtung Techfak nicht schlecht. 

//Und das Buch, weil unser Professor immer erzählt hat, dass die beliebten Seiten zum Beginn seines Biologie-Studiums immer in der Bücherei rausgerissen waren, weil die Studenten sich die eingesteckt haben :-) | Denke aber das ist nicht mehr relevant für 2021/22
![grafik](https://user-images.githubusercontent.com/58593037/134193284-5e5736f0-3cbe-4b69-9479-5dd34e517aad.png)

**Comment by xwolfde** [comment]
Lass mal die Elisabeth schauen. Sie wird hier mal bei unseren Wissenschaftler fragen, dass wir da was individuelles kriegen. Z.B. eine Formel aus der Mathematik/Natfak zur Darstellung einer Nullmenge; Oder eine nihilistische Reflexion aus der Phil. etc pp.
Schaun ma mal.

**Comment by xwolfde** [comment]
Entwürfe liegen vor. Müssen programmiertechnisch umgesetzt werden.

**Comment by xwolfde** [comment]
Code wird wie bei der FAU ORGA Breadcrumb eingebaut mittels Shortcode, wenn das Plugin FAU Fehlermeldungen vorhanden und aktiv ist.
