### ISSUE TITLE
Neue Logo-Dimension berücksichtigen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#866]
Durch neue Maße des Logos verschiebt sich die Positionierung und der Platz. Hierzu bedarf es Lösungen die abwärtscompatibel sind - insbesondere in Hinblick eigener Logos, die bislang auf "Baseline" ausgerichtet waren.

**Comment by xwolfde** [comment]
Zur Umsetzung des HTML-Codes:


Das Theme wird bei Websites, die kein eigenes Logo liefern, das "Logo" generieren.

Und zwar abhängig vom Typ der Website (einstellbar im Customizer):
```
 * website_type: 
	 *  0 = Fakultaetsportal oder zentrale Einrichtung
	 *	=> Fakultatslogo 
	 *  1 = Lehrstuhl oder eine andere Einrichtung die einer Fakultät zugeordnet ist 
         *	=> FAU Logo mit blauer FAU bezeichnung + Titel in Fakultatsfarbe 
	 *  2 = Zentrale Einrichtungen  
	 *	=> FAU Logo mit blauer FAU bezeichnung + Titel in blau 
	 *  3 = Koopertation mit Externen (neu ab 1.4)
	 *	=> Kein FAU Logo 
	 *  -1 = FAU-Portal
         *	=> FAU Logo mit Schrift 
	
```
Das "generierte Logo" könnte theretisch entweder aus einer Inline-SVG zusammengebaut werden oder aus einer SVG + HTML-Texte in `<span>`.

Beispiel Variante IMG-SVG + HTML:
```

<a><img src="Sitelogo-ohne-Textbestandteil.svg" alt=""><span>Sitetitel</span></a>
```

Beispiel Variante Inline SVG:

```
<a><svg aria-labeledby="#titel"><symbol><titel id="titel">Sitetitel</titel>
<g>...</g>
<text>Optischer Titel</text></symbol></svg></a>
```

Nach längeren Überlegen tendiere ich zur Variante IMG-SVG + HTML.

Grund:
Ich habe via CSS bessere Optionen die jeweiligen Textbereiche anzupassen und -bei mobile Devices- anders zu positionieren als wenn dies ein Bereich in der Inline-SVG wäre. Inline-SVG kann ich meines Erachtens nach zwar auch via CSS beeinflussen, jedoch nicht so gut, da einige Anweisungen in dem Kontext nicht wirken.

Der Vorteil von reinen SVG wäre natürlich, dass man alles downloaden könnte.

Ich lass mich aber gern überzeugen, dass es andersrum doch besser wäre.

**Comment by xwolfde** [comment]
Die folgende Grafik gibt Auskunft über die umzusetzenden Abstände zwischen Logo und Titeln, sowie zum Rand:
![schutzzonen-proportionen](https://user-images.githubusercontent.com/1070669/141081514-2e1963b2-5d9e-4b98-878c-a5dba464db73.png)

**Comment by xwolfde** [comment]
Ein erster Ansatz ist im Code. HTML wird geliefert.

ToDO: @jkphl : 
- HTML checken, ob ok
- Kopfteil mit Logo und Menü in Auflösungen < 1400 Pixel prüfen

Info zur Nutzung:
- Customizer: Website-Informationen: Dort kann ein Titel der Site, der Kurztitel für das Logo, die ABkürzung und der Kontext der Website eingegeben werden. Damit kann dieser Teil geprüft werden.
- Momentan wird Roboto als Schrift für das Logo verwendet. Ggf. finden wir aber noch eine Open Font Licence Schrift, die dem "FAUSans" näher kommt, die wir stattdessen nutzen.

**Comment by krokodok** [comment]
Die Einbindung des neuen Logos ist prinzipiell okay.

An anderer Stelle hatten wir zum HTML ja bereits angemerkt:

> Das SVG hat sowohl aria-hidden="true" als auch 'aria-labelledby' und 'role'. Das widerspricht sich. Deshalb schlagen wir vor, aria-hidden beizubehalten und den Rest zu entfernen. Dann existiert das "FAU" für Screenreader quasi nicht. Es hat aber auch nicht wirklich Informationsgehalt, weil darunter/daneben dann sowieso "Friedrich-Alexander-Universität" steht.

Am Markup haben wir aber jetzt erstmal nichts geändert.

**Comment by xwolfde** [comment]
Wenn ich das Menü hovere, wird ein Teil des Logos verdeckt/geschnitten.

Kann man hier irgendwas optimieren?

**Comment by krokodok** [comment]
Nein, fürs mehrzeilige Menü ist mir jetzt nichts eingefallen.

**Comment by xwolfde** [comment]
Ok, dann lassen wir es so. Mir fällt da auch nichts ein, was gut aussehen würde und unaufwendig ist.

Falls euch euch doch noch was einfällt sind Vorschläge für eine spätere Optimierung (Erweiterungsauftrag) willkommen.
