### ISSUE TITLE
Breitere Viewpoint definieren

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#867]
Im Rahmen von #866 wird eine breitere Viewport als $breakLG  eingeführt.

**Comment by krokodok** [comment]
Wir sind alle Templates der Test-Seite durchgegangen und haben alle möglichen kleineren Unsauberkeiten mit CSS ausgebessert. Die Randspalte fängt jetzt erst einen Breakpoint später an, weil vorher der Text zu schmal zum Lesen war.

**Comment by xwolfde** [comment]
Bei dem Template Seite mit Navi links + Sidebar rechts ist bei einer Auflösung  kleiner 1400  und größer 996 die Sidebar rechts falsch. (Diese war vorher von mir in diesem Bereich dann kein flex, sondern als  floating gesetzt.)
Jetzt haben wir dort ein horizontales Scrolling UND der Sidebar-Bereich hat auch nicht die Mindestbreite von 235px.
![grafik](https://user-images.githubusercontent.com/1070669/145035270-a104ed1f-c359-4caf-9730-0de2a3565874.png)

**Comment by krokodok** [comment]
Da hat noch was nicht gestimmt. Mit dem letzten Commit passt es wieder. Ich habe es weiterhin mit Flex gemacht, nicht mit Float. Wenn ihr lieber Float hättet, sagt Bescheid.

**Comment by xwolfde** [comment]
Ggf. auch hier rein, schon im anderen Issue geschrieben:
Der bisherige Sticky Header ist nicht mehr vorhanden/funktioniert nicht mehr.

**Comment by krokodok** [comment]
Der Footer ist jetzt wieder am unteren Seitenende ausgerichtet.

**Comment by xwolfde** [comment]
ok, jetzt passt alles. Issue erfüllt.
