### ISSUE TITLE
Ausrichtung Menü

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#871]
Im Rahmen der Anpassung an die neuen Dimensionen sollte das Problem mit der ungleichen Breite des Submenüs im Verhältnis zum Logo darüber und dem Start des Menüs bei wenig Einträgen berücksichtigt werden.

Konkret: Das Menü soll sich nach rechts ausrichten statt an der Endbreite zum Bereich des Logos links.
Also Bei Auflösung größer 768px: Logo links, Menü rechts.

**Comment by xwolfde** [comment]
Im Branch für ersten Ansatz für Breakpint XL (1400 Pixel) vorhanden. 
Es muss aber noch feingetunet und getestet werden. Außerdem Anpassungen an andere Auflösungen.

**Comment by krokodok** [comment]
Die Ausrichtung sollte in allen Auflösungen passen.

**Comment by xwolfde** [comment]
Äh, nein?
![grafik](https://user-images.githubusercontent.com/1070669/145032995-92ed0fa8-db5b-4b05-bf3e-3f9c56986db3.png)

Menu ist links ausgerichtet?

**Comment by krokodok** [comment]
Wurde mit dem letzten Push wieder korrigiert.

**Comment by xwolfde** [comment]
Ich sehe gerade... Wo ist denn der Sticky Header hin verschwunden?
Mit FF ist in keiner Auflösung noch ein Sticky Header vorhanden

**Comment by krokodok** [comment]
Ist mit dem letzten Commit wiedereingeführt worden.

**Comment by xwolfde** [comment]
Um... fast.

Im Nicht eingeloggten Zustand ist alles in Ordnung.

Aber bei der vorhandensein der Admin-Bar wird die falsche Höhe angesetzt.
(Die WP-Admin-Bar hat zwei Höhen, einmal für mobile und einmal für große AUflösungen)

Bei Auflösung über 768px ist daher noch ein Offset vorhanden:
![grafik](https://user-images.githubusercontent.com/1070669/145065682-9d0114b4-b8fd-4ab4-8fd3-02f2fbeb6145.png)

Bei kleiner Auflösung ist der oben ok::
![grafik](https://user-images.githubusercontent.com/1070669/145065868-2db921d1-71a7-4683-b275-b197b513b3ec.png)


Allerdings haben wir dort nun ein neues Problem: Die Subnav ist offen?

**Comment by xwolfde** [comment]
Die Subnav ist in kleiner Auflösung auch offen, wenn man nicht angemeldet ist:
![grafik](https://user-images.githubusercontent.com/1070669/145066111-93d1f43b-ba44-49b5-92b6-a15ae8d0210d.png)

**Comment by krokodok** [comment]
Abstand zur Admin-Leiste und Submenü mobil sollten jetzt passen.

**Comment by xwolfde** [comment]
Jepp, passt.
Auch die Subnav ist in Ordnung.

Der Issue  ist erfüllt.
