### ISSUE TITLE
Meta + Orga-Breadcrumb

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#873]
(Der Meta-Bereich ist die graue Leiste ganz oben auf der Seite.)

Gewünscht ist folgendes:

Die Meta soll künftig aus folgenden Bestandteilen bestehen:

1. FAU-Logo als Link zur FAU-Website (optional, entfält bei der fau.de Seite). Es handelt sich um ein Link um ein SVG Icon.
2. Organisatorische Breadcrumb (aktuell nur Fakultätssname) (optional, entfält bei der fau.de Seite oder auf Fakultätsseiten)
3. Portallinks (begrenzt)
4. Suchleiste (ggf. aus Widget)
5. Sprachschalter (Optional, ggf. aus Widget)

Bei Auflösungen >=1024px:
Die Meta soll in der Darstellung > 1024px alle Elemente bis auf die OrgaBreadcrumb in einer LInie darstellen, wie jetzt bereits.
Die Orgabreadcrumb soll optisch unter der grauen Linie positioniert werden. Die Orga-Breadcrumb wird minimal aus einem Fakultätsnamen bestehen. In Falle von Lehrstühlen kommt jedoch noch die Angabe eines Departments oder eines Instituts hinzu.

Bei Auflösungen <1024px: 
Das FAU-Logo wird umgewandelt in ein Funktionselement (Button), welches bei Klick nicht mehr auf die Website der FAU führt, sondern ähnlich das Hamburger-Menü optisch ein Submenü aufmacht. In diesem werden dann die folgenden Bestandteile sichtbar/aufrufbar:
- Link zur FAU
- Orga-Breadcrumb
- Suche
- optionaler Sprachschalter
- Portalinks

Die Metaleiste zeigt optisch dann also:
- Links das kleine FAU Logo mit seiner Funktion als Button
- Mittig das Logo der Website in max. 400px
- Rechts das Hamburger für das normale Hauptmenü (und etwaige Subnav, wie bisher)

**Comment by krokodok** [comment]
Ich greife das hier mal auf:

> 1. FAU-Logo als Link zur FAU-Website (optional, entfält bei der fau.de Seite). Es handelt sich um ein Link um ein SVG Icon.
> 2. Organisatorische Breadcrumb (aktuell nur Fakultätssname) (optional, entfält bei der fau.de Seite oder auf Fakultätsseiten)
> 3. Portallinks (begrenzt)
> 4. Suchleiste (ggf. aus Widget)
> 5. Sprachschalter (Optional, ggf. aus Widget)

und darauf aufbauend diesen Vorschlag:

> Die Metaleiste zeigt optisch dann also:

> Links das kleine FAU Logo mit seiner Funktion als Button
> Mittig das Logo der Website in max. 400px
> Rechts das Hamburger für das normale Hauptmenü (und etwaige Subnav, wie bisher)

Hinter dem FAU-Logo verborgen soll ein Submenü sein mit:

> Link zur FAU
> Orga-Breadcrumb
> Suche
> optionaler Sprachschalter
> Portalinks

Der Vorschlag würde bei Nicht-FAU-Seiten problemlos funktionieren. Allerdings ist ja oben beschrieben, dass das FAU-Logo nur optional sein soll, wenn man auf einer Nicht-FAU-Seite ist. Ich frage mich: Wie gelange ich dann auf der FAU-Seite zu Suche, Sprachschalter und Portallinks?

Deshalb würde ich es umsortieren und Suche, Sprachschalter sowie Portallinks mit ins Hamburger-Menü zum Haupt-Menü dazunehmen. Das ist kein unübliches Pattern. Der optionale Button erscheint dann nur, wenn er benötigt wird, und beinhaltet auch nur optionale Steuerungselemente.

Außerdem würde ich das Logo der Website nicht mittig ins kleine Meta-Menü hereinsetzen, sondern darunter belassen. So ist es ja mit dem FAU-Logo auch gemacht; das ist schon fertig gestylet und sitzt gut.

Dann hätten wir bei einer FAU-Seite nur das Burger-Menü im Header, das dann Suche, Sprachschalter, Portallinks, Hauptmenü und Subnav öffnet.

Bei einer Nicht-FAU-Seite hätten wir zusätzlich dazu links davon das FAU-Logo, das den Link zur FAU und die Orga-Breadcrumb öffnet. Das ergibt auch inhaltlich irgendwie mehr Sinn – hier sind nur Steuerungselemente gruppiert, die einen weg von der jetzigen Seite weisen und hin zur FAU, in irgendeiner ebene.

**Comment by xwolfde** [comment]
Hm, also jetzt ist es ja so bei einer FAU-Seite:

![grafik](https://user-images.githubusercontent.com/1070669/144427353-c83579ef-af07-48eb-b806-575082237cfc.png)

Also würde dann die Lupe und der Sprachschalter wegfallen und ins Hamburger?
Aber dann haben wir da keine Symmetrie mehr, weil links dann ja nichts ist.
Und das Problem, dass die Einrichtungen der FAU mit eigenen Logos ihr eigenes Logo nicht sehen können ist dann immer noch vorhanden... Zudem ist dann die Metaleiste über dem Einrichtungsnamen vom Platz her ja noch da un dnimmt eben wertvollen Platz weg.

Wäre es nicht eine Lösung bei Nicht-FAU-Einrichtungen, dass hier dann eben ein Symbol als Fallback aus einer SVG-Background o.ä. gesetzt wird als Klicksymbol?

**Comment by krokodok** [comment]
![image](https://user-images.githubusercontent.com/10128264/144438074-3e7c5899-a5c0-4c0b-ad08-8e634b8158d8.png)

Also ich verstehe es im neuen Design so, dass sowieso immer das Haupt-Logo groß unter der Leiste zu sehen ist; egal ob FAU, oder nicht FAU. Deshalb braucht es das oben im Balken meiner Meinung nach so winzig klein nicht mehr. Symmetrie ist für mich persönlich auch nicht essenziell; die meisten Seiten haben ja nur ein Burger-Menü rechts.

Du meinst das Symbol als Lösung für FAU-Seite, nicht für Nicht-FAU-Seiten, oder? Denn bei denen hätten wir ja das Problem, dass wir das FAU-Logo als Schalter nicht anbieten würden. Ich hatte auch überlegt, was das für ein Symbol sein könnte. Letztendlich finde ich es aber nicht nutzerfreundlich, zwei abstrakte Menü-Symbole nebeneinander zu haben. Deshalb dachte ich: Alle essenziellen Bedienfunktionen ins Hauptmenü.

Ich kann auch heute Abend nochmal @jkphl um seine Meinung fragen.

**Comment by xwolfde** [comment]
Das Symbol dachte ich als Fallback für Nicht-FAU-Seiten. Bei den FAU.Seiten haben wir ja das FAU-Symbol im Meta, welches wir dann damit zweckentfremden.
Somit könnte dann der Top-Teil so aussehen:

![grafik](https://user-images.githubusercontent.com/1070669/144445812-1c35f5d6-2a1f-4312-ba6d-94b90d1461c0.png)


Und bei einer Einrichtung, die nicht der FAU angehört, fehlt ja oben links in der Meta das FAU-Logo, welches wir als OPener" nutzen. Also wird dann ein Fallback-Symbol verwendet. Z.B. das Organization-Symbol (https://www.svgrepo.com/svg/70462/organization) :
![grafik](https://user-images.githubusercontent.com/1070669/144446820-b716a0a5-4329-4c70-befa-a05701e699a0.png)

**Comment by krokodok** [comment]
Okay, aber was ist mit folgendem Fall:

> FAU-Logo als Link zur FAU-Website (optional, entfält bei der fau.de Seite). Es handelt sich um ein Link um ein SVG Icon.
> Organisatorische Breadcrumb (aktuell nur Fakultätssname) (optional, entfällt bei der fau.de Seite oder auf Fakultätsseiten)

Dort würde die Symmetrie dann ja wegfallen, oder?

Und ist das Styling mit dem Logo auf der weißen Fläche unter der Leiste dann nicht in Ordnung? Sollen wir es für kleine Auflösungen herausnehmen?

**Comment by xwolfde** [comment]
Da hast du recht. Bei der einen zentralen FAU-Website (ok, zwei, weil auch fau.eu), da könnte das FAU-Logo nicht links einmal als Klicksymbol und in der Mitte nochmal als Eigenlogo stehen.

Aber an der Stelle könnten wir un sLinks wieder der Fallback-Logos bedienen, oder?

(Erkennen, welcherart Typ der Website ist, tust du nebenbei immer anhand der Class im `<body>.`)

**Comment by krokodok** [comment]
Ja, das können wir so machen. Ich muss dann nur noch wissen, ob das große Logo unten raus soll. Auf der Vorschau-Seite ist das neue FAU-Logo aktuell ganz groß auf weiß unter der Meta-Leiste. Das müsste da ja raus (und custom logos aus), sonst hat man die immer doppelt.

**Comment by xwolfde** [comment]
Also ich denke da müsste eher das große Logo, also SVG + Schriftteil mit Friedrich-Alexander.. nach oben.
Denn gerade den Titel will man ja auch da darstellen.

**Comment by krokodok** [comment]
Dann wird aber die Leiste wesentlich höher werden müssen. Und alle Logos (auch benutzerdefinierte) auf hellblau anzeigen? Man weiß ja nie, welche Farben die haben. Deshalb fände ich auf weiß die sicherere Methode.

Was spricht dagegen, das winzige Logo oben herauszunehmen und es schön groß daunter auf weiß zu lassen?

**Comment by xwolfde** [comment]
uh, die hintergrundfarbe würde ich lieber lassen, weil: Wenn du runterscrollst wird der hintergrund ja auch weiß sein. in den obigen beispielen musst du dir den slider wegdenken. Wenn aber der normalen Hintergrund des Textes dann auch weiß ist, wird es keinen Unterschied mehr zur Meta geben.

Ich kann mir deinen Vorschlag nicht gerade gut vorstellen, kannst du es skizzieren?

**Comment by krokodok** [comment]
![image](https://user-images.githubusercontent.com/10128264/144454470-13e251fc-a2a4-4af6-8446-f12dafa30183.png)

So wie es auf der tindu testseite jetzt bereits umgesetzt ist, nur ohne das kleine Logo oben.

**Comment by xwolfde** [comment]
Dann haben wir aber keinen Platz gewonnen; Der Kopfteil nimmt dann immer noch einen großen Anteil der Darstellungsfläche ein. Und die ORGA-Breadcrumb stört dann auch und nimmt ebenfalls Platz weg

**Comment by krokodok** [comment]
Ah okay, ich wusste nicht, dass es auch ein Platzproblem gibt. Die Orga-Breadcrumb wäre ja aber trotzdem oben im Meta-Menü verborgen, wie von dir vorgeschlagen.

**Comment by xwolfde** [comment]
Ja, wir haben halt Beschwerden, dass der Kopfteil der Seite (der ja auch fixiert wird) zu viel Platz wegnimmt.
(Übrigens nicht nur bei Handy auch bei Desktop-Auflösung.)

Eine komplexere Lösung könnte zwar dahin gehen, den Kopfteil abhängig von der Scrollposition sukzessiv kleiner zu machen, aber ich denke das würde jetzt erstmal zu aufwendig werden.

**Comment by krokodok** [comment]
Wir haben die Meta-Navigation von Grund auf umgebaut, auf Grundlage der Diskussion aus diesem Issue. Wir haben dabei auch die verschiedenen Modi getestet: Website-Typ und custom Logo oder Default Logo. Sollte nochmal unter Produktivbedingungen angesehen werden bzw. von Personen, die mehr Überblick über die möglichen (Grenz-)Fälle haben, als wir.

**Comment by xwolfde** [comment]
Die Metealeiste ist viel höher geworden und das Logo links oben ist nicht mehr vertikal mittig?
![grafik](https://user-images.githubusercontent.com/1070669/145033492-78298599-7adc-4c32-9657-8d736948d9c2.png)
 

Bei einer AUflösung 768> x <1024 wird das FAU-Logo kleiner gestaucht und kaum noch lesbar:
![grafik](https://user-images.githubusercontent.com/1070669/145033849-cc840556-b646-46b3-bc1a-8bb1504948ae.png)

**Comment by xwolfde** [comment]
Der Abstand des Banners bei Template Startseite zu Logo/Menü oben erscheint etwas klein:
![grafik](https://user-images.githubusercontent.com/1070669/145034048-3d6561bc-2bf6-4f72-b914-8919b985749e.png)


Beim Template Startseite Fakultät ist der Slider hingegen nicht mehr richtig positioniert 

![grafik](https://user-images.githubusercontent.com/1070669/145034377-bc9cccc2-a2e3-4aca-8b9a-e8ad7f464839.png)

So war es vorher:
![grafik](https://user-images.githubusercontent.com/1070669/145034440-278d12b2-1d1f-44a2-91c5-b7823bdb1bc2.png)

**Comment by krokodok** [comment]
Abstände habe ich wieder korrigiert. Und die Meta-Navigation ist jetzt ab "Desktop" komplett vertikal mittig. Ich hatte die vorher aktiv auf Oberkante ausgerichtet. Aber nur das Logo links jetzt mittig auszurichten und die Suche und den Sprachschalter auf Oberkante sähe ja auch komisch aus. Paddings und Margins der hellblauen Leiste sind eigentlich gleich zu vorher geblieben!

Und kannst du mir sagen, in welchem Browser du das hast:

> Bei einer Auflösung 768> x <1024 wird das FAU-Logo kleiner gestaucht und kaum noch lesbar:

**Comment by xwolfde** [comment]
ich bin Firefoxer :=)

**Comment by krokodok** [comment]
Bei mir stimmt im neuesten Firefox alles. 🤔

**Comment by xwolfde** [comment]
ok, in der aktuellen Version sehe ich den Fehler mit dem gestauchten kleinen Logo auch nicht mehr. 

Der Slider ist allerdings immer noch nicht richtig positioniert.

**Comment by krokodok** [comment]
![image](https://user-images.githubusercontent.com/10128264/145065556-a44c189d-328d-4d0b-97b6-0cab80e3b55b.png)

Dast ist bei mir im Firefox auf der Fakultäts-Startseite. So soll es doch aussehen, oder?

**Comment by xwolfde** [comment]
jepp. das letzte Update hats gefixt.

ok, dann können wir dieses Issue auch schließen.
