### ISSUE TITLE
Metamenü: Grid-Darstellung ab 1400 prüfen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#891]
Das Metamenü (Hauptmenü) wurde "damals" auf eine Viewport von max. 1024 optimiert.
Dabei werden die Einträge in 3 Spalten dargestellt.

Bei dem neuen Viewport ab 1400 Pixel wäre es denkbar, auf 4 Spalten zu wechslen.
Dies wäre zu prüfen und ggf. umzusetzen.

Teil/Zusammenhang zu #867

**Comment by xwolfde** [comment]
Anmerkung:
Im Sass-Code ist auch noch die Definition des bisherigen Default-Menüs vorhanden (vgl #892 ). 
Nach den Rückfragen und dem Segen des CIO werden wir das alte Default-Menü deaktivieren.

Daher kann bei Prüfung des SASS-Codes für das Metamenü, welches sich ebenfalls in der `src/sass/structure/navigation/_mainmen.scss` befindet, der alte Code entfernt werden, damit nicht weiter verwirrt.


Ohne jetzt zu testen, denke ich, dass damit die Definitionen für diese Klassen raus können:
`.introtext, .introtext-full, .introthumb, figcaption, .mainnav-defaultview`

Muss aber nicht. Aber wenn der Code stört, werft ihn raus.

**Comment by krokodok** [comment]
Wir sind alle Templates der Test-Seite durchgegangen und haben alle möglichen kleineren Unsauberkeiten mit CSS ausgebessert. Die Randspalte fängt jetzt erst einen Breakpoint später an, weil vorher der Text zu schmal zum Lesen war.

**Comment by xwolfde** [comment]
ok, passt
