### ISSUE TITLE
Hauptmenü: Alte Option der Darstellung entfernen oder optional lassen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#892]
Abzustimmen ist, ob mit Version 2 die alte Form der Darstellung des Hauptmenüs noch als Option erhalten bleiben soll, oder diese komplett wegfallen soll.

Alte Darstellung:
![menu-rollout-fau-2018](https://user-images.githubusercontent.com/1070669/142372138-2bf5215d-095f-4e7a-b06b-b9cf2007a5f1.jpg)

Neue Darstellung, eingeführt 2019 (von @jkphl ), bislang als Option, ab V2. als Default:

![Hauptmenu-20211118](https://user-images.githubusercontent.com/1070669/142372183-c57c2a78-4482-4903-8bce-70bc1dc96c8e.jpg)

Die EInstellung wird im Customizer unter Erweitert->Hauptmenu vorgenommen
![menu-optionen-20200810](https://user-images.githubusercontent.com/1070669/142371449-b3f67ba7-4258-4780-91ad-0c9ac83640ee.jpg)

Meine Meinung: Weg damit um den Code aufzuräumen.

**Comment by xwolfde** [comment]
Live-Testcases:

# Altes Menu:
* https://www.phil.fau.de/
* https://www.awro.rw.fau.de/
* https://www.biochemie.med.fau.de/
* https://www.bodyodor.research.fau.eu/
* https://www.aibe.tf.fau.de/
* https://www.anatomie.med.fau.de/

# "Neues" Menu
* https://www.wordpress.rrze.fau.de/
* https://www.fau.de/


Die neue Form war bislang nur versteckt im Customizer zu finden und musste dort erst aktiviert werden.
Sie wurde auch nicht besonders gut kommuniziert, da die Auftraggeberin 2019 zunächst nur die FAU-Hauptseite damit ausstatten wollte.
Daher ist die Option momentan nur wenig verbreitet.

**Comment by lukasniebler** [comment]
Denke auch, dass das alte Menü weg kann. Das erste was man als Nutzer sonst sieht ist das Bild, dann das Zitat, dann erst die Menüpunkte.

Zudem nimmt das alte Menü viel Platz weg, v.a. wenn weder Bilder noch Zitat verwendet werden.

**Comment by AndiWebred** [comment]
Aus Sicht der Webredaktion kann das weg. Aber wir nutzen das "alte" Menü ja auch seit zwei Jahren nicht mehr. Von daher haben wir auch keine Umstellungsschwierigkeiten.

**Comment by xwolfde** [comment]
Nach Rückfrage beim CIO: Auch er hat nichts gegen das Entfernen.
