### ISSUE TITLE
Update Print-Layout

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#901]
Das Stylesheet für das Medium Print bedarf einer Runderneuerung:

- [x] Ausgabe-Layout mit dem neuen Office-Dokumentenformat (wird bereit gestellt) vergleichen und versuchen, hier eine Annäherung zu schaffen.
- [x] Darstellungsprobleme mit Links beheben
- [x] Prüfen, ob im Print Bereiche ausgegeben werden, die ausgeblendet sein sollten und diese ggf. unsichtbar machen
- [x] Prüfen, ob im Print Bereiche nicht ausgegeben werden, die aber sichtbar sein sollten und diese ggf. wieder sichtbar machen 
- [x] Prüfen und finden einer Lösung, wie die Ausgabe von Bildergalerien auf Print dargestellt werden sollte
- [x] Prüfen und finden einer Lösung, wie die Ausgabe von Bilder mit Sliderfunktionalitäten auf Print dargestellt werden sollte
- [x] Prüfen und finden einer Lösung, wie die Ausgabe von eingebetetten Videos auf Print dargestellt werden sollte
- [x] Prüfen und finden einer Lösung, wie die Ausgabe von Tabellen auf Print dargestellt werden sollte; Dabei  insbesondere auch breite Tabellen, die über den Bildschirmrand / Ausdrucksseite hinausgehen würden.
- [x] #1066

**Comment by xwolfde** [comment]
wie besprochen: Eigenes fau-theme-printer.scss, welches via HTML adressiert wird

**Comment by xwolfde** [comment]
Der Slider oben im Hero kann auf Print ignoriert, also auf display: none gesetzt werden. 
Dieser Slider kommt je nach Konfiguration der Website in einer der beiden Ids: "hero-slides" oder "ilifautpl-hero".

Zu beachten: Es gibt noch einen zwei andere Slider, die im Content-Bereich sind. Nämlich den Bildslider (in der Regel sind das Partnerlogos) von Websites und deren Verlinkung gemacht wird und Content-Slider. Bei diesen ist ein display: none ungünstig. Diese sollten daher auch auf Print angezeigt werden - dann aber natürlich statisch.
Bei den Bildslidern wäre eine gekachelte Ausgabe der Bilder denkbar.

ZU sehen unter:
![grafik](https://user-images.githubusercontent.com/1070669/153607134-1b45338d-fc9f-410b-aa6d-2865c417a2b6.png)
https://www.beta.wordpress.rrze.fau.de/ (unten)


Auf der Testinstanz oder in euren Testdaten könnt ihr das als Bildlink finden:
http://zentral.tindu.rrze.uni-erlangen.de/shortcodes/shortcode-imagelink/

**Comment by jkphl** [comment]
Wir haben nun noch ein paar Fixes gepushed, und hier Feedback zu den einzelnen Punkten:

1. wurde letzte Woche schon bearbeitet und hat sich ja inzwischen geklärt.
2. sollte gefixt sein
3. sollte gefixt sein; die Kopf- und Fußzeile wird **vom Browser eingedruckt** und ist nicht zu beeinflussen. Machen die Browser auch unterschiedlich, aber man kann sie bei Bedarf zumindest abschalten (im Druckdialog)
4. sollte gefixt sein.

**Comment by xwolfde** [comment]
Jupp. Alles gut. Für mich ist alles erfüllt. Damit ist dann auch der Milestone 2.1 fertig und kann in die Testphase geworfen werden.
