### ISSUE TITLE
Social Media Optionen erneuern

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#902]
Social Media Icons aus dem Widget unter dem Footer links rausnehmen und nur noch unten per Default
Damit auch Wegfall entsprechender Optionen.
![grafik](https://user-images.githubusercontent.com/1070669/143577537-22eb66f0-7be1-4e4b-b7d8-bbaea64c8972.png)

**Comment by xwolfde** [comment]
Optionen aus Customizer können ganz entfernt werden. Stattdessen wird im Footer stets das WIdget angezeigt. Wenn das WIdget halt leer ist, dann wird ja auch nichts angezeigt.
Die Social Media Icons sind schlicht ein Menu. Die Linkziele und davon abhängige SoMe-Icons werden anhand ihrer URL erkannt.

**Comment by xwolfde** [comment]
Verschieben wir mal auf 2.1, da nicht dringend.

**Comment by MManthey** [comment]
Einmal bitte bestätigen, ob ich das richtig verstanden habe:
Die Footer-Optionen im Customizer:
- 'Social Media' (Toggle) -> faellt weg, wird einfach immer dargestellt
- 'Widget aktivieren' (Multi select) -> faellt weg, wird einfach immer dargestellt (ist evtl. leer)
- 'Social Media Buttons in der ersten Widgetspalte anzeigen' (Toggle) -> faellt weg, wird nicht mehr ausgeben (der Nutzer gestaltet das Widget)

**Comment by xwolfde** [comment]
Ja. Wobei wenn das Widget leer ist, bitte dann auch kein leeren grauen Hintergrund oder so zeigen.

**Comment by MManthey** [comment]
Die Footer-Optionen im Customizer:

- 'Social Media' (Toggle) -> faellt weg, wird einfach immer dargestellt
- 'Widget aktivieren' (Multi select) -> faellt weg, wird einfach immer dargestellt (ist evtl. leer)
- 'Social Media Buttons in der ersten Widgetspalte anzeigen' (Toggle) -> faellt weg, wird nicht mehr ausgeben (der Nutzer gestaltet das Widget)

diese Sachen erledigt und 
- 'Titel' Option fuer das Social Media Menu im Widget entfernt (da nicht mehr verwendet)
