### ISSUE TITLE
Top-Termin auf Startseite: "Verborgenes Element hat fokussierbaren Inhalt"

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/FAU-Einrichtungen#919]
Siteimprove zeigt mir für das Bild vom Top-Termin auf der Startseite einen Accessibility-Fehler an: Verborgenes Element hat fokussierbaren Inhalt.
Siteimprove empfiehlt: "Entfernen Sie das Element aus der Fokusreihenfolge."

**Comment by xwolfde** [comment]
Sollte in der V2 gefixt sein
