### ISSUE TITLE
UnivIS-Plugin: Link ICS

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#926]
unschön
![grafik](https://user-images.githubusercontent.com/1070669/147140827-a7697209-088a-4d06-a482-7cd8a0fad855.png)

**Comment by AndiWebred** [comment]
Eine kleine Anmerkung dazu noch von mir: Das mag auch Siteimprove aus Barrierefreiheitsicht nicht, weil die Links denselben Linktext, aber unterschiedliche Ziele haben. Wenn ihr das angeht, habt ihr vielleicht auch eine Idee, wie man das lösen kann?

Gibt auch Seiten, auf denen mehrere Termine mit dem gleichen Datum und der gleichen Uhrzeit gezeigt werden.

**Comment by xwolfde** [comment]
Ja, da kam das auch her.  Ich denke hier sollte auch das title-Attribut noch angepasst werden, vergleichbar mit dem Issue #949

**Comment by xwolfde** [comment]
In V2
