### ISSUE TITLE
Blogroll - Additional whitespace between individual entries and sidebar on Desktop 1920px+ needed?

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#937]
This issue regards larger screens ( <24" - 32"+) with screen resolutions above 1920 x 1080 px.

Issue:
-------
The blogroll, which is currently visible on home pages with templates "Startseite Fakultät" and "Startseite" could need additional spacing between individual entries and between blogroll and sidebar.

Reasoning:
--------
As user I did not know where to look at first when I scrolled through the home page on a larger monitor (>24" with 1920+ res). For me personally It wasn't clear where to look at first once I'm on the Blogroll section.

How it could be fixed:
--------
There are two ways to fix that issue. A complete fix could be a combination of most issues or just rely on pure whitespace.

a) More whitespace between entries and sidebar
------
The first fix relies on the Law of Proximity, following gestalt principles. The spacing between blogroll and sidebar could be increased up to 2x while the space below each individual entry could be slightly enhanced. The result is a slightly less cluttered blogroll. In return it is easier to separate the sidebar's content from the main content of the home page.

b) Reduced font size - Comes with further issues of hierarchy between h1 - h6
------
Another fix could be, to reduce the font-size slightly along with option a). Currently headlines are huge on monitors >24". They could be slightly reduced to make it more pleasing to the eye. For a rule of thumb I'd recommend to make the font size 1,618 times larger (golden ratio) than the regular font size. With 18 px you'd end up with around 29.124 px (conversion to rem or em req.). Now the question remaining with this fix is how to conserve the hierarchy between h1-h6 headlines. Currently I don't have a solution for this issue, that's why a) might be the fix to go with.

Example with added whitespace:
------
<img width="2240" alt="Blogroll mit mehr Abstand ohne Oben" src="https://user-images.githubusercontent.com/58593037/148218316-f18295d8-8793-490d-9c54-fac38b660bf5.png">
Added whitespace without visible changes
<img width="2240" alt="Sichtbare Hilfslinien" src="https://user-images.githubusercontent.com/58593037/148218387-81ce8ff0-8e88-4c18-954f-b82ebb285e82.png">
Added whitespace with visible changes as green guidelines.

Grobe Übersetzung Deutsch
-------

Der Blogroll fehlt es aktuell etwas an Hierarchie, damit man als Endnutzer sofort erkennt, welche Inhalte zuerst betrachtet werden sollten. Damit man die Sidebar etwas besser abgrenzt und die Beiträge untereinander etwas mehr abgrenzt, sollte etwas mehr Abstand unter den einzelnen Einträgen und zwischen Blogroll und Sidebar entstehen.

Mein Vorschlag:
Mehr Abstand zwischen Blogroll und Sidebar. (Bis zu 2x). Und gleichzeitig etwas mehr Abstand zwischen den einzelnen Einträgen. Im Screenshot sieht man, wie das ganze dann mit etwas mehr Abstand aussehen könnte.

Alternativ wäre es auch eine Option die Schriftgröße der Überschriften auf großen Bildschirmgrößen (1920x1080px - 5k+) leicht zu reduzieren. Auf meinem größeren Bildschirm (sowohl 1920x1080, als auch 4k) erschlägt mich der Inhalt ansonsten schnell auf der Startseite unserer Beta-Seite.

Wie immer nur ein Vorschlag. Das alles betrifft auch nur große Bildschirme mit über 24".

**Comment by xwolfde** [comment]
Hm... mal schauen, der Abstand ist ja genormt in der Variable mit den gutter space von 30px von dem jeweils die Hälfte beim padding right /left der Bereiche gesetzt wird... Muss ich mir mal anschauen ob eine faktoriesierung da passt

**Comment by xwolfde** [comment]
Zu den Größen der Überschriften :
Aktuell sind die h1-6 basierend auf Fibonacci, beginnend an h6

H1 +21
H2 +13
H3 +8
H4 +5
H5 +3
H6 +2 Font-base 


Ggf. Wäre es aber in der Tat besser dies bei h5 :

H1 +13
H2 +8
H3 +5
H4 +3
H5 +2
H6 +1 Font-base

**Comment by lukasniebler** [comment]
Falls wirklich jemand die h6 verwendet, dann hat man ja trotzdem noch die visuelle Trennung durch die Schriftstärke und den Abstand.

Finde die Idee gut.

**Comment by xwolfde** [comment]
Dann mach ich es so.
Bei der Sidebar nehm ich nochmals jeweils eine Stufe runter.

**Comment by xwolfde** [comment]
- [ ] Überschriftgrößen geändert
- [ ] Abstand zur Sidebar >1400 vergrößert
