### ISSUE TITLE
Color gradient on mobile sidebar is reducing readability

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#939]
The grey gradient behind the sidebar's content on mobile devices should be changed to something more pleasing to the eyes. Maybe there shouldn't be a gradient at all.

<img width="710" alt="Bildschirmfoto 2022-01-05 um 14 38 35" src="https://user-images.githubusercontent.com/58593037/148226795-7a08ed0e-5e91-484e-8b04-98e63ea0a054.png">

**Comment by xwolfde** [comment]
Gibst du mir bitte die URL? 
Bei mir erscheint da in den Testcases gar kein Background mehr...

**Comment by lukasniebler** [comment]
https://www.beta.wordpress.rrze.fau.de

(Auf Safari iOS sieht man ihn auch noch. Weiß aber nicht ob das der aktuellste Stand des Themes ist auf der Beta

**Comment by xwolfde** [comment]
ah, jetzt, danke

**Comment by xwolfde** [comment]
im branch umgesetzt
