### ISSUE TITLE
Standardfarben in den Kalendericons

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/FAU-Einrichtungen#94]
Bei den Kalendericons ist derzeit die Standardfarbe blau und nicht die FAK-Farbe. Das war vorher anders ;-) Bitte wieder zurücksetzen. https://www.biologie.nat.fau.de/
Es ist dann so, wenn Startseite und nicht Startseite Fakultät gewählt wurde. Also liegt es dort im Design. => @xwolfde

**Comment by xwolfde** [comment]
Danke für die Meldung

**Comment by xwolfde** [comment]
Fehlermeldung ist falsch - das Theme ist richtig: Bei dem Terminen der Biologie wurde im Backend für die Termine die blaue Farbe gewählt => Bedienerfehler.

Siehe Screenshots
![farben-termine](https://cloud.githubusercontent.com/assets/1070669/17289707/31bd0d7a-57db-11e6-8f3f-cdddae310292.gif)
