### ISSUE TITLE
Mobile: Padding or spacing needed below image links

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#940]
On mobile end devices the padding below image links is missing.
<img width="710" alt="Bildschirmfoto 2022-01-05 um 14 42 13" src="https://user-images.githubusercontent.com/58593037/148227264-9e4c5306-f2cf-4235-b31c-0af43e91b8a2.png">

Der Abstand unter den Imagelinks fehlt auf mobile.

**Comment by xwolfde** [comment]
im nächsten update
