### ISSUE TITLE
Bildlinks funktionieren noch nicht wie erwartet

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#941]
Es werden mehr als der 5 eingestellten Bildlinks dargestellt und das ziehen funktioniert nicht korrekt am Desktop.

![2022-01-05_15-00-45 (1)](https://user-images.githubusercontent.com/58593037/148229976-5c6ddbb5-0733-4890-8e51-d74cbc3b5a7a.gif)

**Comment by xwolfde** [comment]
Ich glaub das ist eine Funktion von der Slider-JS, die ich selbst nicht ganz durchblicke. 
Könnte ein "Feature" sein...

**Comment by xwolfde** [comment]
Ich würde das erstmal nach hinten V2.1 verschieben.

**Comment by lukasniebler** [comment]
Die Pfeile in den neuen Bildlinks passen noch nicht. Und die Darstellung ist etwas ungünstig (sehr kleine Logos) - zumindest im verwendeten Beispiel mit FAU Logos.

Beispiel-Seite: https://www.urlaubaufsagrotan.test.rrze.fau.de

<img width="1456" alt="Bildschirmfoto 2022-01-24 um 08 56 28" src="https://user-images.githubusercontent.com/58593037/150743447-5eebe13a-445b-4377-80aa-a3b030e2aef2.png">

**Comment by xwolfde** [comment]
hol dir das update, ist gefixt. da hatte ich am Wocheende ein Fehler verschlimmbessert

**Comment by lukasniebler** [comment]
Die Pfeile passen jetzt. Für V. 2.1 wäre es vielleicht noch schick, falls weniger Logos und dafür etwas größer erscheinen.
<img width="1610" alt="Bildschirmfoto 2022-01-24 um 13 02 28" src="https://user-images.githubusercontent.com/58593037/150779702-cee33e00-8f75-4d8c-9293-5c6dcf89830a.png">

Wenn man nur 5 Logos hat ist die Darstellung mit 8 Logos sonst sehr klein / schlecht lesbar (Vllt. auch ungünstiges Beispiel, dadurch dass Das FAU logo so breit ist... )
