### ISSUE TITLE
Text selection offset could need minor fixes (Safari)

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#944]
Browser with this issue: Safari 15.1

# Issue (Eng.)
If you select text within a paragraph the marked text isn't covered completely. This might lead to reduced readability of highlighted text passages.

# Problem (Dt.)
Markierter Text in der 2. Zeile und darunter, also innerhalb eines Paragraphen ist nicht komplett durch die Auswahl / Highlighterfarbe markiert.

## Example
www.beta.rrze.fau.de
www.zentral.tindu.rrze.uni-erlangen.de

<img width="992" alt="Bildschirmfoto 2022-01-07 um 11 19 38" src="https://user-images.githubusercontent.com/58593037/148530122-3d1daac6-37ec-4d53-b4e8-5115e19fcbb3.png">
<img width="992" alt="Bildschirmfoto 2022-01-07 um 11 21 45" src="https://user-images.githubusercontent.com/58593037/148530130-d046339d-6fb6-4458-9102-d2d6c671780b.png">

**Comment by lukasniebler** [comment]
( Scheint Safari zu betreffen )

**Comment by xwolfde** [comment]
DuckDuckGo und Firefox auf Android haben diesen Bug nicht. 

(dort hab ich aber ein Touchscreen Problem beim selektieren?)

**Comment by lukasniebler** [comment]
Auf Safari Mobile hat man auch ein Touchscreen-Problem beim selektieren.

Und zwar beim ersten Seitenaufruf / Neu laden der Seite scrollt die Seite automatisch nach oben.

**Comment by xwolfde** [comment]
Genau das hab ich auch erlebt. 
Ich hab keinen Plan was das verursachen könnte und woran das liegt...

**Comment by lukasniebler** [comment]
Also. Ich hab zwar noch nix gefunden, aber das Problem besteht auch wenn man JavaScript deaktiviert.

Außerdem interessant:
Auf dem unteren drittel des Browserfensters funktioniert das selektieren ohne Probleme.
Je näher man der Mitte / Oben kommt, desto schneller springt die Seite nach oben.

**Comment by xwolfde** [comment]
Ich hab den Verdacht, dass hier eine alte Funktion zum Scrolling bei Targets im Dokument rein greift. Das scrolling wird in der neuen Version mit der neuen CSS Eigenschaft scrolling offset erledigt.

@lukasniebler hast du Lust, dir mal das Javascript anzuschauen und da mal zu suchen?

**Comment by xwolfde** [comment]
Oh, dann hat sich das mit dem Javascript erledigt als Ursache...

**Comment by lukasniebler** [comment]
Ja im Entwicklermodus von Safari kann man JS deaktivieren. Wenn man im Responsiven Modus sich die Seite anschaut, dann scrollt es trotzdem. Wie gesagt aber abhängig davon, wo man auf der Seite mit dem Cursor markiert.

**Comment by lukasniebler** [comment]
Wenn ich
html {
    scroll-padding-top:400px
} aus dem Stylesheet im Browser auskommentiere, dann scrollt es bei mir nicht mehr automatisch.

**Comment by lukasniebler** [comment]
Denke da müsste man einfach einen anderen/niedrigeren Wert für mobile setzen, damit das besser passt für scroll-padding-top.

**Comment by xwolfde** [comment]
Scroll-Padding-Fix im Branch. Safari hingegen hat erstmal Pech gehabt/muss warten: Safari-Problem.
