### ISSUE TITLE
Aufgeklappte Accordions

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Einrichtungen#95]
Nachdem üblicherweise erst im Einrichtungstheme Änderungen vorgenommen werden, schreibe ich den Issue hier. Die Phil schrieb heute, weil dort aufgefallen war, dass neuerdings immer das erste Fach des Accordions aufgeklappt ist. Das möchten sie so nicht haben und möchten das nun gern abstellen. Meines Wissens nach kann man das in den Einstellungen nicht machen, deshalb gebe ich die Bitte auf diesem Weg weiter in die Entwicklung.

**Comment by csw-** [comment]
Auch wir haben hierzu entsprechende Rückfragen erhalten. Es wäre vielleicht wirklich nicht schlecht dies optional zu machen, z.B. durch einen Parameter.
Ich sehe in dem Default-geöffneten Akkordeon auch einen kleinen Widerspruch mit der Funktion des Akkordeons - nämlich Inhalt auszublenden um die Seite insgesamt übersichtlicher zu gestalten.

**Comment by xwolfde** [comment]
Das wurde gemacht, weil das Feature als solches noch auf der ToDo von der FAU kam und bislang nicht richtig umgesetzt war. 

Zu Accordions gibt es auch gewisse Empfehlungen, die zu bneachten sind. vgl.
https://blog.seibert-media.net/blog/2010/03/31/wann-sind-akkordeon-effekte-auf-websites-sinnvoll/
http://baymard.com/blog/accordion-and-tab-design

Wie auch immer: Ich (oder jemand anders der schneller ist) werde bei der nächsten Version einbauen, dass das Aufklappen nur gilt für Accordions, die ein Attribut   openonload="true"  bekommen.

Schade, daß die Rückmeldungen erst nach der Testphase kamen.

**Comment by wrkb** [comment]
:+1: hier, wir möchten auch ein zugeklapptes Akkordeon (sonst hat es ja keinen Übersichtscharakter mehr). Das mit dem Zusatzparameter ist eine gute Lösung.

Warum das ein Todo von uns sein sollte, weiß ich nicht, wir wollten das nie so haben :)

**Comment by csw-** [comment]
@xwolfde Danke für die weiteren Informationen zum Thema

**Comment by xwolfde** [comment]
@wrkb Hm, dann hab ich das falsch in Erinnerung gehabt, nehme das zurück und behaupte das Gegenteil .... :/

**Comment by xwolfde** [comment]
Nach gestrigen gespräch sind wir noch am diskutieren über einen besser merkbaren Parameternamen.
Was meint ihr, was besser ist?

   open="onload"
   openonload="true"
   load="open"
   offenbeimstart="true"
  ool="true"
...
?

**Comment by csw-** [comment]
Da es sich ja nur um einen Flag für eine einzige Funktion handelt, würde ich eher zu **openonload="true"** tendieren. Von Kürzeln wie **ool** würde ich eher absehen, sprechende Variablennamen.. wissenschon..

**Comment by AstridSemm** [comment]
Es ging um die Kürze - "openonload" ist halt doch schon recht lang. 
Wir können auch "owl" nehmen. Hat zwar dann mit dem Attribut nichts mehr zu tun, aber Eulen kann ich mir immer merken. ;o)

**Comment by wrkb** [comment]
load=''open''
Leicht zu merken (wir haben schon so viele Codes) und auch für Nicht-Entwickler verständlich.

**Comment by csw-** [comment]
Wird die Funktion denn so oft verwendet werden? So spontan halte ich die Kürze an dieser Stelle für garnicht mal so wichtig...

**Comment by csw-** [comment]
Ansonsten kann man ja vllt auch mal schauen wie die Flags bei anderen Plugins gehandhabt werden, damit man vllt eine Einheitlichkeit erreicht. z.B. bei Personen wurden die Flags ja eingestellt (glaube ich) und dafür wird show/hide verwendet.

**Comment by AstridSemm** [comment]
Rückmeldung aus dem Dept. Pharmazie (soeben telefonisch erhalten): Bitte per Default alles zugeklappt lassen, so dass der Besucher entscheiden kann, was er sich ansehen möchte.

**Comment by xwolfde** [comment]
Verflixt.  Aber die begründung aus Pharmazie ist ja etwas ... Wenn der Besucher selbst entscheiden soll, dann könnte das auch andersrum sein: Der Besucher kann entscheiden was er zuklappen will :P 


Aber ok ok... wir hatten es per Default zu, also machen wir es wieder so.

**Comment by xwolfde** [comment]
Ok, während der Entwicklung stellt sich heraus, dass es Sinn machtm, hier eine Funktionalität zu ergänzen:
"stayopen" (oder so).

D.h. wenn eine Accordion per Standard offen ist, aber dann ein anderes geöffnet wird, soll es weiterhin offen bleiben.

**Comment by AstridSemm** [comment]
Das steht generell dem gestalterischen Sinn eines Accordions entgegen. Dann könnte man den Inhalt nämlich als Textabsatz bringen - ein Accordion ist nur vonnöten, wenn man möchte, dass der Inhalt temporär verborgen werden kann.

**Comment by wrkb** [comment]
Ich glaube, Wolfgang meint offenbleiben nach Klick, oder? Fände ich auch nicht schlecht, insbesondere, wenn Inhalte mehrerer Schubladen sich ergänzen (kommt doch häufig vor). Standard sollte zugeklappt sein. Dass nur die erste Schublade offen ist, ist m.E. ein Zusatzfall - der aber auch nur Platz spart, wenn es viele Schubladen gibt.

**Comment by xwolfde** [comment]
ich habs mal hier simuliert:
http://test8.tindu.rrze.uni-erlangen.de/tests/shortcodes/accordion-und-personen/

Die zweite Lasche "load=open" ist beim Start offen. Genauso ist die 3 Lasche mit load="stayopen" offen.
Wenn ich nun nach dem Laden eine beliebige Lasche  ausser eben die 3. lasche schliesse, bleibt die 3. Lasche offen. Nur wenn ich die 3. Lasche explizit schliesse, wird sie auch geschlossen.

**Comment by AstridSemm** [comment]
Ich kann mir da echt keinen Usecase vorstellen - aber vielleicht bin ich ja auch nur phantasielos...

**Comment by xwolfde** [comment]
wir verraten die funktion einfach erstmal niemand. mal sehen ob jemand auf dieselbe idee kommt wie ich. dann haben wir es.

**Comment by AstridSemm** [comment]
Ok, damit kann ich leben. :o)

**Comment by wrkb** [comment]
Mir fällt auch kein Anwendungsfall ein, aber das muss nichts heißen. Wichtig wäre eher: Kann man stayopen auch einsetzen, wenn die Schublade nicht per default offen war? Dass man also ein komplett manuell zu öffnendes/schließendes Akkordeon erhält?

**Comment by xwolfde** [comment]
@wrkb Öh? Verstehe ich nicht. Das wäre doch der Normalfall, den man gar nicht deklarieren müsste...?

**Comment by AstridSemm** [comment]
Also, man baue ein, was man für sinnvoll hält. Nichtsdestoweniger halte ich beides (stayopen bei onload und stayopen bei manuellem Aufklappen) für Userverwirrung. Das Accordion hat eine Aufgabe, das sollte man nicht vergessen. Schaut euch mal die Irritationen an, die es gab, als das erste Fach onload einfach mal so offen war und sich die Jungs nicht informiert hatten (das wird schon auch Benutzer irritiert haben). Ich täte das nicht, habe aber nichts dagegen, wenn es da ist, wenn jemand meint, so etwas zu brauchen.

**Comment by wrkb** [comment]
Ich weiß nicht, ob in deinem Beispiel zwei Attribute nötig waren - on load open und stayopen. Oder ob stayopen automatisch auch on load open enthält (das wäre nicht wünschenswert in meinen Augen).

**Comment by wrkb** [comment]
@AstridSemm Naja, es ist eine Neuerung, man müsste den tatsächlich eingesetzten Fall kommunizieren (ich wusste damals von nüscht, daher unsere Rückfrage). Es gibt im Web ja auch Akkordeons, die nicht automatisch schließen. Ob man gleich alle Möglichkeiten breit kommuniziert oder auf den Bedarf wartet... keine Ahnung. Was nicht bekannt ist, wirkt aber wie kaputt - das stimmt. Der User, der die Vorgänge hier nicht kennt, muss es wohl immer lernen...

**Comment by xwolfde** [comment]
Hm... 
ja, ich würde es jetzt erstmal so lassen wie auf test8 gemacht und dann abwarten ob noch verbesserungswünsche kommen, die wirklich begründet sind. in der Doku würde ich jetzt erstmal nur 
load="open"  
beschreiben für Accordions (es können mehr als eines sein!) die beim Laden der Seite offen sein sollen.
Per default isnd dann alle zu.

Noch eine kleine Notiz in Ergänzung:
Das title=""-feld darf keine HTML-Anweisungen (mehr) enthalten. Da war ein Bug enthalten, der es erlaubte, darin Nonsense (HTML) zu schreiben und das ganze bei unbedarfter Nutzung kaputt machen ließ. Das ist mir zu heikel; Daher hab ich da auch alle HTML-Anweisungen  escpaed, wie man es eigentlich sowieso machen muss.

**Comment by wrkb** [comment]
Okay, dann probier ich später mal aus, was mit stayopen geht.

**Comment by xwolfde** [comment]
live

**Comment by endv02** [comment]
Bitte in die Doku noch mit aufnehmen, da steht es nicht drin (zumindest mit load="open")

**Comment by AstridSemm** [comment]
Jajajaja, kommt. Ist schon fast fertig! ;o)

**Comment by xwolfde** [comment]
Wieso ist dieser Issue noch offen?

**Comment by AstridSemm** [comment]
Weil ich bisher noch nicht dazugekommen bin, das in die Doku aufzunehmen, vermute ich. Ich prüfe das mal.

**Comment by AstridSemm** [comment]
Ist drin. Ich mache das dann mal zu.
