### ISSUE TITLE
Abstand Seitenuntertitel auf mobile

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#953]
Mobile Safari:

# Issue
Seitenuntertitel liegt direkt am Seitenrand an, da div für den Seitencontent padding oder margin enthält. S. Screenshot.

![image](https://user-images.githubusercontent.com/58593037/148946740-6e20fcfb-e773-4b61-b60d-964d441909e7.png)
https://www.beta.wordpress.rrze.fau.de/texte/ueberschriften/

**Comment by lukasniebler** [comment]
Auf Beitragsseiten könnte der Seitenuntertitel (mobile) auch etwas mehr Abstand zum Artikelbild brauchen.

![image](https://user-images.githubusercontent.com/58593037/148950780-b27bde55-4f4e-4dee-8ada-0c0ac27146d9.png)

https://www.beta.wordpress.rrze.fau.de/2017/10/02/release-kandidat-1-8/
s. mittlerer Screen

**Comment by xwolfde** [comment]
im nächsten update
