### ISSUE TITLE
Abstand Artikelbild zum Rand auf Blog-Seiten (mobile)

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#954]
Betrifft die Darstellung:

Getestet auf Safari mobile

Auf mobile ist zwischen Beitragsbild und Seitenrand ein minimaler Rand sichtbar, der auf den Kategorie-Seiten / Blogroll nicht sichtbar ist. Auf Kategorie-Seiten verläuft das Bild dagegen von Rand zu Rand.

![image](https://user-images.githubusercontent.com/58593037/148947747-67d1dfb1-1c64-4996-a886-83a207a7165b.png)
https://www.beta.wordpress.rrze.fau.de/2020/04/29/update-fau-person-3-0/

Bsp: https://www.beta.wordpress.rrze.fau.de/2020/04/29/update-fau-person-3-0/

**Comment by xwolfde** [comment]
fixed im nächsten Update
