### ISSUE TITLE
Kategorieübersicht (mobile) - Das zweite Chevron ist bei Unterkategorien verschoben (Sidebar)

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#955]
Safari (mobile)
Unterkategorien in der Sidebar > Kategorien erhalten anscheinend ein falsch positioniertes Chevron.
Bzw. das Chevron verschiebt sich nach unten?
＞ s. Screenshot
![image](https://user-images.githubusercontent.com/58593037/148951846-fddba6dc-8621-4ca6-9bb1-bd36f59e9b6c.png)

gefunden auf beta.wordpress.rrze.fau.de

**Comment by lukasniebler** [comment]
Bsp.: https://www.beta.wordpress.rrze.fau.de/2020/01/09/beta-version-1-12-8/

Tritt auch auf Firefox mobile auf.

**Comment by xwolfde** [comment]
Ja, aber das ist grundsätzlich unten rechts und überlagert als toplink alles darunterliegende

**Comment by lukasniebler** [comment]
Meinen wir das gleiche Chevron? Meinte das Aufzählungszeichen. Aber anklickbar bleiben die Links trotzdem

<img width="363" alt="Bildschirmfoto 2022-01-11 um 14 40 49" src="https://user-images.githubusercontent.com/58593037/148953237-1b9c2110-7ff8-45fe-a9ba-d8ad0450508f.png">

**Comment by xwolfde** [comment]
aaah

**Comment by xwolfde** [comment]
fixed im nächsten update
