### ISSUE TITLE
Bildlinks in Portalmenüs - Zwecks Dokumentation

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#956]
Beim durchschauen unserer alten Dokumentation bin ich heute auf ein Feature gestoßen, das mir selbst nicht ganz klar war.
So kann man bei seinem Menü-Editor über "Ansicht anpassen" eine ganze Bandbreite an anderen Post-Types theoretisch in einem Portalmenü/Menü einbinden.

Jetzt wurde auf unseren alten Dokumentation groß angepriesen, dass die Portalindex-Seite extra für Bildlink-Portalmenüs und externe Verlinkungen geschaffen wurde.
https://www.wordpress.rrze.fau.de/themes/fau-themes/templates/die-portalindexseite/

Allerdings funktioniert ein Portalmenüs mit Bildlinks aktuell nicht richtig, wenn man wahllose Logogrößen verwendet.
<img width="2223" alt="Bildschirmfoto 2022-01-12 um 08 58 25" src="https://user-images.githubusercontent.com/58593037/149087804-183ce62d-f755-40bb-98d5-ce981b563d43.png">

# Zwei denkbare Lösungen:

1. Ich entferne dieses "Feature" aus der Dokumentation
2. Ich weise in der Dokumentation darauf hin, dass die Bilder für Portalmenüs im Verhältnis 3:2 eingepflegt werden müssen, falls die Funktion genutzt wird.

Bsp.: Ein Portalmenü mit Kontakteinträgen aus FAU Person:
<img width="2223" alt="Bildschirmfoto 2022-01-12 um 09 03 06" src="https://user-images.githubusercontent.com/58593037/149088111-686f5211-4c82-4b2a-816a-8aa13909c1f9.png">

**Comment by xwolfde** [comment]
Die Leute müssen wissen was wie hochladen. Wegen den Gruppenbilder (das Problem hatten wie bei den Artikel-Thumbs ja auch), können wir kein obect-fit: cover machen. contain bricht aber die Dimension und sorgt für Ränder.

Alternative Lösung für die Leute, die Bilder nicht anpassen wollen und trotzdem object-fit: cover wollen wäre die Nutzung der Bildgalerie mit LInks.

**Comment by xwolfde** [comment]
(Anmerkung: Wegen Bildgalerie gibt es ein Update, bitte nicht den Stand der jetzigen beta nehmen. Oder auf zentral.tindu schauen)

**Comment by lukasniebler** [comment]
In der Schnellstartanleitung dokumentiert
