### ISSUE TITLE
Fehlerseiten und Suchseiten - Menüeinträge auf Desktop doppelt unterstrichen

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#957]
Auf Fehlerseiten:
Getestet auf Safari - Desktop
Die einzelnen Einträge sind doppelt unterstrichen. Einmal mit einer kräftigen blauen Linie. Einmal mit einer deutlich längeren, dünnen Trennlinie.

Bsp.:
https://www.beta.wordpress.rrze.fau.de/404

<img width="153" alt="Bildschirmfoto 2022-01-12 um 10 07 28" src="https://user-images.githubusercontent.com/58593037/149097564-c8423ab3-9411-4f0c-b30c-fb9d30ae5bce.png">

![2022-01-12_09-58-25 (1)](https://user-images.githubusercontent.com/58593037/149096335-f937535e-54bb-4943-877e-91e9c308dbad.gif)

**Comment by xwolfde** [comment]
Zusammenhang mit #962 .

Hier sollte eigentlich dann auch das Contentmenü aufgerufen werden.

**Comment by xwolfde** [comment]
Die 4 Menüs helper 1..4 werden ersetzt durch ein einziges Menü, welches dann in der Portalmenudarstellung gezeigt wird.
Optionen entweder Default oder über Customizer.

**Comment by xwolfde** [comment]
Umgesetzt. Die Menüposition wurde entsprechend angepasst.

![grafik](https://user-images.githubusercontent.com/1070669/150309498-7f123aa9-1e09-4937-bad4-6351c597c38f.png)

Es wird derzeit jedoch nur die Default-Ansicht des Portalmenus verwendet. Diese ist derzeit nicht änderbar. (also kein skew oder Typ-wechsel)
