### ISSUE TITLE
Fehlender Slider auf kleinen Geräten - Verursacht durch einen zu langen Seitentitel

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#958]
Auf kleinen Endgeräten. (z.B. iPhone SE - 4 Zoll Diag.) wird der Slider nicht mehr angezeigt, wenn der Seitentitel über die Navigationsleiste herausragt.
<img width="365" alt="Bildschirmfoto 2022-01-12 um 11 05 08" src="https://user-images.githubusercontent.com/58593037/149119903-3ad36341-7bd8-48c1-a73f-9b600000c788.png">

An sich ok. Allerdings vielleicht problematisch, da der Text auf jeder Unterseite / Inhaltsseite / Beitragsseite / Menüführung immer in den Content übergeht.

Mögliche Lösungen, die aber ggf. visuell unschön sind:
- Den mobilen Header doch vergrößern / anpassen auf den Text, auch wenn es das Design der Seite etwas runter zieht?
(- Option 2 - Im Customizer / Doku nochmals auf ein maximales Limit für die Titel hinweisen? Evtl. aber nur für neue Seiten hilfreich)
- Overflow aus? - Auch nicht ideal... 
- Zwickmühle

<img width="365" alt="Bildschirmfoto 2022-01-12 um 11 07 58" src="https://user-images.githubusercontent.com/58593037/149120235-fa1929bc-0a0a-4b22-851a-dbd5850c8097.png">
<img width="365" alt="Bildschirmfoto 2022-01-12 um 11 08 13" src="https://user-images.githubusercontent.com/58593037/149120244-01e014d1-d2c6-4133-acc9-1c2090ec1427.png">

**Comment by xwolfde** [comment]
Bei mir ist alles bei 414 px (IPhone 11 Simulation) richtig:
![grafik](https://user-images.githubusercontent.com/1070669/149122109-297c498f-9087-4dcf-8eea-f3f2bd2b67ba.png)

**Comment by xwolfde** [comment]
Auch mit Slider auf der Startsetie
![grafik](https://user-images.githubusercontent.com/1070669/149122467-f935ae0f-318d-4228-8562-3e424b02daef.png)

**Comment by lukasniebler** [comment]
iPhone SE wäre wohl (320 x 568 px) laut Safari responsive Mode

**Comment by xwolfde** [comment]
Mist... so eine kleine Auflösung ist echt fitzelig. Ich hab mal geschaut. Leider können wir das nicht wirklich vernachlässigen:
![grafik](https://user-images.githubusercontent.com/1070669/149123143-2c33acb0-aeb2-48b2-8fa0-49acad67f555.png)

**Comment by lukasniebler** [comment]
Ja. Habe auch erst nicht gedacht, dass die Auflösung so verbreitet ist. Allerdings gehört die Gruppe der first million users u.a. zu den Nutzern, die oft auf sehr langsamen, kleinen Geräten surft. 

Also v.a. auch für Studenten wichtig, die ohne großes Budget an die FAU zum studieren kommen und noch ein älteres Smartphone benutzen oder sich im Ausland versuchen über die FAU zu informieren.

**Comment by xwolfde** [comment]
Als ersten Workaround für die V2 werde ich bei Auflösungen < 360px die Base font-size  90% reduzieren.
Dann passt es.

**Comment by xwolfde** [comment]
ich schliesse erstmal, weil der workaround erstmal das problem lösen sollte
