### ISSUE TITLE
Auf Accordionfächer verlinken

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Einrichtungen#96]
Im Dokument https://www.wordpress.rrze.fau.de/plugins/cms-workflow/ möche ich vom Accordionfach "Autoren" auf das Accordionfach "Versionierung verlinken (mit https://www.wordpress.rrze.fau.de/plugins/cms-workflow/#collapse_7). Da tut sich aber nichts. Geht das nur aus Accordions heraus nicht oder ist das allgemein so? Kann man das relativ schnell und unbürokratisch ändern?

**Comment by AstridSemm** [comment]
Also, ich habe dann mal ein wenig weitergetestet:
Der Link auf ein Accordionfach funktioniert innerhalb derselben Seite nicht.
Von einer anderen Seite aus funktioniert er, dummerweise ist dann auch das erste Fach geöffnet, weil das ja per Default auf ist. Irgendwie müssen wir da nochmal dran.

**Comment by xwolfde** [comment]
Mach ;)

**Comment by AstridSemm** [comment]
Jaja, die Initiativstrafe. Ich wäre um unserer Kunden willen ganz froh, wenn sich das noch dieses Jahr realisieren lassen würde. Von daher werde ich wohl ausfallen.

**Comment by steffigebel** [comment]
@AstridSemm: @xwolfde hat doch heute zum Thema "erstes Fach per default geöffnet" ausführlichst geschrieben. Das Verlinken müsste tun. Ich glaube aber, das ist ein anderer Hash. Steht auch irgendwo, wie das geht. Thema für Doku?

**Comment by AstridSemm** [comment]
Das Verlinken tut - von außen (also wenn du auf einer anderen Seite einen Link setzt). Ich versuche mal, ob da mit Sprungmarken was geht - sonst bin ich doch mit meinem Latein am Ende.

**Comment by AstridSemm** [comment]
Kann mir hier irgendjemand sagen, wie ich auf die ID eines Accordionfachs innerhalb der Seite verlinken kann? So als Sprungmarke. Eine ID hat das Fach ja, von daher müßte es gehen. Blöd nur, dass WordPress den URL ergänzt, den es für sinnvoll hält, wenn (egal, ob im Texteditor oder im WYSIWYG) man nur die ID (zb. #collapse_11) eingibt. Wie kann man das Ergänzen des restlichen URL verhindern? Hmmm.....

**Comment by steffigebel** [comment]
Das geht auf jeden Fall. Ich erinnere mich, dass Wolfgang das auch bereits erwähnt/erklärt hat, als er die Funktioanalität einbaute. Ich schau mal nach, ob ichs finde.

--
Steffi Gebel
Webmanagement
Regionales RechenZentrum Erlangen (RRZE)
Friedrich-Alexander-Universität Erlangen-Nürnberg
Martensstrasse 1, 91058 Erlangen, Germany
Tel. +49 9131 85-27807
stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de>
www.rrze.fau.de

Von: Astrid <notifications@github.com>
Antworten an: RRZE-Webteam/FAU-Einrichtungen <reply@reply.github.com>
Datum: Dienstag, 26. Juli 2016 um 09:45
An: RRZE-Webteam/FAU-Einrichtungen <FAU-Einrichtungen@noreply.github.com>
Cc: "Gebel, Stefanie" <stefanie.gebel@fau.de>, Comment <comment@noreply.github.com>
Betreff: Re: [RRZE-Webteam/FAU-Einrichtungen] Auf Accordionfächer verlinken (#96)


Kann mir hier irgendjemand sagen, wie ich auf die ID eines Accordionfachs innerhalb der Seite verlinken kann? So als Sprungmarke. Eine ID hat das Fach ja, von daher müßte es gehen. Blöd nur, dass WordPress den URL ergänzt, den es für sinnvoll hält, wenn (egal, ob im Texteditor oder im WYSIWYG) man nur die ID (zb. #collapse_11) eingibt. Wie kann man das Ergänzen des restlichen URL verhindern? Hmmm.....

**Comment by AstridSemm** [comment]
Es geht in der Tat. Ich dokumentiere hier mal, was Steffi herausgefunden hat (DANKE!):
Im Texteditor verlinken mit &lt;a href="<a href="seite-auf-der-das-accordion-sich-befindet/#collapse_7"&gt;Linktext&lt;/a&gt; 
Das muss man im Texteditor machen, über WISYWIG funktioniert es nicht. Aber so etwas machen ja sowieso nur Profis! ;oD
