### ISSUE TITLE
Portalmenü finetuning

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#962]
Ggf. die Border bei den Sublinks raus?

**Comment by lukasniebler** [comment]
Falls du noch Inspiration brauchst. Ich hatte letztens ein wenig ausprobiert. Vielleicht hilft es dir ja weiter bei den Portalmenüs:

![Portalmenü-Insp](https://user-images.githubusercontent.com/58593037/149331145-cebcfb5d-c053-4a15-93e2-9910868b2de2.png)

https://xd.adobe.com/view/f1851707-89f0-41a4-ba0f-4c69522b45fd-a4d6/

**Comment by xwolfde** [comment]
Wegen #927 und #961 brauchen wir eine neue Option mit zusätzlichem CSS:

- [ ] In den Shortcode-Optionen kommt eine Option hinzu bzgl. der Dimension des Bildes: Default ist ja 3x2. Es soll aber auch eine Option gegeben werden, dass das Bild 3x4 sein kann. Dann können wir es so darstellen wie bei den alten ILI-Bildlinks, die eben 3x4 sind.
![grafik](https://user-images.githubusercontent.com/1070669/149654457-b409303d-1eaa-43cc-9836-db158ea3be1a.png)
Dies wird gesteuer über HTML-Klassen:

* Default (jetzt): `<div class="contentmenu" role="navigation" aria-label="Inhaltsmenu"> ...`
* Bilder in 3:4:  `<div class="contentmenu image3-4" role="navigation" aria-label="Inhaltsmenu">`
* Optional auch 2:3 : `<div class="contentmenu image2-3" role="navigation" aria-label="Inhaltsmenu">...`
* Optional auch 4:3 : `<div class="contentmenu image4-3" role="navigation" aria-label="Inhaltsmenu">...`

- [ ] HTML-technisch sollten wir keine neuen Bildsizes machen, sondern stattdessen dafür das große Bildmaß nehmen + SRC-Sizes- Die Darstellung wird dann via CSS angepasst.
- [ ] Die Portalseiten Portalindex, Portalseite, Satrtseite, Startseite Fakultät erhalten eine Option, dass man ein Portalmenü (mit jewieligen Optionangabe)  auch oben einschalten kann. Dies wird dann vor dem content-row des Contentbereiches gemacht, so dass es auch "vor" der Sidebar ist. Die Möglichkeit, da oben einfach ein Widget zu setzen, würde ich einstweilig verwerfen, weil wir dann wieder ein WIdget unter Widgets mehr haben, was die User verwirrt und wir haben das problem, dass Widgets ja überall auf allen Portalseiten gleich wären. Wir bräuchen aber die Option verschiedene Portalseiten mit verschiedenen Menüs oben auszustatten.

**Comment by xwolfde** [comment]
Ich sehe gerade das wir dei Angabe der Dimension gar nict mehr brauchen, weil wir die über den Parameter type bereits haben!

**Comment by xwolfde** [comment]
@cassandre Die Portalseiten (Portalseite, Portalindex, Startseite, Startseite Sub) haben nun alle die Option ein Portalmenü auch oben einzuschalten.
Ausserdem haben alle Portalseiten -unten wie oben-nun zwei Optionen dazu bekommen für "skewed" = true/false und für den Typ, der dann das gewählte Bild auswählt. Bei Type=3 & Skewed=true soll dann das aussehen wie bei fau.de oben erscheinen.

Kannst du noch das CSS entsprechend setzen, dass die Darstellung dann passt?
Wenn das Portalmeu oben ist, dann ist es in einer .content-row die noch vor der content-row mit den eigentlichen Inhalt ist.

**Comment by xwolfde** [comment]
Kann zu, oder?
