### ISSUE TITLE
Beiträge (single.php) - Beitragsbild schiebt Content mit Hinweisboxen nach unten

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#963]
Per Zufall darüber gestolpert:

Wenn eine Hinweisbox als erstes Content-Element auf der Seite erscheint, dann drückt das Beitragsbild den Hinweis nach unten und es entsteht ungewünschter whitespace:
<img width="1771" alt="Bildschirmfoto 2022-01-13 um 16 19 24" src="https://user-images.githubusercontent.com/58593037/149359171-b4364c2f-1fa3-4572-b2a5-8d5fa3dead04.png">

Beispielseite:
https://www.urlaubaufsagrotan.test.rrze.fau.de/2022/01/13/aenderungen-an-der-pruefungsbewertung-im-sommersemester-2023/

**Comment by xwolfde** [comment]
Ja.  Das liegt am Block-Level-Element. Ggf. in RRZE Elements patchen?


Was ich aber auf dem Screenshot auch sehe: Die Kommentar-Liste in der Sidebar ist kaputt.

**Comment by xwolfde** [comment]
comment-anzeige gefixt im nächsten update
das block-level da oben ist derzeit nicht zufixen; das geschieht aber in Zusammenhang mit der Erneuerung der Beitragsdarstellung in 2.1
