### ISSUE TITLE
Textauszug auf Slider der Startseite Fakultät funktioniert nicht korrekt

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#964]
Setzt man einen Wert über 0, also 10+ dann wird der komplette Textauszug ausgegeben.
Gerade sichtbar auf unserer Beta-Seite. Dort habe ich ebenfalls mal einen Textauszug von 10 im Customizer gesetzt.

Bei Textauszug 0 verschwindet der Text allerdings wie erwartet.
<img width="886" alt="Bildschirmfoto 2022-01-13 um 16 36 33" src="https://user-images.githubusercontent.com/58593037/149361284-ce17044b-2b00-4885-b039-d4792081358f.png">

https://www.beta.wordpress.rrze.fau.de

**Comment by xwolfde** [comment]
Handelt es sich hier um ein Artikel, bei dem der Excerpt für dei Bühne angegeben wurde?
Wenn dies der Fall ist, hat dies Vorrang vor der Einstellung. Die Einstellung wirkt für Artikel die keinen Excerpt haben

**Comment by lukasniebler** [comment]
Finde ich eigentlich etwas ungünstig, wenn man den Anleser in den Beitragsoptionen setzt, dann geht man ja erstmal davon aus, dass das der Anleser für die Blogrolls ist. (Wird ja auch damit gesteuert).

Dass dann aber der komplette Text ungekürzt im Slider erscheint... Im Backend gibt es ja kein Extra-Feld für den Anleser im Slider. Man hätte also entweder einen zu kurzen Anleser für die Blogroll, oder einen zu langen Anleser im Slider, wenn man den Text individuell setzt.

<img width="1478" alt="Bildschirmfoto 2022-01-21 um 08 10 20" src="https://user-images.githubusercontent.com/58593037/150482774-77ce2914-3778-49b8-968d-fa2bd43eee78.png">

**Comment by xwolfde** [comment]
Das ist ja auch nicht der normale Excert, sondern der Anleser , der extra für die Bühne (Slider) gemacht wurde;
![grafik](https://user-images.githubusercontent.com/1070669/150488736-90b9154f-4470-4e3f-809c-f94a641c93a7.png)

Dieses Feld wird/muss ja bewusst gefüllt werden. D.h. der User weiß was er da tat.
Er kann nur so, bei einigen Sliderartikeln eine Ausnahme machen zum Default.

**Comment by lukasniebler** [comment]
Aber den klassischen Excerpt kann man dann nicht individuell setzen, ohne dass der Slider das 1:1 übernimmt und auch betroffen ist, oder?

Ich pass das in der Doku an. Von meiner Seite aus kann hier schon zu

**Comment by xwolfde** [comment]
Ja, soweit ich mich erinnere, wird der Range-Schalter auf den klassischen Excerpt und den Content (wenn kein Excerpt da ist) wirken. 
Du bist halt glaub ich auf genau die Ausnahme gekommen, wo ein Anlesertext für den Slider eingegeben wurde .)

**Comment by xwolfde** [comment]
Nochmal getestet: Funktioniert, wie gewollt: Der Customizer bezieht sich in seiner Länge auf den Content-Text für den Fall, dass man keinen eigenen Anlesertext definierte. Wenn man aber ein Anlesertext extra für die Bühne definierte, dann zählt der und hat Priorität gegenüber dem Customizer.
