### ISSUE TITLE
Hierarchie von Ansprechpartnern in der Sidebar

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#965]
Mir ist aufgefallen, dass die Kontaktkarten in der Sidebar h2 als Gewichtung haben.

Wenn man allerdings jetzt eine Überschrift darüber verwendet in der Sidebar.
z.B. "Ansprechpartner", dann haben die Ansprechpartner im Default auch h2.

Beispiel:
https://www.urlaubaufsagrotan.test.rrze.fau.de/
<img width="412" alt="Bildschirmfoto 2022-01-14 um 09 05 50" src="https://user-images.githubusercontent.com/58593037/149473331-03a36cbe-7092-4c14-b46d-d9618c5655fe.png">

**Comment by xwolfde** [comment]
Ja, ich weiß nicht, welche Lösung da die bessere wäre.
h3 zu setzen bei den Kontakten wäre zwar korrekt, aber das ist nicht der Regelfall.  

Der Regelfall ist nämlich: Dort ist kein Titel und stattdessen nur die Person mit den Namen. In dem Fall, dass dem ein Titel vorgesetzt wird und es nur eine Person ist, die gezeigt wird, wäre eine Hierachie auch nicht korrekt, da der Titel und der Name  dieselbe Ebene haben sollten.

**Comment by lukasniebler** [comment]
Also ich finde, dass man schon eine Überschrift zu den Ansprechpartner vergeben sollte. (Ansprechpartner, Kontakt, Studienberatung, Sekretariat, Schlüsseldienst...). Das können ja immer mehr Kollegen sein, die dann z.B. unter dem Punkt Studienberatung in der Sidebar gesammelt ausgegeben werden.

Bei der Standardausgabe mit format="sidebar" wird ja auch die klassische h3 verwendet.

Ansonsten macht es ja eigentlich wenig Sinn, wenn wir den Nutzern über dem Ansprechpartner die Option für einen Titel überhaupt bereitstellen.
<img width="496" alt="Bildschirmfoto 2022-01-14 um 13 19 02" src="https://user-images.githubusercontent.com/58593037/149514507-b08dd12c-c8e7-45a2-8102-e9c89eeb4c1d.png">

https://www.wordpress.rrze.fau.de/tutorials/eine-kontaktuebersicht-erstellen-und-anlegen/kontaktuebersicht-musterseite-b/

**Comment by xwolfde** [comment]
Also nochmal schauen, warum da der hstart in der Sidebar falsch ist.

**Comment by xwolfde** [comment]
fixed im Update
