### ISSUE TITLE
Logoschrift passt zum Teil nicht

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Einrichtungen#966]
Die Logoschrift passt irgendwie nicht überall. Auf einem Monitor passt sie nicht, auf einen anderen sieht sie gut aus... 
<img width="395" alt="Logo-Ansicht2-1920x1080" src="https://user-images.githubusercontent.com/9526974/149474278-606a9cdb-1549-442b-91d2-ba2771c21b99.png">
<img width="367" alt="Logo-Ansicht1-1920x1080" src="https://user-images.githubusercontent.com/9526974/149474282-a49d50d4-6ac1-4cdf-811a-1761b2c4ba4b.png">
Liegt das am Monitor oder an der Schrift? Auflösung ist überall gleich...

**Comment by xwolfde** [comment]
Es kann eigentlich weder an Monitor noch an Schrift liegen. 
Was für ein Browser wird denn da verwendet?

**Comment by xwolfde** [comment]
Sorry, auch die anderen konnten es nicht nachvollziehen mit verschiedenen Geräten und Software-Instalationen...
