### ISSUE TITLE
Featured Post - Datumspicker / Symbolbild und Co.

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#967]
Getestet in Google Chrome

# Issue
Der Datumswähler funktioniert für Top-Events seit einiger Zeit nicht mehr korrekt.
Gleichzeitig kann man zwar ein Symbolbild auswählen / Einschalten, allerdings wird dieses nicht in der Sidebar ausgegeben.

Beispielseiten:
https://www.beta.wordpress.rrze.fau.de/
https://www.urlaubaufsagrotan.test.rrze.fau.de/

<img width="1742" alt="Bildschirmfoto 2022-01-14 um 09 17 51" src="https://user-images.githubusercontent.com/58593037/149475107-0aaaf0ef-214c-494b-ba00-efd3e6f2a5c0.png">

**Comment by lukasniebler** [comment]
<img width="402" alt="Bildschirmfoto 2022-01-14 um 09 23 54" src="https://user-images.githubusercontent.com/58593037/149475345-40eb1137-5a2a-415f-9053-f2d5e739f3d3.png">
( Getestet auf Startseite & Startseite Fakultät )

**Comment by cassandre** [comment]
jQuery-ui.scss ist auskommentiert. 
Ich habe es aber auch mit dem Entfernen des Kommentars nicht zum Laufen bekommen.

**Comment by xwolfde** [comment]
Ist im Git.

Das Bild zu wechseln funktionierte bei mir jedoch...

**Comment by cassandre** [comment]
@lukasniebler Bist du sicher, dass das Bild nicht angezeigt wird? Es gibt an der Stelle wieder einen dieser verwirrenden An-/Aus-Schalter mit doppelter Verneinung: `Kein Symbolbild anzeigen: Aus` zeigt das Symbolbild an. :-/

**Comment by lukasniebler** [comment]
Inzwischen funktioniert die Ausgabe des Symbolbilds bei meiner Testinstanz. Vielleicht hab ich mich damals auch einfach verklickt?

**Comment by lukasniebler** [comment]
Aber die doppelte Verneinung ist wirklich ungünstig. Vielleicht kann man die ja rausnehmen/Text anpassen?

**Comment by xwolfde** [comment]
Also ich mag doppelte Verneinungen ja auch nicht ohne dass keine Zustimmung durch einen Widerspruch deutlich verneint wird.
