### ISSUE TITLE
Zusammenspiel der automatischen Synchronisierung von CRIS und Theme scheint Probleme zu verursachen

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#968]
s. verknüpftes Issue in CRIS:
https://github.com/RRZE-Webteam/fau-cris/issues/267

# In Kurz:
Das Logo und Seiteninhalt verschwindet nach Aktivierung der automatischen Synchronisation, nachdem verschiedene Forschungsseiten erstellt wurden.
(Mehr Details im Verknüpften Issue bei CRIS)

# Screenshot mit dem Problem
<img width="2221" alt="Bildschirmfoto 2022-01-14 um 09 36 05" src="https://user-images.githubusercontent.com/58593037/149485296-38836927-fded-4481-9b4e-7c1dbe6c5049.png">

Beispiel:
https://www.urlaubaufsagrotan.test.rrze.fau.de/forschung/betriebssysteme/softwarekontrollierte-konsistenz-und-kohaerenz-fuer-vielkernige-prozessorarchitekturen/

**Comment by xwolfde** [comment]
Strange

**Comment by cassandre** [comment]
In https://github.com/RRZE-Webteam/fau-cris/commit/e4fb129318b5969793851088b60692bbafce305d erledigt.
