### ISSUE TITLE
outside-the-box-class

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Einrichtungen#969]
https://www.beta.wordpress.rrze.fau.de/tests/testseite-mit-outside-the-box-class/
das passt noch nicht, wird aber meines Wissens nach auch nicht verwendet

**Comment by xwolfde** [comment]
stimmt, die Funktion sollte erstmal draußen bleiben. Hatte vergessen den Testcase wegzumachen. Wird erst mit V2.1 relevant, wenn wir die Artikelfunktionen anreichern wollen. 

Ich ergänze mal den Issue #910 dort.
