### ISSUE TITLE
Einstellung Menühierarchie/Ebenenanzahl bei der Bearbeitung einer Seite mit Navi ist weg

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/FAU-Einrichtungen#97]
Unterschied https://anglistik.cms.rrze.uni-erlangen.de/fields_of_study/american-studies/american-studies-literature/publications/
und 
https://anglistik.cms.rrze.uni-erlangen.de/fields_of_study/american-studies/american-studies-literature/research/
Andere Einstellung, aber nicht veränderbar, da die Einstellungen im Backend jetzt fehlen!

**Comment by xwolfde** [comment]
Das ist Absicht und gewollt. Diskussion dazu war lang und ausufernd.

**Comment by steffigebel** [comment]
Ok, aber dann müsste es einheitlich dargestellt werden

Von meinem iPhone gesendet

Am 27.07.2016 um 16:57 schrieb Wolfgang Wiese <notifications@github.com<mailto:notifications@github.com>>:


Das ist Absicht und gewollt. Diskussion dazu war lang und ausufernd.

**Comment by xwolfde** [comment]
Bereits gespeicherte alte Variablen müssen durch naviaufbau ignoriert werden

**Comment by xwolfde** [comment]
In der nächsten version werden die alten Werte nicht mehr berücksichtigt und das gewünschte Defaltverhalten genutzt. Es sei denn, es wäre Websitetype = -1 (=FAU Webauftritt)
