### ISSUE TITLE
Sidebar jetzt über die ganze Länge der Seite?

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Einrichtungen#970]
https://www.beta.wordpress.rrze.fau.de/tests/komplexe-testseite/
Die Sidebar sollte enden, wenn kein Text/Inhalt mehr kommt, und damit der Contentbereich der Seite nach der Sidebar wieder breiter werden

**Comment by xwolfde** [comment]
Ja, leider hat sich das als unpraktikabel erwiesen und führte zu Fehlern bei Blocklevel-Elementen (z.B. Gallerie, Alerts), die neben der Sidebar begannen und zu Fehlern bei der mobilen Darstellung.

Durch den größeren Platzangebot bei der großen Bildschirmdarstellung verliert der Inhalt aber wiederum kein Platz zu dem Stand von vorher. 

ggf. für Doku zu erwähnen @lukasniebler

**Comment by xwolfde** [comment]
Kann das zu bzw. in den Sammel-Issue für die Doku?

**Comment by lukasniebler** [comment]
Kann zu. Ist in anderer Form bereits in der Schnellstart-Anleitung erwähnt.
