### ISSUE TITLE
Buttonfarbe neu?

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Einrichtungen#971]
<img width="499" alt="image" src="https://user-images.githubusercontent.com/9526974/149489266-07b0f513-d589-42c0-9b11-1aaef3ded3e4.png">
Die Standardbuttonfarbe ist noch ein "altes" Blau

**Comment by xwolfde** [comment]
Gibst du bitte die URL? 
Kann  sein, dass der Button dort nicht vom THeme ist, sondern von RRZE ELements...

**Comment by wrcg** [comment]
https://www.beta.wordpress.rrze.fau.de/?page_id=2216490 sieht nach Elements aus :-)

**Comment by xwolfde** [comment]
Ahjupp. Elements

[button width="full" link="https://www.muster-lehrstuhl.wordpress.rrze.fau.de/"]Musterseite Lehrstuhl[/button]
Ich nehm es trotzdem als Enc für das Design auf, da hier die Defaultvariante aufgerufen wurde und das THeme diese überschrieben können sollte.

**Comment by xwolfde** [comment]
fixed in update
