### ISSUE TITLE
Darstellung Untertitel auf Inhaltsseiten

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#974]
Kein Bug, allerdings wär es vielleicht schöner, wenn der Untertitel wie eine H2 im Content-Bereich neben der Sidebar umklappen würde ab gewisser Bildschirmbreite. Wie immer Ansichtssache

Betrifft nur längere Untertitel auf Inhaltsseiten mit aktivierter Sidebar

https://www.urlaubaufsagrotan.test.rrze.fau.de/anleitungen/schnellstart-fau-einrichtungen/
<img width="1135" alt="Bildschirmfoto 2022-01-14 um 16 48 00" src="https://user-images.githubusercontent.com/58593037/149545426-169f5ca0-ed60-4035-b80c-01f619e690a4.png">

<img width="1135" alt="Bildschirmfoto 2022-01-14 um 16 47 54" src="https://user-images.githubusercontent.com/58593037/149545400-5aa87fb7-bc06-4e6a-b071-f4b4299f46c5.png">

**Comment by lukasniebler** [comment]
Würde es fast so lassen, wie es aktuell ist. Weiß nicht, ob das Umklappen es schöner macht. Von mir aus kann hier schon wieder zu, wenn du dem zustimmst.

**Comment by xwolfde** [comment]
Ich glaub das war damals Absicht, dass es über beide Bereiche drüber geht.

=> Alles lassen wir es so.
