### ISSUE TITLE
Kalender: Abonnement-Button und "Mehr Veranstaltungen" Button -> dunkles Blau?

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/FAU-Einrichtungen#978]
Vermutlich einfach Geschmacksache, aber mir würds besser gefallen, wenn der "Abonnement"-Button bei Kalendereinträgen im dunkleren Blau wäre (so wie das Kalenderblatt). Gerade bei kurzen Einträgen würde das glaub ich besser aussehen, oder? https://www.beta.wordpress.rrze.fau.de/events/ringvorlesung-klimaschutz-klimakrise-bedeutet-gesundheitskrise-%e2%80%93-was-koennen-wir-tun/

Das selbe gilt für den "Mehr Veranstaltungen"-Button auf der Startseite (https://www.beta.wordpress.rrze.fau.de/plugins/plugin-ili-fau-templates/)

**Comment by FlorianFiller** [comment]
Sollten die Kalenderblätter überhaupt einen Mouseover-Effekt haben, wenn sich darunter kein Link verbirgt? Sollten sie dann nicht lieber statisch sein?

**Comment by xwolfde** [comment]
Fehlerhafter Mouseover entfernt
