### ISSUE TITLE
FAU-Person Listenausgabe: Kein Mouseover bei Symbol vor Mail/Webseite

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/FAU-Einrichtungen#979]
https://www.beta.wordpress.rrze.fau.de/plugins/fau-person/format-liste/
Das Symbol vor der Mail-Adresse (Brief) bzw. der Webseite (Haus) ändert die Farbe nicht in weiß beim Mouse-Over.

**Comment by AndiWebred** [comment]
Oder es müsste dort das gleiche Mouseover geben, wie bei den restlichen FAU Person Formaten (also nur unterstrichen).

**Comment by xwolfde** [comment]
da hast du recht. wird im nächsten update gefixt sein
