### ISSUE TITLE
Anregung: In der Breadcrumb letzten Eintrag der Seite, auf der man sich gerade befindet nicht anzeigen lassen, da es unter Umständen 

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/FAU-Einrichtungen#98]
Z. B. Bei einem Terminetitel sehr lang werden kann

**Comment by xwolfde** [comment]
Nein, die Usability-Regeln sind hier eindeutig und das soll auch einheitlich für alle Sites bleiben - daher auch keine Option
