### ISSUE TITLE
Glossar: Alphabet Mouse-Over fehlerhaft?

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/FAU-Einrichtungen#980]
https://www.beta.wordpress.rrze.fau.de/theme-shortcodes/glossar/#ID-2216129
Das Mouse-Over im Alphabet scheint mir noch nicht ganz sauber zu sein. Es bleibt so ein sehr dunkler blauer Balken oben im Feld. Konkurrieren da zwei Mouseover-Effekte miteinander?

**Comment by xwolfde** [comment]
Verflixt, jemand hat es gefunden :)
ich fand den Effekt garnicht so schlecht.

im nächsten update gefixt

**Comment by AndiWebred** [comment]
ist das schon auf beta? da scheint jetzt ein neuer fehler drin zu sein. jetzt gibt es einen hellen balken unten im feld - der hat sein ganz eigenes mouse-over.

**Comment by xwolfde** [comment]
Mist, was ist da wieder reingekommen....

**Comment by xwolfde** [comment]
.fau-glossar .letters li.filled a { } bbraucht ein line-height: 2rem; und ein text-decoration: none;
.fau-glossar .letters li {} ein height: 2rem;

**Comment by xwolfde** [comment]
Update im Git
