### ISSUE TITLE
Darstellung von HTML-Definitionslisten

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#983]
Die Darstellung der HTML-Darstellungslisten könnte noch etwas verbessert werden:

<img width="1115" alt="Bildschirmfoto 2022-01-18 um 10 44 27" src="https://user-images.githubusercontent.com/58593037/149912375-62a5d6ea-ed42-49b1-81b8-b07779f84db0.png">
https://www.urlaubaufsagrotan.test.rrze.fau.de/anleitungen/schnellstart-fau-einrichtungen/eine-startseite-erstellen-und-konfigurieren/

Als Anregung:
https://css-tricks.com/utilizing-the-underused-but-semantically-awesome-definition-list/

**Comment by xwolfde** [comment]
Im Git
