### ISSUE TITLE
Bildergrößen werden z.T. nicht übernommen

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Einrichtungen#984]
Bei der Kopie des Quelltextes von https://www.fau.de/newsportal/ auf https://www.beta.wordpress.rrze.fau.de/tests/newsportal/ werden die Bilder bei den Magazinen Alexander und friedrich größenmäßig nicht korrekt dargestellt. 
Ohne die Umrahmung mit [caption id="attachment_2278520" align="alignleft" width="141"] passt es. Ich befürchte, wir haben an mehreren Stellen caption ;-(

**Comment by xwolfde** [comment]
Bitte prüfe das nochmal, aber ohne HTML Kopie, sondern durch die Einstellung und Uploads von Testbildern auf dem Testportal.

Ggf. hat der kürzliche Fix zu #986 das bereits behoben.

**Comment by wrcg** [comment]
passt, danke
