### ISSUE TITLE
Umbruch bei Bildunterschrift fehlt

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Einrichtungen#986]
<img width="799" alt="image" src="https://user-images.githubusercontent.com/9526974/150111804-b0d36029-5e22-4898-b5b3-2b9641b3510b.png">
Seite: https://www.beta.wordpress.rrze.fau.de/tests/testseite-wissenschaft-fuer-buergerinnen-und-buerger/

**Comment by xwolfde** [comment]
@cassandre Das ist ein Elements-SHortcode, oder?

**Comment by xwolfde** [comment]
Elements hat damit wenig zu tun. Liegt am CSS. Schwierig zu lösen.

**Comment by xwolfde** [comment]
Ist im nächsten Update gefixt
