### ISSUE TITLE
Abstand bei columns

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Einrichtungen#987]
![6b3bfd9f-53ca-470e-ae18-8566d7ae4f3a](https://user-images.githubusercontent.com/9526974/150114718-740bc298-0193-4d93-8a5b-b938771496a7.jpg)
![39d6dffa-f2d6-497a-a21a-e9c0194ddaff](https://user-images.githubusercontent.com/9526974/150114736-4ed13fe2-7d50-4d46-a59c-331cb31a5049.jpg)
https://www.beta.wordpress.rrze.fau.de/tests/testseite-wissenschaft-fuer-buergerinnen-und-buerger/ 
wenn die Seite jetzt so breit läuft, hätten wir mehr Platz für etwas mehr Abstand zwischen den Spalten ;-)

**Comment by xwolfde** [comment]
@cassandre Ich glaub das betrifft die Spalten-Shortcodes in Elements?

**Comment by cassandre** [comment]
Die Angabe ist eigentlich schon prozentual.
Besser wäre, auch das Padding des Alerts anzupassen.

**Comment by cassandre** [comment]
Padding habe ich angepasst. 
Der Shortcode two-columns-one etc. ist veraltet und sollte ersetzt werden durch:
```
[columns]
[column] … [/column]
[column] … [/column]
[/columns]
````
Damit passt auch der Spaltenabstand.
