### ISSUE TITLE
Leerzeichen fehlt

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Einrichtungen#989]
Leerzeichen vor "Weiterlesen" fehlt
<img width="446" alt="image" src="https://user-images.githubusercontent.com/9526974/150117622-7fbe9fe9-1cc1-460f-889b-8840295337e9.png">
https://www.beta.wordpress.rrze.fau.de/tests/newsportal/
alternativ wäre es auch möglich, dass das "Weiterlesen" immer eine neue Zeile bekommt, dann bricht das Wort nicht um...

**Comment by xwolfde** [comment]
Da ist noch mehr Kaputt: Das Weiterlesen ist nicht im Ghost-Button-Style.

**Comment by wrcg** [comment]
ja, gerne auch den anderen Weiterlesen-Button verwenden. ...und gerne auch gleich das Bild noch 
mit dem Beitrag verlinken ;-)

**Comment by xwolfde** [comment]
@cassandre Ist das Teil von dem News-Shortcode? Kannst du da das "Weiterlesen" auch entsprechend ändern?

**Comment by cassandre** [comment]
Verlinktes Bild ist erst im nächsten Elements-Update live.
