### ISSUE TITLE
Englische Seite Termine

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/FAU-Einrichtungen#99]
https://anglistik.cms.rrze.uni-erlangen.de/event/general-enrollment-for-classes-in-erlangen-begins-142/?

Hier wird in der Breadcrumb "Termine" und nicht das englische Wort gezeigt. Ein Klick darauf leitet auf eine Fehlerseite. Rolf wird das erste problem lösen, Wolfgang evtl das zweite?

**Comment by xwolfde** [comment]
Sehe da nirgends "Termine".
