### ISSUE TITLE
Lesbarkeit auf Desktop - Zeilenlänge 

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#990]
Mal wieder etwas für die Diskussionsrunde.

Beim Erstellen der Anleitungen fällt mir schon auf, dass es für mich teilweise auf großen Bildschirmen schwer ist die Texte zu lesen, vermutlich durch die Zeilenlänge

https://www.urlaubaufsagrotan.test.rrze.fau.de/anleitungen/schnellstart-fau-einrichtungen/inhalte-erstellen-fuer-anfaenger/

An den empfohlenen ±40 bis ±72-Zeichen (Quelle: 100 Things every Designer needs to know about People) schießt man als Ottonormalverbraucher deutlich dran vorbei, wenn man keine Columns verwendet.

Vllt. auch eher was für ein komplettes Redesign in weit entfernter Zukunft? 

----
Bsp.: https://www.urlaubaufsagrotan.test.rrze.fau.de/2022/01/14/studicare-report-2021-wie-die-pandemie-das-leben-der-studierenden-beeinflusst-hat/
Markierte Zeilenlänge: 72 Zeichen.
(Man kann es über die Klasse rrze-vrevision-72-characters highlighten)
<img width="1628" alt="Bildschirmfoto 2022-01-19 um 14 01 17" src="https://user-images.githubusercontent.com/58593037/150137364-1ef01566-3a60-4d81-ba96-65a7b2e9efb3.png">
<img width="1628" alt="Bildschirmfoto 2022-01-19 um 14 02 11" src="https://user-images.githubusercontent.com/58593037/150137398-95467cbc-ae3f-4be1-954b-202d95ba4dbd.png">
<img width="1628" alt="Bildschirmfoto 2022-01-19 um 14 02 19" src="https://user-images.githubusercontent.com/58593037/150137408-1a8726ea-934c-40e9-ba55-71be0311b60e.png">
<img width="1628" alt="Bildschirmfoto 2022-01-19 um 14 03 12" src="https://user-images.githubusercontent.com/58593037/150137413-6648daa7-5d52-4a67-92d6-d72d35813e2e.png">

Ein paar Beispiele von Seiten mit kürzeren Zeilenlängen und dadurch deutlich lesbareren Beiträgen:
https://xd.adobe.com/ideas/principles/web-design/proximity-in-design-principles/
https://www.apple.com/de/newsroom/2022/01/apple-welcomes-200th-german-developer-to-its-app-store-foundations-program/
https://blog.zeit.de/stufenlos/
https://uxdesign.cc/the-laws-of-simplicity-applied-to-vr-87418ec34aa4
nytimes.com
sz.de

Wie gesagt ist das meine persönliche Meinung. Deshalb werf Ichs einfach mal in die Diskussionsrunde

**Comment by xwolfde** [comment]
Die jetzige Schriftgröße und Breite ist auch schon mit der Agentur besprochen wurden. (Der Guten, nicht dem Printdesigner).
Problem ist, dass wir 3 Templates haben,  die die Inhaltsbreite einschränken können. 
Aus der Vergangenheit und der Erfahrung sehen wir dass die Form mit Navigation links und optionaler Sidebar rechts am häufigsten benutzt wurde. 
Hier allerdings soll der Inhalt nicht mehr so gedrängt erscheinen, was passieren würde wenn wir die Schriften vergrößern. 

Wenn wir die Sidebar und/oder Navigation weglassen hat der content dann mehr Platz. Und vielleicht eben zu viel. 
Aber wenn wir dann das Grid einschränken oder Weißraum an der Position der leeren Navigation oder Set sidebar lassen, sieht das ganze ebenfalls schlecht aus und stört auch beim Lesen. 

Ich denke daher, die jetzt umgesetzte Form ist daher der beste Kompromiss den wir finden konnten.
