### ISSUE TITLE
Ghostbutton-Hover

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#992]
Derzeit hat das Ghostbutton bei der Hoverfarbe die Hover-Farbe des normalen Buttons.

Bei einem normalen Button wird als Hintergrundfarbe die "dunkler"-Farbe verwenden und beim Hover die "dunkelste".
Bei dem Ghostbutton ist die normale Farbe aber transparent, bzw auf dem Standardhintergrund eben weiß.
Damit ist aber Sprung beim Hovern gleich auf die dunkelste Farne zu krass.

Normal, ohne Hover:
![grafik](https://user-images.githubusercontent.com/1070669/150335114-b0492473-0a0f-4f68-8a10-a4538c33bd36.png)

Hover bei Zentral:
![grafik](https://user-images.githubusercontent.com/1070669/150335298-9815d3d7-10c2-4981-9893-2449aef3b2da.png)

Hover bei Phil:
![grafik](https://user-images.githubusercontent.com/1070669/150335218-6522ba2e-584e-471d-897c-6bf6785eac66.png)

Die Frage wäre daher, ob man bei dem Ghostbottons als Hoverfarbe daher nicht stattdessen entweder die
"ci-hell" nimmt, wie bei den Linkhover im Textcontent oder aber die erste dunklere Farbe.

Das sähe dann entweder so aus (ci-hell):

Zentral:
![grafik](https://user-images.githubusercontent.com/1070669/150335746-f8d36917-6e89-4d45-9721-97a05cd5ea43.png)

Phil: 
![grafik](https://user-images.githubusercontent.com/1070669/150335499-8399b266-1fc1-4961-be74-ded1385dab95.png)

oder so (dunkler):

Zentral:
![grafik](https://user-images.githubusercontent.com/1070669/150335826-e67d8867-89dd-4d52-9d91-bcf5b3db5dd3.png)

Phil:
![grafik](https://user-images.githubusercontent.com/1070669/150335598-e9257ad7-1411-4400-83e5-9b2c5a399a94.png)

Am besten vor Release 2.0 klären, da die Ghostbuttons neu sind und eine Gewöhnung an etwas was man dann in 2.1 ändert ungünstig wäre.

**Comment by lukasniebler** [comment]
Ich würde die Cover-Farbe identisch zum Link-Hover setzen. So hat der Nutzer die gleiche Farbe/Interaktion sowohl bei den Buttons als auch bei den Links im Text.

(Oder zum nachlesen (UX) https://lawsofux.com/law-of-similarity/ )

**Comment by cassandre** [comment]
Ich würde es auch so lassen. Die anderen Vorschläge wären nur bunter, nicht besser. ;-)
Bootstrap invertiert seine Outline-Buttons auch: https://getbootstrap.com/docs/5.1/components/buttons/#outline-buttons

**Comment by xwolfde** [comment]
Von einer Kundenseite hab ich via Mail auch das Votum zur Variante ci-hell.

**Comment by xwolfde** [comment]
Also 4:0 für die ci-hell-Variante.

Demnächst in Ihrem Git-Repo...
